### ISSUE TITLE
Have an 'audit log' for each package

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#1018]
Something like https://help.github.com/articles/reviewing-the-audit-log-for-your-organization/

- Version X uploaded by y@example.com
- Uploader foo@ was added by bar@
- Uploader foo@ was removed by bar@
- Analysis succeeded/failed for vX.Y – link to log
- Doc generation succeeded/failed for vX.Y - link to log
- etc

Would be great for a package maintainer

Since all of the emails are public anyway, I'm not sure we'd need to put this behind a login – should discuss.

Related to https://github.com/dart-lang/pub-dartlang-dart/issues/993

**Comment by isoos** [comment]
I think we should separate two major groups here:
- Package-level messages, which are usually initiated by the user (e.g. upload, uploader maintenance)
- PackageVersion-level messages, which are usually coming from our services

The PackageVersion-level ones will be more frequent and larger in numbers, it may be reasonable to separate their display (and maybe their database representation too).

The straightforward use case is relatively simple: 1 event -> 1 database record, which we can list in reverse chronological order. However we have multiple edge cases:
- A package may be analyzed multiple times a day (e.g. several of its dependencies get an update, and we finish its analysis before the next update happens).
- A failed analysis may be retried multiple times over a week, and it may fail each time.

In such cases I think it would be better to aggregate multiple events in a single record, e.g. "We have tried to analyze `pkg` `v0.1.0` 4 times between `May 23, 2018 and May 30, 2018`, but failed".

Alternatives:
- do such aggregation at the time we are displaying the audit log (seems harder when if/when we need to do pagination)
- do such aggregation into of a separate table that gets displayed on the UI

WDYT?

**Comment by kevmoo** [comment]
I like the idea of splitting out the user actions and the auto actions
I get the point about too many actions happening at once
Aggregation sounds nice, but it seems like something we should look at later.

Are we talking about dozens of possible events for one package in a day?

**Comment by isoos** [comment]
> Are we talking about dozens of possible events for one package in a day?

I'd guesstimate it to be 1 event for each package-version per day. If we are displaying "auto" events separately for each version, it shouldn't be a problem.

We could start with immutable user-initiated events, and maybe-mutable auto-events. The aggregation can be added later.

**Comment by isoos** [comment]
Right now (in staging) we have `History` entries enabled, and storing:
- uploader invites
- uploader changes (add/remove)
- package uploads

The above can be listed through the `/api/history` API access. What do you think, what would be the best way to display it on the package page? Shall we create another tab like 'readme.md', ..., Example, Versions, ..., History?

**Comment by isoos** [comment]
Conclusion of today's discussion: it makes sense to display similar data in the soon-to-be publisher profile (for its admin users), but it doesn't add much value for a single package now. If we want to increase transparency for a single package, we should display the uploader's e-mail address for each published version.

I'm pushing this issue to the backlog, as we want to finalize the publisher-event-log design first.

**Comment by jonasfj** [comment]
I note that we might want to consider this two different features:
 A) audit log (the package level changes as @isoos puts it, notably these have to do with ownership)
 B) event log (the package version level events such as analysis completed, etc)

We should do (A) to increase security. The motivation for (B) is more about transparency..

**Comment by isoos** [comment]
We do have a new structure as `AuditLogRecord`s. Tracking the status of displaying them in #4525.
