### ISSUE TITLE
Implement SERVER tag for packages

### ISSUE THREAD

**Issue by sandrobilbeisi** [dart-lang/pub-dev#1031]
a few of us are partial to DartVM on the server
it would be useful to have a package tag classification for 'SERVER'

URL: https://pub.dartlang.org/server

currently, only the client-side 'FLUTTER' and 'WEB' tags are implemented

**Comment by sandrobilbeisi** [comment]
alternatively , use 'DartVM' as a tag name

**Comment by isoos** [comment]
Thanks for the request! This is an ongoing quest (see #858, we had a `server` tag, but it was confusing and misleading in certain cases). It is not forgotten, but we want to make sure we can get it right.

**Comment by isoos** [comment]
We've deployed a new analysis and tagging, which indicates if a package is for Dart native (a.k.a. server).
