### ISSUE TITLE
Canonical URL for "latest" page wrong?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#1182]
https://pub.dartlang.org/documentation/angular/latest/

Has a canonical URL of `https://pub.dartlang.org/documentation/angular/4.0.0+2//index.html`

1 - Extra slash is sad
2 - Doesn't feel like it aligns w/ discussion here https://github.com/dart-lang/pub-dartlang-dart/issues/1017#issuecomment-378746468

We want the canonical URL to be stable – https://pub.dartlang.org/documentation/angular/latest/ – so search engines aren't constantly linking to different pages as the content updates

**Comment by mit-mit** [comment]
cc @isoos
