### ISSUE TITLE
package pages show the full email of the uploader, with no obvious way to turn this off

### ISSUE THREAD

**Issue by aardappel** [dart-lang/pub-dev#1309]
URL: https://pub.dartlang.org/packages/flat_buffers#-analysis-tab-

I get enough spam as it is.

**Comment by isoos** [comment]
Noted. /cc @mit-mit 

I believe a similar request came up only one time last year, but otherwise the feedback was most devs don't mind it, especially since we provide a way to look up packages from the same author.

**Comment by aardappel** [comment]
Sure, whoever doesn't mind, can leave it up there. But why not provide an option for those who do?

And looking up by the same author can still be done, even the email address is internal.

**Comment by mit-mit** [comment]
Triage discussion: Let's put the email behind a 'Show email' link, and put the Google captcha on that link

**Comment by isoos** [comment]
Follow-up: we expose e-mails in the the `author(s)` property in `pubspec.yaml`. It is served via various API methods too, e.g. `/api/packages/pana`. Do we want to mask those e-mail addresses too? With those endpoints there is not much we can do for unmasking the address if we mask it while serving.

**Comment by isoos** [comment]
After the introduction of publishers, we have two ways of keeping the authoritative developers of the package:
- the list of uploader e-mails, or
- if the packages is under a publisher, the publisher itself (and its contact e-mail).

To hide your personal e-mail, the package should be moved under a publisher, and you can set a different contact e-mail to the publisher.

**Comment by aardappel** [comment]
I don't have a second contact email. This is clearly not a useful solution for most people. Why not simply add an option to hide it?
