### ISSUE TITLE
Flutter scoring should take into account native factors

### ISSUE THREAD

**Issue by lukef** [dart-lang/pub-dev#1493]
If flutter packages are not tested and compliant with "current" packages, OSes, etc then they will most likely create integration issues for the developer. This is especially more important as flutter moves to allow integration into existing native code projects. 

A few suggestions (some more important than others):
- are "key" libraries up to date (or close to). E.g. GMS/firebase/etc on Android. Maybe also popular libraries or libraries with known security right on both platforms (if that info is available).
- is the library configuration targeting a newish build environment and runtime version 
- platform level tests?
- Android and iOS specific configuration elements

I'm sure there are more so it's probably best to come up with a brief. I'm happy to help on one.

**Comment by isoos** [comment]
The now-current (new) scoring improved many parts of these suggestions, including native factors and up-to-date dependencies. Please feel free to open a new issue if you see further-improvements.
