### ISSUE TITLE
Dart 1/2 SDK constraints on a package versions tab

### ISSUE THREAD

**Issue by robbecker-wf** [dart-lang/pub-dev#1500]
# Overview
It would be pretty helpful to be able to determine more quickly which versions of a package require which version of the SDK. I'd like to see a 1 or 2 indicator on the versions tab for a package on the pub site like so:
![image](https://user-images.githubusercontent.com/6053699/43665674-38a8cbbc-972e-11e8-9167-96c1c20b155c.png)
In this way, it's easy to find the versions that are installable under dart 1, dart 2, or both.

**Comment by isoos** [comment]
As we are not analyzing packages with Dart 1 SDK, it would be misleading to put the "1" indicator there (edge case being: package is broken in all SDKs, but all we can say is that it is broken with Dart 2, we can't assume it will work with Dart 1).

Are you looking for the last package versions that is running on Dart 1 or the earliest that is running with Dart 2?

**Comment by robbecker-wf** [comment]
> Are you looking for the last package versions that is running on Dart 1 or the earliest that is running with Dart 2?
I suppose both. It would just be nice to see, at a glance, at what version a package made the transition to Dart 2. I'd settle for just including the SDK constraints on the versions tab.
Sometimes it's hard to determine why you're not getting a newer version and it turns out it's because of the SDK constraints. Or, it's sometimes helpful to know what the minimum version of a package that solves under dart 2 is to unblock a series of dependencies.

**Comment by robbecker-wf** [comment]
Thanks! I noticed the banner.

**Comment by robbecker-wf** [comment]
I think we can probably close this since the changes @isoos mentioned have addressed the issue well enough.
