### ISSUE TITLE
Consider namespacing package names

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#1503]
Currently all packages live in one, combined, global namespace. This makes it hard to see which organization maintains a certain package. Some publishers use a prefix or suffix in the package, but this is very error prone as any publishers can then 'squat' these prefixes/suffixes.

This bug tracks a request to have some sort of name-spacing of packages, so that their id is a combination of [organization name] & [package name] (e.g. `flutter.io/sensors`) rather than simply [package name].

**Comment by jonasfj** [comment]
We've recently worked over such a proposal, and the downsides are clear:
 * transfer of ownership means changing the package name in all imports.

This might be something we should accept in some future. But for now there is no need to rush it, there is plenty of good top-level names available. When these start to run dry, maybe we can reopen this discussion.

**Comment by isoos** [comment]
Maybe we could also introduce a claim mechanism: if a package name is squatted, but no development happens on it, a legit developer should be able to claim the name...

**Comment by jonasfj** [comment]
We could define a policy and process for how claim squatted package names, but we probably don't need this just yet.

**Comment by softmarshmallow** [comment]
This is required for micro package scenarios. e.g. There is a service like bit.dev and provides user to publish their package on their service using their namespace (not exactly bit, but some do that). and for this feature. i think namespaces are required. for massive package production
