### ISSUE TITLE
Rating/sentiment voting

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#1517]
Currently package scores are based on static analysis and popularity. But they don't do a great job at expressing 'utility'’; whether a given package is actually useful. 

Potential feature idea: Add an option for rating or voting up/down to attempt to capture this.

**Comment by escamoteur** [comment]
Besides Voting there also should be a way to report packages that pollute namings like 'UI' or brands 'twitter' so that they could be removed.

**Comment by escamoteur** [comment]
https://github.com/dart-lang/pub-dartlang-dart/issues/1570

**Comment by mit-mit** [comment]
Yes, it indeed looks like it is. Closing this newer issue as a duplicate.
