### ISSUE TITLE
Add support for team based permissions

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#1520]
Today permissions to upload new versions is based on adding uploaders one-by-one via the `pub` command. It would be convenient if we supported some notion of a team, potentially based on google groups or some other group concept.

**Comment by eseidelGoogle** [comment]
Just ran into this again, as we had yet another old package for which all-but-one of the publishers had left the team.  I'm not sure what the escalation path for gaining access to a package would have been if *all* of the publishers had left.  Groups potentially could have helped there.

**Comment by sortie** [comment]
@eseidelGoogle, the current escalation path is to open an issue about the package that you don't have any remaining uploaders for. I can then add new uploaders to the package.

**Comment by isoos** [comment]
This was implemented with publishers.
