### ISSUE TITLE
Add an RSS feed for each platform

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/pub-dev#1562]
Hi,

currently there is a Twitter account 'Dartocode' that informs about any published packages which is really great to stay updated, Unfortunately he cannot filter it for platforms because the RSS feed from pub doesn't allow that. 
Would it be possible to add separate feeds for Flutter / Web ?

**Comment by sigurdm** [comment]
I don't think we'll do this.

Consider doing https://pub.dev/packages?q=platform%3Awindows&sort=updated to see recent updates for a platform.
