### ISSUE TITLE
Add function to report questionable packages

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/pub-dev#1570]
There also should be a way to report packages that pollute namings like 'UI' or brands 'twitter',  so that they could be removed.

**Comment by mit-mit** [comment]
Specifically for the 'pollute' part, this seems related: https://github.com/dart-lang/pub-dartlang-dart/issues/1503

**Comment by escamoteur** [comment]
Yes I agree namespacing could be one improvement but still there is a need to moderate packages as no one prohibits the use of any name.

**Comment by mit-mit** [comment]
Marking closed, this is documented in https://pub.dev/policy
