### ISSUE TITLE
Conflicting platforms in latest pkg:test

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#1643]
URL: https://pub.dartlang.org/packages/test#-analysis-tab-

Help?
CC @grouma

**Comment by isoos** [comment]
https://github.com/dart-lang/test/blob/master/lib/src/runner/browser/post_message_channel.dart

This file imports web platforms (`dart:js_util`, `package:js`) and isolates (through `package:stream_channel`'s exported `isolate_channel.dart`). As isolates are not supported on the web, this is considered a conflict.

**Comment by grouma** [comment]
cc @jakemac53 this is likely another package that needs to use conditional imports.

**Comment by jakemac53** [comment]
dart:isolate is also a weird one... I think dartdevc and dart2js actually don't agree on support?

**Comment by isoos** [comment]
This has become obsolete after the new platform tagging.
