### ISSUE TITLE
Would like to have pub badges for Github projects

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/pub-dev#1670]
Would be nice to have some kind of badge to link to your pub page from your github.  Ideally one which shows how awesome your package is (e.g. N most used, or similar).

Just occurred to me when looking at a package on github and wanted to know how good/not it was.

This is just me adding to the brainstorming.  I expect @mit-mit is working on planned lists of improvements.

**Comment by mit-mit** [comment]
We have one already that shows the most recent version published, as shown for example here:
https://github.com/flutter/plugins

But interesting idea to also show something about quality and usage

**Comment by isoos** [comment]
Btw. that badge is not something we host ourselves. Not sure if it is important for us to do the hosting, just pointing out.

**Comment by IchordeDionysos** [comment]
@mit-mit isn’t this already implemented?
https://github.com/flutter/plugins

**Comment by mit-mit** [comment]
Yes, an external contributor created https://badges.bar (thanks @bruno-garcia !), and that seems to be working fine, so closing this.

**Comment by guidezpl** [comment]
For the lazy (myself), these are all the options available today
[shields.io](https://shields.io/category/version)
[![pub package](https://img.shields.io/pub/v/sentry.svg)](https://pub.dev/packages/sentry) 
[badges.bar](https://badges.bar)
[![likes](https://badges.bar/sentry/likes)](https://pub.dev/packages/sentry/score)
[![popularity](https://badges.bar/sentry/popularity)](https://pub.dev/packages/sentry/score)
[![pub points](https://badges.bar/sentry/pub%20points)](https://pub.dev/packages/sentry/score)
