### ISSUE TITLE
Reduce memory of search index

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#1750]
The current in-memory index is getting ever-larger, and I think it would be worth to check if something is an easy win or not:
- using bitarray indexes as the inverted index base data structure
- storing weights in reduced resolution (instead of double values, we may be able to store them as bytes?)
- maybe store parts of it on disk and use memory-mapped reads (is this possible in Dart?)

**Comment by jonasfj** [comment]
> maybe store parts of it on disk and use memory-mapped reads (is this possible in Dart?)

I would be surprised if it was...

Maybe we should explore throwing it into elasticsearch or something else.. and make it less of our problem.

**Comment by isoos** [comment]
> Maybe we should explore throwing it into elasticsearch or something else.. and make it less of our problem.

My experience with operating ElasticSearch cluster and indexing was that it is always our problem. I'm referring to mostly the index tuning, but also the various failure cases that such clusters can go out-of-sync.

**Comment by isoos** [comment]
I've did a quick experiment with the tokenization part: changing the max word length from 80 to 20 reduces the memory used by 20-25%, while changing it from 80 to 10 reduced the memory use by ~50%.

**Comment by sigurdm** [comment]
That sounds like a nice easy win.
My guess is that searches for such long words are rare.
Can we test that hypothesis from the logs?

**Comment by isoos** [comment]
Well, `geolocation` and `face recognition` are two recent searches, both have phrases longer than 10 characters, although just by 1. It is a nice plan-B if the number of packages jump a lot in a short time though...

**Comment by sigurdm** [comment]
But not longer than 20...

**Comment by sigurdm** [comment]
ByteData supports storing 32 bit floats in a packed array if you wanted to save memory on the weights.
It would require mapping document ids to integers

**Comment by isoos** [comment]
In practice we don't even need 32 bits for the weights, I think we could get away with 4 or 5 bits and still keep the current ranking.

**Comment by isoos** [comment]
I've done an experiment today using `package:bit_array` to create the inverted index. While it had a speed benefit, the memory requirement was about 3 times than the current index, and it took much more to build the index. For now I'd probably drop that line of exploration.

The next step could be to explore if the current index format could be read efficiently from a binary-file format, and then figuring out how to build it.
