### ISSUE TITLE
api docs looses "package context"

### ISSUE THREAD

**Issue by pedromorgan** [dart-lang/pub-dev#1866]
When jumping between api docs, am confused as to where i am

Viewing this package...https://pub.dartlang.org/packages/sqflite

# package "Home"

- it has the package + version no in **bold**
- and small on the right is the repos, issues + mainly API docs...
- these could be icons or alike

# api home
 https://pub.dartlang.org/documentation/sqflite/latest/

- am in the api home, but not sure as the package+version not to prominent...
- also have lost link to repos + issues which could be on top bar

# api page

https://pub.dartlang.org/documentation/sqflite/latest/sqflite/sqflite-library.html

same snag of not knowing which repos, version no, issues etc
So the scrolling is driving me nuts
and one possible solution is to make the "lib" column to the second left...
ie

package col <> lib col + classes <> api content

ref https://github.com/dart-lang/dartdoc/issues/1870
anyway.,... ;-)

**Comment by sigurdm** [comment]
Seems this was mostly fixed by https://github.com/dart-lang/dartdoc/issues/1870
