### ISSUE TITLE
Statistics about API and their documentation.

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#1901]
As port of solving https://github.com/dart-lang/pub-dartlang-dart/issues/1881, we want to understand what kind of statistical characteristic describes the classification of "self-documenting" API names. This issue will track the statistics and hopefully some conclusion.

**Comment by isoos** [comment]
First statistics from top 1000 package (by popularity):

API names:
- extracted word-like phrases: 12775
- used more than 100 times (may be used inside the same package): 534
- top values: `visit, to, json, from, get, type, on, is, name, id, value, color, set, text, state, create, code, outline, list, map, message, data, error, key, time, string, file, add, default, start, read, with,`

Documentation:
- extracted word-like phrases: 15230
- used more than 100 times: 1425
- top values: `the, a, of, to, this, is, for, in, if, and, be, that, an, or, with, not, will, by, returns, as, from, it, on, are, can, when, value, which, set, used, object, only, method, should, return, given,`

Frequent name parts that are not used that much in documentation: `variant, light, crypto, actor, solid, currency, dark, uuid, minus, join, bold, star, zoom, align, square, lock, alt, bluetooth, white, strength, ago, interpolation, country, drop, thumb, medium`

**Comment by isoos** [comment]
Frequent words that are co-located within both the name and its documentation: `name, is, type, code, state, to, hash, create, value, list, id, time, get, text, on, from, build, error, string, message, set, request, response, key, token, file, color, element, json, page, add, size, data, with, of, url, length, path, date, next, location, stream, map, uri, in, source, client, default, instance, content, offset, event, status, user, start, service, all, version, query, update,`

Words that are usually in the name only: `get, on, to, is, set, from, add, create, max, with, id, update, kind, count, start, name, remove, type, write, read, has, min, ng, load, close, visit, end, builder, google, cloud, length, change, dialogflow, config, apply, register, value, delete,`

Words that are usually in the documentation only: `the, a, of, to, this, is, for, in, if, and, be, that, an, or, with, not, will, by, returns, as, it, from, are, on, can, when, which, used, object, value, only, set, method, given, should, return, use, all, see, example, at, list, must, true, https, new, may, null, default, have, has, same, type, instance, data, class, string, error,`

Words that are unique to the documentation: `the, whether, also, there, creates, instead, implementation, represents, associated, either, they, about, their, your, well, otherwise, 24px, newly, provides, according, gets, calling, implement, represent, typically, overridden, consistent, it s, again, further, indicates, might,`

**Comment by jonasfj** [comment]
I'm thinking that analyzing the text isn't going to get us far. And that we should instead look at the structure.
Notably, do if we have 5 or more of the same thing (same signature but different name), we could ignore lacking docs...

However, given the complexity of all this, it seems like something that is likely to be surprising. And @sigurdm makes a good argument that leaving a comment or a comment disabling the lint is easy.

So I'm leaning towards suggesting that we **won't fix** this. We have bigger fish to fry, and it's not obvious that this is going to yield a good result. And we already mitigated with a non-linear scoring, so the penalty is small.
