### ISSUE TITLE
Provide ability to search for non-GUI -centric packages

### ISSUE THREAD

**Issue by bradyt** [dart-lang/pub-dev#1991]
URL: https://pub.dartlang.org/packages

I would like to search for cli's, or other non-GUI packages, in pub, and a reasonable way would seem to be to filter out flutter and web, but those seem to be the only buttons available.

Is there an existing trick, like maybe in the url arguments, to view packages that are not for flutter or web?

(Goal: trying to get some minimal, non- resource intensive, interface going for an app, to get things working, before I shift to learning about writing the GUI part.)

**Comment by bradyt** [comment]
Ah, search terms like `dependency:build_version` help in my goal. (Search term was a link at package description, https://pub.dartlang.org/packages/build_version.)

**Comment by jonasfj** [comment]
Hmm, maybe we should support negated terms like `-flutter`

**Comment by isoos** [comment]
In that case we should move the platform selection into the query itself, e.g. `+flutter`, `flutter`, or rather `platform:flutter` would become part of the query when somebody switches from "all packages" to "Flutter packages".

With that, we could also have `-platform:flutter -platform:web` or `platform:other` to match the above request.

`package:query` has support for query parsing, but it still some work required on the pub site.

**Comment by isoos** [comment]
This needs to be separated into two scopes:
- one part is whether we want to put everything into the query text (can be a gradual change)
- the other part is whether we want to have hierarchical query support (probably a single, larger change)

@mit-mit what do you think about moving the search filters into the query string?

**Comment by mit-mit** [comment]
I like the suggestion in https://github.com/dart-lang/pub-dartlang-dart/issues/1991#issuecomment-458856526, but I'm not sure I'd use the term 'platform'. I think we are going to need that for things like expressing that a plugin supports the Android platform. How about 'framework'? Or something more general like 'type'?

**Comment by isoos** [comment]
I think platform can be hierarchical and non-exclusive, e.g. `platform:flutter` would list all the Flutter packages, while (when we can classify it) `platform:android` could identify the Android-only ones.

**Comment by mit-mit** [comment]
I don't think those are the same kind of 'platform'. 'android' is a subcategory of 'flutter'.

**Comment by isoos** [comment]
Closing this, as such packages can be searched for via https://pub.dev/dart/packages?runtime=native-jit
