### ISSUE TITLE
README inside example has broken link on pub website

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [dart-lang/pub-dev#2018]
Hello,

My project structure looks as follows:
```
| my_library
| pubspec.yaml
| README.md
| example -->
        README.md
        pubspec.yaml
        ...
```

The README in the example shows in correctly in the example tab, but the problem is that it has a link that looks like this:
```
[lib/main.dart](./lib/main.dart)
```
This is supposed to refer to `example/lib/main.dart` because the README is inside the example directory. However, it is referring to `lib/main.dart` on the pub website.

Please note that the link works correctly on GitHub.

Here is a link to my package for testing:
https://pub.dartlang.org/packages/flutter_pagewise/#-example-tab-

Thank you!

**Comment by isoos** [comment]
good catch, thanks for reporting!
