### ISSUE TITLE
Don't generate API docs for packages without APIs

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#2047]
Examples:
- https://pub.dartlang.org/packages/devtools
- https://pub.dartlang.org/packages/peanut

**Comment by kevmoo** [comment]
See also https://github.com/dart-lang/pana/issues/510

**Comment by isoos** [comment]
I understand the penalize part, but what's wrong with the packages you have mentioned here?

**Comment by kevmoo** [comment]
There are no APIs!

**Comment by isoos** [comment]
Are you suggesting that we should hide the "API reference" link on the package page? Otherwise I see very little harm generating and serving the /documentation/.../latest/index.html for such packages.

**Comment by kevmoo** [comment]
> Are you suggesting that we should hide the "API reference" link on the package page? Otherwise I see very little harm generating and serving the /documentation/.../latest/index.html for such packages.

Sure! No point in generating, hosting, and linking to a superfluous page, right?

**Comment by sigurdm** [comment]
I think it is hard to detect up-front that there is no API.

We could detect that there is no API, and not link to it (perhaps not expose it)

But it is unclear how much we would benefit from this change. Perhaps it would be confusing to some that there is no link (did it not get generated, or does it not contain public API??)

Closing for now as WONTFIX
