### ISSUE TITLE
Report errors to stackdriver error correlation service

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2086]
See: https://cloud.google.com/error-reporting/docs/quickstart

We have API for this:
https://pub.dartlang.org/documentation/googleapis_beta/latest/googleapis_beta.clouderrorreporting.v1beta1/ProjectsEventsResourceApi/report.html

We just need to:
A) build utilities to format the stack traces correctly,
B) intercept unhandled global exceptions and report them before we crash,
C) intercept unhandled exceptions we're currently logging and ignoring.

Some of this might involve some grunt work in the appengine package.

**Comment by jonasfj** [comment]
Let's format the error message in the error logs:
https://cloud.google.com/error-reporting/docs/formatting-error-messages

**Comment by isoos** [comment]
At the moment we catch request-related exceptions here: https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/shared/handler_helpers.dart#L47

**Comment by jonasfj** [comment]
We started this a long time ago :D
