### ISSUE TITLE
When redirecting to blob we're not encoding the URL

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2093]
This might be a bug we can't fix... Or it might not be a bug at all...

If you list versions available for a package, for example: https://pub.dartlang.org/api/packages/google_sign_in

It contains:
```json
"archive_url":"https://pub.dartlang.org/packages/google_sign_in/versions/4.0.1%2B1.tar.gz"
```
Which is correct...

If you fetch that URL we're redirected to:
```console
curl -v https://pub.dartlang.org/packages/google_sign_in/versions/4.0.1%2B1.tar.gz
...
< HTTP/2 303 
< location: https://storage.googleapis.com/pub-packages/packages/google_sign_in-4.0.1+1.tar.gz
```
Which is not encoded... this **might** be a mistake... I'm not 100% sure...

Note: fixing this might not be possible, as it's probably stored this way in GCS... And if GCS didn't decode the `+` into a space then maybe we can just start to encode it... If GCS does do percent decoding.

Credits @chenglu for sending me down this rabbit hole with https://github.com/dart-lang/pub/issues/2082

**Comment by isoos** [comment]
It seems that CSD is able to resolve the encoded URLs:
```
curl -v https://storage.googleapis.com/pub-packages/packages/google_sign_in-4.0.1%2B1.tar.gz >/dev/null
```

**Comment by jonasfj** [comment]
I checked up on the logs from over the weekend and concluded that this is the issue.
