### ISSUE TITLE
allow package retraction within 48 hours

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2103]
We generally don't allow packages to be deleted. But maybe we should allow packages to be deleted within 7 days, or some other number... And let people manage through a web UI.

We get quite a few requests to have packages deleted, for things that people published by accident :)
Usually, they notice really fast that they accidentally published version 1.0.0 too fast or something and they just want to undo.

Allowing deletion of packages in general, creates the `leftpad` problem, where someone deletes their packages and others who depend on them can't download the packages anymore. But allowing packages to be retracted within 7 days or so, would not create problems of massive eco-system wide scale.

**Comment by sigurdm** [comment]
Another solution would be to have a "staging" state of each package:
The uploader/publisher can see the package, analysis, dartdoc etc, but it is not  advertised from search and not included in package listings.
While it is in staging it can still be deleted
Then a button in the ui/waiting 24 hours will promote it to fully published.

**Comment by jonasfj** [comment]
note: I think this is more of an open question, than a specific proposal :)

**Comment by mit-mit** [comment]
I don't think we can do this in a a window as long as 7 days; that might be very breaking. Maybe 1 hour is tolerable?

**Comment by miyoyo** [comment]
1 Hour is way too short for someone that might be experimenting, I don't think going below 12h would leave enough time for someone that's experimenting to "clean up" after themselves

**Comment by jonasfj** [comment]
Policy is 48 hours, whether or not we should have an automatic button is a good question.

**Comment by isoos** [comment]
This has been implemented.
