### ISSUE TITLE
dartdoc includes core libraries for some packages

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2108]
See: https://pub.dartlang.org/documentation/shared_preferences/latest/dart-core/dart-core-library.html

This means that uploading dartdoc takes forever... We really should avoid this..

In fact this probably explains why it took me an hour to delete a package..

**Comment by jonasfj** [comment]
@isoos, filed #2109 which is a good temporary fix... but we should fine the underlying issue, or at-least report it to `dartdoc`.

**Comment by isoos** [comment]
I've identified some differences. Regular package + Dart SDK yields parsing the libraries inside the SDK's lib library:

```
STDOUT:
parsing /tmp/pub-dartlang-dartdocIZDTBG/pkg/lib/models.dart...
parsing /tmp/pub-dartlang-dartdocIZDTBG/pkg/lib/pana.dart...
parsing /dart-sdk/lib/core/core.dart...
parsing /dart-sdk/lib/collection/collection.dart...
parsing /dart-sdk/lib/internal/internal.dart...
parsing /dart-sdk/lib/async/async.dart...
parsing /dart-sdk/lib/convert/convert.dart...
parsing /dart-sdk/lib/typed_data/typed_data.dart...
parsing /dart-sdk/lib/math/math.dart...
parsing /tmp/pub-dartlang-dartdocIZDTBG/pkg/lib/src/model.dart...
```

While with a Flutter package, the `bin/cache/dart-sdk/lib` is not used, instead `dartdoc` uses the `bin/cache/pkg/sky_engine/` directory:

```
STDOUT:
parsing /tmp/pub-dartlang-dartdocNKAEGT/pkg/lib/shared_preferences.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/collection/collection.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/developer/developer.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/internal/internal.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/io/io.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/async/async.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/convert/convert.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/typed_data/typed_data.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/_empty.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/math/math.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/core/core.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/_http/http.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/ui/ui.dart...
parsing /flutter/packages/flutter/lib/services.dart...
parsing /flutter/packages/flutter/lib/src/services/asset_bundle.dart...
parsing /flutter/packages/flutter/lib/foundation.dart...
parsing /tmp/pub-cache-dirWUJLES/hosted/pub.dartlang.org/meta-1.1.6/lib/meta.dart...
```

In the second case I was running our dartdoc with `--sdk-dir` pointing to the `bin/cache/dart-sdk` inside Flutter.

@jcollins-g: could you please highlight why that could happen and maybe how we can fix that?

**Comment by jcollins-g** [comment]
The main reason this happens is that Flutter is using a customized version of the Dart SDK.  Dartdoc tries to detect the Dart SDK and handle it specially so it is never included in an ordinary package's documentation.  Something about what Flutter is doing is clearly breaking that detection and sadly I've just never been able to circle around and debug this.

A good place to start looking is PackageMeta, specifically the methods/constructors `fromDir`, `_sdkDirParent`, and `sdkType`.  Some breakpoints there during initialization of Dartdoc on a flutter plugin should be illustrative.
