### ISSUE TITLE
Display a related list of packages

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#211]
We could detect it from:
- the name, or
- the author, or
- the dependencies,
- pubspec entry

**Comment by orestesgaolin** [comment]
Would love to have a way to reference similar packages by its name in the pubspec or website GUI. This could also be detected from the tags/keywords #368

**Comment by mit-mit** [comment]
Closing as a duplicate of https://github.com/dart-lang/pub-dev/issues/5219. Please vote on that one instead.
