### ISSUE TITLE
docs for flutter packages doesn't have links to api.dartlang.org

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2117]
https://pub.dartlang.org/documentation/image_picker/latest/image_picker/ImagePicker-class.html

This is after we filter libraries such as `dart:*`.

**Comment by jcollins-g** [comment]
Unfortunately this is a side effect of the workaround for dart-lang/dartdoc#2108.  If you fix that and remove the workaround, Dartdoc should again be able to tie this all together.

**Comment by mit-mit** [comment]
Assigning to @jcollins-g as this is blocked on a dartdoc issue
