### ISSUE TITLE
Google Search Console: Submitted URL seems to be a Soft 404

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2177]
[See more](https://support.google.com/webmasters/answer/7440203#submitted_soft_404)

**URL**: `https://pub.dartlang.org/documentation/shared_prefs_resource/latest/`

**Comment by isoos** [comment]
Not sure how google classifies this one as a soft-404... maybe the strikethrough of the title? Or maybe it was an older version like https://pub.dartlang.org/packages/shared_prefs_resource/versions/0.0.1 ?

**Comment by isoos** [comment]
This seems to be no longer relevant.
