### ISSUE TITLE
Google Search Console: Submitted URL marked ‘noindex’

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2178]
[See more](https://support.google.com/webmasters/answer/7440203#submitted_but_noindex)

**URL**: `https://pub.dartlang.org/documentation/flutter_bloc_inject/latest/`

**Comment by isoos** [comment]
This one is strange, I don't see that the content is marked as `noindex`.

**Comment by isoos** [comment]
I think at that point the sitemap contained packages that were marked as `noindex` (because they were created only recently). This doesn't happen anymore, and sitemap uses the same flag as the `noindex` tag.
