### ISSUE TITLE
Google Search Console: Submitted URL not found (404)

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2179]
[See more](https://support.google.com/webmasters/answer/7440203#submitted_404)

**URL**: `https://pub.dartlang.org/documentation/swg_config_ui_angular/latest/`

**Comment by isoos** [comment]
To fix this, we'll need to remove the packages from the sitemap that have no documentation (or at minimum the ones that are legacy).

**Comment by jonasfj** [comment]
I'm not saying we're in a rush... this is really a nit to fix :)

**Comment by isoos** [comment]
I think this is no longer relevant.
