### ISSUE TITLE
Give users a hint if you redirect on an unfound package

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#2181]
Go to https://pub.dartlang.org/packages/not_a_package
Redirect to https://pub.dartlang.org/packages?q=not_a_package

No hint that I was redirected – maybe redirect to

https://pub.dartlang.org/packages?q=not_a_package&prompt=bad_package_name or similar and show a message that the package in question doesn't exist

...I don't like unexpected redirect behavior :-)

**Comment by isoos** [comment]
Redirect no longer happens, we 404 instead.

**Comment by kevmoo** [comment]
Better!
