### ISSUE TITLE
filter http:// images from rendered markdown to avoid mixed-content

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2202]
Security scanners (and browsers) will report mixed-content warnings if we have `http://` images. We should remove the images, we already reduce package score in pana if readme contains http images...

**Comment by jonasfj** [comment]
This is technically a bug, because our CSP policy forbids the images from loading, but the HTML we generate actually contains the image tags..

**Comment by isoos** [comment]
We could auto-upgrade `http` to `https`. It wouldn't really worsen the current state, because we are not loading the content on `http`, and if `https` is missing we wouldn't load them either. There is a distinct possibility that different content is served, but I think that is the edge case.

**Comment by jonasfj** [comment]
There is something nice about not messing with other people's content :)

But yeah, in most cases it would probably be fine..

**Comment by kevmoo** [comment]
...just make sure to be clear in the "score" tab that we're doing the upgrade

**Comment by sigurdm** [comment]
We do mention this in the scoring report, and give fewer points. So I think there is a path for package authors to find and fix the issue.

Given that the CSP policy blocks the images we don't have a security issue.

If we filtered the images completely there would be no visual indication that something is missing, making the issue harder to notice and fix.

I vote for a WONTFIX.
