### ISSUE TITLE
display license file for packages where we can't link

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2226]
For packages where we can't detect the license, we should consider showing something scary like.
```
License:
**Custom** (LICENSE)
```
And in cases where we can't link to the license file on github, it's probably better to simply have a "license" tab for hosting the license...

In fact, we could display the license from the package on `https://pub.dartlang.org/packages/<package>/license` and just link to that in the `(LICENSE)` link..

IMO, it's important that we highlight bad licenses, and that we refer to the exact license file the package was published with. Just rendering as a `<pre>` sounds reasonable to me..

-----
This was previously discussed in #201, but I just noticed some packages with very obscure licenses and this was not obvious from looking at the package page.

**Comment by jonasfj** [comment]
@mit-mit, any concerns?

**Comment by mit-mit** [comment]
What's an example of a package with an obscure license? Just want to take a look at how we currently show it.

**Comment by jonasfj** [comment]
I'll forward an email with an example to you..

**Comment by isoos** [comment]
This has been implemented.
