### ISSUE TITLE
refactor validation of uploaded packages

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2227]
We should refactor validation of packages when they are uploaded, such that we don't allow packages that the `pub` CLI client wouldn't allow to be published...

For example the `pub` CLI client requires there to be a LICENSE file... we should also require this.

Ideally, we refactor the code such that the same checks can be used both in the CLI and on the server... These should not include static analysis... this should be light weight package checks.

Note. even if we share this code, not all the of the checks should be shared. Checks that are enforced on the client cannot be loosen again, so we should be careful about apply new checks there.

However, if we add too many checks on the server, we can easily revert those checks.

**Comment by sigurdm** [comment]
Another example:

I tried to upload a package with a dependency_override and got this message:
```
Missing requirements:
* Your pubspec.yaml must not override non-dev dependencies.
  This ensures you test your package against the same versions of its dependencies
  that users will have when they use it.
Sorry, your package is missing a requirement and can't be published yet.
```
I believe we don't enforce this on the server - but we should.

**Comment by isoos** [comment]
On a cursory scan of the problem space, I think we will depend on such shared package from both `pub` client, `pub` server, and possibly `pana` too (e.g. for the full definition of filename patterns, maybe even extracting the content of them)... While the current pub server checks throw an exception right away when they encounter an issue, pub client and pana would continue scanning the archive and work on the entire report.

I think the best way to get this started is to create a new package somewhere with a minimal skeleton, and start porting features to it (e.g. filename candidates and content extraction). Any preference where it should live?

**Comment by jonasfj** [comment]
> Any preference where it should live?

We can just stick it in `pkg/` for now... ideally, we'll adopt it server-side before we adopt it client-side, as the server is more flexible (ie. we can always rollback a mistake). I agree, we should have a separate repo for it in the long run.

**Comment by sigurdm** [comment]
I don't think the server and client checks are the same in general.
Client checks are more general, and can be ignored.
server checks are fundamental.

I don't see that we save much by sharing the code.
