### ISSUE TITLE
Markdown inline HTML is not rendered: <a> <img /> </a> 

### ISSUE THREAD

**Issue by bjbrogan** [dart-lang/pub-dev#2229]
URL: https://pub.dartlang.org/packages/tree_view

Trivial HTML error.  Incorrectly formatted link to sample page: a missing "<" character in page source HTML causes improper rendering of sample link at bottom of page.

**Comment by isoos** [comment]
This is not a missing "<", rather our strict markup handling: we block most inline HTML markup, and the readme contains the following:

````
<a href="https://imgur.com/d4n4p1b"><img src="https://i.imgur.com/d4n4p1b.gif" title="source: imgur.com" /></a>
````

**Comment by jonasfj** [comment]
We probably do want to improve this... and we might have to tools with the `html_sanitizer`.

**Comment by jonasfj** [comment]
IMO, it would be nice if our markdown rendering was reasonably aligned github...

**Comment by isoos** [comment]
It looks like we've deployed a fix for this a few weeks ago.
