### ISSUE TITLE
Apply referrer-policy

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2235]
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

See security header scan:
https://securityheaders.com/?q=https%3A%2F%2Fpub.dartlang.org

**Comment by jonasfj** [comment]
We might want to allow `refrerrer` headers... as it allows people who look at traffic on their own website to determine where it came from. Which can be a feature.

**Comment by jonasfj** [comment]
I propose `Referrer-Policy: origin` that way you can still see that you get traffic from `pub.dev`, but you can't see the specific page.

**Comment by isoos** [comment]
Consent pages have `no-referrer` policy since #3493, while the rest gets `no-referrer-when-downgrade`. I think we don't have any other non-public page that is exposed to users than the currently logged in, so I think this can be closed.
