### ISSUE TITLE
Syntax highlighting broken when mixing quotes

### ISSUE THREAD

**Issue by srawlins** [dart-lang/pub-dev#2256]
Check this documentation page at pub.dartlang.org:

https://pub.dartlang.org/documentation/source_span/latest/source_span/SourceSpanWithContext/SourceSpanWithContext.html

The line, `'The context line "$context" must contain "$text".');` starts out highlighting as a String, and then seems to keep that highlighting until the end of the code snippet, with brief un-highlighting, as in interpolation or something...

I suspect this is a bug that occurs when mixing `'` and `"`, but it could be because of the interpolation as well... I'm not sure.

I'm not sure what syntax highlighting code we're using, but even if we file a bug against said code, I think we should track the bug's presence at pub.dartlang.org here.

**Comment by kevmoo** [comment]
It's `highlight-js` – there are other issues here, too.

Need to find someone who wants to dig in to the Dart impl there.

**Comment by POWRFULCOW89** [comment]
Looks like this is fixed as per [PR #1946](https://github.com/highlightjs/highlight.js/pull/1946).

**Comment by sigurdm** [comment]
Yes, this seems to be fixed!
