### ISSUE TITLE
detect Dart sources that we can't parse 

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#2259]
- [ ] report it as a single issue on the package page
- [ ] don't flood the logs with issues around such packages

**Comment by jonasfj** [comment]
Flooding the logs is a problem because:
A) it hide real issues in a sea of log messages,
B) it causes us to be casual about the presence of warnings and errors in the logs, which ideally we shouldn't happen unless there is something we should consider.

**Comment by isoos** [comment]
I think this is no longer relevant with the new report summaries.
