### ISSUE TITLE
pub.dev clips search bar in WebView

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/pub-dev#2263]
URL: https://pub.dev/

Screenshot is from within TweetDeck, which I presume uses either UIWebView or SFSafariViewController.

![image](https://user-images.githubusercontent.com/11857803/57258927-bb8fda80-7012-11e9-801b-2c33379c597e.png)

**Comment by enyo** [comment]
Same issue on plain Safari Desktop/Mobile:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/133277/57440089-a5b72b00-7247-11e9-85f5-7ea76dc75679.png">

It's the first thing a user sees, and it doesn't look good.
