### ISSUE TITLE
Convenient "Copy" for package code snippets

### ISSUE THREAD

**Issue by BrianRichardson** [dart-lang/pub-dev#2274]
It would really be handy to have a convenient "Copy" snippet button next to code snippets on appropriate sections of packages, for example, on the Installing tab.  Without this, you are required to drag over code snippets and copy.

**Comment by jonasfj** [comment]
Yeah, this would be nice to have :)

**Comment by deepak-digimogo** [comment]
I was going to just request this and saw your request.  This would be convenient as a feature.

**Comment by jayoung-lee** [comment]
This feature is added via https://github.com/dart-lang/pub-dev/pull/4412 :)
