### ISSUE TITLE
Confusing upload error

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub-dev#2281]
The only uploader listed for [the `sass_migrator` package](https://pub.dev/packages/sass_migrator) is `sass.bot.beep.boop@gmail.com`, but when that user tries to upload a new version, it gets an error message:

> ```
> Uploading...
> UnauthorizedAccess: Unauthorized user: sass.bot.beep.boop@gmail.com is not allowed to upload versions to package sass_migrator..
> Script failed with status 1
> ```

See [this Travis log](https://travis-ci.com/sass/migrator/jobs/200567426) for an example of this happening (click on "Deploying application" for the pub log).

**Comment by mit-mit** [comment]
cc @jonasfj

**Comment by isoos** [comment]
It looks like that the user was authenticated properly, but the resolved userId didn't match the approved uploader userids on the `Package` object.

[The upload history](https://pub.dartlang.org/api/history?package=sass_migrator&version=1.0.0-alpha.1) says the uploaderId was `bb60b590-e00d-4240-8ffe-cf675913e454`, while the log message says a different userId:
```
2019-05-16 03:06:01.844 CEST
pub.cloud_repository: User 8e4b508f-851f-467d-aa95-e8f94704adb7 (sass.bot.beep.boop@gmail.com) is not an uploader for package sass_migrator, rolling transaction back.
```

Staging has a user `8e4b508f-851f-467d-aa95-e8f94704adb7` with the single consistent `OAuthUserID` entry, I don't see issues there, but `sass_migrator` is a new package and it is not in staging yet.

@nex3:
- Was the upload (or the pub authentication) done with an aliased Google account?
- Was there anything special with the account done in the past few months?
- I see that it is also an uploader for sass, was it working properly?

@jonasfj:
- Could you run the integrity check?
- Could you check the `uploaders` field on the `Package` object for `sass_migrator`?

**Comment by nex3** [comment]
> * Was the upload (or the pub authentication) done with an aliased Google account?

I'm not sure what this means.

> * Was there anything special with the account done in the past few months?

I don't think so...

> * I see that it is also an uploader for sass, was it working properly?

We haven't tried to release a new version of `sass` recently, so I'm not sure.

**Comment by isoos** [comment]
>> Was the upload (or the pub authentication) done with an aliased Google account?
> I'm not sure what this means.

When you've done the pub authorization, was it on the `sass.bot.beep.boop@gmail.com` account, or was it on a different account that has the email linked to it? (Not sure if it is possible to get authorized that way, but it may be.)

Btw. I've cleared my `credentials.json` and re-authorized, looks like I'm still able to add/remove uploaders, or upload a new version for a previous package I have.

**Comment by nex3** [comment]
It was on that account. I used the exact same `credentials.json` file to upload the first version as I used to upload later versions, and that I had been using for ages to upload `sass` versions.

**Comment by jonasfj** [comment]
The credentials files in question should now stop working... We need an extra scope that has become implicit since this credentials file was created.. So recreate the credentials file and things should be fine.

We deployed a fix that will 401 the old credentials file... For more background see the postmortem you were CC'ed on.
