### ISSUE TITLE
Delete version request

### ISSUE THREAD

**Issue by CaiJingLong** [dart-lang/pub-dev#2293]
Please delete version 0.5.0 for me.

package url: https://pub.dev/packages/flutter_image_compress

Due to the use of a flutter 1.5.9 constraint, it now shows that SDK is incompatible, so please delete this 0.5.0 version for me for the time being. 

At present, the package is incompatible and the score is much lower.

You can see the details in #2290.

**Comment by jonasfj** [comment]
uh, I think our maintenance scripts have problems deleting the latest version.

I would suggest override it by just publishing a newer version... If it's just changing constraints or other packaging details you can publish as `0.5.0+1`.

**Comment by CaiJingLong** [comment]
The main reason is that there is a disruptive change in flutter SDK that results in incompatibility, so I upgraded the middle version number. 

If I upload a new version of 0.4.1, is the latest version 0.5.0 or 0.4.1?

**Comment by isoos** [comment]
> If I upload a new version of 0.4.1, is the latest version 0.5.0 or 0.4.1?

0.5.0 will be the latest

**Comment by CaiJingLong** [comment]
I uploaded a new version to solve this problem and close issue.
