### ISSUE TITLE
update email sender to @pub.dev

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#2300]
Also the name of the sender should be 'pub.dev'

**Comment by isoos** [comment]
Is this to change `pub@dartlang.org` to `pub@pub.dev`? Can you please verify that the smtp credentials allow us to send it with that new sender?

**Comment by jonasfj** [comment]
This is a bug to setup gsuite on the domain, we can talk about assigning it to @mit-mit when he is around.

Maybe we can send from `_@pub.dev` :)

**Comment by isoos** [comment]
It was done, sending emails with `noreply@pub.dev`.
