### ISSUE TITLE
Example tab is not beginner friendly

### ISSUE THREAD

**Issue by vincevargadev** [dart-lang/pub-dev#2305]
I find the example code very useful in the Dart ecosystem. I know that for most plugins,

* I can check the repo, navigate to the `example` folder and check what's in there
* I can just clone/download the repo and run the example app to figure out how things work.

If a new user is checking Dart Pub's Example tab, the rendered HTML for most packages is pretty useless in finding the actual code examples.

The user needs to know that there's a "Repository (GitHub)" link on the side and that the example can be looked up in the repository's `example` folder (in simple cases where one repo => one package).

In my opinion, this user interface should be improved. One quick-win solution could be just a link to the repo's `example` folder (of course, I don't mind finding an even better solution)

## Example packages with "almost useless" example tabs on Pub

* [`shared_preferences`](https://pub.dev/packages/shared_preferences#-example-tab-)
* [`url_launcher`](https://pub.dev/packages/url_launcher#-example-tab-)
* [`uni_links`](https://pub.dev/packages/uni_links#-example-tab-)
* ... and many more

These are all very popular packages and every package has examples. As a new user, however, just by checking the pub.dev website, I cannot really tell that there are actually good examples for these packages. I cannot click on anything, no links to the actual source code.

**Comment by jonasfj** [comment]
I'm not exactly sure  how, but I agree we should offer a code browser for all the files in the example folder, or something like that.

**Comment by vargavince91** [comment]
Thanks for the quick feedback. Yes, that would be awesome. Though a complete "code browser within Dart Pub's Example tab" solution sounds like a major undertaking.

Just an idea: Maybe as a first iteration, place a link to the repository's `example` folder after the rendered `README.md` (I'm not 100% it's that simple, but sounds easier than the code browser). I don't know how it would work for repository's with multiple packages (e.g. [`flutter/plugins`](https://github.com/flutter/plugins)) and repositories that are not on GitHub (GitLab, BitBucket, whatever)

For example, in `uni_links` package's case, we could link to [`https://github.com/avioli/uni_links/tree/master/example`](https://github.com/avioli/uni_links/tree/master/example)

**Comment by jonasfj** [comment]
Yeah, the problem is repositories with multiple packages...

It might be easier to file PRs for these packages to add absolute links in the `example/README.md` file instead...

If we just fix the top 10 packages that'll go far :)

**Comment by isoos** [comment]
> It might be easier to file PRs for these packages to add absolute links in the example/README.md file instead...

We have #2018 for fixing relative links in the `example/readme.md`. It is not that hard but we haven't had the priority for it yet.

**Comment by isoos** [comment]
We could also link to the example folder on GitHub... E.g. the first line (`example/README.md`) could link to the folder.

**Comment by sigurdm** [comment]
We have improved this, and link to the file on github.

When/if we do source listings on pub.dev, that link could point there instead.
