### ISSUE TITLE
Review of the /doc/ redirect rules

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#2313]
We have a few redirect rules that we have kept for a while, but most of them stopped working with the dart.dev site redesign and content refactoring. They still go to dart.dev, but the content is not there:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/frontend/handlers/redirects.dart#L59-L95

@mit-mit: can we drop the support of these redirects?

I think we had moved the `pub` command documentation to the dart site for over two years ago. We still receive traffic on e.g. `/doc` or `/doc/` URLs (<10 requests a day), but I think we don't have any on e.g. `/doc/getting-started.html`, which indicates that the `/doc/` request may be a typo or a random guess.

/cc @jonasfj @sigurdm

**Comment by jonasfj** [comment]
Maybe we can redirect the broken links to something else that makes sense?

Note. I propose that we rewrite this logic to also embed hostname in the mapping, so that these redirects don't have effect on pub.dev which is a completely new domain.

**Comment by isoos** [comment]
It would be nice to see the hostname in the logs, but unfortunately they are absent... if the hostname is on pub.dev, we could just drop them all...

**Comment by isoos** [comment]
Discussed offline.
