### ISSUE TITLE
example/ directory upload semantics

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/pub-dev#2323]
Recently, I was trying to publish a package with a large-ish flutter app in the example/ directory (~9mb). Pub displayed a message saying the example/ directory was too large. Publishing is working now but I don't think I changed anything in the project. I was able to work around by just deleting it and bringing it back after the publish but this is not the best DX :).

What are the rules around publishing projects with an example/ directory? Is there a way to exclude the example/ from being published? In this case there isn't anything useful in the `example/README.md` file.

**Comment by isoos** [comment]
We have an overall size limit for uploaded packages, there is no specific limit in the example directory.

One common thing that happens is that e.g. Flutter examples include native build artifacts that push the size over the limit. Excluding such artifacts via `.gitignore` usually helps. Could you please check which artifacts are there that are too large and happen during the build? We could probably expand the  [stagehand](https://github.com/dart-lang/stagehand) templates with the appropriate `.gitignore` rules.

**Comment by jonasfj** [comment]
The `pub` client will warn if files in `example/` imports packages not declared in top-level pubspec..
I fixed that yesterday, so it doesn't warn anymore, it'll be part of the next Dart release.
