### ISSUE TITLE
Pub is not feeling well. Fatal package site error.

### ISSUE THREAD

**Issue by komapeb** [dart-lang/pub-dev#2336]
You asked me for this issue, here are the details:

```
Requested URL: https://pub.dev/packages?q=data+connection&page=3
Request ID: ffb554334f52295caca5b70914b68506
```

**Comment by jonasfj** [comment]
Can you reference where we asked for this... I think I might have forgotten the context..

Sorry, we're are more than one person and we juggle at lot of issues.

What is the problem, are you getting an error message?

**Comment by isoos** [comment]
I believe it has something to do with the google cloud outage that happened roughly 2 hours ago.

**Comment by komapeb** [comment]
This is on the pub.dev site, exactly on the requested URL provided in the details of the first comment.

**Comment by isoos** [comment]
Actually, I think this is not caused by the gcloud network issues, rather our `search` service restarting. The failing request was hitting the `search` service during the bootup process and it responded with status code `600` (a custom code indicating that it was not ready yet).

**Comment by jonasfj** [comment]
@isoos, so that sounds like we've 3 possible problems:
1) the `search` service returns 200 ok to health checks before it's ready.
2) the health check configuration for the `search` service is wrong,
3) the `search` service is crashing and causing restarts.

**Comment by isoos** [comment]
Looking at the logs in depth, and it seems that when the `search` service was starting up, it failed to load the snapshot (and the popularity data as well), and it started to populate search via normal Datastore queries.

- The snapshot failure happened for multiple service instances between `2019-06-02 20:53:36.385 CEST` and `2019-06-02 20:58:23.088 CEST`.
- Based on the logs this self-building process completed at `2019-06-02 22:41:30.015 CEST`, almost 2 hours later.
- In the meantime another instance restarted and was able to merge the snapshot and was up and running at `2019-06-02 22:19:48.489`.

We have a retry in place that would try another request if the search index was not ready, however, in such prolonged case there is a good chance that the second request goes to the same uninitialized index. We'll need to refactor the service startup and use not only the health checks, but also the readiness checks to indicate when the load balancer can route requests towards the service.

**Comment by jonasfj** [comment]
Yes, "readiness checks" (sorry, I confused that with health checks).

**Comment by isoos** [comment]
Yeah, correct, we'll need to implement `readiness_check` (and split the health checks for it).

**Comment by isoos** [comment]
[`app_start_timeout_sec`](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/configuring-your-app-with-app-yaml#updated_health_checks) seems to be 1800 seconds maximum, which means we can't just blindly rely on the current update mechanism, as it takes almost three times to get to that point. I think (in the absence of the ready-made search snapshot) one thing that we can do is to build a search index without the dartdoc content, that should be doable within a few minutes after the startup, and start indicate readiness. It would be not that ideal compared to the full index, but it would provide a good fallback.

**Comment by jonasfj** [comment]
Yes, degrading to a smaller search index would be perfectly fine... Even if we just used package name, description and popularity that would be perfectly fine for 10 minutes or so...

**Comment by sigurdm** [comment]
To make the set-up less fragile the front page should, in my opinion, have a fall-back version that doesn't rely on search at all (Either bake in a fixed set of popular packages or don't show popular packages if search has problems).
