### ISSUE TITLE
Authorization stuck

### ISSUE THREAD

**Issue by Benx4001** [dart-lang/pub-dev#2340]
URL: https://pub.dev/authorized#

when Autorization received, processing.... nothing happen.  I just stuck there...

**Comment by isoos** [comment]
@Benx4001: what happened in your `pub` client (command line tool)? Did it report that you've successfully authorized? At the moment the website does not do much more (but we are working on it to improve that)

**Comment by jonasfj** [comment]
Please provide additional information, otherwise we'll have to closed this as we can make no further progress.

**Comment by Benx4001** [comment]
just as i said, nothing happend. no comment, no words, just let me waiting... and i have waited for half an hour....

**Comment by Benx4001** [comment]
> h more (but we are working on it to improve that)

yes, it tells me authorized ok, but then no reply any more(no response and just stuck there), no more words there.  Could you please help me out~?

**Comment by isoos** [comment]
@Benx4001:
1) What platform are you using (e.g. Windows/Linux)?
2) Are you referring to the command-line client or the web site that is stuck? Did you try to re-do it?
3) Are you able to upload packages?

**Comment by Benx4001** [comment]
@isoos 
1. I'm using macos.
2.I just execute the command pub publish and then as follow:
Benjamins-MacBook-Air:h5Compress benx4$ pub publish
Publishing h5compress 1.0.0 to https://pub.dartlang.org:
|-- .packages
|-- LICENSE
|-- README.md
|-- index.html
|-- lib
|   '-- h5Compress.dart
|-- main.dart
'-- pubspec.yaml

Looks great! Are you ready to upload your package (y/n)? y
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A62414&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Then click "Allow access".

Waiting for your authorization...
Authorization received, processing...
----------
And i goto the link and the screen tell me "Pub Authorized Successfully" and no more, **according to the response, there should be a button called "Allow access", but there isn't.**

3. and i cannot upload the package to the pub

**Comment by jonasfj** [comment]
@Benx4001, you need to open it in a browser that has access to `localhost`.

Try to open it in an incognito mode... I all have to do is to select account..

Please make sure copying the entire URL too...

**Comment by Benx4001** [comment]
@jonasfj 
I have tried as what you said but the browser finally take me to https://accounts.youtube.com/accounts/SetSID and then tell me the site cannot be reached....

**Comment by jonasfj** [comment]
@Benx4001,

Can you try to document the list of URLs you're redirected through.. Make sure to obfuscate `?code=XXX` and other sensitive parts.

**Comment by jonasfj** [comment]
> then tell me the site cannot be reached....

Who tells you that? which site.. was your pub client still running? Did you use the same account you use with gmail? ie. your google account..

**Comment by Benx4001** [comment]
@jonasfj 

Ok, i describe the issue again.

First, i type the "pub publish" in the terminal and the screen told me that it needs my authorization, so i FULLY copy the link and go to the authorize site and then, the site tolds me i have passed the authorzation and the terminal said Authorization received, processing... and then, nothing happen, and i have followed your suggestion visit the link in the incognito window, that's all, and until now i still cannot upload my package.  my system is macos. and my pub client just hold up there, still waiting for something, and i use gmail.

**Comment by jonasfj** [comment]
Hmm, post the terminal output in a code fences:
https://help.github.com/en/articles/creating-and-highlighting-code-blocks

Do you have a file `$HOME/.pub-cache/credentials.json`?

**Comment by Benx4001** [comment]
@jonasfj 

The output and the process i meet list as follow:

```
Benjamins-MacBook-Air:h5Compress benx4$ pub publish
Publishing h5compress 1.0.0 to https://pub.dartlang.org:
|-- .packages
|-- LICENSE
|-- README.md
|-- index.html
|-- lib
| '-- h5Compress.dart
|-- main.dart
'-- pubspec.yaml
Looks great! Are you ready to upload your package (y/n)? y
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=**********.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A62414&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Then click "Allow access".
```

### **and i have a look at the directory "$HOME/.pub-cache", but no file as you mentioned.**

**Comment by jonasfj** [comment]
Where does it say "processing"?

Are you behind a corporate proxy or similar... Do you have a firewall preventing `pub` from making external requests?

Note. This looks a problem specific to your machine...

Also try to run with `pub publish --trace` to get more information about what is going on...
