### ISSUE TITLE
Use another gmail to publish

### ISSUE THREAD

**Issue by GanZhiXiong** [dart-lang/pub-dev#2345]
I used gmail A to publish A package to pub. Dev, since gmail A will not be used in the future, so I want to publish the package with gmail B, what should I do?

I'm from China, and my English is not very good. If you don't understand, you can ask me again, Thanks!

**Comment by isoos** [comment]
@GanZhiXiong You can invite the other e-mail (gmail B) to become an uploader to the package. [the pub uploader documentation](https://dart.dev/tools/pub/cmd/pub-uploader) gives more details, but in short:
- run `pub uploader add otheremail@gmail.com`
- follow the instructions in the email
- re-login to your pub credentials, now with the new email (`pub logout` and then `pub publish`)
- remove your old email from the package as uploader.

**Comment by GanZhiXiong** [comment]
run pub uploader add otheremail@gmail.com
output command not found: pub
![image](https://user-images.githubusercontent.com/27394631/59112087-e7391400-8974-11e9-9693-efb50faa2d9b.png)

**Comment by isoos** [comment]
oh, you are using flutter... You need to use `flutter pub pub uploader add ...` then.

**Comment by GanZhiXiong** [comment]
Yes, thank you very much, problem solved!
