### ISSUE TITLE
Delete version request

### ISSUE THREAD

**Issue by NicolaChimerapps** [dart-lang/pub-dev#2346]
Please delete version 0.2.0 for me.

package url: https://pub.dev/packages/niddler_dart

Due to the use of a flutter > 2.3.1 constraint, it now shows that SDK is incompatible, so please delete this 0.2.0 version for me for the time being.

Related to #2290

**Comment by jonasfj** [comment]
I sent a confirmation email.

**Comment by jonasfj** [comment]
confirmed and deleted :)
