### ISSUE TITLE
analysis does not ignore dependency_overrides

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2355]
When we install a package dependencies to do analysis on it, we should ignore `dependency_overrides`.

See also https://github.com/dart-lang/pub/issues/1867

**Comment by jonasfj** [comment]
This is naturally blocked on https://github.com/dart-lang/pub/issues/1867

**Comment by isoos** [comment]
We ignore them: https://github.com/dart-lang/pana/blob/master/lib/src/sdk_env.dart#L447

Is there an example/package where we do use them?

**Comment by jonasfj** [comment]
oh, nice :)
