### ISSUE TITLE
Remove author from the package page

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2384]
The `author` field from the `pubspec.yaml` is trivial to spoof.

I proposal that we just don't expose it anymore, and then move to remove it from documentation later.

thoughts, @mit-mit, @isoos?

**Comment by isoos** [comment]
In some cases I'm a contributor to a package or somebody else is also a contributor to mine, but the publish right is kept at the original person. I kind of like this recognition of contribution, but of course it could be expressed in the `README.md` too.

**Comment by isoos** [comment]
Also I think `author` or `authors` is a required field in `pubspec.yaml`, maybe we should make it optional first?

**Comment by kevmoo** [comment]
We could encourage folks to use an `AUTHORS` file, too...

I think this is worth a doc. Need to coordinate with the site, pub, pub-dev, and pubspec-parse.

...and should email announce@ to let folks know our plans, etc.

**Comment by jonasfj** [comment]
Okay, this might need some bigger thoughts, I'll close this for now and file an issue for figuring out what we want to do for authors. It might come after publishers.

**Comment by kevmoo** [comment]
After publishers seems like the right ordering
