### ISSUE TITLE
Suggestion: git user integration so we can curate favorite packages outside of github?

### ISSUE THREAD

**Issue by exts** [dart-lang/pub-dev#2387]
Right now the only way to keep track of packages is through github's star system, but that can get a bit cluttered and mixed with all your other stuff . So why not have basic user integration into the pub.dev site with github integration to allow us to keep track of our favorite packages?

Similar to how composer does it over at https://packagist.org

**Comment by jonasfj** [comment]
I'm not sure we can do github integration, as we're using google accounts when publishing.

But letting users sign-in and star packages would be cool, but as a way to track favorite packages and as a manner to signal interest.

I don't want to promise anything, but we're interesting in adding features if users are interested in using them :)

**Comment by exts** [comment]
I guess since pub.dev supports this I can close the issue :O
