### ISSUE TITLE
integration tests for publishing existing package version

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2398]
We should probably have tests for:
  * Publishing existing version,
 * Publishing a package for when not an uploader

Maybe there is other failure cases we want to test too?

Probably we could make an assert that the error message contains some sane substring... just a substring like..."failed" or "unauthorized".

**Comment by sigurdm** [comment]
FYI: The current error message when uploading an existing version is just:
```
Package upload canceled.
```
That could probably be improved.

**Comment by isoos** [comment]
@sigurdm: Not sure how you got that, I'm getting `Version 0.0.2+5fhvo of package _dummy_pkg already exists.` (this is from the test I'm about to submit).

**Comment by sigurdm** [comment]
> Not sure how you got that, I'm getting Version 0.0.2+5fhvo of package _dummy_pkg already exists. (this is from the test I'm about to submit).

I am not able to reproduce. Might have been some other fluke.
