### ISSUE TITLE
50 Package score should not be red

### ISSUE THREAD

**Issue by miyoyo** [dart-lang/pub-dev#2445]
A package with a low score (Say, [this one](https://pub.dev/packages/event_commander)) has it's score shown in deep red, indicating a problem, or at least a negative emotion.

However, brand new, quality packages (Say, [this one](https://pub.dev/packages/spa)) that have  a score of 50 are *also* shown in red, decreasing the potential chances an user has to pick it.

Showing a neutral (Gray) or the cyan score given to packages with scores higher than 50 should put them forward and increase their chances of being used, it also brings another incentive for people to keep their package quality high.

**Comment by isoos** [comment]
The color coding is there to help creating quick decisions. red = needs to investigate before use, teal = looks okay, blue = looks good.

The choice of 50 being red was a deliberate choice: You can get to 50 by having a package with no issues, but can't get above it if you have no users (no downloads, no popularity). Keeping 50 red is a good way to separate packages with real use from packages without actual use (or they have some use but also identified issues).

If I remember correctly, even the smallest use of the package will push the popularity score up enough to move out of red. (Note: it may take a day or two for the popularity score to change). To counter the lack of use for new packages, in the first month we display the 'new' sticker on the score.

If we were to use grey for new packages, that wouldn't mean that new users would need to investigate less, it wouldn't mean that we can trust it more than a package that has no use either but is 6 months old. It wouldn't add a different visual clue for quick decisions.

I understand that the choice of this is very opinionated, it is not ideal for a brand new package, but I think it serves the users of the pub site better by removing an ambiguity. Having said that, the usual disclaimer applies: we are open to refine it (with the goal to provide more value to the current or future users of the published package).
