### ISSUE TITLE
Request to delete plugin

### ISSUE THREAD

**Issue by konyavic** [dart-lang/pub-dev#2453]
Plugin: https://pub.dev/packages/pushenabledplugin

I was learning to develop a flutter plugin but didn't noticed that it's not easy to delete it from pub.dev after published.
Please delete it. I'm sorry for taking your time.

**Comment by jonasfj** [comment]
I sent an email for confirmation, please reply to that :)

**Comment by jonasfj** [comment]
Request confirmed.

**Comment by jonasfj** [comment]
Package should have been deleted. it might linger in caches a bit longer..
