### ISSUE TITLE
Ins't pub supposed to use flutter stable channel?

### ISSUE THREAD

**Issue by erickzanardo** [dart-lang/pub-dev#2464]
Hi,

Ins't pub supposed to use current stable channel from flutter?

We just uploaded a new version of our package flame, and it is getting errors regarding flutter version: https://pub.dev/packages/flame#-analysis-tab-

Saying that we should still be using `1.5.4-hotfix.2`.
Flutter stable channel is now at `v1.7.8+hotfix.2`.

We are losing a lot of points due this.

Thanks for you time

**Comment by isoos** [comment]
At the moment every SDK change is manual (including the Flutter version we are using), and we haven't upgraded it yet (note: 1.7.8+hotfix.2 was only promoted yesterday). We do a bit integration testing before releasing a new version, please be patient until that happens, we'll do our best to release the new version with the updated Flutter SDK as soon as possible.

As soon as we release the new version, the package will receive an updated analysis with the new SDK, you don't need to do anything for it to happen.

**Comment by erickzanardo** [comment]
Oh, I didn't knew this was a manual process, I thought it was a bug or something.

Sorry to bother with this issue, we will wait for the upgrade them.

Thanks!

**Comment by vlidholt** [comment]
Having the same issue, Flutter has breaking changes for my package (spritewidget). When uploading the working package for latest stable Flutter pub.dev doesn't produce documentation and cannot identify it as a Flutter package. The version running on pub seem to be at least a couple of months old.

**Comment by isoos** [comment]
Traffic was switched to the new release, your packages are now displaying healthy status with the new SDK. Closing issue.

FYI: we are planning to automatically follow the stable releases in the feature, but up until that happens, feel free to open issues like this if we are behind again.

**Comment by erickzanardo** [comment]
Thanks for the response!
