### ISSUE TITLE
Request to delete plugin

### ISSUE THREAD

**Issue by james-alex** [dart-lang/pub-dev#2473]
Hello, I just uploaded a package using a different google account than intended.

https://pub.dev/packages/html_character_entities

Would it be possible to delete the package so I can re-upload it using the correct account?

Thank you and sorry for the trouble!

**Comment by jonasfj** [comment]
You can also do `pub uploader add <email>` to invite the google account you want to be uploader.
You'll need to accept an invitation email...

Then you can remove your current account with `pub uploader remove <email>`.

**Comment by jonasfj** [comment]
See also: https://dart.dev/tools/pub/cmd/pub-uploader

**Comment by james-alex** [comment]
That worked. Thanks so much.
