### ISSUE TITLE
Feature  suggestion :: Depracated/Failing packages shoud be marked visibly.

### ISSUE THREAD

**Issue by Arthur-Kamau** [dart-lang/pub-dev#2485]
Quick suggestion, Earlier on i decide to use simple permissions package hosted on pub.dev.
Later on i decided to switch to android x only to find simple permission is incompatible with android, thats ok, the trouble started when i realized the package is no longer maintained, in fact its github repository had been deleted.

_Suggestion_
When deciding to use a package the ability to have a quick view of the package health and/ or report a package could be quite usefule on the pub.dev website.

Thanks in advance.

**Comment by jonasfj** [comment]
Isn't that pretty much what we have here:
 https://pub.dev/packages/simple_permissions#-analysis-tab-

Sure, the numbers could be tweaked. But this package does get a lower score because the homepage is down.

**Comment by isoos** [comment]
We consider one year inactivity as acceptable in a package's life, and start to decrease its maintenance score until it reaches the age of two years. I'm not sure if it is worth to make that more strict.

We are planning to implement something along the lines of #798 (community feedback), which would provide another tool to gauge the usefulness of a package.
