### ISSUE TITLE
Pub search not working

### ISSUE THREAD

**Issue by v0l** [dart-lang/pub-dev#2517]
```
Requested URL: https://pub.dev/packages?q=pay
Request ID: a24c3c02d7d8ea29b9197f05926d0e4c
```

**Comment by isoos** [comment]
Thanks for the report. We are experiencing a site-wide issue with "quota exceeded" errors on many requests, this did affect your search too.

**Comment by isoos** [comment]
The site received far more traffic than we have anticipated. We've allocated more resources and plan to keep up with increased usage going forward.
