### ISSUE TITLE
Pub is not feeling well

### ISSUE THREAD

**Issue by OliverNarramore** [dart-lang/pub-dev#2520]
Requested URL: https://pub.dev/packages/flutter_rating_bar
Request ID: ae41ddb86c9cd688c99fd11d2f05dd7d

**Comment by catalin260** [comment]
I've encountered also this issue, today.

**Comment by isoos** [comment]
Thanks for reporting. The site received far more traffic than we have anticipated. We've allocated more resources and plan to keep up with increased usage going forward.
