### ISSUE TITLE
Pub is not feeling well

### ISSUE THREAD

**Issue by SameerMasood** [dart-lang/pub-dev#2521]
Requested URL: https://pub.dev/packages?q=http
Request ID: 013e9660ab09096716a744f4f121b72c

**Comment by minikin** [comment]
I have the same issue but with different packages.

> HTTP error 500: Internal Server Error at https://pub.dartlang.org/api/packages/flutter_blue.
> This is likely a transient error. Please try again later.

**Comment by isoos** [comment]
Thanks for reporting. The site received far more traffic than we have anticipated. We've allocated more resources and plan to keep up with increased usage going forward.
