### ISSUE TITLE
pub.dev searches are leading to "Fatal package site error."

### ISSUE THREAD

**Issue by hmayer00** [dart-lang/pub-dev#2536]
Requested URL: https://pub.dev/packages?q=flutter
Request ID: 38aefbb9634ac004e2033bf4af94d0d1

This leads to the following message:

>Pub is not feeling well #
Fatal package site error.

I saw this first when going to http://pub.dev/packages/mobx, and at the time running a search for flutter worked and did not error. But checking now, it also errors. Not sure what to make of it but the page advised me to open an issue and that seemed like the appropriate step.

**Comment by isoos** [comment]
Thanks for reporting. The site received far more traffic than we have anticipated. We've allocated more resources and plan to keep up with increased usage going forward.
