### ISSUE TITLE
Fatal package site error on opening every package page

### ISSUE THREAD

**Issue by DP1000** [dart-lang/pub-dev#2541]
When i open every package page pub.dev says this to me:

**Pub is not feeling well #**

**Fatal package site error.**

Please open an issue: [https://github.com/dart-lang/pub-dev/issues/new](https://github.com/dart-lang/pub-dev/issues/new)

Add these details to help us fix the issue:

```
Requested URL: https://pub.dev/packages/http
Request ID: f1aa7b36c15dc1822c713dc7df0d655c
```

**Comment by isoos** [comment]
Thanks for reporting. The site received far more traffic than we have anticipated. We've allocated more resources and plan to keep up with increased usage going forward.
