### ISSUE TITLE
Pub site crashed during search

### ISSUE THREAD

**Issue by CukierPuder420** [dart-lang/pub-dev#2546]
I tried to search "appbar" on pub.dev.
"Fatal package site error" appeared.
Error info that the site has given me to put in a GitHub issue:
`Requested URL: https://pub.dev/packages?q=appbar`
`Request ID: 91338555db2f8a5027ef8cb0bc9eef2a`

**Comment by isoos** [comment]
Thanks for reporting. The site received far more traffic than we have anticipated. We've allocated more resources and plan to keep up with increased usage going forward.
