### ISSUE TITLE
pub.dev fatal error

### ISSUE THREAD

**Issue by rtessler** [dart-lang/pub-dev#2558]
search for any package

Pub is not feeling well #
Fatal package site error.

Requested URL: https://pub.dev/packages?q=location
Request ID: efc9d3cbced20aeb218d3c7e40cbb5b6

**Comment by isoos** [comment]
Thanks for reporting. The site received far more traffic than we have anticipated. We've allocated more resources and plan to keep up with increased usage going forward.
