### ISSUE TITLE
Fatal package site error

### ISSUE THREAD

**Issue by Lujain-Kotb** [dart-lang/pub-dev#2566]
Requested URL: https://pub.dev/packages/dots_indicator
Request ID: 8e395bd108261f57e6cf46387b283332

The returned status code is 500.
I've been trying to open up multiple packages but the same error returns, whether I enter it from a google search or try to search for a certain package

**Comment by isoos** [comment]
Thanks for reporting. The site received far more traffic than we have anticipated. We've allocated more resources and plan to keep up with increased usage going forward.
