### ISSUE TITLE
Search for "auth0" caused an error

### ISSUE THREAD

**Issue by en237** [dart-lang/pub-dev#2567]
Pub is not feeling well #
Fatal package site error.

Please open an issue: https://github.com/dart-lang/pub-dev/issues/new

Add these details to help us fix the issue:
Requested URL: https://pub.dev/packages?q=auth0
Request ID: 84f39f0eb46a8365cd060faf84ca23e0

**Comment by isoos** [comment]
Thanks for reporting. The site received far more traffic than we have anticipated. We've allocated more resources and plan to keep up with increased usage going forward.
