### ISSUE TITLE
https://pub.flutter-io.cn/packages?q=flutter_flipperkit

### ISSUE THREAD

**Issue by phpmaple** [dart-lang/pub-dev#2569]
Requested URL: https://pub.flutter-io.cn/packages?q=flutter_flipperkit
Request ID: f8b709328e01f075a68ffac6b777be66

**Comment by isoos** [comment]
Thanks for reporting. The site received far more traffic than we have anticipated. We've allocated more resources and plan to keep up with increased usage going forward.
