### ISSUE TITLE
Fatal package site error.

### ISSUE THREAD

**Issue by HappyCodingLife** [dart-lang/pub-dev#2570]
Requested URL: https://pub.dev/packages/event_bus
Request ID: e96deafde4f09eea2a90e84a1219e44d

**Comment by cis-emp1822** [comment]
Requested URL: https://pub.dev/packages
Request ID: d5dab2d9203e3d0e22c5452787bf3a30

**Comment by isoos** [comment]
Thanks for reporting. The site received far more traffic than we have anticipated. We've allocated more resources and plan to keep up with increased usage going forward.
