### ISSUE TITLE
Pub is unreachable

### ISSUE THREAD

**Issue by joshuadeguzman** [dart-lang/pub-dev#2571]
It seems like pub is not feeling well, it's not package specific.

Fatal package site error.

Please open an issue: https://github.com/dart-lang/pub-dev/issues/new

Add these details to help us fix the issue:

Requested URL: https://pub.dev/packages?q=floor_generator
Request ID: a00dd673fd3454ca84b842102298abea

Attachment
![Screen Shot 2019-07-24 at 5 56 51 PM](https://user-images.githubusercontent.com/20706361/61784533-72df0500-ae3c-11e9-85a2-a00eee7afa2b.png)

**Comment by isoos** [comment]
Thanks for reporting. The site received far more traffic than we have anticipated. We've allocated more resources and plan to keep up with increased usage going forward.
