### ISSUE TITLE
Pub is not feeling well

### ISSUE THREAD

**Issue by rostopira** [dart-lang/pub-dev#2574]
`Pub is not feeling well #
Fatal package site error.

Please open an issue: https://github.com/dart-lang/pub-dev/issues/new

Add these details to help us fix the issue:

Requested URL: https://pub.dev/packages?q=admob
Request ID: 5a37660f986e610855efdc776c688571`

**Comment by isoos** [comment]
Thanks for reporting. The site received far more traffic than we have anticipated. We've allocated more resources and plan to keep up with increased usage going forward.
