### ISSUE TITLE
Pub is not feeling well

### ISSUE THREAD

**Issue by izik1** [dart-lang/pub-dev#2583]
Requested URL: https://pub.dev/packages?q=package_info
Request ID: 41254eb5990e19e02a42f53f9966ff7a
Happens with other packages too, searching for the same package again seems to fix the issue, which leads me to believe that it has something to do with caching
fairly quick edit: only sometimes gets fixed, it seemed to have stopped doing so right after submitting

**Comment by jonasfj** [comment]
Thanks for reporting, pub is feeling much better now!

We apologize for the inconvenience.
