### ISSUE TITLE
Pub is not feeling well - tried search a few times and got this error

### ISSUE THREAD

**Issue by MacRonin** [dart-lang/pub-dev#2588]
Pub is not feeling well #

Fatal package site error.

Please open an issue: https://github.com/dart-lang/pub-dev/issues/new

Add these details to help us fix the issue:

Requested URL: https://pub.dev/packages?q=fffff
Request ID: 1f3097ccf1116144d70c8463cafc0688

**Comment by jonasfj** [comment]
Thanks for reporting, pub is feeling much better now!

We apologize for the inconvenience.
