### ISSUE TITLE
Pub is not feeling well #

### ISSUE THREAD

**Issue by kmusham** [dart-lang/pub-dev#2591]
Pub is not feeling well #
Fatal package site error.

Please open an issue: https://github.com/dart-lang/pub-dev/issues/new

Add these details to help us fix the issue:

Requested URL: https://pub.dev/flutter/packages?q=http
Request ID: b2be5486499a7dabf62387d836832ee3

**Comment by jonasfj** [comment]
Thanks for reporting, pub is feeling much better now!

We apologize for the inconvenience.
