### ISSUE TITLE
discontinue: vm_service_lib

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#2601]
URL: https://pub.dev/packages/vm_service_lib

See https://github.com/dart-lang/vm_service_drivers

CC @bkonyi

**Comment by bkonyi** [comment]
Thanks Kevin! We haven't migrated clients off of the package quite yet, so
just confirming this won't remove it from pub?

**Comment by kevmoo** [comment]
Nope! Will just keep new users away from it!

I'm holding off doing the archive until everyone has moved off...

**Comment by jonasfj** [comment]
Should be resolved.
