### ISSUE TITLE
isHandlerForApiPackageMetrics used? Could be removed?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#2606]
https://github.com/dart-lang/pub-dev/blob/31278da4085df55e135d21b9a9dbe5a6e5d17670/app/lib/frontend/handlers/custom_api.dart#L173-L183

Didn't see any usage of this...

**Comment by isoos** [comment]
Good catch, it became obsolete with the pub API extraction. Do you use a tool for detecting these?

**Comment by kevmoo** [comment]
> Good catch, it became obsolete with the pub API extraction. Do you use a tool for detecting these?

Lucky catch. I wish we had such a tool!
