### ISSUE TITLE
Dump dartdoc log w/ JSON

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#2607]
dartdoc has a `--json` flag. Use it when generating the log. Would allow easier parsing of issues – future hints on score tab on what/how to fix!

https://pub.dev/documentation/path/latest/log.txt

**Comment by sigurdm** [comment]
We now have the dartdoc output in the task log: https://pub.dev/packages/retry/score/log.txt linked from the scoring page.

It is most like sufficient that that is non-json human readable.
