### ISSUE TITLE
Search seems to repeat itself

### ISSUE THREAD

**Issue by MTRNord** [dart-lang/pub-dev#2608]
I went to page 40 on https://pub.dev/packages?q=dependency%3Aflutter&page=40 and seem to have reached the beginning of the search. Also, there are ALOT of duplicates in the results anyway. It feels kinda bugged tbh.

**Comment by isoos** [comment]
@MTRNord: What package was duplicated in the result?

I don't see search outage in the logs (that would cause use to revert to a much simpler search).

**Comment by MTRNord** [comment]
uhm actually I saw multiple packages twice. There was not one specific that's duplicated. But around page 40 it felt like I reached page 1 again. There were mostly exactly the same packages shown. But actually I just was trying to verify it but it seems like it fixed itself or something.

**Comment by isoos** [comment]
I've reviewed the related code, and I couldn't find much that would stand out causing such issues:
- the search service cache is set to 10 minutes, is using the correct cache key (the request URL)
- in case the search service has an outage, the fallback name-only search does have a pre-sort by package name, which means it couldn't have an unpredicted order between pages.

I've found one explanation that could explain a small glitch at best: if two instances of the search service could have diverged, e.g. one received the new popularity score update, while the other did not, and the first query hit the one, while the second query hit the other, the package ordering may differ.

It certainly does not explain the feeling of "search pages repeating themselves".

**Comment by MTRNord** [comment]
As said in my second comment, I wasn't able to reproduce it. The issue seems to have been a one time glitch. I am not sure what happened, but it quickly resolved itself. So I am not sure why it happened, but it can't have been more than a glitch.
