### ISSUE TITLE
Don't display "API documentation" URL for versions that have no valid documentation generated.

### ISSUE THREAD

**Issue by GITANSHU7** [dart-lang/pub-dev#2610]
URL: https://pub.dev/documentation/intl/0.15.2/

<Describe your issue or suggestion here>

**Comment by isoos** [comment]
`intl 0.15.2` is almost two years old, and its SDK constraints do not support our current Dart SDK for analysis. Check the latest version, in this case it is `0.15.8`, and it works: https://pub.dev/documentation/intl/latest/

**Comment by isoos** [comment]
Updated the title to track the UI part of this issue.
