### ISSUE TITLE
URL in upload notification e-mail ends with an extra dot.

### ISSUE THREAD

**Issue by ACE-YANGCE** [dart-lang/pub-dev#2612]
What's wrong???

Requested URL: https://pub.dev/packages/flutter_bubble/versions/0.0.1.
Request ID: 46cf88f370ce738912955180af3caa09

**Comment by isoos** [comment]
Did you try to open the URL with the ending dot (`.`)? Yeah, that's an issue with the e-mail we are sending out, we should remove that. Let me keep this issue open for it.
