### ISSUE TITLE
Need more quality signals

### ISSUE THREAD

**Issue by jayoung-lee** [dart-lang/pub-dev#2616]
From the comments we collected from the Q2 2019 user survey, we learned that pub.dev users are in need of more information about the packages for better decision making. 

Some of the improvements we could consider making are: 
* Surfacing more information about the packages, such as dependencies or compatibility (which is related to #187)
* Providing more trust signals that can help users identify trustworthy and well-maintained packages (which is related to #1229)

 cc: @mit-mit

**Comment by isoos** [comment]
I think these were implemented (in the past year).
