### ISSUE TITLE
Request to delete packages flutter_exoplayer and exoplayer

### ISSUE THREAD

**Issue by danielR2001** [dart-lang/pub-dev#2620]
hi, I'm new to flutter and it's my first package uploaded and by mistake I opened two packages flutter_exoplayer and exoplayer (with author name luan, not my name) that I want to be removed because I made some mistakes in the package name and the author name, I know that you recommend not doing that but I uploaded these packages just right now and don't think someone is depending on them.
please help me.

**Comment by jonasfj** [comment]
I've sent an email asking for confirmation to remove:
 
https://pub.dev/packages/exoplayer
https://pub.dev/packages/flutter_exoplayer

**Comment by jonasfj** [comment]
Request confirmed...

**Comment by jonasfj** [comment]
Packages deleted, give caches a some time to clear.
