### ISSUE TITLE
Flutter pub error since 1.7.8 hotfix 4 pub finished with exit code 64

### ISSUE THREAD

**Issue by richasay** [dart-lang/pub-dev#2621]
Last week I started getting error on my flutter_web projects when I try to run `flutter packages pub global get ` where it is giving me an exit code of 64. 
`

> PS C:\Users\xxxxxxxx\Documents\flutter_training\testing\test080219\test_080219> flutter packages pub global get
> Could not find a subcommand named "get" for "pub global".
> 
> Usage: pub global <subcommand>
> -h, --help    Print this usage information.
> 
> Available subcommands:
>   activate     Make a package's executables globally available.
>   deactivate   Remove a previously activated package.
>   list         List globally activated packages.
>   run          Run an executable from a globally activated package.
> 
> Run "pub help" to see global options.
> See https://dart.dev/tools/pub/cmd/pub-global for detailed documentation.
> **_pub finished with exit code 64_**

` 

Since this is happening, I cannot get the webdev server to launch, and cannot use hot-reload for development.  Any ideas on what I can try?
Win10 64
VS Code
Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"
Flutter 1.7.8 hf 4

**Comment by isoos** [comment]
IIRC you want to run either `flutter package **pub get**` or `flutter package **pub global run**`, but not `[...] global get`. What are you trying to do here?

**Comment by isoos** [comment]
@richasay any update on this?
