### ISSUE TITLE
Cant remove package for URGENT matter

### ISSUE THREAD

**Issue by vkDreamInCode** [dart-lang/pub-dev#2625]
I want to COMPLETLY remove 2 packages i made URGENTLY because of personal matters. I myself seem to be unable to do so.

The packages i am talking about:
- https://pub.dev/packages/json_form
- https://pub.dev/packages/forma

I would really appriciate if somebody with the right authority can help me with this.

Thanks for the time,

Vince Kieft

**Comment by jonasfj** [comment]
I sent an email asking for confirmation.

**Comment by jonasfj** [comment]
Packages have been removed following confirmation, give the caches a few minutes to clear...
