### ISSUE TITLE
Search functionality in pub.dev does not take into consideration common typos

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/pub-dev#2626]
URL: https://pub.dev/packages?q=lombock

The above URL returns an empty search result, even though there's a package called `lombok` (very close to `lombock`). I think a Google product should support matching on similar strings :) not only exact search!

**Comment by jonasfj** [comment]
There is actually some fuzzy matching. Even fuzzy matching against words in the API documentation.

@istvan, should we perhaps consider doing a super high quality fuzzy matching against package names? We could perhaps maintain a separate index with my n-grams for packages names only.

**Comment by jonasfj** [comment]
I'm not sure there is something we can fix here, but it's always good to investigate things we can do to improve search results.

**Comment by isoos** [comment]
We do use fuzzy matching, I'll need to investigate why it is was not applied/useful in this case.

**Comment by isoos** [comment]
This is an interesting edge-case, which should be easy to fix:
- The index stored the following parts for `lombok`: `lo, om, mb, bo, ok, lom, omb, mbo, bok, lomb, ombo, mbok, lombo, ombok`.
- The query created the following parts for `lombock`: `lo, om, mb, bo, oc, ck, lom, omb, mbo, boc, ock, lomb, ombo, mboc, bock, lombo, omboc, mbock, lomboc, ombock`
- The current similarity function weights parts with `length^2`, and the similarity score is `0.2994`.
- The current threshold is `0.3`, and with that, the match is rejected.

I'm considering changing the `length^2` to `length^1.5` or similar, that would push this one above the threshold.

**Comment by renatoathaydes** [comment]
Thank you.

**Comment by isoos** [comment]
@renatoathaydes a note: it may take a while to get this change in production (our next planned release is weeks out, due to vacations and ongoing development that we don't want to expose prematurely)

**Comment by renatoathaydes** [comment]
No problem, this is just a minor nuisance as finding packages is a bit harder than it should.

**Comment by isoos** [comment]
FYI: this is in prod now

**Comment by renatoathaydes** [comment]
Hi! Thanks for letting me know... the case I reported definitely works now.

But I found another odd behaviour: if you search for `actor`, a lot of seemingly unrelated projects are shown:

https://pub.dev/packages?q=actor

Doing `Ctrl+F` on that page, I can see that it reports projects that have `actors` in any of their APIs names... for example the first result, `flare_flutter` contains a `flare_actor/flare_actor-library.html` file.

However, an actual package called `actors` exists (I know because I wrote it 😄) and it is not shown on the first page.

Shouldn't the name of the package be the most important term used in the search, with files contained within the package used only as secondary terms? Or perhaps the search uses popularity and other concepts (it was sorted by relevance)?

**Comment by isoos** [comment]
Yes, the search uses both the popularity and the package score as part of the ranking. We do plan to overweight package names and lower the weight of the extracted API surface, which would help to surface your `actors` package, but it is not on our plate for the next few weeks.
