### ISSUE TITLE
Wait for popularity metrics to be loaded before accepting requests

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2639]
If popularity metrics have no been loaded before we start serving requests, we'll report a popularity metric of zero. This can probably make it's way into the cache where it can linger for a long time.

We could clear cache when updating popularity metrics, but that seems risky as we would have to purge a lot of data.

Instead, I propose that we attempt to load popularity metrics before we start accepting requests.
If loading popularity metrics fail, we should log a warning and continue regardless. It's important that we don't block forever, but we can still wait for the first attempt to load popularity metrics to pass.

**Comment by isoos** [comment]
In `PopularityStorage.init` we do fetch the data in a 'blocking' mode, and we also start a timer to refresh it in every 4 hours.

In `default` and in `search`, `init()` is called before the HTTP-serving starts. In `dartdoc` and `analyzer` the `init()` happens on a 'worker' isolate, before the analysis starts (their frontend isolate does very minimal and does not need the data).

Unless there is a bug in this, let's close?

**Comment by jonasfj** [comment]
There is a probably a bug where someone reported that the popularity metrics for `camera` was zero.

How it got to be that is "interesting" :)

**Comment by jonasfj** [comment]
This was an August 7th or so...
