### ISSUE TITLE
Request to delete 

### ISSUE THREAD

**Issue by steven0529** [dart-lang/pub-dev#2641]
Hi, I'm currently exploring uploading packages to help contribute to the community and I've published a dart package by mistake. I would like to request to delete this package. 

This is the link of the package:

[https://pub.dev/packages/chuck_test](https://pub.dev/packages/chuck_test)

Thank you

**Comment by isoos** [comment]
I'm curious: did you find something that was not covered with documentation?

**Comment by jonasfj** [comment]
I sent a confirmation requests by email.

**Comment by steven0529** [comment]
@isoos 
I was following a guide in 

[https://flutter.dev/docs/development/packages-and-plugins/developing-packages](https://flutter.dev/docs/development/packages-and-plugins/developing-packages)

and did not think that there would be no delete option after publishing. I only figured it out when I read the 

[https://dart.dev/tools/pub/publishing](https://dart.dev/tools/pub/publishing) 

Hope that helps, Thanks!

**Comment by jonasfj** [comment]
confirmed.

**Comment by jonasfj** [comment]
package removed, caches might take a few minutes to clear.
