### ISSUE TITLE
API listing package versions sometimes return pub.dev URLs

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2646]
`https://pub.dartlang.org/api/packages/retry`
usually contains:
`"archive_url":"https://pub.dartlang.org/packages/retry/versions/3.0.0.tar.gz"`

but sometimes it contains:
`"archive_url":"https://pub.dev/packages/retry/versions/3.0.0.tar.gz"`

This happens for about 10 minutes, then it's cleared from cache and things return to normal.

Note. it's not a critical bug, but we should be consistent about what we return.

**Comment by jonasfj** [comment]
Note: this is what has been causing one of our status checks to misbehave.

**Comment by isoos** [comment]
I think this happens in https://github.com/dart-lang/pub_server/blob/master/lib/shelf_pubserver.dart
The code does two things:
- it keeps the `http://host:port` part of the `requestedUri` when creating the `archive_url`
- it serves the result content from cache (if it is available)

In effect, if the endpoint receives two different host names, it will eventually serve the "wrong" domain name, which is not checked flexibly in the status checks.

**Comment by chenglu** [comment]
@jonasfj 
Hi Jonas, could you please also check the returns at https://pub.dev/api/packages/, the URL domain of `next_url`, `archive_url`, `package_url ` and `url` seems be changed to `default.dartlang-pub.appspot.com` which could not be reached anywhere.

It will be better to change this URL back to pub.dev, pub.dartlang.org or dartlang-pub.appspot.com, thanks!

**Comment by jonasfj** [comment]
Yeah, we should look into all these, thanks.

**Comment by isoos** [comment]
It looks like we have a second case of "cache poisoning" with the `/api/packages`: there were a lot of requests for `default.dartlang-pub.appspot.com`, and they all seems to be coming from StackDriver. This time I think the endpoint is served by our code directly, at least the `?pretty` URL parameter works with it.

**Comment by jonasfj** [comment]
hmm, so the problem is that we're using the hostname from the incoming request..

**Comment by isoos** [comment]
I think this is now fixed.
