### ISSUE TITLE
incorrect package rejection message

### ISSUE THREAD

**Issue by view-man** [dart-lang/pub-dev#2648]
URL: https://pub.dev/packages?page=4

<Describe your issue or suggestion here>
Looks great! Are you ready to upload your package (y/n)? y
Uploading...
It looks like pub.dartlang.org is having some trouble.
Pub will wait for a while before trying to connect again.
HTTP error 500: Internal Server Error at https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b3bab4c5-454c-4b0a-b933-78489828d090&bucket=pub-packages&key=tmp/b3bab4c5-454c-4b0a-b933-78489828d090&etag=77cf7c034b486b6af3f7574326a4a2ec.
This is likely a transient error. Please try again later.
pub finished with exit code 1

**Comment by view-man** [comment]
{"error":{"message":"UnauthorizedAccess: No active user.."}}

**Comment by isoos** [comment]
Sorry for the confusion, we have a known issue that the failure reason gets lost in such cases.
From the logs it seems that your `pubspec.yaml` doesn't contain `homepage` field. Could you please copy-paste its content here?

**Comment by view-man** [comment]
name: ywz_blue_plugin
description: YWZ Bluetooth Flutter plugin.
version: 0.0.1
author: sunyifei <sunyifei2016@gmail.com>
homepage: https://git@github.com:view-man/ywz_blue_plugin.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue: ^0.6.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.ywz.blue.ywz_blue_plugin
    pluginClass: YwzBluePlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

**Comment by view-man** [comment]
> Sorry for the confusion, we have a known issue that the failure reason gets lost in such cases.
> From the logs it seems that your `pubspec.yaml` doesn't contain `homepage` field. Could you please copy-paste its content here?

name: ywz_blue_plugin
description: YWZ Bluetooth Flutter plugin.
version: 0.0.1
author: sunyifei <sunyifei2016@gmail.com>
homepage: https://git@github.com:view-man/ywz_blue_plugin.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue: ^0.6.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.ywz.blue.ywz_blue_plugin
    pluginClass: YwzBluePlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

**Comment by view-man** [comment]
> Sorry for the confusion, we have a known issue that the failure reason gets lost in such cases.
> From the logs it seems that your `pubspec.yaml` doesn't contain `homepage` field. Could you please copy-paste its content here?

ok，thank you ！My homepage is wrong.

**Comment by jonasfj** [comment]
We should probably make sure we report the right errors :)

**Comment by isoos** [comment]
I think this has been fixed.
