### ISSUE TITLE
version conflict warning in dry run

### ISSUE THREAD

**Issue by BugsBunnyBR** [dart-lang/pub-dev#2649]
I just wanted to use the package meta, went to pub.dev grabbed the latest version and included in my project. I got errors in the analyze just after I published an update.
https://pub.dev/packages/flutter_plugin_annotations
https://pub.dev/packages/flutter_plugin_generator

So, I would like to use this a case to request a better dry run and avoid the analyzes errors pointed in my packages.

Also, how to proceed now? Another release downgrading the meta package version?
```
ERR: Because flutter_plugin_annotations depends on flutter any from sdk which depends on meta 1.1.6, meta 1.1.6 is required.
 So, because flutter_plugin_annotations depends on meta ^1.1.7, version solving failed.
```

I downgraded the meta version and published a new version of my libraries and now I get this
```
The version constraint in pubspec.yaml does not support the latest published versions for 1 dependency (meta).
```

which is not so bad as the previous error, but does not help my libraries classification at all.

**Comment by isoos** [comment]
The good news is: your libraries are classified as Flutter packages properly.

The bad news: Flutter uses version pinning, and you can't always use the latest version, and that's the reason you were needed to lower the version constraint.

Don't worry about the analysis issue ("pubspec.yaml does not support the latest published versions"), we are aware of it (open bug: #2380), and when it gets fixed, your score penalty will get removed automatically.

**Comment by BugsBunnyBR** [comment]
@isoos, thanks for the quick reply.
Would it be possible to improve the dry run to get a warning/error for cases like the one in the bad news? (version pinning)

**Comment by isoos** [comment]
I thought that version constraint checks should be running at upload time, but maybe I'm mistaken. wdyt @jonasfj?

**Comment by jonasfj** [comment]
I think we should make the analysis on the server less strict and not publish your package because flutter is version pinning `meta`. See: https://github.com/dart-lang/pana/issues/551

But yes, extending `pub publish --dry-run` or build some other analysis tooling for warning earlier is something we're thinking about. But it's not clear when we'll get to it. For now I think we should focus on making these analysis errors/warnings less aggressive. If using default lints from flutter or dart templates, most of them should show up in the IDE.

**Comment by isoos** [comment]
> I think we should make the analysis on the server less strict and not publish your package because flutter is version pinning meta.

To be precise: there server is not that strict, and do allow publishing the package. I think the initial version constraint issue was probably caught by the `pub` client, doing a `pub get`.
