### ISSUE TITLE
How to delete my Plugin

### ISSUE THREAD

**Issue by lishuzhi1121** [dart-lang/pub-dev#2677]
URL: https://pub.dev/

<Describe your issue or suggestion here>

Hello, I want to about how to remove my plugin, due to the plugin can't used in iOS Swift project, I need to remake it. I tried to update it, but it doesn't work.

**Comment by isoos** [comment]
@lishuzhi1121:

1) you need to specify the name of your package.
2) What do you mean that you've tried to update but it doesn't work? Could you include the command and its output here?

**Comment by lishuzhi1121** [comment]
> @lishuzhi1121:
> 
> 1. you need to specify the name of your package.
> 2. What do you mean that you've tried to update but it doesn't work? Could you include the command and its output here?

1. My package is  [sharesdk](https://pub.dev/packages/sharesdk)
2. I mean through update the plugin couldn't solve the Swift project problem ,but I commit another plugin in the same way ,it's used well in Swift project ,I don't known why. Maybe the  **[sharesdk](https://pub.dev/packages/sharesdk)** first time make at a lower Flutter version (now, my Flutter is 1.7.8).

**Comment by lishuzhi1121** [comment]
Another plugin I committed is  **[sharesdk_plugin](https://pub.dev/packages/sharesdk_plugin)**

**Comment by isoos** [comment]
Usually we don't recommend to delete a package that is in use, and `sharesdk` seems to be used a lot. I'd suggest that if the plugin has limitations, make it clear in the readme, and guide your users to other solutions when needed.

**Comment by lishuzhi1121** [comment]
Thank you for your suggestion ! I will thinking about it ,but I’m confused on why the `sharesdk` package doesn't support iOS Swift project ,may I have your help to check what’s the differences between `sharesdk` and `sharesdk_plugin` (I motioned above)

**Comment by lishuzhi1121** [comment]
Thank you for your suggestion ! I will thinking about it ,but I’m confused on why the sharesdk package doesn't support iOS Swift project ,may I have your help to check what’s the differences between sharesdk and sharesdk_plugin (I mentioned above)

**Comment by lishuzhi1121** [comment]
Thank you for your suggestion ! I will thinking about it ,but I’m confused on why the `sharesdk` package doesn't support iOS Swift project ,may I have your help to check what’s the differences between `sharesdk` and `sharesdk_plugin` (I mentioned above)

**Comment by isoos** [comment]
I'm not that familiar with Flutter or mobile internals, I'd suggest you to ask it on the following Gitter channel: https://gitter.im/flutter/flutter

This repository is for reporting issues with the pub site, and as we can't really do much with the package (which is under use), I'm closing the issue.

**Comment by lishuzhi1121** [comment]
Thanks!
