### ISSUE TITLE
Admin API authentication

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2679]
We should expect an `id_token` in the `authorization: Bearer <id_token>` header.

It should be verified as follows:
```http
GET https://oauth2.googleapis.com/tokeninfo?id_token=<token>
{
  "aud": "https://pub.dev",
  "azp": "105806801273967101517",
  "email": "jonasfj-toy@dartlang-pub-dev.iam.gserviceaccount.com",
  "email_verified": "true",
  "exp": "1566224729",
  "iat": "1566221129",
  "iss": "https://accounts.google.com",
  "sub": "105806801273967101517",
  "alg": "RS256",
  "kid": "60f4060e58d75fd3f70beff88c794a775327aa31",
  "typ": "JWT"
}
```
Items to verify is:
 * `iss` should be "https://accounts.google.com"
 * `exp` is a timestamp in the future,
 * `iat` is a timestamp no more than 61 minutes before `exp`,
 * `aud` should be `https://pub.dev`
 * `email_verified` should be `"true"`
 * `sub` is listed as `adminServiceAccount` in `configuration.dart`

When verifying we should write a message to logs containing:
 * the request URL,
 * `email` from the JWT above,
 * `azp` from the JWT above (this tells who the JWT was given to).

-----
Clients can authenticate against this by requesting an `id_token` for a service account listed as `adminServiceAccount` in `configuration.dart`. When doing this the client should be sure to specify `audience` and `includeEmail: true`.

For details see: https://cloud.google.com/iam/credentials/reference/rest/v1/projects.serviceAccounts/generateIdToken

**Comment by isoos** [comment]
I think this was done.
