### ISSUE TITLE
discuss: should users be allowed to remove themselves as uploader?

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2681]
Should users be allowed to remove themselves as uploader?

This is a fair question, we've previously prevented this to avoid having any packages without an uploader. But since users can just delete their Google accounts, maybe we should reconsider this policy.

@mit-mit?

----

From a security perspective it's also nice that users can remove permissions they believe they don't need anymore.

**Comment by sigurdm** [comment]
But they should get a big fat warning before doing it.
Retrieving the package after it is left with no uploaders will be a lot of trouble.

**Comment by mit-mit** [comment]
I don't see much value in this for the uploader (we'd need to retain their email address for history to retain trust), and I see lots of pitfalls, so I don't think there's any reason to make this change.

**Comment by jonasfj** [comment]
Okay, keeping this as is, is fine with me :)
