### ISSUE TITLE
Please remove package

### ISSUE THREAD

**Issue by Delagen** [dart-lang/pub-dev#2692]
https://pub.dev/packages/ib_development/versions/0.0.1+1

Published by missing PUB_HOSTED_URL

**Comment by jonasfj** [comment]
Sent an email asking for confirmation..

For future reference you can add a "publish_to: ..." entry in your pubspec.yaml

**Comment by jonasfj** [comment]
Confirmed.

**Comment by Delagen** [comment]
>> For future reference you can add a "publish_to: ..." entry in your pubspec.yaml
Thanks. I forgot to restart terminal after environment variables update.

**Comment by jonasfj** [comment]
Package removed, cache might take a bit to clear :)
