### ISSUE TITLE
README.md is not displayed properly

### ISSUE THREAD

**Issue by DokkarRachidReda** [dart-lang/pub-dev#2697]
URL: https://pub.dev/packages/fancy_dialog#-readme-tab-

the readme doesn't appear properly in the website while it does in github and any other mark down editor

**Comment by isoos** [comment]
@DokkarRachidReda: thanks for reporting it here. I've reported the upstream bug on the markdown repository: https://github.com/dart-lang/markdown/issues/259

**Comment by jonasfj** [comment]
@DokkarRachidReda, a workaround for now is to write:

```md
  * `okFun` : the function ...
```

Instead of:
```md
  * ``` okFun ``` : the function ...
```

Both should render the same on github.

**Comment by DokkarRachidReda** [comment]
@jonasfj  Thank you i will update it

**Comment by DokkarRachidReda** [comment]
i still have problem with images 

<img src="https://github.com/DokkarRachidReda/Fancy-Flutter-Alert-Dialog/blob/master/Screenshots/1.gif" height="420" width="240" hspace="20"><img src="https://github.com/DokkarRachidReda/Fancy-Flutter-Alert-Dialog/blob/master/Screenshots/2_flat.gif" height="420" width="240" hspace="20">

it can't display the image from github 

thank's 👍
