### ISSUE TITLE
Add caching in the name-tracker

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2706]
The name tracker queries for all names periodically, and this is expensive, furthermore it would probably be faster if we cached the list of all package names, and then purged it when a new package is published.

**Comment by isoos** [comment]
I'm not sure where caching could help here. The initial scan is expensive (~ 10 seconds on my local machine, may be network-bound), but the periodic updates (one poll per minute) doesn't seem to be much of a problem.

Assuming we were to cache the names in one big blob, we still need to update it from time-to-time, or on-demand. The on-demand method would create an unexpected latency spike on (a) upload times and (b) when `search` service fails and we are using the fallback search with package names only.

We could probably improve the current solution though, by making the periodic polling less frequent, and/or doing the required polling on-demand (only at package upload).
