### ISSUE TITLE
Missing tab for Dart (only) packages

### ISSUE THREAD

**Issue by guyluz11** [dart-lang/pub-dev#2710]
URL: https://pub.dev/

I am working only with dart, **without Flutter** and **without Web**.
Currently when I am searching for new package I use the tab **All** and filter through the result one by one to check if it compatible with dart natively.

My suggestion is to add new tag (and add the **other** tag)  to the search options so that users that use dart standalone can search for packages.

**Comment by isoos** [comment]
Thanks for reporting this! There was a bit of prior work on this in #858 and #1031. We have this on the horizon, and appreciate every feedback and related requests to make this better.

**Comment by isoos** [comment]
We've deployed a new analysis and tagging, which indicates if a package is for Dart native (a.k.a. server).
