### ISSUE TITLE
Search problems can't find angular_router

### ISSUE THREAD

**Issue by crud-boy** [dart-lang/pub-dev#2715]
1

**Comment by isoos** [comment]
The latest stable version of `angular_router` is `1.0.2`, published on Aug 30, 2017 (almost two years ago), and it is not Dart 2 compatible. The [`2.0.0-alpha+*` releases](https://pub.dev/packages/angular_router/versions/2.0.0-alpha+24) are Dart 2 compatible, but we only index the latest stable versions.

/cc @matanlurey @alorenzen maybe it is due for a new stable release?

**Comment by crud-boy** [comment]
Enable 1.X results, still can not search

**Comment by isoos** [comment]
> Enable 1.X results, still can not search

It is not the first result, but it is on the first page. It has bad quality score :/
