### ISSUE TITLE
The current way to add packages, really like a brother as retarded

### ISSUE THREAD

**Issue by crud-boy** [dart-lang/pub-dev#2717]
You must go to pub. dev to see the version number,
copy it to pubspec. yaml, and execute pub get
Look at the installation of NPM next door

**Comment by crud-boy** [comment]
Bad package management, does not automatically install the corresponding package according to the sdk version, at least also suggest that the current package support sdk version, human drop version test method

**Comment by isoos** [comment]
@crud-boy: there are a lot to unpack here, could you please give us more info what bothers you with package management and versions?

Wrt. visiting the pub.dev site for the latest version, you could do the following in the `pubspec.yaml`:

````
dependencies:
  http: any
  other_package: any
````

That way you could use the latest version, without visiting the pub site, and all the constraints are resolved. Keep in mind, while this works to get started, it is recommended to stick with version constraints, as a breaking change in a library (`2.1.0` -> `3.0.0`) means that your code gets likely broken.

You could also stick with "everything in the 1.X.Y releases" with `^1.0.0`. See more about [version constraints](https://dart.dev/tools/pub/dependencies#version-constraints)
