### ISSUE TITLE
Package needs to be removed

### ISSUE THREAD

**Issue by bsoykal** [dart-lang/pub-dev#2726]
Hi guys,

Package [flutter_nm_sdk](https://pub.dev/packages/flutter_nm_sdk) was a trial plugin and needs to be removed. At the beginning I thought there is a remove button or something similar for deleting unused packages, but later on I discovered it is not possible. Thanks in advance.

**Comment by jonasfj** [comment]
I sent an email to the uploader for confirmation.

**Comment by jonasfj** [comment]
Request confirmed.

**Comment by jonasfj** [comment]
Package removed, caches should clear given a little time..
