### ISSUE TITLE
Need to delete a pub package i accidentally uploaded

### ISSUE THREAD

**Issue by Falsammarraie** [dart-lang/pub-dev#2741]
I accidentally uploaded a local package to pub, this package is not meant to be public, i need it deleted.

**Comment by caoyunxiao** [comment]
Me too

**Comment by jonasfj** [comment]
File a request to have the package delete as an issue... I'll send the uploader and email for confirmation and get this done...

Would that work?

**Comment by caoyunxiao** [comment]
Yes, that's exactly what I want

**Comment by jonasfj** [comment]
Okay, feel free to link the package here... Or create a new issue.

Then I'll look at the package and send the uploader a confirmation email.

**Comment by Falsammarraie** [comment]
this is my package:

https://pub.dev/packages/hotech_flutter_utilities/

**Comment by jonasfj** [comment]
Email sent, request conformed.

**Comment by jonasfj** [comment]
Package removed, caches will expire shortly.

**Comment by caoyunxiao** [comment]
this is my package:

https://pub.dev/packages/album_manager

**Comment by caoyunxiao** [comment]
Why does not directly provide convenient command to developers own management?Can better maintain the community framework quality, because the bad will be deleted.

**Comment by Falsammarraie** [comment]
@caoyunxiao you should probably open a new issue since this one got closed

**Comment by jonasfj** [comment]
> Why does not directly provide convenient command to developers own management?Can better maintain the community framework quality, because the bad will be deleted.

When others depend on your package, it's not fair that you just remove it.

We could plausibly allow removal within a short time framework -- the feature request comes up from time to time.
