### ISSUE TITLE
Need to delete a pub package i accidentally uploaded

### ISSUE THREAD

**Issue by caoyunxiao** [dart-lang/pub-dev#2744]
this is my package:

https://pub.dev/packages/album_manager

**Comment by jonasfj** [comment]
Email sent.

**Comment by caoyunxiao** [comment]
Haven't received, when will search it?It is in

**Comment by jonasfj** [comment]
Sent another email to the `uploader` of the package in question, please confirm by email.

**Comment by jonasfj** [comment]
Confirmed.

**Comment by caoyunxiao** [comment]
thank you

**Comment by jonasfj** [comment]
Done, caches should clear over time..
