### ISSUE TITLE
pub deletion request: davison

### ISSUE THREAD

**Issue by hardyeats** [dart-lang/pub-dev#2746]
https://pub.dev/packages/davison

This is a package that I made and uploaded as a hobbyist, but I'm afraid it's not in the right place. Please delete this package if possible.

**Comment by jonasfj** [comment]
Sent an email to the uploader for confirmation.

Note: hobbyists are welcome to publish packages :)

**Comment by jonasfj** [comment]
Confirmed, and package removed.
