### ISSUE TITLE
pub deletion request:alibc;wxwx_alibc

### ISSUE THREAD

**Issue by XingXiaoWu** [dart-lang/pub-dev#2747]
alibc:  https://pub.dev/packages/alibc

wxwx_alibc: https://pub.dev/packages/wxwx_alibc

I made a plug-in, but upload plugin name wrong, then I changed the plug-in name to upload, the results of flutter plug-in warehouse have two same function but is not the same as the name of the plug-in, I feel very bad, I want to delete the plugin, I write the wrong name, I'm sure no one use it.
thx

**Comment by jonasfj** [comment]
I send an email to the uploader asking for confirmation :)

**Comment by XingXiaoWu** [comment]
I just replied your email
thx

**Comment by jonasfj** [comment]
Confirmed, and removed..
