### ISSUE TITLE
Mail address on https://pub.dev/security bounces

### ISSUE THREAD

**Issue by codemasterover9000** [dart-lang/pub-dev#2756]
URL: https://pub.dev/security

The page contains an email link to product-security@google.com. Sending mail to that address bounces:

> Hello \*\*\*\*\*\*\*@\*\*\*\*\*\*\*,
>
> We're writing to let you know that the group you tried to contact (product-security) may not > exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
> 
>  * You might have spelled or formatted the group name incorrectly.
>  * The owner of the group may have removed this group.
>  * You may need to join the group before receiving permission to post.
>  * This group may not be open to posting.
> 
> If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/google.com/bin/topic.py?topic=25838.
> 
> Thanks,
> 
> google.com admins

**Comment by jonasfj** [comment]
Huh, thanks for reporting, we'll definitely resolve this.

/CC @mit-mit

**Comment by jonasfj** [comment]
For any urgent security concerns, you can also drop me a direct line: `jonasfj@google.com`.

**Comment by jonasfj** [comment]
Okay, it seems vulnerabilities should be reported to https://www.google.com/about/appsecurity/

**Comment by mit-mit** [comment]
I believe the appropriate link specifically for technical vulnerabilities is https://goo.gl/vulnz
