### ISSUE TITLE
Understand conditional imports

### ISSUE THREAD

**Issue by leisim** [dart-lang/pub-dev#2763]
My package has a conditional import which either imports a file which uses `dart:io` (for vm) or another file which uses `dart:indexed_db` (for web).

The analysis tab on pub.dev says:
```
Detected platforms: Flutter, other

Primary library: package:hive/hive.dart with components: io.
```

It should also detect "web". I think there is a problem with detecting the supported platform when conditional imports are used.

**Comment by yjbanov** [comment]
See also: https://github.com/flutter/flutter/issues/35588

**Comment by jonasfj** [comment]
I think this is fixed now, please reopen if not.
