### ISSUE TITLE
Please help to unpublish a package

### ISSUE THREAD

**Issue by yegor-pelykh** [dart-lang/pub-dev#2780]
Hi! I want to unpublish/remove the package I published. It is very new and there is no other packages or projects dependent on it. It is just empty.
Please, may you help me to unpublish it?
Thank you!

**Comment by jonasfj** [comment]
Post a link to the package and I'll send you a confirmation email.

**Comment by yegor-pelykh** [comment]
https://pub.dev/packages/telegram_api

**Comment by jonasfj** [comment]
Email confirmation sent.

**Comment by jonasfj** [comment]
Request confirmed.

**Comment by jonasfj** [comment]
Package removed, caches might take a few minutes to clear...
