### ISSUE TITLE
Searchbox is broken on Chrome OS 78

### ISSUE THREAD

**Issue by timsneath** [dart-lang/pub-dev#2797]
This is Chrome OS 78:
![image](https://user-images.githubusercontent.com/2319867/65288522-f7c46300-dafb-11e9-8228-435d655e5760.png)

Compare with Windows / Chrome 77:
![image](https://user-images.githubusercontent.com/2319867/65288649-6c979d00-dafc-11e9-818c-9da4956e031c.png)

Contrast isn't great in either (it might well not meet accessibility guidelines on Windows), but on ChromeOS, the box seems disabled.

**Comment by isoos** [comment]
This can also be reproduced in Chrome Canary 79 (79.0.3918.0).

**Comment by isoos** [comment]
From #2803: "It looks like that Chrome 78 changed the default color of input::placeholder CSS style, and now defaults to something close to black, which reduced the visibility in our dark grey input field. Setting it explicitly will fix that."
