### ISSUE TITLE
Search works poorly for niche packages

### ISSUE THREAD

**Issue by floitsch** [dart-lang/pub-dev#2813]
I understand that packages with few users should be scored lower than other packages, but the current algorithm is taking this too far.

Search, for example, for "apps script tools".
The user clearly searched for "apps_script_tools".
Instead they get: "flutter_vector_icons", "mdi", and "dart:io", ...
None of these packages even have "apps", "script" or "tools" in their description.

**Comment by jonasfj** [comment]
Agreed,

**Comment by isoos** [comment]
On staging, in the case of `apps script tools` search, the text match score is the following:
- `apps_script_tools`: `0.986`
- `flutter_vector_icons`: `0.807`

But after that there is the overall score based weighting: `F = T * (0.3 + 0.7 * O)`, where `T` = text match score, `O` = overall score, and `F` = final score. This results in the scores of:
- `apps_script_tools`: `0.574 = 0.986 * (0.3 + 0.7 * 0.403)`
- `flutter_vector_icons`: `0.784 = 0.807 * (0.3 + 0.7 * 0.959)`

Some options:
1) We could switch the weights of 30-70%, and that would put the `apps_script_tools` to the top. 
2) We could highly reduce the weights of description (0.95 -> 0.85), readme (0.9 -> 0.8) and api (0.95 -> 0.75, 0.9 -> 0.5), so if there is a name match, we would favour that.
3) We could modify the overall score calculation from multiplication to other weighted average.
4) We could add more "special cases" to promote name matches.

I'll explore 1 and 2 a bit more, to see what else would change with those.

I don't like 4 (and to an extent 3), as it makes the code more complex and it would become harder to migrate to a generic external search tool.

**Comment by floitsch** [comment]
I think decreasing the impact of the overall score is ok. The search page still shows it anyway. If I have three "red" packages at the top (because of best match), and the fourth one is green, users will have a look and see if that one is the one they are looking for.

I don't know how matches in API and Readmes are detected, but it feels like *big* READMEs and APIs will always yield some matches. In particular the huge Flutter package with tons of documentation, or the Google API (which references all of Google services and thus matches for almost everything), are candidates of packages that will probably always have an API match. Maybe one should decrease their score if the surface is huge.
This might also be the reason for icons always being among the first found. There is an icon for almost everything (like "email", "popup", "pencil", "paypal", ...) which yields a match?

Also, I just accidentally searched for "app script tools" (instead of "apps script tools") and apps_script_tools wasn't even in the list of the 34 possible results. The text-matcher clearly seems to have troubles with slightly-off searches.

**Comment by isoos** [comment]
#2869 was deployed. `apps script tools` yields better results, but `app script tools` is still missing it to include in the results.
