### ISSUE TITLE
Remove package flutter_push_notification

### ISSUE THREAD

**Issue by Henry-Keys** [dart-lang/pub-dev#2820]
Could you please remove https://pub.dev/packages/flutter_push_notification

Thanks.

**Comment by jonasfj** [comment]
Any particular reason?

We are also happy to flag the package discontinued.
It's been around for almost a week and from the looks of it might already
have users.

I'll check stats, but we prefer to avoid breaking users if anyone is using
it.


Is it completely broken or are you just discontinuing development?

**Comment by Henry-Keys** [comment]
We will proceed development of it in private for a while. Business decision.

**Comment by Henry-Keys** [comment]
>I'll check stats, but we prefer to avoid breaking users if anyone is using
it.

It is still in pre-release, so probably no one is using it in production.

**Comment by jonasfj** [comment]
Sent a confirmation email. 

> One question: will the package name be vacant after the removal?

Yes,

**Comment by Henry-Keys** [comment]
Confirmed!!

**Comment by jonasfj** [comment]
Package removed, caches might clear in a little while.
