### ISSUE TITLE
Menu Appears Automatically When On Mobile Size

### ISSUE THREAD

**Issue by angelhdz** [dart-lang/pub-dev#2821]
URL: https://pub.dev

<Describe your issue or suggestion here>
When the browser window is resized to mobile size, the menu appears and hides quickly, even when it is not open directly by clicking the hamburger menu icon. I just happen to found this bug because I was looking at a Flutter package called digital_lcd, and they were talking about how responsive their widgets are, and I started to think about "responsiveness", so I tried that page that happened to be open to test its responsiveness (if any), and noticed the bug.

**Comment by isoos** [comment]
Yes, that's a weird effect when resizing, thanks for reporting it.
