### ISSUE TITLE
pub.dev website does not load

### ISSUE THREAD

**Issue by Geperson** [dart-lang/pub-dev#2827]
URL: https://pub.dev/ does not load on my PC and IPAD on ip 178.134.62.108. I tried to switch on LTE and it's OK. Looks like IP blocked. In he same device website does not load in Firefox, Chrome, IE when I use wi-fi and works when I switc to LTE/GPRS.
Could you help me?

**Comment by isoos** [comment]
@Geperson: in Nigeria people have found that their access depends on their Internet Service Provider (ISP). Please check this thread if the same may apply to you too: #1767

Unfortunately, if the ISP mishandles the IP routes, we can't really do much about it. To have a quick test on this, please check which of the hosts here you are able to reach any:
https://github.com/dart-lang/pub-dev/issues/1767#issuecomment-442493817

**Comment by Geperson** [comment]
Thanks isoos

> Can you please report if you can reach the following sites?
> 
> https://dartlang-pub.appspot.com/ (FYI: this is the same site as pub.dartlang.org)
> https://www.dartlang.org/
> https://dartpad.dartlang.org/
> https://news.dartlang.org/
> (I'm just trying to rule out some cases.)

I have access to all of this websites. My provider's support says the they have the same problem: website pub.dev does not load. They checking the reason now.

https://dartlang-pub.appspot.com looks like pub.dev. Is this a mirror?

**Comment by jonasfj** [comment]
> https://dartlang-pub.appspot.com looks like pub.dev. Is this a mirror?

For now, but we will likely redirect it soon.

**Comment by mit-mit** [comment]
Closing as unactionable on our end.

**Comment by henryadebayo** [comment]
pub.dev is not loading up in Nigeria i always use a vpn to access pub.dev which i'm really not comfortable with please fix it

**Comment by isoos** [comment]
@henryadebayo: what ISP and what kind of setup (OS, firewall, antivirus) are you using?

We have a script that can further help you debug the core issue, please download and run it, report back the output of the script:
https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart

Also, please, next time open a new issue for this.

**Comment by emmanueledem** [comment]
please fix it soon

**Comment by isoos** [comment]
@emmanueledem: the site works for me right now. What ISP and what kind of setup (OS, firewall, antivirus) are you using?

**Comment by JudeOchalifu** [comment]
In Nigeria, switching from 9Mobile to MTN works.

**Comment by Goddy101** [comment]
Thank you all for your responses and contributions. I found everyone of them helpful.

**Comment by klaus139** [comment]
pub.dev is not working, what settings do I have to change on my mac to get it to work
