### ISSUE TITLE
fatal-error #import <cloud_firestore/CloudFirestorePlugin.h>

### ISSUE THREAD

**Issue by zlindaz2411** [dart-lang/pub-dev#2828]
URL: https://pub.dev/packages/cloud_firestore#-installing-tab-

'cloud_firestore/CloudFirestorePlugin.h' file not found
    #import <cloud_firestore/CloudFirestorePlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

How can I solve this? I just added the dependency: cloud_firestore: ^0.12.9+4 and this happened

**Comment by jonasfj** [comment]
@zlindaz2411, this is the issue tracker for `pub.dev` we host packages, we do not maintain the packages on the website.

You'll probably want to report this here: https://github.com/FirebaseExtended/flutterfire

Seems like maybe you're missing some Flutter setup.
