### ISSUE TITLE
Ensure migration to v1 metadata endpoint

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2832]
> Warning: The v0.1 metadata server endpoint is deprecated and scheduled for shutdown.

See: https://cloud.google.com/compute/docs/migrating-from-0.1-to-v1-metadata-server

Based on emails, it seems something is using an old metadata server interface. My guess would be:
 * `package:appengine`
 * `package:gcloud`
 * `package:grpc`

I think these are the only packages we have that uses the metadata service.

**Comment by isoos** [comment]
We may use it from here:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/service/entrypoint/frontend.dart#L102

**Comment by jonasfj** [comment]
hmm, this might be in `googleapis_auth`, which has [`_DEFAULT_METADATA_HOST = "metadata"`](https://github.com/dart-lang/googleapis_auth/blob/5bb42ae16d43c8c701e709125a3729bdfab61f03/lib/src/oauth2_flows/metadata_server.dart#L26), I don't know why, but I would expect `metadata.google.internal`. Otherwise, it looks as if it's hitting the `v1/` API.

**Comment by jonasfj** [comment]
Note. we should investigate this and try out it out on the staging site with:
`gcloud compute project-info add-metadata --metadata disable-legacy-endpoints=TRUE`

I think deadline is early January.

**Comment by jonasfj** [comment]
Note. to self, this could also be happening in our popularity analysis job..

**Comment by isoos** [comment]
This has been done.
