### ISSUE TITLE
Not sure what happened but here it is.

### ISSUE THREAD

**Issue by w4ll3** [dart-lang/pub-dev#2836]
Requested URL: https://pub.dev/packages?sort=created&page=16
Request ID: a14a34860528e52cb81b80c1f0c17250

**Comment by isoos** [comment]
Based on the logs this is the same issue as #2823, probably because `flutter_push_notification` was removed (#2820). #2823 was not deployed yet.

**Comment by mit-mit** [comment]
Closing as we deployed. Let us know if this repros again.
