### ISSUE TITLE
Request to delete

### ISSUE THREAD

**Issue by marquesinijatinha** [dart-lang/pub-dev#2844]
I need to delete the version 3.0.0 of this package
it was wrongly changed in a pull request
https://pub.dev/packages/bungie_api

I also need to delete this package entirely
https://pub.dev/packages/bungie_api_dart

Thanks

**Comment by jonasfj** [comment]
Sent email requesting confirmation.

Also suggesting that maybe we flag `bungie_api_dart` package as discontinued instead, as this is less disruptive.

And suggesting that you retain `bungie_api` version 3.0.0, it was published a long time ago, and users might already be depending on this package.

**Comment by marquesinijatinha** [comment]
This package is an wrapper for an API that I have no control over. The
version number reflects the API version, which is 2.4.0 right now. I will
need to use the 3.0.0 version sometime as the API evolves.

**Comment by marquesinijatinha** [comment]
Also, about flagging bungie_api_dart as discontinued, how do I do that?

**Comment by jonasfj** [comment]
> I will need to use the 3.0.0 version sometime as the API evolves.

But what about the developers who have already taken dependency upon `3.0.0`.
That's why I would suggest bumping the version number to `3.x` and continue from there.

**Comment by jonasfj** [comment]
I've flagged `bungie_api_dart` as discontinued (in the future you'll be able to change this state, just haven't shipped controls for it yet).

But after detail review of moderation policy it's clear that removing `bungie_api` version `3.0.0` is outside our moderation policy. It is less disruptive to users if you publish version `4.0.0` and continue from there.
