### ISSUE TITLE
`dart:` is not a qualifier

### ISSUE THREAD

**Issue by jayoung-lee** [dart-lang/pub-dev#2845]
When I search for `dart:js` on pub.dev, it says `Your query contains an unsupported qualifier. Check the supported search qualifiers.` although `dart:js` is a valid library name. 

It thinks that `dart:` is a qualifier just like `dependency:`.

**Comment by lrhn** [comment]
I'm not personally against considering `dart:js` an invalid qualifier (if it's easier), the error message is also shown for `"dart:js"`, which should be treated as an exact phrase and not a qualifier.
