### ISSUE TITLE
Remove 3 packages

### ISSUE THREAD

**Issue by matthew-carroll** [dart-lang/pub-dev#2853]
Hi,

I'd like to have the following packages taken down from pub for IP reasons:

https://pub.dev/packages/fluttery
https://pub.dev/packages/fluttery_audio
https://pub.dev/packages/fluttery_seekbar

**Comment by jonasfj** [comment]
Packages removed.

**Comment by kafein** [comment]
Hi @matthew-carroll

Why do you remove these packages? Also i need your youtube videos :(

**Comment by radyoof** [comment]
bana yollarmısın Fluttery_seekbar_0.0.1
