### ISSUE TITLE
pub website crashed when searching

### ISSUE THREAD

**Issue by nbros** [dart-lang/pub-dev#2854]
![image](https://user-images.githubusercontent.com/141089/66201850-94facc00-e6a4-11e9-9379-3727ad845456.png)

Requested URL: https://pub.dev/flutter/packages?q=audio
Request ID: 2074a4a06facfc86e105a6ecee968910

**Comment by isoos** [comment]
Based on the logs this is the same issue as #2823, probably because packages were removed (#2853 and ). #2823 was not deployed yet.

**Comment by isoos** [comment]
#2823 was deployed
