### ISSUE TITLE
ERR: The current Dart SDK version is 2.4.0

### ISSUE THREAD

**Issue by cedx** [dart-lang/pub-dev#2861]
I'm not sure if this issue is already reported...
The latest SDK version is still not enabled on Pub website: every package that targets the SDK 2.5.0 and above has the following error in its analysis:

`ERR: The current Dart SDK version is 2.4.0`

**Comment by jonasfj** [comment]
Sorry, we rolled back to previous version due to a minor fluke in search.. we'll get 2.5 online again early next week.

**Comment by jonasfj** [comment]
I switched traffic back...
