### ISSUE TITLE
Reuse package name

### ISSUE THREAD

**Issue by leisim** [dart-lang/pub-dev#2862]
I'm working on a package for which the perfect name would be `dartx`. Unfortunately this name is already taken.

The `dartx` package on pub.dev is incompatible with Dart 2 and has not been updated for over two years. No other packages depend on it and it cannot be found via search.

I contacted the owner and he is allowing me to publish my package instead.

Would you say it is a bad idea to replace an existing package with a new one? What is the recommended way of doing this?

**Comment by jonasfj** [comment]
Ask the existing owner to add you as uploader. Then you can remove the original uploader and publish your code as a new major version.

You'll still have the old dart 1.x releases in your history, but this also means that users of the package won't be broken.

---

We're working on a policy for this. But ideally this is how it would work.

**Comment by isoos** [comment]
Relevant part on the policy page: https://pub.dev/policy#name-squatting
