### ISSUE TITLE
Official package recognition

### ISSUE THREAD

**Issue by nicovak** [dart-lang/pub-dev#2865]
Hello

I'm asking if there is any way to differentiate official packages from google and community ones. 

Actually we have **Flutter** / **Web** / **All**

Maybe we could have a second level to filter _official_ package or adding an other way to have the information.

**Comment by mit-mit** [comment]
How would you define "official" here?

**Comment by nicovak** [comment]
The "verified" system has been added some times ago, my issue should be closed. Official for me was a way to know If a package has been published by the Flutter Team. Now we can have the information.
