### ISSUE TITLE
Support third-level domains in verified publishers

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#2905]
The new verified publishers feature only supports second-level domains (e.g. foo.org). This tracks a request to support third-level domains (e.g. foo.co.uk).

**Comment by mit-mit** [comment]
One concrete suggestion was to use the ICANN domains list in:
https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat#L10 (from https://publicsuffix.org/)

**Comment by isoos** [comment]
I think we may want to have some protective design around the wrapping and displaying the long domain names, but other than that, we could enable more levels.

**Comment by jonasfj** [comment]
Okay, talking about this we reach consensus that we allow arbitrary sub-domains, and limit the publisherId to 64 characters.

**Comment by mit-mit** [comment]
Please make sure the id length limitation and our templates is aligned. 64 chars looks very odd right now:

![Screenshot 2019-10-23 at 13 52 33](https://user-images.githubusercontent.com/13644170/67390207-7b122200-f59c-11e9-902d-7311d219bdbd.png)

**Comment by jonasfj** [comment]
note. we already support 53 + extension length, so that's already a problem -- a different issue though :)

**Comment by isoos** [comment]
Displaying long publisher names seems to be about the following choices:
- we either wrap the long name into multiple lines, or
- we hide the overflow part of the name and keep it in a single line

As the name is a sign of trust, I think it would be better to wrap the name into multiple lines. wdyt?

**Comment by jonasfj** [comment]
Wrap would be ideal... If we can do `max-width: 32ex` so there can be at-least 32 chars on the first line.

**Comment by isoos** [comment]
I think this is done.
