### ISSUE TITLE
pub.dev login flow/text issues

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/pub-dev#2909]
If I log in to pub.dev and then log out and then click **Login** again, I don't get a choice of identities to sign in as, and I still see **Login**.

However, the login did apparently work: If I reload the page, I see my face (as the original identity I signed in as).

Also, to conform to Google standards (e.g. see google.dev):
* **Login** -> **Sign in**
* **Log out** -> **Sign out**

**Comment by jonasfj** [comment]
Hmm, interesting, if signed in to multiple accounts in the same browser, you do get the account selector.

We probably have to force account selection whenever you sign-in:
https://developers.google.com/identity/sign-in/web/reference#gapiauth2signinoptions
