### ISSUE TITLE
Cannot add custom email as a member of the a verified package publisher

### ISSUE THREAD

**Issue by joshuadeguzman** [dart-lang/pub-dev#2914]
**UPDATE**
Apparently, pub.dev identifies my custom email, which is added as a secondary email on my gmail account, same with email I used for the invitation. Is allowing custom emails on top of Gmail accounts, part of the roadmap for the authentication?

**Problem**
I'm trying to add an email, take note this email is not registered in a GSuite subscription. Is this some sort of limitation when we try to add members with custom emails?

**Attachment**
Error
![Screen Shot 2019-10-11 at 11 01 52 AM](https://user-images.githubusercontent.com/20706361/66621382-8cf7da80-ec16-11e9-8081-d781c3c069a4.png)

Publisher Page
https://pub.dev/publishers/flutter.ph/packages

**Comment by isoos** [comment]
@joshuadeguzman: you need to be logged in with the other account to see and accept the consent request. If you can log in as that e-mail to the site, then you'll able to see and accept the consent.

**Comment by joshuadeguzman** [comment]
Hi @isoos, yup. I'm aware, unfortunately I was trying to add a custom email, which happens to be a secondary email on my Gmail account (which is the one used for the invitation link).

Is there by any chance pub.dev supporting manual signing up of emails other than Gmail auth?

**Comment by jonasfj** [comment]
For contact email we probably just need to verify that the email works. I think we want this at some point.

It's often convenient to use a private mailing list as contact email.

**Comment by joshuadeguzman** [comment]
Great, thanks for considering it!

**Comment by frank06** [comment]
> Is there by any chance pub.dev supporting manual signing up of emails other than Gmail auth?

I also would like to know this. I do not have a Gmail account.

**Comment by jonasfj** [comment]
> I also would like to know this. I do not have a Gmail account.

You do not need a gmail account, you do need a google account (you can use a non-gmail email to create a google account -- afaik you do not need to sign-up for gmail).

Using an email that is not a Google account as contact email might be supported in the future.
Ie. using a private mailinglist would often make sense.

Using a non-Google account as user account will probably never be supported. We have requirements that user-data be mapped to user_ids and that we remove such user-data when accounts are deleted. For pub.dev we don't remove published packages, but we do remove any user settings (more of which will be introduced in the future). Besides I don't think it would be desirable to re-implement password recovery, support, 2FA, U2F, etc for pub.dev when we instead rely on the many security features available through regular Google accounts.

**Comment by jonasfj** [comment]
> Is allowing custom emails on top of Gmail accounts, part of the roadmap for the authentication?

No, I think we'll always use the primary associated with your Google account. But you can create a Google account using a custom email. You just can't change the primary email, if it's a gmail.

**Comment by frank06** [comment]
@jonasfj  I prefer not to have a Google account. Why not support at least one other provider like Github?  Is this a technical restriction or policy?

**Comment by jonasfj** [comment]
@frank06, this is getting off-topic for this issue which pertains to "contact email".
While I suspect we could -- I haven't tested it by trying to do the privacy review :)

Mostly I think we should invest our time and energy in other features that delivers more value. Improving search results, hardening security, performance improvements, improving UI on the site, and many more things. Adding further account-linking options won't make much difference. If anything, adding more complexity around account management just increases the risk of a security vulnerability (or privacy concern).

Finally, if someday a malicious packages was published from a compromised account, I think our internal security team would be delighted to help investigate such an incident.

**Comment by frank06** [comment]
@jonasfj  Very small startups routinely offer multiple sign in providers, this is almost standard practice.

> Finally, if someday a malicious packages was published from a compromised account, I think our internal security team would be delighted to help investigate such an incident.

It's like saying the police should have access to all your conversations in case one day you commit a crime.

I don't think it's right for an open source repository to require a Google account to contribute. But I'm not funding the project so I guess I will shut up now.

Anyway, it's all good. I hope one day you will consider alternative sign in methods.

**Comment by jonasfj** [comment]
> It's like saying the police should have access to all your conversations in case one day you commit a crime.

No, that is not what I meant. I think that upon request for help from a user, the security team might be able to help with correlating access logs. See [privacy policy](https://policies.google.com/privacy?hl=en) for more information. I'm concerned anything I say can be misunderstood.

In any event, this was off topic :)
