### ISSUE TITLE
Is it possible to remove a publisher from "My Publishers"?

### ISSUE THREAD

**Issue by felangel** [dart-lang/pub-dev#2925]
Is it possible to delete/remove a publisher from the "My Publishers" section in pub.dev?https://pub.dev/publishers/{publisher}/admin

**Comment by jonasfj** [comment]
You can have someone else remove "you" as member from the publisher. I still don't think we allow removing yourself from a publisher.

I'm not convinced we should allow publisher deletion, last we discussed it we aimed at marking a publisher as "abandon".

Curious, what is the concern?

**Comment by felangel** [comment]
I verified multiple domains and plan on only using one so I was just wondering if I could delete the unused one to avoid confusion as well as to free the name in case someone else wanted to  use it later.

**Comment by jonasfj** [comment]
I think that like package names, it's perhaps best if publisher ids can't be reused. 

>... to free the name in case someone else wanted to use it later.

This is not a huge problem since you have to buy the domain. And if you transfer to domain to someone else you can also transfer the publisher to them (invited them and have them remove you).

If you just let the domain registration expire, then I don't know -- I imagine sketchy domain sharks might try to claim it.

**Comment by felangel** [comment]
So if the domain expires and someone else buys it can they take the publisher? Or do you have to explicitly transfer the publisher over even if you no longer own the domain?

**Comment by jonasfj** [comment]
> So if the domain expires and someone else buys it can they take the publisher?

As of writing the publisher must be explicitly transferred. I think this is best.

Think of it as a trust-on-first-use scheme :)

Maybe if the publisher had no members and no packages we could allow owners to take over the publisher, but I doubt this is going to be necessary. People are good at coming up with clever domain names.

**Comment by felangel** [comment]
Sounds good! Thanks for the clarification 👍
