### ISSUE TITLE
Can't sign-in to pub.dev

### ISSUE THREAD

**Issue by Blaxou** [dart-lang/pub-dev#2929]
It seems I can't sign-in to pub.dev, when I click the button to do so, the Google login popup pops up, I then choose the account I want to sign-in with, the popup closes, and nothing at all happens.

### What I tried so far : 

- Refreshing the page
- Disabling my AdBlocker

**EDIT** : This bug is most likely because Google Chrome Dev breaks something in the login flow

**Comment by isoos** [comment]
@Blaxou can you give us some more information about your environment (OS, browser, plugins)? Does the same happen if you try it in the Chrome Guest mode window?

**Comment by Blaxou** [comment]
@isoos Yeah my bad way kind of tired, here are the full specs :
**OS** : `Windows 10`
**Browser** : `Chrome 79.0.3941.4 (Official Build) dev (64-bit)`
**Plugins** : Can't login on the site globally
**Guest mode** : Also happens

**Comment by jonasfj** [comment]
Yeah, I noticed those warnings in the console. We should investigate this further, I suspect it's a cookie created by the sign-in flow which causes this.

**Comment by hterkelsen** [comment]
I'm hitting this too. I couldn't log in in Incognito mode either. Using "Google Chrome (beta)" I was able to log in.

**Comment by jonasfj** [comment]
I have no problems logging in on Linux with `Version 79.0.3941.4 (Official Build) dev (64-bit)`.

Please list browser version, OS and extensions you have installed.

**Comment by Blaxou** [comment]
@jonasfj Not sure who you're talking to, but if it's me, I listed all of my specs in my last comment

**Comment by jonasfj** [comment]
Ah, no extensions in incognito mode, sorry I missed that.

@Blaxou, Have you tried to sign-in with google on other sites? does that work in Chrome dev?

----

Reading https://developers.google.com/identity/sign-in/web/reference#gapiauth2clientconfig
I'm wondering if `cookie_policy: single_host_origin` is a fix, but that seems oddly specific...

I have no solution right now... We probably need to setup a window environment to test this.

**Comment by Blaxou** [comment]
@jonasfj I didn't specifically tried but I could login to any of the Google services without any problems, I'm not really sure but as it seems to be a cookie issue your fix might work ? (Not really aware of how cookies and all work)

**Comment by szakarias** [comment]
Feel free to reopen if this is still an issue.

**Comment by hterkelsen** [comment]
I still see the issue on [pub.dev]() and other sites with Google sign-in, but I was able to resolve them by going to `chrome://flags` and turning off `Experimental Web Platform features`

**Comment by jonasfj** [comment]
@Blaxou, we deployed some changes that improved the login flow, fixing a few corner cases. Are you still experiencing issue with Google sign-in on `pub.dev`?

@hterkelsen, okay, that sounds like an experimental feature, that's not enabled by default.

If anyone experiences problems with sign-on on `pub.dev` we're very curious to know about it. But at this point, we hope we fixed the bugs.

**Comment by imamtarique** [comment]
Still cant login. 
I am using Firefox 81.0 on iMac.

**Comment by isoos** [comment]
@imamtarique: What's you ISP/VPN/local network setup? Are you using any plugins, content blockers or strict cookie handling? I've just tried with a default Firefox 81.0 on a Macbook - no plugins or content blockers, and it was working.

**Comment by ghostpirate** [comment]
I had the same problem with sign-in. Disabling privacy badger extension solved the issue.
