### ISSUE TITLE
Remove package version

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/pub-dev#2933]
Could someone please help me remove this version of a  package I published as I forgot to remove an API key? It's inconsequential on my end, but it's not a good look :)
https://pub.dev/packages/fonoapi_dart/versions/0.1.2

**Comment by jonasfj** [comment]
Sent an email for confirmation.

**Comment by jonasfj** [comment]
Request confirmed.

**Comment by jonasfj** [comment]
Package version removed.
