### ISSUE TITLE
Add support for banner ads/announcements to pub.dev

### ISSUE THREAD

**Issue by athomas** [dart-lang/pub-dev#2936]
dart.dev currently advertises the new publishers feature:
![image](https://user-images.githubusercontent.com/19993735/67286634-08407280-f4da-11e9-9768-1336d288d867.png)

It would be nice if we can advertise new pub features, or have other announcements (e.g. something that points you at an NNBD package migration guide) on pub.dev as well.

**Comment by jonasfj** [comment]
Only on the frontpage, but yes it would be nice.

**Comment by isoos** [comment]
> Only on the frontpage, but yes it would be nice.

dart.dev puts it on all (most) of the pages, and I think it makes sense if people are opening bookmarked pages. A few parameters that further influence the design:

- Would the user dismiss it and we'll never show it again? (would it be stored in a cookie or in the user session)

- Should it be part of the page (scroll out) or should it be sticky (on scroll out stays on top) or always-floating (displayed separately from the row)?

- Would it be always bound to a new release version (e.g. hard-coded in the app), or configured externally (e.g. HTML comes from Datastore)?

**Comment by mit-mit** [comment]
For simplicity, I would make it on all pages, non-dismissable, but have it scroll out of view. And would be nice if changing it was a configuration option somehow and unrelated to deployments.
