### ISSUE TITLE
Feature: Dart SDK version in version tab

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/pub-dev#2940]
For example after a column with a version: dart minimum sdk version

**Comment by jonasfj** [comment]
Are you looking for the required Dart SDK version, I think that's in the analysis tab:

![Rdyg0p0aYtP](https://user-images.githubusercontent.com/149732/67775164-cf1a7c00-fa5e-11e9-942a-3ef579dcada5.png)

**Comment by ykmnkmi** [comment]
yes, but looking for half of all versions is little much

**Comment by isoos** [comment]
@ykmnkmi: Could you please describe your high-level use case for this feature request? What kind of decision are you trying to support with it? Maybe we should address this question in the `pub` client tool or other way...

**Comment by ykmnkmi** [comment]
@isoos 
![versions](https://user-images.githubusercontent.com/53435297/72979360-5bd89a00-3e02-11ea-87bf-3d372cdf2fac.png)
or horizontal delimeter when sdk version changed.
When NNDB comes, it will be easier to see which version packages support this feature.

_ps: sorry for grammar, non-native english user_

**Comment by isoos** [comment]
This has been implemented, and we are listing the minimum Dart SDK version on the versions page.
