### ISSUE TITLE
A weird letter n

### ISSUE THREAD

**Issue by Larry-Liu2016** [dart-lang/pub-dev#2947]
URL: https://pub.dev/

<Describe your issue or suggestion here>
![Screenshot_20191024-232017](https://user-images.githubusercontent.com/25881407/67485061-11396b80-f6b5-11e9-87de-bfdda7fa60c4.jpg)

**Comment by isoos** [comment]
Yeah, that's the broken login menu on mobile. Should be fixed via #2938. We'll probably deploy it next week.
