### ISSUE TITLE
Example tab should link to source

### ISSUE THREAD

**Issue by filiph** [dart-lang/pub-dev#2957]
URL: https://pub.dev/packages/path_provider#-example-tab-

I like how, when you have an `example/example.dart` file, its contents are immediately rendered in the Example tab on pub.dev. But many packages and plugins nowadays use the approach of having an app, not a single file, in `example/`.

This means that the example tab will often show the contents of the README in `example`, which is not helpful at all.

I think the logic should be the following:

* Do we have a single `.dart` file to show in `example`? Show it.
* In all other cases, try to link to the source. I.e. for most packages, that would be the github link to `example`.
* If there happens to be a README in `example`, show the contents below the link to the source.

**Comment by sigurdm** [comment]
This would be nice. Only slight issue is that we cannot link to the exact commit.

**Comment by isoos** [comment]
> Only slight issue is that we cannot link to the exact commit.

There are a few more failure cases there: git history can get rewritten (the specific commit will be gone), repository can be deleted... I think for now it is already an improvement to link to the file in the repo, and if we want to be pedantic about it, we might just serve the uploaded file in an archive browser.

**Comment by isoos** [comment]
#2963 is not the final solution yet, as in case of [`path_provider`](https://github.com/flutter/plugins/blob/master/packages/path_provider/pubspec.yaml), the `homepage` is the specific URL, the `repository` is derived, and we are using the later as the `baseUrl` in the code. I'll need to review a few examples if it is better to ignore the repository if it was derived.
