### ISSUE TITLE
Access-Control-Allow-Origin for the API endpoints

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/pub-dev#2958]
I've created a static Flutter Web App for bookmarking pub.dev packages (https://github.com/modulovalue/dart_pub_package_watcher).
I'd like to use the pub.dev API via [pub_client](https://github.com/jimsimon/pub_client) to receive the author, homepage and so on.

I was stopped by:

```
Access to XMLHttpRequest at 'https://pub.dartlang.org/api/packages/test' from origin 'http://localhost:51764' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
:51764/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:32476 XMLHttpRequest error.
:51764/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:32476 ClientException
```

Are there are any security issues or other implications that would make an 'Access-Control-Allow-Origin: *' header a bad idea for the API endpoints?

I'd like to ask for that header in pub.dev API responses if that's possible.

**Comment by jonasfj** [comment]
> Are there are any security issues or other implications that would make an 'Access-Control-Allow-Origin: *' header a bad idea for the API endpoints?

Not really, my only concern is the complexity it adds to the surface of our service. As we do have some handlers that rely on cookies, it'll require more diligence if we open up to CORS requests.

If there is a huge demand for this we can consider it.

Have you considered doing a simple CORS proxy on cloud run?

**Comment by modulovalue** [comment]
> Have you considered doing a simple CORS proxy on cloud run?

If possible, I'd like to just run it as a GitHub page for the community without having to worry about or monitor the traffic.

I think there are quite a few interesting use-cases and the community would also greatly benefit from having an API for experimentation and demonstration purposes that is easy to understand, useful, and works across all platforms (now that Flutter Web is somewhat ""stable enough"").

> my only concern is the complexity it adds to the surface of our service.

I can't really assess the potential complexity so feel free to just close this issue if you think it's not worth it.

**Comment by Kleak** [comment]
I would also like to have the possibility to acces pub.dev api endpoint from the web.
I'm working on a project that have easy search across https://api.dart.dev, https://api.flutter.dev and https://pub.dev with some short keyword to filter one or the other.

In the case the pub api is accessible from the web i would be capable to suggest package from what they have search.

The website is here if you want to try : https://flome.kleak.dev/

**Comment by Rexios80** [comment]
Here is a Caddy proxy I set up for reference: https://github.com/Rexios80/pub_stats/tree/92773bd5e43bc150be59d43be5973017d343e233/proxy

It was a royal pain to get working so hopefully this helps someone
