### ISSUE TITLE
Log in does not refresh page if I have two tabs

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#2988]
In an incognito window I open a tab and log into pub.dev
I open `pub.dev` in another tab, click "sign out", and log in again.
I still see the "log-in" instead of my avatar.
Refreshing the page shows that I'm logged in.

**Comment by isoos** [comment]
I think this may be related to our double-checking of the sign-in and sign-out: we reload the page only if the second request does not change the status. However, that logic is the server-centric view of the client state, and maybe we should rather use a client-based state check.

**Comment by jonasfj** [comment]
> I think this may be related to our double-checking of the sign-in and sign-out.

I thought so too.. but it still didn't add up. If you're signed in on multiple tabs, and you sign-out, then you get signed-out on all tabs. So how does the session survive.

**Comment by rhalff** [comment]
For me sign in doesn't work at all, the authentication through google is successful but there is no visible change in sign in status. Clearing session and local storage also doesn't help.

**Comment by isoos** [comment]
@rhalff: What browser/platform are you using? Do you have extensions (e.g. adblocker / privacy protection)?

**Comment by rhalff** [comment]
Ah, yes I am, I've just tried to login with Firefox and it does work. Will try to find out what extension in chrome is causing this. Thanks!

**Comment by jonasfj** [comment]
@rhalff does sign-in with Google work on other websites in Chrome?

**Comment by rhalff** [comment]
I've disabled my extensions and tried signing out of a site also using google sign-in and couldn't get back in, perhaps it's due to the chromium version I'm using. So I guess this is not related to pub.dev nor this particular issue, sorry :)

**Comment by jonasfj** [comment]
@rhalff check `chrome://flags` maybe you've enabled something experimental.

**Comment by sigurdm** [comment]
With the new login-flow this might still happen.

**Comment by sigurdm** [comment]
I cannot reproduce this.

Probably stale?

**Comment by isoos** [comment]
I don't think we actively poll and refresh the pages on tabs when one them gets signed in... but I don't think we should either, so maybe close this? (The previous behavior was more of a side-effect of the js-based sign in we were using)

**Comment by sigurdm** [comment]
Let's close and open a new issue if we find similar problems!
