### ISSUE TITLE
Links generated in the "Example" tab are incorrect

### ISSUE THREAD

**Issue by mklim** [dart-lang/pub-dev#3003]
URL: https://pub.dev/packages/android_alarm_manager#-example-tab-

This is pulling the `packages/android_alarm_manager/example/README.md` and attempting to link back to it, but the link is broken. So users who see this page are stuck with a mostly empty README and no clear way to find the actual example app.

- Expected link: https://github.com/flutter/plugins/blob/master/packages/android_alarm_manager/example/README.md
- Actual link: https://github.com/flutter/plugins/blob/master/example/README.md

I expect that the problem has something to do with `android_alarm_manager` being in a subdirectory of the `flutter/plugins` repo, instead of a top level folder in its own repo.

This appears to be impacting all of the `flutter/plugins` packages.

/cc @csells

**Comment by isoos** [comment]
Thanks for reporting this! Similar issue: #2957, pending PR: #2999.

**Comment by mklim** [comment]
Thanks for the quick fix!
