### ISSUE TITLE
Consider replacing 'installation' tab with an 'AUTHORS' tab

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3008]
Installation 'tab' does have much useful information, maybe we should do an `AUTHORS` tab instead that renders the contents of the `AUTHORS(.md)?` file from package.

**Comment by isoos** [comment]
Why not have both?
- I'd rather replace /extend the current tab with `INSTALL.md` or the `#setup`/`#install` section from the `README.md`.
- And we could also display the authors file if present.

**Comment by mit-mit** [comment]
Let's split this issue into two: 1) add authors info, 2) remove/redesign install

**Comment by jonasfj** [comment]
Filed https://github.com/dart-lang/pub-dev/issues/3009.
