### ISSUE TITLE
Remove a package, please

### ISSUE THREAD

**Issue by Den163** [dart-lang/pub-dev#3029]
Have a good day! I'm new to the flutter and dart community, so when I publish my first package I did some mistakes. I want to publish my package again with a new name. Can you delete my package from the pub search, please? It's https://pub.dev/packages/veider

**Comment by Den163** [comment]
And I have another problem. When I try to publish next version, there is an error 'InsufficientPermissions: Insufficient permissions to upload new versions of package `vader`..'

**Comment by sigurdm** [comment]
Package vader seems to exist already: https://pub.dev/packages/vader

**Comment by Den163** [comment]
Very thanks for help. But can you remove the package from a search index?

**Comment by sigurdm** [comment]
Sure - I have sent a confirmation request to the uploader. Please respond to that, and I will delete the package.

**Comment by sigurdm** [comment]
Confirmation received. Package removed. It might still be in the caches for a short while.

**Comment by eyoeldefare** [comment]
I signed in with different google login and now I get the same error, is it possiable to login again?

**Comment by isoos** [comment]
@eyoeldefare: The credentials are stored in `credentials.json` in your pub cache directory (in Unix/Mac: `~/.pub-cache/credentials.json`. You can remove the file and run login again, or just run `pub logout`.

**Comment by eyoeldefare** [comment]
> 
> 
> @eyoeldefare: The credentials are stored in `credentials.json` in your pub cache directory (in Unix/Mac: `~/.pub-cache/credentials.json`. You can remove the file and run login again, or just run `pub logout`.

Hey yeah, thanks for the help

**Comment by ayazemre** [comment]
@sigurdm I had simillar problems when I first published my library. Is this possible for other libraries? What is the requirement for completely deleting a library from pub.dev? As far as I read on docs it was not possible to delete a package once it is published.

**Comment by sigurdm** [comment]
>What is the requirement for completely deleting a library from pub.dev? 

pub.dev/policy states the general conditions - but basically each case is us estimating the impact on the community.
Any deletion is done manually by the pub.dev operations team.
