### ISSUE TITLE
Migrating ownership without publisher?

### ISSUE THREAD

**Issue by Daegalus** [dart-lang/pub-dev#3030]
I am currently working on moving from a GSuite account to a Personal account. Currently it is yulian@yuvaks.com (yulian@kuncheff.com as an alias) and the new email is yuliankuncheff@gmail.com (which i will alias yulian@kuncheff.com to after the transition).

I have added the new email as an uploader, but I plan to actually remove the entire gsuite account, so everything will be deleted.

Is there a way to migrate ownership from one account to another without using a publisher? Primarily I want the following packages transferred to yuliankuncheff@gmail.com:

* uuid
* otp
* base32
* formler (not urgent as i am going to be marking it as discontinued)

Not sure if there is anything else I need to do to get these moved over.

**Comment by sigurdm** [comment]
To transfer a package from a to b
Add the new email  b to the package using acccount a.
`pub uploader add b`.
Then do `pub logout`.
And do `pub uploader remove a` for the old email using account b.

**Comment by Daegalus** [comment]
My apologies, I thought it didn't work because the packages didn't show up under the "my packages" section of my new email, but it seems it might have just been a caching delay, as they all show up now. Non-issue, and thank you for the step by step anyway.

**Comment by jonasfj** [comment]
Yes, caches are a bit slow at the moment.
