### ISSUE TITLE
Prevent deleted package  versions from being reused

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#3034]
After a package version has been through the manual deletion process (due to eg. accidental publishing of security keys), we should prevent others from ever publishing the same version (and even versions that are semantically equivalent) to it. For example store a tombstone.

If a whole package has been deleted we should probably prevent that name from being used again without special handling by the pub.dev team.

**Comment by jonasfj** [comment]
We can do this by, supporting the `PackageVersion` continues to exist, even though the tarball has been deleted.

We just need to not return it in the list of versions from the API, and remove all the dartdoc and scorecard information... and ideally set a boolean `isRetracted` to mean: that the version has been published, but _retracted_, hence, deleted.

By maintaining the `PackageVersion` and `Package` entities, we ensure that the owner also maintains the name. The owner can later transfer that to someone else, but it can never go away and become available again.

Note. We also need to do tricks to remove the README and other stuff that has been stored in our datastore.

**Comment by jonasfj** [comment]
I realize this is important, but also non-trivial. But we should work up a brief design first. I think the idea outlined above might work. But it could have other downsides, as all the analysis/dartdoc code, etc. needs to understand the `isRetracted` property.

**Comment by isoos** [comment]
This is now done via `Package.deletedVersions`.
