### ISSUE TITLE
"flutter packages pub publish" fails

### ISSUE THREAD

**Issue by ozc** [dart-lang/pub-dev#3037]
I've updated a Flutter package that I've developed long time ago, and made it Dart 2 compatible.

I'm trying to publish it buy using this command

`
flutter packages pub publish
`

I've done the OAuth2 authentication on browser as the command output asked.

On pub.dev site when I login using my Google account, I have access to admin functions of the package and in fact after getting an error I've created a verified publisher, and transferred the package to it, hoping it would solve the problem.

But this leads to another problem.Now even package ownership is shown as the publisher, on package page, it doesn't list the package on publisher's package list.

And I still get this error

```
Looks great! Are you ready to upload your package (y/n)? y
Uploading...
Invalid server response:
{"code":"MissingAuthentication","message":"authenication is required, please add `authorization` header."}

```

https://pub.dev/packages/phonecallstate
https://pub.dev/publishers/plusdt.com/packages

**Comment by isoos** [comment]
> Now even package ownership is shown as the publisher, on package page, it doesn't list the package on publisher's package list.

That part is a known issue, and we are working on it to fix it. The publisher-filtered search lists only the active, Dart-2-compatible packages, and the published version of yours is not Dart-2 compatible. Your package is not lost, it is just not listed in some of the searches, but that should change soon.

> And I still get this error

Could you please create a detailed log with `flutter packages pub publish -v` and upload it here? (Assuming it doesn't contain sensitive information.)

It could also help if you create a new upload and just put the timestamp here, as we'll need more information to narrow this down in the logs.

**Comment by ozc** [comment]
I was just trying to update it to make it Dart2 compatible.

If it helps I've committed and pushed the change. It's just a single line in pubspec.yaml

https://github.com/ozc/flutter-phonecallstate


```
...
IO  : Spawning "tar --format=ustar --create --gzip --directory /Users/ozc/Development/phonecallstate/phonecallstate/. @/dev/stdin" in /Users/ozc/Development/phonecallstate/phonecallstate/.
FINE: Showing confirm message: 
    | Looks great! Are you ready to upload your package

Looks great! Are you ready to upload your package (y/n)? y
FINE: Loading OAuth2 credentials.
FINE: Saving OAuth2 credentials.
IO  : Writing 382 characters to text file /Users/ozc/Development/flutter/.pub-cache/credentials.json.
MSG : Uploading...
IO  : HTTP POST https://accounts.google.com/o/oauth2/token
    | content-type: application/x-www-form-urlencoded; charset=utf-8
    | user-agent: Dart pub 2.6.0-dev.0.0.flutter-1103600280
IO  : HTTP response 200 OK for POST https://accounts.google.com/o/oauth2/token
    | took 0:00:00.409875
    | alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
    | cache-control: private
    | transfer-encoding: chunked
    | date: Tue, 19 Nov 2019 15:21:01 GMT
    | vary: Origin,X-Origin,Referer
    | content-encoding: gzip
    | x-frame-options: SAMEORIGIN
    | content-type: application/json; charset=utf-8
    | x-xss-protection: 0
    | x-content-type-options: nosniff
    | server: ESF
IO  : HTTP GET https://pub.dartlang.org/api/packages/versions/new
    | Accept: application/vnd.pub.v2+json
    | authorization: <censored>
    | user-agent: Dart pub 2.6.0-dev.0.0.flutter-1103600280
IO  : HTTP response 401 Unauthorized for GET https://pub.dartlang.org/api/packages/versions/new
    | took 0:00:00.484703
    | date: Tue, 19 Nov 2019 15:21:01 GMT
    | content-length: 106
    | strict-transport-security: max-age=31536000; preload
    | via: 1.1 google
    | content-type: application/json; charset="utf-8"
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
FINE: Uploading finished (0.968s).
FINE: Saving OAuth2 credentials.
IO  : Writing 383 characters to text file /Users/ozc/Development/flutter/.pub-cache/credentials.json.
ERR : Invalid server response:
    | {"code":"MissingAuthentication","message":"authenication is required, please add `authorization` header."}
FINE: Exception type: ApplicationException
FINE: package:pub/src/utils.dart 571:5            fail
    | package:pub/src/http.dart 322:5             invalidServerResponse
    | package:pub/src/command/lish.dart 150:5     LishCommand._expectField
    | package:pub/src/command/lish.dart 74:21     LishCommand._publish.<fn>.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                  Future.catchError
    | package:pub/src/utils.dart 109:52           captureErrors.<fn>
    | package:stack_trace                         Chain.capture
    | package:pub/src/utils.dart 122:11           captureErrors
    | package:pub/src/command_runner.dart 171:13  PubCommandRunner.runCommand
pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      pubInteractively (package:flutter_tools/src/dart/pub.dart:213:5)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:269:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:553:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)




```

**Comment by ozc** [comment]
I've renamed the flutter/.pub-cache/credentials.json and run `flutter packages pub publish -v` again.

This time, it asked for OAuth again. When I clicked the link and done the login, it uploaded without a problem.

The only problem looks like README.md file was not read on upload.

**Comment by jonasfj** [comment]
hmm, how long time ago was the `flutter/.pub-cache/credentials.json` created? is it more than a year old?

That could plausibly explain it. `pub logout` should have done the trick too.

I'm thinking that the credentials might have been so old that they didn't include the `openid` scope, which we started requiring not that long ago. Hmm, that's interesting.

Maybe we should update our error message for the special case where we don't get an openid user_id, such that the message directs the user to logout and login again.

**Comment by ozc** [comment]
It is not that old. And while trying to upload the update few days ago, when I encountered this error, command line output asked me to OAuth login, with the url.  Then I logged in through the browser. I was being able to access the account from the browser, but the command line failed. I guess it then created the file.

stat on previously renamed credentials.json file gives the creation date as November 11th.


One thing though. That you have mentioned openid scope, I don't know if it's relevant or not, after I've retried uploading "after renaming credentials.json file", command line asked me to OAuth login with the url it provided. I clicked the url (in Android Studio terminal window) and it opened the page in the browser. It gave an 400 or 500 with text about scope missing error. 
I thought terminal window was line wrapping long url, leading to missing parameters, so I've copied the url and pasted to browser address line. Then the command succeeded.

It would be good the command line output give suggestion. Missing authentication error is a bit misleading, given the fact that browser could login.

**Comment by jonasfj** [comment]
The `pub` client authentication is separate from the authentication in the browser. It stores credentials in `credentials.json`.. The error you got from the server was that the `credentials.json` file you were using was not valid credentials -- I'm not sure why that is.

Maybe the `pub` client should reauthenticate if the `credentials.json` is invalid, this seems to be low risk.

**Comment by rmazur** [comment]
Hi,
I also get same error while trying to publish a new package even after a pub logout.
"MissingAuthentication: Authenication is required, please add `authorization` header.."
credentials.json file seems to be fine.
-----------------------------------------------
    | Then click "Allow access".
    | 
    | Waiting for your authorization...
MSG : Authorization received, processing...
IO  : HTTP POST https://accounts.google.com/o/oauth2/token
    | content-type: application/x-www-form-urlencoded; charset=utf-8
    | user-agent: Dart pub 2.7.0
IO  : HTTP response 200 OK for POST https://accounts.google.com/o/oauth2/token
    | took 0:00:00.236578
    | alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
    | cache-control: private
    | transfer-encoding: chunked
    | date: Fri, 14 Feb 2020 20:17:16 GMT
    | vary: Origin,X-Origin,Referer
    | content-encoding: gzip
    | x-frame-options: SAMEORIGIN
    | content-type: application/json; charset=utf-8
    | x-xss-protection: 0
    | x-content-type-options: nosniff
    | server: scaffolding on HTTPServer2
MSG : Successfully authorized.
MSG : Uploading...
IO  : HTTP GET https://pub.dartlang.org/api/packages/versions/new
    | Accept: application/vnd.pub.v2+json
    | authorization: <censored>
    | user-agent: Dart pub 2.7.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/versions/new
    | took 0:00:00.558460
    | transfer-encoding: chunked
    | date: Fri, 14 Feb 2020 20:17:16 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | strict-transport-security: max-age=31536000; preload
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : HTTP POST https://storage.googleapis.com
    | authorization: <censored>
    | content-type: multipart/form-data; boundary=dart-http-boundary-vppadLo58HjQ5v0JXEWTP5-vIhxs8YHQdB5AWXIAbcRmRPgut7-
    | user-agent: Dart pub 2.7.0
IO  : HTTP response 303 See Other for POST https://storage.googleapis.com
    | took 0:00:00.470125
    | alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
    | location: https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e
    | date: Fri, 14 Feb 2020 20:17:17 GMT
    | vary: Origin
    | content-length: 0
    | x-guploader-uploadid: AEnB2UrvYz2qoNChBB_xRnJufJFSi6m9mpvP7qRSTzapyIGsGXZfgffHOdnx3WkBCNQIXMGRljlc6dcBUOY4apaK1EyByHHSKg
    | content-type: text/html; charset=UTF-8
    | server: UploadServer
IO  : HTTP GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e
    | Accept: application/vnd.pub.v2+json
    | authorization: <censored>
    | user-agent: Dart pub 2.7.0
IO  : HTTP response 500 Internal Server Error for GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e
    | took 0:00:00.409397
    | date: Fri, 14 Feb 2020 20:17:17 GMT
    | content-length: 68
    | strict-transport-security: max-age=31536000; preload
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Retry #1 for GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e...
IO  : HTTP GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e
    | Accept: application/vnd.pub.v2+json
    | authorization: <censored>
    | user-agent: Dart pub 2.7.0
IO  : HTTP response 500 Internal Server Error for GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e
    | took 0:00:00.209540
    | date: Fri, 14 Feb 2020 20:17:18 GMT
    | content-length: 111
    | strict-transport-security: max-age=31536000; preload
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Retry #2 for GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e...
IO  : HTTP GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e
    | Accept: application/vnd.pub.v2+json
    | authorization: <censored>
    | user-agent: Dart pub 2.7.0
IO  : HTTP response 500 Internal Server Error for GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e
    | took 0:00:00.255745
    | date: Fri, 14 Feb 2020 20:17:19 GMT
    | content-length: 111
    | strict-transport-security: max-age=31536000; preload
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Retry #3 for GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e...
IO  : HTTP GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e
    | Accept: application/vnd.pub.v2+json
    | authorization: <censored>
    | user-agent: Dart pub 2.7.0
IO  : HTTP response 500 Internal Server Error for GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e
    | took 0:00:00.215080
    | date: Fri, 14 Feb 2020 20:17:21 GMT
    | content-length: 111
    | strict-transport-security: max-age=31536000; preload
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Retry #4 for GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e...
MSG : It looks like pub.dartlang.org is having some trouble.
    | Pub will wait for a while before trying to connect again.
IO  : HTTP GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e
    | Accept: application/vnd.pub.v2+json
    | authorization: <censored>
    | user-agent: Dart pub 2.7.0
IO  : HTTP response 500 Internal Server Error for GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e
    | took 0:00:00.305335
    | date: Fri, 14 Feb 2020 20:17:51 GMT
    | content-length: 111
    | strict-transport-security: max-age=31536000; preload
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Retry #5 for GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e...
IO  : HTTP GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e
    | Accept: application/vnd.pub.v2+json
    | authorization: <censored>
    | user-agent: Dart pub 2.7.0
IO  : HTTP response 500 Internal Server Error for GET https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e
    | took 0:00:00.354310
    | date: Fri, 14 Feb 2020 20:18:21 GMT
    | content-length: 111
    | strict-transport-security: max-age=31536000; preload
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
FINE: Uploading finished (1:05.818s).
FINE: Saving OAuth2 credentials.
IO  : Writing 431 characters to text file /home/regis/flutter/.pub-cache/credentials.json.
ERR : HTTP error 500: Internal Server Error at https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b2bc5c99-3fa2-4659-9fb2-27d85db3d039&bucket=pub-packages&key=tmp/b2bc5c99-3fa2-4659-9fb2-27d85db3d039&etag=d41d8cd98f00b204e9800998ecf8427e.
    | This is likely a transient error. Please try again later.
FINE: Exception type: ApplicationException
FINE: package:pub/src/utils.dart 571:5            fail
    | package:pub/src/http.dart 214:7             _ThrowingClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                  Future.catchError
    | package:pub/src/utils.dart 109:52           captureErrors.<fn>
    | package:stack_trace                         Chain.capture
    | package:pub/src/utils.dart 122:11           captureErrors
    | package:pub/src/command_runner.dart 171:13  PubCommandRunner.runCommand
pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DefaultPub.interactively
(package:flutter_tools/src/dart/pub.dart:323:7)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand
(package:flutter_tools/src/commands/packages.dart:269:15)
#3      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:615:18)
#4      _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:73:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     Future._asyncComplete.<anonymous closure>
(dart:async/future_impl.dart:554:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:175:5)
----------------------------------------------------

Any idea why?

**Comment by isoos** [comment]
@rmazur: what OS are you using?

**Comment by Tokenyet** [comment]
I can't figure out where is the bug on this issue, here is my enviroment and report:

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.592], locale zh-TW)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.41.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

```
It looks like pub.dartlang.org is having some trouble.
Pub will wait for a while before trying to connect again.
HTTP error 500: Internal Server Error at https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=773b0344-a617-43e2-8c69-8e7f4d3b0ddb&bucket=pub-packages&key=tmp/773b0344-a617-43e2-8c69-8e7f4d3b0ddb&etag=d41d8cd98f00b204e9800998ecf8427e.
This is likely a transient error. Please try again later.
[+85169 ms] "flutter publish" took 85,447ms.
pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:323:7)
<asynchronous suspension>
#2      PackagesPublishCommand.runCommand (package:flutter_tools/src/commands/packages.dart:210:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

This is not the first time to publish, but It has been two months for the previous publish. The errors display the same no matter creadentials.json is existed or not, the only difference is OAuth login, and nothing changed.

**Comment by isoos** [comment]
> Edit: look like 7za can't compress? but I'm using admin cmd, can't find where is the problem.

Yeah, looks like it failed for some reason, and the uploaded archive was an empty file on server upload. Not sure why, maybe the `@` in the filenames (should be fine normally, but I have no idea what happens with them on Windows).

**Comment by isoos** [comment]
Closing as we are reporting zero-length archives back to the client properly.
