### ISSUE TITLE
Tapping 'Mark as discontinued' does nothing

### ISSUE THREAD

**Issue by filiph** [dart-lang/pub-dev#3038]
URL: https://pub.dev/packages/slot_machine/admin

* Tapping the button does nothing.
* Nothing gets printed in the console, neither.

Here's the JS console (clicking the button has no effect on it, nothing more gets printed):

<img width="943" alt="Screen Shot 2019-11-17 at 2 21 03 PM" src="https://user-images.githubusercontent.com/919717/69015104-aabb0c80-0945-11ea-8a39-ab8e0e525181.png">

**Comment by isoos** [comment]
@filiph: could you please check the network tab and what kind of requests do you have there?

**Comment by filiph** [comment]
Nothing in the Network tab after initial load. (I.e. tapping the button doesn't send any request, it seems.)

**Comment by isoos** [comment]
I've checked it on a package, and it was working for me (Chrome 78 on Mac). What device / browser / extensions are you using?

When you click on the button, it should show a confirmation dialog. Do you see that? If not, then the event is not reaching the button's handler at all.

**Comment by filiph** [comment]
Hmm, I'm on Chrome Version 78.0.3904.97 (Official Build) (64-bit), also Mac. I do have a bunch of extensions, that is true.

Tapping the button does not show any confirmation dialog.

Tomorrow, I'll try with an incognito window, and if that works, I'll try to triangulate the extension (assuming it's an extension interference).

**Comment by isoos** [comment]
My Chrome version is the same, it is likely it will be an extension. They can also present in incognito, maybe the Guest-user window will be better to confirm it first.

**Comment by jonasfj** [comment]
If it is an extension I think we would be curious to learn which, and see if we can find a way to avoid this issue.

**Comment by filiph** [comment]
I just tried

* in normal window, removing each extension in turn, and then
* in incognito window, no extensions.

No change. Tapping the button still fails to do anything.

I may try clearing cookies but then I think the underlying problem might be harder to assess. I'm in no hurry to mark the package discontinued. Please advise what's the best way forward.

**Comment by jonasfj** [comment]
Just checked it works fine for me in Chrome on Linux. Can you try another browser, maybe?

Note. we're still very curious to find out what's going wrong in your Chrome instance.

**Comment by filiph** [comment]
Firefox has the same issue. I'm including a gif here in case that helps in any way.

![pub-dev-discontinued 2019-11-18 12_11_47](https://user-images.githubusercontent.com/919717/69089136-ad2c6d80-09fc-11ea-9d7a-19dbf294131c.gif)

**Comment by filiph** [comment]
Oh, wait a minute. Going back to the tab in Chrome after a long while, I do get errors:

<img width="1431" alt="Screen Shot 2019-11-18 at 12 14 07 PM" src="https://user-images.githubusercontent.com/919717/69089340-05636f80-09fd-11ea-94f7-37c2b7a2884a.png">

It says `Unchecked runtime.lastError: The message port closed before a response was received.`

**Comment by jonasfj** [comment]
Is there a proxy, anti virus or VPN interfering here? This is certainly curious.

Thanks for all the insights, this is very interesting.

**Comment by isoos** [comment]
The really surprising part is that the button displays the ripple effect => there is JS processing of the event, yet there is no sign of triggering our event handler (which would display the confirm dialog first).

**Comment by filiph** [comment]
@jonasfj I have the regular Googler setup. It didn't work on my home connection and it doesn't work on `Google-A` now.

@isoos Is there a way for me to debug this? E.g. can you send me the source maps?

**Comment by jonasfj** [comment]
If you click inspect on the button, do and look at the event handlers in chrome.. it should have one for click that says `js_helper.dart`, do you have that one?

![bitmap](https://user-images.githubusercontent.com/149732/69151706-6eb9b000-0adb-11ea-88b8-75ff9eebe72b.png)

**Comment by filiph** [comment]
I see two seemingly identical click handlers on the button:

<img width="368" alt="Screen Shot 2019-11-19 at 8 29 45 AM" src="https://user-images.githubusercontent.com/919717/69165666-ce499880-0aa6-11ea-9a8f-bb1401828847.png">

**Comment by jonasfj** [comment]
@isoos, could we be double initializing or something like that? This is certainly curious.

I don't know if this is the same event handler, because `js_helper.dart` is probably some `dart2js` utility that wraps event handlers. This location just says where the function to call is defined, not what variables this closure may have captured.

**Comment by isoos** [comment]
Strange, I have three event listeners there:

<img width="322" alt="Screen Shot 2019-11-20 at 11 11 05" src="https://user-images.githubusercontent.com/4778111/69229846-84d07a80-0b86-11ea-8585-5ea13ab36df2.png">

If I do an extra `console.log` on the event that we receive, it is only displaying a single line, so I don't think we are binding it twice for any reason. The material component may be a second binding (for the ripple effect).

**Comment by isoos** [comment]
I've identified the two click listeners: they are both on the `<body>` element. If you unclick the `Ancestors` checkbox, they go away:
- https://github.com/dart-lang/pub-dev/blob/master/pkg/web_app/lib/src/hoverable.dart#L22
- https://github.com/dart-lang/pub-dev/blob/master/pkg/web_app/lib/src/scroll.dart#L48

Stripping away the material decorations and other styles does not change the local behaviour for me: there is only one registration, on clicking there is only one event.

**Comment by isoos** [comment]
Identified the issue (fix in #3050): @filiph is not a member of a publisher, and with that, the publisher transfer button was missing. We did the event binding only if both buttons were present, due to an earlier version of the page, where the buttons were always present.
