### ISSUE TITLE
Homepage URL doesn't exist?

### ISSUE THREAD

**Issue by lisen87** [dart-lang/pub-dev#3039]
I added a homepage to yaml, and the homepage url (https://github.com/lisen87/image_pickers.git) is accessible, but after the release: At the time of the analysis the homepage field https: //github.com/lisen87/image_pickers.git was unreachable.(-20 points)

**Comment by isoos** [comment]
@lisen87: you are using a GitHub URL that redirects, and the current implementation accepts only non-redirecting homepages:
https://github.com/dart-lang/pana/blob/master/lib/src/download_utils.dart#L201

If you leave out the `.git` suffix next time you publish it, the warning will go away.

I'd like to keep the issue open, as we'll need to consider a few options to investigate and change in the future:
- allow redirects (not sure why we are not allowing it)
- follow redirects (not sure why the http client does not follow them)
- handle `.git`-suffix URLs separately

**Comment by lisen87** [comment]
Thank you for your reply.

**Comment by jonasfj** [comment]
I propose that we follow redirects to see that the "homepage" is redirected to some page that isn't 4xx.

I don't think we should do anything to handle `.git` separately.

------
Note, from a security/transparency perspective I can see that it is tempting to discourage redirects by scoring them lower, as redirects reduces transparency. But:
 * If you refactor your website and maintain permalinks (like a good web citizen would do), then we shouldn't discourage such behavior.
 * If you really want to redirect users to some obscure site that's very different from your `homepage` URL, then you can just use a client-side redirect. Or you can detect who is calling the site, using `User-Agent`, or IP address and server a different response to `pub.dev`. Thus, still redirecting human visitors that open the URL in a web browser.

Hence, I don't think there is any security/transparency reason to discourage redirects.

**Comment by lisen87** [comment]
Hello, I'm a Chinese user. Yesterday, I took out the .git suffix and released it according to the suggestion, which solved the problem. But when I run packages get, I now prompt why: depends on image_pickers ^ 1.0.5 + 2 which doesn't match any versions, version solving failed

**Comment by jonasfj** [comment]
If using a chinese mirror, those could be a bit behind... But I'm also not sure what the issue is?'

Please paste as code fences, I can't tell if you added whitespace between 5 and +2 by accident or..
