### ISSUE TITLE
Dart 1+2 compatible packages being marked as unhealthy

### ISSUE THREAD

**Issue by spebbe** [dart-lang/pub-dev#3055]
Recently, pub.dev started to heavily punish packages that try to stay compatible with Dart 1 by slashing their "Health" score via the "Unnecessary new keyword" check. The new keyword is not at all unnecessary in Dart 1. Could packages that explicitly declare compatibility with both Dart 1 and Dart 2 in the "sdk" section of the pubspec maybe be exempt from this check?

**Comment by isoos** [comment]
@spebbe: I agree, it would be great if explicit Dart 1+2 support would be factored in the analysis and health score, but at the moment I don't think that it would get high priority.

However, until it happens, we allow a self-proclaimed exemption of the linter rules via the following:
https://dart.dev/guides/language/analysis-options#suppressing-rules-for-a-file

Putting the following in the beginning of each file should exempt you from that rule:
```dart
// ignore_for_file: unnecessary_new
```

Note: there is no guarantee that such exemptions will remain in place forever.

**Comment by spebbe** [comment]
@isoos, thanks! I won't be maintaining Dart 1 compatibility forever either, so this sounds like a reasonable workaround for my purposes at least :-)
Closing.
