### ISSUE TITLE
upgrade dartdoc to 0.29.1

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3088]
For better extension type support.

**Comment by jcollins-g** [comment]
Recommend 0.29.2, includes some cosmetic fixes

**Comment by mit-mit** [comment]
@jonasfj this is fixed in the upcoming release, right?

**Comment by jonasfj** [comment]
Yes, this landed in https://github.com/dart-lang/pub-dev/pull/3090
