### ISSUE TITLE
Pub example tab link results in 404

### ISSUE THREAD

**Issue by shihaohong** [dart-lang/pub-dev#3092]
In pub, the `sembast.dart` package's [Example tab](https://pub.dev/packages/sembast#-example-tab-) link to `example/main.dart` results in a 404 error.

Instead of linking to https://github.com/tekartik/sembast.dart/blob/master/example/main.dart, it should link to https://github.com/tekartik/sembast.dart/blob/master/sembast/example/main.dart.

According to https://github.com/tekartik/sembast.dart/issues/100, it seems like this might be an issue for the pub site since the link is generated by the pub server.

**Comment by isoos** [comment]
(added explanations on the issue)

I'd be curios if you see a better way to (a) resolve the URL or (b) specify the deep URL of the package, and also (c) why that package is structured in this way.

**Comment by alextekartik** [comment]
Indeed sembast uses a weird layout. it is not at the top level directory of the github project but in a subdirectory.
Shoud I follow what is done in flutter plugins:
* packages/sembast

I think the project home page and the github folder can not always be the same (but could be both github pages). The github project could contain extra test project, examples...

As a note, many packages have the same issue:
* provider: https://pub.dev/packages/provider#-example-tab-
* shared_preferences: https://pub.dev/packages/shared_preferences#-example-tab-
