### ISSUE TITLE
<Summarize your issues here>

### ISSUE THREAD

**Issue by ranjannisha** [dart-lang/pub-dev#3093]
URL: https://pub.dev/packages/flutter_tex

Hi,
I am not able to make text(latex) clickable for my quiz to submit the correct answer.
Thanks in Advance!!!

**Comment by isoos** [comment]
@ranjannisha: I'm closing this, as this tracker is for issues with the pub.dev site. Please use the package's repository to create package-specific questions: https://github.com/shah-xad/flutter_tex
(You can find it on the package page, on the right-side info box.)
