### ISSUE TITLE
Error: Could not resolve the package 'kernel' in 'package:kernel/util/graph.dart'.

### ISSUE THREAD

**Issue by CodeUXI** [dart-lang/pub-dev#3131]
I get this error when I run 'pub get' when I try to provision required packages after using stagehand-console template

pub get
Resolving dependencies...
+ _fe_analyzer_shared 1.0.1
+ analyzer 0.39.2
+ args 1.5.2
+ async 2.4.0
+ boolean_selector 1.0.5
+ charcode 1.1.2
+ collection 1.14.12
+ convert 2.1.1
+ coverage 0.13.3+3
+ crypto 2.1.4
+ csslib 0.16.1
+ glob 1.2.0
+ html 0.14.0+3
+ http 0.12.0+2
+ http_multi_server 2.1.0
+ http_parser 3.1.3
+ io 0.3.3
+ js 0.6.1+1
+ logging 0.11.3+2
+ matcher 0.12.6
+ meta 1.1.8
+ mime 0.9.6+3
+ multi_server_socket 1.0.2
+ node_interop 1.0.3
+ node_io 1.0.1+2
+ node_preamble 1.4.8
+ package_config 1.1.0
+ package_resolver 1.0.10
+ path 1.6.4
+ pedantic 1.9.0
+ pool 1.4.0
+ pub_semver 1.4.2
+ shelf 0.7.5
+ shelf_packages_handler 1.0.4
+ shelf_static 0.2.8
+ shelf_web_socket 0.2.3
+ source_map_stack_trace 1.1.5
+ source_maps 0.10.8
+ source_span 1.5.5
+ stack_trace 1.9.3
+ stream_channel 2.0.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ test 1.9.4
+ test_api 0.2.11
+ test_core 0.2.15
+ typed_data 1.1.6
+ vm_service 2.1.3
+ watcher 0.9.7+13
+ web_socket_channel 1.1.0
+ yaml 2.2.0
Changed 51 dependencies!
Precompiling executables...
Failed to precompile test:test:
Error: Could not resolve the package 'kernel' in 'package:kernel/util/graph.dart'.
../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart:15:8: Error: Not found: 'package:kernel/util/graph.dart'
import 'package:kernel/util/graph.dart' show Graph, computeStrongComponents;
       ^
../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart:256:39: Error: Type 'Graph' not found.
class _TypeParametersGraph implements Graph<int> {
                                      ^^^^^
../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart:256:39: Error: Expected 0 type arguments.
class _TypeParametersGraph implements Graph<int> {
                                      ^
../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart:125:29: Error: The method 'computeStrongComponents' isn't defined for the class 'DefaultTypesBuilder'.
 - 'DefaultTypesBuilder' is from 'package:analyzer/src/summary2/default_types_builder.dart' ('../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart').
Try correcting the name to the name of an existing method, or defining a method named 'computeStrongComponents'.
    var stronglyConnected = computeStrongComponents(graph);
                            ^^^^^^^^^^^^^^^^^^^^^^^
exit code 0

**Comment by isoos** [comment]
@CodeUXI: Does the problem still exist? Which SDK were you using? Could you please upload the output of `pub get -v`?

**Comment by sigurdm** [comment]
This is issue: https://github.com/dart-lang/sdk/issues/39702 should be solved by now.
