### ISSUE TITLE
Review tags on mobile search UI

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3153]
Maybe we just hide them, or add a line break.
![6YNn8afQykA](https://user-images.githubusercontent.com/149732/70469130-c2ab2980-1ac8-11ea-8127-505dec9eef2b.png)

Not as bad when API results are present:
![O5irEHAK8K2](https://user-images.githubusercontent.com/149732/70469043-9394b800-1ac8-11ea-820f-a90418592a2b.png)

**Comment by theswerd** [comment]
If no contributor is working on this can I take it?

**Comment by isoos** [comment]
@theswerd: thanks for volunteering, it is really appreciated! A status update on this issue:

We are working on a new UI design, and it has been already implemented for package lists. This is the soon-to-be mobile view of tags:

<img width="380" alt="Screen Shot 2020-02-07 at 7 34 13" src="https://user-images.githubusercontent.com/4778111/74006892-4d02f300-497d-11ea-8175-df050c1d1b8e.png">

However, we are not going to deploy the new design until all the UI elements are updated, which could take a few more weeks. As we focus on the new design, we don't spend much time fixing current design's issues. If you still would like to fix this on the current design, I'm happy to review the PR. The file you would need to change is probably this:
https://github.com/dart-lang/pub-dev/blob/master/pkg/web_css/lib/src/_list.scss

**Comment by isoos** [comment]
Closing as we have a new UI which should have fixed the issue.
