### ISSUE TITLE
dartdoc sometimes includes SDK libraries

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3158]
This probably explains why it's slow too :)

![yR1dnqrMwOn](https://user-images.githubusercontent.com/149732/70543730-28e88880-1b6b-11ea-837e-3f6b42c55210.png)

**Comment by isoos** [comment]
Ugh, that strikes again... 
Previously: https://github.com/dart-lang/pub-dev/issues/2108
I don't remember the details, but something embedder SDK-related was not working the way Flutter did its layout, and we have to manually blacklist packages:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/dartdoc/dartdoc_runner.dart#L40-L51
