### ISSUE TITLE
"Bad state: Members must be created from a declarations."

### ISSUE THREAD

**Issue by leisim** [dart-lang/pub-dev#3162]
I have not published a new version for [hive](https://pub.dev/packages/hive#-analysis-tab-) but I'm getting the following error and only a score of 64 (a few hours ago it was 98)

```
Running dartanalyzer. failed with the following output:

Invalid argument(s): dartanalyzer exception: Bad state: Members must be created from a declarations.
```

How can I fix this issue? I don't understand what the error is trying to say.

**Comment by leisim** [comment]
This seems to be a dartanalyzer problem I opened dart-lang/sdk#39752. Should I close this issue?

**Comment by isoos** [comment]
@leisim Thank you for reporting this `dart-lang/sdk`. We won't be able to do much about it until it gets fixed, and once the Dart SDK ships with a fixed `dartanalyzer`, pub.dev will pick it up. Let's close the issue.
