### ISSUE TITLE
Issue in lint error showing

### ISSUE THREAD

**Issue by dharanidharandharmasivam** [dart-lang/pub-dev#3163]
I am having the below-unused field and I need to know what is the lint that I need to use in **analysis_option.yaml** file to detect the unused field.

`final int _padding = 5; `

I know using **unused_field** we can find this. But my concern is, in a single project consider for example I am having two files viz **file1.dart** and **file2.dart** with different classes in each. I have declared the above variable(**_padding**) in file1.dart but never used it any where in the file1.dart and also declared the same variable(**_padding**) in file2.dart and I have used the variable. In this case, in the file1.dart, it has to show lint error i.e **The value of the field '_padding' isn't used**. But it isn't showing in this case.

And when I publish this to the pub, I am getting the error. So, can how can I know such an error?

**Comment by isoos** [comment]
@dharanidharandharmasivam could you please link to you package on pub, or to your sources?

We are using `dartanalyzer` for analysis, and it reports the file and source code location of the issues. If there is only a single report, we display it with full information. However, if there are more than a certain number of issues reported, for keeping it shorter on the UI, we merge some of them, and hide parts of that information.

This can also come from a new version of `dartanalyzer`. We've deployed a new Dart SDK version (2.7) on pub.dev a few days ago, it may be related to something changing in that.

**Comment by dharanidharandharmasivam** [comment]
@isoos ,

Thanks for the information. The issue is resolved with the latest SDK version and thus I am closing the issue.
