### ISSUE TITLE
Can't login, cookie blocked without SameSite attribute?

### ISSUE THREAD

**Issue by mnordine** [dart-lang/pub-dev#3171]
I can't login. I click the "Sign in" link, Google login window pops up, I login, the Google login window disappears, but no change in pub.dev. I'm still no logged in. I'm not blocking 3rd party cookies either.

**Comment by mnordine** [comment]
Update: It may be due to cookie blocking without `SameSite`:

> A cookie associated with a cross-site resource at http://google.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by mnordine** [comment]
I'm seeing a ton of cookies blocked for the following urls:
integrator.js?domain=pub.dev
prompt

**Comment by isoos** [comment]
I can reproduce this with Chrome Canary 81.0.4000.2.

On my stable Chrome 78.0.3904.108 on Mac it is working, and the console has the following log:

"A cookie associated with a cross-site resource at http://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032."

Apparently we'll need to update the current `SameSite=Lax` soon.

/cc @jonasfj @sigurdm

**Comment by mnordine** [comment]
Curiously, it doesn't work for me with the current stable Chrome Version 79.0.3945.88 (Official Build) (64-bit) on Mac

**Comment by isoos** [comment]
Re: Chrome 79:
https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

>  In addition, these experiments will be automatically enabled for a subset of Chrome 79 Beta users. Some Beta users with the experiments enabled could experience incompatibility issues with services that do not yet support the new model; users can opt out of the Beta experiments by going to chrome://flags and disabling them.

Also: the breaking change for Chrome stable comes in February:

> Some providers (including some Google services) will implement the necessary changes in the months leading up to Chrome 80 in February;

**Comment by isoos** [comment]
https://www.chromium.org/updates/same-site

> Launch Timeline
> 
> Last updated Dec 16, 2019.
> 
> - Early October, 2019: Experimental SameSite-by-default and SameSite=None-requires-Secure behavior launched to 50% of users on Chrome Canary and Dev (Chrome Canary and Dev versions 78+). Windows and Mac users on domain-joined devices and Chrome OS users on enterprise-registered devices will be excluded from the experiment. Chrome 78 Beta users will not receive the experimental behavior.
> - October 31, 2019: Chrome 79 Beta released. Experiment extended to 50% of Chrome 79 Beta users, including domain-joined and enterprise-registered devices. Policies to manage the experimental behavior (see below) will be available on Chrome 79.
> - Dec 10, 2019: Chrome 79 Stable released. Stable users on Chrome 79 will NOT receive the new SameSite behavior.
> - Dec 19, 2019: Chrome 80 Beta released. Experimental behavior still enabled for 50% of Chrome 80 Beta users.
> - February 4, 2020: Chrome 80 Stable released. SameSite-by-default and SameSite=None-requires-Secure become default behavior for all users on Stable.

**Comment by mnordine** [comment]
Yeah, it's just weird I have stable Chrome, not using extensions, no flags set, yet doesn't work. Cookies are blocked.

**Comment by jonasfj** [comment]
Hmm, I've seen this warning else where too, I'm not sure it's related to login issues.

**Comment by isoos** [comment]
We don't see issues with logins, I think this is now resolved.

**Comment by mnordine** [comment]
Yep, I've logged in without issue.
