### ISSUE TITLE
Delete package Request.

### ISSUE THREAD

**Issue by ibrahimAlii** [dart-lang/pub-dev#3177]
Hi, I just published package with name `push_bots` and I wanna change it to `pushbots`. I tried to publish another one with new name but I get `Package name is too similar to another package..`

So Can I delete the first one please `push_bots`.

Thank you!

**Comment by ibrahimAlii** [comment]
@jonasfj

**Comment by jonasfj** [comment]
Sent uploader an email asking for confirmation.

**Comment by ibrahimAlii** [comment]
@jonasfj  Confirmed, Thank you for rapid response !

**Comment by jonasfj** [comment]
Email confirmed.. package removed..


Sorry for the delay.

**Comment by MuYuLi** [comment]
@jonasfj   i also want to delete my packet named "magpiecli" please

**Comment by jonasfj** [comment]
@MuYuLi, please file a separate request.
