### ISSUE TITLE
Change Log Date

### ISSUE THREAD

**Issue by amreniouinnovent** [dart-lang/pub-dev#3180]
I want to see the Date beside every Change log so I can understand when the developer add a specific feature.

![Screen Shot 2019-12-17 at 9 43 18 AM](https://user-images.githubusercontent.com/52191652/70968075-a94e4280-20b1-11ea-94bb-8e55fd777daa.png)

**Comment by sigurdm** [comment]
On the versions page (like https://pub.dev/packages/battery/versions) you can see when each version is published.

Currently we do no validation on the contents of CHANGELOGS. It is something I would like to do, but I don't think we will find the time soon.

**Comment by amreniouinnovent** [comment]
@sigurdm I don't know that I can compare versions tab with changelogs tab
I will close it as for now maybe if some feel it is important then he could vote on the issue
