### ISSUE TITLE
ImagePicker多次点击导致崩溃

### ISSUE THREAD

**Issue by geyifen** [dart-lang/pub-dev#3200]
URL: https://pub.flutter-io.cn/security

<Describe your issue or suggestion here>
使用ImagePicker时，一下点击了很多次会导致崩溃；
+ (NSData *)updateMetaData:(NSDictionary *)metaData toImage:(NSData *)imageData中使用
CGImageDestinationCreateWithData返回了一个空的destination

**Comment by isoos** [comment]
@geyifen: this repository is for issues for the pub.dev project. If you have issues with a package, please file a bug for the specific issue repository. (E.g. if you have issues with `package:image_picker`, please file in the following repository: https://github.com/flutter/flutter/issues
