### ISSUE TITLE
Package unpublish request: "horizantal_picker"

### ISSUE THREAD

**Issue by kaiserleka** [dart-lang/pub-dev#3202]
URL (Package to be removed): https://pub.dev/packages/horizantal_picker

Reason: Incorrect spelling on package name

I have published new one with correct name
(https://pub.dev/packages/horizontal_picker)

**Comment by sigurdm** [comment]
By default we do not delete packages unless there is a pressing reason.

The best course of action would be to mark it discontinued:
go to https://pub.dev/packages/horizantal_picker/admin and mark it as discontinued.

Now it will not show up in search etc.

You can upload a new version of `horizantal_picker` with an updated `README.md` that links to the `horizontal_picker` package.
