### ISSUE TITLE
License detection issue

### ISSUE THREAD

**Issue by ryanheise** [dart-lang/pub-dev#3204]
URL: https://pub.dev/packages/just_audio

In the side bar, the License is reported as Apache but it should be reported as MIT. The reason is that I have two licenses in the one file, but the headline license is MIT, and the second license is for another library that I'm bundling with the source. I am using a row of === signs between the two licenses which is different from the advice given here:

https://api.flutter.dev/flutter/foundation/LicenseRegistry-class.html 

However, that advice does not apply to my situation since the second license is for a bundled library and it has no associated package name.

**Comment by jonasfj** [comment]
See also: https://github.com/dart-lang/pana/issues/92

The `LicenseRegistry` is an interesting data point, I wonder if there is a specification for having multiple licenses in a `LICENSE` file.

**Comment by sigurdm** [comment]
Seems this has been done!
