### ISSUE TITLE
Please delete flutter_lwa version 0.0.1

### ISSUE THREAD

**Issue by ayvazj** [dart-lang/pub-dev#3207]
Kindly remove flutter_lwa version 0.0.1 it was uploaded by accident.  I have already replaced it with version 0.1.0.

direct link to the version to delete.
https://pub.dev/packages/flutter_lwa/versions/0.0.1

**Comment by sigurdm** [comment]
By default we do not remove old/broken versions of packages. That is in order not to break clients.
It is fine to leave it there, `pub upgrade` will find the newer verion - if you have special reasons you want the package version removed, please reopen.

**Comment by jonasfj** [comment]
If you accidentally publishing some files you would rather be private that's a good reason :)
