### ISSUE TITLE
Sign in link doesn't work

### ISSUE THREAD

**Issue by shavyg2** [dart-lang/pub-dev#3208]
URL: https://pub.dev/

Sign in link doesn't work,

**Comment by isoos** [comment]
@shavyg2 Could you please share a bit more detail: browser, version, active extensions, whether you are using any blocking software (ad, cookie...)

**Comment by shavyg2** [comment]
ver
Microsoft Windows [Version 10.0.18362.535]
It works in incognito mode.
I guess it's the latest version of chrome.

Google Chrome is up to date
Version 79.0.3945.88 (Official Build) (64-bit)

might be connection #2929

**Comment by isoos** [comment]
If it works in incognito, then it is likely that an adblocker or other extension is at fault. Do you use any of these?

**Comment by shavyg2** [comment]
I do, i am going thru and disabling one at a time to see what could be the issue.

**Comment by shavyg2** [comment]
Yes was ad-blocker
