### ISSUE TITLE
Please delete package staterepository 

### ISSUE THREAD

**Issue by petrusje** [dart-lang/pub-dev#3209]
please delete package staterepository so i can upload with a better proper name state_repository. Thanks in advance

**Comment by jonasfj** [comment]
Sent an email asking for confirmation...

**Comment by petrusje** [comment]
Just answer your email.

**Comment by jonasfj** [comment]
Confirmed, package removed.

**Comment by petrusje** [comment]
I am sitio receiving the message:
Package name is too similar to another package..
pub finished with exit code 1

**Comment by jonasfj** [comment]
@petrusje, can you give it another shot? caches might take a bit to clear, maybe you were too fast.

**Comment by jonasfj** [comment]
Ping me again if this isn't resolved.

**Comment by isoos** [comment]
This may be on us to restart / redeploy the frontend, as we don't remove the deleted name from name_tracker right away, and it is stored on the instance and not in redis.

**Comment by petrusje** [comment]
The problem still remains :(

**Comment by petrusje** [comment]
It works! Thanks ! 
Best Regards.
