### ISSUE TITLE
New Version subscription

### ISSUE THREAD

**Issue by amreniouinnovent** [dart-lang/pub-dev#3213]
I wonder if we could get an update weekly or monthly on a list of packages we are using on our apps?

**Comment by jonasfj** [comment]
Maybe https://github.com/dependabot/feedback/issues/430 would solve this?

**Comment by isoos** [comment]
@amreniouinnovent: What kind of update are you looking for? What is the scope that would be useful?

e.g. if you want to check how the real dependencies changed, it may be better if we developed a `pub` CLI command that checks them and creates a report (e.g. what to update, what are the new ones, who is the developer/publisher)...

e.g. If you want to follow the development of some packages that you are not yet using, maybe a per-package or multi-package RSS feed would be useful (whether specified explicitly, or using the liked packages).

**Comment by amreniouinnovent** [comment]
@jonasfj I checked that issue and I found what I need https://github.com/vrtdev/dep_check
@isoos I know the team is busy so dep_check is enough for what I need.
In the future maybe an advanced dep_check report would be nice like 

```
camera : 0.0.1
new >> 0.0.3
Change Log:
0.0.2
crop support
0.0.3
flashlight support

```
I will track the issue here https://github.com/dart-lang/pub-dev/issues/2339

**Comment by jonasfj** [comment]
@amreniouinnovent, just curious, but wouldn't dependabot integration solve this problem?

**Comment by amreniouinnovent** [comment]
@jonasfj yes it could but it requires:
1-Your code has already a unit tests TDD
2-API don't have any security release info check https://pub.dev/api/packages/hive on Postman
So how could dependabot know if update is a security or not?

What I think is that dependabot is better than dep_check as it is fully automated but I would need it for features changelogs and performance, not security 
I can't tell dependabot to add changelog too but in dep_check I can fork it and add changelog implementation if changelog public api released.

**Comment by jonasfj** [comment]
> So how could dependabot know if the update is a security or a feature?

One step at the time, there is a separate issue for security vulnerability reporting/tracking.

I'm not dependabot expert, but I think it might support opening PRs with CHANGELOG snippets. See https://dependabot.com/

![GdP9d4npxVx](https://user-images.githubusercontent.com/149732/72175587-c0e0c880-33dc-11ea-9d0a-0636ecaa7139.png)

**Comment by jonasfj** [comment]
> I can fork it and add changelog implementation if changelog public api released.

Changelogs are already available in the [public API](https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md), you just download the tarball/package, extract and parse the `CHANGELOG(.md|markdown|txt)` file. Changelog parsing will always be best effort, but a good guess that it's markdown, and has titles that contains the version numbers.

If you go about this, please share a `package:changelog_parser` on `pub.dev`, one day we might get around to parse changelogs too :)
