### ISSUE TITLE
Excpetion while removing package

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3217]
Remove package caused following stack trace.
```
Removing GCS objects ...
Committing changes to DB ...
Removing package from dartdoc backend ...
^[[1;3DUnhandled exception:
DetailedApiRequestError(status: 504, message: )
#0      _validateResponse (package:_discoveryapis_commons/src/clients.dart:852:9)
<asynchronous suspension>
#1      ApiRequester.request (package:_discoveryapis_commons/src/clients.dart:74:22)
<asynchronous suspension>
#2      ObjectsResourceApi.delete (package:googleapis/storage/v1.dart:2714:32)
#3      _BucketImpl.delete (package:gcloud/src/storage_impl.dart:235:25)
#4      deleteFromBucket (package:pub_dev/shared/storage.dart:36:18)
<asynchronous suspension>
#5      DartdocBackend._deleteAllWithPrefix.<anonymous closure> (package:pub_dev/dartdoc/backend.dart:381:33)
#6      Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#7      DartdocBackend._deleteAllWithPrefix (package:pub_dev/dartdoc/backend.dart:381:14)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#17     ApiRequester.request (package:_discoveryapis_commons/src/clients.dart)
```

I don't it's important the package looks gone... I suppose the dartdoc will be garbage collected someday?

**Comment by jonasfj** [comment]
@isoos, any ideas if we want to do something about this.. or just close it?

It seems to be a `504 | DEADLINE_EXCEEDED`, see https://cloud.google.com/apis/design/errors

**Comment by isoos** [comment]
The dartdoc GC cleans only existing packages with qualified versions. We'd need to write a scanner for the stale objects that are not covered by GC, or we can postpone this issue until we do the dartdoc storage refactoring, which would probably go to a different bucket and we can remove this bucket in a single delete op.

The scanner is not that hard to do, a day would probably be enough for it, if you want it to be done soon-ish...

**Comment by isoos** [comment]
For the package in question, maybe we could just re-run the delete script again after a few hours.

**Comment by jonasfj** [comment]
> For the package in question, maybe we could just re-run the delete script again after a few hours.

I don't think that'll work.. last I tried it failed because the entity didn't exist.
