### ISSUE TITLE
delete my userless packages please

### ISSUE THREAD

**Issue by MuYuLi** [dart-lang/pub-dev#3220]
i have some packages on pub.dev that i donot want to use it

so i want you guys help me  to delete them

they are "mpcli" && "pagpiecli"

my account is "zyl1881@163.com"

thanks

**Comment by MuYuLi** [comment]
@sigurdm please help me to remove my packages thanks

**Comment by sigurdm** [comment]
I have sent an email confirmation

There doesn't seem to be a package called https://pub.dev/packages/pagpiecli

**Comment by MuYuLi** [comment]
<img width="767" alt="图片" src="https://user-images.githubusercontent.com/16809810/71861022-d1204b80-312f-11ea-8215-29a6066823be.png">

**Comment by MuYuLi** [comment]
> I have sent an email confirmation
> 
> There doesn't seem to be a package called https://pub.dev/packages/pagpiecli

Sorry  I wrote the wrong name   the right name is "magpiecli" && "mpcli"

**Comment by sigurdm** [comment]
packages are deleted
