### ISSUE TITLE
I think developers started to use my plugins, but popularity is just 0

### ISSUE THREAD

**Issue by MohamedSayed95** [dart-lang/pub-dev#3222]
URL: https://pub.dev/packages/print_color
URL: https://pub.dev/packages/localize_and_translate
URL: https://pub.dev/packages/user_auth : analysis frozen since a while

I request re-analysis, and please tell me what's wrong !!

**Comment by isoos** [comment]
@MohamedSayed95: Thanks for reporting this, we'll take a look. Please note:

You don't need to request re-analysis (or upload a new version), if there were a bug in our system, we'll do the repeated analysis and get it fixed, without you needing to do anything.

`user_auth` has a clean analysis and also popularity. `localize_and_translate` has only a few hints. So the analysis here seems to be okay.

@jonasfj: `/debug` shows that the current popularity range is `"dateRange": "2019-10-18T00:00:00.000Z - 2019-12-16T12:38:47.000Z"`, maybe something did stuck?

**Comment by jonasfj** [comment]
Yeah, I actually think popularity isn't updating.

**Comment by MohamedSayed95** [comment]
any news !

**Comment by entronad** [comment]
@isoos 
The same feeling.
A month ago I updated my package: https://pub.dev/packages/flutter_echarts and did some propaganda.
I belive people begin to use it because the Github stars number grows. But the pub.dev popularity score stays unchaned.

**Comment by jonasfj** [comment]
I started working to get popularity metrics working  again. Still has to pass review, get landed and then the caches has to empty..

**Comment by Ephenodrom** [comment]
@jonasfj Seems to be fixed, the popularity of my packages was updated over night.

**Comment by jonasfj** [comment]
The job should be running, I'll checkup if it does the update tomorrow too :)
