### ISSUE TITLE
Web page is confusing

### ISSUE THREAD

**Issue by sfshaza2** [dart-lang/pub-dev#3224]
When you look at the page of web plugins, it's very confusing. It doesn't say anywhere, or confirm that the list of plugins are, indeed, for the web. It's only in the URL Can you make it more clear?

https://pub.dev/dart/packages?runtime=web

**Comment by legalcodes** [comment]
Have you tried the following instead?

https://pub.dev/flutter/packages?runtime=web

There's a 'web' label in these results (see screenshot). Not sure if that's what you were looking for, though.

![flutter](https://user-images.githubusercontent.com/5550175/71856895-50fbd680-309a-11ea-94b1-b0d47528c2a5.png)

**Comment by sfshaza2** [comment]
Nope, but I was following the "web" link on the front page, which is sub-optimal.

Mariam has found an even better link:  https://pub.dev/flutter/packages?platform=web

**Comment by legalcodes** [comment]
> Nope, but I was following the "web" link on the front page, which is sub-optimal.

Sorry -- which link are you talking about? Where did we originally find the https://pub.dev/dart/packages?runtime=web link?

> Mariam has found an even better link: https://pub.dev/flutter/packages?platform=web

Right -- that's the URL that results from clicking the **FLUTTER** and **WEB** buttons on pub.dev (see screenshot above). So do we need to keep this issue open?

**Comment by sfshaza2** [comment]
I still think this needs to be fixed. So, yes. The link on the front page is confusing. See attached screenshot. (Under the word "ANY", you'll see the "web" link.

<img width="1207" alt="Screen Shot 2020-01-06 at 4 26 23 PM" src="https://user-images.githubusercontent.com/44418985/71858870-a091d080-30a1-11ea-96cc-80bc3285c365.png">
