### ISSUE TITLE
Issue with Omitting type annotations for local variables

### ISSUE THREAD

**Issue by ShivamArora** [dart-lang/pub-dev#3225]
As part of the upgrade to Dart language and the [pub.dev](https://pub.dev) website, I'm now getting lesser scores for my [package](https://pub.dev/packages/meteorify).

The reason for the lower scores are health suggestions informing a linter issue as follows:
>Omit type annotations for local variables

This is an issue at multiple lines.

And I don't want to remove type annotations for local variables for readability and testing purposes.

I've ignored the rule using `analysis_options.yaml`, but the pub.dev still uses the standard linting rules.

Can anyone provide a reason why Dart has added this rule to the linter? What are the benefits to this?

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/pedantic/issues/45.

**Comment by isoos** [comment]
Since the issue was opened, we have limited the amount of lint penalty, and reverted to use pedantic 1.8.0.
