### ISSUE TITLE
upgrade dartdoc to 0.30.0+1

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/pub-dev#3232]
I recommend updating pub.dev to [dartdoc 0.30.0](https://github.com/dart-lang/dartdoc/releases/tag/v0.30.0) as soon as possible because of a number of critical bugfixes.  Some of them are in the new version of analyzer and you'll get those for free, but others require updating the version of dartdoc.

**Comment by isoos** [comment]
Thanks, I'll do the upgrade tomorrow.

**Comment by jcollins-g** [comment]
A consequence of base href being removed was a small bug, patched in [dartdoc 0.30.0+1](https://github.com/dart-lang/dartdoc/releases/tag/v0.30.0%2B1).

**Comment by isoos** [comment]
I've found a small issue with the canonical URL generation: https://github.com/dart-lang/dartdoc/issues/2122, which we should be able to fix on our end, and it also seems that we'll need to adjust some of the HTML customization we are doing.

**Comment by isoos** [comment]
https://github.com/dart-lang/dartdoc/issues/2123 seems to be more interesting issue, as it seems to be random in which library the classes end up with, and there is no visual clue where to look for them if I'm looking in the other library. No mention in the changelog why it would happen or how to influence it.
