### ISSUE TITLE
Searching for 'map' doesn't return 'maps' amongst first results

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3235]
Not sure if we can fix this...

**Comment by isoos** [comment]
There is no `package:maps`, is there? What would you expect to be returned?

**Comment by jonasfj** [comment]
`google_maps_flutter`, `maps_launcher`, `clustering_google_maps`, `google_maps_webservice` and maybe `flutter_maps`.. These feel map related..

**Comment by isoos** [comment]
Yeah... this is related to #3236 in the prefix part, but a slightly better approach would be to remove the plural from the words both in the index and in the query.
