### ISSUE TITLE
flutter_background_geolocation doesn't show for searches on "background geo"

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3236]
Not even "flutter background geo"... I'm not sure this is easily fixable..

Maybe not mentioning a common word like "flutter" shouldn't affect the matching.. It's not clear.
Or maybe we should bias more on popularity, likes, flutter-favorite.

**Comment by isoos** [comment]
`'background geol'` yields `flutter_background_geolocation`, and `'background geo'` does not yield it. The `flutter` word does not matter in this case, instead, the difference here is in the `'geo'` vs `'geol'` prefixes. We start prefix indexing with 4 characters right now. It could be lowered to 3 (with a bit of memory tradeoff).

**Comment by isoos** [comment]
This was fixed in search.
