### ISSUE TITLE
Remove title from README.md if it matches the package name

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3238]
Example:
![dpeLaWLhGEk](https://user-images.githubusercontent.com/149732/72257339-b8220980-360b-11ea-880c-d87f94a2898e.png)

Obviously, we would have to parse and modify the markdown.

**Comment by elbeicktalat** [comment]
> Example:
> ![dpeLaWLhGEk](https://user-images.githubusercontent.com/149732/72257339-b8220980-360b-11ea-880c-d87f94a2898e.png)
> 
> Obviously, we would have to parse and modify the markdown.

Cool but I'm not sure if we have to do this or the owner of package should thinking in this.

**Comment by sigurdm** [comment]
I think we have decided to not do this. This is too much special casing.

In https://dart.dev/tools/pub/writing-package-pages we show a package page where the headline is not exactly the package name.
