### ISSUE TITLE
Remove Package

### ISSUE THREAD

**Issue by ebi-igweze** [dart-lang/pub-dev#3256]
Please I need help removing a published package, I have tried to look for a way to delete it but I cannot, I would like to remove it please, thanks in advance.

packageName: isw_mobile_sdk

**Comment by sigurdm** [comment]
I sent a confirmation email to the package uploader. Please confirm that, and we'll remove the package.

**Comment by ebi-igweze** [comment]
I have confirmed thanks

**Comment by sigurdm** [comment]
Package is removed

It might still be in caches for a short while
