### ISSUE TITLE
velocity => acceleration

### ISSUE THREAD

**Issue by willhaslett** [dart-lang/pub-dev#3265]
URL: https://pub.dev/packages/sensors

The two instances of 'velocity' on this page need to be replaced with 'acceleration'. Of course, we can integrate acceleration to get...

**Comment by isoos** [comment]
@willhaslett this issue tracker is for the pub.dev site, and not for individual packages. Please use the "View/report issues" link to visit the package's issue tracker (when specified or inferred).
