### ISSUE TITLE
Put the API docs link at the top of the info box

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#3274]
![Screen Shot 2020-01-28 at 9 12 00 AM](https://user-images.githubusercontent.com/17034/73287592-525a8380-41ae-11ea-9385-6d343cd927e3.png)

"API reference" (I'm guessing) is the most important thing in the info box – the link should be at the top!

**Comment by jonasfj** [comment]
Already being under taken in the new experimental design (not deployed yet). Hence, I don't think we should take any short term action here :)
