### ISSUE TITLE
Install tab always recommends adding package as dependency

### ISSUE THREAD

**Issue by vargavince91** [dart-lang/pub-dev#3275]
The install tab always recommends adding packages to the `dependencies`, even if the package is used as a development dependency and should be listed in the `dev_dependencies` section in 97% of the cases.

Common examples are testing libraries and builders.

**Comment by isoos** [comment]
@vargavince91 Thanks for reporting it! I'll link this suggestion to #2967 (customize the installing tab).

@jonasfj: can we derive this from the logs / usage stats? If the package is mostly included as `dev_dependency`, we may just flag it as such, and render it without any user customization...

**Comment by vargavince91** [comment]
Thank you, @isoos, I think I also found that this issue is a duplicate of https://github.com/dart-lang/pub-dev/issues/2125
