### ISSUE TITLE
Track the number of open source projects using a Dart package

### ISSUE THREAD

**Issue by ShivamArora** [dart-lang/pub-dev#3276]
This is a request for a feature addition.

It would be great if  [pub.dev](https://pub.dev) provides a count of how many projects are using a particular package along with the package score.

I know it wouldn't be possible to track down the private repositories. But, we can track down open source projects which are using a package.

**How it would help everyone?**
- **The maintainers** would be able to know how much their package is being used and it serves as a great motivation to keep on maintaining that package for a longer run.
- **The prospective users** can guess the stability and popularity of the package by the count of how many other projects are using it.
- Both of them can also track down how different projects are using the package by visiting the open source repositories.

**Comment by isoos** [comment]
Are you suggesting to scan and track the public git repositories that are using Dart/Flutter and reference a public package on pub? Or would this be an opt-in registry?

On pub.dev we expose dependencies of the published packages, e.g. `dependency:pana` search query will list packages that depend on `package:pana`: https://pub.dev/packages?q=dependency%3Apana

**Comment by ShivamArora** [comment]
@isoos Yes. I suggested scanning and tracking the public git repositories that are using Dart/Flutter.

I know [pub.dev](https://pub.dev) exposes dependencies of the published packages but that covers up only those packages which are published on the pub repository.

It doesn't cover up open-source repositories which might consist of unpublished packages as well.

Also, leaving apart the dependent packages, I was suggesting to keep track of open-source projects in general which might cover up packages as well as apps.

The apps need not be published but many a times our packages might be used for demo apps or personal projects which are mostly open sourced by those who teach.

This would add up to how we can measure the popularity of the package.

> Just for an example, there may be very less packages that depend on the **material** package. But almost all the flutter apps use the **material** package and we can keep a track of the open source repositories of such apps.

**Comment by ShivamArora** [comment]
@isoos Something that looks like this.

![Annotation 2020-02-04 104537](https://user-images.githubusercontent.com/4353659/73715962-a845a300-473b-11ea-9ecf-fd9bc9daa2f8.png)

**Comment by jonasfj** [comment]
I think this is outside the scope of pub.dev, at-least for now :)
