### ISSUE TITLE
Consider measuring popularity of CLI utilities differently than other packages

### ISSUE THREAD

**Issue by shyndman** [dart-lang/pub-dev#3282]
A package's score can impact whether a user considers it for use, but seems to assume that it is installed/upgraded frequently as is the case with pubspec-referenced libraries. 

For CLI utility packages (ie, provide binaries intended to be used by the user, not imported by software), this is not likely to be the case, and as such their scores can be quite low.

**Comment by isoos** [comment]
Thanks for suggesting this. We had a long-term plans to use `pub global activate` (#3282), tracking the page views, and also should use with the new like counts. However, it is a tricky question, as we need to respect private projects and users who do not want to have any tracking on their machines.

**Comment by jonasfj** [comment]
I think we are planning to overhaul popularity metrics so that they are more absolute numbers.. It's not clear exactly when or how we get there yet.

With absolute numbers  I don't think special casing CLI utilities is as pressing a concern.
