### ISSUE TITLE
[Feature Request] Provide total downloads for a package

### ISSUE THREAD

**Issue by feinstein** [dart-lang/pub-dev#3291]
URL: https://pub.dev/packages/

The `popularity` score is really nice to evaluate is a package has wide spread adoption, but as a package owner I would like to know if my package had 1000 or 10000 downloads (discarding build tools and etc). It's nice to know how many people/projects we impacted and the 0 -100 popularity score hides the actual impact we had. This kind of data stimulates us to keep going.

If you think is too much info, it could be available to the package owners alone.

**Comment by isoos** [comment]
@feinstein: thanks for submitting this. Please track progress on #2714, I'll close this as duplicate.

**Comment by jonasfj** [comment]
@feinstein, I'm curious what metrics would you like:

 *  Number of times `pub get` was called on a `pubspec.yaml` with dependency on the package (number of `pub gets`).
 * Number of times `pub get` was called  on a `pubspec.yaml` with dependency on the package, AND the packages wasn't already cached locally (number of downloads).
 * Number of times `pub get` was called  on a `pubspec.yaml` with dependency on the package, AND the package wasn't already in the `pubspec.lock` (number of installations/activiations).

I'm thinking of igoring transitive dependencies and simply compute those statically after that fact.

I personally fear that the number of downloads is utterly domintated by automated CI systems without caching.

**Comment by feinstein** [comment]
I agree and IMO the number of installations/activations (last option) is the one that most resembles "projects that use my package", which is what I would love to see. 

Considering the limitations I think this metric should come with a disclaimer note explaining its caveats.
