### ISSUE TITLE
Example tab should use /example/readme.md only when other options are not available

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#3298]
https://dart.dev/tools/pub/package-layout#examples says to lay out packages with examples like this:

1. example/readme[.md]
1. example/example[.md]
1. example[/lib]/main.dart
1. example[/lib]/package_name.dart
1. example[/lib]/package_name_example.dart
1. example[/lib]/example.dart

Currently it seems we select the example to show in the Example tab by looking in this order. I'm don't think having readme.md as the primary selected file makes sense; we should be picking an explicit example.md or a code file first. I suggest we re-order to:

1. example/example[.md]
1. example[/lib]/main.dart
1. example[/lib]/package_name.dart
1. example[/lib]/example.dart
1. example[/lib]/package_name_example.dart
1. example/readme[.md]

As a concrete example of this, for [shared_preferences](https://pub.dev/packages/shared_preferences#-example-tab-) we currently pick [this empty readme](https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences/example), but with the new order above would pick [a much more meaningful code file](https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences/example/lib/main.dart)

**Comment by mit-mit** [comment]
@jonasfj and I discussed, and sounded like he agreed. @isoos WDYT?

**Comment by isoos** [comment]
lgtm

**Comment by mit-mit** [comment]
@isoos can you help with the needed changes for pub.dev? I'll update dart.dev (https://github.com/dart-lang/site-www/pull/2256).

**Comment by isoos** [comment]
The actual code is in pana, I think it should be without much side-effect to update it:
https://github.com/dart-lang/pana/blob/master/lib/src/maintenance.dart#L40-L53

**Comment by jonasfj** [comment]
@isoos, yes, it should be... we'll need to backfill all examples won't we? and these won't be covered by `runtimeVersion`, so we have no rollback..

**Comment by isoos** [comment]
> we'll need to backfill all examples won't we?

Maybe we could just ask the authors that are affected to release a new version after we go live with it? Not sure if <10 packages is worth the effort and risk of the backfill.

**Comment by mit-mit** [comment]
@isoos was this implemented?

**Comment by jonasfj** [comment]
Might have rolled, but we haven't backfilled examples...

**Comment by isoos** [comment]
`shared_preferences` had a recent new version, but the `example/lib/main.dart` was not picked up.

**Comment by isoos** [comment]
Apparently we have two code paths for example filename candidates:
- one in `pana` (already updated)
- one in `pkg/pub_package_reader`: https://github.com/dart-lang/pub-dev/blob/master/pkg/pub_package_reader/lib/src/file_names.dart#L21 (not yet updated)

Background: hte intent for `pub_package_reader` was to provide a better code sharing between `pana`, pub server and pub CLI client, but we never got to do it.

**Comment by jonasfj** [comment]
I'll do a backup and backfill.

**Comment by mit-mit** [comment]
@jonasfj what's the status of this?

**Comment by jonasfj** [comment]
@mit-mit, I filed: https://github.com/dart-lang/site-www/pull/2306 to update docs..

**Comment by jonasfj** [comment]
Started backfill process..

**Comment by jonasfj** [comment]
> Updated: 87822 package versions.

Done.
