### ISSUE TITLE
Add support for warnings and notes

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/pub-dev#3308]
It would be nice if we could define warnings and notes for our README.md files.  Slatedoc uses CSS classes on `aside` for achieving them:

https://github.com/slatedocs/slate/wiki/markdown-syntax#notes-and-warnings

**Comment by jonasfj** [comment]
Agreed, this would be nice feature.

Doing it is not trivial, worse is documenting in a manner that people will find it.

**Comment by jonasfj** [comment]
disclaimer: I don't think we have time to work on this anytime soon. If somone is interested in driving it we can likely do reviews, etc.

**Comment by GAyan17** [comment]
I would like to work on this issue. Can I just get more information on what things I have to do?

**Comment by isoos** [comment]
@GAyan17: Could you please comment here with examples and screenshots: what kind of markup would you like to support, and what they should look like?

I'm happy to point you to the right direction in the codebase, but we may need to refactor a few style names to prevent collisions, that's the reason I'm looking for all the details upfront.

**Comment by GAyan17** [comment]
I inspired my markup from slate docs only. There way is good and simple. I think we can use yellow for notices and red as usual for warning and maybe we can bold the warnings. Suggestions and guidance is most welcome.
![Screenshot from 2020-02-26 11-46-45](https://user-images.githubusercontent.com/43421120/75353314-36dbb900-58d1-11ea-9edd-a67e67b5e973.png)
![Screenshot from 2020-02-26 11-47-08](https://user-images.githubusercontent.com/43421120/75353320-380ce600-58d1-11ea-851d-d3fb8239b268.png)

**Comment by jonasfj** [comment]
I'm sure there is something useful in https://material.io/, maybe card or icon + elevation... there is probably something to look around for.

**Comment by isoos** [comment]
@GAyan17: Also keep in mind that while new features are welcome, we'd like to be as close to the standard(s) as possible, and potentially using features from markdown-native format(s) or well established practices. E.g. your original link mentioned `<aside class="notice">...</aside>` as a markup, which seems to be more natural choice for this than `<dl><dt>...`.

**Comment by gaaclarke** [comment]
Design tip, don't use fully saturated colors.  Here is a material color picker: https://material.io/design/color/the-color-system.html#tools-for-picking-colors

Here is a typography tool too: https://material.io/design/typography/the-type-system.html#

**Comment by GAyan17** [comment]
@isoos I will keep that in mind. I made some changes in the markup, if anything more to be done, tell me please.
![Screenshot from 2020-02-28 07-16-26](https://user-images.githubusercontent.com/43421120/75537906-cb632a00-5a3d-11ea-88a6-8de11d366527.png)
![Screenshot from 2020-02-28 07-16-36](https://user-images.githubusercontent.com/43421120/75537911-cc945700-5a3d-11ea-8374-c4362079455e.png)

**Comment by sigurdm** [comment]
I don't think we will implement this for now.

It seems a little arbitrary in choice of allowed markup.
