### ISSUE TITLE
Wrong command to activating the package

### ISSUE THREAD

**Issue by cookie-blood** [dart-lang/pub-dev#3309]
URL: https://pub.dev/packages/encrypt

Command in the docs for package activation is `pub global active encrypt`.
The right one is `pub global activate encrypt`.

**Comment by jonasfj** [comment]
This the repository for `pub.dev`, we do not write all the packages.

You can find the repository here: https://pub.dev/packages/encrypt

https://github.com/leocavalcante/encrypt
