### ISSUE TITLE
Delete v2 of package_config

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#3314]
Since we don't have https://github.com/dart-lang/pub-dev/issues/378 yet...

![Screen Shot 2020-02-11 at 8 06 55 AM](https://user-images.githubusercontent.com/17034/74254606-87ce9900-4ca5-11ea-9019-c763b8cdd476.png)

We don't like the API shipped in v2. We'd like to make sure no one gets it.

So far, there has only been **1** download of it. I think it's safe to eliminate.

CC @jakemac53 @lrhn

**Comment by jakemac53** [comment]
Lets do this quickly before it does actually pick up some usages please! It should greatly simplify things.

**Comment by jonasfj** [comment]
It's been a bit long after publishing, so need sign-off from mit-mit@ :)

**Comment by jonasfj** [comment]
Resolved.
