### ISSUE TITLE
Add platform:macos tag

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3321]
Add a tag for packages compatible with `macos`. or at-least discuss doing so.

**Comment by jonasfj** [comment]
This is perhaps a TODO to me to find out if/when we want to add this tag.

**Comment by jonasfj** [comment]
After discussions in chat a few days ago, I think we decided not to do this yet.

**Comment by AndroidNils** [comment]
> After discussions in chat a few days ago, I think we decided not to do this yet.
What were the reasons for this? I miss this feature 😢

**Comment by sigurdm** [comment]
We actually have 'hidden' support for this.

https://pub.dev/flutter/packages?platform=macos

But until https://github.com/dart-lang/pana/issues/639 is solved it is not super-useful as all old-style plugins are tagged as working on mac-os.

**Comment by sigurdm** [comment]
Now dart-lang/pana#639 is fixed, you should be able to use https://pub.dev/flutter/packages?platform=macos . Not sure when we want to include it as an option in the interface itself.
