### ISSUE TITLE
Can't publish a package

### ISSUE THREAD

**Issue by TheCloudGit** [dart-lang/pub-dev#3324]
URL: https://pub.dev/

pub publish is not working.

HTTP error 500: Internal Server Error at https://pub.dartlang.org/api/packages/versions/newUploadFinish?upload_id=b578094d-3b47-47ac-a088-f477cea31686&bucket=pub-packages&key=tmp/b578094d-3b47-47ac-a088-f477cea31686&etag=d41d8cd98f00b204e9800998ecf8427e.
This is likely a transient error. Please try again later.

**Comment by isoos** [comment]
@TheCloudGit: server logs indicate that we were not able to unpack the archive you've uploaded. Could you please share more about your system? (e.g. OS, Dart SDK)

Please also include a verbose log: `pub publish -v` (or similar with Flutter if you are using that.).

**Comment by TheCloudGit** [comment]
I test in two centos 7 servers, one in my notebook and the other in a Google cloud instance.
This are the results for the flutter --version
Centos 7
Flutter 1.12.13+hotfix.8 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (3 days ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

With a windows 10 in my notebook a success, so its seems that Centos 7 or some configuration or software installation was the problem.
I will use windows in the future for publishing packages, seems linux has some bug with the flutter sdk, dart sdk. or with git.

Thanks for your response

**Comment by isoos** [comment]
@TheCloudGit: FYI: Others had problems with Centos a while back: #101. The issue may be with `tar`...

**Comment by isoos** [comment]
Closing the issue, as I don't see anything else we can add to it on the pub server side. Tracking the rest in the following issue: https://github.com/dart-lang/pub/issues/1602
