### ISSUE TITLE
meta tags for twitter / facebook needs review

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3330]
Running a URL like `https://pub.dev/packages/built_collection` through:
 * https://cards-dev.twitter.com/validator
 * https://developers.facebook.com/tools/debug

It's clear that we might need to update our meta tags. At-least twitter seems to be unable to parse our meta tags.

Guide to essential tags is available here: https://css-tricks.com/essential-meta-tags-social-media/

**Comment by isoos** [comment]
Is there a validator that is public and not tied to a login?

**Comment by jonasfj** [comment]
> Is there a validator that is public and not tied to a login?

I haven't seen any --- but I just signed in with my personal twitter/facebook accounts and that worked fine.

I makes no sense to me why they are behind login, maybe it's a quick way to mitigate abuse who knows.

**Comment by isoos** [comment]
> https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image
> 
> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages.

I think this is a rule we may want to break (temporarily, until we figure out per-package images) :)

**Comment by kevmoo** [comment]
Could/should this issue be closed out?

**Comment by isoos** [comment]
> Could/should this issue be closed out?

I wanted to do a verification with the next prod release, but feel free to close it.

**Comment by kevmoo** [comment]
We should have a label for "fixed but not deployed"

**Comment by isoos** [comment]
Verified:
- twitter validator is now good with the page
- facebook debug tool only has `fb:app_id` missing.
