### ISSUE TITLE
Request to delete package from pub

### ISSUE THREAD

**Issue by samuelematias** [dart-lang/pub-dev#3347]
Hi @jonasfj , could you delete this package [pasquim](https://pub.dev/packages/pasquim#-readme-tab-) ?
It was uploaded by mistake.
I was learning how to upload a package, I thought I could delete it after the test, but I didn't find that option.
I am the owner of the package.
my email hi@samuelematias.com

Thanks.

**Comment by jonasfj** [comment]
For future reference please send such requests to support@pub.dev, see: https://pub.dev/policy
