### ISSUE TITLE
Default filter should be `any` not `flutter`

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/pub-dev#3356]
Seen result: going to pub.dev presents a search box that only searches 'flutter' packages
Expected result: going to pub.dev presents a search box that searches 'flutter' and 'dart' packages

**Comment by isoos** [comment]
@gaaclarke: the default filter is `any`. When you switch between the SDKs, we'll remember your choice in a cookie and present it next time as a default. (You can check this e.g. in a Guest mode Chrome window).

Is there something we could do better to make this mechanism easier to follow?

**Comment by gaaclarke** [comment]
Thanks @isoos.

I would forget what filter users were previously using.  http://cs doesn't remember what domain you were searching for when you come back to the page, http://google.com doesn't remember if you were filtering for image search.  The results are so similar too, it's easy to miss you were filtering by the wrong thing.

**Comment by jonasfj** [comment]
Hmm, maybe we should reconsider this UX in the future. Especially, if others find this confusing too.
