### ISSUE TITLE
Package unpublish request: expanding_picker_sheet

### ISSUE THREAD

**Issue by TahaTesser** [dart-lang/pub-dev#3364]
URL: https://pub.dev/packages/expanding_picker_sheet
please help me to remove this package.  [1193](https://github.com/dart-lang/pub-dev/issues/1193)

This was bascilly my first package from Shrine code and there is no real use of it anymore since we have opencontainer in new animations library by Flutter
Thank you

**Comment by sigurdm** [comment]
Please see https://pub.dev/policy.

I think it would be better to mark this package discontinued: https://dart.dev/tools/pub/publishing#discontinue.
