### ISSUE TITLE
Consider featuring platform tags for macos, etc. with a labs icon

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3384]
We currently have tags for `android | ios | web`:
![p5o03EsnLpZ](https://user-images.githubusercontent.com/149732/75490058-b5108c00-59b3-11ea-8a05-ca89333bcbd5.png)

 It would be nice to add `macos` and then maybe left it be followed by a flask / labs icon, indicating that this is still an alpha technology.
https://fontawesome.com/icons/flask?style=solid

**Comment by stuartmorgan** [comment]
Given that people are also using the Linux and Windows technical previews, it would be nice to include Windows and Linux now as well even though plugins shouldn't be published with Windows or Linux support yet, so that people can easily distinguish between packages (which will work) and plugins (which won't)

**Comment by jonasfj** [comment]
Okay, maybe we need to ask our designer for help here.. maybe we can incorporate it in the new design..

Conceptually, I imagine something like:

![piKmtzeHPeO](https://user-images.githubusercontent.com/149732/75523819-0ac55280-5a0d-11ea-9dd7-e69715f0e4a9.png)

(or maybe the icon is after the tags, and is raised a little)

**Comment by isoos** [comment]
We should also consider how it would look if/when we add 2-3 more platform labels there.

I'm not sure about the icon though: do we really need to communicate the status of a platform support? We won't track their development in Flutter closely, but developers using them would, and they will be able to infer if it is useful for them or not.

**Comment by jonasfj** [comment]
@mit-mit, thoughts?

**Comment by mit-mit** [comment]
My initial thoughts are to not use an icon, but rather a url-parameter to turn on the display of these while desktop support is still in alpha.

**Comment by Sunbreak** [comment]
@isoos Any conclusion?

**Comment by isoos** [comment]
@Sunbreak: The following url lists packages with macos tagging:
https://pub.dev/flutter/packages?platform=macos

We will expose the UI control for it later.
