### ISSUE TITLE
Regression email validation too strict

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3408]
Monitoring deployment during gradual traffic migration I noticed one user unable to sign-in as we tightened the email validation pattern too much. From what I can see we only have one user affected. Traffic has been migrated back -- it was never more than 5% :)

Maybe we need to improve the validation pattern.. or fallback to the old pattern and somehow encode charaters correctly when sending emails.

**Comment by isoos** [comment]
Enabling the missing `-` character in the RegExp is not hard: `r'^\S+@[\w\-]+(\.[\w\-]+)+$'`.
However, it makes me wonder if we should search for characters that are known to be not allowed in the domain part?
