### ISSUE TITLE
[Request]: Add support for interactive flutter code to package page

### ISSUE THREAD

**Issue by hawkinsjb1** [dart-lang/pub-dev#3413]
With the maturity of flutter-web, I think it would be totally possible and very useful for package pages to offer interactive examples of their widgets. Probably not the easiest or most important feature, but it would be very beneficial to devs and also show off the cross-platformability of Flutter.

**Comment by jonasfj** [comment]
Yes, support for embedding dartpad would be pretty neat :)

**Comment by RedBrogdon** [comment]
This is a long-standing feature request for DartPad which the team hasn't had time to design and implement:

https://github.com/dart-lang/dart-pad/issues/901

We're hoping to go after it later this year, though it's unlikely we'll be able to implement a solution that includes all the packages available on pub.

**Comment by hawkinsjb1** [comment]
@RedBrogdon If you leave it up to the package publisher to write their own examples then you wouldn't have to worry about 'supporting all the packages' right?

**Comment by RedBrogdon** [comment]
Each example would still need to be able to import the package for which it's the example, which is something DartPad's backend compilation and analysis server isn't able to handle right now.

It's not capable of running `pub get` for each individual request, in other words, in order to solve versions, download things to the pub cache, and so on.

**Comment by amorenew** [comment]
I was checking one of the packages and I found that GIF is not enough then I think about Dartpad

**Comment by krjw-eyev** [comment]
Since [dart-lang/dart-pad#901](https://github.com/dart-lang/dart-pad/issues/901) has been closed but dart-pad does [NOT](https://github.com/dart-lang/dart-pad/wiki/Adding-support-for-a-new-package) support adding packages automatically, what's the plan on this?

**Comment by domesticmouse** [comment]
We aren't aiming to add packages automatically. There are concerns with security, and we don't intend to support builder based code generation.

**Comment by hawkinsjb1** [comment]
@domesticmouse Interesting, if this adds a layer for potential malice then its no good, but I would've thought some basic checks can eliminate those concerns for a wide range of simple (mostly UI-based) packages. Seeing actual Flutter code run in the web like in the official docs is very cool and on-brand for Flutter.

**Comment by sigurdm** [comment]
@jonasfj If we get sandboxing up and running we could totally do a compilation of a designated (web-friendly) example right?

It would not be editable on-line like dart-pad, but still pretty neat...

**Comment by jonasfj** [comment]
I think we want to host such demos, I think it's better to just deploy to github pages, if you want to ship a demo.

**Comment by sigurdm** [comment]
> I think it's better to just deploy to github pages, if you want to ship a demo.

But for dartdoc it would be awesome to have them inlined, like the official flutter docs already has:

Like the interactive sample on this page:

https://api.flutter.dev/flutter/widgets/AbsorbPointer-class.html
