### ISSUE TITLE
Flutter Favorite icon is blurry on HiDPI screens

### ISSUE THREAD

**Issue by cbenhagen** [dart-lang/pub-dev#3422]
<img width="645" alt="Screenshot 2020-03-10 at 11 59 14" src="https://user-images.githubusercontent.com/814785/76306169-b3559b00-62c6-11ea-8dd0-6935f0932374.png">

Either an svg version or a bigger resolution image which is downscaled would fix this.

**Comment by isoos** [comment]
@cbenhagen thanks for reporting. We are working on a new design which has this fixed:

<img width="346" alt="Screen Shot 2020-03-10 at 14 59 16" src="https://user-images.githubusercontent.com/4778111/76319647-cf196b00-62df-11ea-9ac0-233139368940.png">

I'm not sure if we'll put in effort fixing it in the current design...
