### ISSUE TITLE
Pub allows empty license file

### ISSUE THREAD

**Issue by lesnitsky** [dart-lang/pub-dev#3449]
If LICENSE doesn't exist pub shows
```
Missing requirements:
* You must have a COPYING, LICENSE or UNLICENSE file in the root directory.
```
and it treats empty LICENSE file as a valid license
If the intent is to prevent unlicensed packages to be published – this should be also an error

Validating license is something hard to implement, b.c. there are no strict rules, so maybe it makes sense to drop LICENSE missing requirement and suggest to generate MIT/BSD license instead?

**Comment by sigurdm** [comment]
This is indeed not an easy area.

We can only do so much.

But demanding a LICENSE file at least makes it clear that we expect packages to declare their license, and I think it leads to many more packages having a valid license: People see the validation error, and actually choses the terms they like.

If the file contains nonsensical (or even no) text, the licensing terms are left unclear - not much we can do.

We have some plans to try to recognize the license if it is from a subset of known licenses: https://github.com/dart-lang/sdk/wiki/Dart-GSoC-2020-Project-Ideas#idea-spdx-license-detection-package

**Comment by jonasfj** [comment]
Let's forbid cases where the LICENSE file contains only whitespace.

**Comment by isoos** [comment]
A few more of the weird license contents:
- "See COPYING.md"
- "TODO: add license"
