### ISSUE TITLE
Can pub publish authrized with API key, Not OAuth

### ISSUE THREAD

**Issue by JacksonTian** [dart-lang/pub-dev#3486]
- In my company, a lots of people need to publish packages to pub.dev under a verified publisher. But we can give the credential to every one, Because the people maybe leave company. We want to verify publisher with our inner portal.
- The OAuth authorize flow need user to open browser. It cause we can't integrate with pub.dev via server.

**Comment by isoos** [comment]
Related `pub` client issues: https://github.com/dart-lang/pub/issues/2201 and https://github.com/dart-lang/pub/issues/1381

**Comment by JeremyChenn** [comment]
perfect

**Comment by jonasfj** [comment]
@JeremyChenn would more granular permissions solve this? You could probably also use gsuite accounts, that way you admin all accounts and can revoke them when people leave.

That said automation is something we're thinking about.
