### ISSUE TITLE
Can not get flutter packages due to http error

### ISSUE THREAD

**Issue by csisanyi** [dart-lang/pub-dev#3487]
Hello,

I've been using flutter for a couple of months and everything worked well until march 26th.

 * I've tried to upgrade to flutter 1.12, but packages get failed.
 * I reverted back to the old 1.9... version, but the problem persisted.

**I have to emphasize that I'm working behind a corporate proxy**

flutter doctor -v shows no issues

When I run **flutter pub get** or **flutter packages get** I receive the following error.
```
HTTP error: HandshakeException: Handshake error in client (OS Error:CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:354))
```
After some research I tried to add our own certificate to the Dart VM using env variable

* If I add it as .der file I receive the following error
```
DART_VM_OPTIONS=--root-certs-file=<my-cert>.der
```
```
HTTP error: TlsException: Failure trusting builtin roots (OS Error: errno = 0)
```
* If I add the same certificate as .crt file I receive the following error
```
DART_VM_OPTIONS=--root-certs-file=<my-cert>.crt
```
```
HTTP error: HandshakeException: Handshake error in client (OS Error:CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))

```

I have also reported the problem to our corporate support, but they closed my issue with the following response:
*We don't deal with certificate of external websites. Perhaps you need to contact the website administrator.*

Could somebody help me what might be the problem?
Is the problem in our system or am I receiving the error from pub.dartlang.org?
What can I do from my side to solve the issue?

**Comment by timoteosoutello** [comment]
Same issue !

**Comment by jonasfj** [comment]
@timoteosoutello are you also behind a corporate proxy?

**Comment by timoteosoutello** [comment]
Yes !

**Comment by Inconnu08** [comment]
I'm recently facing this for the past few days. So I set up a VPN, and it works. 😶

**Comment by jonasfj** [comment]
This sounds more like an issue with the proxy... are you guys behind the same proxy? (Same company)

> We don't deal with certificate of external websites. Perhaps you need to contact the website administrator.

What kind of proxy are you going through? if the proxy is doesn't blindly forward the encrypted TCP stream, then how can the certificate on `pub.dev` be a problem on your local machine?

On the server side we use automatically renewed certificates through GCP, which uses let's encrypt.

I might not be entirely up-to-date on how such proxy operate. But try to write a minimalistic dart program and see if you can access other HTTPS resources unline through your corporate proxy.

**Comment by jonasfj** [comment]
We think this a proxy issue. Making HTTPS proxies work with custom certificate stores is probably hard.
