### ISSUE TITLE
Poor search result

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub-dev#3488]
A search for `grinder` shows lots of results 
but the `grinder` package is not one of them.

As far as I remember packages that are not Dart2 compatible are not shown in search results, but I haven't found anything like that wrong with the `grinder` package.

I think packages exactly matching the search term should **always** be shown anyway.

When someone searches for an unused package name, finds nothing and therefore uses it for his project only to find when he tries to publish later that it's already taken by an old package)

**Comment by isoos** [comment]
@zoechi: Do you recall when this happened? I'm searching for `grinder` now and I get it as a top result.

**Comment by isoos** [comment]
Oh, maybe this another case of keeping the search preferences: do you have the `Flutter` filter on? As grinder is not a flutter-compatible package, it is not listed under `Flutter`.

**Comment by zoechi** [comment]
Sorry this is my fault, this is a dup of #3356
