### ISSUE TITLE
Error in custom selection

### ISSUE THREAD

**Issue by AnkitKumar0110** [dart-lang/pub-dev#3498]
URL: https://pub.dev/packages/file_picker

<Describe your issue or suggestion here>

If we select custom section for the file extension and type only 'pdf' we still select any image that is .jpg

**Comment by isoos** [comment]
@AnkitKumar0110: this repository is for issues with the pub.dev site. Please use the package's issue tracker to file bugs: https://github.com/miguelpruivo/flutter_file_picker

Closing.
