### ISSUE TITLE
pub.dev Awaiting analysis to complete.

### ISSUE THREAD

**Issue by imtoori** [dart-lang/pub-dev#3507]
- I uploaded an update of my package yesterday evening
- The analysis is still incomplete

There is a way to restart it or I have to release an update?

**Comment by isoos** [comment]
@imtoori: there was a Google cloud outage yesterday that upended some of our operations (e.g. some analysis were aborted). The package analysis scheduling will re-schedule your package for analysis, there is no need to release a new version for this. However, in cases like this, it may take a day or two. (What's the package name?)

**Comment by imtoori** [comment]
thank you @isoos 
the package name is `stream_chat_flutter`
I'll close this issue and wait for the analysis to complete
