### ISSUE TITLE
Removing / moderating uploaded package

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [dart-lang/pub-dev#3513]
Please read https://pub.dev/policy and send requests to support@pub.dev
I would like my package to be removed since it is not working and no one would use it. So if you are worried about people depending on it, I have discontinued it but need it to be removed because it has no purpose! I know that is weird to say about my package but I didn't know and I was just experimenting so I hope that you can remove it.

Package link:
https://pub.dev/packages/loading_indicators_flutter

**Comment by jonasfj** [comment]
Please email `support@pub.dev`.

**Comment by YazeedAlKhalaf** [comment]
Thanks
