### ISSUE TITLE
Score reduced by 10 points for dependency that cannot be resolved

### ISSUE THREAD

**Issue by larryaasen** [dart-lang/pub-dev#3514]
My package [upgrader](https://pub.dev/packages/upgrader), v 0.10.3, depends on flutter_test, which depends on xml. Currently, flutter_test must use xml 3.5.0, and cannot be used with xml 4.1.0, as is suggested on the pub.dev [analysis tab](https://pub.dev/packages/upgrader#-analysis-tab). The score is reduced by 10 points, using Flutter: 1.12.13+hotfix.8. That is not something that I can resolve. Something is wrong here.

**Comment by isoos** [comment]
@larryaasen: apologies, the analysis does not yet provide helpful suggestions yet, and we don't handle all the edge cases. (Filed https://github.com/dart-lang/pana/issues/633 and https://github.com/dart-lang/pub-dev/issues/3515).

In your case, if you also support `xml 4.1.0` and there is no breaking change, you could use a version constraint in your `pubspec.yaml` like the following:

````
  xml: ">=3.5.0 <5.0.0"
````

That way you are supporting both major versions, and the pub site will be happy about it :)

**Comment by larryaasen** [comment]
@isoos Thanks for the tip on the version constraint. That worked!
