### ISSUE TITLE
Send notification if dependent package has new major version.

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#3515]
Related to: https://github.com/dart-lang/pana/issues/633

When a dependent package releases a new major version, it would be nice to notify its users that they could upgrade to it.

**Comment by jonasfj** [comment]
I think we should design a configurable notifications... including making current notifications configurable. And maybe consider if/when we need this when we have dependabot integration.

**Comment by Ephenodrom** [comment]
Consider the situtation in this issue, if you plan to implement the mailing function. #3179

**Comment by isoos** [comment]
This is now covered with the dependabot integration.
