### ISSUE TITLE
Feature requeast: Keep/save/favorite packages for quick access

### ISSUE THREAD

**Issue by Luckey-Elijah** [dart-lang/pub-dev#3516]
URL: https://pub.dev/

On the pub.dev site, it would be really cool if one would be able to "save" packages to an account or something similar. I understand that there is already sign in functionality for google in order to "like" the packages - but this would be more along the lines to reference a package and it's API quickly without searching for it.

**Comment by isoos** [comment]
@Luckey-Elijah: What would be the conceptual difference between this one and e.g. liking the packages and visiting `https://pub.dev/my-packages`? Would these list of packages public? What purpose would these serve?

**Comment by Luckey-Elijah** [comment]
Okay! I didn't know that the `/my-packages` page was a thing. It seems there's no difference conceptually.

But I am having difficulties logging in and liking packages.

**Comment by Luckey-Elijah** [comment]
This issue can probably be closed now since it's been addressed.

**Comment by isoos** [comment]
> But I am having difficulties logging in and liking packages.

What's your OS / browser / plugins? Aggressive blocking of cookies may result in issues with the login.

**Comment by Luckey-Elijah** [comment]
Firefox on MacOS and running a tracking blocker and ad blocker (I can provide details of those if needed).

I navigate to the `accounts.google.com` URL and see my Google accoun as an option and select it. The "One moment please" screen launches and then I'm back at the original page and am not signed in.

I don't seem to have any issue of  login on any other sites. My cookies are only wiped manually.

**Comment by isoos** [comment]
@Luckey-Elijah: please try it without the blockers. If it is working, then you may need to adjust the whitelists / block intensity settings.

**Comment by Luckey-Elijah** [comment]
Just attempted a sign in without the any extensions enabled and on a new browser session via Private window, sign in was unsuccessful.

**Comment by Luckey-Elijah** [comment]
It works on Chrome. Had to Quit the application and sign back min and works on Firefox. Likely some config on my end. Thank you!

**Comment by isoos** [comment]
Closing this for now. @Luckey-Elijah please try out the liked packages, and open a new issue if there is something else we can do to improve them.
