### ISSUE TITLE
tags in package version listing API

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3519]
Let's add _package level tags_ and _package-version level tags_ to version listing API.
```js
// GET <PUB_HOSTED_URL>/api/packages/<PACKAGE>
{
  "name": "<PACKAGE>",
  "tags": [ // <--- NEW
    "is:discontinued",
    "is:flutter-favorite",
    "publisher:<publisher>", // if package has a publisher
    /* other package level tags*/,
  ]
  "latest": {
    "version": "<VERSION>",
    "archive_url": "https://.../archive.tar.gz",
    "tags": [ // <--- NEW
      "sdk:flutter",
      "platform:web",
      /* other package-version level tags */
    ],
    "pubspec": {
      /* pubspec contents as JSON object */
    }
  },
  "versions": [
    {
      "version": "<VERSION>",
      "archive_url": "https://.../archive.tar.gz",
      "tags": [ // <--- NEW
        "sdk:flutter",
        "platform:web",
        /* other package-version level tags */
      ],
      "pubspec": {
        /* pubspec contents as JSON object */
      }
    },
    /* additional versions */
  ]
}
```

**Comment by isoos** [comment]
@jonasfj: I think "other package level tags" only applies to the first block (under `name`), while the rest should be "other version-level tags". Is this assumption correct?

**Comment by jonasfj** [comment]
Correct, I updated it. I obviously meant `package-version level tags`.

**Comment by isoos** [comment]
#3540 exposes the readily available tags, but some (e.g. the ones from analysis) are not cheaply available, as we'd need to load the related `ScoreCard` instance for getting access to those.

Some possible alternatives:
- we only load it for the `latest` version
- we only load it for the version-specific endpoint (so the package aggregate version list does not have it in full detail)
- we update the `PackageVersion[Info]` object with the analysis result of the latest runtime (has some inconsistency when rolling back a version)
- we create a package-level aggregate object with the versions and their analysis results
- .... (your idea comes here)

wdyt?

**Comment by jonasfj** [comment]
> we only load it for the version-specific endpoint (so the package aggregate version list does not have it in full detail)

This end-point has been deprecated.

> we update the `PackageVersion[Info]` object with the analysis result of the latest runtime (has some inconsistency when rolling back a version)

I think this is the best option. I'm even open to making `PackageVersionInfo` runtime versioned.
Since it only reflects derived values we can make it runtimeVersioned and regenerate everything when we make a new `runtimeVersion`.

Otherwise, I think the compromise about using the value from latest runtimeVersion is acceptable.
