### ISSUE TITLE
Duplicate library entries in generated dartdoc

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3542]
See docs for: https://pub.dev/packages/basics

Presumably, this is to do with exports, not sure if this only happens with recent versions of `dartdoc` or if it's a bug in our embedding.

![E1TSXQT66KC](https://user-images.githubusercontent.com/149732/79859824-e618a600-83d1-11ea-91b6-b2eec75ccc90.png)

**Comment by jonasfj** [comment]
@isoos, can you reproduce with dartdoc flags... and without our customizations.

**Comment by jonasfj** [comment]
Trying to debug this locally I found that `lib/` was included twice:
```
$ wget https://storage.googleapis.com/pub-packages/packages/basics-0.4.0%2B1.tar.gz
$ tar -xvzf basics-0.4.0+1.tar.gz
$ tree lib
lib
├── basics.dart
├── date_time_basics.dart
├── int_basics.dart
├── iterable_basics.dart
├── lib
│   ├── basics.dart
│   ├── int_basics.dart
│   ├── iterable_basics.dart
│   ├── list_basics.dart
│   ├── map_basics.dart
│   ├── object_basics.dart
│   ├── set_basics.dart
│   ├── src
│   │   └── slice_indices.dart
│   └── string_basics.dart
├── list_basics.dart
├── map_basics.dart
├── object_basics.dart
├── set_basics.dart
├── src
│   └── slice_indices.dart
└── string_basics.dart

3 directories, 19 files
```

**Comment by jamesderlin** [comment]
> Trying to debug this locally I found that `lib/` was included twice:

Any idea how that might have happened?  Isn't generation of the `.tar.gz` file automated?
