### ISSUE TITLE
note may be error

### ISSUE THREAD

**Issue by xialonghua** [dart-lang/pub-dev#3566]
https://github.com/dart-lang/pub-dev/blob/fab984fbe0d3b9f1ac092771da98496f23abce40/app/lib/shared/exceptions.dart#L110

note must be: less than?

**Comment by isoos** [comment]
@xialonghua: Thanks for reporting, I'll fix it soon... I'm curious though: how did you find it / what brought you to that part of the code?

**Comment by xialonghua** [comment]
@isoos my work about flutter pub、ci and flutter development, so i was reading code to learn how pub-dev works and what custom function i can do.found this error that a coincidence ^_^
