### ISSUE TITLE
Request to rename package from pub

### ISSUE THREAD

**Issue by ehowlsla** [dart-lang/pub-dev#3591]
my package url is https://pub.dev/packages/flutterbootpay

i want change pakcage name 'flutterbootpay' to 'flutter_bootpay'

Please tell me what to do

**Comment by jonasfj** [comment]
See: https://pub.dev/policy

You can request package removal within 48 hours.

This is not the place to ask.

**Comment by jonasfj** [comment]
Just please do it within 48 hours of publication... we try to keep the policy rather strict :D

**Comment by sigurdm** [comment]
You can mark the old package as 'discontinued' and publish the new package.
Then the old package will no longer appear in search results etc.
