### ISSUE TITLE
json format exception : unexpected character

### ISSUE THREAD

**Issue by pravitasari** [dart-lang/pub-dev#3613]
Exception has occurred.
FormatException (FormatException: Unexpected character (at character 1)
<br />
^
)

code :
login() async {
    final response = await http.post("http://192.168.1.5/login/api/login.php",
    body: {"username": username, "password": password});
    final data = jsonDecode(response.body);
    int value = data['value'];
    String pesan = data['message'];
    String namaAPI = data['nama'];
    if (value == 1) {
      setState(() {
        _loginStatus = LoginStatus.signIn;
        savePref(value, namaAPI);
      });
      print(pesan);
    } else {
      print(pesan);
    }
  }

**Comment by sigurdm** [comment]
Not sure what you are trying to do.

Could you explain a bit what you expected to happen?
Is this an issue with the pub.dev site?

Please edit the comment and use code-fencing for the code to make it readable.

https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks
