### ISSUE TITLE
How detect and remove some ppl make a reservation

### ISSUE THREAD

**Issue by minhvn** [dart-lang/pub-dev#3629]
Hi team, How detect and remove some ppl **make a reservation** to get **nice name** and longtime didn't push source code"
Only run create plugin project and push to pub.dev.
Thank team.

**Comment by isoos** [comment]
@minhvn: Please follow the "Name squatting" guides on the policy page:
https://pub.dev/policy#name-squatting

"If you believe a package is engaged in name squatting, you can use the following steps to request a pub.dev moderator review and that the package be transferred to you:

- Locate the email of the publisher, as shown in the details pane on the package page on pub.dev.
- Email the publisher and copy/cc support@pub.dev, politely asking the publisher to either explain their intended purpose or transfer the ownership of the package to you.
- If the publisher does not respond within three (3) weeks, forward the thread to support@pub.dev, and a pub.dev moderator will review your request."
