### ISSUE TITLE
pub.dartlang.org is down

### ISSUE THREAD

**Issue by JSWilProf** [dart-lang/pub-dev#3633]
![Captura de Tela 2020-05-17 às 10 40 17](https://user-images.githubusercontent.com/19787516/82148913-7dcfaf80-982b-11ea-84a2-039e9df9665f.png)
URL: https://pub.dartlahg.org/

flutter packages get 
or
pub get

Does not work, show timeout when trying to access pub.dartlang.org
only works when set PUB_HOSTED_URL=https://pub.dev/.

**Comment by JSWilProf** [comment]
![Captura de Tela 2020-05-17 às 10 46 40](https://user-images.githubusercontent.com/19787516/82148941-bcfe0080-982b-11ea-9e8d-bc1b3084617e.png)
Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (5 days ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2

**Comment by JSWilProf** [comment]
correcting: it only works if we add the pub.dev resolution in /
![Captura de Tela 2020-05-17 às 11 43 50](https://user-images.githubusercontent.com/19787516/82151850-0d795c00-9834-11ea-8bad-28f08c72e76a.png)
etc/hosts

**Comment by jonasfj** [comment]
What DNS server are you using? ISP? where are you located?

What does `dig any pub.dartlang.org` report?

**Comment by jonasfj** [comment]
What OS / configuration.

**Comment by isoos** [comment]
Assuming the issue was resolved. Feel free to reopen if it still persist.
