### ISSUE TITLE
advanced search in new design disappears when making page less wide

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3642]
Seems the advanced options leaves the viewport if the window is made narrow... Even though we have plenty of space.

![HBK3wZxSvbO](https://user-images.githubusercontent.com/149732/82350755-0c932680-99fc-11ea-839a-f1f3e922167b.png)

**Comment by isoos** [comment]
Fixed by #3643.

**Comment by isoos** [comment]
(Closed by mistake)

**Comment by isoos** [comment]
This has been fixed.
