### ISSUE TITLE
[Feature Request] Better scoring 

### ISSUE THREAD

**Issue by chimon2000** [dart-lang/pub-dev#3644]
The current method of computing scores is largely influenced by popularity.  This method is flawed in the following ways:

* Popular package creators will almost always start with high scores, while new package creators will almost always start with low scores.

* A package can achieve a high score regardless of criteria that should weigh heavily in scoring, like test coverage.

## Proposed solution

My proposal is to remove overall scoring in favor of three separate scores. 

* Quality - Quality includes considerations such as the presence of code coverage, presence of a CHANGELOG/README file, stability, tests, up-to-date dependencies, custom website, and code complexity.

* Popularity - Popularity indicates how many times the package has been downloaded. This is a strong indicator of packages that others have found to be useful.

* Maintenance - Maintenance ranks packages according to the attention they are given by developers. Release frequency, commit frequency, open issues, issue distribution, etc.

These scores should be displayed in both the list view of packages and the package detail view.

## Alternative solution

Keep overall scoring but combine it in a more meaningful way *and* displaying the score separately.  Here's an example of npm:

![image](https://user-images.githubusercontent.com/6907797/82581896-416bbe80-9b5f-11ea-9f2a-bde72f8f3b5e.png)

Notice that the scoring is broken up into the three categories and the developer can immediately filter on each category.  This gives developers a more accurate depiction of the package at discovery time, without them having to navigate to each package individually.

## Additional context

https://docs.npmjs.com/searching-for-and-choosing-packages-to-download
https://itnext.io/increasing-an-npm-packages-search-score-fb557f859300

**Comment by sigurdm** [comment]
Thanks for the idea.
We are actually currently working on an improved package scoring model - and what we have come up with is very similar to your proposal.

**Comment by chimon2000** [comment]
Awesome, I am glad to hear this is something you are thinking about!

**Comment by isoos** [comment]
@chimon2000: in the light of the new scoring, what would you change/keep from your original suggestions?

**Comment by chimon2000** [comment]
@isoos does the new scoring account for test coverage? If not, that'd be my only nitpick. Otherwise I'm perfectly fine with the latest update.

**Comment by isoos** [comment]
> does the new scoring account for test coverage?

No, not yet. That is something we eventually want to implement, but it has a few security implications that need to be solved upfront.

>  Otherwise I'm perfectly fine with the latest update.

I'll close this issue then. :)
