### ISSUE TITLE
Link is markdown package's README not parsed as link.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/pub-dev#3660]
Link is not being parsed as a link, in markdown's README:

![t5ty4mUNCOm](https://user-images.githubusercontent.com/103167/82959541-ce05ea80-9f6c-11ea-9810-47988a392918.png)

User opened https://github.com/dart-lang/markdown/issues/286. But bug does not appear to be in markdown package; appears to be in pub.dev. Source markdown is:

```markdown
This package offers no features in the way of HTML sanitization. Read Estevão
Soares dos Santos's great article, ["Markdown's XSS Vulnerability (and how to
mitigate it)"], to learn more.

["Markdown's XSS Vulnerability (and how to mitigate it)"]: https://github.com/showdownjs/showdown/wiki/Markdown%27s-XSS-Vulnerability-(and-how-to-mitigate-it)
```

Possible vectors:

* reference link w/o trailing `[]`
* reference link w/ `"` or `()`
* link reference w/ `"` or `()`

**Comment by isoos** [comment]
@srawlins: could you please help me out why the below example wouldn't convert the link? I think it should be the equivalent of the `dart bin/markdown.dart --extension-set GitHubWeb` command that was mentioned in the other issue.

````dart
import 'package:markdown/markdown.dart';

main() {
  final input = '''
This package offers no features in the way of HTML sanitization. Read Estevão
Soares dos Santos's great article, ["Markdown's XSS Vulnerability (and how to
mitigate it)"], to learn more.

["Markdown's XSS Vulnerability (and how to mitigate it)"]: https://github.com/showdownjs/showdown/wiki/Markdown%27s-XSS-Vulnerability-(and-how-to-mitigate-it)
''';
  final doc = Document(extensionSet: ExtensionSet.gitHubWeb);
  final nodes = doc.parseLines(input.split('\n'));
  print(renderToHtml(nodes));
  // prints:
  // <p>This package offers no features in the way of HTML sanitization. Read Estevão
  // Soares dos Santos's great article, ["Markdown's XSS Vulnerability (and how to
  // mitigate it)"], to learn more.</p>
}
````

**Comment by srawlins** [comment]
Ah, it appears to be fixed at HEAD! I can reproduce the bug in 2.1.3 tag, but not at HEAD...

**Comment by srawlins** [comment]
Likely fixed by [this](https://github.com/dart-lang/markdown/commit/5e9163bfe165c420a91ae236440898188d622663) then. Apologies. I will release, and I'll bump this issue to request a version bump.

**Comment by srawlins** [comment]
Released. Bumping to 2.1.4 should solve this.

**Comment by isoos** [comment]
@srawlins: thank you!
