### ISSUE TITLE
Copyright / proprietary issue

### ISSUE THREAD

**Issue by fkhan-hesabe** [dart-lang/pub-dev#3676]
URL: https://pub.dev/packages/flutter_hesabe_payment

We would like to report a copyright / proprietary issue related to the package https://pub.dev/packages/flutter_hesabe_payment 

We, at Hesabe, have not authorized the author (jeetb.wedowebapps@gmail.com) to publish this on the site. In addition to that, there is conflicting information that portrays our system as one of our local competitors. 

We would like you to remove this post and take the necessary action against the author. 

Looking forward to hearing from you.

**Comment by mit-mit** [comment]
Sorry to hear @fkhan-hesabe, can you please contact support@ as per https://pub.dev/policy?

The present issue tracker is meant for issues in the site infrastructure.
