### ISSUE TITLE
Investigate: we should minimize the time of Datastore transactions when uploading

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#3678]

**Comment by isoos** [comment]
After looking into the internals of the upload, I have found a few nits that could be done differently, but the`_updatePackageSortIndex` overshadows all of them:
- in a separate transaction (not sure if that is possible, I think we had issue with that prior),
- it loads all the `PackageVersion` entities,
- and updates some, depending on the order of the version.

I've also found a recent log record with `Sorting by `sort_order` failed, but upload was successful.`.

The worst part of this: we do not use the `sortOrder` field for anything, and I don't think we have used it in the past few years. I think this should be removed, and we ever want to have ordered queries on `PackageVersion`, we should implement it differently.

**Comment by jonasfj** [comment]
Removing `sortOrder` seems like a nice improvement. Given the size of the `PackageVersion` entities, updating a lot of these in a single transaction isn't wise.

(note. we have other work in progress to reduce the size of `PackageVersion` entities).

**Comment by isoos** [comment]
`PackageVersion.sortOrder` was removed in #3691. The other parts of the upload transaction seem to be required, so I'm closing this issue.
