### ISSUE TITLE
Add a Dark Theme for the docs pages

### ISSUE THREAD

**Issue by feinstein** [dart-lang/pub-dev#3679]
The docs pages like: https://pub.dev/documentation/http/latest/http/BaseRequest-class.html are hard to read at night with all that white. A dark theme would be a very welcome addition.

**Comment by jonasfj** [comment]
Yes, I know we've thought about this many times..
(Personally, I often use https://darkreader.org/)

I suspect we would need to file for `dartdoc`, or maybe we can tweak the CSS to just be dark based on [`@media(prefers-color-scheme: dark)`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

**Comment by feinstein** [comment]
I think this should be just a CSS change, maybe add a button to toggle and save this preference on a cookie or something.

**Comment by subzero911** [comment]
+1 for dark theme

**Comment by DeveloperZoneIO** [comment]
+1 for dark theme (for package pages and docs pages)

**Comment by gmpassos** [comment]
+1 for dark theme.

It's just a CSS and a button: you can do it!

**Comment by guidezpl** [comment]
Related: https://github.com/dart-lang/dartdoc/issues/1885

**Comment by isoos** [comment]
Dartdoc is now generated with dark theme support.

**Comment by feinstein** [comment]
Awesome! Many thanks!
