### ISSUE TITLE
Changelog parsing: detect version labels in addition to levels

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#3681]
https://pub.dev/packages/built_value_test/changelog
https://raw.githubusercontent.com/google/built_value.dart/master/CHANGELOG.md

````
# 5.1.1
[...]
## 5.1.0
````

We should be able to detect the version, and treat it as top-level entry instead of the sub-content of the entry above it.

**Comment by isoos** [comment]
We should probably include the pattern of https://keepachangelog.com/en/1.0.0/ too

**Comment by sigurdm** [comment]
IMO https://raw.githubusercontent.com/google/built_value.dart/master/CHANGELOG.md is broken. We should rather try to make a warning in pana/pub publish...

**Comment by jonasfj** [comment]
Different sections levels for different versions in a changelog is not a good pattern we wish to support.

**Comment by jonasfj** [comment]
Notably, it's problematic in cases such as:
```md
# Changelog

## 2.1.0
bla bla bla...

### Migration from
#### 2.0.0
bla bla bla...

#### 1.0.0
bla bla bla...

## 2.0.0
bla bla bla...

## 1.0.0
bla bla bla...
```
