### ISSUE TITLE
Limit number of versions allowed to 2k

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3685]
Do not allow publishing if 2000 versions of the package already exists.

Note. we could warn in publishing emails if the previous publish is less than 24 hours ago, and the package has more than 100 verisons. I'm not sure this is critical.

Stats from public API:
```
No packages with more than 486 exists

packages with >= 25 versions: 776
packages with >= 50 versions: 238
packages with >= 100 versions: 46
packages with >= 200 versions: 5
Packages with >= 200 versions: 
 - analyzer has 254 versions
 - bokain_models has 284 versions
 - fo_components has 486 versions
 - osam has 227 versions
 - viltage has 419 versions
```

**Comment by sigurdm** [comment]
Seems we fixed this (but limited to 1000)
