### ISSUE TITLE
Forbid uploads of packages with pubspec.yaml that can't be JSON

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3692]
YAML can contain values that cannot be presented in JSON.
```
mykey:
  [1,2,3,4,5]: 'value of a composite key'
```
is a good example.

As custom keys are allowed in `pubspec.yaml` we need to:
 * Check that the `pubspec.yaml` can be represented as JSON, and,
 * Have a test case that publishing such a package will fail.

Today, this will presumably throw an unhandled exception when we try to convert the pubspec into JSON. This might be preferable to test this, and convert the exception into something more human friendly.

**Comment by ramyak-mehra** [comment]
@jonasfj 
I would like to work on this. I think the JSON parsing happens here and the exception needs to be handled here [mode_properties.dart](https://github.com/dart-lang/pub-dev/blob/master/app/lib/package/model_properties.dart). Can you please confirm? And if you could tell me any other thing to keep in mind while working on this.

**Comment by jonasfj** [comment]
`pubspec.yaml` contains YAML, not JSON.
Once parsed, a subset of YAML can be represented JSON, we only want to allow this subset in packages that are uploaded.

So we need to write a function that checks if a some value parsed by `package:yaml`, can be represented as JSON.

This is probably best done in:
https://github.com/dart-lang/pub-dev/blob/master/pkg/pub_package_reader/lib/pub_package_reader.dart

Which has other upload-time validations, that cause us to reject a package.

**Comment by ramyak-mehra** [comment]
@jonasfj  can you please point me in the direction where the unhandled exception is being thrown

**Comment by isoos** [comment]
@ramyak-mehra: I think this check should go before this block, as a generic check of the yaml content:
https://github.com/dart-lang/pub-dev/blob/master/pkg/pub_package_reader/lib/pub_package_reader.dart#L81-L97

I think `yaml`'s `ErrorListener` may be not what we are looking for here, as the example in the original report is a valid `yaml` content. Rather we are looking for a validation that tries to convert the `yaml` content to `json`, and if that fails, reports the issue.

**Comment by ramyak-mehra** [comment]
@jonasfj  @isoos would something like this work?
``` dart
try {
    final map = loadYaml(pubspecContent) as Map;
    var decodedMap = json.decode(json.encode(map)) as Map<String, dynamic>;
  } on JsonUnsupportedObjectError catch (e) {
    issues.add(ArchiveIssue('Error parsing pubspec.yaml: $e'));
  }
```

**Comment by ramyak-mehra** [comment]
@isoos  these are the possible combinations I could think of for this, any other would you recommend? 
mykey:
  [1,2,3,4,5]: 'value of a composite key'

[1, 2, 3, 4, 5]:
  key: value

mykey:
  "something"
