### ISSUE TITLE
Urgent requesting to remove initial version from plugin package

### ISSUE THREAD

**Issue by abhimortal6** [dart-lang/pub-dev#3698]
I've developed a S3 uploader plugin but I may have shared some credentials. Which I'm not supposed to share. I have uploaded an instant fix but the initial version 0.0.1 still shows the file which have creds.

can we still remove it?
please remove the version 0.0.1 

here is the link
https://pub.dev/packages/simple_s3/

**Comment by isoos** [comment]
@abhimortal6: Please contact support@ as per https://pub.dev/policy

**Comment by isoos** [comment]
As for the credentials, you should treat them as compromised and revoke them. Even if the package gets deleted, there is a non-zero chance that somebody made a copy of it.

**Comment by abhimortal6** [comment]
yes thanks
