### ISSUE TITLE
Google sign in not redirecting and signing in

### ISSUE THREAD

**Issue by SwissCheese5** [dart-lang/pub-dev#3699]
URL: https://pub.dev/

Google sign in not redirecting me after the pop-up closes.

Most likely related to this issue despite it being a flutter issue. I think it's related, it's the exact same symptoms.
https://github.com/flutter/flutter/issues/52338

**Comment by isoos** [comment]
@SwissCheese5: Could you please share more information about your environment? OS, browser, plugins...

I've just tried to log in on a clean (plugin-free, cookie-free) browser window on Mac Chrome and on Mac Firefox, both latest versions, and it was working fine. It is common that content blockers does not allow some JS code to run, which can break the sign in.

**Comment by SwissCheese5** [comment]
Hm. I disabled privacy badger and ublock origin in an incognito window before on windows 10 in a chrome browser (latest). It didn't work.

Then I tried it again to be absolutely sure after your comment and it... worked... I'm so confused but this can shed some light on the issue I linked at least

**Comment by isoos** [comment]
I usually try it with a brand new window on the "Guest" profile, instead of the incognito window. Not sure what the difference is, but incognito sometimes behaves differently.
