### ISSUE TITLE
Migrate to appengine 0.12.0 using ADC

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3711]
Moving to [appengine version 0.12.0](https://pub.dev/packages/appengine/versions/0.12.0), and update README (and other development documentation) to reflect how development should now be done using:
 * `export GOOGLE_CLOUD_PROJECT=project_id`
 * `gcloud auth application-default login`

**Comment by sigurdm** [comment]
We are currently at appengine v 0.13.9
