### ISSUE TITLE
Temporary dartdoc upload exception surfaced to the UI

### ISSUE THREAD

**Issue by mark-veenstra** [dart-lang/pub-dev#3714]
Our package health receives the error as described in the title.

https://pub.dev/packages/twilio_programmable_video#-analysis-tab-

What can we do about it?

**Comment by isoos** [comment]
@mark-veenstra: thanks for reporting! I looks like this is a bug in our dartdoc processing and content upload, you can do nothing about it. This looks like a temporary issue that may resolve automatically in a day or two, after the backend retries the upload again.

I'll keep the relevant part of the stacktrace in this comment, as we'll need to fix the bug which caused this exception to surface as if it were a dartdoc issue.

````
#0      _validateResponse (package:_discoveryapis_commons/src/clients.dart:852:9)
<asynchronous suspension>
#1      ApiRequester.request (package:_discoveryapis_commons/src/clients.dart:74:22)
<asynchronous suspension>
#2      ObjectsResourceApi.insert (package:googleapis/storage/v1.dart:3366:32)
#3      _MediaUploadStreamSink._startNormalUpload (package:gcloud/src/storage_impl.dart:631:10)
#4      new _MediaUploadStreamSink (package:gcloud/src/storage_impl.dart:543:9)
#5      _BucketImpl.write (package:gcloud/src/storage_impl.dart:194:16)
#6      uploadWithRetry.<anonymous closure> (package:pub_dev/shared/storage.dart:107:27)
<asynchronous suspension>
#7      uploadWithRetry.<anonymous closure> (package:pub_dev/shared/storage.dart)
#8      retryAsync (package:pub_dev/shared/utils.dart:321:24)
<asynchronous suspension>
#9      uploadWithRetry (package:pub_dev/shared/storage.dart:105:9)
<asynchronous suspension>
#10     DartdocBackend.uploadDir.upload (package:pub_dev/dartdoc/backend.dart:134:13)
<asynchronous suspension>
````

**Comment by isoos** [comment]
@mark-veenstra: Our backend did re-generate the dartdoc content and uploaded it successfully, the error report cleared. I'm keeping the bug open as it would be better to not expose temporary issues from our backend.
