### ISSUE TITLE
Unnatural example display

### ISSUE THREAD

**Issue by iLnaar** [dart-lang/pub-dev#3715]
URL: https://pub.dev/packages/swlabels#-example-tab-

Hello colleagues. I am publishing my first trial package on "pub.dev". The project contains an example. This example is a nested Flutter project. The problem is that the sample project is also a sub repository on Github, and it does not appear inside the main repository.

"Pub.dev" does not take this information into account. It displays only one file of the attached project example "main.dart". But this file separately does not carry any useful information. And also the site gives the wrong link to maindart, because in reality on Github the file lies in another repository.

I would like the page to display a link to the Github repository and a link to a separate example project on Pubdev.

**Comment by isoos** [comment]
@iLnaar: you can use other files as example content, see the layout guide:
https://dart.dev/tools/pub/package-layout#examples

e.g. `example/example.md` could contain your links and description to the example sub-repo, with additional information on how to use it.

**Comment by iLnaar** [comment]
> @iLnaar: you can use other files as example content, see the layout guide:
> https://dart.dev/tools/pub/package-layout#examples
> 
> e.g. `example/example.md` could contain your links and description to the example sub-repo, with additional information on how to use it.

The problem is that the "README.md" file must be mandatory as it is shown on Github. But he is the last on the search list. Therefore, the first thing that will usually be used is the "lib/main.dart" file. You can also write an "EXAMPLE.md" file, but it will duplicate the "README.md" file, but you do not want to. Therefore, I have come up with such a solution so far, but it is very bad.
You can write only the "README.md" file, and rename the "lib/main.dart" file, for example, to "lib/_main.dart".

It seems to me that you need to come up with something else ...

In addition, this does not solve the problem of the wrong link:
![image](https://user-images.githubusercontent.com/58101392/84579850-2dbc1c80-adda-11ea-810d-f31e684a6958.png)

**Comment by iLnaar** [comment]
Thanks for the help. I had to abandon internal repositories. I will design a "README.md" for a separate repository.
