### ISSUE TITLE
pub.dev doesn't list package that is available via pub cmd

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/pub-dev#3728]
When searching for `package_resolver` on pub.dev website, I cannot find the package at all. When using it as a dependency from `pubspec.yaml`, I can download and use it normally.

Not sure where the problem might be but I definitely find this strange.

**Comment by daniel-v** [comment]
Never mind! Being a dummy: https://github.com/dart-archive/package_resolver/issues/30

They archived the package, that's why it didn't show up.

**Comment by isoos** [comment]
For reference, it can be visited/read on pub.dev: https://pub.dev/packages/package_resolver, however, as it is marked discontinued, it is not part of standard listing or search.

There is a magic search expression to expose the discontinued packages: https://pub.dev/packages?q=package_resolver+is%3Adiscontinued

You can mark your own packages as discontinued, pub.dev does not check the github repo's status - but maybe we should, /cc @jonasfj.

**Comment by daniel-v** [comment]
Magic! 

I think a better solution/idea would be to tell people that "yo, this project depends on a package that was discontinued". Maybe not when running `pub get` but maybe on `pub upgrade` as I expect that to take longer and tend to pay more attention to the version changes.

Maybe, the author of the package could provide a "discontinuation message" as well that would redirect me to `package_config` in this case. This would be really nice!

**Comment by isoos** [comment]
> Maybe not when running pub get but on pub upgrade as I expect that to take longer and tend to pay more attention to the version changes.

Yeah, there is something planned in this area: https://github.com/dart-lang/pub/issues/2361
