### ISSUE TITLE
Feature request: add a "recommended" or "similar" packages.

### ISSUE THREAD

**Issue by Luckey-Elijah** [dart-lang/pub-dev#3738]
* It would be really neat (and help the community out when browsing the many packages) to see a "recommended packages" or "similar packages" section of pages. 
* For example, it would appear on the side bar underneath the "Publisher", "About", "Dependencies, etc. section of a page.
* Would make recommendations like:
  * "Commonly used together."
  * "Package doesn't work like you want? Look into these."
* Would this be a useful part of the package browsing experience?

**Comment by sigurdm** [comment]
I think "recommended" is covered by flutter-favorites.

The similar packages might be covered by https://github.com/dart-lang/pub-dev/issues/5219

**Comment by sigurdm** [comment]
I'll close this in favor of these other items.
