### ISSUE TITLE
Search UI for packages with null safety

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#3745]
https://github.com/dart-lang/pub-dev/issues/3503 added tagging for packages with null safety. This adds a search UI option for searching only packages that have null safety.

**Comment by mit-mit** [comment]
Note: We'll likely need support for searching in pre-release packages as there is how we currently think null safety versions are likely to first be published.

**Comment by leafpetersen** [comment]
Is this still planned?  If so, for when?

**Comment by isoos** [comment]
Launched.
