### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by AndroidNils** [dart-lang/pub-dev#3771]
## Description
It seems to me that the search on "PubDev" is very hard. For me its very difficult the find the right packages, if I don't know the exact name.

### Example
I searched for the package `flutter95`, but I didn't had the exact name in mind. So I tried this names:
* flutter 95
* flutter_95
* 95 flutter
* flutter-95

But the result was this (same result for all mentioned combinations):
![image](https://user-images.githubusercontent.com/24459435/86479013-9b10fc80-bd4b-11ea-9b3f-5fe82e904cd1.png)

No result for all three packages.

I have to search exactly `flutter95` to find the package:
![image](https://user-images.githubusercontent.com/24459435/86479126-d6abc680-bd4b-11ea-9716-0a5548d558bc.png)

This only one example. I had this issue several times.

**Comment by isoos** [comment]
@AndroidNils: Thanks for reporting it!

The current index doesn't handle short numeric substrings in names like in this case, but I'll take a look and check how we can support it better.

**Comment by AndroidNils** [comment]
@isoos Thanks for quick fixing!
