### ISSUE TITLE
Strange Behavior Scoring/Sorting

### ISSUE THREAD

**Issue by felangel** [dart-lang/pub-dev#3779]
URL: https://pub.dev/packages/flutter_bloc

<Describe your issue or suggestion here>
Hello 👋 

I recently noticed that the `flutter_bloc` package score dropped to 99 but is still sorted with other packages with a score of 100. Is this expected behavior? Seems to me like the score is still 100 but is being rendered as 99 (not sure if that's possible). Thanks!

The [google_fonts](https://pub.dev/packages/google_fonts) package seems to be in a similar spot.

![Screen Shot 2020-07-06 at 10 09 37 AM](https://user-images.githubusercontent.com/8855632/86609053-fa9c2180-bf70-11ea-9683-37ca3a46fbb8.png)

**Comment by isoos** [comment]
@felangel: Thanks for reporting it!

Yes, it is somewhat expected. We've recently started to use the number of likes as part of the default ranking for a package (alongside the package score), and while it is not reflected in the total score, it is part of the listing order.

Internally the score is not `int`, it is rounded for displaying only - the sort order was on the original `double` value.

We are also working towards updating the display of the score components differently, it hopefully removes such confusing ordering in the future.
