### ISSUE TITLE
Allow marking specific package versions as "broken"

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#378]
We need a way to handle "oops" publishes.

Examples:

* analyzer 0.30.0+3 – worthless, need +4
* analyzer 0.30.0+1 – also broken, need +2
* isolate 1.1.0 - bad SDK constraint. Allows older Dart versions to get package that uses generic methods - which causes crashes.
  * Fix PR here - https://github.com/dart-lang/isolate/pull/17

**Comment by kevmoo** [comment]
Related to https://github.com/dart-lang/pub-dartlang-dart/issues/289 – although I think there are seperate concepts

**Comment by isoos** [comment]
What do we need to do with them, e.g.
- Hide?
- Delete (from Datastore and blob storage)?
- Mark them as broken? (how?)

**Comment by kevmoo** [comment]
Current idea:

* By default, don't return them when accessing https://pub.dartlang.org/api/packages/async
* Or, return them, but flagged broken
* Then add options to the pub client to "do the right thing" – let a user override, etc...

Highlight them as broken in the version list. If it's the "latest" one, maybe show the one before by default and give a pointer to the broken one in a subtle way

**Comment by isoos** [comment]
Why not just delete them? (Related: who gets to approve what to consider broken?)
If they are truly broken, there is no reason for anybody to rely on them or use them, is there?

**Comment by kevmoo** [comment]
There is some weirdness. If a user (for some reason) has depended on a broken package, we have a bit of a promise to honor it. We want pub to "feel" immutable.

**Comment by mkustermann** [comment]
Is that the same as https://github.com/dart-lang/pub-dartlang-dart/issues/289 ?

**Comment by mkustermann** [comment]
There have been discussions about this before, here are a few points:

   * usually constraints don't contain `<a.b.c>+...` as upper bound, so if a package fixes the problem by doing a bugfix with a `+1` all clients will get the fixed version.
   * only the uploader has the right do change anything, mark it deprecated/buggy/whatever
   * we should avoid deleting as much as we can, since users might have `pubspec.lock` files which refer to these versions. If we delete them a `pub get` which used to work will suddenly fail
   * there is the question what happens if an author accidentally uploaded a package with confidential information in it (e.g. ssh keys, passwords, ...): this is one of the few cases which supports the deletion case (even though the uploader should consider everything as being leaked the moment he published it)

Before implementing something, we should give it enough thought and come up with a good design and let other people provide feedback on the design.

I don't think this has super high priority, in particular given all the other things that are on the road map.

**Comment by kevmoo** [comment]
> Before implementing something, we should give it enough thought and come up with a good design and let other people provide feedback on the design.

Agreed! We should do zero impl here. Just tracking it.

> I don't think this has super high priority, in particular given all the other things that are on the road map.

Also agree.

**Comment by mit-mit** [comment]
Specific idea discussed:

* Allow publishers to mark a specific version as 'broken'
* On a package page, show the broken versions as such
* On the package list page, show the latest version *not marked broken*
* If pub asks for a specific version, and that is known broken, still return it
* if pub asks for a list of versions (eg. in `pub upgrade`), exclude the broken versions from the list

**Comment by kevmoo** [comment]
Another example: https://github.com/dart-lang/args/pull/89

Would be great to mark `1.3.0` as "broken" – since it allows folks on pre 1.24 to get a package with `FutureOr`

**Comment by sigurdm** [comment]
Could a bugfix release (One that increases the third digit 1.0.0 => 1.0.1) automatically mark the previous version as broken?

**Comment by isoos** [comment]
> Could a bugfix release (One that increases the third digit 1.0.0 => 1.0.1) automatically mark the previous version as broken?

Maybe a `+1` release. `1.0.1` is often adding a really minor feature or extra option.

**Comment by kevmoo** [comment]
No automatic here. In both cases I may be just fixing docs, or the
changlog, or the pubspec description.

Marking a broken version should always be an EXPLICIT thing IMHO.

**Comment by kevmoo** [comment]
See my other request about arbitrary messages from server. One could image
sending a URL down to the client in the +1 case: "was the previous release
broken in some way? If so, click here to mark it as such: ..."

**Comment by jonasfj** [comment]
I think that:

A) Allowing _package retraction_ within the first 24, 48 or 72 hours would fix many of cases where a broken package is accidentally published.

B) Users who don't use caret notation, but pin versions in the `pubspec.yaml` should be warned in `pub upgrade`. And that generally we should discourage version pinning in `pubspec.yaml`.

If users aren't doing version pinning in the `pubspec.yaml` what is the desire for marking a package as broken?

**Comment by kevmoo** [comment]
> I think that:
> 
> A) Allowing _package retraction_ within the first 24, 48 or 72 hours would fix many of cases where a broken package is accidentally published.

We need to keep this period short. I'd say 12 hours. Once folks download, everything assumes it doesn't change.

> B) Users who don't use caret notation, but pin versions in the `pubspec.yaml` should be warned in `pub upgrade`. And that generally we should discourage version pinning in `pubspec.yaml`.

> 
> If users aren't doing version pinning in the `pubspec.yaml` what is the desire for marking a package as broken?

The issue is that `pub get` (I think) is much more used than `upgrade`. The Flutter command AFAIK runs get a lot, but not upgrade.

It's also not just about the direct user. Flutter, for example, pins all of its dependencies, which is inherited by any flutter app.

**Comment by jonasfj** [comment]
> It's also not just about the direct user. Flutter, for example, pins all of its dependencies, which is inherited by any flutter app.

Giving them a message that one of their dependencies is broken, won't help much if the dependency is version locked by flutter.

**Comment by Hixie** [comment]
It's common for packages to be published and later found to be fundamentally broken, and yet for the next version to not be usable, and so the broken version to get selected. For example:

A depends on B^1.0 and C^1.0.
B uses C but doesn't expose it.
B 1.0 depends on C ^1.0.
B 1.1 depends on C ^1.1 and is broken.
B 1.2 depends on C ^2.0.

A is now broken, and without explicitly pinning its dependency on B, or going through the hard work to handle the breaking change involved in going from C 1.0 to C 2.0, it cannot be fixed.

If we could just have B's authors mark B 1.1 as bad, then A would just fall back to B 1.0 happily.

**Comment by jonasfj** [comment]
> If we could just have B's authors mark B 1.1 as bad, then A would just fall back to B 1.0 happily.

I'm convinced this has merit :)

**Comment by kevmoo** [comment]
FYI, we just hit this AGAIN with 0.39.2 (0.39.2+1 fixed things)

This with https://github.com/dart-lang/pub-dev/issues/2457 would be great – if a user runs `pub get` they can get a warning that they should run`pub upgrade` to get the latest

**Comment by franklinyow** [comment]
This happen again for package:meta.  [Post-morten](https://docs.google.com/document/d/14r_tNTasKpfCo4zQWqLXmaelzGypJAFv1EnkNW6_hcA/edit?usp=sharing)

**Comment by kevmoo** [comment]
Happened again with pkg:analyzer today!

**Comment by devoncarew** [comment]
And again - the same issue as https://github.com/dart-lang/pub-dev/issues/378#issuecomment-848320549 - but more severe because package:meta is pinned at a specific version by stable flutter releases, which transitively pins analyzer, package:build, ...

**Comment by kevmoo** [comment]
See also

https://github.com/dart-lang/sdk/issues/46583
https://github.com/dart-lang/sdk/issues/46687

**Comment by szakarias** [comment]
Closing. The [package retraction feature](https://dart.dev/tools/pub/publishing#retract) launched with Dart 2.15.
