### ISSUE TITLE
I just uploaded my package with different account. Is it possible to remove my package from it so that i republish it with correct account

### ISSUE THREAD

**Issue by jaiswalshubham84** [dart-lang/pub-dev#3781]
I just uploaded my package with different account. can it is possible to remove my package from it so that i republish it current account.
Link to package is 
https://pub.dev/packages/launchexternalapp/versions/0.0.1

Thanks in advance.

**Comment by isoos** [comment]
@jaiswalshubham84 You can see our package removal policy here: https://pub.dev/policy

In this case I'd suggest that you add account B as a second uploader to the package, then with account B's credentials you can remove account A (the current uploader).

**Comment by jaiswalshubham84** [comment]
@isoos 
Yeah got your point but the package that I uploaded is meant to be published from the account of the organization in which I am working.
So if you can delete it, it will very helpful and easy situation for me.

Thanks in Advance.

**Comment by isoos** [comment]
I'm sorry, but you will need to update the uploaders the way I've suggested (let me know if you need more help on that one). If the organization is using a publisher account, you can also transfer the package to the publisher if your account is administrator in both the publisher and the package.
