### ISSUE TITLE
dartdoc category support

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3793]
dartdoc generation should support `categories` and `categoryOrder` from `dartdoc_options.yaml`.

See: https://github.com/dart-lang/dartdoc#advanced-features

**Note**, we don't want to allow other options to be customized, but these seem reasonable.

**Comment by jonasfj** [comment]
@isoos I think we fixed this didn't we?

**Comment by isoos** [comment]
Yes, we have them as pass-through keys:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/dartdoc/dartdoc_options.dart#L36-L44
