### ISSUE TITLE
analyzer: Free disk space (739 MB) is lower than threshold value 746 MB.

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3801]
From logs:
> Free disk space (739 MB) is lower than threshold value 746 MB. Reporting instance permanently unhealthy. Note: different instances will have a different threshold value.

Seems we should clear `pub-cache` every once in a while.. Maybe when we have less than 2GB space available, or maybe every 1000 packages analyzed.

This is a trigger for the `app-unhealthy` metric.

**Comment by isoos** [comment]
We should verify if these cleanup rules are still applied and working:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/shared/tool_env.dart#L12-L26

**Comment by isoos** [comment]
#3817 fixed it.
