### ISSUE TITLE
Unable to sign in on pub.dev website

### ISSUE THREAD

**Issue by abhinav2127** [dart-lang/pub-dev#3822]
I tried clicking on the `Sign in` but unable to login. I saw console and saw following issue.

Please refer to attached snapshot.

![image](https://user-images.githubusercontent.com/12818644/87345014-04bfb080-c56d-11ea-9e7a-d480820b2305.png)

Since this is the first time i'm facing this issue. Not sure why it is blocked.

![image](https://user-images.githubusercontent.com/12818644/87345121-30429b00-c56d-11ea-85e7-2f18edaae78c.png)

**Comment by isoos** [comment]
@abhinav2127: based on the console logs, you are using content blocker and/or privacy protection extensions. Please unblock `pub.dev` on one or all of those, as they block the JS-based OAuth2 mechanism that we are using for the sign-in.

**Comment by abhinav2127** [comment]
Thanks @isoos, it worked fine.

Closing this issue.
