### ISSUE TITLE
Font in the new site design

### ISSUE THREAD

**Issue by Gyoko** [dart-lang/pub-dev#3835]
URL: https://pub.dev/

Can you please revert back the font changes made in the new design? The current font is too thin and makes it harder to read the page quickly. If you don't want change the font then please increase the weight of the current one and change the color of the main text back to black. 

The current text color (#212529) combined with a lot of spacing between the page elements on a larger screen makes it frustrating to navigate pages.

**Comment by jonasfj** [comment]
Please leave a thumbs up if thicker font would be preferable to you.

**Comment by AndroidNils** [comment]
For me is the biggest problem the thin font. This makes it hard to read. It's much more readable with 110% oder 125% zoom 👍

![image](https://user-images.githubusercontent.com/24459435/87607162-fef8d500-c6fc-11ea-944e-9d9715f5d837.png)

**Comment by Gowtham-mg** [comment]
Ya its true..increasing font weight is really a good option. Even we expect darkmode, which can reduce the kind of eyestrain issues

**Comment by isoos** [comment]
We've released a new version with increased font-weights.

**Comment by Gyoko** [comment]
@isoos 
The new UI has still ways to go, but it's definitely better, thanks

**Comment by isoos** [comment]
> The new UI has still ways to go, but it's definitely better, thanks

Feel free to open specific suggestions! :)
