### ISSUE TITLE
Poor legibility and contrast ratio in code snippets

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/pub-dev#3846]
Related to https://github.com/dart-lang/pub-dev/issues/3835, the contrast ratio of certain colors in code snippets (particularly comments), paired with the thin default font weight, makes code snippets difficult to read.

I think the default font weight should be increased, and the colors should be adjusted to improve contrast.

Lighthouse report indicating the contrast is too low:
<img width="606" alt="Screen Shot 2020-07-16 at 10 48 13 AM" src="https://user-images.githubusercontent.com/1713967/87704870-e070f900-c751-11ea-93c3-c2d59c1edcfb.png">

Screenshot:
<img width="565" alt="Screen Shot 2020-07-16 at 10 43 47 AM" src="https://user-images.githubusercontent.com/1713967/87704565-735d6380-c751-11ea-84af-d601eb64cb92.png">

**Comment by isoos** [comment]
We've released a new version with increased font-weights.
