### ISSUE TITLE
License link isn't highlighted for some packages. 

### ISSUE THREAD

**Issue by daniel-maxhari** [dart-lang/pub-dev#3856]
I noticed that for some packages, including the mine, the "LICENSE" link (go to metadata, under License) is not highlighted. 
Also, if you click it, nothing happens. 

What's the root of the problem? 

Link of my package: https://pub.dev/packages/dynamic_text_highlighting

**Comment by isoos** [comment]
@daniel-maxhari: Thanks for reporting this. The core reason was that our URL-utility that links to these files didn't handle the special case of `.git` in the repository/homepage URL in your `pubspec.yaml`. I've filed a PR in pana to fix it.

**Comment by daniel-maxhari** [comment]
Thank you. Should I do something to make the changes on my package or it is all handled by the program?

**Comment by isoos** [comment]
@daniel-maxhari: no need to do anything on your side. It will take a while until it gets released (depending on other stuff in our release schedule), but once it is released, the site will get an update for all versions.

**Comment by daniel-maxhari** [comment]
Thanks for all your help and clarification 💯
