### ISSUE TITLE
HTML <pre> tag support for MarkDown files on pub.dev

### ISSUE THREAD

**Issue by mannprerak2** [dart-lang/pub-dev#3881]
URL: https://pub.dev/packages/ffigen

The `<pre>` tag doesn't seem to work properly for markdown files on **pub.dev**, however, it is working on **Github**.

Here are the files for comparison
Pub - https://pub.dev/packages/ffigen#configurations
Github - https://github.com/dart-lang/ffigen#configurations

Should this be supported? If not, is there any workaround?

**Comment by isoos** [comment]
@mannprerak2: thanks for reporting this! It looks like this is because our `<pre>` styles are expecting an additional `<code>` element inside the `<pre>`. I'll take a look on how we can update this.

**Comment by mannprerak2** [comment]
Hi @isoos 
Has this been updated on pub.dev?

I can still see indentation issues and there is no syntax highlighting on Pub.dev either.
Pub link:  https://pub.dev/packages/ffigen#configurations 
GitHub link https://github.com/dart-lang/ffigen#configurations (Working on github)

**Comment by mannprerak2** [comment]
This may help too -

This does give the correct syntax highlighting and indentation on Pub but has no syntax highlighting for Github.
```html
<pre><code>
some-yaml: hello
more:
  - 'yaml'
</code></pre>
```
If I add `lang="yaml"` attribute to `<pre>` tag, 
```html
<pre lang="yaml"><code>
some-yaml: hello
more:
  - 'yaml'
</code></pre>
```
the syntax highlighting works on Github, but all indentation is stripped off for Pub.

**Comment by isoos** [comment]
> I can still see indentation issues

Not sure where to look, could you please add a screenshot with annotation on what seems to be wrong?

> no syntax highlighting

We are using `highlight.js` for the syntax highlighting, and you can see on your block where you've specified <code>```yaml</code> that it is working (right after "`Add configurations to Pubspec File:`". The markdown formatting generated `language-yaml` as the CSS class and hljs does the rest.

Your inlined `<pre>` block inside the table has only `lang="yaml"`, which we are not handling, and `highlight.js` does not recognize either. Please open a separate issue for that, we also accept PRs handling it, but considering all the other things on our plate, I don't think it will be only in our backlog of things to implement some time in future.

**Comment by mannprerak2** [comment]
The output for this code 
```html
<td><pre lang="yaml">
headers:
  entry-points:
    - 'folder/**.h'
    - 'folder/specific_header.h'
  include-directives:
    - '**index.h'
    - '**/clang-c/**'
    - '/full/path/to/a/header.h'
  </pre></td>
```
is the following (can be found under the [configuration](https://pub.dev/packages/ffigen#configurations) section of the readme)
<img width="500" alt="Screenshot 2020-09-07 at 9 55 34 AM" src="https://user-images.githubusercontent.com/31154435/92348284-4b0a3980-f0f0-11ea-8ad7-59cf54f3b8f0.png">

Removing the `lang="yaml"` tag, however, fixes the indentation.

---

I was also [experimenting on a dummy package](https://pub.dev/packages/m_android_notification_listener)
Even when adding an additional `<code>` element
```html
<td><pre lang="yaml"><code>
comments:
  style: doxygen
  length: full</code></pre>
    </td>
```
We still see indentation issues when using `lang="yaml"`.
<img width="787" alt="Screenshot 2020-09-07 at 10 04 46 AM" src="https://user-images.githubusercontent.com/31154435/92348908-244d0280-f0f2-11ea-9b4e-cd104bc4ab59.png">


I could use `lang="language-yaml"` but that does not work on Github (`lang="yaml" does).

**Comment by mannprerak2** [comment]
I have opened a new issue for this #4010
