### ISSUE TITLE
Pub.dev shows my old email address

### ISSUE THREAD

**Issue by jascodes** [dart-lang/pub-dev#3884]
I showes account@jas.bio but my current google account is mail@jas.bio. I didn't find ability to update it. If it has to be requested, then I formally request to switch my email to mail@jas.bio.

Thx

**Comment by isoos** [comment]
@jascodes: you should use account "A" to add account "B" as an uploader to the same package (`pub uploader add B`). Later, using account "B" you can remove account "A".

**Comment by isoos** [comment]
More on this: https://dart.dev/tools/pub/cmd/pub-uploader

**Comment by jascodes** [comment]
Hey @isoos 

Thanks 🙏 for quick response.

I already tried that. The problem is mail@jas.bio is being used as Authentication account for account@jas.bio(old email). When I tried to add mail@jas.bio to a package, it wanted Auth and when I tried to auth with google account linked to mail@jas.bio it gave error since it was already linked to account@jas.bio

I will be awefully thankful if you can update it from backend and I suggest allowing to update email on pub.dev as email change quiet coomon requirement and unlike packages which need to be immutable, it should not cause any issues if it is mutable.

Stay Safe 
Jas

**Comment by jonasfj** [comment]
Please report the issue to support@pub.dev

If it's the same google account, then changing the email should work with pub.dev (this could be a bug, if it doesn't).

If your first login was prior to 2019 (April I believe), and you haven't logged in again, before changing your email, then a bug in pub.dev at the time may have caused two accounts to be created.. this we can remedy.

If you've migrated from one google account to another, then ordinary account recovery is the path..

Drop an email to support@pub.dev and I'll take a look when I'm back in August.
