### ISSUE TITLE
Closed source code distribution

### ISSUE THREAD

**Issue by Defuera** [dart-lang/pub-dev#3887]
Hello, I'm working on Dart SDK for flutter applications. It is closed source. But I cannot find any way to distribute it.

I've investigated following possibilities:

- Building obfuscated and compiled package, like Android .apk
- Distributing via pub.dev the way client does not have access to source code.

But non of this options seem to be feasible. Is there's really no way to distribute closed source code with dart?

Thank you.

**Comment by isoos** [comment]
From our [policy](https://pub.dev/policy):

> Pub.dev is intended to enable developers to share Dart packages with other developers. Thus, these packages are expected to contain Dart source code, assets (images, audio files, etc.) directly related to the main function of this source code, and possibly, additional source code in other programming languages with which the Dart code interfaces. Any other content is not allowed on pub.dev, and may be subject to moderation at the discretion of the pub.dev moderators, up to and including unpublishing of a package.

We are here to service public Dart packages with their source code available / visible / unobfuscated. If you wish to distribute a closed-sourced binary, you shall seek a different distribution channel for that.

**Comment by Defuera** [comment]
@isoos Thank you very much for your response. Would you be so kind to give me some directions. I'm really lost on this subject.
