### ISSUE TITLE
Pub.dev branding guidelines.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/pub-dev#3889]
pub.dev doesn't seem to have a brand identity and therefore no branding guidelines. 

- what icon/colors should be used to represent pub.dev?
- why should I use pub.dev?

I don't think I need to list any downsides here, people who are specialized in branding/corporate identity should deal with this. This is a missed opportunity and will hurt the Dart ecosystem over the long term.
Could someone make sure that this is addressed?

/cc @timsneath @mit-mit

**Comment by isoos** [comment]
I think in the absence of pub.dev-specific branding guides, the Dart branding guide applies: https://dart.dev/brand

**Comment by timsneath** [comment]
Yeah, that's correct. pub.dev is not a distinct brand.
