### ISSUE TITLE
I hard error with the image_gallery_saver

### ISSUE THREAD

**Issue by winsweba** [dart-lang/pub-dev#3891]
URL: https://pub.dev/packages/image_gallery_saver

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_gallery_saver:compileDebugKotlin'.
> Could not resolve all artifacts for configuration ':image_gallery_saver:debugCompileClasspath'.
   > Failed to transform artifact 'kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.3.72)' to match attributes {artifactType=android-classes, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\Winchester\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.3.72\8032138f12c0180bc4e51fe139d4c52b46db6109\kotlin-stdlib-1.3.72.jar.
         > Cannot parse result path string:

**Comment by isoos** [comment]
@winsweba this repository is for the pub.dev site, not individual packages. Please report you issue in the package's issue tracker (e.g. https://github.com/hui-z/image_gallery_saver/issues in this case).

**Comment by winsweba** [comment]
thanks
