### ISSUE TITLE
Pub dev analyzer still uses 1.17.5 flutter version

### ISSUE THREAD

**Issue by TatsuUkraine** [dart-lang/pub-dev#3913]
Flutter 1.20 was released in the stable channel, but pub.dev still uses 1.17.5 to analyze packages.

So if a package has restrictions on Flutter version, for instance because it's not compatible with prev version, analizer can't properly process such package

**Example package**
https://pub.dev/packages/sticky_infinite_list/score

![Снимок экрана 2020-08-05 в 22 19 19](https://user-images.githubusercontent.com/621542/89454674-bb2c4500-d769-11ea-87e8-a5882f95c438.png)

**Comment by isoos** [comment]
Thanks for reporting! Unfortunately we do not have an automatic upgrade process yet, and we need a bit of time until a tool-environment change like this (e.g. #3912) reaches the production site. We will deploy the new version with the upgraded Flutter SDK in the coming days.

**Comment by isoos** [comment]
#3912 was deployed. It may take a while to analyze all packages with the new Flutter SDK, you don't need to do anything, it happens automatically.
