### ISSUE TITLE
Pub scoring penalises cli tool packages for not supporting js

### ISSUE THREAD

**Issue by maks** [dart-lang/pub-dev#3923]
Currently pub dev penalises Dart SDK CLI tool packages (eg. https://pub.dev/packages/dsg/score) due to them not supporting js: 
>Package not compatible with runtime js

where as I don't think it's really viable for these kinds of tools to support JS as they are intended to be specifically used in a CLI environment and in fact for my package I use `dart2native` to supply executables for linux, macos and win already in the packages github repo and of course it can also be installed via `pub global activate` as well.

Is there perhaps a pubspec.yaml that could be used to indicate the nature of the package being for cli tooling only so that it wouldn't then be checked for js support?

**Comment by sigurdm** [comment]
Basically the same as https://github.com/dart-lang/pana/issues/720

**Comment by sigurdm** [comment]
Closing as duplicate
