### ISSUE TITLE
Mainpage SearchBar: default auto-hint is " filter, vomiting, female puke, female vomit, vomit, toilet seat up" 

### ISSUE THREAD

**Issue by van-8** [dart-lang/pub-dev#3924]
URL: https://pub.dev/packages?q=form&sort=popularity

The dropdown list of auto-hint search Strings is:
`filter, vomiting, female puke, female vomit, vomit, toilet seat up`

I have nothing like this in my search history, but just to double check this occurs also in Incognito Mode. 
Not clear if this is intentional...

<img width="624" alt="Screen Shot 2020-08-10 at 14 45 42" src="https://user-images.githubusercontent.com/28463475/89757824-ec659600-db18-11ea-95f2-a170cab598b5.png">

**Comment by isoos** [comment]
@van-8: What's your region (country, ISP) and locale (default language settings)? Could you please repeat the same with different profiles and/or "Guest mode"?

I am not experiencing similar suggestions, and we are not actively fetching any hints from third-party services. We could set the `autocomplete` property to an explicit `off` value though...

**Comment by tusharojha** [comment]
Search suggestions come from your last searches on the same website.
Please make sure that you have not searched these terms before on pub.dev.
Also, As per my knowledge chrome shares configurations & cache memories from default mode to incognito mode (not vice-versa).

**Comment by van-8** [comment]
@isoos I am located in Beijing, China. Default language of browser is English (American).

This only occurs in **Chrome** 84.0.4147.105 (Official Build) (64-bit). I did search `filter` before, but it did not save my searches for dozens of other search terms from the past few months.
**Safari**: no auto-suggestions, even though I've searched on the site before.
**Firefox**: proper auto-suggestions I've searched on the site before.

@tusharojha: I understand how suggestions normally work. I wouldn't choose to publicly humiliate myself, except that:
(a) I've never searched those terms before (on any website, especially not Pub.Dev) or even thought about those words in those combinations, 
(b) observed the same issue in Incognito Mode, 
(c) genuinely confused, 
(d) want the Flutter/Dart community to thrive. 

If it's just some bizarre cookie or tracking recognition localized only to me alone, please go ahead and close the issue. I'll consider myself a victim of something weird, and laugh the whole thing off 😂. Wouldn't want to waste anyone's valuable time.

**Comment by van-8** [comment]
1. Cleared all cookies in Chrome from pub.dev; still encountered issue.
2. Cleared all browsing history, cookies, cache, autocompletes from all websites in Chrome; still encountered issue.
3. Restart Macbook Pro; still encountered issue.
4. Signed out of my Chrome profile. Still encountered issue.
5. **Hard reset my Chrome profile**. Log back in with clean profile. **Issue no longer occurs.**

I'm guessing it must be linked with Chrome profile? I'm still perplexed, as I've never searched those terms before (on any website, but especially not pub.dev) but issue has disappeared.
