### ISSUE TITLE
Missing package information/metadata on small screens

### ISSUE THREAD

**Issue by davidmartos96** [dart-lang/pub-dev#3930]
WIth the new design of the website, accesing to the package repository or API documentation is not possible anymore from a mobile device browser. Previously, those links could be accessed at the very bottom of the website.

![image](https://user-images.githubusercontent.com/22084723/89999440-14770580-dc8f-11ea-8480-14f1e6bb680d.png)

**Comment by isoos** [comment]
@davidmartos96: on the mobile view, above the tabs, you should be able to click on this metadata header (either the label or the arrow):

<img width="321" alt="Screenshot 2020-08-12 at 11 41 48" src="https://user-images.githubusercontent.com/4778111/90000512-8c91fb00-dc90-11ea-9262-6764e3195c2c.png">

Does that work you?

**Comment by davidmartos96** [comment]
@isoos Oh, I completely missed it! Yes, it works perfectly. Thanks!
