### ISSUE TITLE
Sign in button

### ISSUE THREAD

**Issue by paybackweb** [dart-lang/pub-dev#3936]
URL: https://pub.dev/

The sign in button is not working.

**Comment by isoos** [comment]
@paybackweb: What's your environment? Any content blockers or extensions?

I've just checked it with Chrome and Firefox (both on Mac), and it was working.

**Comment by felangel** [comment]
Not working for me either on Chrome MacOS.

**Comment by isoos** [comment]
@felangel: Any content blockers or extensions?

**Comment by felangel** [comment]
@isoos just google translate

**Comment by paybackweb** [comment]
> @paybackweb: What's your environment? Any content blockers or extensions?
> 
> I've just checked it with Chrome and Firefox (both on Mac), and it was working.

I disable Add block plus extension it works now. Thanks!
