### ISSUE TITLE
Reject invite should not require a sign-in

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3941]
When arriving on an invitation page (from the email link), we should probably display the invitation, and allow users to reject the invite without sign-in.

However, if they accept the invite, they must ofcouse sign-in, so if not authenticated this button needs to trigger a login-flow.

Note. we also need to ensure that it says in the invite that accepting it, will create an account.

**Comment by isoos** [comment]
How about to display the invite without authentication, but don't allow any action without logging in? There is no harm when the invite is not acted on it: if they do nothing, the invite will expire in a week and will become void anyway.

**Comment by jonasfj** [comment]
I'll dig into whether we want unauthenticated invite flow as this would imply.
