### ISSUE TITLE
Bring back the Search bar and add a Dark Theme

### ISSUE THREAD

**Issue by brazc** [dart-lang/pub-dev#3945]
The old version of pub.dev had a search bar on the header of the page.  
It was removed with the new update.  
  
The search bar was pretty useful when you had to search for packages one after another.
Now I have to go back to the homepage to search for another package. This feature is much needed I believe.  
  
Also, its 2020. We need a dark theme for pub.dev.

**Comment by satvikpendem** [comment]
#3834

**Comment by jonasfj** [comment]
Please upvote in #3834
