### ISSUE TITLE
The site should always have a search bar on the top

### ISSUE THREAD

**Issue by feinstein** [dart-lang/pub-dev#3948]
Sometimes I want to update many of my packages, but I like to read the Changelogs for all of them before I do.

The current version of the website forces me to go back to the main page in order to search for something else, it would be much more pleasant to have a search bar on the side of the pub logo:

![image](https://user-images.githubusercontent.com/8120472/90668795-fc6f2b00-e226-11ea-8863-50d6d376ee0b.png)

This way from any package we can search for another one immediately.

I could be even a magnifying glass icon that expands into a search bar when the mouse hovers or clicks on it (thinking on mobile access).

**Comment by isoos** [comment]
We've released a new version that has a search icon / unfolding search input at the top nav bar. I hope that resolves this issue.

**Comment by feinstein** [comment]
It does, but I think it could be refined a bit more 😅 

I am using Firefox, the cursor turns to an I Beam when I hover:

![image](https://user-images.githubusercontent.com/8120472/91491488-7ab47880-e88a-11ea-92eb-55575c020c9a.png)

It could bring a lighter-color circle on the back of the search icon, maybe even have an ink splash when we click (ok that's maybe too much lol). And only when there's an actual text input the mouse cursor turns to an I Beam cursor.
