### ISSUE TITLE
Please put the persistent search bar back!

### ISSUE THREAD

**Issue by bagintz** [dart-lang/pub-dev#3958]
URL: https://pub.dev/packages?q=[anything]

I don't see a button or persistent search bar, it makes it very hard to switch between packages when you are "deep" into one particular package.

To repeat:
1) Go to pub.dev
2) Search for a package (e.g. firebase_core)
3) Click on result
4) First page shows the package with a "Back to search", which is nice, but then...
5) Click on "Example"
6) Get trapped on a page with no link to search or box to go to a new package and no clear direction of how to navigate "out".

![Screen Shot 2020-08-23 at 1 05 51 PM](https://user-images.githubusercontent.com/5341290/90984214-998cd500-e541-11ea-8d81-75a21d207ca9.png)

Thanks!!

**Comment by isoos** [comment]
We've released a new version that has a search icon / unfolding search input at the top nav bar. I hope that resolves this issue.

**Comment by bagintz** [comment]
Thank you!

**Comment by orsenkucher** [comment]
@isoos @jonasfj yo, just saying, further improvement is possible 🥰 
![image](https://user-images.githubusercontent.com/15790628/103356716-2e887780-4aba-11eb-9ae3-d3fa46cdea30.png)
![image](https://user-images.githubusercontent.com/15790628/103356728-38aa7600-4aba-11eb-9524-9704068ac628.png)

---

Consider making search box always open, consider adding shortcut to focus on it. Search is an essential thing, why to hide it?
![image](https://user-images.githubusercontent.com/15790628/103356870-89ba6a00-4aba-11eb-879f-2e1f8afde96a.png)
