### ISSUE TITLE
could you support groupId in pubspec.yaml dependencies?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/pub-dev#3969]
there have many lib not maintain in pub, such as mysql ...

**Comment by isoos** [comment]
@Silentdoer: could you please explain what the groupId would do in the pubspec.yaml?

**Comment by Silentdoer** [comment]
> @Silentdoer: could you please explain what the groupId would do in the pubspec.yaml?

like java maven's groupId, such as multi people can create same name lib, for example, user1 create mysql lib with com.user1 group, user2 can also create mysql with com.user2, not create mysql1 or mysql_xx, it's not beautiful

**Comment by isoos** [comment]
We have considered creating namespaces, but for various reasons decided to not implement it, and we have no plans to do it in the near future. It doesn't automatically solve neither the maintenance, nor the recognition of the packages (e.g. who do you trust if there are many `xyz/mysql` packages, some may be forks, some abandoned). We think that the discovery and trust can be done better by doing analysis and exposing popularity on the package listings and package pages.
