### ISSUE TITLE
Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.

### ISSUE THREAD

**Issue by marymini** [dart-lang/pub-dev#3973]
Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.
Not able to create flutter project in my laptop. I tried flutter reinstallation. But the error not solved.

**Comment by isoos** [comment]
@marymini: could you please include more details about your environment, network and be a bit more verbose about the output of the tools and what is failing?

**Comment by marymini** [comment]
[image: image.png]
this is one error message

**Comment by marymini** [comment]
![image](https://user-images.githubusercontent.com/22218043/91794481-c8d5cd00-ec38-11ea-8073-ea50042383d5.png)

**Comment by marymini** [comment]
![image](https://user-images.githubusercontent.com/22218043/91795301-ec017c00-ec3a-11ea-9a16-549824c67025.png)

**Comment by isoos** [comment]
@marymini: it seems that for some reason the `PUB_HOSTED_URL` environment variable is set to `http://dartlang-pub-dev.appspot.com/`. That is a wrong setting (it is our testing site with no guarantees that it has the same packages as the prod site), and should be cleared. Do you recall why did you set that variable?

**Comment by marymini** [comment]
I tried it bcose from google search some did it solved the issue similar to mine. I will remove it.


Is there any option for Reinstalling flutter windows set up . what to do before that .

**Comment by marymini** [comment]
Is it need to format my laptop to continue  flutter development ?

**Comment by isoos** [comment]
I'm no expert on how to reset the Flutter setup you have, but removing the `PUB_HOSTED_URL` from where you have put it should be probably enough.

**Comment by marymini** [comment]
Thank you for your response.
i removed it.
Now trying reintalling flutter and its required

**Comment by marymini** [comment]
Solved my problem. Exactly i do not  know the solution.
But i update the jdk and put in the env path
reinstalled git .
Thats all.
My Flutter is working

Once again Thank you.
