### ISSUE TITLE
Cleanup packages with invalid YAML in pubspec.yaml

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3976]
Presumably, these were published before https://github.com/dart-lang/yaml/pull/22/files

They can't be used with recent `pub` versions either. It might be reasonable to simply remove these.

 * dart_begin / 0.0.1
 * diff_match_patch / 0.1.0
 * elements / 0.9.74

Still running analysis to verify that there is no more packages versions.

**Comment by jonasfj** [comment]
For these versions I've found no requests in past 60 days, apart from a few browser requests, some web crawlers and mirrors.
No requests that appears to origin from a Dart 1.x client, which is the only clients compatible with these versions.

**Comment by jonasfj** [comment]
Conclusion, I think a reasonable solution is to delete these package versions, because:
 * they have `pubspec.yaml` that is invalid YAML,
 * they cannot be consumed by any Dart 2.x clients,
 * they have no downloads in past 60 days,
 * they do not work with the latest version of Dart 1.x (1.24.3).

``` console
$ pub --version
Pub 1.24.3
$ echo -e 'name: hack\ndependencies:\n  diff_match_patch: 0.1.0\n' > pubspec.yaml
$ pub get
Resolving dependencies... 
+ diff_match_patch 0.1.0 (0.3.0 available)
Downloading diff_match_patch 0.1.0...
Error on line 9, column 1 of /home/jonasfj/.pub-cache/hosted/pub.dartlang.org/diff_match_patch-0.1.0/pubspec.yaml: Duplicate mapping key.
description: A pub package
^^^^^^^^^^^
```

**Comment by mit-mit** [comment]
SGTM to remove the three listed package versions:

- dart_begin / 0.0.1
- diff_match_patch / 0.1.0
- elements / 0.9.74

**Comment by jonasfj** [comment]
I apparently missed:
 * `syntax` / `0.2.0`

This the only version of `package:syntax`, I propose we remove the package entirely.

**Comment by mit-mit** [comment]
SGTM

**Comment by isoos** [comment]
I think these versions have been removed.

**Comment by jonasfj** [comment]
Removed :D
