### ISSUE TITLE
Pub.dev misuse / hacked by illegal content

### ISSUE THREAD

**Issue by stefandevo** [dart-lang/pub-dev#3991]
Need to find a way to stop this abuse of packages that are not packages but promotion for illegal content. ![image](https://user-images.githubusercontent.com/1656051/92277942-6dcffe80-eef4-11ea-83c9-6156f134a6f1.png)

**Comment by JellyO1** [comment]
It's even more annoying when you use RSS 
![image](https://user-images.githubusercontent.com/1593882/92280718-f305e400-eef1-11ea-9db3-bc10a012e6df.png)

**Comment by malikdoksoz** [comment]
Package reporting system should be introduced.

**Comment by isoos** [comment]
Thanks for reporting. We are aware of this spam effort, and will address it.

**Comment by kaumudpa** [comment]
+1

**Comment by isoos** [comment]
It looks like that the second iteration of our spam-response did drive the spammer away. Closing the issue for now.
