### ISSUE TITLE
Remove Package not compatible with runtime JS check for CLI Apps

### ISSUE THREAD

**Issue by BirjuVachhani** [dart-lang/pub-dev#3995]
URL: https://pub.dev/packages/spider/score

My package `Spider` is a command-line app that doesn't create any dependency on the project. Considering that, ideally it shouldn't require to provide support or `native.js`. But I am getting this issue in the package score section which doesn't make any sense for command-line apps I guess.

![image](https://user-images.githubusercontent.com/20423471/92354724-78f77a00-f100-11ea-83f7-c6c8f6ecc089.png)

**Comment by isoos** [comment]
@BirjuVachhani: I'm sorry for the potential confusion, but your spider package is just fine, and it doesn't need any removal. Not supporting a platform is by any means not a show-stopper for packages, it is a signal for their potential users what they can expect from a package. There is already an issue open in pana for this to track, we may change this in the near future: https://github.com/dart-lang/pana/issues/720

**Comment by BirjuVachhani** [comment]
This sounds wonderful. Thank you @isoos 😄
