### ISSUE TITLE
Not showing all the issues in score details page of a package

### ISSUE THREAD

**Issue by tusharojha** [dart-lang/pub-dev#4009]
* As the title describes the problem, it's hectic for the developers to find the remaining issues themselves. While it was showing all in previous versions.
 * Check out the screenshot attached.
<img width="691" alt="error" src="https://user-images.githubusercontent.com/36601970/92489511-7afb2f00-f20d-11ea-8d6a-57ff8439494c.png">

Also, if I am taking it wrong. Then please let me know how to see all the 7 issues rather than just 2.

Thanks

**Comment by tusharojha** [comment]
@isoos Please look into it.

**Comment by isoos** [comment]
We have never displayed all the issues that `dartanalyzer` (or `dartfmt`) revealed, only a limited items, right now only the first few (which is configured at 2). This part of the report is for developers who are looking to use the package, and are interested what kind of issues it may have.

The current report displays the instruction to run `dartanalyzer` on a specific file. We need to display the instruction to display it on the entire package.
