### ISSUE TITLE
<pre> tag with incorrect lang attribute messes up indentation.

### ISSUE THREAD

**Issue by mannprerak2** [dart-lang/pub-dev#4010]
The `<pre>` tag fails to preserve the indentation when it has an attribute `lang="yaml"`. I cannot remove this because it's needed for syntax highlighting on Github 

### Relevant Code -
```html
<pre lang="yaml"> <!-- removing lang="yaml" fixes the indentation issue>
headers:
  entry-points:
    - 'folder/**.h'
    - 'folder/specific_header.h'
  include-directives:
    - '**index.h'
    - '**/clang-c/**'
    - '/full/path/to/a/header.h'
</pre>
```

### Screenshot -
<img width="795" alt="Screenshot 2020-09-09 at 1 52 05 PM" src="https://user-images.githubusercontent.com/31154435/92573909-0b844e80-f2a4-11ea-8aff-4b75e414994b.png">

**Comment by sigurdm** [comment]
We believe this has been fixed. Please reopen if this is still an issue
