### ISSUE TITLE
Version building issues

### ISSUE THREAD

**Issue by StrangerKjq** [dart-lang/pub-dev#4012]
URL: https://pub.flutter-io.cn/packages/fast_develop

I don't know what went wrong with this package. Now I am in awaiting. The project relies on and executes pub get to get the data of the package

**Comment by isoos** [comment]
@StrangerKjq: "awaiting" status means that the package is scheduled for analysis and dartdoc generation, but it is not done yet. You are not limited by anything to use it - as soon as it is on the package page, it is available for download and use.

**Comment by StrangerKjq** [comment]
When the build was completed, the data still could not be pulled. I found that the problem appeared in version 1.1.14

The problem has just been fixed. I don't know why

**Comment by StrangerKjq** [comment]
How can I manually download the package and configure the corresponding dependency version number

I can't find help using it


> @StrangerKjq: "awaiting" status means that the package is scheduled for analysis and dartdoc generation, but it is not done yet. You are not limited by anything to use it - as soon as it is on the package page, it is available for download and use.

**Comment by isoos** [comment]
To debug a problem, use `pub get -v` (verbose output), that usually highlights what the issue was.

To download directly, you can visit the version tabs, the table has a download icon with a link to the package archive.

**Comment by StrangerKjq** [comment]
I downloaded the corresponding version and put it in the corresponding location, but the project still prompts me to do the pub get command

> To debug a problem, use `pub get -v` (verbose output), that usually highlights what the issue was.
> 
> To download directly, you can visit the version tabs, the table has a download icon with a link to the package archive.
