### ISSUE TITLE
why dont have api like "/api/packages?q=[some]"

### ISSUE THREAD

**Issue by franticn** [dart-lang/pub-dev#4037]

**Comment by jonasfj** [comment]
Curious, what is the use-case?

**Comment by franticn** [comment]
> Curious, what is the use-case?

Sorry to reply now, I am developing a vs-code plugin to help developers only need to search for keywords to get the corresponding packages information, including version code and name; But dont have api can help me to do these.

The method I currently use like these:
1. query packages by using api "api/search?q=keyword"
2. according selected package's name to query package's infomation by using api "api/documentation/packageName"

**Comment by isoos** [comment]
> according selected package's name to query package's infomation by using api "api/documentation/packageName"

What's the information that you need form that endpoint? Maybe we serve that better differently?

**Comment by franticn** [comment]
> What's the information that you need form that endpoint? Maybe we serve that better differently?

Just this package's lastest stable version and history versions
![preview1](https://user-images.githubusercontent.com/21286570/95558568-0522f700-0a49-11eb-90a1-bd066cf35106.gif)

**Comment by isoos** [comment]
Calling the `documentation` endpoint may not be the best for the list of versions, I'm sure we can figure out better (and faster) endpoints for these.

**Comment by sigurdm** [comment]
I think this has become obsolete with: https://github.com/dart-lang/pub-dev/issues/4302 there is now tab-completion for package-names in vscode.

Please open a new issue if this is not satisfactory compared to this feature request.
