### ISSUE TITLE
Package name is too similar

### ISSUE THREAD

**Issue by isacjunior** [dart-lang/pub-dev#4045]
I try to publish my packages and received `Package name is too similar to another active or moderated package.` to publish `flutter_doc` package.

My packages and status: https://pub.dev/publishers/isacjunior.dev/packages

**flutter_doc_annotation**: `published`
**flutter_doc_builder**: `published`
**flutter_doc**: `error`

If it is not possible to publish `flutter_doc`, delete `flutter_doc_annotation` and `flutter_doc_builder`

**Comment by isoos** [comment]
@isacjunior: there is already an existing package with the name `flutterdoc`. We do not allow close name matches (e.g. where the name differs only with `_`), as we think it would be confusing to the users if there are multiple very similar package names.

**Comment by isacjunior** [comment]
If is possible, Do you delete flutter_doc_annotation and flutter_doc_build packages?

**Comment by jonasfj** [comment]
> If is possible, Do you delete flutter_doc_annotation and flutter_doc_build packages?

Please file a request with `support@pub.dev`, see: https://pub.dev/policy
