### ISSUE TITLE
Search term is ignored after sorting

### ISSUE THREAD

**Issue by syntacops** [dart-lang/pub-dev#4050]
URL: https://pub.dev/

I just noticed that the search terms are ignored if you choose a sorting other than "Relevance" and "Score". 

![image](https://user-images.githubusercontent.com/68994521/93996406-84020980-fd92-11ea-86fa-701c2a013a8f.png)

---

For example, if I enter the search term "responsive", I will get all packages that are related to responsiveness or contain this term. If I then sort the listing by likes or popularity because I want to know which "reponsive" package has the most likes or is the most popular, I get a listing that does not include the search term.

Here the whole thing becomes a bit clearer:
[https://pub.dev/packages?q=responsive&sort=like](https://pub.dev/packages?q=responsive&sort=like)

![image](https://user-images.githubusercontent.com/68994521/93996320-646ae100-fd92-11ea-8ca4-cf2208a37bf0.png)

This link should find the packages that match the search term "responsive" and then sort them by likes. The result: none of the displayed packages has anything to do with responsiveness. You only get all packages sorted by likes.

---

Here is another example:
[https://pub.dev/packages?q=forms&sort=popularity](https://pub.dev/packages?q=forms&sort=popularity)

![image](https://user-images.githubusercontent.com/68994521/93996345-6c2a8580-fd92-11ea-80ec-8b098cc89145.png)

Instead of the most popular form packages, I again only get a general overview sorted by popularity.

---

All this is unproblematic as long as you search via the main page, because there is no sorting. 

![image](https://user-images.githubusercontent.com/68994521/93997083-481b7400-fd93-11ea-8e85-8ea8d45c42c7.png)

But on the main page you can view the top list "Most popular packages" by clicking on "View all". The sorting is then already set to "Popularity" by default, making any search useless.

![image](https://user-images.githubusercontent.com/68994521/93997141-59648080-fd93-11ea-8765-0b6359b3dd83.png)

I think it would be a great improvement if all sorting methods would take the entered search term into account.

**Comment by isoos** [comment]
> The result: none of the displayed packages has anything to do with responsiveness.

What happens here is that we are using a fuzzy text-matching algorithm that matches `response` with `responsive` and lists packages that have either of these terms in their text corpus. (+ `package:get` has verbatim `responsive` in its readme).

**Comment by isoos** [comment]
Closing this as we've deployed a new search on the site, with reduced fuzzy matching on the text contents. In this specific use-case it reduced the number of packages significantly. Please open a new issue if you find another query that seems to be wrong.
