### ISSUE TITLE
dartdoc fatal errors are invisible to the user

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/pub-dev#4062]
Some overlap with #4057 in this being a hard situation to debug and the presence of many "awaiting" indications, but this includes stable versions.  Other than the user report, I wouldn't even be able to determine an error occurred at the dartdoc level.

1) the state seems to remains stuck in "awaiting":

<img width="838" alt="Screen Shot 2020-09-28 at 10 10 31 AM" src="https://user-images.githubusercontent.com/14116827/94464509-69a1a480-0173-11eb-84ca-9da6e304a2b1.png">

2) there is no way to view the error logs (clicking on "awaiting" doesn't seem to help)

3) there appears to be no impact to scoring percentage.  Instead, 10 points are removed from the possible total:

<img width="814" alt="Screen Shot 2020-09-28 at 10 16 53 AM" src="https://user-images.githubusercontent.com/14116827/94464778-c1d8a680-0173-11eb-8356-da6f8159f5dc.png">

An example package is https://pub.dev/packages/kana_kit/versions.  The package owner reported a dartdoc error prior to 1.0.4 that was preventing generation, but they had a hard time debugging what was wrong since it just showed "awaiting" on the pub site.

I tried myself and couldn't figure out a better way to debug, hence the issue.

**Comment by jeroen-meijer** [comment]
Thanks for reporting the bug. I'm the maintainer of the `kana_kit` package. If I can provide any help or data, please let me know! 👍🏻

**Comment by isoos** [comment]
Thanks for reporting this!

> there is no way to view the error logs (clicking on "awaiting" doesn't seem to help)

`awaiting` status means that we haven't processed the packages yet. There is a priority queue and they haven't reached it yet. It is a bit startling, as these versions are rather new, and the processing should have reached them already.

Debug information shows that we are behind for 52% of the last-90 uploads, we need to investigate and fix that.

> there appears to be no impact to scoring percentage. Instead, 10 points are removed from the possible total

That is the side-effect of the asynchronous nature of our processing: as the documentation coverage points can be awarded only after `dartdoc` was running, we need to decide whether to block on that or display it without it. Hence you can see the X/100 totals instead of the Y/110 totals.

**Comment by jcollins-g** [comment]
@isoos Well, my assumption is something's gone wrong and we're not displaying a dartdoc error where we should, because these versions were published months ago, and shortly after the package maintainer fixed a dartdoc related problem they had docs again (see the latest version).

But, if they really are in "awaiting" status, I guess it's reasonable to not include the docs in scoring yet.  The main issue is, where are the (presumed) dartdoc errors?

**Comment by isoos** [comment]
> The main issue is, where are the (presumed) dartdoc errors?

Old failures (and also successful results) are deleted frequently. Presumably the new versions should have been finished by that time, but in this case they clearly had not.

**Comment by isoos** [comment]
Investigation shows that we have dependent packages being published that trigger a new dartdoc run for almost all latest stable every 12-24 hours. We will disable this until we have some stop-gap on that trigger.

**Comment by isoos** [comment]
We've deployed a new version that has this fix.
