### ISSUE TITLE
Add deprecation/discontinued warning to e2e 

### ISSUE THREAD

**Issue by TahaTesser** [dart-lang/pub-dev#4096]
Please add deprecation/discontinued warning to https://pub.dev/packages/e2e
Deprecation readme here https://github.com/flutter/plugins/tree/master/packages/e2e 

This will close this https://github.com/flutter/flutter/issues/67397 issue
CC @ditman  @christopherfujino

**Comment by ditman** [comment]
I think in order to publish the 'deprecated' README, we need to add a bunch of files to the package that were deleted earlier (like a pubspec).

/cc @dnfield

**Comment by dnfield** [comment]
I had a copy saved locally for this and have published it. I do not intend to push this to git since the package is discontinued. I have also marked the package as discontinued on pub.dev.

**Comment by dnfield** [comment]
(I do not have perms to close this bug, but it can be closed)

**Comment by ditman** [comment]
Thanks for that publish @dnfield! (I can't close this either, but can confirm this is fixed)

**Comment by TahaTesser** [comment]
Thank you!
