### ISSUE TITLE
Packages API incorrect pagination - page 5

### ISSUE THREAD

**Issue by aarena** [dart-lang/pub-dev#4104]
* Each api/packages page returns a json with a next_url key
   * api/packages?page=1 returns api/packages?page=2
   * api/packages?page=2 returns api/packages?page=3
   * ect...
 *  Page 5 returns a null url, instead of page 6 even though page 6 exists
 * https://pub.dev/api/packages?page=5
 * https://pub.dev/api/packages?page=6

<img width="485" alt="Screen Shot 2020-10-07 at 4 05 17 PM" src="https://user-images.githubusercontent.com/23458964/95382003-fa385d00-08b6-11eb-89e4-c840aaa4c82d.png">

**Comment by isoos** [comment]
@aarena: thanks for reporting. This is a side-effect of one of the internals wrt. withheld packages, should be possible to fix soon.

However, we are considering to update the format/content/scope of this `/api/packages?page=2` API. Could you please share us your use case for it?

**Comment by aarena** [comment]
@isoos Thank you for the quick response and merge request! My use case is just gathering metadata and dependency information for open-source projects I am interested in. 

I checked and page 5 does now have `"next_url":"https://pub.dartlang.org/api/packages?page=6"` but page 6 now has the null next page.

**Comment by isoos** [comment]
> I checked and page 5 does now have "next_url":"https://pub.dartlang.org/api/packages?page=6" but page 6 now has the null next page.

The code that we've merged is not deployed yet. We'll have a new release possibly next week..

**Comment by isoos** [comment]
> My use case is just gathering metadata and dependency information for open-source projects I am interested in.

We are considering to change this API. Could you please write some more details about your API use in the following bug: https://github.com/dart-lang/pub-dev/issues/4092

The fix has been deployed, I'm closing this issue.
