### ISSUE TITLE
Having trouble setting up local development server

### ISSUE THREAD

**Issue by sumandipanshu** [dart-lang/pub-dev#4105]
**What is the problem?**
1. Exception: Unknown project id: &lt;my-project-id&gt;
2. DetailedApiRequestError(status: 403, message: &lt;my-service-account&gt; does not have storage.buckets.get access to the Google Cloud Storage bucket.)

**Steps to reproduce:**
1. Follow steps mentioned in [development.md](https://github.com/dart-lang/pub-dev/blob/master/doc/development.md)
2. If you use:
```terminal
export GCLOUD_PROJECT=<my-project-id>
export GCLOUD_KEY=<path-to-service-account-key.json>
dart bin/server.dart default
```
It results in problem#1(already mentioned above).
After digging into the source code, what i found maybe is the root cause of this issue. [Refer here.](https://github.com/dart-lang/pub-dev/blob/fae2152c81ca80bdd918f2850ff1650683cf20d1/app/lib/shared/configuration.dart#L237-L245)

3. If you use:
```terminal
export GCLOUD_PROJECT=dartlang-pub-dev
export GCLOUD_KEY=<path-to-service-account-key.json>
dart bin/server.dart default
```
It results in problem#2(already mentioned above).

**Screenshots:**
![problem1](https://user-images.githubusercontent.com/42720239/95382180-e1579800-0906-11eb-9833-bb2e9ba2687b.png)
![problem2](https://user-images.githubusercontent.com/42720239/95382185-e3215b80-0906-11eb-8324-80d5ccfb74ed.png)

**Note:**
1. My service account has following roles assigned:
     - Storage Admin
     - Storage Legacy Bucket Owner
     - Storage Object Admin
2. Tried on both access controls: Fine-grained and Uniform

**Comment by jonasfj** [comment]
Hold on this is something we're working to improve.

**Comment by gfb-47** [comment]
I'm having the same issue.

**Comment by isoos** [comment]
Since the original report we've introduced the local development server that has no direct use of google cloud (`app/bin/fake_server.dart`). Please use that for local development:
https://github.com/dart-lang/pub-dev/blob/master/doc/development.md#local-development-without-external-services
