### ISSUE TITLE
When a zero is entered in the decimal part, the cursor moves to the begining positon of whole part

### ISSUE THREAD

**Issue by quan-codemetrics** [dart-lang/pub-dev#4123]
URL: https://pub.dev/packages/flutter_multi_formatter.

When entering  4.06. It becomes 64.0 
![image](https://user-images.githubusercontent.com/70996524/95701620-44815b80-0c74-11eb-9b1a-fe19469ad95e.png)

**Comment by isoos** [comment]
@quan-codemetrics: this repository is for issues of the pub.dev site, not for individual packages. Please report the issue to the package's directory, e.g. in this case https://github.com/caseyryan/flutter_multi_formatter/issues

**Comment by quan-codemetrics** [comment]
Sorry and thank @isoos
