### ISSUE TITLE
Add canonical-link to all pages

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4136]
Add `<link rel="canonical" href="https://pub.dev/path/page..." />` to all pages.

See: https://support.google.com/webmasters/answer/139066

**Comment by Ankitkj1999** [comment]
I am new here. Can you please tell me where on what pages canonical URL needs to be added?

**Comment by isoos** [comment]
@Ankitkj1999: Welcome :)

On the question of where: the `canonicalUrl` parameter needs to be set on the `renderLayoutPage` method: https://github.com/dart-lang/pub-dev/blob/master/app/lib/frontend/templates/layout.dart#L47

This is called from a few places, where it is not yet set, and we should add it. To have a full coverage, I'm working to extend our HTML validation to always check for the presence of it. However, as you can see on the earlier related PRs, the challenge is not adding the value itself, rather adding it in a consistent and trackable way.
