### ISSUE TITLE
Ensure RetryClient from package:http_retry handles IOException

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4161]
Notably: DNS, broken TCP connections, etc.. This is likely to happen when we use an HTTP client that reuses connections which may have timed out.

https://github.com/dart-lang/pub-dev/pull/4159/files#diff-eae17a35e4cad105a467861b9b0c4e83df6761d0bed2f51ac61d3e26607b2211R429-R433

**Comment by isoos** [comment]
Closing as duplicate of #7825.
