### ISSUE TITLE
pub.dev fails to run dartdoc: "NoSuchMethodError: The getter 'documentationComment' was called on null."

### ISSUE THREAD

**Issue by sebthom** [dart-lang/pub-dev#4166]
When we try to publish our Dart library [hotreloader](https://pub.dev/packages/hotreloader), the dartdoc generation task on pub.dev fails with a dartdoc internal error message.

```dart
Unhandled exception:
NoSuchMethodError: The getter 'documentationComment' was called on null.
Receiver: null
Tried calling: documentationComment
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Accessor.computeDocumentationComment (package:dartdoc/src/model/accessor.dart:67:44)
#2      DocumentationComment.documentationComment (package:dartdoc/src/model/documentation_comment.dart:39:31)
#3      ModelElement.computeDocumentationFrom (package:dartdoc/src/model/model_element.dart:589:9)
#4      ModelElement.documentationFrom (package:dartdoc/src/model/model_element.dart:569:28)
#5      PackageGraph.precacheLocalDocs.<anonymous closure>.precacheOneElement.<anonymous closure> (package:dartdoc/src/model/package_graph.dart:109:16)
#6      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:165:25)
#7      Future.wait (dart:async/future.dart:406:26)
#8      PackageGraph.initializePackageGraph (package:dartdoc/src/model/package_graph.dart:74:18)
#9      PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:77:20)
<asynchronous suspension>
#10     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:182:41)
#11     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:223:34)
#12     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:32:33)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

See https://pub.dev/packages/hotreloader/score

![image](https://user-images.githubusercontent.com/426959/96635296-f7f4ea80-131b-11eb-9d8c-8bd5bc7fb560.png)

When running dartdoc locally the documentation is generated successfully. So we cannot reproduce the issue and don't know how to prevent it.

**Comment by isoos** [comment]
I've reproduced this with both `dartdoc 0.35.0` (the version we are using on pub.dev) and `dartdoc 0.36.0` (the latest published). Reported at the `dartdoc` repository: https://github.com/dart-lang/dartdoc/issues/2402

**Comment by znjameswu** [comment]
Any updates on this? dartdoc has released 0.36.2.

**Comment by jonataslaw** [comment]
The problem still persists today 
![97118203-7d471900-16e7-11eb-95b9-bb03c4cb16d9](https://user-images.githubusercontent.com/35742643/98615229-e0849e00-22d8-11eb-9c32-a60b675b94c9.png)

**Comment by isoos** [comment]
@jonataslaw We haven't deployed a new version of pub.dev yet, and this change (among others that were marked as fixed) is not in prod. Please have a bit of patience until it happens, probably soon.
