### ISSUE TITLE
Improve links for packages with documentation link

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4168]
I actually thought that we would not have the "API reference" when the package has a `documentation` link in `pubspec.yaml`.
But I can see that both of these makes sense :)

Can we come up with a better link name, so that it's called something else than "Documentation"?

![5q2fbwa4VrBWeaT](https://user-images.githubusercontent.com/149732/96692119-fa8c2a00-1385-11eb-8967-fd5af05e224f.png)

**Comment by isoos** [comment]
As an alternative to the renaming, we could hide the "Documentation" title element if there is a "Documentation" link. Maybe the styles needs to be adjusted to keep the horizontal separator line...
