### ISSUE TITLE
Ability to find packages with null-safety in prerelease

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4182]
It would be nice if during the beta-phase it was possible to find packages that has migrated to null-safety in a prerelease.
Currently, search does not index prereleases, it only indexes the latest stable release (falling back to a prerelease, if there are no stable releases).

Adding multiple versions of a package to the search index will probably increase the complexity of the search UX/UI and causing significantly more overhead.

However, the documents indexed in search already track what the latest stable and latest prerelease versions are.
Hence, it seems feasible to index the tags from the latest prerelease version with `is:<tag>-in-prerelease`.

There are minor concerns regarding the overhead of loading this data, but that's something we can investigate when implementing it.

**Comment by isoos** [comment]
Launched.
