### ISSUE TITLE
make pub REST API client public

### ISSUE THREAD

**Issue by lesnitsky** [dart-lang/pub-dev#4194]
Example use-cases for such a client are mostly tooling related:
- https://marketplace.visualstudio.com/items?itemName=jeroen-meijer.pubspec-assist
- https://plugins.jetbrains.com/plugin/12400-flutter-pub-version-checker
- https://twitter.com/lesnitsky_dev/status/1235614665641562112?s=20 😉

all three extensions are using the same endpoint https://pub.dartlang.org/api/ to fetch required information
it would be very useful to have an official REST API client 

- to be able to reuse it
- to make sure it won't break (breaking changes are taken care of by the pub team)

Please let me know if that's a reasonable request and if relevant PRs would be accepted

cc @pszklarska, @jeroen-meijer, @csells

**Comment by lesnitsky** [comment]
does pub tool itself use https://pub.dartlang.org under the hood?

**Comment by isoos** [comment]
> does pub tool itself use https://pub.dartlang.org under the hood?

Yes it does. (Not sure: what else could it use?)

**Comment by lesnitsky** [comment]
what are your concerns about making https://github.com/dart-lang/pub/blob/master/lib/src/http.dart public + wrapping it with a verbose facade (this`httpClient.read` [here](https://github.com/dart-lang/pub/blob/master/tool/extract_all_pub_dev.dart#L28) could have been `httpClient.getPackage(packageName)`?

**Comment by sigurdm** [comment]
> what are your concerns about making https://github.com/dart-lang/pub/blob/master/lib/src/http.dart public + wrapping it with a verbose facade (thishttpClient.read [here](https://github.com/dart-lang/pub/blob/master/tool/extract_all_pub_dev.dart#L28) could have been httpClient.getPackage(packageName)?

* really simple (really just do `GET` of `http://pub.dev/packages/<package>` and read the json response), 
* Reasonably well documented
* Language-independent
* there's no real advantage to us wrapping it with helpers. It would only make more work for us.

The API is already public, so if we would ever break it, a facade would not help. We would still need to work out any migrations.

Closing this as we have no plans for this.
