### ISSUE TITLE
Empty api/packages pages. No packages, but has next_url

### ISSUE THREAD

**Issue by aarena** [dart-lang/pub-dev#4216]
When browsing the api/packages when you get to page 35 it shows a next_url link, but no packages on the page itself.

Starting at
https://pub.dartlang.org/api/packages?page=35

I did not check every page in the range, but it appears to happen between pages 35-40.

-
<img width="798" alt="page_35_empty" src="https://user-images.githubusercontent.com/23458964/98125708-c2571200-1e82-11eb-9988-b10e91dcf4b3.png">
----
<img width="718" alt="page_39_empty" src="https://user-images.githubusercontent.com/23458964/98125709-c2efa880-1e82-11eb-8acd-3f2b685ce916.png">
----
<img width="608" alt="page_40_empty" src="https://user-images.githubusercontent.com/23458964/98125711-c2efa880-1e82-11eb-82e1-dc44b9a8778f.png">
----
<img width="647" alt="page_41_has_packages" src="https://user-images.githubusercontent.com/23458964/98125712-c2efa880-1e82-11eb-95fd-fc70ecd217a1.png">

**Comment by isoos** [comment]
Yeah, this is a known thing that we won't fix for now. We have packages that are withdrawn from public view (they were spam), and we haven't done the full cleanup yet. Until then, please use the `next_url` as an indication whether there is more.

Curious: what is your use case for this API? We are planning to refactor/remove this, and it would be great if you could add what you are using it for to the following tracker: https://github.com/dart-lang/pub-dev/issues/4092
