### ISSUE TITLE
Flutter favorit page navigation bug

### ISSUE THREAD

**Issue by pipaliyachirag** [dart-lang/pub-dev#4226]
URL: https://pub.dev/flutter/favorites?page=3

after going to this link when we try to navigate to dart or flutter specific page in navigation of dart | flutter | any in all ancher link it is staying the same.

**Comment by isoos** [comment]
@pipaliyachirag: thanks for reporting. I think the FF pages shouldn't even have the SDK selection, wdyt @jonasfj ?

**Comment by jonasfj** [comment]
hmm, seems like something worth fixing.
