### ISSUE TITLE
How to add a Example and License?

### ISSUE THREAD

**Issue by augustkimo** [dart-lang/pub-dev#4227]
I just uploaded my first package: [instagram_media](https://pub.dev/packages/instagram_media) , and I have two questions.

1 - I edited the ```LICENSE``` file that was included in the template with the license/code at the bottom of this post, but on pub.dev under License it shows "unknown (LICENSE)" (with no link to the license). How can I fix this? (BSD 2)

2 - I would like to include a basic example, but I can't find any documentation on how to upload a example if somebody could help guide me?  

The license code/text in the LICENSE File:

```
Copyright (c) 2020, August Kimacovich 
All rights reserved. 

Redistribution and use in source and binary forms, with or without 
modification, are permitted provided that the following conditions are met: 

 * Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimer. 
 * Redistributions in binary form must reproduce the above copyright 
   notice, this list of conditions and the following disclaimer in the 
   documentation and/or other materials provided with the distribution. 

THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY 
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY 
OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH 
DAMAGE. 
```

**Comment by isoos** [comment]
1) License:

We do link to LICENSE files if one of the `homepage` or `repository` fields in your `pubspec.yaml` point to a `github.com` or a `gitlab.com` repository, and we can find the referenced file. You pubspec doesn't have this information, and we don't display the license file from the archive (yet).
See more about this here: https://dart.dev/tools/pub/pubspec#repository

2) Examples:

See the package layout conventions: https://dart.dev/tools/pub/package-layout#examples

We detect these file patterns and expose the example file we find.
