### ISSUE TITLE
Migrate packages from one verified publisher to another

### ISSUE THREAD

**Issue by josiahsrc** [dart-lang/pub-dev#4237]
Hello!  I'm in the middle of a domain switch and I'm looking to migrate my packages from my old domain to be credited to my new domain. Is there a way to migrate packages from one verified publisher to another verified publisher? Or possibly change my verified publisher's domain?

Thank you in advance for any help 🙂

**Comment by isoos** [comment]
@josiahsrc: If your account is admin in both publishers, you can move the package between them. Once you have the new publisher, make sure they share an admin account, and with that account you can move them on the admin page of the package.

**Comment by josiahsrc** [comment]
Oh perfect! Thank you @isoos
