### ISSUE TITLE
Show a copied message feedback after the copy button was pressed

### ISSUE THREAD

**Issue by pedromassangocode** [dart-lang/pub-dev#4244]
The newly added feature (https://github.com/dart-lang/pub-dev/issues/3336) in pub.dev is awesome but it is quite strange to me when I tap a button and  don't get any visual feedback.

### Proposal

I propose to show a copied feedback message once the copy button is pressed. It is quite strange to me when I tap a button and  don't get any visual feedback.

### Suggestion

The message shown when we place the cursor over the copy button is quite useless as it just shows the package name and version which is already visible. I would remove it. I know it shows package and version in a format that is acceptable by `pubspec.yaml` but it still useless since we usually know that.

**Comment by orestesgaolin** [comment]
I think it would be more natural to copy the content not only when clicking on the tooltip but also on the copy icon.

**Comment by pedromassangocode** [comment]
Noticed now that the content is only copied when you tap the tooltip message, I honestly expected to copy the content when the button is pressed **AND** show the tooltip when it is pressed.
