### ISSUE TITLE
Migration readiness emails for packages

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#4252]
Inspired by https://github.com/flutter/flutter/issues/70409, I think it would be nice if pub.dev could sent out emails to package owners when their deps are ready. Something like this:

```
Hi package owner,

We've detected that all your dependencies have now enabled null safety,
and that you should be able to get a package resolution that enables null safety
with the following package versions:

[table with deps and versions that have null safety]

We would like to encourage you to add null safety to your own package.
Please see the migration guide [link].

Regards, pub.dev
```

**Comment by jonasfj** [comment]
If we want to do this, I think a one-off script that we run once per week locally is better.
The information required to determine this is public, as is the contact email address we would use.

We could also file issues with repositories as the packages become migration ready.

**Comment by isoos** [comment]
I assume this is no longer relevant, closing.
