### ISSUE TITLE
Avoid double-initializing

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#426]
Within this call to `withAppEngineServices`

https://github.com/dart-lang/pub-dartlang-dart/blob/c5717accd2ad9f6836e6f89812608995e296812d/app/bin/service/frontend.dart#L35

We call `runAppEngine`

https://github.com/dart-lang/pub-dartlang-dart/blob/c5717accd2ad9f6836e6f89812608995e296812d/app/bin/service/frontend.dart#L39

Both of these call `_withAppengineServicesInternal`. We end up with double calls to initialize memcache, etc. Double warnings when the expected host doesn't exist, etc.

I'm guessing we don't want to set up the handler on the first request, so I'm thinking this would end up being a `pkg/appengine` bug/feature request.

We could add an optional `initialize` callback to `runAppEngine` that runs before any requests are handled.

...or something else?

**Comment by kevmoo** [comment]
CC @mkustermann

**Comment by mkustermann** [comment]
`withAppEngineServices` behaves as expected: It will setup a new service scope for the duration of the callback with the services injected into it. If you nest `withAppEngineServices`, you'll inevitably inject new services.

`runAppEngine` will **need to** make a new service scope and initialize some services, namely the ones which are on a per-request basis, for example logging. It needs to initialize other services as well, for users which don't have the other scope around it.

The best solution we could do is provide a `runAppEngineServer()` method, which just does the request-specific service scope initialization.

Why is this a big issue anyway? What kind of host doesn't exist?

Yes, please move it to `package:appengine` if you think it's a problem.

**Comment by isoos** [comment]
Is there something we can change on our side with this? It still produces two warnings (and exception stacks) in local dev mode without the memcache service, but I'm fine if it remains that way.

**Comment by kevmoo** [comment]
I think updating the appengine package is in the realm of acceptable to fix
this.

...but I consider it low priority.

Better to start on dartdoc IMHO

**Comment by isoos** [comment]
I think this was fixed since then.
