### ISSUE TITLE
pub.dartdoc.runner/fhir/0.0.11 -> exitCode: -9

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4261]
This is worth investigating, if it's a bug or a buggy packages. We should either fix it, or ensure that dartdoc runner doesn't log a warning when this happens.
```
pub.dartdoc.runner/fhir/0.0.11: Error while running dartdoc for fhir 0.0.11.
exitCode: -9
stdout: Documenting fhir...
stderr: 
```

**Comment by isoos** [comment]
This seems to be a dartdoc issue, filed https://github.com/dart-lang/dartdoc/issues/2436

**Comment by jonasfj** [comment]
Seems like this is a timeout, while we could debate increasing the timeout, etc.

We will always have timeouts, so it's worth:
 * [ ] Reporting the timeout to the user, and,
 * [ ] Avoid reporting it as a warning in our logs.

**Comment by isoos** [comment]
The reporting and logging of the timeout is done. Closing this while the dartdoc issue is still pending.
