### ISSUE TITLE
Getting access to lost publisher

### ISSUE THREAD

**Issue by Kleak** [dart-lang/pub-dev#4262]
Hi have created a publisher during the first lockdown but now none of my account have access to it.
And I don't find a way to get access to it.

Could someone help ?

**Comment by isoos** [comment]
@Kleak As described on the policy page (https://pub.dev/policy), please contact support on `support@pub.dev`.

**Comment by Kleak** [comment]
thanks

**Comment by natanelyoung** [comment]
@Kleak were you able to regain access to your account? The same thing happened to me and I also sent an email..

**Comment by Kleak** [comment]
Yes i regain access thanks to @isoos.
