### ISSUE TITLE
Null safety filtering does not work for packages which depend on flutter sdk 

### ISSUE THREAD

**Issue by Dimibe** [dart-lang/pub-dev#4277]
The pub.dev site now supports filtering for packages which support null safety. This seems to work only for packages which do not depend on the flutter sdk. 

* Here is the link which does not find any package: https://pub.dev/packages?q=grouped_list&prerelease-null-safe=1 
![Bildschirmfoto 2020-11-20 um 17 59 52](https://user-images.githubusercontent.com/15692917/99828122-d5443480-2b5a-11eb-937f-b4a1f42b6a44.png)
* Same link without the filter works: https://pub.dev/packages?q=grouped_list
* Also when going to the packages [detail site](https://pub.dev/packages/grouped_list/versions/4.0.0-nullsafety.0) of the null-safety version there is a button which just says "unidentified":
![Bildschirmfoto 2020-11-20 um 18 00 19](https://user-images.githubusercontent.com/15692917/99827850-754d8e00-2b5a-11eb-90ed-6ce880cd2a42.png)

When [browsing](https://pub.dev/packages?prerelease-null-safe=1) through all packages which support null safety (so without a search string) I noticed that there is no package in the list which depends on the flutter sdk. An easy prove for this is that the number of results for [dart only packages](https://pub.dev/dart/packages?prerelease-null-safe=1) is the same as for [any](https://pub.dev/packages?prerelease-null-safe=1).

**Comment by sigurdm** [comment]
Fixed by https://github.com/dart-lang/pana/pull/807
