### ISSUE TITLE
Null safety scores missing/not awarded to packges versions already updated

### ISSUE THREAD

**Issue by yeradis** [dart-lang/pub-dev#4278]
* Null safety points are missing from the pub.dev points models so nothing is awarded yet to packages versions already updated to support sound null safety

![image](https://user-images.githubusercontent.com/666944/99896880-ebeea680-2c94-11eb-9ee3-518d9fa20815.jpeg)

As we can read there, its planned but just wanted to point that nothing published exist yet and would be nice to have something to help with package discovery

As an example lets take 

https://pub.dev/packages/equatable/versions/2.0.0-nullsafety.0/score

https://pub.dev/packages/bloc/versions/7.0.0-nullsafety.0/score

**Comment by isoos** [comment]
> that nothing published exist yet and would be nice to have something to help with package discovery

Scoring and full exposure for null-safe packages is in its early stages, however, we do support package discovery through the advanced search options:

<img width="1103" alt="Screenshot 2020-11-23 at 8 25 26" src="https://user-images.githubusercontent.com/4778111/99937262-92a27800-2d65-11eb-8a1f-9058233e4918.png">

Does this help?
