### ISSUE TITLE
Stable API for listing package names

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4282]
```
GET /api/package-names
{
  "packages": [..., 'retry', ...], // first N package names,
  "nextUrl": null, // URL for next page, null, if this is the last page.
}
```

I would suggest we document this in `doc/api.md`, and that we state that:
 * page size (`N`) may change at any time,
 * ordering is unspecified and may change at any time,
 * the API is eventually consistent and it may take time before new packages appear.

Presumably, it's most sensible for us to do an ordering by name, but we shouldn't promise that this is what we'll always have.

**Comment by jonasfj** [comment]
Note. while this API is paging, we probably won't have multiple pages anytime soon.
The downside of this is that anyone who fails to implement the paging, won't get all package names -- but they'll still get a lot of packages.

We could also choose to not make the API paging, even at 1M package names, that's large but not impossible. And it would be very reasonable to only update the list once per hour.

**Comment by isoos** [comment]
This has been released in prod.
