### ISSUE TITLE
Pub publish "insufficient permissions error" after attempt to publish with missing LICENSE

### ISSUE THREAD

**Issue by timsneath** [dart-lang/pub-dev#4298]
# Environment

- `pub version` or `flutter pub version`: Pub 2.12.0-40.0.dev
- OS version: Windows 10
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

After attempting to load a package with a missing LICENSE file, further attempts to upload fail with:

```
ERR : Insufficient permissions to upload new versions of package `device_info_windows`.
```

## Repro

Attempted to publish my null-safe package:
https://gist.github.com/timsneath/0156bf97eed2c3ff0653057489c3205f#file-error-txt-L1

No warning, but after attempting to publish I got a LICENSE error:
https://gist.github.com/timsneath/0156bf97eed2c3ff0653057489c3205f#file-error-txt-L68

After copying the LICENSE file, I attempted to publish again, but received an insufficient permissions error:
https://gist.github.com/timsneath/0156bf97eed2c3ff0653057489c3205f#file-error-txt-L74

Even after bumping the version in pubspec, I still received insufficient permissions error. Verbose log:
https://gist.github.com/timsneath/0156bf97eed2c3ff0653057489c3205f#file-error-txt-L143

Credentials are correct (attempted flutter pub logout):
https://gist.github.com/timsneath/0156bf97eed2c3ff0653057489c3205f#file-error-txt-L1876

**Comment by isoos** [comment]
The only place where we throw this exception is here:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/package/backend.dart#L617

Checked the server logs, and in this case @timsneath was using his `tim@<non-google-com-domain>` and not the `timsneath@google.com` account. The later is an uploader on the package, the former is not.

I'll put the current account's email address in the error message, so that next time it becomes clear for the user that they are using a different account.

**Comment by timsneath** [comment]
Thank you very much. I think your error message will greatly help confusion for this error.

But I *am* still confused: you're saying this had nothing to do with the `LICENSE`? What then happened with the original attempt to publish in [lines 1-68 of the above gist](https://gist.github.com/timsneath/0156bf97eed2c3ff0653057489c3205f#file-error-txt-L1)? 
```
Package validation found the following hint:
* You're about to publish a package that opts into null safety.
  The previous version (0.1.1) isn't opted in.
  See https://dart.dev/null-safety/migration-guide for best practices.

Publishing is forever; packages cannot be unpublished.
Policy details are available at https://pub.dev/policy


Package has 0 warnings and 1 hint... Do you want to publish device_info_windows 0.2.0-nullsafety.0 (y/N)? y
Uploading...
LICENSE file `LICENSE` contains generic TODO.
```

- Was this a failed attempt to upload that didn't throw an exception? (If not, why not?)
- Why did the LICENSE warning appear during the upload attempt and not as a warning? Was it an error? If so, is this a new one, since previous (0.1.x) versions of this package had the same generic LICENSE file.

**Comment by isoos** [comment]
> Was this a failed attempt to upload that didn't throw an exception? (If not, why not?)

That too came from the server:
https://github.com/dart-lang/pub-dev/blob/master/pkg/pub_package_reader/lib/pub_package_reader.dart#L431

And it does throw a similar exception:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/package/backend.dart#L1099-L1101

> Why did the LICENSE warning appear during the upload attempt and not as a warning? Was it an error?

Parsing the `.tar.gz` archive is done before the authorization check, as first we need to have (1) a valid archive, then (2) a valid `pubspec.yaml`, and (3) finally we get the package's name to check authorization against. The current implementation, mostly for simplicity, we also do other checks like `LICENSE` before that authorization check or whether the uploaded version already exists.

I'm not sure why `pub` client doesn't display it with the same `ERR` prefix, I think that is something the client's logger puts there. Maybe status code `403` is treated differently than `400`? Possibly @sigurdm can find the reason quicker than me.

**Comment by sigurdm** [comment]
Hmm - I think the run where the license file is missing is without `--verbose`. That is why there is no prefix.
