### ISSUE TITLE
Clarity on desigating uploaders for Verified Publishers

### ISSUE THREAD

**Issue by diegotori** [dart-lang/pub-dev#4303]
So I'm asking this question on behalf of the [wifi_iot](https://github.com/alternadom/WiFiFlutter) plugin also listed on [pub.dev](https://pub.dev/packages/wifi_iot). The author of the library, @alternadom, who is also the Verified Publisher for this package, has been facing issues in trying to designate me and another developer (@daadu) as uploaders to this project. In other words, he is unable to add me or @daadu as an uploader, despite making the latter an Admin of that library on pub.dev.

For example, he does not have the ability to designate uploaders in the [Admin tab](https://www.alternadom.com/wp-content/uploads/2020/11/Capture-de%CC%81cran-2020-11-26-a%CC%80-14.30.28.png) for his library. Furthermore, when @daadu attempted to publish an update to the library, he was met with the [following error](https://user-images.githubusercontent.com/4963236/100379411-dbdf1a00-303a-11eb-9eb1-c98c97c3bf6d.png).

After reading the documentation for publishing, there's no clear instructions on how to handle uploading from a verified publisher, let alone designating proxy users for uploading new builds on the publisher's behalf. Is that something that's even supported from a Verified Publisher's perspective? Is the Verified Publisher the **ONLY** user that's allowed to publish new versions of a pub.dev library? Just trying to understand the options available to @alternadom, since he's no longer able to maintain the library full time, and he does not remember how to upload new versions to pub.dev. Therefore, he's trying to designate new maintainers to this project who can maintain/release new versions going forward.

Thank you in advance.

**Comment by isoos** [comment]
A publisher can have multiple members, although currently only admin-level members. Any of these members can publish a new version of the package that is under the publisher. (Or for-completes, transfer the package to another publisher - if they are admins in both).

However, packages that are under a publisher cannot have additional uploaders, only the publisher's members can upload new versions.

In your case, you seem to have two options:
- either the publisher of wifi_iot adds you as a member to the publisher, or
- you may register yet another publisher, have both of you as admin there, and transfer the package to the new one.

The first option is typical for companies or teams in companies: it is an easy way to handle access rights to multiple packages.

I've used the later option with https://pub.dev/publishers/aws-dart.agilord.com/packages for the AWS dart packages: the three contributors to the project are working for unrelated companies, and we've agreed to create a new publisher to manage the packages under the project.

Does this answer your question?

**Comment by diegotori** [comment]
@isoos so what you're saying is that @alternadom would have to add me as an Admin-level member of his Verified Project, then that would give me the ability to publish a new build? Also, since he originally added @daadu as an Admin-level member, he too was unable to publish as stated in the original post. Just wondering why Admin-level members cannot publish despite being added as a member of a Verified Project?

**Comment by daadu** [comment]
@diegotori I wasn't able to upload new release because the invitation for membership of publisher was not accepted.

**Comment by isoos** [comment]
> I wasn't able to upload new release because the invitation for membership of publisher was not accepted.

Yes, pending invites do not grant upload rights.

Another issue that can happen is to use two accounts, and while one is authorized, the other is not.

> @alternadom would have to add me as an Admin-level member of his Verified Project, then that would give me the ability to publish a new build?

That is correct.

**Comment by diegotori** [comment]
@isoos was able to confirm that @daadu released a new version to pub.dev. Going forward, I would suggest making the documentation clearer with regards to how a Verified Publisher can publish new releases, by adding Admin level members to the publisher. That way there's no ambiguity when Verified Publishers try to delegate folks to release new updates to projects on their behalf.

**Comment by isoos** [comment]
> I would suggest making the documentation clearer with regards to how a Verified Publisher can publish new releases, by adding Admin level members to the publisher.

Any particular place where you think this is missing?

**Comment by guidezpl** [comment]
I also ran into this issue for our verified publisher. I thinkhttps://dart.dev/tools/pub/publishing#uploaders and maybe https://dart.dev/tools/pub/verified-publishers should be updated.

**Comment by sigurdm** [comment]
I think this is now covered by: https://github.com/dart-lang/site-www/issues/4456 .
