### ISSUE TITLE
Remove Package.downloads and PackageVersion.downloads

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4311]
Properties: 
 * `Package.downloads`, and,
 * `PackageVersion.downloads`,

are  not used, thus, they should probably just be removed.

**Steps**:
 * [x] Set properties to not be required (Flip `@db.IntProperty(required: true)` to make it optional),
 * [x] Annotated properties `@deprecated`,
 * [ ] Make a deployment where properties is not required, and wait for older deployments to be deleted before proceeding.
 * [ ] Remove properties and update `CHANGELOG`,
 * [ ] Run `app/bin/tools/clear_package_properties.dart`

**Comment by isoos** [comment]
This has been done.
