### ISSUE TITLE
'Package does not support Flutter platform Web'   However, it does support the Web

### ISSUE THREAD

**Issue by Andrious** [dart-lang/pub-dev#4317]
Please, I'm not certain how to address the issues cited on my [mvc_application](https://pub.dev/packages/mvc_application) package.

Two issues, in particular, I have no solution.

1)  Support multiple platforms   10/20
     'Package does not support Flutter platform Web'
     package:shared_preferences_windows/shared_preferences_windows.dart that declares support for platforms: Windows

However, I'm using shared_preferences 0.5.12+4 with the web version: shared_preferences_web-0.1.2+7

2) Pass static analysis  0/30
    'ERROR: The named parameter 'nullOk' isn't defined.'

However, I'm using scaffoldstate.dart with that named parameter??
static ScaffoldState of(BuildContext context, { bool nullOk = false }) {

**Comment by isoos** [comment]
1. is now supported via the [platforms](https://dart.dev/tools/pub/pubspec#platforms) key in pubspec.
2. is no longer relevant in the latest version (there is another warning though...)
