### ISSUE TITLE
Request to delete plugin

### ISSUE THREAD

**Issue by RalphNoel** [dart-lang/pub-dev#4319]
Plugin : https://pub.dev/packages/kurukkupattiyal

I was learning to develop a flutter plugin but didn't notice that, no option to delete it from pub.dev after published.
Please delete it or send a delete link.

**Comment by isoos** [comment]
@RalphNoel: please follow instructions as described on the policy page, and contact support via e-mail: https://pub.dev/policy#purpose

**Comment by RalphNoel** [comment]
@isoos After published, How to change a Plugin Name and i want to add Uploader but i got an error : 
 Unsufficient permissions to change uploaders.

**Comment by isoos** [comment]
> How to change a Plugin Name 

Package names are immutable, you cannot change a published package. You can publish a new package with a different name though...

> add Uploader but i got an error: Unsufficient permissions to change uploaders.

Please login on pub.dev with the account that has the uploader rights. Go to the package page, then the admin tab, and you can invite another account to become an uploader. (The new account needs to accept the invitation.)
