### ISSUE TITLE
Request to change the Package Name

### ISSUE THREAD

**Issue by RalphNoel** [dart-lang/pub-dev#4321]
After published, How to change a Plugin Name and i want to add Uploader but i got an error :
Unsufficient permissions to change uploaders.

**Comment by isoos** [comment]
> How to change a Plugin Name

Package names are immutable, you cannot change a published package. You can publish a new package with a different name though...

> add Uploader but i got an error: Unsufficient permissions to change uploaders.

Please login on pub.dev with the account that has the uploader rights. Go to the package page, then the admin tab, and you can invite another account to become an uploader. (The new account needs to accept the invitation.)

**Comment by RalphNoel** [comment]
@isoos pub uploader add  ************@***.com.

This above command will work or not ?

**Comment by isoos** [comment]
It will for now, but we have plans to retire it from `pub`, and use only the pub.dev UI. (The command has little relevance on third-party pub servers.) 

However, if you go with that, please double-check if you are logged in with the correct account, that's the most common reason to get the `Unsufficient permissions to change uploaders` response.
