### ISSUE TITLE
Search button in search bar not working when on the page of a particular package. 

### ISSUE THREAD

**Issue by Ankur-Khandelwal** [dart-lang/pub-dev#4322]
URL: https://pub.dev/packages/sqflite

There is a search bar in the top right of the page, when we enter a package name in the bar and click on the search button, the button doesn't work.

**Comment by isoos** [comment]
Thanks for reporting this.

At the moment the search icon is not a button, only a background image on the search input field. It triggers the input to be focused, which makes it wider (with the little animation). As most users will hit just an enter after typing, I don't think we are in a particular hurry to change this behaviour (it will make the implementation of the search slightly more complex), but will keep this issue open for future entry-level contributions.

**Comment by Ankur-Khandelwal** [comment]
@isoos Yes, you are right. However, still it feels a bit odd when we click on the icon, and it doesn't work. Actually, I have been developing a number of apps on Flutter and Dart lately. So I am frequently using this website. If possible, can you guide me a bit on how to contribute to this ? I would like to fix this.

**Comment by isoos** [comment]
@Ankur-Khandelwal: I'm happy to assist you, here are some pointers:

1. Create a "fake" server with some local data: https://github.com/dart-lang/pub-dev/blob/master/doc/development.md#local-development-without-external-services

2. The input field is in the following template: https://github.com/dart-lang/pub-dev/blob/master/app/lib/frontend/templates/views/shared/site_header.mustache#L16

3. Its style is here: https://github.com/dart-lang/pub-dev/blob/master/pkg/web_css/lib/src/_site_header.scss#L93-L132
4. Building the styles are done via: https://github.com/dart-lang/pub-dev/blob/master/pkg/web_css/build.sh

Unfortunately we still need to port some of the auto-builder code to the fake server, so to make/refresh changes, you may need to re-build the CSS files and restart the server.

Let me know if the above process doesn't work somehow.

**Comment by Ankur-Khandelwal** [comment]
Thank You @isoos for sharing the steps. I did go through them and understood the workflow. However for a few points, I have some doubts. For example, in the first step, its written to initialize with some minimal data by creating a file. Is it written about an yaml file? 

And I might need help in further steps as well, so whether I should ask about them in these comments, or there is some other mode of communication as well ?

**Comment by isoos** [comment]
> in the first step, its written to initialize with some minimal data by creating a file. Is it written about an yaml file?

Yes, you can create the following `test-profile.yaml`:

```yaml
defaultUser: 'your-email@example.com'
packages:
  - name: retry
  - name: http
```

(and then follow the initialization step with `--test-profile=test-profile.yaml`)

> whether I should ask about them in these comments

Comments work fine. You could open a new issue if you want to separate it from this feature or continue a similar issue about the local development process e.g. #4105.

**Comment by Ankur-Khandelwal** [comment]
@isoos I am getting the following error, on trying to create the fake server.
`Error: Could not resolve the package 'args' in 'package:args/command_runner.dart'.
Error: Could not resolve the package 'pub_dev' in 'package:pub_dev/fake/server/fake_server_entrypoint.dart'.
Error: Could not resolve the package 'pub_dev' in 'package:pub_dev/fake/tool/init_data_file.dart'.
bin/fake_server.dart:5:8: Error: Not found: 'package:args/command_runner.dart'
import 'package:args/command_runner.dart';
       ^
bin/fake_server.dart:7:8: Error: Not found: 'package:pub_dev/fake/server/fake_server_entrypoint.dart'
import 'package:pub_dev/fake/server/fake_server_entrypoint.dart';
       ^
bin/fake_server.dart:8:8: Error: Not found: 'package:pub_dev/fake/tool/init_data_file.dart'
import 'package:pub_dev/fake/tool/init_data_file.dart';
       ^
bin/fake_server.dart:11:18: Error: Method not found: 'CommandRunner'.
  final runner = CommandRunner('fake_server', 'Fake pub server')
                 ^^^^^^^^^^^^^
bin/fake_server.dart:12:18: Error: Method not found: 'FakeServerCommand'.
    ..addCommand(FakeServerCommand())
                 ^^^^^^^^^^^^^^^^^
bin/fake_server.dart:13:18: Error: Method not found: 'FakeInitDataFileCommand'.
    ..addCommand(FakeInitDataFileCommand());
                 ^^^^^^^^^^^^^^^^^^^^^^^
`

**Comment by Ankur-Khandelwal** [comment]
@isoos While trying to set up the fake-server, I am getting the following error:
`Error: Could not resolve the package 'args' in 'package:args/command_runner.dart'.
Error: Could not resolve the package 'pub_dev' in 'package:pub_dev/fake/server/fake_server_entrypoint.dart'.
Error: Could not resolve the package 'pub_dev' in 'package:pub_dev/fake/tool/init_data_file.dart'.
bin/fake_server.dart:5:8: Error: Not found: 'package:args/command_runner.dart'
import 'package:args/command_runner.dart';
       ^
bin/fake_server.dart:7:8: Error: Not found: 'package:pub_dev/fake/server/fake_server_entrypoint.dart'
import 'package:pub_dev/fake/server/fake_server_entrypoint.dart';
       ^
bin/fake_server.dart:8:8: Error: Not found: 'package:pub_dev/fake/tool/init_data_file.dart'
import 'package:pub_dev/fake/tool/init_data_file.dart';
       ^
bin/fake_server.dart:11:18: Error: Method not found: 'CommandRunner'.
  final runner = CommandRunner('fake_server', 'Fake pub server')
                 ^^^^^^^^^^^^^
bin/fake_server.dart:12:18: Error: Method not found: 'FakeServerCommand'.
    ..addCommand(FakeServerCommand())
                 ^^^^^^^^^^^^^^^^^
bin/fake_server.dart:13:18: Error: Method not found: 'FakeInitDataFileCommand'.
    ..addCommand(FakeInitDataFileCommand());`

Attaching the screenshot for better readability:
![fake-server](https://user-images.githubusercontent.com/55295915/104997886-5c753200-5a50-11eb-8aa7-b5ebf0cbb242.png)

**Comment by isoos** [comment]
@Ankur-Khandelwal: I think you may need to run `pub get`.

**Comment by Ankur-Khandelwal** [comment]
@isoos Yes. I used `dart pub get` and the dependencies got downloaded. 

After that I typed 
`dart bin/fake_server.dart init-data-file \
  --test-profile=[the file you have created] \
  --analyze \
  --data-file=dev-data-file.jsonl`

Then I received some thousands of lines of output on the terminal which seemed to denote that the things are working. But in the middle, I noted these:

`2021-01-19T14:02:44.941072 [INFO] pub.job: dartdoc failed for latest version of string_scanner (1.0.5): ProcessException: No such file or directory
  Command: pub get`

`2021-01-19T14:02:48.415850 [INFO] pub.job: dartdoc failed for latest version of retry (3.0.1): ProcessException: No such file or directory
  Command: pub get`

and same outputs for `term_glyph`, `meta`, `http_parser`, `http` and other packages.

After that, I used `dart bin/fake_server.dart run --data-file=dev-data-file.jsonl`, which returned the following output:

`2021-01-19T14:30:52.666874 [INFO] pub.static_files: pkg/web_app build status: source: 2020-12-27 10:05:30.000, target: null
2021-01-19T14:30:52.685022 [INFO] pana: Running `pub get`...
Unhandled exception:
ProcessException: No such file or directory
  Command: pub get
`

**Comment by isoos** [comment]
Are you on Windows or Linux/Mac?
What are the logs lines before and after the `ProcessException`?

**Comment by Ankur-Khandelwal** [comment]
I am on Linux - Ubuntu 20.10

There are literally hundreds of log lines here and copying them here would make it too cluttered actually.

**Comment by Ankur-Khandelwal** [comment]
@isoos 
Here is a part of the log:
`2021-01-19T14:03:01.849233 [INFO] pub.scorecard.backend: Creating new report: http_parser 3.1.4 dartdoc.
2021-01-19T14:03:01.851346 [INFO] pub.scorecard.backend: Updating ScoreCard http_parser 3.1.4.
2021-01-19T14:03:01.853185 [INFO] pub.scorecard.backend: Updating ScoreCard http_parser 3.1.4.
2021-01-19T14:03:01.853630 [INFO] pub.job: dartdoc job completed: http_parser 3.1.4
2021-01-19T14:03:01.853859 [INFO] pub.job.backend: Updating http_parser 3.1.4 with JobStatus.success
2021-01-19T14:03:01.855018 [INFO] pub.job: dartdoc job started: http 0.12.2
2021-01-19T14:03:05.797007 [INFO] pana: Running `/bin/chmod -R -x+X /tmp/pub-dartlang-dartdocQEGNVM/pkg`...
2021-01-19T14:03:05.807877 [INFO] pana: Running `/home/ankur/flutter/bin/cache/dart-sdk/bin/pub upgrade --verbosity io --no-precompile`...
2021-01-19T14:03:08.969921 [INFO] pana: Running `pub get`...
2021-01-19T14:03:08.971604 [INFO] pub.job: dartdoc failed for latest version of http (0.12.2): ProcessException: No such file or directory
  Command: pub get`

I have copied the entire log into this google doc: https://docs.google.com/document/d/1WYp-swDr8uq7QKDNXtVf1ZWpICnaF_WAt1xt4H_YLGs/edit?usp=sharing

**Comment by Ankur-Khandelwal** [comment]
Yes @isoos. I am using flutter. Should I add dart sdk into the path ?

**Comment by isoos** [comment]
> Should I add dart sdk into the path ?

Yes. By default we run it from Dart SDK, no idea what happens if you run it from Flutter SDK.

**Comment by Ankur-Khandelwal** [comment]
> > Should I add dart sdk into the path ?
> 
> Yes. By default we run it from Dart SDK, no idea what happens if you run it from Flutter SDK.

Ok. Let me try. I got these instructions below from https://dart.dev/get-dart
![dartSDK_path](https://user-images.githubusercontent.com/55295915/110690373-ded8d180-8209-11eb-9f62-caf2b09172f5.png)

I assume after doing this, ```pub-dev``` will use the Dart SDK.

**Comment by Ankur-Khandelwal** [comment]
@isoos I tried out everything. I added the Dart SDK path to my .bashrc file and the again tried to setup the fake server. I got some logs somewhat similar to previous ones. I have pasted them here https://docs.google.com/document/d/1dTag8C8fsDXLgZOlDzvK56a2SppoorClOrSh27yRK8E/edit?usp=sharing

I even removed the path variable for flutter completely from the .bashrc file in my system to ensure that only Dart SDK was used, but they led to another set of errors.
![dartError](https://user-images.githubusercontent.com/55295915/110710549-16ed0e00-8224-11eb-92a2-9b2018c470a5.png)

**Comment by Ankur-Khandelwal** [comment]
Hi @isoos. I have finally made the "fake-server" run on my local system.  Now I can modify the code and see the changes in my browser. Now I can focus on modifying the search behavior. 

Can you please confirm whether I will also need to make any changes in this file - https://github.com/dart-lang/pub-dev/blob/master/pkg/web_css/build.sh?

**Comment by isoos** [comment]
I hope you won't need to modify the `build.sh`, but it is likely that you will run it (e.g. when running fake server with `--watch`, which I recommend). What makes you think you'll need to modify it?

**Comment by Ankur-Khandelwal** [comment]
> @Ankur-Khandelwal: I'm happy to assist you, here are some pointers:
> 
> 1. Create a "fake" server with some local data: https://github.com/dart-lang/pub-dev/blob/master/doc/development.md#local-development-without-external-services
> 2. The input field is in the following template: https://github.com/dart-lang/pub-dev/blob/master/app/lib/frontend/templates/views/shared/site_header.mustache#L16
> 3. Its style is here: https://github.com/dart-lang/pub-dev/blob/master/pkg/web_css/lib/src/_site_header.scss#L93-L132
> 4. Building the styles are done via: https://github.com/dart-lang/pub-dev/blob/master/pkg/web_css/build.sh
> 
> Unfortunately we still need to port some of the auto-builder code to the fake server, so to make/refresh changes, you may need to re-build the CSS files and restart the server.
> 
> Let me know if the above process doesn't work somehow.

No, just that you had mentioned that file in one of the pointers above. So I wondered if some change is needed there as well.

**Comment by isoos** [comment]
Assuming this is no longer relevant, closing.
