### ISSUE TITLE
pub.dev falsely claims package to be not null safe

### ISSUE THREAD

**Issue by DRSchlaubi** [dart-lang/pub-dev#4330]
Pub gives me this rating: 
![alt text](https://rice.by.devs-from.asia/chrome_wUfsi3XXJz.png "package1")
Pub score: https://pub.dev/packages/contact_picker_platform_interface/versions/4.3.0-nullsafety.2/score

But if you take a look at the score of the dependency dart claims to be not nullsafe you can see here that it is: https://pub.dev/packages/contact_picker_platform_interface/versions/4.3.0-nullsafety.2/score

Which can be confirmed by `dart migrate`:
```
D:\WORK\contact_picker\contact_picker_web>dart migrate
Migrating D:\WORK\contact_picker\contact_picker_web

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\]
All sources appear to be already migrated.  Nothing to do.
```

and `pub outdated`:
```
D:\WORK\contact_picker\contact_picker_web>flutter pub outdated --mode=null-safety
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

All your dependencies declare support for null-safety.

```

pubspec.yaml:
```yaml
name: contact_picker_web
version: 4.3.0-nullsafety.4
description: Use Chromes contact picker to chose phone numbers and email addresses from contacts of the users address book
homepage: https://github.com/DRSchlaubi/contact_picker/tree/feature/web/contact_picker_web

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterContactPickerPlugin
        fileName: contact_picker_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3-nullsafety.3
  contact_picker_platform_interface: ^4.3.0-nullsafety.2

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.24.0-3.0.pre <2.0.0"```

**Comment by isoos** [comment]
@DRSchlaubi: When did you create the screenshot? The score page you've linked does show that the package is null-safe.

**Comment by DRSchlaubi** [comment]
that explains why the other package suddenly became null-safe.
The the issue is that sometimes it will false report it as not null-safe (even if the analysis seems finished as all other scores are there too) and then it updates it

**Comment by isoos** [comment]
Did you check the page shortly after it was uploaded?

I think the following have happened: We have two versions of the site running: the old version is not displayed, but it does analyze uploaded packages, while the new version both analysis and display the most recent data. It may happen that on a new upload the old site completed the analysis a bit faster than the new one, and for a short period we've displayed the old version (as opposed to displaying nothing).

**Comment by DRSchlaubi** [comment]
yes this happens when visiting the site shortly after analysis is done
