### ISSUE TITLE
Very long time for a new publisher to show up for me

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#4334]
I was invited to join the cloud.google.com publisher at 2pm Pacific time – I accepted right away.

I DO have access to https://pub.dev/publishers/cloud.google.com/admin 👍 

At 2:30 it's still not showing up at https://pub.dev/my-publishers

Nor can I see it in the package admin dropdown to move move a package to the publisher. 😢

**Comment by isoos** [comment]
Yeah, we have a long cache timeout for the my-publishers list (4 hours), and a cache purge is missing somewhere.

**Comment by isoos** [comment]
Looking at the code, it seems that we do have the correct cache purge there:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/publisher/backend.dart#L210

However, by accepting the invite, the user is likely to trigger a cache population event within seconds, and at that time `Datastore.query` may not yet return the new entity instance. We need an off-request delayed cache purge here (and possibly at other similar places).
