### ISSUE TITLE
API endpoint for package changelogs

### ISSUE THREAD

**Issue by svenjacobs** [dart-lang/pub-dev#4335]
As mentioned in #2142 I kindly request the addition of an API endpoint for querying a package's changelogs.

Use case: I'm thinking about writing a graphical version of `pub outdated` that also displays all changelogs of outdated library versions starting from _current_ version (+1) to _upgradable_ giving a nice overview of what has changed.

**Comment by jonasfj** [comment]
I think it's better to just download the entire archive and extract the on the fly.

Take a look at `package:tar` it can extract from a stream.

Closing this as I don't think we'll write this end-point anytime soon.
