### ISSUE TITLE
Drag to select doesn't work in example code snippet 

### ISSUE THREAD

**Issue by TahaTesser** [dart-lang/pub-dev#4336]
As part of the Flutter Triage team member, I copy a lot of code every day from the pub.dev.  Whenever I want to select code in the example from any package (if it is long enough), I need to click the source link on top, copy code from there instead of selecting right here on the pub page and drag to select the whole code. 

#### GitHub 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/101879455-5ec5b000-3bb7-11eb-959f-76a699b5d451.gif)

#### When I drag to select inside snippet area in example tab
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/101879529-7c931500-3bb7-11eb-9f89-c07829026674.gif)

#### Drag to select works outside of the snippet area but this will select unrelated text  
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/48603081/101879668-b3692b00-3bb7-11eb-9eb6-e15ecc3abb11.gif)

**Comment by isoos** [comment]
@TahaTesser: thanks for reporting.

A little bit of debugging shows:
- Chrome on Windows works.
- Safari on Mac works.
- Firefox on Mac works.
- Chrome on Mac is affected, but opening Chrome Developer Tools triggers it to work again.
- On Chrome on Mac, the issue it is not related to highlight.js, as disabling it doesn't affect the behaviour.

**Comment by sigurdm** [comment]
Trying this now I am unable to reproduce.

Please reopen if you still see this.
