### ISSUE TITLE
Package with copied code, license violation

### ISSUE THREAD

**Issue by priezz** [dart-lang/pub-dev#4340]
Hello,

The publisher of this package https://pub.dev/packages/sums_inner just copied the code from my StackOverflow answer https://stackoverflow.com/a/60530625/3445280 w/o any change, but put his own copyright. This should be the  license ([CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)) violation. Please remove that package from the repository or change the ownership to myself (same email as in the GitHub). Thank you in advance.

**Comment by isoos** [comment]
@priezz: please follow the process as described on https://pub.dev/policy#copyright-policy 

I'd also suggest that you contact the uploader of the package first. It seems to me that they are a junior developer, still attending university, and might not be fully aware all of the implications of their actions. An official process may take much longer than a mutual agreement if you can reach one.

**Comment by priezz** [comment]
Thank you for the link and for the advice
