### ISSUE TITLE
i can't signin 

### ISSUE THREAD

**Issue by hibkh** [dart-lang/pub-dev#4341]
URL: https://pub.flutter-io.cn/

<Describe your issue or suggestion here>
Hi, I try to sign in but no response.

**Comment by isoos** [comment]
I think you'll need to use https://pub.dev/ to sign in (and don't use content blockers or 3rd-party blocking for the google login).

https://pub.flutter-io.cn/ seems to be a pass-through proxy, not sure if/how login would work there. /cc @jonasfj

**Comment by jonasfj** [comment]
We do not operate `URL: https://pub.flutter-io.cn/`, we cannot vouch for the authenticity, integrity or security of such mirrors.

This is clearly stated: https://flutter.dev/community/china
