### ISSUE TITLE
Unclear which version null safety badge is for

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#4344]
We currently place the null safety badge before the versions:
<img width="832" alt="Screenshot 2020-12-14 at 15 07 52" src="https://user-images.githubusercontent.com/13644170/102090911-5ae79700-3e1e-11eb-8ef6-0240a5ebde8a.png">

I think it would be clearer if we placed it next to the version(s) with null safety support (so a package with it in both stable and pre-release would have it twice). WDYT?

**Comment by isoos** [comment]
On the package page, the badge is present if the currently displayed version has an `is:null-safe` tag. In the most complex case, we have three versions displayed:
- the selected version (header + content)
- latest stable version link
- latest prerelease version link

I think if we put the badge after each of these version, it will increase the confusion.

Maybe the latest and the prerelease links should go between the SDK tags and the readme tab bar?

**Comment by alexeyinkin** [comment]
Maybe it's time to show a badge on non-null-safe packages? This way properly maintained packages will not have cluttered headers. And the negative badge will encourage package maintainers to migrate.

**Comment by sigurdm** [comment]
Most likely we want a "Dart-3-ready" badge (null-safety, but not using deprecated items removed in dart-3).

Or even better a **disapproving badge** for packages that are not dart-3-ready.
Maybe we can make a variation of the "legacy"-badge that currently covers dart-1 packages: https://pub.dev/packages?q=show%3Aunlisted+svg .

This will be reconsidered elsewhere when we get closer to dart-3. So closing this for now.

**Comment by sigurdm** [comment]
Follow https://github.com/dart-lang/pub-dev/issues/6023
