### ISSUE TITLE
Click to zoom on images

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4357]
In the README...

For all images where the image is also a link to the image itself. This way, badges, etc won't have this feature.

Example, we want to detect:
`[[!alt text](https://image-link)](https://image-link)`

-------------

![8Me9a4tygYojgHy](https://user-images.githubusercontent.com/149732/113143413-66739800-922c-11eb-9a1c-2aff256c6643.png)

**Comment by sigurdm** [comment]
This is relevant because we currently display images with `max-width: 100%`.

**Comment by sigurdm** [comment]
Questions about this feature. It is not clear that we want this, especially after we landed screenshots...
What about images that are also links?
What about badges?

Do we need image proxying for this, such that we know ahead of time how big images are?

**Comment by sigurdm** [comment]
Closing @jonasfj do you agree?
