### ISSUE TITLE
Get an error when I invite a new member to my publisher.

### ISSUE THREAD

**Issue by okadan** [dart-lang/pub-dev#4360]
1. Go to `https://pub.dev/publishers/[MY DOMAIN]/admin`.
2. In `Members` section, press the `ADD MEMBER` button.
3. Enter the new member's email and submit.

As a result, I received the following message in popup:

`Internal server error, ask operator to lookup incidentId: fd5d9e97-5746-4afd-8d3d-79c80d9ad7d3`

**Comment by isoos** [comment]
Hm, that seems to be a strange case:

```
Error:
    Exception: More than one User exists for email: <-- redacted -->

Stack:
    #0      AccountBackend.lookupUserByEmail (package:pub_dev/account/backend.dart:147:7)
    <asynchronous suspension>
    #1      PublisherBackend.invitePublisherMember (package:pub_dev/publisher/backend.dart:331:46)
    <asynchronous suspension>
    #2      PubApi.invitePublisherMember (package:pub_dev/frontend/handlers/pubapi.dart:194:24)
```

Was there any special event with this e-mail address of yours? (E.g. aliases, migrated to/from different GSuite domains...)
/cc @jonasfj

**Comment by okadan** [comment]
@isoos  I'm concerned that I used this email (not @gmail.com) temporarily to create other Google Account in the past.

**Comment by jonasfj** [comment]
@okadan that explains it...

So we have two users registered on the same email..

Maybe we shouldn't try to to associate the invite with a user-id until it's been accepted.

**Comment by okadan** [comment]
But I can login to pub.dev with this email.

This means that pub.dev has only one account associated with this email.

So invite should also be successful.

**Comment by jonasfj** [comment]
We've just deployed a fix, please try again :D

**Comment by okadan** [comment]
@isoos @jonasfj 

The invite was successful.

Thank you for your great work.

**Comment by jonasfj** [comment]
Awesome 💯
