### ISSUE TITLE
print the url to the package (pub.dev/packages/my_package) after a pub publish operation

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pub-dev#4363]
After publishing a package, the pub tool should print out the url of the package on pub.dev. This would be similar to the behavior of `git` after pushing to a branch.

Here's the current behavior:

```
Uploading... (3.0s)
Successfully uploaded package.
```

And what `git` prints:

```
...
Writing objects: 100% (7/7), 658 bytes | 658.00 KiB/s, done.
Total 7 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: 
remote: Create a pull request for 'fix_subscription_leak' on GitHub by visiting:
remote:      https://github.com/devoncarew/flutter-intellij/pull/new/fix_subscription_leak
```

**Comment by isoos** [comment]
I think the server-provided message will be important if we go for staged publishing, and the URL needs to be dynamic. It would be nice to start with something like this though...

**Comment by elbeicktalat** [comment]
For sure it will be helpful, but I think this a staff of the command line tools.

**Comment by isoos** [comment]
Closing the issue, as for a while now, we emit the package page URL in the message from the server.
