### ISSUE TITLE
Show more information added by authors on the search results page (e.g., images, external links)

### ISSUE THREAD

**Issue by jayoung-lee** [dart-lang/pub-dev#4365]
In a recent user study, users really liked that Flutter has its dedicated package site. Yet, users searched on Google when they don't know about the problem area very well or when they need images.

Good search system may make it easy to access all the information. We can consider adding more information to pub.dev, such as images as well as relevant external resources (such as tutorials), if authors add the information. Featuring this information may motivate authors to add images and other resources.

See the suggestion below.

<img width="963" alt="sample" src="https://user-images.githubusercontent.com/11873270/102838690-ad432d80-43b3-11eb-921a-81be7661d30b.png">

**Comment by InMatrix** [comment]
Is it time to celebrate and close this issue with https://github.com/dart-lang/pub-dev/pull/6015?

**Comment by sigurdm** [comment]
Well - there are still more things we could show in the search results page. Eg. the repository link.

**Comment by sigurdm** [comment]
Maybe we should not put more information (ie. the repository link) in the search results to not bloat them with too much information before we have research showing that these specific pieces of information are genuinely useful.

If we want a repository link, it should probably be a small icon to not take up too much space.

**Comment by jayoung-lee** [comment]
I agree that icons could provide valuable package information without cluttering search results. Instead of a repository link, however, users might find metrics like update frequency and open issue counts more helpful. 

But I also agree that we should also consider a minimalist approach, as the results already provide a good amount of information. :)

**Comment by sigurdm** [comment]
Closing this issue for now as not actionable.

Feel free to open new issues with specific things we should add to the result listings.
