### ISSUE TITLE
Further search bar improvement is possible 🥰

### ISSUE THREAD

**Issue by orsenkucher** [dart-lang/pub-dev#4390]
Yo, just saying, further improvement is possible 🥰 
![image](https://user-images.githubusercontent.com/15790628/103356716-2e887780-4aba-11eb-9ae3-d3fa46cdea30.png)
![image](https://user-images.githubusercontent.com/15790628/103356728-38aa7600-4aba-11eb-9524-9704068ac628.png)
![image](https://user-images.githubusercontent.com/15790628/103357508-08fc6d80-4abc-11eb-9fe7-a6f6aff3efb0.png)

---

Consider making search box always open, consider adding shortcut to focus on it. Search is an essential thing, why to hide it?
![image](https://user-images.githubusercontent.com/15790628/103356870-89ba6a00-4aba-11eb-879f-2e1f8afde96a.png)

_Originally posted by @orsenkucher in https://github.com/dart-lang/pub-dev/issues/3958#issuecomment-752639400_

**Comment by jonasfj** [comment]
Could it be that `/` open search, like it does on github...

Also we could make the cursor a "pointer" and give the search icon a  tooltip...

**Comment by orsenkucher** [comment]
You can leave the cursor as is. Just suggesting to reduce number of steps required to begin search
![image](https://user-images.githubusercontent.com/15790628/104345878-7c17d200-5507-11eb-9eae-7224867c468f.png)
Github search looks like Github, but not that bad... agree? @jonasfj
