### ISSUE TITLE
Required to include one screenshot publication/update package

### ISSUE THREAD

**Issue by fabioselau077** [dart-lang/pub-dev#4397]
URL: https://pub.dev/

We have a lot of good UI packages, but they don't even have a screenshot in the description, which ends up reducing consumption, since you can't get a preview of how it will look when using the package.
The solution is to be **required** to include at least one screenshot of the final product when the package is related to the UI in the **publication/update** of the package on pub.dev.

**Comment by isoos** [comment]
I think that can leave this up to the developer: if they want to include screenshots, they can do so by including them in the `README.md`, and pub will display them. Requiring it will lead to a lot of fake screenshots, code screenshots and similar solutions for packages that are not mainly for the UI.

We had prior discussions and maybe even open issues about having a runnable example for UI projects, that we can "play" on the package page, however the required infrastructure (including isolation and security) is just not there yet.
