### ISSUE TITLE
Support preview releases on pub.dev

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#4404]
Currently we differentiate between two kinds of package versions on pub.dev:

  1. Stable versions: Package versions that use a stable version format, x.y.z
  2. Prerelease versions: Package versions that use a prerelease version format, x.y.z-prerelease_suffix

An example is the current `characters` package, which has a version 1.1.0 stable version and a 1.1.0-nullsafety.5 prerelease:

<img width="773" alt="Screenshot 2021-01-12 at 14 45 47" src="https://user-images.githubusercontent.com/13644170/104322170-e66b4b00-54e4-11eb-8a42-3d35d0ce172f.png">

It can be convenient to allow publishing future stable versions of a package (e.g. characters 1.1.0 stable)
prior to the corresponding stable Dart release (Dart 2.12 stable) being available. If that is done on the current pub.site, then the pub UI would suddenly recommend `characters: 1.1.0` as the main stable version to all consumers, despite this depending on a non-stable SDK.

The present bug proposes refining the pub UI to show three kinds of versions:

  1. Stable versions: Package versions that use a stable version format, x.y.z, AND depend on a stable Dart SDK
  1. Preview versions: Package versions that use a stable version format, x.y.z, AND depend on a Dart SDK which is higher than the current stable Dart SDK
  1. Prerelease versions: Package versions that use a prerelease version format, x.y.z-prerelease_suffix

Here is an example of how we would render this for characters after a `1.1.0` version has been published, which depends on Dart `2.12.0-200-0.beta`, in a situation where the most recent stable Dart SDK is `2.10`:

<img width="779" alt="Screenshot 2021-01-12 at 14 21 23" src="https://user-images.githubusercontent.com/13644170/104322180-e9fed200-54e4-11eb-80d9-1610bad4b0f9.png">

**Comment by mit-mit** [comment]
Note: the screenshot above it a bit confusing; you would not see `Preview: 1.1.0` and `Prerelease: 1.1.0-nullsafety.5` together (as we'd continue to hide prereleases which are < than the most recent stable or preview release). But you might see `Preview: 1.1.0` and `Prerelease: 1.2.0-foobar.1`.

**Comment by mit-mit** [comment]
Functionality note: We probably also need to update the version tags on the search pages:
<img width="660" alt="Screenshot 2021-01-12 at 19 44 39" src="https://user-images.githubusercontent.com/13644170/104358409-b2a51b00-550e-11eb-8f6e-48ba7093c907.png">

**Comment by kevmoo** [comment]
Do we every explain what the distinction is?

**Comment by mit-mit** [comment]
> Do we every explain what the distinction is?

we're planning on adding tool-tips that help to explain this + docs on dart.dev

**Comment by mit-mit** [comment]
@domesticmouse had a great question about this one: what do we do in places like `pub outdated` and the pub.dev APIs with these preview packages?

**Comment by jonasfj** [comment]
In `pub outdated` preview will show up in `latest`, but not `resolvable`.

We could treat _preview_ the same way was we treat _pre-release_. But I'm not sure that's super important, because `pub outdated` does distinguish between _resolvable_ (latest that can be installed) and _latest_.

**Comment by mit-mit** [comment]
Ah, yes, won't be in resolvable for a developer with a stable SDK. That sounds good. Not worried about `pub outdated` then.

I guess for APIs it's OK to do nothing either, as a client can itself do the 'preview' filtering if needed?

**Comment by jonasfj** [comment]
deployed
