### ISSUE TITLE
my plugin is not building in ios, but example inside the plugin works

### ISSUE THREAD

**Issue by nooralam6** [dart-lang/pub-dev#4413]
I have tried to embed cryptlib from android and ios source from here is the repo: https://github.com/nooralam6/Cross-Platform-AES

It works in ios inside example project in flutter plugin 

when I published the plugin, to use it in other flutter projects, after getting with pub, it does not build in ios but works in android

```Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CryptlibPlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

here is my plugin link: https://pub.dev/packages/cryptlib

Please help me out with this, I have tried every solution like updating flutter, flutter clean, and other suggestions like changing the build setting of workspace, changing build setting for arm64.

**Comment by isoos** [comment]
The issue tracker is for the `pub.dev` site, please report issues with individual packages to their own repositories.
