### ISSUE TITLE
Migrate tar usage to package:tar

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4440]
I've done a decent review of https://pub.dev/packages/tar, it's all streaming in-memory.. Reasonably easy to use.
I propose that we:
 * [ ] Verify all tar archives on pub.dev can be read with `package:tar`
 * [ ] Migrate pub.dev to use `package:tar` read incoming archives, rejecting all archives that can be parsed by `package:tar`.

We could compare incoming archives against GNU tar too, to test for correctness in `package:tar`, but it looks reasonably well tested, so I propose we instead fix issues when users report them to us. So long as our rejection message about whatever was uploaded being an invalid tar archive gives users a pointer to where bugs should be reported we can roll `package:tar` serverside and undo it if something goes wrong.

**Comment by isoos** [comment]
Work on this is blocked on `package:tar`'s dependency on Dart SDK 2.12, pub-dev is still on 2.10.
