### ISSUE TITLE
If you add / at the end of https://pub.dev/packages/package_name, you get 404

### ISSUE THREAD

**Issue by nohli** [dart-lang/pub-dev#4444]
* https://pub.dev/packages/hue_rotation => working
 * https://pub.dev/packages/hue_rotation/ => 404
 * This is a new behavior, since I've bookmarked some packages including the trailing `/` - and the bookmarks stopped working today (maybe a few days earlier)
 * It's not necessarily a bug, but a different behavior than before

**Comment by jonasfj** [comment]
I think redirect `https://pub.dev/packages/hue_rotation/ -> https://pub.dev/packages/hue_rotation` might be a good solution.

**Comment by isoos** [comment]
We don't have any API that ends with `/`, but we do redirect `/documentation/<package>/<version>` -> `/documentation/<package>/<version>/`.

**Comment by isoos** [comment]
The code that caused the regression: https://github.com/dart-lang/pub-dev/pull/4396/files#diff-098effa5d2845729238d877a315be15db5859b4b7b987f4cce9b35c4e126a890R324-R330
