### ISSUE TITLE
Which flutter version does pub.dev use for dartdoc for prerelease versions?

### ISSUE THREAD

**Issue by nohli** [dart-lang/pub-dev#4452]
* After publishing a prerelease version to pub.dev yesterday, the score was really low
 * https://pub.dev/packages/simple_html_css/versions/3.0.0-nullsafety.0/score
 * The log said:
 ```
runtime: 2021.01.18
toolEnv Dart SDK: 2.12.0-133.2.beta
runtime Dart SDK: 2.10.0
pana: 0.14.10
dartdoc: 0.39.0
flutter: 1.25.0-8.1.pre
usesFlutter: true
started: 2021-01-27T11:21:31.806001Z
```
 ```
Because simple_html_css depends on html_unescape >=2.0.0-nullsafety.0 which requires SDK version >=2.12.0-133.7.beta <3.0.0, version solving failed.
pub finished with exit code 1
```
 * But the required sdk version `2.12.0-133.7.beta` is the latest version used by flutter beta `1.25.0-8.3.pre`
 * These are the recent flutter beta versions:

```
1.25.0-8.3.pre | 5d36f2e | 1/15/2021
1.25.0-8.2.pre | b0a2299 | 1/6/2021
1.25.0-8.1.pre | 8f89f65 | 12/16/2020
```

**Comment by isoos** [comment]
As the log says `flutter: 1.25.0-8.1.pre`, and that was the version being used for it. We are in the process to upgrade the Flutter SDK used by pub dev to `-8.3.pre`, and the site will automatically reanalyze the package and regenerate the docs with the new version. The upgrade is a manual process, we don't auto-upgrade to new SDK versions.
(And in general we usually depend on stable SDK versions, this time we do the beta channel to help null-safety migration).
