### ISSUE TITLE
/readiness_check failReason:"disk full"

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4458]
Happens for both `dartdoc` and `analyzer`.

**Comment by isoos** [comment]
On some machines, the tool environment cycle's (which is capped either by 50 analysis or going over a threshold size for pub cache) reached over 100 as the counters in the log report. That part seems to be okay.

When there is a disk full readiness check failure, there is an accompanying log entry that goes along the lines:

> "Free disk space (570 MB) is lower than threshold value 800 MB. Reporting instance permanently unhealthy. Note: different instances will have a different threshold value."

Based on the logs, I think the process of handling the temporary directory for pub cache is okay, assuming that there is no hanging/timed out but not killed process that writes into it later.

We should further monitor the following:
- [ ] a separate base directory used only for the pub caches
- [ ] the system temp directory
- [ ] the tool directories (Dart and Flutter SDKs)

**Comment by isoos** [comment]
The issue seems to be gone from the logs.
