### ISSUE TITLE
Target platform not consistently available when using API

### ISSUE THREAD

**Issue by philippecade** [dart-lang/pub-dev#4480]
I want to use the API to determine whether a given package supports the web platform or not but the supported platforms don't always appear in the response.

Examples
* https://pub.dev/api/packages/auto_size_text information is missing
* https://pub.dev/api/packages/shared_preferences information is available

The information is shown on the package pages (e.g. https://pub.dev/packages/auto_size_text) but not available via the API.

**Comment by isoos** [comment]
@philippecade: I'm not sure: what information is available in one that is missing in the other?

@jonasfj: maybe we should consider having a separate `/api/packages/<p>/tags` endpoint?

**Comment by philippecade** [comment]
Sorry I should have been more detailed. I am missing the "flutter/plugin" node in the response for shared_preferences and it is missing in auto_size_text:

```
...
"pubspec": {
            "name": "shared_preferences",
            "description": "Flutter plugin for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS a            
            "homepage": "https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences",            
            "version": "0.5.12+4",
            "flutter": {
                "plugin": {
                    "platforms": {
                        "android": {
                            "package": "io.flutter.plugins.sharedpreferences",
                            "pluginClass": "SharedPreferencesPlugin"
                        },
                        "ios": {
                            "pluginClass": "FLTSharedPreferencesPlugin"
                        },
                        "linux": {
                            "default_package": "shared_preferences_linux"
                        },
                        "macos": {
                            "default_package": "shared_preferences_macos"
                        },
                        "web": {
                            "default_package": "shared_preferences_web"
                        }
...
```

I assume that if I can find a flutter/plugin/platforms/web node in the pubspec that this plugin supports the web platform. My assumption may be however wrong.

If my assumption is wrong, it would be nice to have the list of supported platforms somewhere else in the tree.

**Comment by isoos** [comment]
The data under `pubspec` is the parsed, but otherwise unmodified content of the `pubspec.yaml`, it doesn't contain any analysis that pub.dev otherwise does. We use [pana](https://pub.dev/packages/pana) to do additional analysis of the package, including platform support, and the tags you see on the package page are coming from that data. Some of it may be inferred from the `pubspec` content (although it may be wrong or incomplete).

We expose some of this data on API endpoints for internal debugging, but there is no guarantee that these endpoints will work in the long term. Can share some information on what you'd like to use this for?

**Comment by philippecade** [comment]
We are developing a Flutter app that now runs on Android and iOS and now we would like to also run in the browser. So we're interested in finding out if we use some packages that don't support the web platform.

Pana is what I was looking for, thank you for the link. This tool totally provides all the information that I need, also for example what kind of licenses the packages are using so we can document our product correctly. I will be using this then instead of the API.

Thanks for you help.
