### ISSUE TITLE
'Pub is not feeling well'

### ISSUE THREAD

**Issue by imrhk** [dart-lang/pub-dev#4485]
Requested URL: https://pub.dev/packages/firebase_remote_config
Request ID: f52ae00df3e2487e38414e1876713139

**Comment by XutongGithub** [comment]
the same to me, anyone know why?

**Comment by jonasfj** [comment]
We had a partial service interruption after hitting some sanity limits :)

Afaik we resolved the issue within 30min, if you still see something please reopen.
