### ISSUE TITLE
Packages cannot be downloaded from Sudan

### ISSUE THREAD

**Issue by okahmed** [dart-lang/pub-dev#4515]
URL: https://pub.dev/help
Hi
Packages cannot be downloaded from Sudan

According to www.bis.doc.gov, Sudan has been removed from the list of prohibited countries

**Comment by jonasfj** [comment]
Is the problem downloading the actual package files like:
`https://storage.googleapis.com/pub-packages/packages/retry-3.0.1.tar.gz`

Which is stored on Google Cloud Storage, I'm not sure we can do much about that..
It might be blocked by ISP or something else I don't quite understand.
