### ISSUE TITLE
Example readme link broken

### ISSUE THREAD

**Issue by vaind** [dart-lang/pub-dev#4516]
In a multi-package repository, the link-to-self (`example/README.md`) generated on the example tab points to a wrong path. Is there a workaround? Or can we get rid of that link (doesn't provide much value, since you're looking at the same page anyway)?

Example: https://pub.dev/packages/objectbox/example

**Comment by isoos** [comment]
@vaind: in your `pubspec.yaml` you can provide a deep link into the repository, and (relative) links will be calculated against it. e.g.: `https://github.com/<org>/<repo>/tree/master/<dir>/<subdir>`

**Comment by vaind** [comment]
Thanks I'll try that and reopen if it doesn't work :D
