### ISSUE TITLE
How to publish package for a specified group of users?

### ISSUE THREAD

**Issue by Vishnupriya-M** [dart-lang/pub-dev#4520]
Hi,
Is there an option to publish a flutter package for a specified group and not publically??

Thank you.

**Comment by sigurdm** [comment]
No - you should either 

* host your own pub-server (though unfortunately authentication is not supported for 3rd party servers yet: https://github.com/dart-lang/pub/issues/1381)
* use git dependencies hosted in private repos https://dart.dev/tools/pub/dependencies#git-packages

I close this as we have no current plans for supporting "private packages" on the pub.dev site.

**Comment by Vishnupriya-M** [comment]
Ok..Thank you for your reply.

**Comment by Vishnupriya-M** [comment]
What happens if I mentioned any private git url  as home page? Actually I tried to publish one package like that..but just kept a common name.It showed successfully uploaded but I cant see that in search . Then I tried to update the version and publish it ,showed some error like I dont have permission to do that.( I can see a package with same name as that of mine that is published before  )
