### ISSUE TITLE
Option to remove API reference from pub.dev page

### ISSUE THREAD

**Issue by timsneath** [dart-lang/pub-dev#4521]
Since the pub.dev site doesn't support the full range of options available in `dartdoc`, I publish my own version of the docs for my package at https://win32.pub. 

But while the package page offers this link ("Documentation"), it also offers a link to the inferior, pub-generated version of my dartdoc pages ("API Reference"). 

This is confusing and results in unnecessary duplication. I don't think there's a way for me to suppress this from `pubspec.yaml`, is there? I think this is an issue with pub.dev.

See:
https://pub.dev/packages/win32/versions/2.0.0/score

**Comment by sigurdm** [comment]
We would rather have the generated documentation improved.

If we allowed pass-through of dartdoc options for categories, would you consider the pub.dev docs to be on-par with what you serve?

One issue with overriding the generated api docs is that privately hosted documentation can be missing in other aspects (for example https://win32.pub is not versioned).

Here are a list of all current dartdoc options and considerations of whether we should allow pass-through:
* categories: pass-through.
* categoryOrder: pass-through
* examplePathPrefix: pass-through (perhaps check that the relative path doesn't escape the package folder)
* exclude: pass-through
* errors: ??
* favicon: avoid - we want pub.dev documentation to have a consistent look and feel
* footer: avoid - we want pub.dev documentation to look consistent
* footerText: avoid - we want pub.dev documentation to look consistent
* header: avoid - we want pub.dev documentation to look consistent
* ignore: ???
* include: pass-through
* includeExternal: ???
* linkTo: avoid - we want to control link creation on pub.dev
* url: avoid - we want to control link creation on pub.dev
* linkToSource: ??? I guess we want to control this
* excludes: A list of directories to exclude from processing source links.
* root: ???
* uriTemplate: avoid we want to control link creation on pub.dev
* nodoc: pass-through
* warnings: ???
* tools: avoid until we have better execution control (sandboxing) of the dartdoc generation.

**Comment by timsneath** [comment]
Thanks! For me personally, yes -- I think categories is the big thing I'm missing. 

But I suspect we want to empower package authors to make their own decisions here. Otherwise why have a documentation link at all? Some publishers may want to host their documentation, for consistency and alignment with their other offerings.

**Comment by isoos** [comment]
> Otherwise why have a documentation link at all?

Tutorials, videos, podcasts or books (or their collection of) could be linked there.

By providing the API docs regardless of the link, we make sure that consumers of the package are able to read the documentation in cases when the publisher's content changes, domain expires, or project is dropped.

**Comment by timsneath** [comment]
I'd love that the 'golden path' doesn't encourage customers to bifurcate their documentation, whether by allowing more flexibility in what dartdoc allows, or by allowing more flexibility in how customers host their documentation. 

Allowing categories and custom Markdown pages in dartdoc is a viable path.

**Comment by isoos** [comment]
This update has been deployed, and API documentation is being generated with categories specified in `dartdoc_options.yaml`. @timsneath Is there anything else here that you'd like to change?

**Comment by timsneath** [comment]
Sorry -- things got a bit busy and I didn't get round to replying. But this is great -- thanks! The styling on pub.dev is slightly nicer than the raw styling from `dartdoc` so this is a good update. I'll update my package and domain to point to the pub.dev hosted version over the weekend.

**Comment by parlough** [comment]
@timsneath I plan to work on some style improvements to dartdoc's base HTML generator soon. Any simple wins you have in mind?

**Comment by timsneath** [comment]
What a kind offer!

@mit-mit might well have some specific thoughts. In terms of pure _style_ (as in CSS), I'd love to see the dartdoc output become a little more consistent with pub.dev itself. It's very vanilla right now; not that there's anything wrong with that, but people loved the redesign of pub.dev, and I'd love to see this get similar love at some point. 

There are other potential changes to what's generated -- for example, it's unclear that we need to include properties and methods like `runtimeType`, `noSuchMethod()` and `toString()` on every single class just because `Object` has them. And  a [page like this](https://pub.dev/documentation/win32/latest/win32/win32-library.html) is unwieldy because of the sheer quantity of types expressed in the library. In both these cases, there's perhaps the possibility of hiding or collapsing regions so that the important stuff is immediately visible. 

Is that helpful?
