### ISSUE TITLE
Display audit log

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#4525]
- [x] for a package (only for admins, new tab?)
- [x] for a publisher (only for admins, new tab?)
- [x] for the logged-in user (new tab?)

**Comment by kevmoo** [comment]
What would `for the logged-in user` mean? Who sees what where?

**Comment by isoos** [comment]
> What would for the logged-in user mean? Who sees what where?

Similar to my-packages, my-publishers, we could have a my-events. You would see the events that you did or were part of (e.g. was invited).

**Comment by kevmoo** [comment]
Makes sense!

**Comment by jonasfj** [comment]
Yeah, we need to write up a short design document for this first, and drive it through privacy reviews.

**Comment by jonasfj** [comment]
> Yeah, we need to write up a short design document for this first, and drive it through privacy reviews.

Done.

--------

Also we've decided to rename it to "Activity Log".

**Comment by IchordeDionysos** [comment]
Is it released yet? :)

**Comment by isoos** [comment]
@IchordeDionysos not yet, but hopefully soon

**Comment by IchordeDionysos** [comment]
@isoos thanks, it's a great start already 😍

Would be great to know which activity logs are shown and what they mean.
Might make sense to provide a link to read about this somewhere on the log page.

**Comment by isoos** [comment]
Until there is a documentation, you might want to take a look at this list:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/audit/models.dart#L596-L663
