### ISSUE TITLE
"Failed to run dartdoc" with blank output

### ISSUE THREAD

**Issue by aleksanderwozniak** [dart-lang/pub-dev#4528]
For some reason autogenerated dartdoc on pub.dev failed, and the output is blank:

<img src="https://user-images.githubusercontent.com/22658673/108345456-92880c00-71de-11eb-9b25-5886968eff9c.PNG" width="600">

This issue seems to have happened very recently, as v2.3.3 of the package had correctly generated docs all the time since its upload. I haven't noticed this problem with any of my other packages. Also, when I run dartdoc locally, the docs are generated successfully. 

Docs for previous versions seem to be intact:

<img src="https://user-images.githubusercontent.com/22658673/108345465-961b9300-71de-11eb-8c9a-2681f303232b.png" width="600">

Here is a link to the package: https://pub.dev/packages/table_calendar

**Comment by isoos** [comment]
It looks like that the package is around the size where `dartdoc` takes too much time to generate the docs, and we cut it after the threshold. We do retry such packages automatically, and yesterday it had a successful run, and now documents are serving.
