### ISSUE TITLE
Nit: Improve headlines on front page

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#4534]
The sections on the front page have headers like:

> Top Dart packages
> Top packages for any Dart-based app or program

And then follows a **random sample** of the 100 top packages.

This is slightly confusing. From the wording I would think it would be the 6 **absolute** top packages.

One could perhaps phrase it as: "A sample of the top packages for any Dart-based app or program"

**Comment by jonasfj** [comment]
Maybe something like:

![3u5eYWWLfqmtU8n](https://user-images.githubusercontent.com/149732/108519201-b6744c00-72c9-11eb-952f-85d36fae7cd7.png)

**Comment by jonasfj** [comment]
@mit-mit do you have any preference here?

I think prefixing `A slice of ` or `A sample of ` would work.

**Comment by mit-mit** [comment]
Can we just say "Some of the most..." ?
