### ISSUE TITLE
API documents not getting generated in pub

### ISSUE THREAD

**Issue by dharanidharandharmasivam** [dart-lang/pub-dev#4536]
We have published [our package](https://pub.dev/packages/syncfusion_flutter_charts) in the pub. After publishing the new version, the API documents are not generated and shown as failed to run `dartdoc `which I have shown below.

![image](https://user-images.githubusercontent.com/19346074/108532150-8d6dae80-72fd-11eb-98dc-e61196b0ae76.png)

But from the above, I couldn't find the exact cause/issue. I have tried to replicate this locally, but while generating API documents using `dartdoc `command, there were no errors in it, and API documents are generated properly. I have ensured in the latest stable and beta channels. In both, API documents are generating properly without any errors.

In the **stable** channel, dartdoc tool version is **0.32.4** and in the **beta** channel, dartdoc tool version is **0.39.0**.

### Steps to Reproduce

1. Download the package
2. Run dartdoc

<details>
  <summary>Logs</summary>
```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.22.6 at C:\FlutterSDK\flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\TempKaruna\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
```

</details>

**Comment by dharanidharandharmasivam** [comment]
Hi Team,

Any update on this?

Thanks,
Dharani.

**Comment by isoos** [comment]
We have a pending change that improves the reporting on `dartdoc` timeouts, and it seems that it did timeout on this package.

**Comment by jhomlala** [comment]
Same here: https://pub.dev/packages/better_player

Tried to generate dartdoc locally, but it didn't give any output for 5 minutes and more.

**Comment by JayavigneshwaranG** [comment]
@isoos , Can you please let us know when this will be fixed? 

We have published a new version of our package(https://pub.dev/packages/syncfusion_flutter_charts) today, but still, the same issue persists. Our customers couldn't view the latest API documentation from pub.dev because of this. 

All help on this is really appreciated.

**Comment by dharanidharandharmasivam** [comment]
Hi @isoos ,

Thanks for the revert. Today we have published another version 18.4.44, but the same result, the score got reduced without showing any errors.

<img width="590" alt="Screenshot 2021-02-23 at 5 51 04 PM" src="https://user-images.githubusercontent.com/19346074/108842857-e8561d00-75ff-11eb-8751-c7127bef43c6.png">

Can you please let me know when your pending changes will get moved

**Comment by isoos** [comment]
There is an ongoing investigation why some of the packages experience larger than usual dartdoc generation and timeout on pub.dev. We have some leads, and expect to fix it next week.

**Comment by JayavigneshwaranG** [comment]
@isoos , Just for your reference. Now we have got this timeout log in our latest update. 
![image](https://user-images.githubusercontent.com/19405163/109797174-1ad6ca00-7c3f-11eb-8e74-c1e9e64b09ea.png)

**Comment by isoos** [comment]
It seems that the latest `dartdoc` combined with a recent Flutter SDK resolved the timeouts in the packages mentioned here. I've checked the time it took to run dartdoc, and it was usually in a few minutes (vs. the previous 20+ minutes). I think we can close this issue.
