### ISSUE TITLE
Pub score calculated incorrectly

### ISSUE THREAD

**Issue by tneotia** [dart-lang/pub-dev#4537]
I recently published a new package and looked at the score `pana` returned, and it seems wrong:

![image](https://user-images.githubusercontent.com/50850142/108572555-8f754480-72e0-11eb-93f5-2ceacf444b64.png)

When I run `pana` locally I get back a score of 80 (I think this is the correct score) and then a score of 70.

<details>

INFO       Running `C:\flutter\bin\cache\dart-sdk\bin\dart.exe --version`...
INFO       Running `flutter.bat --no-version-check --version --machine`...
WARNING    pana might update or modify files in `C:\Users\tanay\html_editor_enhanced`.
           Analysis will begin in 15 seconds, hit CTRL+C to abort it.
           To remove this message, use `--no-warning`.
INFO       Running `flutter.bat --no-version-check packages pub upgrade --verbosity io --no-precompile`...
INFO       Analyzing package...
INFO       Running `C:\flutter\bin\cache\dart-sdk\bin\dartanalyzer.bat --options C:\Users\tanay\html_editor_enhanced\pana_analysis_options_1613777506333685.g.yaml --format machine lib`...
INFO       Running `flutter.bat --no-version-check format --dry-run --set-exit-if-changed C:\Users\tanay\html_editor_enhanced\lib`...
INFO       Running `C:\flutter\bin\cache\dart-sdk\bin\pub.bat get`...
INFO       Running `C:\flutter\bin\cache\dart-sdk\bin\pub.bat outdated --json --up-to-date --no-dev-dependencies --no-dependency-overrides`...
FINE       Downloading: https://pub.dartlang.org/api/packages/mime

### [*] 10/10 points: Package has an example

* Found example at: `example/lib/main.dart`

### [~] 10/20 points: Supports 2 of 3 possible platforms (**iOS**, **Android**, Web)

Found 6 issues. Showing the first 2:

Consider supporting multiple platforms:

<details>
<summary>
Package does not support Flutter platform Web
</summary>

Because:
* `package:html_editor_enhanced/html_editor.dart` that imports:
* `package:html_editor_enhanced/html_editor_widget.dart` that imports:
* `package:image_picker/image_picker.dart` that declares support for platforms: Android, iOS
</details>

### [~] 20/30 points: code has no errors, warnings, lints, or formatting issues

Found 3 issues. Showing the first 2:

<details>
<summary>
lib\html_editor.dart is not formatted according to dartfmt
</summary>

To format your files run: `dartfmt -w .`
</details>
<details>
<summary>
lib\html_editor_widget.dart is not formatted according to dartfmt
</summary>

To format your files run: `dartfmt -w .`
</details>

### [~] 10/10 points: All of the package dependencies are supported in the latest version

|Package|Constraint|Compatible|Latest|
|:-|:-|:-|:-|
|[`flutter`]|`flutter`|0.0.0|0.0.0|
|[`flutter_inappwebview`]|`^4.0.0+4`|4.0.0+4|4.0.0+4|
|[`image_picker`]|`^0.7.0-nullsafety`|0.7.0-nullsafety|0.7.0-nullsafety|
|[`mime`]|`^0.9.6+2`|0.9.7|**1.0.0**|
|[`path`]|`^1.8.0`|1.8.0|1.8.0|

<details><summary>Transitive dependencies</summary>

|Package|Constraint|Compatible|Latest|
|:-|:-|:-|:-|
|[`characters`]|-|1.1.0|1.1.0|
|[`charcode`]|-|1.2.0|1.2.0|
|[`collection`]|-|1.15.0|1.15.0|
|[`convert`]|-|2.1.1|3.0.0|
|[`crypto`]|-|2.1.5|3.0.0|
|[`flutter_plugin_android_lifecycle`]|-|2.0.0-nullsafety.2|2.0.0-nullsafety.2|
|[`http`]|-|0.13.0|0.13.0|
|[`http_parser`]|-|4.0.0|4.0.0|
|[`image_picker_platform_interface`]|-|2.0.0|2.0.0|
|[`meta`]|-|1.3.0|1.3.0|
|[`pedantic`]|-|1.10.0|1.10.0|
|[`plugin_platform_interface`]|-|2.0.0|2.0.0|
|[`sky_engine`]|-|0.0.99|0.0.99|
|[`source_span`]|-|1.8.1|1.8.1|
|[`string_scanner`]|-|1.1.0|1.1.0|
|[`term_glyph`]|-|1.2.0|1.2.0|
|[`typed_data`]|-|1.3.0|1.3.0|
|[`uuid`]|-|2.2.2|2.2.2|
|[`vector_math`]|-|2.1.0|2.1.0|
</details>

To reproduce run `pub outdated --no-dev-dependencies --up-to-date --no-dependency-overrides`.

[`flutter`]: https://pub.dev/packages/flutter
[`flutter_inappwebview`]: https://pub.dev/packages/flutter_inappwebview
[`image_picker`]: https://pub.dev/packages/image_picker
[`mime`]: https://pub.dev/packages/mime
[`path`]: https://pub.dev/packages/path
[`characters`]: https://pub.dev/packages/characters
[`charcode`]: https://pub.dev/packages/charcode
[`collection`]: https://pub.dev/packages/collection
[`convert`]: https://pub.dev/packages/convert
[`crypto`]: https://pub.dev/packages/crypto
[`flutter_plugin_android_lifecycle`]: https://pub.dev/packages/flutter_plugin_android_lifecycle
[`http`]: https://pub.dev/packages/http
[`http_parser`]: https://pub.dev/packages/http_parser
[`image_picker_platform_interface`]: https://pub.dev/packages/image_picker_platform_interface
[`meta`]: https://pub.dev/packages/meta
[`pedantic`]: https://pub.dev/packages/pedantic
[`plugin_platform_interface`]: https://pub.dev/packages/plugin_platform_interface
[`sky_engine`]: https://pub.dev/packages/sky_engine
[`source_span`]: https://pub.dev/packages/source_span
[`string_scanner`]: https://pub.dev/packages/string_scanner
[`term_glyph`]: https://pub.dev/packages/term_glyph
[`typed_data`]: https://pub.dev/packages/typed_data
[`uuid`]: https://pub.dev/packages/uuid
[`vector_math`]: https://pub.dev/packages/vector_math

<details>
<summary>
The constraint `^0.9.6+2` on mime does not support the stable version `1.0.0`, that was published 14 days ago.

 When mime is 30 days old, this package will no longer be awarded points in this category.
</summary>

Try running `dart pub upgrade --major-versions mime` to update the constraint.
</details>

### [*] 10/10 points: Package supports latest stable Dart and Flutter SDKs

Points: 80/100.
INFO       Running `C:\flutter\bin\cache\dart-sdk\bin\dart.exe --version`...
INFO       Running `flutter.bat --no-version-check --version --machine`...
WARNING    pana might update or modify files in `C:\Users\tanay\html_editor_enhanced`.
           Analysis will begin in 15 seconds, hit CTRL+C to abort it.
           To remove this message, use `--no-warning`.
INFO       Running `flutter.bat --no-version-check packages pub upgrade --verbosity io --no-precompile`...
INFO       Analyzing package...
INFO       Running `C:\flutter\bin\cache\dart-sdk\bin\dartanalyzer.bat --options C:\Users\tanay\html_editor_enhanced\pana_analysis_options_1613777559004543.g.yaml --format machine lib`...
INFO       Running `flutter.bat --no-version-check format --dry-run --set-exit-if-changed C:\Users\tanay\html_editor_enhanced\lib`...
INFO       Running `C:\flutter\bin\cache\dart-sdk\bin\pub.bat get`...

### [*] 10/10 points: Package has an example

* Found example at: `example/lib/main.dart`

### [~] 10/20 points: Supports 2 of 3 possible platforms (**iOS**, **Android**, Web)

Found 6 issues. Showing the first 2:

Consider supporting multiple platforms:

<details>
<summary>
Package does not support Flutter platform Web
</summary>

Because:
* `package:html_editor_enhanced/html_editor.dart` that imports:
* `package:html_editor_enhanced/html_editor_widget.dart` that imports:
* `package:image_picker/image_picker.dart` that declares support for platforms: Android, iOS
</details>

### [~] 20/30 points: code has no errors, warnings, lints, or formatting issues

Found 3 issues. Showing the first 2:

<details>
<summary>
lib\html_editor.dart is not formatted according to dartfmt
</summary>

To format your files run: `dartfmt -w .`
</details>
<details>
<summary>
lib\html_editor_widget.dart is not formatted according to dartfmt
</summary>

To format your files run: `dartfmt -w .`
</details>

### [x] 0/10 points: All of the package dependencies are supported in the latest version

* Could not run pub outdated: `pub get` failed:

 ```
Because html_editor_enhanced requires the Flutter SDK, version solving failed.

Flutter users should run `flutter pub get` instead of `pub get`.
```

### [*] 10/10 points: Package supports latest stable Dart and Flutter SDKs

Points: 70/100.

</details>

Is this happening because of something I'm doing or is it a bug with pub.dev?

**Comment by jhomlala** [comment]
Same issue on my libs. Pub dev score algorithm is being changed each week. Not all devs has time to be prepared for these changes. I believe right now the best way is to ignore this score until pub dev maintainers resolve issues.

**Comment by tneotia** [comment]
Actually I played around with it a bit, after manually going into the API docs page, I could see the error output from dartdoc and it was an incompatible dependency that was causing it! I was using nullsafety dependencies, as soon as I downgraded those and uploaded a new package, the score was calculated correctly (it gave me 80).

**Comment by sigurdm** [comment]
> Same issue on my libs.
@jhomlala what are your libs?

I think the main issue here is that the dartdoc error message is not included correctly in the report. @isoos do you agree?

**Comment by isoos** [comment]
We've updated and fixed multiple parts of the scoring and reporting on dartdoc timeouts, it has been rolled out, and fixes some of the issues reported here.

There is an ongoing investigation why some of the packages experience larger than usual dartdoc generation and time out on pub.dev. We have some leads, and expect to fix it next week.

**Comment by isoos** [comment]
The recent SDK upgrades fixed most of the issues that are within our reach (there is also another `dartdoc` upgrade in the works).

The largest pending one on the reported package seems to be the `ui.platformViewRegistry`, which can be tracked in https://github.com/flutter/flutter/issues/41563

I'm closing this as I don't see any immediate thing that pub.dev can do here. Please feel free to open new issues if you see discrepancies in the analysis or in the scores.

**Comment by tneotia** [comment]
@isoos is there a way to have pana ignore the `ui.platformViewRegistry` issue for now? It also affects my package, and thus I don't get the "Null Safety" banner and my package fails static analysis. 

I have the error ignored under my `analysis_options.yaml` but it seems the pub analysis tool doesn't ignore it.

**Comment by sigurdm** [comment]
Look into the suggested solutions on flutter/flutter#41563. You should be able to use a shim like suggested here: https://github.com/flutter/flutter/issues/41563#issuecomment-794384561.

We really prefer not letting users ignore errors for the analysis we do - hopefully there will be a solution on the Flutter side.
