### ISSUE TITLE
Lost points on up-to-date dependencies

### ISSUE THREAD

**Issue by singerdmx** [dart-lang/pub-dev#4539]
![image](https://user-images.githubusercontent.com/122956/108614349-9e2a2d00-73ae-11eb-89e5-12f6b2bb9775.png)

Our pub https://pub.dev/packages/flutter_quill is published based on `stable` channel and we cannot update those dependencies to the latest which are beta.

Do we need to specify `stable` channel somewhere during publishing?

**Comment by jhomlala** [comment]
Same issue on my libraries. I believe this issue is happening, because pub dev is being prepared for nullsafety/web stable release., but from my perspective it shouldn't happen. I hope this will be resolved soon.

**Comment by isoos** [comment]
This should be fixed via https://github.com/dart-lang/pana/pull/830
We've already merged the fix in pub-dev's code, but it will be applied only with our next deployment this week or next week.

**Comment by isoos** [comment]
This issue has been fixed in the latest release of pub.dev. (There is also an upcoming pana version that fixes the color of the report section. Note: up-to-date dependencies are still important, but there is a 30-days window before it affects the score.)
