### ISSUE TITLE
avoid use of --no-link-to-remote

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/pub-dev#4543]
It would appear --no-link-to-remote is now used for all runs of dartdoc on pub.dev, apparently in an attempt to reduce the time that dartdoc takes to run.  In addition to making the generated documentation less useful, dartdoc will run slightly slower with this flag.  This is because dartdoc will generate duplicate documentation for parts of the documented package that would otherwise be referred to.

**Comment by isoos** [comment]
Good to know, I'll remove that.
