### ISSUE TITLE
Results from api.flutter.dev, like how we surface api.dart.dev

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4549]
Could we surface results from api.flutter.dev like how we have api.dart.dev.

I imagine libraries like:
* `package:flutter/animation.dart`
* `package:flutter/cupertino.dart`
* `package:flutter/foundation.dart`
* `package:flutter/gestures.dart`
* `package:flutter/material.dart`
* `package:flutter/painting.dart`
* `package:flutter/physics.dart`
* `package:flutter/rendering.dart`
* `package:flutter/scheduler.dart`
* `package:flutter/semantics.dart`
* `package:flutter/services.dart`
* `package:flutter/widgets.dart`

Not all the libraries on `api.flutter.dev` because some of them are just packages from `pub.dev` that have been pinned.

At the very least we should investigate:
 1. How feasible is this technically?
 2. How desirable is it? Will it produce too much noise?

**Comment by isoos** [comment]
> How feasible is this technically?

Flutter's API docs generator code is here:
https://github.com/flutter/flutter/blob/master/dev/tools/dartdoc.dart

While our current `pub_dartdoc` is really close to `package:dartdoc`, adopting the above would be a measurable work. An option to consider: let's incorporate the data-extraction we have into `package:dartdoc`, and Flutter (and us) will get it automatically.

Another option is to use the JS search's `index.json` file and extract the symbols from there: https://api.flutter.dev/flutter/index.json

Note: api.flutter.dev has only a single version of documentation. This simplifies linking but also limits the above option to the single version that is being hosted.

> How desirable is it?

I think this is useful if done right.

> Will it produce too much noise?

It seems to me that the current search produces too little useful SDK results. Mixing these results inside the normal package list seems to be lacking.

However, if we moved both the Dart and the Flutter SDK results to their own block (e.g. top 3 SDK results on the first search result page), it could be really useful.

**Comment by jonasfj** [comment]
TODO:
 * Consider if we need to index more than symbols at all? (check if we already do that)
 * Consider if maybe `Dart SDK` and `Flutter SDK` are just two packages, instead of each library being a possible result.
