### ISSUE TITLE
Deploy without self-dependency

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4550]
We currently deploy `pub.dev` using `dart pub get`, this might be undesirable in case we ever have to deploy while the service is down.

We could probably write a dart script in something like `tool/resolve-deps.dart` that:
 * Reads `app/pubspec.lock` to find package names and versions,
 * Download packages directly from Google Cloud Storage
    (`https://storage.googleapis.com/pub-packages/packages/<package>-<version>.tar.gz`)
 * Extracts tarballs into `.dart_tool/pub-dev-cache/` with same directory format as `PUB_CACHE`.
 * Calls `dart pub get --offline` with `PUB_CACHE=.dart_tool/pub-dev-cache/`

This might be so simple that we can do with simple bash scripting.

Then we can use this script in our dockerfiles, and avoid self-dependency during deployment.

**Comment by ramyak-mehra** [comment]
@jonasfj would something like work for getting all the packages and then fetching and extracting them later.
```dart 
var packages = <PackageInfo>[];
  var file =
      io.File('pubspec.lock');
  var yaml = file.readAsStringSync();
 var  map = loadYaml(yaml) as Map; 
    var decodedJMap = json.decode(json.encode(map)) as Map<String, dynamic>;
    var map1 = decodedJMap['packages'] as Map<dynamic, dynamic>;
    map1.forEach((key, value) {
      var package = PackageInfo(key, value['version']);
      packages.add(package);
    });

  print(packages.length);
```

also, would all the packages be going into .dart_tool/pub-dev-cache/bin since I guess packages from git are not supported now.

**Comment by ramyak-mehra** [comment]
@jonasfj I wrote this [script](https://gist.github.com/ramyak-mehra/fceb5529ffeb7a155b7be0f58e439dbd)  , but I am having trouble with tar.gz file I know how to extract its contents but I am having trouble where and what directory format.
In my machine all the  packages go to .pub-cache/hosted/pub.dartlang.org

**Comment by ramyak-mehra** [comment]
> @jonasfj I wrote this [script](https://gist.github.com/ramyak-mehra/fceb5529ffeb7a155b7be0f58e439dbd)  , but I am having trouble with tar.gz file I know how to extract its contents but I am having trouble where and what directory format.
> In my machine all the  packages go to .pub-cache/hosted/pub.dartlang.org. is this the right format and path here also.

@isoos can you take a look at this in your free time?

**Comment by isoos** [comment]
@ramyak-mehra thanks for script so far, it is a good start. If you don't mind, I'd take over, as I think it needs changes in a few aspects (e.g. removing any `package:<xyz>` dependency, also handle the other packages inside `pkg/` directories), and also ties into the deployment build process which I have familiarity with.
