### ISSUE TITLE
Failing Checks after publishing

### ISSUE THREAD

**Issue by tusharojha** [dart-lang/pub-dev#4557]
* I published the null safe version on pub dev today but it's showing 30/110 points. I am confused why it's so. 
 * Link to package: https://pub.dev/packages/web_scraper/versions/0.1.4

**Comment by isoos** [comment]
Your SDK constraint is larger than the one being used at pub.dev at the moment. We are planning to update it soon, and your score should get higher automatically.

**Comment by tusharojha** [comment]
Also, For the latest stable version of my package i.e. 0.0.9 it's showing me to use up-to-date dependencies but I am already using the most compatible dependencies. Check the following screenshot:

<img width="578" alt="Capture" src="https://user-images.githubusercontent.com/36601970/109033843-0d748980-76ed-11eb-9518-c8a38453b719.PNG">

**Comment by isoos** [comment]
This issue has been fixed in the latest release of pub.dev. (There is also an upcoming pana version that fixes the color of the report section.)
