### ISSUE TITLE
Feature package of the week on pub.dev landing page

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4561]
@afitz0 and @redbrogdon have a [package of the week youtube channel][1], with short videos introducing a package.

When we did the redesign we envisioned a concept of "featured" packages on the landing page, similar to how we have "Flutter Favorites" on the landing page. Let's use this youtube channel the same way :rocket:

**Proposal:**
 * Feature 2-4 videos at the bottom of the page (depending on page width).
 * Pick the latest video from the "Package of the week" channel, and 3 other videos at random.
 * Use the same "grey" design as we use for the "Flutter Favorites" bar at the top.
 * Instead of a "VIEW ALL" links we have a "VIEW PLAYLIST" link that goes to youtube
    * Possibly prefixed with a small youtube icon (not sure)
 * Instead of cards we use:
     * Use a youtube preview image: `https://img.youtube.com/vi/HHzAJdlEj1c/0.jpg`
     * Overlay with a "play" icon so it looks similar to an embedded youtube player.
     * Handle click on the video, such that we open the video center screen (`position: fixed`)
        with a semi transparent black background, where clicking the background closes the video.
     * Or maybe we just open youtube in a new tab, that might work better on phones, etc.
  * We could also, instead of cards, use an embedded youtube player, however:
      * This might have increased load time (not sure),
      * Also playing videos in a size 290x190 does work well, so we would need to change size of the player, do the black background thing and center the play on screen regardless.
 * Google analytics events reporting when a video is clicked.

I'm open to ideas about how we embed the videos. It might simply be something we have to play with.

**Mockups**:
 * [bottom of landing page](https://user-images.githubusercontent.com/149732/109142487-359cd080-775f-11eb-9649-a813ed2b18d5.png)
* [bottom of landing page zoomed out](https://user-images.githubusercontent.com/149732/109142472-32094980-775f-11eb-9d4c-bd007d3c748a.png)
* [image vs embed](https://user-images.githubusercontent.com/149732/109142495-37ff2a80-775f-11eb-9c37-c3dd0ae75097.png)

[1]: https://www.youtube.com/playlist?list=PLjxrf2q8roU1quF6ny8oFHJ2gBdrYN_AK

**Comment by jonasfj** [comment]
There is a few options for getting the list of https://stackoverflow.com/questions/2068344/how-do-i-get-a-youtube-video-thumbnail-from-the-youtube-api

We probably also have to get an API key, or somehow configure our service account correctly to fetch list of videos:
https://developers.google.com/youtube/v3

**Comment by jonasfj** [comment]
Uh, maybe we should use the following design:

* [Design for featured packages](https://user-images.githubusercontent.com/149732/109484759-1c5a9380-7a81-11eb-947f-4d0fbfdeb732.png)

**Comment by gfb-47** [comment]
Couldn't this could become a package? Once it's going be a good integration between Dart - Youtube.

**Comment by jonasfj** [comment]
@gfb-47 `package:googleapis` has auto-generated wrappers for [YouTube Data API v3](https://pub.dev/documentation/googleapis/latest/youtube.v3/youtube.v3-library.html).

The documentation isn't great because it's just automatically generated, but I don't think it's hard to get it working. If you just want to list videos on a playlist or something like that.

**Comment by jonasfj** [comment]
For best mobile experience, let's just make thumbnails with play-button overlay and link to youtube with `target=_blank` (new tab)
