### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by nirala96** [dart-lang/pub-dev#4569]
URL: https://pub.dev/packages/flutter_bluetooth_serial

In the plugin feature the last point "Sending and recieving data ", should be "Sending and receiving data" after fixing typo in the word "receiving"

**Comment by parlough** [comment]
This would probably be better submitted as an issue or a pull request to that package's repository. Pub just hosts the contents that packages provide. You can find the package in question's repository by clicking the `Repository (GitHub)` button at the right of pub which will bring you to [their published Github repository](https://github.com/edufolly/flutter_bluetooth_serial).

**Comment by nirala96** [comment]
ok
