### ISSUE TITLE
Development doc is Ambiguous

### ISSUE THREAD

**Issue by Sameerkash** [dart-lang/pub-dev#4577]
The `development.md` doc is very ambiguous for setting up things.

Here are some questions and suggestions I have, 

**1** : 
To initialize it with some minimal data, create the following file:
```
defaultUser: 'your-email@example.com'
packages:
  - name: retry
  - name: http
 ```
- The above file is ambiguous on where to create the file, although it can be figured out as I created in the /app directory, 
I feel specifying it would be helpful. 
- I would also like to suggest we add this and dev-data-file.jsonl  to `.gitignore`  which would help while pushing with no unstaged files. 
- Also, some packages failed to upload while running the `fake_server.dart`

<details>
  <summary>log</summary>

```

_ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      runProc (package:pana/src/utils.dart:41:31)
#3      DartdocJobProcessor._initializeIfNeeded (package:pub_dev/dartdoc/dartdoc_runner.dart:57:11)
#4      DartdocJobProcessor._generateDocs.runDartdoc (package:pub_dev/dartdoc/dartdoc_runner.dart:373:13)
#5      DartdocJobProcessor._generateDocs.runDartdoc (package:pub_dev/dartdoc/dartdoc_runner.dart:372:37)
#6      DartdocJobProcessor._generateDocs (package:pub_dev/dartdoc/dartdoc_runner.dart:414:31)
<asynchronous suspension>
#7      DartdocJobProcessor.process.<anonymous closure> (package:pub_dev/dartdoc/dartdoc_runner.dart:210:29)
<asynchronous suspension>
#8      withToolEnv.<anonymous closure> (package:pub_dev/shared/tool_env.dart:58:14)
<asynchronous suspension>
#9      Pool.withResource (package:pool/pool.dart:127:14)
<asynchronous suspension>
#10     withToolEnv (package:pub_dev/shared/tool_env.dart:50:10)
<asynchronous suspension>
#11     DartdocJobProcessor.process (package:pub_dev/dartdoc/dartdoc_runner.dart:179:7)
<asynchronous suspension>
#12     JobProcessor._runOneJob (package:pub_dev/job/job.dart:73:20)
<asynchronous suspension>
#13     JobMaintenance.scanUpdateAndRunOnce (package:pub_dev/job/job.dart:136:22)
<asynchronous suspension>
#14     _analyze.<anonymous closure> (package:pub_dev/fake/tool/init_data_file.dart:98:5)
<asynchronous suspension>
#15     _analyze (package:pub_dev/fake/tool/init_data_file.dart:94:3)
<asynchronous suspension>
#16     FakeInitDataFileCommand.run.<anonymous closure> (package:pub_dev/fake/tool/init_data_file.dart:77:13)
<asynchronous suspension>
#17     _withPubServices.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:pub_dev/service/services.dart:203:28)
<asynchronous suspension>
#18     _withPubServices.<anonymous closure> (package:pub_dev/service/services.dart:201:12)
<asynchronous suspension>
#19     withFakeServices.<anonymous closure> (package:pub_dev/service/services.dart:137:12)
<asynchronous suspension>
#20     withFakeServices (package:pub_dev/service/services.dart:117:10)
<asynchronous suspension>
#21     FakeInitDataFileCommand.run (package:pub_dev/fake/tool/init_data_file.dart:66:5)
<asynchronous suspension>
#22     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#23     main (file:///Volumes/FAST/Projects/pub-dev/app/bin/fake_server.dart:14:3)
<asynchronous suspension>

2021-03-03T14:14:18.015980 [INFO] pub.scorecard.backend: Creating new report: meta 1.3.0 dartdoc.
```
</details>

**2**

The GCLOUD_KEY must be an exported service account key for the cloud project. This can be created in console.cloud.google.com under IAM and Admin > Service Accounts > Create Service Account (export in JSON format).

- It would also be helpful to specify which project to select a service account is associated with a project, or if the user should create a new one if they don't have one in their google cloud. 
- Although I followed all the steps, I wasn't able to setup the server successfully, ended with this error 
```
Unhandled exception:
SocketException: Failed host lookup: 'metadata' (OS Error: nodename nor servname provided, or not known, errno = 8)
```
I can confirm I have a working internet connection 

It'd be great if this could be documented as well, I am ready to make a PR If this sounds good.

**Comment by isoos** [comment]
@Sameerkash thanks for the feedback and helping to improve the docs!

> The above file is ambiguous on where to create the file, although it can be figured out as I created in the /app directory, I feel specifying it would be helpful.

The reason we have no single file specified for that is that we might use multiple files with different settings. Maybe it can be standardized in a `dev-data` directory which can put into `.gitignore`...

> Also, some packages failed to upload while running the fake_server.dart

This seems to me a failure in this code:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/frontend/static_files.dart#L67-L71

What OS are you using? What was the current working directory? IIRC the code assumes that it is being run from `app/`.

> The GCLOUD_KEY must be an exported service account key for the cloud project.

I think this code should be really in a separate file. We no longer need direct gcloud dependency for local development, and this would be more useful if somebody wants to run it as a gcloud project.

**Comment by Sameerkash** [comment]
> The reason we have no single file specified for that is that we might use multiple files with different settings. Maybe it can be standardized in a `dev-data` directory which can put into `.gitignore`...

Yeah, this would be helpful.

> This seems to me a failure in this code:
> https://github.com/dart-lang/pub-dev/blob/master/app/lib/frontend/static_files.dart#L67-L71

How can I fix this? 
 
> What OS are you using? What was the current working directory? IIRC the code assumes that it is being run from `app/`.

Currently, I'm on macOS BigSur 11.0.1, and yes it is running from /app as the command does cd into app.

> I think this code should be really in a separate file. We no longer need direct gcloud dependency for local development, and this would be more useful if somebody wants to run it as a gcloud project.

Okay, I can fix that up.

@isoos

**Comment by isoos** [comment]
>> What OS are you using? What was the current working directory? IIRC the code assumes that it is being run from app/.

> Currently, I'm on macOS BigSur 11.0.1, and yes it is running from /app as the command does cd into app.

Another thing that can happen here is how your `PATH` is set up. Do you have only Flutter SDK, or do you have a separate Dart SDK in the path? (I do have the later, prod and CI also works on a standalone Dart SDK.)

**Comment by Sameerkash** [comment]
> > > What OS are you using? What was the current working directory? IIRC the code assumes that it is being run from app/.
> 
> > Currently, I'm on macOS BigSur 11.0.1, and yes it is running from /app as the command does cd into app.
> 
> Another thing that can happen here is how your `PATH` is set up. Do you have only Flutter SDK, or do you have a separate Dart SDK in the path? (I do have the later, prod and CI also works on a standalone Dart SDK.)

I have the flutter sdk running on master.

**Comment by Sameerkash** [comment]
> > The GCLOUD_KEY must be an exported service account key for the cloud project.
> 
> I think this code should be really in a separate file. We no longer need direct gcloud dependency for local development, and this would be more useful if somebody wants to run it as a gcloud project.

Getting this incase GCLOUD is not set 

```
Unhandled exception:
Bad state: Expected environment variable GCLOUD_PROJECT to be set!
```

**Comment by isoos** [comment]
> Getting this incase GCLOUD is not set
> Bad state: Expected environment variable GCLOUD_PROJECT to be set!

Could you please include the full stack trace here?

**Comment by Sameerkash** [comment]
Here is the full stack trace on running dart bin/server.dart default 
@isoos 

```
sameerkashyap@Sameers-MacBook-Pro app % dart bin/server.dart default
Unhandled exception:
Bad state: Expected environment variable GCLOUD_PROJECT to be set!
#0      _initializeAppEngine._findEnvironmentVariable (package:appengine/src/appengine_internal.dart:141:7)
#1      _initializeAppEngine (package:appengine/src/appengine_internal.dart:146:45)
<asynchronous suspension>
#2      _withAppEngineServicesInternal.<anonymous closure> (package:appengine/src/appengine_internal.dart:103:45)
<asynchronous suspension>
#3      startIsolates (package:pub_dev/service/entrypoint/_isolate.dart:64:3)
<asynchronous suspension>
#4      DefaultCommand.run (package:pub_dev/service/entrypoint/frontend.dart:52:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#6      main (file:///Volumes/FAST/Projects/pub-dev/app/bin/server.dart:18:3)
<asynchronous suspension>
```

**Comment by isoos** [comment]
@Sameerkash this is the key:
> dart bin/server.dart default

The documentation should be clear that we don't recommend to run `bin/server` for local development. The Google AppEngine setup is long, especially as we migrate to service accounts. Rather, it should only mention `dart bin/fake_server run`...

**Comment by Sameerkash** [comment]
@isoos I understand how the setup works no, but I'm still having some problems. 


```
dart bin/fake_server.dart run --data-file=dev-data-file.jsonl
2021-03-04T21:01:33.408821 [INFO] pub.static_files: pkg/web_app build status: source: 2021-03-03 14:15:47.000, target: null
2021-03-04T21:01:33.417567 [INFO] pana: Running `pub get`...
Unhandled exception:
ProcessException: No such file or directory
  Command: pub get
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      runProc (package:pana/src/utils.dart:41:31)
#3      _runPubGet (package:pub_dev/frontend/static_files.dart:257:20)
#4      updateWebAppBuild (package:pub_dev/frontend/static_files.dart:307:9)
#5      updateLocalBuiltFilesIfNeeded (package:pub_dev/frontend/static_files.dart:287:11)
<asynchronous suspension>
#6      FakeServerCommand.run (package:pub_dev/fake/server/fake_server_entrypoint.dart:121:5)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#8      main (file:///Volumes/FAST/Projects/pub-dev/app/bin/fake_server.dart:14:3)
<asynchronous suspension>
```

**Comment by isoos** [comment]
Do you have `pub` in your `PATH`? I think that is the missing piece there.

**Comment by Sameerkash** [comment]
> Do you have `pub` in your `PATH`? I think that is the missing piece there.
just pub? is this not using the latest dart cli? is it calling just pub get?

**Comment by isoos** [comment]
The failing code in question does two things:
- it determines the absolute path of the `pkg/web_app` directory
- it runs `pub get` in that directory
- it runs the `build.sh` in that directory

https://github.com/dart-lang/pub-dev/blob/master/app/lib/frontend/static_files.dart#L305-L312

It is possible that the first step fails, but more likely that the second step fails when `pub` is not in the `PATH`.

**Comment by Sameerkash** [comment]
@isoos  Yes, I had removed it from my path since it was recommended to use `dart pub run`. 

Wouldn't it be better if the server used the latest CLI tools too? 

And although the site built successfully, I'm getting an empty pub.dev site. Shouldn't it be filled with the data in jsonl? 

I'll go ahead and make a PR if you think some suggestions I made are valid.

**Comment by isoos** [comment]
> Wouldn't it be better if the server used the latest CLI tools too?

I think that is reasonable now that we've upgraded to 2.12.

> And although the site built successfully, I'm getting an empty pub.dev site. Shouldn't it be filled with the data in jsonl?

The search index and with that the landing page may be empty if you haven't analyzed the packages during the init-data-file phase (or if the analysis happened on a runtime-version that is old and no longer accepted). Unfortunately a periodic re-generation of the file is required.

> I'll go ahead and make a PR if you think some suggestions I made are valid.

I think you've made a lot of valid point, I'd be happy to review them, please go ahead!

**Comment by Sameerkash** [comment]
Regenerated the file but still an empty site, I'll try to see what can be the issue.

For the PR, I propose these changes, 
- Specify the location to create the file.
- standardize the filename and add it to .gitignore
- add `dev-data-file.jsonl` to .gitignore 
- Move Gcloud deployment to another file(or add it with more precise instructions) 
- mention running `fake-server.dart` instead of `server.dart`

separate PR
-  migrate fake_server to use latest dart cli tools while running pub get.

cc @isoos

**Comment by isoos** [comment]
@Sameerkash I like the proposed change, with the following add-ons: 
- I think the location of the profile and data file should be in a directory e.g. `app/dev-data`. (the gitignore could ignore the directory).
- The gcloud deployment should live in a separate file, and use of `server.dart` should be mentioned only there

**Comment by Sameerkash** [comment]
@isoos , so I was trying to work on this, how would you like the init file to be created, shall I change only the command to include the path to the `dev-data-file.jsonl` or enforce it within the code while creation of the file? 

One doubt I have is, I'm unable to create it either way, I'm getting a read only OS error=2, any tips on how I can solve this?

**Comment by sigurdm** [comment]
Fixed in https://github.com/dart-lang/pub-dev/pull/4599
