### ISSUE TITLE
Updated package with 2.12.0 stable has issues with analyzer

### ISSUE THREAD

**Issue by vegaro** [dart-lang/pub-dev#4582]
* We published a new version with minimum Dart SDK 2.12.0 (https://pub.dev/packages/purchases_flutter/)
 * It looks like the analyzer ran on 2.12.0-259.16.beta
 * The pub score went down to 50. The labels say [Unidentified]
 * ![Screen Shot 2021-03-03 at 7 30 09 PM](https://user-images.githubusercontent.com/664544/109907293-e0792700-7c56-11eb-87c9-d427bf8202a4.png)

**Comment by vegaro** [comment]
Just saw https://github.com/dart-lang/pub-dev/issues/4537 . I think it's related so I am closing it. Sorry about the noise

**Comment by nohli** [comment]
https://pub.dev/documentation/purchases_flutter/latest/log.txt

It says `The current Dart SDK version is 2.12.0-259.16.beta`, so pub.dev uses the last beta and not 2.0.0.

Perhaps, if you change sdk constraints to >2.12.0-0 (including the above version), it will work.
Otherwise, the score should automatically get updated once pub.dev uses 2.0.0 (had a similar issue).

**Comment by isoos** [comment]
@vegaro @nohli: pub.dev uses multiple deployed runtimes (as we want to keep the capability to roll back from a release), and right now both `2.12.0-259.16.beta` and `2.12.0` deployed. The actively displayed deployment will display the results from `2.12.0` when it becomes analyzed, or `2.12.0-259.16.beta` if it is the only available one. The processing will eventually analyse the packages and also to generate dartdoc with the new SDKs. With the new Flutter release we see an increase in deployed packages and the analysis backlog is a bit longer than usual, but feel free to reopen issues if you think something is way off or unexpected.

**Comment by vegaro** [comment]
Thanks so much. We will just wait then! We thought about making that extra release using the beta version matching the current analyzer results, but if we can wait, we'll wait.

**Comment by isoos** [comment]
> We thought about making that extra release using the beta version matching the current analyzer results, but if we can wait, we'll wait.

Please, please, please: report issues as you encounter them, we'll do out best to get them fixed without the need of extra versions :)
