### ISSUE TITLE
permission issue - file: popularity.json.gz

### ISSUE THREAD

**Issue by n0npax** [dart-lang/pub-dev#4587]
Local development using app engine relays on this [docs](https://github.com/dart-lang/pub-dev/blob/master/doc/development.md#local-development-with-google-appengine).

Unfortunately one of the files used to populate DB is not public.

Please refer to the log:
```
dart bin/server.dart default
...
...
2021-03-07 19:32:11.097256 Info: pub.popularity: Loading popularity data (init): gs://dartlang-pub-dev-popularity/v3/popularity.json.gz
Error .......
```

```dart
gsutil ls gs://dartlang-pub--popularity/
AccessDeniedException: 403 blah.blah@gmail.com does not have storage.objects.list access to the Google Cloud Storage bucket.
```
☝🏻  same for `get` on file

**Proposed solution:**
Please make this file public

**Comment by isoos** [comment]
Since the fake server has now popularity values, and the lack of access to the bucket file does not block the real server running locally, I'm closing this issue.
