### ISSUE TITLE
Sign in button not working

### ISSUE THREAD

**Issue by mukundoesflutter** [dart-lang/pub-dev#4598]
URL: https://pub.dev/

The sign in button is not working even after clearing cache. It is getting selected onClick but nothing happens.

**Comment by nirala96** [comment]
It is working in my system. Maybe there is a network issue.

**Comment by isoos** [comment]
@mukundoesflutter: what OS, browser and version are you using? Any content blockers or plugins?

**Comment by mukundoesflutter** [comment]
@isoos Windows 10, Google Chrome Version 89.0.4389.82 (Official Build) (64-bit). No blockers or plugins that I know of.
@nirala96 There is no network issue.

**Comment by isoos** [comment]
>  It is getting selected onClick but nothing happens.

Not sure I follow, could you be more specific?
- You click on the `Sign in` button.
- There should be a window popup of the Google login. (maybe that is blocked?)
- ...

**Comment by mukundoesflutter** [comment]
After clicking the `Sign in` button, nothing happens... No popup.
I even enabled _Pop-ups and redirects_ in the Google chrome settings for the site.
No additional pop-up blockers installed.

**Comment by isoos** [comment]
@mukundoesflutter: Could you please check the developer tools in the browser, specifically the network tab during loading the page, and the console. I'd be interested if there is any asset that doesn't get loaded, or any warning or error message that gets printed.

**Comment by mukundoesflutter** [comment]
@isoos Console is empty. No blocked requests or cookies during reload on Network tab.

Have attached a short video for your reference...


https://user-images.githubusercontent.com/67651118/111036444-34e58900-8445-11eb-96fe-8379d5e82d9f.mp4

**Comment by isoos** [comment]
@mukundoesflutter: Do you happen to block all third-party cookies? We try to detect it and emit a warning if that happens, but maybe we are not able to detect all the cases.

**Comment by mukundoesflutter** [comment]
@isoos third-party cookies are enabled except in incognito mode. Preload pages in enabled. The attached images shows the list of cookies for pub.dev: 
<img width="516" alt="pub dev cookie list" src="https://user-images.githubusercontent.com/67651118/111075828-ca4d4f80-850f-11eb-9511-39b1a1686f11.PNG">

**Comment by StarTrooper08** [comment]
@mukundoesflutter try sign in with different browser it may help.

**Comment by mukundoesflutter** [comment]
@StarTrooper08 It does not work even on Edge..

**Comment by mukundoesflutter** [comment]
@isoos Finally found the solution: Kaspersky Internet Security was blocking the pop up even without an extension in the browser.
I turned it off and was able to login. Thanks for your help and support everyone.
