### ISSUE TITLE
Creating a Flutter app for pub.dev

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [dart-lang/pub-dev#4604]
I would like to make an app for pub.dev using Flutter, except that I can't seem to find any API or way of requesting data.

So can you note anyways that this would be possible?

This is a question for knowing if there is an api or not.

Not a feature request, I will be doing it on my own as a community project.

**Comment by Sameerkash** [comment]
You can request for a specific package using this host and path, 

```
https://pub.dev/api/package/<pacakgename>/version/<version name>
```

Although the `/version` path is deprecated, but, it still works. 

But I'm unsure if you'll be able to fetch multiple packages at once as you might be rate-limited.  

[this](https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md) spec might give you some idea

**Comment by YazeedAlKhalaf** [comment]
I need the following functionality:

- searching
- getting package info, the info you get when going into a package

**Comment by YazeedAlKhalaf** [comment]
> You can request for a specific package using this host and path,
> 
> ```
> https://pub.dev/api/package/<pacakgename>/version/<version name>
> ```
> 
> Although the `/version` path is deprecated, but, it still works.
> 
> But I'm unsure if you'll be able to fetch multiple packages at once as you might be rate-limited.
> 
> [this](https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md) spec might give you some idea

Thanks will look into it 🚀

**Comment by sigurdm** [comment]
> searching

Follow https://github.com/dart-lang/pub-dev/issues/4194 for discussions of the pub.dev api being made public.
I'm not sure we are going to commit to eg. search in the short term.

> Could be run anywhere 🚀.

The current pub.dev site has a "mobile" view depending on the screen size. It should run everywhere with a browser.
What advantage would the Flutter app have?

**Comment by sigurdm** [comment]
> Native experience, I am thinking of adding the ability to run an example inside the app. So say package x has an example., it can be run inside the Flutter app. Do you have any idea how this can be done? running some new dynamic code inside a flutter as another app.

This is per default not possible without including the entire flutter-sdk (plus dependencies) in your app. And as the flutter sdk doesn't run on mobile, the app would not run on mobile...

**Comment by sigurdm** [comment]
I don't think the pub team is gonna take on this anytime soon.

Also we are somewhat reluctant to expose things like a search api making it hard for the community to make anything much better than a thin shell around the pub.dev website.

Closing for now.
