### ISSUE TITLE
Add a way to see version of dependency

### ISSUE THREAD

**Issue by ranjithrd** [dart-lang/pub-dev#4608]
- Most packages depend on other packages
- They often depend on specific versions of other packages
- There is no way to see this without either seeing the package documentation, which if exists does not (usually) give information about such stuff, or opening the GitHub repo.
- A more convenient way would be to be able to view this in the package page on pub.dev.
- Please refer to the redesigned screenshot.
![pub dev-old](https://user-images.githubusercontent.com/32879598/111022257-ad255d80-83f7-11eb-80d6-499fe14bb5a1.png)
![pub dev-new](https://user-images.githubusercontent.com/32879598/111022258-af87b780-83f7-11eb-94f9-e577d06662e9.png)

**Comment by isoos** [comment]
@ranjithrd which version would you be interested in?
- the constraint in the `pubspec.yaml`
- the latest stable of the dependency (regardless if the constraint or other resolution allows it)
- the latest resolvable version

**Comment by ranjithrd** [comment]
Ideally the constraints in the pubspec.yaml, so when there is a version solver conflict it is easier to see where the problem originates without having to go to GitHub.

**Comment by mzdm** [comment]
if you have conflict you can also use `flutter pub deps` to view the dependency tree

**Comment by ranjithrd** [comment]
Looks like a PR has been opened!.Looking forward for its approval.

**Comment by ranjithrd** [comment]
Closed by PR #4635
