### ISSUE TITLE
notification package (NotificationEvent) Not working

### ISSUE THREAD

**Issue by RisabhKedai** [dart-lang/pub-dev#4609]
URL: https://pub.dev/packages/notifications
I want to use the above package for making an app to read out the notification my phone receives. Similar to the example code in the action of notifications package I wrote my code, it didn't show any notification. I then tried to run the example code itself. Even that didn't work. I used WhatsApp to send a message to my phone which would create a notification. 
I have checked all the permissions and all, everything seems to be in place
 But nothing is working out. Please help.

**Comment by isoos** [comment]
@RisabhKedai This repository is for `pub.dev`, not their individual packages. Please use the package's repository (can be found on the side of the package page) to file bugs or feature requests. In this case it would be https://github.com/cph-cachet/flutter-plugins
