### ISSUE TITLE
dartdoc generation failing for null safe projects.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/pub-dev#4612]
It looks like pub.dev is being affected by https://github.com/dart-lang/dartdoc/issues/2531

You can see the problem on my dcli project:

https://pub.dev/packages/dcli/score

Unhandled exception:
NoSuchMethodError: The getter 'nullabilitySuffix' was called on null.
Receiver: null
Tried calling: nullabilitySuffix
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SubtypeHelper.isSubtypeOf (package:analyzer/src/dart/element/subtype.dart:51:29)
#2      TypeSystemImpl.isSubtypeOf2 (package:analyzer/src/dart/element/type_system.dart:1125:27)
#3      TypeSystemImpl.isSubtypeOf (package:analyzer/src/dart/element/type_system.dart:1121:12)
#4      TypeSystemImpl._refineNumericInvocationContextNullSafe (package:analyzer/src/dart/element/type_system.dart:1644:11)
#5      TypeSystemImpl.refineNumericInvocationContext (package:analyzer/src/dart/element/type_system.dart:1333:14)
#6      ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:826:24)
#7      ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:354:49)
#8      InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:316:18)
#9      InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:356:7)
#10     InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:334:7)
#11     InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:239:5)
#12     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:802:24)
#13     MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:505:16)
#14     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:93:7)
#15     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:394:31)
#16     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7137:49)
#17     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1650:10)
#18     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7137:49)
#19     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3655:18)
#20     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1694:10)
#21     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3229:59)
#22     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3651:49)
#23     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:2914:14)
#24     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/reso

**Comment by parlough** [comment]
The fix for this issue is unfortunately not part of dartdoc until the next release(0.40) which is not yet included until Dart 2.13(https://github.com/dart-lang/sdk/commit/40b469cc30c96a9883e4848b1c98a5144d09161c).

**Comment by bsutton** [comment]
So pub.dev is going to remain broken until then?

This seems rather problematic.

Surely this warrants a priority fix?

**Comment by parlough** [comment]
I agree with you, it would be nice to fix. 

Pub could utilize a custom version of dartdoc for the analysis rather than the built in one. I'm not too familiar with pub but I could look into this when I get a chance.

The dartdoc update could also be cherry picked back to the next stable release of the SDK but I'm not sure how that process works and I'm assuming it's quite unlikely.

**Comment by isoos** [comment]
@parlough: We already use a custom build and do not rely on the SDK-provided dartdoc. See `pkg/pub_dartdoc`.

@bsutton: We have already upgraded to `dartdoc 0.40.0`, and planning to do a pub site release in the next few days. If it is fixed in 0.40, it will clear automatically on pub.dev.

**Comment by parlough** [comment]
Well that works perfectly, thanks for the update!

**Comment by bsutton** [comment]
@isoos @parlough  thanks for that. Appreciate the attention applied to this issue.

**Comment by isoos** [comment]
The issue has been fixed with the latest pub-dev release.
