### ISSUE TITLE
[Feature] Add Label to indicate package dependency on Google Play Services

### ISSUE THREAD

**Issue by ashamnx** [dart-lang/pub-dev#4614]
* Apps targeting to phones that doesn't have google play services available causes issue at runtime.
 * It might be a good idea to identify the dependency before installing the package maybe via a label in package page. 

 There is already a "Dependencies" section on the page. However it only lists the dependency on other pub packages.
 
![photo_2021-03-15 12 27 54](https://user-images.githubusercontent.com/3396812/111117864-e988c300-8589-11eb-951c-35070b42ed3b.jpeg)

**Comment by jonasfj** [comment]
I filed https://github.com/dart-lang/pub-dev/issues/4615 for exploring options to detect and display non-pub dependencies.
