### ISSUE TITLE
Add "Filter by supported OS"

### ISSUE THREAD

**Issue by jayoung-lee** [dart-lang/pub-dev#4636]
In the recent HaTS survey, at least 4 users requested a filter on the search result page that allows users to choose operating systems they're interested in (Android, iOS, web, ...). 

Relevant: https://github.com/dart-lang/pub-dev/issues/4373

**Comment by jonasfj** [comment]
This is already supported. Users simply have to click "Flutter" which then filters to only flutter packages, and displays platform filters.

But we might need to review usage data, to see if users are discovering this. Perhaps it would simply be better to put all these filter options into the advanced menu -- and to always display platform filters and runtime filters.

Today, we only display:
 * "platform filters" when scoped to "Flutter" packages.
 * "runtime filters" when scoped to "Dart" packages.
 * No filters when scope to "Any".

![BaZ9j8Fuei9Q5e4](https://user-images.githubusercontent.com/149732/111768904-d4bd6f80-88a8-11eb-8222-458ad7bf029f.png)

**Comment by jayoung-lee** [comment]
It's great to know that it's actually already supported! 

In that case, I think the issue is with the discoverability of the existing feature. (It was the most common request among the comments I read.)

Like you suggested, putting all those options into the advanced menu sounds like a really good idea. Something like this:
<img width="1655" alt="filters in the advanced menu" src="https://user-images.githubusercontent.com/11873270/111958252-3d276f00-8aaa-11eb-9147-5b1b1891ae38.png">

**Comment by isoos** [comment]
One thing to note: these items become links only in one of the recent releases:
<img width="577" alt="Screenshot 2021-03-22 at 10 25 51" src="https://user-images.githubusercontent.com/4778111/111968059-0e84b500-8af9-11eb-82c9-5eefaea0019f.png">

Clicking on them will go the the related search page with the SDK and the runtime/platform selected. We should wait out the effect of this and see whether it has helped to discover the feature.

**Comment by jayoung-lee** [comment]
> Clicking on them will go the the related search page with the SDK and the runtime/platform selected. We should wait out the effect of this and see whether it has helped to discover the feature.

It's really cool! The analytics shows that the number of users who used Android filter `/flutter/packages?platform=android` increased from ~500 per week to ~5,000 per week. :)

**Comment by jayoung-lee** [comment]
I had to come back to this one after thinking about #4721. 

If a user wants to see packages that support a specific platform only, I _think_ the natural reaction would be clicking on the "Advanced" menu, because that's where the filters are. So I still think that showing the platform filters under the advanced menu (regardless of the behavior of the platform tags under the packages) is a good idea.

**Comment by jayoung-lee** [comment]
In addition to adding the platform filter under the advanced menu, 

I still think that keeping the search context is important, when users click on those runtime/platform names under each package.  For example, when someone searches for "bluetooth" and click on "iOS", this person is probably looking for a bluetooth package for iOS devices.

In any case, features related to platform filters may be revisited this quarter. :)  @jonasfj

**Comment by jonasfj** [comment]
I think this has been solved with latest rework of search.
