### ISSUE TITLE
Clicking on the pub points of a prerelease opens the stable score calculation

### ISSUE THREAD

**Issue by nohli** [dart-lang/pub-dev#4642]
* When clicking on the pub points here https://pub.dev/packages/assets_audio_player_web/versions/3.0.0-nullsafety.0
 * It leads to https://pub.dev/packages/assets_audio_player_web/score
 * Expected would be https://pub.dev/packages/assets_audio_player_web/versions/3.0.0-nullsafety.0/score

**Comment by isoos** [comment]
@nohli: thanks for reporting it, we shall fix it soon!
