### ISSUE TITLE
In the list of Countries, the Vatican City State is coming with the countries starting with alphabet 'H'. Please update it so i can use it in my project.

### ISSUE THREAD

**Issue by BhaveshRao180** [dart-lang/pub-dev#4644]
URL: https://pub.dev/packages/intl_phone_number_input

<Describe your issue or suggestion here>

**Comment by isoos** [comment]
@BhaveshRao180 This repository is for `pub.dev`. Please use the package's repository to report issues. You can find it in the right-side infobox, in this case: https://github.com/natintosh/intl_phone_number_input/issues
