### ISSUE TITLE
Change the Way Last Commit is Displayed and Unmaintained Tag [Enhancement]

### ISSUE THREAD

**Issue by ranjithrd** [dart-lang/pub-dev#4648]
- Many packages on pub.dev are released and not maintained after some time.
- To help package hunters know if the package is maintained or not, the "Last Commit" metric is very helpful.
- In the search page on pub.dev, it is displayed as "Updated: Mar 4, 2021". It would be more helpful for it to be displayed as "Updated: 17 days ago".
- In the package page on pub.dev, it is displayed as "Published Mar 4, 2021". Again, the same copy can be used here. "Updated 17 days ago".
- The "Published" date can be kept on a separate line, for example, under the "Metadata" section.

- Another helpful enhancement would be to add an "Unmaintained" tag if the last commit is more than 6 months old. Flutter's ecosystem keeps changing every so often and packages almost always need to be updated to keep in line. If a package is not commited to in more than 6 months, it can be clear that it is not being unmaintained.
- This tag on both the search and the package page can be next to the new "Null Safety" tag.

Thanks for considering this. Have a good day.

**Comment by isoos** [comment]
Closing, as we have implemented the "X ago" pattern for timestamps.

The "Unmaintained" tag seems to be a bit too restrictive, there may be cases where the package doesn't need frequent updates.

Instead, we will keep using the current methods, that compares a packages to evergreen standards. If it fails to match them (either the new lints or warnings, or it has a newer dependency that is not supported), the pub score will reflect that. It may be still useful for users, so this is only affecting the rank of the package, and its position in search.
