### ISSUE TITLE
pub.dev is down (global outage)

### ISSUE THREAD

**Issue by timsneath** [dart-lang/pub-dev#4663]
![image](https://user-images.githubusercontent.com/2319867/112408932-da1a2000-8cd5-11eb-905b-a55b0a986ed0.png)

## Overview
At approximately 7pm, the pub infrastructure began to respond with a **HTTP 502 Site Error** message. The site infra is deployed to the `us-central` GCP region. This impacts core Flutter services, specifically:

- The pub.dev website itself, which presents the error above;
- Calls made by the `flutter` or `pub` commands (e.g. `flutter upgrade` or `pub upgrade`). 

Please do not reply to this bug with "me too" or +1 messages, it makes it harder for folk to track. Thanks!

## Updates
**7:10pm Pacific**
We're currently experiencing an outage on pub.dev, which appears to be related to a load balancer issue. We don't have an ETA for a resolution at this time; we're currently working to understand the issue.

**7:59pm Pacific**
The pub.dev site is still down. We have a Google on-call engineer currently investigating. We have not yet identified a root cause. 

**8:15pm Pacific**
We apologize for the inconvenience. We're seeing load balancer errors and are escalating to the appropriate team. Still no ETA, unfortunately, since we're still haven't determined the root cause.  

**8:27pm Pacific**
We have multiple Google Cloud engineers on-call investigating, but I'm sorry to report that we still don't have a root cause. We'll continue to post updates regularly. Thank you for your patience.

**9:00pm Pacific**
We are continuing to debug the problem. We have declared a Google escalated outage while we attempt to identify the root cause. Some folk have been successful using the Chinese mirror site at https://pub.flutter-io.cn. 

**9:20pm Pacific**
Again, apologies. 

**9:35pm Pacific**
We are currently exploring the theory that we have exceeded a quota, but that the error didn't show in the log. Paging an oncall team to try and increase the quota to see if this resolves. Again, this really sucks -- we recognize that it's a major inconvenience to you all, and we're feeling sick that we're down. Thank you for being patient with us :(

**9:45pm Pacific**
We have updated the quota and are resetting the VM instances, to see if we have successfully identified the root cause. 

**9:51pm Pacific**
We are seeing evidence of partially restored service.

**9:55pm Pacific**
The pub service appears to be fully restored.

**10:15pm Pacific**
Here's what we think we know at this point in time. At some point within the last day or two, a change was made to the pub.dev landing page that includes a call to the YouTube API.  There is a quota limit for YouTube calls that we didn't hit over the last few days, but today we hit it. Confounding the issue, the code was missing exception handling and the logging was inadequate or obfuscated sufficiently that we were unable to immediately spot the problem. The immediate resolution was to raise the quota temporarily to give us time to revert the original change.

At this time we think the issue is resolved, but we'll obviously be monitoring closely. Again, apologies on behalf of the Flutter & Dart teams for the disruption. We take this very seriously, and we will perform a full post-mortem and share the learnings and actions we'll take as a result of this.

**Comment by timsneath** [comment]
Internal bug: https://buganizer.corp.google.com/issues/183665226

**Comment by GiteshDalal** [comment]
Does anyone have an ETA on this?

**Comment by timsneath** [comment]
Afraid not. We're figuring out what's gone wrong; we'll update this bug with status as we learn more.

**Comment by Levi-Lesches** [comment]
The package I uploaded last night must've been so useful and efficient, the server couldn't handle it 😎

**Comment by yuebenshan** [comment]
whats happening

**Comment by GiteshDalal** [comment]
Dont we have a back up website that we can point to while pub.dev is down?
This is a big blocker for business.

**Comment by duongtruong12** [comment]
my pub get and pub upgrade is failed now, cannot do anything else...

**Comment by boyan01** [comment]
> Is there any back up website that we can point to while pub.dev is down?
> This is a big blocker for business.

If you can access pub.flutter-io.cn, then you can try to use this URL as a temporary solution.

```shell
export PUB_HOSTED_URL=https://pub.flutter-io.cn
```

ref: https://flutter.dev/community/china

**Comment by timsneath** [comment]
Updates will be posted at the top of this bug.

**Comment by xuning0** [comment]
@boyan01 Can only access the homepage

**Comment by eseidelGoogle** [comment]
Status:  All of pub.dev remain down.  Internal load-balancing errors.  We're diagnosing with SREs on call.  No ETA yet.

**Comment by GiteshDalal** [comment]
> > Is there any back up website that we can point to while pub.dev is down?
> > This is a big blocker for business.
> 
> If you can access pub.flutter-io.cn, then you can try to use this URL as a temporary solution.
> 
> ```shell
> export PUB_HOSTED_URL=https://pub.flutter-io.cn
> ```
> 
> ref: https://flutter.dev/community/china

Didn't work, seems like the backend is common for both websites.
Unable to query packages using it, even though the website homepage is available.

**Comment by LeoAiolia** [comment]
Kpi is gone this month

**Comment by yy1300326388** [comment]
I provide the following solutions, If you can't pack it, please try as follows
- pub.dev
``` shell
 export PUB_HOSTED_URL=/Users/${userName}/.pub-cache/hosted/pub.dev
```
- pub.flutter-io.cn （中国地区请使用下面的命令）
``` shell
 export PUB_HOSTED_URL=/Users/${userName}/.pub-cache/hosted/pub.flutter-io.cn
```

**Comment by paurakhsharma** [comment]
Is this the reason for me being stuck at this? This happened after I downgraded from `2.0.1` to `1.22.6`. I even reinstalled flutter but still stuck at it.

![image](https://user-images.githubusercontent.com/20378877/112414952-18055b80-8d4b-11eb-91c8-8b7850ea0acd.png)

**Comment by Rquinz** [comment]
> Is this the reason for me being stuck at this? This happened after I downgraded from `2.0.1` to `1.22.6`. I even reinstalled flutter but still stuck at it.
> 
> ![image](https://user-images.githubusercontent.com/20378877/112414952-18055b80-8d4b-11eb-91c8-8b7850ea0acd.png)

Yeah, it is

**Comment by paurakhsharma** [comment]
> Yeah, it is

Thanks 😅

**Comment by almpazel** [comment]
It's happen , @flutter team can fixed that yeah....
Good luck......
We are wating..............

**Comment by yubaokang** [comment]
挂球了

**Comment by Anoirwork** [comment]
PUBdemic 😂😂

**Comment by kyg5474** [comment]
머슨129

**Comment by YowFung** [comment]
Flutter 团队开启了 `996ICU` 拯救模式……

**Comment by mingyouzhu** [comment]
Pub is down,挂球了😂😂😂😂😂

**Comment by milewski** [comment]
Does aliyun has any pub.dev mirrors? or something we can use meanwhile?

**Comment by wwtssu** [comment]
早く回復してほしい

**Comment by Rquinz** [comment]
> Does aliyun has any pub.dev mirrors? or something we can use meanwhile?

Saw this above. You can try this.

If you can access pub.flutter-io.cn, then you can try to use this URL as a temporary solution.

export PUB_HOSTED_URL=https://pub.flutter-io.cn

ref: https://flutter.dev/community/china

doesnt work for me though. goodluck

**Comment by mingyouzhu** [comment]
the "pub.flutter-io.cn" is accessible

**Comment by wwtssu** [comment]
> Does aliyun has any pub.dev mirrors like it does for composer/npm/others package manegers? or something we can use meanwhile?

try this: https://mirrors.tuna.tsinghua.edu.cn/help/dart-pub/
but it not work for me

**Comment by azhon** [comment]
Can't write code, forced to paddle

**Comment by almpazel** [comment]
http( https://pub.flutter-io.cn/packages/alm ).then(res){
       if(res.statusCode==200){
           Is that happen Again? what happen if happenS>??????????
       }else{
           We are still waiting ........{What happen? Flutter Pub >???? }
       }
}

**Comment by stargt** [comment]
help

**Comment by rmasonh18** [comment]
Thanks for being on top the issue ~ good to know problem isn't issue on my mac.

**Comment by hienlh** [comment]
Many businesses are being blocked. Please resolve it soon!

**Comment by yy1300326388** [comment]
> 许多企业被封锁。请尽快解决！等待一个好消息

Please see my solution https://github.com/dart-lang/pub-dev/issues/4663#issuecomment-806338861

**Comment by yy1300326388** [comment]
> Thanks for being on top the issue ~ good to know problem isn't issue on my mac.

Please see my solution https://github.com/dart-lang/pub-dev/issues/4663#issuecomment-806338861

**Comment by ahyangnb** [comment]
help

**Comment by Levi-Lesches** [comment]
Guys please stop spamming this issue. We all get notified every time. Just press the subscribe button on the side and wait for an update please, we're all being patient.

**Comment by bhtri** [comment]
Got socket error trying to find package example at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...

**Comment by doyle-flutter** [comment]
![image](https://user-images.githubusercontent.com/56661529/112417937-e5b82600-8d6b-11eb-8a2c-11703d32ec66.png)
cn.. error...

**Comment by Levi-Lesches** [comment]
Again, if you have this error -- just wait. Please don't post unless you're on the team fixing this. (I'll stop so I don't spam either).

**Comment by milewski** [comment]
Run this command, assuming the packages you are using are common enough and have been previously cached via this flutter mirror before the outage, if it doesn't work for you that's because the package didn't exist on mirror cache and it will attempt to fetch `pub.dev` which obviously will not work.. so good luck

```bash
PUB_HOSTED_URL=https://pub.flutter-io.cn flutter pub get
```

**Comment by jo3ght** [comment]
I'm becoming short on a deadline

**Comment by davidlawson** [comment]
pub.flutter-io.cn isn't working for me, but the following mirrors are:
```
https://mirrors.tuna.tsinghua.edu.cn/dart-pub
https://mirrors.cloud.tencent.com/dart-pub
```

**Comment by blupointmedia** [comment]
> Run this command, assuming the packages you are using are common enough and have been previously cached via this flutter mirror before the outage, if it doesn't work for you that's because the package didn't exist on mirror cache and it will attempt to fetch `pub.dev` which obviously will not work.. so good luck
> 
> ```shell
> PUB_HOSTED_URL=https://pub.flutter-io.cn flutter pub get
> ```

How would I clear this after it is back up again?

**Comment by awaisahmad94** [comment]
@davidlawson How to set to this mirror to fetch pls guide for mac. thanks

**Comment by milewski** [comment]
> How would I clear this after it is back up again?

You don't need to do anything. this is not setting anything up permanently

**Comment by simonpham** [comment]
> > Run this command, assuming the packages you are using are common enough and have been previously cached via this flutter mirror before the outage, if it doesn't work for you that's because the package didn't exist on mirror cache and it will attempt to fetch `pub.dev` which obviously will not work.. so good luck
> > ```shell
> > PUB_HOSTED_URL=https://pub.flutter-io.cn flutter pub get
> > ```
> 
> How would I clear this after it is back up again?

Just close your Terminal

**Comment by awaisahmad94** [comment]
> pub.flutter-io.cn isn't working for me, but the following mirrors are:
> 
> ```
> https://mirrors.tuna.tsinghua.edu.cn/dart-pub
> https://mirrors.cloud.tencent.com/dart-pub
> ```

☝️

**Comment by 1l0** [comment]
I've confirmed that one of the mirrors works for `flutter upgrade`. Thanks for the info.
```
PUB_HOSTED_URL=https://mirrors.cloud.tencent.com/dart-pub flutter upgrade
```

**Comment by ensaryusuf** [comment]
TencentsCDN network can be partially distributed. Packages keep not working.

> pub.flutter-io.cn isn't working for me, but the following mirrors are:
> 
> ```
> https://mirrors.tuna.tsinghua.edu.cn/dart-pub
> https://mirrors.cloud.tencent.com/dart-pub
> ```
> 
> example terminal usage (non-permanent):
> 
> ```
> PUB_HOSTED_URL=https://mirrors.tuna.tsinghua.edu.cn/dart-pub flutter pub get
> PUB_HOSTED_URL=https://mirrors.cloud.tencent.com/dart-pub flutter pub get
> ```

Tencents CDN network can be partially distributed. Packages keep not working.

**Comment by xxived** [comment]
server is up now, at least for me

**Comment by Salahadin48** [comment]
Running this command in the terminal of the current project resolves my issue. PUB_HOSTED_URL=https://mirrors.cloud.tencent.com/dart-pub flutter pub get

**Comment by MrBirb** [comment]
Looks like it is back!

**Comment by yeras-is** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by rifat-hossain1** [comment]
Ah..finally its UP now!

**Comment by Adityachavda** [comment]
Its Back, Site is Now Working

**Comment by ChanYuXuan** [comment]
It's back finally!!

**Comment by whatamelon** [comment]
Finally Pub dev fixed! All of flutter team Congrats!

**Comment by huynhchicuong** [comment]
gz team! 🎉🎉

**Comment by vinothvino42** [comment]
Congratulations Team 👏

**Comment by ensaryusuf** [comment]
Everyone to the beginning of the code. 😂
Pub.dev is now stable.

**Comment by H-Zaman** [comment]
GGWP

**Comment by HasanAlyazidi** [comment]
Up and running, thank you

**Comment by goose-intestine** [comment]
Congrats Team

**Comment by hienlh** [comment]
Many thank for all Flutter team

**Comment by arteevraina** [comment]
You are superheroes.

**Comment by daiki1003** [comment]
Thanks all :)

**Comment by DevKhalyd** [comment]
Working 👍

**Comment by bhtri** [comment]
Thank you very much

**Comment by 3lVv0w** [comment]
Working 🙏

**Comment by doyle-flutter** [comment]
Thanks !!! 🙏
'pub get' working !
![image](https://user-images.githubusercontent.com/56661529/112421128-d936cc00-8d71-11eb-92fd-0c69afede2bf.png)

**Comment by saswatsaubhagya** [comment]
Working , Thank you.

**Comment by kojimakumi** [comment]
ありがとう!!! 🙏

**Comment by luoxufeiyan** [comment]
`Pub.dev` is now accessable in Australia. 

```
HTTP/1.1 303 See Other
Date: Thu, 25 Mar 2021 04:57:07 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
location: https://pub.dev/
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
server: dart:io with Shelf
Via: 1.1 google
```

**Comment by wwtssu** [comment]
Working!!! 🙏

**Comment by sudoaccess** [comment]
uuuuuuuppppppp

**Comment by ensaryusuf** [comment]
@timsneath What was the source of the problem?

**Comment by Nanra** [comment]
Pub.dev is accessable in Indonesia. Great !!!
<img width="1771" alt="Screen Shot 2021-03-25 at 12 00 35" src="https://user-images.githubusercontent.com/9511668/112421515-c1574c00-8d61-11eb-8c4f-661e97a2155a.png">

**Comment by kevkanae** [comment]
pub.dev seems to back, but pub get is aint working

**Comment by kevkanae** [comment]
pub.dev seems to back, but pub get is aint working

**Comment by hjleesm** [comment]
👍

**Comment by Nanra** [comment]
pub.dev is now accessible from Indonesia. Great 👍🏻✨
<img width="1390" alt="Screen Shot 2021-03-25 at 12 07 46" src="https://user-images.githubusercontent.com/9511668/112422140-00d26800-8d63-11eb-813f-726904b2245c.png">

**Comment by timsneath** [comment]
Thank you all. I've posted a quick update at the top of this bug, but in summary services should now be resolved. We've identified the root cause and increased the quota as a short-term measure until we rollback the offending code.

**Comment by timnew** [comment]
@timsneath any status page for the pub.dev. in case similar issue happens in the future so we can check the service status.
And will it be any public incident report?

**Comment by timsneath** [comment]
Can't speak to the status page yet; we'll figure out the right mitigations during the post mortem. I'm not sure it would have helped us much: the issue page seemed fairly effective to communicate status. But interested to hear from others. 

Yes, we'll share the post-mortem summary. It should make for fun reading :) We operate a blameless post-mortem policy at Google; it's all about learning lessons rather than finding scapegoats. Any failure is a system failure, and we try and learn how we can address the system causes.

**Comment by lookiestudio** [comment]
pub.dev is now accessible from Vietnam.

**Comment by vgsrivathsan** [comment]
![sock error](https://user-images.githubusercontent.com/56731835/112440955-eacba400-8d70-11eb-9266-dff13ff91043.png)
pub get is showing socket error

**Comment by yy1300326388** [comment]
> ![袜子错误](https://user-images.githubusercontent.com/56731835/112440955-eacba400-8d70-11eb-9266-dff13ff91043.png)
> pub get显示套接字错误

你被墙了

**Comment by frostfoxx** [comment]
> 
> 
> > ![袜子错误](https://user-images.githubusercontent.com/56731835/112440955-eacba400-8d70-11eb-9266-dff13ff91043.png)
> > pub get显示套接字错误
> 
> 你被墙了

thanks!

**Comment by TheMisir** [comment]
Seriously, why didn't you cached YouTube calls for some period of time (eg: release cache a few times a day) in the beginning?
Just wondering, seriously.

**Comment by isoos** [comment]
> Seriously, why didn't you cached YouTube calls for some period of time (eg: release cache a few times a day) in the beginning?
> Just wondering, seriously.

We do cache them, here is the related code with history:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/service/youtube/backend.dart

However, once the fetched failed with the quota limit, the error propagated up in the chain - until the isolate was killed, restarted and with the restart we started to fetch it again. We will redesign/refactor this and similar background task so we can make sure such failures will not be propagated in the future.

**Comment by TheMisir** [comment]
> > Seriously, why didn't you cached YouTube calls for some period of time (eg: release cache a few times a day) in the beginning?
> > Just wondering, seriously.
> 
> We do cache them, here is the related code with history:
> https://github.com/dart-lang/pub-dev/blob/master/app/lib/service/youtube/backend.dart
> 
> However, once the fetched failed with the quota limit, the error propagated up in the chain - until the isolate was killed, restarted and with the restart we started to fetch it again. We will redesign/refactor this and similar background task so we can make sure such failures will not be propagated in the future.

Oh I get it. :D Since the previous fetch is failed and the cache was empty the restarted isolate tried to fetch new data again, and it failed & crashed the isolate and gce restarted it then the loop continued... Interesting failure.

Thanks for letting us know!

**Comment by Levi-Lesches** [comment]
Want to reiterate that -- **thanks for the quick response and clear communication**. Maintenance is one of those things that goes unnoticed until it's a _bad_ thing, but it makes us appreciate that pub.dev is otherwise 100% reliable and easy-to-use. ❤️

**Comment by jonasfj** [comment]
Postmortem is referenced here: https://github.com/flutter/flutter/wiki/Postmortems

**Comment by xi1570-krupeshanadkat** [comment]
It seems it is down again (region South Asia - India)

<img width="1135" alt="Screenshot 2021-11-29 at 10 35 44 AM" src="https://user-images.githubusercontent.com/59952787/143811914-c89e0118-e1b4-466d-8b7d-1236dadcbdbf.png">

Attached chrome devtools > Network tab screenshots for reference.

My network seems fine, rest of the stuff is opening correctly.
<img width="1667" alt="Screenshot 2021-11-29 at 10 37 50 AM" src="https://user-images.githubusercontent.com/59952787/143812079-4e8e462b-5dc4-49e2-bc1b-9b3a3d23c41f.png">

**Comment by xi1570-krupeshanadkat** [comment]
> It seems it is down again (region South Asia - India)
> 
> <img alt="Screenshot 2021-11-29 at 10 35 44 AM" width="1135" src="https://user-images.githubusercontent.com/59952787/143811914-c89e0118-e1b4-466d-8b7d-1236dadcbdbf.png">
> 
> Attached chrome devtools > Network tab screenshots for reference.
> 
> My network seems fine, rest of the stuff is opening correctly. <img alt="Screenshot 2021-11-29 at 10 37 50 AM" width="1667" src="https://user-images.githubusercontent.com/59952787/143812079-4e8e462b-5dc4-49e2-bc1b-9b3a3d23c41f.png">

Looks like resolved.

**Comment by manglide** [comment]
It's still not working. Can't access pub.dev

**Comment by isoos** [comment]
@manglide: please open a new issue next time, we don't monitor closed issues.

As pub.dev is working for me, it is possible that the problem is at your ISP's side. Please run this script and return back its output:
https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart

**Comment by manglide** [comment]
Hi @isoos, thanks for your response. The issue is from my local dnsmasq configuration on mac. I have resolved it now and can access pub.dev.

Thanks once again.

**Comment by luis901101** [comment]
Hi, is any problem with this again right now?

**Comment by rirjkl19** [comment]
Pub dev is down again

**Comment by iamchathu** [comment]
Is there any public status page for pub.dev?

**Comment by sigurdm** [comment]
@iamchathu no we don't have such a page
