### ISSUE TITLE
Pub.dev support mirror (self-hosted server)?

### ISSUE THREAD

**Issue by SomboChea** [dart-lang/pub-dev#4665]
I want to set up my own pub.dev mirror for local development. It seems like [verdaccio](https://github.com/verdaccio/verdaccio) that provider NPM registry mirror and cached packages too.

***Does pub.dev support?***
 * Self-hosted
 * Packages cached for mirror-hosted
 
***Advantages***
- Easy us to download or upgrade packages faster and no down-time
- Caching on packages
- Easy maintenance

Thank you.

**Comment by isoos** [comment]
I think `package:pub_mirror` and `package:mpp` may be of help here too. See more details about it here: https://github.com/dart-lang/pub-dev/issues/4671#issuecomment-808032714

Would that solve the issue for you?

**Comment by SomboChea** [comment]
@isoos For this `package:pub_mirror` it's pretty nice for pub.dev mirror in our development.

Thank you.
