### ISSUE TITLE
Packages are showing Unidentified tag in pub.dev

### ISSUE THREAD

**Issue by SriramKiranSenthilkumar** [dart-lang/pub-dev#4668]
All our packages got unidentified after publishing recently, but we are able to get the packages at our end and we are not able to find the exact cause for this case. Kindly check and resolve this.

Our packages: https://pub.dev/publishers/syncfusion.com/packages

![image](https://user-images.githubusercontent.com/63577117/112450204-2880fa80-8d7a-11eb-92a3-fb6777832037.png)

**Comment by isoos** [comment]
Based on the logs, the analysis of your packages were affected by the outage pub.dev had today and they failed as `pub get` failed to run. They should be scheduled for another analysis run within a day...

**Comment by isoos** [comment]
The re-run was successful, tags are displayed as expected.
