### ISSUE TITLE
Private package

### ISSUE THREAD

**Issue by rodmoreno** [dart-lang/pub-dev#4671]
Hi, into my organization we're building a SDK that we offer only to certain clients that their apps are built on Flutter. As npm we can upload a private package only for certain authenticated clients?

In the case that pub.dev don't offer private packages my organization can create their own pub.dev? And finally our customers with Flutter apps can use this own pub.dev?

**Comment by isoos** [comment]
You have several options to specify a different pub server:
- You can use the `PUB_HOSTED_URL` environment variable to point to a different server https://dart.dev/tools/pub/environment-variables
- The dependencies in `pubspec.yaml` can specify their server: https://dart.dev/tools/pub/dependencies#hosted-packages

In the end, the `pub` client uses the following repository API specification to access the server:
https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md

Unfortunately, third-party authentication is not yet a solved issue with the `pub` client:
https://github.com/dart-lang/pub/issues/1381

However, there are a few pub servers that one may use on internal corporate networks (in no particular order):
- https://pub.dev/packages/mpp
- https://pub.dev/packages/pub_mirror
- https://pub.dev/packages/unpub
- https://github.com/dart-archive/pub_server (discontinued, but pub.dev used it as its backbone for a while)

I'm not sure if you will be able to use these for the goals you've specified, but I hope it gave you some pointers. Let us know if we can help with something specific.
