### ISSUE TITLE
"Failed to run dartdoc" shows empty output

### ISSUE THREAD

**Issue by Komposten** [dart-lang/pub-dev#4675]
My package [public_suffix](https://pub.dev/packages/public_suffix/) has lost 10 points because dartdoc failed to run in the latest analysis. When I check the score page it says "Running dartdoc failed with the following output" but no output is provided:

![image](https://user-images.githubusercontent.com/7335682/112724560-3cf8fa80-8f14-11eb-8321-7d40430dcbf0.png)

**Comment by sethloco** [comment]
I had the same issue ([es_compression](https://pub.dev/packages/es_compression)) which seemed to happen around the time of the recent pub.dev outage.  Of course, this is just a guess.

However, I did a small update to pub.dev just a moment ago and it seems to be fixed

**Comment by Komposten** [comment]
Yeah, it probably fixes itself when the analysis is run again so I'm not too worried about that. It's just that the output probably should say _something_ (whether it is actual dartdoc output or that the request to run the command failed or whatever). :)

**Comment by sethloco** [comment]
Your absolutely right...empty error output indicates there is probably some room to improve:)

**Comment by tiloc** [comment]
Same thing here for my just published package "faiadashu". No indication of a general outage. Also happens to colleagues of mine on a regular basis with their packages. I assumed it was because their package is huge (>10k files), but mine is very compact and it still happens.

**Comment by isoos** [comment]
In case of `faiadashu` the log has an indication that no content was detected in the output: https://pub.dev/documentation/faiadashu/latest/log.txt

Not sure why that would be, the package looks fine otherwise, I'll investigate a bit more.
