### ISSUE TITLE
Provide counts/popularity for cli apps.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/pub-dev#4684]
I have published a number of dart packages which are cli apps and which don't provide an api.

Example projects:
https://pub.dev/packages/nginx_le
https://pub.dev/packages/dswitch

It appears that as the package doesn't have an api, that can be included in a dependency, then pub.dev doesn't seem to count the 'pub global activations'.

Can we please get counts that reflect global activations.

**Comment by sigurdm** [comment]
Yes! - we have started sending analytics on `pub get` to improve our popularity counts (still the popularity is not based on those). We should also do that for global activations. Filed https://github.com/dart-lang/pub/issues/3226 .

**Comment by sigurdm** [comment]
Closing in favor of the other issue
