### ISSUE TITLE
Got socket error trying to find package json_serializable at https://pub.dartlang.org

### ISSUE THREAD

**Issue by EtienneBauscher** [dart-lang/pub-dev#4690]
Good morning from South Africa

- Not able to run the "flutter pub get" command since last night. It produced the following error:
"Got socket error trying to find package json_serializable at https://pub.dartlang.org" and then 
"pub get failed (server unavailable) -- attempting retry 1 in 1 second..." 

Any assistance would be greatly appreciated.

**Comment by EtienneBauscher** [comment]
@isoos : Yes I can access the link via curl. Below command and the response:

`curl -s 'https://pub.dartlang.org/api/packages/json_serializable/versions/4.1.0'
{"version":"4.1.0","pubspec":{"name":"json_serializable","version":"4.1.0","description":"Automatically generate code for converting to and from JSON by annotating Dart classes.","repository":"https://github.com/google/json_serializable.dart/tree/master/json_serializable","environment":{"sdk":">=2.12.0 <3.0.0"},"dependencies":{"analyzer":">=0.41.2 <2.0.0","build":"^2.0.0","build_config":"^0.4.4","collection":"^1.14.0","json_annotation":">=4.0.1 <4.1.0","meta":"^1.3.0","path":"^1.8.0","source_gen":"^1.0.0"},"dev_dependencies":{"build_runner":"^1.0.0","build_verify":"^2.0.0","dart_style":"^2.0.0","logging":"^1.0.0","pub_semver":"^2.0.0","source_gen_test":"^1.0.0","stack_trace":"^1.10.0","test":"^1.16.0","yaml":"^3.0.0"}},"archive_url":"https://pub.dartlang.org/packages/json_serializable/versions/4.1.0.tar.gz","published":"2021-03-19T21:12:21.426982Z"}%`

I am on MacOS Big Sur 11.2.3 (20D91) - Flutter 2.0.1, Dart v3.21.0 - No VPN - Using Kaspersky Internet Security, disabled it but the problem persists. ISP is Technology Access Group.

The file is extremely lengthy. Is there anything in particular that I can look out for?

**Comment by EtienneBauscher** [comment]
@isoos - Attached the file, it seems the command could not finish executing as the connection to the server failed.
[PubGet.txt](https://github.com/dart-lang/pub-dev/files/6243790/PubGet.txt)

**Comment by isoos** [comment]
@EtienneBauscher This seems to be either an OS-level issue / limit being triggered, or a bug in Dart VM. Could you please try to experiment with the following?

- Let's get the number of open files while doing the `pub get` command, I think `lsof | wc -l` could do the trick...
- Let's check and potentially increase the limits `uname -n 65536` for example...

**Comment by EtienneBauscher** [comment]
@isoos - Thank you for the assistance, kindly see below as requested.

- pub get lsof | wc -l
  The current Dart SDK version is 2.10.1.
  Because xml_app requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
  1

The above response is strange as my pubspec.yaml file has the below as SDK version

environment:
  sdk: ">=2.12.0-0 <3.0.0"

- uname -n 65536
  usage: uname [-amnprsv]

The current Dart SDK version is 2.10.1.

Because xml_app requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
       1

**Comment by isoos** [comment]
@EtienneBauscher sorry, I wasn't clear. It is not `pub get lsof`, it is just `lsof | wc -l ` (`lsof` lists the open file descriptors, `wc -l` takes them as input and outputs the number of lines).

**Comment by EtienneBauscher** [comment]
@isoos - Okay the response was:

-  6610

**Comment by EtienneBauscher** [comment]
@isoos And again 6589 on another...

**Comment by EtienneBauscher** [comment]
@isoos And again 6659 with `flutter pub get` running...

**Comment by EtienneBauscher** [comment]
@isoos - And once more 6654...

**Comment by isoos** [comment]
Oops, I've got the `uname` wrong, it was `ulimit`. Basically this example: https://stackoverflow.com/a/65397634
- `ulimit -a` lists the current limits
- `ulimit -n 65535` can increase e.g. the open file limit to the specified value

**Comment by EtienneBauscher** [comment]
@isoos 

- ulimit -a 
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2784
-n: file descriptors                10496

- ulimit -n 65535   DONE

**Comment by isoos** [comment]
@EtienneBauscher Does the increased limit solve the issue?

**Comment by EtienneBauscher** [comment]
@isoos - No unfortunately not... Thanks in any case..

ulimit -n 65535
my path % flutter pub get
Got socket error trying to find package json_serializable at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Got socket error trying to find package json_serializable at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
Got socket error trying to find package json_serializable at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
Got socket error trying to find package json_serializable at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...
Got socket error trying to find package json_serializable at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 5 in 16 seconds...
Got socket error trying to find package json_serializable at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...
Got socket error trying to find package json_serializable at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...
Got socket error trying to find package json_serializable at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 8 in 64 seconds...
Got socket error trying to find package json_serializable at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 9 in 64 seconds...
Got socket error trying to find package json_serializable at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 10 in 64 seconds...
Got socket error trying to find package json_serializable at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 11 in 64 seconds...
Got socket error trying to find package json_serializable at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 12 in 64 seconds...

**Comment by EtienneBauscher** [comment]
@isoos - Will declaring the environment variable PUB_HOSTED_URL not work in this instance as it did with the issue [here](https://github.com/dart-lang/pub/issues/1989) ? I see the URL was not recommended at the end, is there not another I could possibly use? Desperate to get my app up and running again :)

**Comment by EtienneBauscher** [comment]
@isoos - I have noted that the` ulimit `parameters are reset every time I open a new terminal - Is this normal behaviour of the system?

**Comment by isoos** [comment]
@EtienneBauscher please do not use the `*.appspot.com` URLs as a replacement for `pub.dev` (staging site may not work, and may have corrupted/inconsistent data).

There are a few more things that could help you:
- a concurrency-restricted local http proxy, which `pub` client would use to access the internet. `pub` uses concurrent http request, and the proxy could restrict them to serialized requests.
- a local pub mirror eg. https://pub.dev/packages/pub_mirror (which also has concurrency controls)

**Comment by EtienneBauscher** [comment]
@isoos - I have tried all but the Docker installation method of the pub mirror library and I still get a similar error, 

`pub global activate mirror
Resolving dependencies... (33.4s)
It looks like pub.dartlang.org is having some trouble.
Pub will wait for a while before trying to connect again.
Got socket error trying to find package mirror at https://pub.dartlang.org.`

I am not familiar with using Docker yet as I am in the process of learning how to use Images with Containers.
I am also not familiar with the concurrency-restricted local HTTP proxy method but I can try and learn.
Any further news on your side with regards to this error?

**Comment by isoos** [comment]
If you do a local mirror, than you should combine `pub` with `PUB_HOSTED_URL` pointing to `http://localhost:<port>/` (whatever the pub mirror runs on). I haven't used `package:pub_mirror` yet, but based on the description `pub global activate pub_mirror` + `pub global run pub_mirror` should work.

**Comment by EtienneBauscher** [comment]
Thank you @isoos - I'll implement and revert...

**Comment by EtienneBauscher** [comment]
@isoos - Storing a downloaded package on a local xampp server. I can access the url but need assistance with how to install it from the terminal and to which folder in the flutter projects structure (Or is there a command that will do this?). I have tried `pub get path_provider PUB_HOSTED_URL="http://localhost:8080/pub_dev"` but it is not successful. The downloaded package is in tar.gz format. It seems I would have to do this for all the packages in the project. 
Any assistance would be greatly appreciated...

**Comment by jonasfj** [comment]
@EtienneBauscher do you have IPv6 enabled? Can you try to disable it and see if that makes any difference?

**Comment by EtienneBauscher** [comment]
@jonasfj - The funny thing is, there is no option to disable it :) -  I only have options to configure IPv6 "Manually", "Automatically" and "Link-Local Only".

**Comment by EtienneBauscher** [comment]
@jonasfj -  I have also spoken to my ISP and was told that it is not utilised from their side so I can leave it on "Automatically"

**Comment by jonasfj** [comment]
@EtienneBauscher maybe try the tool @isoos wrote in https://github.com/dart-lang/pub-dev/pull/4699

```
wget https://raw.githubusercontent.com/dart-lang/pub-dev/6b54bf4b7eae607d0a6b1c0fc878b77b67bae083/app/bin/tools/check_domain_access.dart
dart check_domain_access.dart 
``` 

quick note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).

**Comment by EtienneBauscher** [comment]
@jonasfj - Below the response 

`wget https://raw.githubusercontent.com/dart-lang/pub-dev/6b54bf4b7eae607d0a6b1c0fc878b77b67bae083/app/bin/tools/check_domain_access.dart
dart check_domain_access.dart
--2021-04-06 14:48:39--  https://raw.githubusercontent.com/dart-lang/pub-dev/6b54bf4b7eae607d0a6b1c0fc878b77b67bae083/app/bin/tools/check_domain_access.dart
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1440 (1.4K) [text/plain]
Saving to: ‘check_domain_access.dart’

check_domain_access.dart      100%[=================================================>]   1.41K  --.-KB/s    in 0.001s  

2021-04-06 14:48:40 (2.26 MB/s) - ‘check_domain_access.dart’ saved [1440/1440]

Iteration #1/10...
Unhandled exception:
SocketException: Connection failed, address = pub.dev, port = 443`

**Comment by jonasfj** [comment]
@EtienneBauscher I patched it to print addresses resolved, maybe give that a spin:
https://gist.github.com/jonasfj/0c60d28223efc9149a2497962c1e25b5

**Comment by EtienneBauscher** [comment]
@jonasfj - See the attached file
[0c60d28223efc9149a2497962c1e25b5.txt](https://github.com/dart-lang/pub-dev/files/6264950/0c60d28223efc9149a2497962c1e25b5.txt)

**Comment by jonasfj** [comment]
@EtienneBauscher I created another patched version which also tries to connect to the IPs we've resolved the address to:
https://gist.github.com/038129aecca4640c62787081ff884c86

It gives me output like:
```console
$ dart check_domain_access.dart 
Iteration #1/10...
Addresses for https://pub.dev/api/packages/http
- InternetAddress('216.239.38.21', IPv4) works!
- InternetAddress('216.239.34.21', IPv4) works!
- InternetAddress('216.239.36.21', IPv4) works!
- InternetAddress('216.239.32.21', IPv4) works!
- InternetAddress('2001:4860:4802:32::15', IPv6) FAILED TO CONNECT: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = pub.dev, port = 443
- InternetAddress('2001:4860:4802:36::15', IPv6) FAILED TO CONNECT: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = pub.dev, port = 443
- InternetAddress('2001:4860:4802:34::15', IPv6) FAILED TO CONNECT: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = pub.dev, port = 443
- InternetAddress('2001:4860:4802:38::15', IPv6) FAILED TO CONNECT: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = pub.dev, port = 443
...
```

But running https://test-ipv6.com/ (I just picked the top search result) I get the impression that my ISP doesn't have ipv6.

**Comment by EtienneBauscher** [comment]
@jonasfj - The response below 

```
 wget https://gist.github.com/jonasfj/0c60d28223efc9149a2497962c1e25b5
--2021-04-06 15:27:52--  https://gist.github.com/jonasfj/0c60d28223efc9149a2497962c1e25b5
Resolving gist.github.com (gist.github.com)... 140.82.121.3
Connecting to gist.github.com (gist.github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘0c60d28223efc9149a2497962c1e25b5’

0c60d28223efc9149a2497962c1e2     [  <=>                                             ]  68.78K   170KB/s    in 0.4s    

2021-04-06 15:27:53 (170 KB/s) - ‘0c60d28223efc9149a2497962c1e25b5’ saved [70432]
```

Here is the attached file

[0c60d28223efc9149a2497962c1e25b5.txt](https://github.com/dart-lang/pub-dev/files/6264958/0c60d28223efc9149a2497962c1e25b5.txt)

**Comment by jonasfj** [comment]
> @jonasfj - See the attached file
0c60d28223efc9149a2497962c1e25b5.txt

 @EtienneBauscher I don't see anything in the attached file.. it just looks like HTML.

Try using https://gist.github.com/

**Comment by jonasfj** [comment]
You are going to want to do:
```
wget https://gist.githubusercontent.com/jonasfj/038129aecca4640c62787081ff884c86/raw/309306f55f33178cad370ce11958a57e83f2e2f5/check_domain_access.dart
dart check_domain_access.dart 
```

**Comment by jonasfj** [comment]
@EtienneBauscher 
Running ` wget https://gist.github.com/jonasfj/0c60d28223efc9149a2497962c1e25b5` will download an HTML file.. which just produces garbage when you try to run it...

The raw URL is: `https://gist.githubusercontent.com/jonasfj/038129aecca4640c62787081ff884c86/raw/309306f55f33178cad370ce11958a57e83f2e2f5/check_domain_access.dart` --- sorry I just posted a link to the gist..

**Comment by EtienneBauscher** [comment]
@jonasfj - Kindly see the gist link 

https://gist.github.com/EtienneBauscher/af85ead5b387f34453cf3be136fe3a57

**Comment by jonasfj** [comment]
So this is a bit of a mystery to me:
```
- InternetAddress('216.239.32.21', IPv4) FAILED TO CONNECT: SocketException: Connection failed, address = pub.dev, port = 443
- InternetAddress('216.239.34.21', IPv4) FAILED TO CONNECT: SocketException: Connection failed, address = pub.dev, port = 443
- InternetAddress('216.239.36.21', IPv4) FAILED TO CONNECT: SocketException: Connection failed, address = pub.dev, port = 443
- InternetAddress('216.239.38.21', IPv4) FAILED TO CONNECT: SocketException: Connection failed, address = pub.dev, port = 443
```

But now we're getting somewhere! :rocket: 
Your DNS server seems to be working correctly. But for some reason dart cannot connect to the IPv4 addresses.

What do you get from `curl -s -v https://pub.dev/api/packages/http -o /dev/null`, the first two lines of my output is:
```
*   Trying 216.239.38.21:443...
* Connected to pub.dev (216.239.38.21) port 443 (#0)
```
That says I successfully connected to `216.239.38.21` which is one of the IPs that your `dart` failed to connect to.

If your curl can do this, then it suggests you have a system configuration, security measure or firewall which prevents `dart` programs from connecting to the internet.

**Comment by EtienneBauscher** [comment]
@jonasfj - Thank you and yes I too wondered why I have internet connection and the IPv4 failed in the curl. Below the link to the gist. 

https://gist.github.com/EtienneBauscher/f12daf74f2d4589cb56699ca3a16fdd0

**Comment by jonasfj** [comment]
> the IPv4 failed in the curl.

What do you mean, it seems from:
https://gist.github.com/EtienneBauscher/f12daf74f2d4589cb56699ca3a16fdd0#file-curl-pub-dev-api-response-L1-L3 

That IPv4 is working in `curl`.

---------------------

I think you have a firewall or other security software / sandboxing that prevents `dart` from connecting to the internet.
Perhaps if you install the dart SDK differently, or something like that, do you do a `flutter upgrade`?..
or maybe you can configure the security software to allow `dart` to talk to the internet.

If you figure out what is wrong, it'd be great to add it to: https://dart.dev/tools/pub/troubleshoot (assuming it's a common mistake others are likely to make too).

But I'm not sure how much we can help here.

**Comment by EtienneBauscher** [comment]
@jonasfj - Is it possible for Kaspersky Internet Protection to be the blockage? I have recently installed it. I have turned the protection of though but do however see a filter running. When I try to disconnect it just restarts its timing counter. See the attached screen shot.
<img width="672" alt="Screen Shot 2021-04-06 at 15 58 21" src="https://user-images.githubusercontent.com/44187788/113722879-1e9fb580-96f1-11eb-87f4-dfd1c193c6e1.png">

**Comment by EtienneBauscher** [comment]
@jonasfj - 

> > the IPv4 failed in the curl.
> 
> What do you mean, it seems from:
> https://gist.github.com/EtienneBauscher/f12daf74f2d4589cb56699ca3a16fdd0#file-curl-pub-dev-api-response-L1-L3
> 
> That IPv4 is working in `curl`.
> 
> I think you have a firewall or other security software / sandboxing that prevents `dart` from connecting to the internet.
> Perhaps if you install the dart SDK differently, or something like that, do you do a `flutter upgrade`?..
> or maybe you can configure the security software to allow `dart` to talk to the internet.
> 
> If you figure out what is wrong, it'd be great to add it to: https://dart.dev/tools/pub/troubleshoot (assuming it's a common mistake others are likely to make too).
> 
> But I'm not sure how much we can help here.

I meant the IPv4 Failed to connect to Pub Dev, apologies. So I will troubleshoot further and revert. Thanks for all the assistance!

**Comment by EtienneBauscher** [comment]
@jonasfj - Wow, I have just uninstalled Kaspersky Internet Security and I can now successfully run `flutter pub get` LOL

**Comment by jonasfj** [comment]
I filed https://github.com/dart-lang/site-www/pull/3121
