### ISSUE TITLE
Pub publish insufficient permissions

### ISSUE THREAD

**Issue by flikkr** [dart-lang/pub-dev#4693]
I am trying to upload a new dart package on pub.dev by running `dart pub publish`. 

After confirming that I want to publish the package, I get the following error: `[my-email] has insufficient permissions to upload new versions of package 'dartpedia'`. I have also tried running `dart pub uploader add [my-email]` but it gives me this message: `Unsufficient permissions to change uploaders for 'dartpedia'`. Even after logging out and back in via `dart pub logout` and `dart pub login`, it's still refusing to let me publish. 

The package name is also available on pub.dev so I'm a bit lost right now. I have managed to publish a dart package in the past.
The package I am trying to publish can be found [here](https://github.com/flikkr/dartpedia).

**Comment by isoos** [comment]
@flikkr: `package:dartpedia` exists on pub.dev:
https://pub.dev/packages/dartpedia

You can see it in search if you include discontinued packages in advanced search:
https://pub.dev/packages?q=dartpedia&discontinued=1

If you really like the name, it would be worth to contact the previous uploader - if they invite you as uploader, you will be able to take over the package...
