### ISSUE TITLE
Package not getting analysed for > 1 day.

### ISSUE THREAD

**Issue by tiloc** [dart-lang/pub-dev#4694]
My two most recent uploads of package `faiadashu` (0.1.3 and 0.1.4) did not get analysed. No indication as to why. It has previously analysed OK within a few minutes, albeit without a successful run of `dartdoc` (issue #4675). Now it is stuck in status 'Awaiting' forever.

**Comment by isoos** [comment]
Checked the logs: the `pana` analysis completed after the upload within 2.5 minutes, but the `dartdoc` did not complete. It was started after the upload, and retried this morning, both got stuck for some reason - and dartdoc was not killed.

After ~25-30 minutes we have the following exception on the stdout (but not in the regular logs) 3 times (as it if was retried) :
```
Error: The transaction was aborted.
    at GrpcDatastoreImpl.commit (package:appengine/src/grpc_api_impl/datastore_impl.dart:111:9)
    at StackZoneSpecification._registerUnaryCallback.<fn> (unknown location)
```

Not sure why this is missed, other packages have clean timeout / process kill / report.

**Comment by tiloc** [comment]
As a comparison point: It is running locally (M1 mac mini) in 160 seconds.
I am wondering whether pub.dev is trying to recreate the missing documentation for the referenced `fhir` package, which can take 30+ minutes?

**Comment by isoos** [comment]
It looks like that our latest release was able to properly detect the timeout, and the analysis is no longer stuck in 'awaiting'.
Unfortunately it is still a timeout... :/

**Comment by tiloc** [comment]
Unfortunately, it is happening again...
