### ISSUE TITLE
Expose package repository URL via API

### ISSUE THREAD

**Issue by IchordeDionysos** [dart-lang/pub-dev#4696]
I am currently working on a dependabot implementation for pub: https://github.com/dependabot/dependabot-core/pull/3438

Dependabot needs some information to generate Changelogs between versions, etc.
They build very good implementations for this already in the Dependabot Core and as a Dependabot package implementer you basically only have to provide a link to the Git repository and with that link dependabot can figure everything else on its own.

So we would basically only need the `look_up_source` and return the Git URL:
https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/metadata_finders/README.md

But from looking at the Pub API there does not seem to be any option to do this right now 🤔

**Comment by IchordeDionysos** [comment]
Okay, I am currently trying to understand how this information is retrieved ☺️ 

So correct me if I am wrong, but the logic to detect the package repo works like this:

1. Is `repository` present in the `pubspec.yaml`?
   1. If yes, then take this as the repository.
   2. If no, go to next steps.
2. Is `homepage` present in the `pubspec.yaml`?
   1. If yes, is it a repository URL?
      1. If yes, take this as the repository.
      2. If no, no link to the repository is shown.
   2. If no, no link to the repository is shown.
   
Is that how the logic works?

**Comment by IchordeDionysos** [comment]
If that's the case we probably don't need anything else in the API.

**Comment by jameschensmith** [comment]
Hey @IchordeDionysos. I'm not a maintainer of pub, so take my response with a grain of salt. I'm assuming this is specifically related to [hosted packages](https://dart.dev/tools/pub/dependencies#hosted-packages). I think you're on the right track, as [`repository`](https://dart.dev/tools/pub/pubspec#repository) and [`homepage`](https://dart.dev/tools/pub/pubspec#homepage) seem like the top contenders (you may even add [`documentation`](https://dart.dev/tools/pub/pubspec#documentation) as well).

As an example, it appears `dependabot-cargo` is also doing this same check (see lines [11](https://github.com/dependabot/dependabot-core/blob/f3b45ce7fbd43ffff223dd1a01299e062f218f33/cargo/lib/dependabot/cargo/metadata_finder.rb#L11) & [33-41](https://github.com/dependabot/dependabot-core/blob/f3b45ce7fbd43ffff223dd1a01299e062f218f33/cargo/lib/dependabot/cargo/metadata_finder.rb#L33-L41)). So, I think this is a good assumption until you hear back from the pub maintainers. Good luck getting pub in Dependabot! :blush: :+1:

**Comment by jonasfj** [comment]
I don't think it makes sense to expose information already available in `pubspec.yaml`.

If we have a verified github repository link, then I think it makes sense to expose this from the API.

------


side note: @sigurdm and I have been playing with dependabot integration too, hit me up on discord [#hackers-pub-dev](https://github.com/flutter/flutter/wiki/Chat) if you want to get involved.

**Comment by jonasfj** [comment]
Repository URL is in the pubspec YAML, so download the package and extract it.

When we have a verified repository link, I think we might expose that.
