### ISSUE TITLE
Website doesnt load properly so I cant use it

### ISSUE THREAD

**Issue by lachikhin-mikhail** [dart-lang/pub-dev#4697]
https://postimg.cc/2b1H5Zy4
pub.dev doesnt load properly for days :(

**Comment by isoos** [comment]
@lachikhin-mikhail you seem to use lots of extensions. Please check if you can open pub.dev in "Guest mode" (no extensions), and then maybe narrow down which extension interferes with the styles (or other assets).

**Comment by lachikhin-mikhail** [comment]
@isoos thanks a lot :) It was ModHeader all along
