### ISSUE TITLE
Remove old credentials.json file from getting authenticated in pub.dev

### ISSUE THREAD

**Issue by AbhishekTaparia** [dart-lang/pub-dev#4701]
I want to make sure the my old credentials.json file is not getting authenticated in pub.dev when I publish packages. I have removed the file from flutter home directory and created new json file, but previous credentials is still working.

**Comment by isoos** [comment]
The credentials file is located in `$HOME/.pub-cache/credentials.json`. I'm not sure why it would exists in Flutter home, but the pub cache is the location where you want to delete it from.

**Comment by AbhishekTaparia** [comment]
Sorry I meant `$HOME/.pub-cache/credentials.json` file only. I deleted that and created new `credentials.json`. But when I tried with old credentials(just to assure that it is not working), it was working.
