### ISSUE TITLE
Copying commands should not copy leading "$"

### ISSUE THREAD

**Issue by snehitsah** [dart-lang/pub-dev#4716]
Example link : [https://pub.dev/packages/url_launcher/install](https://pub.dev/packages/url_launcher/install)

On copying the install command to clipboard, the leading dollar sign is also copied. This is inconvenient, because when pasting it into the shell, you need to go to the beginning of command and remove it.

On the example, clicking the copy but
```
 $ flutter pub pub add url_launcher
```
while it should be this
```
flutter pub pub add url_launcher
```

This minor enhancement will improve user experience.

**Comment by jonasfj** [comment]
I think it's also sufficient to do `flutter pub add url_launcher`
