### ISSUE TITLE
Be clear about whether a Open Source license is required

### ISSUE THREAD

**Issue by ChristianKleineidam** [dart-lang/pub-dev#4720]
Currently, pub.dev hosts syncfusion packages that are not Open Source in the sense of OSI. At the same [time dart documentation ](https://dart.dev/tools/pub/publishing#preparing-to-publish) says:

`You must include a LICENSE file that contains an open-source license. We recommend the BSD license, which is used by Dart itself. You must also have the legal right to redistribute anything that you upload as part of your package.`

There's a [Reddit discussion ](https://www.reddit.com/r/FlutterDev/comments/mm1w10/friendly_reminder_and_warning_about_licenses_for/) about this and someone opened a ticket at the [syncfusion Github](https://github.com/syncfusion/flutter-widgets/issues/178).

I think both allowing non-open source packages at pub.dev and forbidding them are valid ways, but pub.dev should have a clear policy and not accept packages that violate it's policies.

**Comment by jonasfj** [comment]
The content policy is: https://pub.dev/policy#content-policy

We'll revise the documentation publishing documentation on:
`https://dart.dev/tools/pub/publishing#preparing-to-publish`

There is a requirement that a `LICENSE` file is present. But no requirement on what license you choose. I think our documentation on `https://dart.dev/tools/pub/publishing` should suggest using an OSI license.

----------------

Slightly related, we are looking into better license detection and someday we'll probably support filtering in search.

**Comment by mit-mit** [comment]
Our goal for pub.dev is to facilitate the most vibrant ecosystem possible for all Dart developers. Some developers might only be interested in open-source; others may desire to include commercial offerings. We should provide a home for all.

That being said, there are clearly things we can do to make the use cases here even better. Two concrete ideas are:

* `pub audit` feature for getting an inventory of all dependencies: https://github.com/dart-lang/pub/issues/2961

* Search filter on pub.dev for open-source licenses: https://github.com/dart-lang/pub/issues/2961
