### ISSUE TITLE
Keep the search keyword when clicked on the platform names

### ISSUE THREAD

**Issue by jayoung-lee** [dart-lang/pub-dev#4721]
These buttons work as platform filters:
![image](https://user-images.githubusercontent.com/11873270/114505099-ba935a80-9be4-11eb-8e86-32ca98a1d1e5.png)

However, if you click on one of the platform after searching for a keyword, it ignores the search keyword and show all the packages that support the platform.

For instance, if I search for `camera`, there are 555 packages. Then if I click `iOS` to see all the camera packages that support iOS, it shows 14435 packages that support iOS, starting from provider. 

Could we make the filter keep the search context?

**Comment by isoos** [comment]
I think it is f air to say that these are platform indicators, and not filters, as they are display under/inside a package description. They act as links to search, and I can see how that can be confusing, e.g. if somebody is not aware of the platform filters in search.

I think we should expose the platform filters in the default search (e.g. `/packages?q=`), and it will be less confusing for the users after seeing them both on the same page.

**Comment by jayoung-lee** [comment]
> I think we should expose the platform filters in the default search (e.g. /packages?q=), and it will be less confusing for the users after seeing them both on the same page.

Yeah, I think it makes sense to control all the filters in one place. Then this actually goes back to https://github.com/dart-lang/pub-dev/issues/4636#issuecomment-803852404. Could we add the platform filters to the `advanced` menu, so that it's easier to find?

**Comment by isoos** [comment]
On a second thought, we could treat these tags as (search-)context-aware links, with the difference that on a package page, there is no search context, and the link will be a generic search, while on the search results page it would be an additional constraint that we add to the query.

**Comment by jayoung-lee** [comment]
Hmm. Using the same UI for different purposes can potentially be confusing to users… But on the other hand, users may expect to see the filtered result and be aware of the context, if we keep the search query in the search box.
