### ISSUE TITLE
Front-End: Search input without autofocus

### ISSUE THREAD

**Issue by elbeicktalat** [dart-lang/pub-dev#4733]
Hi guys,
When the pub.dev site is loaded the input search is by default auto focused, which is not good for the following reasons:

1. Some time people want to see the popular packages by scrolling down, but what he get is a list of previous searches.
2. Most of the time when people click to `My Liked package` probably he want to scroll to see the list of those pak, but he see also same result of before.

The main idea is: when you go between the pages the search input should not be focused, instead of this, allows searching by shortcut keyboard.

**Comment by isoos** [comment]
@jayoung-lee Do we have any insight on the frequencies of these actions? My personal experience goes heavily towards search first, and for keyboard navigation hitting tab twice (or shift tab for backwards navigation) seems to be a good compromise.

**Comment by jayoung-lee** [comment]
According to the analytics data we have, most of the pub.dev visitors use the search feature. Last week, 73% of the page views of the pub.dev landing page included site search. Also, 86% of the users didn't scroll beyond 1/4 of the landing page. 

So I'd argue that the auto focus should stay, and hitting tab is a good compromise for those who're looking for something else.
