### ISSUE TITLE
Default authorization link for dart pub publish fails with 400 error

### ISSUE THREAD

**Issue by ChristianKleineidam** [dart-lang/pub-dev#4747]
I'm working on publishing [my package ](https://github.com/ChristianKleineidam/logging_to_logcat) to pub.dev.
After running `dart pub publish`  I got the message:
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A54515&code_challenge=pTZeXRwlO7v8hpsTZ3oNqJGaolGxmG6fcuBH8tFCl34&code_challenge_method=S256&scope=openid+https%3A%2%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Then click "Allow access"

When visiting https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A54515&code_challenge=pTZeXRwlO7v8hpsTZ3oNqJGaolGxmG6fcuBH8tFCl34&code_challenge_method=S256&scope=openid+https%3A%2%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email I get the error:

![grafik](https://user-images.githubusercontent.com/5765379/115881782-64c47b00-a44c-11eb-9ae3-141d03d7320e.png)

On the other hand calling:

https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A54515&code_challenge=pTZeXRwlO7v8hpsTZ3oNqJGaolGxmG6fcuBH8tFCl34&code_challenge_method=S256&scope=https%3A%2%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email 

works for authorizing myself.

**Comment by isoos** [comment]
Assuming this was temporary, as we haven't seen similar issues reported.

**Comment by shahul-hamed** [comment]
Hi , authorization not working for me it shows status 400 error
![image](https://user-images.githubusercontent.com/53473914/184471139-5175b36b-b8a3-4196-b894-a4319f17b569.png)

**Comment by isoos** [comment]
@shahul-hamed: please open new issues for something like this, and include other details, e.g. the network, ISP details and the output of the pub command with `-v`.
