### ISSUE TITLE
Pub.dartlang.org is not working in Nigeria

### ISSUE THREAD

**Issue by Ensonberg** [dart-lang/pub-dev#4749]
have been trying to get some packages from vs-code and all have been getting is:
Got socket error trying to find package english_words at https://pub.dartlang.org
I tried accessing the site from my browser and my browser was unable to resolve the link.
It is working in some other countries like Canada 
Please fix this ASAP

**Comment by isoos** [comment]
@Ensonberg we have a script that usually helps to debug issues like that:
https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart

Could you please run it locally, without the VPN, and include the results here?

Could you also include the details of your system (OS, antivirus, ISP). Usually it is one of those components that blocks access.

**Comment by Ensonberg** [comment]
The problem was actually from , my network provider in Nigeria.
Thanks @isoos
