### ISSUE TITLE
problem to find the index 1

### ISSUE THREAD

**Issue by kabaly** [dart-lang/pub-dev#4756]
URL: https://pub.dev/packages/scrollable_positioned_list/example

Hi, I used this package, I liked it a lot but there is a problem when recovering the index of item 2, i.e. index 1, at the start of the scroll it's okay but when I scroll to the last element and I return index 1 is no longer on the second item, otherwise my code is simple.
I use this to access the index
itemPositionsListener.itemPositions.value.first.index

**Comment by isoos** [comment]
@kabaly This issue tracker is for the pub.dev site, and not for individual packages. Please use the package's issue tracker to report bugs (can be found on the package page), in this case: https://github.com/google/flutter.widgets
