### ISSUE TITLE
Incorrect "web-only libraries" analysis issue

### ISSUE THREAD

**Issue by tomgilder** [dart-lang/pub-dev#4768]
I'm getting the static analysis error "Avoid using web-only libraries outside Flutter web plugin packages" on https://pub.dev/packages/routemaster/score. I don't think this is a valid analysis issue.

```
INFO: Avoid using web-only libraries outside Flutter web plugin packages.
lib/src/system_nav_web.dart:1:1

  ╷
1 │ import 'dart:html';
  │ ^^^^^^^^^^^^^^^^^^^
```

The plugin _is_ a Flutter web plugin, and the `system_nav_web.dart` file is behind a conditional import in `system_nav.dart`:

`export 'system_nav_main.dart' if (dart.library.js) 'system_nav_web.dart';`

This wasn't happening with previous releases, and I'm not sure what could have changed in my package to cause this.

**Comment by isoos** [comment]
We had a few changes recently (e.g. strictly follow the Flutter SDK's lints), and also upgraded Flutter SDK, the change may come from there. Do you have the lint info locally?

**Comment by tomgilder** [comment]
No, it doesn't show locally at all.

**Comment by isoos** [comment]
@tomgilder: Could you please share your platform and Flutter SDK version?

**Comment by tomgilder** [comment]
Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale en-FI)

**Comment by tomgilder** [comment]
Just confirm, the warning does show up locally when running `pana`. It also shows up when running pana against older versions of the project that didn't show the warning on pub.dev.

**Comment by tomgilder** [comment]
Moving this issue to https://github.com/dart-lang/linter/issues/2651 as I get it locally and it's a linter problem

**Comment by jonasfj** [comment]
linter is the right place if this happens when running `dart analyze` locally (with the right `analysis_options.yaml`)
