### ISSUE TITLE
pub_dartdoc is not generating API documentation even for libraries that are not big!

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/pub-dev#4778]
My package that is already published at pub.dev for more than 1 month (swiss_knife 3.0.6), now is reaching doc generation limit, and the API is no longer being presented!

```
Unhandled exception:
Assertion failed: "Reached 10485760 bytes in the output directory."
#0      PubResourceProvider._aboutToWriteBytes (package:pub_dartdoc/src/pub_hooks.dart:68:7)
#1      _File.writeAsBytesSync (package:pub_dartdoc/src/pub_hooks.dart:176:15)
#2      _File.writeAsStringSync (package:pub_dartdoc/src/pub_hooks.dart:182:5)
#3      DartdocFileWriter.write (package:dartdoc/dartdoc.dart:82:12)
#4      DartdocGeneratorBackend.write (package:dartdoc/src/generator/dartdoc_generator_backend.dart:103:12)
#5      DartdocGeneratorBackend.generateFunction (package:dartdoc/src/generator/dartdoc_generator_backend.dart:212:5)
#6      GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator_frontend.dart:262:29)
#7      GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:21:5)
#8      Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:189:23)
<asynchronous suspension>
#9      Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:217:28)
<asynchronous suspension>
#10     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:34:19)
<asynchronous suspension>

```

You can see the error at pub.dev:

https://pub.dev/packages/swiss_knife/score

I think that 10MB of limit is a very low limit, since my library is not a big library.

The line that checks the limit:
https://github.com/dart-lang/pub-dev/blob/85bdbf4b74c4302061885e5b7c21705e10d8fc49/pkg/pub_dartdoc/lib/src/pub_hooks.dart#L67

Note that generating the documentation in my computer I can see that my library is generating 17M of files:
```
$> dart pub global run dartdoc  --version
dartdoc version: 0.42.0

$> dart pub global run dartdoc  --output /tmp/swiss_knife/doc-test
...

$> du -h -d 1 /tmp/swiss_knife/doc-test 
 17M	/tmp/swiss_knife/doc-test/swiss_knife
116K	/tmp/swiss_knife/doc-test/static-assets
 40K	/tmp/swiss_knife/doc-test/swiss_knife_vm
 17M	/tmp/swiss_knife/doc-test
```

**Comment by jonasfj** [comment]
Hmm, we might want to see how many packages this limit affected... And perhaps tweak the limits a bit.

Thanks for the report.

**Comment by gmpassos** [comment]
Well, I don't think that a project like mine should have a special configuration to generate docs. It's normal size project.

**Comment by jonasfj** [comment]
There are many ways we could make it smaller... that wasn't really the goal. It was just to enforce some sanity limit.

**Comment by dharanidharandharmasivam** [comment]
Hey Guys, 

I am too facing such issues on pub alone for our packages(listed below), but when I generate API docs locally, it's generated properly.

1. [syncfusion_flutter_pdf](https://pub.dev/packages/syncfusion_flutter_pdf/score)
2. [syncfusion_localizations](https://pub.dev/packages/syncfusion_localizations/score)

Can you please let me know the way to resolve this?

**Comment by jonasfj** [comment]
We looked into it, and our size limit for docs was probably too low.. At-least it looked to affect more than just a few packages, so we've rolled these changes back for now.

**Comment by dharanidharandharmasivam** [comment]
@jonasfj , thank you, now API docs are generated properly.

**Comment by gmpassos** [comment]
The API docs are back! Thank you.

**Comment by isoos** [comment]
Keeping this open, as we have some related work.
