### ISSUE TITLE
update analyzer pin in pub_dartdoc package

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/pub-dev#4790]
The timing of this is possibly questionable since 2.13 isn't marked stable yet, but users are starting to report that the pub site (in my case, generated documentation) does not understand packages using 2.13 features.

dart-lang/dartdoc#2638

**Comment by jcollins-g** [comment]
@timsneath mentioned [here](https://github.com/dart-lang/dartdoc/issues/2638#issuecomment-836942571) that we are already using 2.13 beta for analysis (I couldn't find where that was set for the analysis portion of pub in a quick hurry).  If that's the case, moving to the beta for dartdoc would make sense.

**Comment by isoos** [comment]
@jcollins-g: Thanks for bringing this up, I think we can run `pkg/pub_dartdoc` from the preview SDK if the package is using it.

I'm curious: is there any specific API or feature that `dartdoc` is using under the 2.13 SDK? I though that new language features should be handled by `package:analyzer`... Or is it the linking that gets broken with the old SDK?

**Comment by jcollins-g** [comment]
@isoos Using the runtime as a different version from the tool used to generate package files is not something I had tested; I had therefore assumed some incorrect things in my testing.   Will try that and get back to you.

**Comment by jcollins-g** [comment]
@isoos I can not reproduce the problem of generating invalid documentation when running dartdoc by hand using the same versions of the runtime and beta SDKs logged for that version via pub here: https://pub.dev/documentation/winmd/1.0.0-pre.12/log.txt.  I do not know what is causing this.

**Comment by jcollins-g** [comment]
@isoos Looks like there is something about the pub_dartdoc entry point that creates this problem.  Haven't isolated it further than that, yet.

**Comment by isoos** [comment]
An update has been deployed to pub.dev and now type aliases are generated as expected.
