### ISSUE TITLE
Using secondary e-mail addresses for publishers

### ISSUE THREAD

**Issue by simolus3** [dart-lang/pub-dev#4801]
I have a publisher on pub.dev which has been created using my personal Google account. In its contact information, it shows my gmail address. I would like it to show an alternative email address that I typically use for OSS development. Of course, I've added the e-mail in question to the Google account that I use to login to pub.dev.

However, attempting to change the e-mail in the admin page of the publisher first asks to add that account to the publisher (even though it is the same logical account). When I try to invite myself to my publisher using the secondary e-mail, I can't accept the confirmation because "This invitation is not for the user account currently logged in.".

Would it be possible to also consider secondary e-mail addresses of users in a publisher?

**Comment by jonasfj** [comment]
> However, attempting to change the e-mail in the admin page of the publisher first asks to add that account to the publisher

On the admin page? I thought we decoupled this, so that the contact email doesn't have to be an account at all.

Did you actually try to add it?

I guess the text might actually be unclear.. if it's not the primary email of another admin it'll send an email that then have to be confirmed.

**Comment by simolus3** [comment]
It looks like me adding that mail to my Google account may be the problem then? I'm getting this error when trying to set the contact email:

![grafik](https://user-images.githubusercontent.com/5738860/118391086-d306f280-b632-11eb-92f5-44c8d4b7a028.png)

I tried adding it as a member, but that just causes the first problem.

**Comment by jonasfj** [comment]
Hmm, if you've removed the email from another account... That association
may still be stored in pub.dev

For contact email we should probably just send a confirmation email. And
resolve it that way.

**Comment by jonasfj** [comment]
Filed https://github.com/dart-lang/pub-dev/issues/4803

**Comment by simolus3** [comment]
> It certainly leads to cases where an email association have been moved around, yet pub.dev isn't aware

FWIW I don't think that I've actually moved the e-mail around to another account. Maybe I'm misremembering or not understanding something here, but I think the e-mail I'm trying to set has never belonged to another Google account than mine. It may be that the session I use on pub.dev is older than the association of that email address? Logging out and back in didn't help. I can send you the e-mails and the publisher if that helps to see what's going on here.

**Comment by simolus3** [comment]
I'm closing this in favor of the other issue. Thanks a lot for looking into it @jonasfj!
