### ISSUE TITLE
Feature request: Ability to manual mark a pre release as the latest pre release

### ISSUE THREAD

**Issue by erickzanardo** [dart-lang/pub-dev#4808]
Hello,

I would like to request a feature, it would be great if admins could somehow mark a pre release as the latest one.

Currently on [Flame](https://pub.dev/packages/flame/versions) we are working on a series of pre releases and we are naming them `1.0.0-rcX`, and recently we have reached our `1.0.0-rc10`.

The problem is that pub.dev shows that our latest pre release is `1.0.0-rc9`, which isn't the reality and is confusing our users.

One simple solution that I thought that could work, was if we admins could mark a version as the latest, so we could manually inform the correct one for our context. Does that makes sense? Or is there any other way we could solve this scenario?

Thanks for reading the issue and I willing to help if this is a valid feature request.

**Comment by jonasfj** [comment]
The version semantics is documented here: https://github.com/dart-lang/pub_semver
Note the specific version of semver we're following: https://semver.org/spec/v2.0.0-rc.1.html
> identifiers consisting of only digits are compared numerically and identifiers with letters or dashes are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers.

If you had named it `1.0.0-rc.X` or `1.0.0-X.rc` it would have been fine...

If you look at dart releases prereleases they are named: `2.13.0-<x>.<y>.<channel>` like `2.13.0-211.14.beta`.

This allows for `x` and `y` to control the ordering, and `channel` to be mostly informational.

You can shape these however you like, I would suggest keeping it simple.. Beware, the ordering matters in the pub solver!
So if you have `1.0.0-10.alpha` it'll be preferred over `1.0.0-9.rc` -- even for a user who has a constraint `^1.0.0-8.rc`.

--------

If you have suggestions for how to better highlight this in documentation please file an issue. I'm not sure it's a common problem.
