### ISSUE TITLE
Add unlist option to pubspec

### ISSUE THREAD

**Issue by EPNW** [dart-lang/pub-dev#4822]
With the upcoming of flutter deferal plugins, there will be many packages on pub that should work under the hood and should be thus marked as unlisted. It might be desirable to configure the listing behaviour right in the `pubspec.yaml`, rather than on the pub `Admin` page.

**Comment by isoos** [comment]
Having such option controlled via `pubspec.yaml` raises a lot of questions: what happens if the package is unlisted and you publish a new version without the property in the pubspec? What if you publish a prerelease without the property, while the latest stable marks it as unlisted.

I think this is a package-level property that doesn't really translates well to the version-level control of the `pubspec.yaml`.

**Comment by EPNW** [comment]
Hm yes, I see your point. I guess that currently, the unlisted marking from the `Admin` page is global for the package so newly published versions respect that...

When introducing a `unlisted` flag in the `pubspec.yaml` we could simply define that for the display on pub only the flag of the last stable package is considered. That of course might cause confusion if someone does not know this rule and publish a new package...

Besides all this, could you document the option for unlisting on [Publishing packages | Dart] (https://dart.dev/tools/pub/publishing)? I searched for a while to find out that unlisting is only possible using the `Admin` pannel. If I haven't had a package on pub myself, I would never have found out how to unlist a package.

**Comment by isoos** [comment]
> When introducing a unlisted flag in the pubspec.yaml we could simply define that for the display on pub only the flag of the last stable package is considered.

To complicate that logic a bit, the current search implementation considers the preview and prerelease versions. (e.g. if the prerelease version has null-safety enabled, we surface the package for the advanced filter.) In such cases, a conflict in the published versions is hard to resolve.

> I searched for a while to find out that unlisting is only possible using the Admin panel.

That is correct, and we are planning to reduce alternative admin channels (e.g. uploader control via pub client). Having an alternative flag in the pubspec seems to complicate things (we'd need parsing, handling and documentation for it), for a very thin benefit.

**Comment by jonasfj** [comment]
There is a bug for documenting this here: https://github.com/dart-lang/site-www/issues/2647

I don't think we should add `unlisted: true` to `pubspec.yaml`.

But writing better documentation and possibly adding it to Flutter federated package could also be a good idea.
