### ISSUE TITLE
#import <Flutter/Flutter.h>

### ISSUE THREAD

**Issue by zydpro** [dart-lang/pub-dev#4823]
URL: https://pub.dev/help/search

I think there is a conflict between ``` Shared_Preferences, URL_LANCHER and SHARE ``` 
on iOS because any application i use one of this i get this error

Xcode's output:
↳
    In file included from /Users/yazan/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/ios/Classes/FLTSharedPreferencesPlugin.m:5:
    /Users/yazan/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/ios/Classes/FLTSharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/yazan/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.4/ios/Classes/FLTURLLauncherPlugin.m:7:
    /Users/yazan/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.4/ios/Classes/FLTURLLauncherPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/yazan/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/share-2.0.1/ios/Classes/FLTSharePlugin.m:5:
    /Users/yazan/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/share-2.0.1/ios/Classes/FLTSharePlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>

**Comment by isoos** [comment]
This is an issue tracker for the pub.dev site. If you have issues with packages or other tools, please file it on their issue tracker.

**Comment by zydpro** [comment]
> This is an issue tracker for the pub.dev site. If you have issues with packages or other tools, please file it on their issue tracker.

when i must ask about this issue??
