### ISSUE TITLE
How to removing uploaded package

### ISSUE THREAD

**Issue by tazik561** [dart-lang/pub-dev#4834]
Hi. This is [my library](https://pub.dev/packages/alt_persian_date_picker).
is there any way to remove a particular package version from pub.dev.
i have multiple version of the package with same functionalities, didn't find any option to remove the unwanted version. I want to delete `0.0.6` to this version `0.1.2+8` 
How can I delete ?

**Comment by isoos** [comment]
@tazik561: Please check and follow the steps on our policy page: https://pub.dev/policy#purpose
