### ISSUE TITLE
https://pub.dev/ not working in my country.

### ISSUE THREAD

**Issue by khalifa007** [dart-lang/pub-dev#4837]
* Before [](https://pub.dev/ )was working but this month wasnt working on Oman its says : 
```
 * This site can’t be reachedpub.dev took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_TIMED_OUT
```
 * When i use US vpn its work , Can you please solve the issue ?

**Comment by isoos** [comment]
@khalifa007: this is a dart script we've developed to debug such issues:
https://raw.githubusercontent.com/dart-lang/pub-dev/master/app/bin/tools/check_domain_access.dart

Please download and run locally with `dart check_domain_access.dart` and include the output here.

**Comment by khalifa007** [comment]
@isoos Thank you for replaying , its stucking in "Testing one connection per request..." .

Here output 👍 

```
PS C:\Users\new97\cli> dart run
Testing host resolves...
- pub.dev IPv4 resolve and connect succeeded: 4 / 4
- pub.dev IPv6 lookup failed: SocketException: Failed host lookup: 'pub.dev' (OS Error: The requested name is valid, but no data of the requested type was found.
, errno = 11004)
- pub.dartlang.org IPv4 resolve and connect succeeded: 1 / 1
- pub.dartlang.org IPv6 lookup failed: SocketException: Failed host lookup: 'pub.dartlang.org' (OS Error: The requested name is valid, but no data of the requested type was found.
, errno = 11004)
- storage.googleapis.com IPv4 resolve and connect succeeded: 7 / 7
- storage.googleapis.com IPv6 lookup failed: SocketException: Failed host lookup: 'storage.googleapis.com' (OS Error: The requested name is valid, but no data of the requested type was found.
, errno = 11004)
Testing one connection per request...

```

**Comment by isoos** [comment]
It looks like that the IPv4 address is working for all of our hosts, but something blocks the HTTP connections. There is a small chance that you OS is running an anti-* software that blocks the connection, but if the VPN works, chances are that it is an Internet-provider issue/block. I suggest to contact them, as we can't do much about it.

**Comment by khalifa007** [comment]
@isoos  Now im angry , Why would they block this domain ! I will contact with them.

**Comment by rirjkl19** [comment]
Seems pub.dev is not working in my country right now.

**Comment by sigurdm** [comment]
@rirjkl19 where are you located? We have people in the Philippines not able to connect (see https://github.com/dart-lang/pub-dev/issues/7034)

**Comment by rirjkl19** [comment]
> @rirjkl19 where are you located? We have people in the Philippines not able to connect (see #7034)

Same case!

**Comment by khalifa007** [comment]
> Seems pub.dev is not working in my country right now.

contact your ISP they may help you to resolve this issue .
