### ISSUE TITLE
<Summarize your issues here>

### ISSUE THREAD

**Issue by OguzBektas** [dart-lang/pub-dev#4841]
URL: https://pub.dev/packages/audioplayers

<
AudioCache full documentation is broken. "https://github.com/packages/audioplayers/doc/audio_cache.md" 

>> AudioCache:
>> You can find the full documentation for this class here - https://github.com/packages/audioplayers/doc/audio_cache.md".

>

**Comment by jonasfj** [comment]
It's probably best if `audioplayers` make an absolute link in their `README.md`.

**Comment by jonasfj** [comment]
In theory, I think we try to support some of these links... but when the readme is a symlink... our heuristics will probably hit a wall.

**Comment by jonasfj** [comment]
Filed: https://github.com/luanpotter/audioplayers/pull/919
