### ISSUE TITLE
Published a package in April, still waiting to analyze

### ISSUE THREAD

**Issue by Dokotela** [dart-lang/pub-dev#4848]
- I maintain a number of packages on pub.dev surrounding using the medical data standard called FHIR. 
- The base package can be found here: https://pub.dev/packages/fhir
- The last time I tried to publish it was apparently April 16th. It still states that it's [waiting to analyze](https://pub.dev/packages/fhir/score).
- I tried to update it to a new version because I've made changes, and the command line states that it's been uploaded, but pub.dev does not show it.

**Comment by isoos** [comment]
`fhir` is a large package, and `dartdoc` struggles to generate documentation within the time limits that we have for each package. The `pana` side completes the analysis and I can see that it would get 110 out of 120. However,  the current scoring logic displays this score only if both the `pana` and the `dartdoc` analysis is present. Maybe we should relax this requirement, wdyt @jonasfj?

**Comment by jonasfj** [comment]
> Maybe we should relax this requirement, wdyt @jonasfj?

I forget, but as I recall we had a good reason for this logic.


> I'd be happy to upload documentation along with the package if there was a way to do so.

I don't think we want to allow that... Hmm, I wonder if maybe using `dartdoc_options.yaml` can reduce the time and number of files created by dartdoc:

https://pub.dev/packages/dartdoc#advanced-features

Perhaps `exclude` and/or add `nodoc` to a few things that aren't worth documenting.

You can try running dartdoc on the package locally, I'm guessing it'll be slow... but reducing the amount of source code to be documented might help fix some of that.
