### ISSUE TITLE
Remove uploader emails from pub.dev

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4858]
Since we have successfully introduced publishers, emails is no longer the only form of supported identity on pub.dev

So let's try to stop displaying the "uploader" emails.

**Comment by jonasfj** [comment]
Now we should also simply say "publisher: unknown", when there is uploaders are used:

![4A2bnis9sWz2nLa](https://user-images.githubusercontent.com/149732/120998983-e5370500-c788-11eb-88ba-33db7de8610b.png)

**Comment by mzdm** [comment]
But how do you search now for all packages made by the same author? It was very intuitive that you could just click on the email address. And when I saw Unknown status I thought that the package was compromised / not validated.
