### ISSUE TITLE
Over-application of "DART 2 INCOMPATIBLE" label

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/pub-dev#4860]
(Split out of https://github.com/flutter/flutter/issues/84109)

httpss://pub.dev/packages/responsive_sizer/versions/3.0.1 is marked as "DART 2 INCOMPATIBLE". Looking at the change, it appears that this is the result of a bad search/replace on the package version that resulted in the SDK constraint changing from

```
 sdk: '>;=2.12.0 <3.0.0' 
```

to

```
sdk: '>=2.12.0 <3.0.1'
```

The latter is obviously a very bad idea, and pub should warn about it (which maybe it did and the author ignored it), but it's not incompatible with Dart 2; the use of that message actively confused the package author about what was wrong.

**Comment by isoos** [comment]
The current logic, which originates from the Dart 1->2 migration times defines Dart2 package as:
- has an SDK constraint
- supports some of the `>=2.0.0 <3.0.0` range
- does not support any of the `>=3.0.0` range

The `'>=2.12.0 <3.0.1'` constraint enabled `3.0.0`, therefore it got `false` on the last one.

Maybe we could have an extension to the above rule: if the **min SDK constraint** is `>=2.0.0 <3.0.0` we treat it as Dart2-compatible, regardless of the upper bound. /cc @mit-mit @jonasfj
