### ISSUE TITLE
accidentially uploaded get_it_hooks 1.0.1 with wrong Version number

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/pub-dev#4893]
Hi,

I somehow messed up this morning my Versionnumber in my pubspec file.
Could you please remove 1.0.1? The correct one 2.0.1 is already published.

Thanks
Thomas

**Comment by isoos** [comment]
As the [policy page](https://pub.dev/policy) describes, please contact support@pub.dev with the details. However, in this case I see no harm keeping it around, as you we jumping from 0.9 -> 2.0 without any 1.0.*, no client will be confused with the versions.
