### ISSUE TITLE
Got stuck with no access to my publisher

### ISSUE THREAD

**Issue by natanelyoung** [dart-lang/pub-dev#4894]
## Got stuck with no access to my publisher
 * After creating a publisher, I removed then recreated the email address on gsuite, this locked me out of my publisher.
 * I can no longer access my publisher - even though I have access on Google search console with the same account
 * Here's the link to the publisher: https://pub.dev/publishers/bageldb.com/packages

**Comment by isoos** [comment]
Please contact `support@pub.dev` with the details. There may be a delay because of holidays, but someone should reply eventually.

We identify users based on the oauthUserId, which may have changed when you've changed and recreated the email. Curious: why did you do that?

**Comment by natanelyoung** [comment]
@isoos we made changes in the organisation - and had to remove the account. Upon realising the issue in pub.dev we quickly tried to open the account again, which didn't work
