### ISSUE TITLE
Issue publishing package with Github Actions

### ISSUE THREAD

**Issue by muhammadidrees** [dart-lang/pub-dev#4910]
I've set up a GitHub action following the [guide](https://birju.dev/posts/publish-your-flutter-package-using-github-actions/). It has been working fine till my current release of [my package](https://github.com/muhammadidrees/bloc_rest_api).

The issue is when publishing the packages I am asked to:

```shell
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A45011&code_challenge=OIFNIz23Oli7ngQ2-h71PZ0sELZvTjrb_GSSv-bLAKw&code_challenge_method=S256&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Then click "Allow access".

Waiting for your authorization...
```

and the actions get stuck there. I tried following the link but once I select my account it redirects to a localhost link which doesn't do anything.

I am not sure how to authorize this request or bypass this when using Github actions.

Provided it was working perfectly fine before what seems to be the issue I don't understand. Furthermore, I tried uploading the package from my machine and it works without asking for authentications. I even refreshed the credential secrets just to be sure and it still not working.

Can someone please help?

Thanks.

**Comment by sigurdm** [comment]
This is not a supported workflow.

Publishing from github is something we are thinking about - but we are not there yet.
