### ISSUE TITLE
"Latest updated packages" page

### ISSUE THREAD

**Issue by harujuki** [dart-lang/pub-dev#4939]
I think this is needed to find more packages.

**Comment by isoos** [comment]
@harujuki: do you mean sorted by recently updated?

https://pub.dev/packages?sort=updated

Lower right corner in the following screenshot:
<img width="836" alt="Screenshot 2021-07-10 084946" src="https://user-images.githubusercontent.com/4778111/125154740-d4006000-e15b-11eb-9e4b-eee0e4d79c6f.png">

**Comment by harujuki** [comment]
@isoos
Yes!
I didn't know packages can be sorted by updated date
I'm sorry...
