### ISSUE TITLE
Extensions header in docs sidebar doesn't scroll the page

### ISSUE THREAD

**Issue by geisterfurz007** [dart-lang/pub-dev#4944]
* The anchor of the extensions header links to extension (no s) and thus doesn't scroll the page
 * It should be extensions (with s)
 * This is the thing I am talking about: https://user-images.githubusercontent.com/26303198/125404906-77997c80-e3b7-11eb-8851-8036110cfc1a.png

I would fix this as well but couldn't seem to find the right place in the codebase with a search for "extension", so I am not even sure if this repo is the correct place to report the issue. If it isn't, let me know!

**Comment by isoos** [comment]
@geisterfurz007: thanks for reporting this. The `dartdoc` tool lives in the following repository: https://github.com/dart-lang/dartdoc
Could you please move (or re-submit) the issue there?

**Comment by geisterfurz007** [comment]
Absolutely; sorry about that!

**Comment by isoos** [comment]
No worries, we really appreciate the help!
