### ISSUE TITLE
Suggestion: keep separate copy icon for only package name.

### ISSUE THREAD

**Issue by alishahid-github** [dart-lang/pub-dev#4952]
URL: https://pub.dev/

In Installing tab of each package, we most of the time copying the package name with its proper version name. So, main point is, there is a button which copies it along the word 'dependencies' on top of it. Which many of the times we explicitly select the package name's line and hit the copy command from keyboard.

it would be nicer if we have only a copy button of only package name

**Comment by alishahid-github** [comment]
![image_2021-07-14_203252](https://user-images.githubusercontent.com/71405228/125649700-8bc1d386-aafb-4ec0-82f9-9ae1ba7882f2.png)

**Comment by isoos** [comment]
@alishahid-github: Do you want to copy only the package name, or the `package: ^version` string?

For the package name, I think clicking on the package and hitting CTRL+C would be faster than any button. For the above string, we have another copy button for it: at the top, to the right of the title. Is that working for you?

**Comment by alishahid-github** [comment]
> @alishahid-github: Do you want to copy only the package name, or the `package: ^version` string?
> 
> For the package name, I think clicking on the package and hitting CTRL+C would be faster than any button. For the above string, we have another copy button for it: at the top, to the right of the title. Is that working for you?

package: ^version string? Yes,

yes it will be faster, 

and the current copy button, copy both two lines( one the hardcoded word 'dependencies' and the second one 'package: ^version' string. 
if the copy button copy only that particular string it would be good.

**Comment by isoos** [comment]
@alishahid-github: Have you tried this copy button?

<img width="265" alt="Screenshot 2021-07-14 181046" src="https://user-images.githubusercontent.com/4778111/125655716-3221207e-83a9-4f67-8390-19c534aee8df.png">
