### ISSUE TITLE
Host old.pub.dev

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [dart-lang/pub-dev#5007]
What do you think if the old design of pub.dev got hosted on the domain old.pub.dev?

**Comment by sigurdm** [comment]
We don't want to maintain old designs. 

We would rather like to focus our efforts on improving our current design.

If there are specifics of the new design that are causing trouble, or seems worse than their old counterparts: please open new issues for each of these and we can consider how/if we can improve the new design to be on par with the old.
