### ISSUE TITLE
DNS issue with pub.dev from Myanmar

### ISSUE THREAD

**Issue by bksubhuti** [dart-lang/pub-dev#5024]
* Explain the issue,
I need to use a vpn in order to get into pub.dev.. but it is a pain because the vpn ruins some of my phone connectivity with my computer while developing.
 need to use a vpn to get to pub.dev from Myanmar.
Please don't block it.

api.dart.dev ----works fine
flutter.dev ----works fine
Steps to Reproduce

    ...set a vpn to myanmar (haha) and see if it loads. or call me and I'll verify it.
    ...some of your other websites..okay.
    api.dart.dev ----works fine
    flutter.dev ----works fine

 * Link to screenshot.
Nothing loads so there is no screenshot to give.. 
I could show you an empty ping.. but just believe me. 
However, often people are on the old embargo for Myanmar (or new one coming), and they often forget to turn access to us back on. 

```dart
// Write example code here
```

**Comment by isoos** [comment]
@bksubhuti: for further debugging, please download and run this script, and copy-paste the output here:
https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart

**Comment by bksubhuti** [comment]
Is there a timeout on this code?  It just waits.

**Comment by bksubhuti** [comment]
Untitled-2.dart: Warning: Interpreting this as package URI, 'package:buddhist_sun/Untitled-2.dart'.
Testing host resolves...
^C
bhante@subhuntu:/mnt/Data/git/buddhist_sun/lib$

**Comment by isoos** [comment]
> Is there a timeout on this code? It just waits.

That's a new symptom, so far it was usually failing fast. I guess your ISP / country is swallowing some packages, even the ones that can make it fail fast. We should add timeouts...

As a temporary solution to access pub.dev, you could try the Chinese Flutter mirror:
```
PUB_HOSTED_URL=https://pub.flutter-io.cn pub get
```

**Comment by bksubhuti** [comment]
Ironic..but the isp (mytel) owned by "the leader" is totally open (even Facebook works) while the other Telco companies require a special vpn (not a normal ones..psiphon or 1111.  I'm stuck with mytel because Linux doesn't have special VPNs like those.  And you don't need VPN anyway.

However..  it is needed for 
 pub.dev and news.google.com (desktop only)

I do think it is a regional DNS thing.  I experienced this before with digitalpalireader.online. It was served by Microsoft and the admin was able to fix it.  (This was before the coup)
However , unlikely that pub.dev is not hosted by Google. 😇

I think that it is a DNS and server setting.

**Comment by bksubhuti** [comment]
How to set up the Chinese pin dev in vscode and AS?

**Comment by bksubhuti** [comment]
pub get works without vpn.. so I guess I'll just use the mirror site for getting the information.

**Comment by isoos** [comment]
In #5025 I'm adding timeouts to the script. Could you also run
https://github.com/dart-lang/pub-dev/blob/a77e802191d658a1dcb17aa329e401a9b814f884/app/bin/tools/check_domain_access.dart ?

**Comment by isoos** [comment]
Copying the output from [the PR](https://github.com/dart-lang/pub-dev/pull/5025#issuecomment-900049691):

```
bhante@subhuntu:/mnt/Data/git/buddhist_sun$ dart run lib/Untitled-1.dart
lib/Untitled-1.dart: Warning: Interpreting this as package URI, 'package:buddhist_sun/Untitled-1.dart'.
Testing host resolves...
- pub.dev IPv4 resolve and connect succeeded: 0 / 4
- pub.dev IPv6 resolve and connect succeeded: 0 / 4
- pub.dartlang.org IPv4 resolve and connect succeeded: 1 / 1
- pub.dartlang.org IPv6 resolve and connect succeeded: 0 / 1
- storage.googleapis.com IPv4 resolve and connect succeeded: 6 / 6
- storage.googleapis.com IPv6 resolve and connect succeeded: 0 / 4
Testing one connection per request...
Unhandled exception:
TimeoutException after 0:00:15.000000: Future not completed
bhante@subhuntu:/mnt/Data/git/buddhist_sun$ 
```

**Comment by bksubhuti** [comment]
sorry.. clicked on the wrong item...  I guess that if I have problems.. it is an ipv6 compatibility issue?

**Comment by isoos** [comment]
@bksubhuti: the site should work with IPv4 just fine, however you can't resolve the `pub.dev` domain. As a workaround, could you try to use the Google public DNS servers (e.g. 8.8.8.8)? https://developers.google.com/speed/public-dns/docs/using

**Comment by isoos** [comment]
@bksubhuti did you have any success with different DNS settings?

**Comment by bksubhuti** [comment]
I ha e not been able to get DNS to work on Ubuntu.  It loads nothing when I do it.  I have been using the china mirror.
However..fyi.  The Chinese mirror does not allow likes or logon.

**Comment by sigurdm** [comment]
Not sure we can do much more. Closing for now.
