### ISSUE TITLE
Idea : Gallery

### ISSUE THREAD

**Issue by ehabme** [dart-lang/pub-dev#5029]
URL: https://pub.dev/
Hello,
I'm Dart/Flutter User , and i see most of Developer ask for : Which Component for Do that [screen shot] ? 
So , i think if you can make gallery for widget ,, its will be good idea because it will help Developers to find there needs quickly.

thanks

**Comment by jonasfj** [comment]
We have been thinking about something like this, filed as:
https://github.com/dart-lang/pub-dev/issues/5092
