### ISSUE TITLE
Repository link isn't honoring repository entry in pubspec.yaml

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/pub-dev#5060]
For the package [`snippets`](https://pub.dev/packages/snippets), there is this line in the [pubspec.yaml](https://github.com/flutter/assets-for-api-docs/blob/master/packages/snippets/pubspec.yaml):

```
repository: https://github.com/flutter/assets-for-api-docs/tree/master/packages/snippets
```

But on the pub.dev page for it, it is linked to [https://github.com/flutter/flutter](https://github.com/flutter/flutter) instead.

Shouldn't it be pointing to the repository linked in the pubspec?

**Comment by gspencergoog** [comment]
Huh. Well, now it works.  When I filed this issue 2 hours ago, the "Repository (GitHub)" link took me to flutter/flutter instead of the right location. I just tried it again, though, and it now takes me to the right place.

Perhaps there was a recent site update?

**Comment by gspencergoog** [comment]
Or maybe my re-publishing of the package updated it?

**Comment by creativecreatorormaybenot** [comment]
@isoos Check the link from my issue: https://pub.dev/packages/snippets/versions/0.2.3

In this version, the link does not work.

**Comment by isoos** [comment]
@creativecreatorormaybenot: for `0.2.3`, the `pubspec.yaml` has only a single `homepage: https://github.com/flutter/flutter`. pub.dev is linking to it correctly.
