### ISSUE TITLE
Issue on the pub.dev policy

### ISSUE THREAD

**Issue by yivanscreations** [dart-lang/pub-dev#5074]
URL: https://pub.dev/policy

In the policy, under Name Squatting, item 1 states:

> Locate the email of the publisher, as shown in the details pane on the package page on pub.dev.

However, as per #4858, emails are no longer shown in the details pane. Heck, there is no details pane anymore. We cannot locate the email of the publisher at all.

**Comment by sigurdm** [comment]
I guess we can do 1 rather easily as a stop-gap measure.
We want to update the https://pub.dev/policy 

@isoos do you think making a contact form would be hard?

**Comment by sigurdm** [comment]
> I think this should be authenticated users so we have a valid Reply-To: header.

That sounds good!

> rate limiting at minimum

Yeah - I guess we don't have to support many emails per day.

> possibly also an opt-out.

I think we want package authors to be reachable - in worst case the package-authors could set up a filter on their own side.
