### ISSUE TITLE
Move "dependencies:" word out of the copy section

### ISSUE THREAD

**Issue by itspersie** [dart-lang/pub-dev#5081]
Whenever we need to install any dependencies we simply need the dependency name along with the version so whenever we press the copy to clipboard button it should only copy the name and version.

![image](https://user-images.githubusercontent.com/56320328/132244227-5698c93a-199c-4732-9c55-4e3dd19d8810.png)

copy button should work like this:-

"provider: ^6.0.0"

currently, it's working like this:-

"dependencies:
  provider: ^6.0.0"

[https://pub.dev/packages/provider/install](url)

**Comment by isoos** [comment]
@itspersie: there is another place where you can have the `<pkg>: ^<version>` string copied to clipboard: on the package page, hover over the title (`<pkg> <version>`), and to the right a copy icon appears. Clicking on that will copy the string.

![image](https://user-images.githubusercontent.com/4778111/132245382-bc091e90-bea5-4faf-aa27-261dd0b37d34.png)
