### ISSUE TITLE
flutter pub publish is now returning html instead of allowing upload

### ISSUE THREAD

**Issue by jhancock4d** [dart-lang/pub-dev#5096]
URL: https://pub.dev/my-packages

Until about 30 minutes ago I was able to publish packages without issue. Now I can't publish anything and get back the home page from flutter pub publish.

No version change of flutter (worked fine with 2.5.0 before)

Only thing I noticed is that for one package that it accepted out of the 8 that I maintain which we're updating this morning because of improvements in Dart 2.14 and Flutter 2.5, it refused a bunch of times saying that the package was too large. It look a while to diagnose why that was because there are no assets, and it turned out to have to flutter clean on the example project and then it accepted the upload.

Note: dart pub publish works fine.

**Comment by sigurdm** [comment]
Can you give more details about the folder structure of your packages (are they in a mono-repo sharing a parent .gitignore?)

In that case this is probably a duplicate of: https://github.com/dart-lang/pub/issues/3102 - the workaround would be to copy the parent .gitignore into each package or publish with dart 2.13...)

**Comment by jhancock4d** [comment]
It's a mono-repro and yes, shared .gitignore. Closing.
