### ISSUE TITLE
Support Flutter 2.5

### ISSUE THREAD

**Issue by tiloc** [dart-lang/pub-dev#5097]
I have updated my package `faiadashu` to use Flutter 2.5.0, and it completely fails on the scoring, as pub.dev can only support Flutter 2.2.3.

**Comment by isoos** [comment]
@tiloc we will release a new pub.dev version next week, updating to Flutter 2.5.0 SDK. The scoring will be re-run and it should fix itself.

**Comment by tiloc** [comment]
Works now
