### ISSUE TITLE
In android，using screen_brightness is OK，but In iOS，there is a lack

### ISSUE THREAD

**Issue by niumj** [dart-lang/pub-dev#5098]
URL: https://pub.dev/packages/screen_brightness

In android，using screen_brightness is OK，but In iOS，there is a lack。when leave the page, sencon go to the page, the last setting brightness is lost. How can I do?need your help.

- [ question]

**Comment by sigurdm** [comment]
Please ask in the issue tracker of: https://github.com/aaassseee/screen_brightness/issues/new
