### ISSUE TITLE
There is a mistake in code sample

### ISSUE THREAD

**Issue by IBugraGezer** [dart-lang/pub-dev#5100]
URL: https://pub.dev/packages/android_alarm_manager_plus

this code:
```
static void printHello() {
  final DateTime now = DateTime.now();
  final int isolateId = Isolate.current.hashCode;
  print("[$now] Hello, world! isolate=${isolateId} function='$printHello'");
}
```
should have been:
```
void printHello() {
  final DateTime now = DateTime.now();
  final int isolateId = Isolate.current.hashCode;
  print("[$now] Hello, world! isolate=${isolateId} function='$printHello'");
}
```

**Comment by jonasfj** [comment]
This is the issue tracker for the `pub.dev` website, we don't not author all packages on pub.dev

Please use the repository link:

![ABicoqkwjrR59oq](https://user-images.githubusercontent.com/149732/133395144-6668cece-3e48-4564-98fc-a0c287037461.png)
