### ISSUE TITLE
ı cant sign in

### ISSUE THREAD

**Issue by teknotok** [dart-lang/pub-dev#5151]
URL: https://pub.dev/

<Describe your issue or suggestion here>

**Comment by CCXXXI** [comment]
Me too. But I finally found that I am already signed in by liking some packages and visiting https://pub.dev/my-liked-packages . It's just a bug about the navbar.

**Comment by RobinFarmer** [comment]
I have the same issue.

**Comment by isoos** [comment]
Yes, I can confirm, this is a nav-bar issue. We are looking into fixing it...

**Comment by sigurdm** [comment]
I have rolled back to our previous deployment while we deploy the fix.

**Comment by sigurdm** [comment]
We have deployed a fix - manually confirmed logging in works.
