### ISSUE TITLE
The flutter_tex version page takes way too long to load

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#5171]
https://pub.dev/packages/flutter_tex/versions takes >5 secs to load

And seemingly it doesn't get cached.

**Comment by isoos** [comment]
Related: `pub` client sends `"accept-encoding": "gzip",` header, we should cache and send the gzipped content.

**Comment by isoos** [comment]
This version page, and potentially other pages are always slow because we are serving them uncached for signed-in users.
We'll need to either rewrite the page rendering to enable cached content parts, or create a cached data object for the versions list too.

**Comment by isoos** [comment]
I think this has been fixed now.
