### ISSUE TITLE
Core libraries look very "empty" in search results

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#5214]
I suggest two changes:

* Add package descriptions: Just use the first paragraph of text from the core lib
* Add a 'Core library' tag (similar to the 'Null safety tag')

![Screen Shot 2021-10-27 at 10 36 15](https://user-images.githubusercontent.com/13644170/139030755-0ea40ce3-6339-4392-8f65-7d08abd3b680.png)

**Comment by elbeicktalat** [comment]
Nice idea,
Of course they will be have no pub points or popularity indication.
