### ISSUE TITLE
Build a category classification system on pub.dev

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5219]
Allowing users to browse and filter packages by category.

**Comment by Simran1604** [comment]
Hello !
I'm interested to work on this issue. May I get some help?

**Comment by mit-mit** [comment]
Low fidelity UI mock:
![Screen Shot 2022-03-08 at 13 58 55](https://user-images.githubusercontent.com/13644170/157242760-57b806c0-5831-4cd2-9003-dac9fa0112ca.png)

**Comment by Ehesp** [comment]
Not sure if this is planned / in scope, but it'd be good if packages were searchable by specific categories too (also on the public API).

**Comment by leighajarett** [comment]
+1 This came up in research sessions at Flutter Vikings and it resonated with several developers

**Comment by jonasfj** [comment]
This has shipped on pub.dev, see https://pub.dev/topics
