### ISSUE TITLE
Add ability to view non-flutter packages

### ISSUE THREAD

**Issue by mnordine** [dart-lang/pub-dev#5247]
`pub.dev` has become a bit of a minefield with Flutter-related packages. It distracts from finding agnostic dart packages. For example, just look at the recently updated packages. You'll see many Flutter-related packages. I have no interest in Flutter whatsoever, but as far as I can tell, there's no way for me to filter out these packages. There should be.

**Comment by isoos** [comment]
@mnordine: `https://pub.dev/dart/packages` should give you packages that work on the Dart SDK. Is that what you are looking for, or exclusively Dart SDK packages, that don't work on Flutter at all (although not sure why one would look for those).

**Comment by mnordine** [comment]
Sorry if I wasn't clear. Conceptually, it's very simple. I don't use Flutter. On `pub.dev`, I want to a way to hide any Flutter-related packages, *everywhere* on the site.

**Comment by isoos** [comment]
@mnordine: could you please give us some examples of searches? E.g. starting from the above url, where you see a package that is Flutter-only but still showing up?

**Comment by mnordine** [comment]
Sure, here's an example, looking at the latest updated packages: https://pub.dev/packages?sort=updated

**Comment by isoos** [comment]
You should (a) either go to the Dart tab, or (b) use the URL above to go the Dart tab (see the upper left corner in the screenshot:)
![image](https://user-images.githubusercontent.com/4778111/140752958-65666f98-d36b-4a96-9794-6f110276dabc.png)

As you can see in the lower right corner, you can still order by recently updated. For reference, here is the URL for the above:
https://pub.dev/dart/packages?sort=updated

**Comment by mnordine** [comment]
Right, that's the first thing I tried, but it seems a lot of Flutter packages still show up, for instance: https://pub.dev/packages/protospacemesh

How does pub "know" it's a Flutter package?

**Comment by mnordine** [comment]
Is there any way I could omit packages `pana` tagged with `sdk:flutter`?

**Comment by isoos** [comment]
Yes, you can type `-sdk:flutter` in the search query, but it may not be the result that you are looking for...
https://pub.dev/packages?q=-sdk%3Aflutter

**Comment by isoos** [comment]
Oh, we have `-is:plugin` now (still experimental, may change in the future), which may be closer to what you are looking for:
https://pub.dev/packages?q=-is%3Aplugin

**Comment by sigurdm** [comment]
Do we need anything more here, or can we close this issue?

**Comment by mnordine** [comment]
I tried `-sdk:flutter` and I get for example: https://pub.dev/packages/flutter_gen
I tried `is:plugin` and I get for example: https://pub.dev/packages/incrementally_loading_listview

They seem better than nothing, though. I'm not sure the best way to accomplish this via package analysis. Maybe categories would help, but even then, it'd be up to the package author.

**Comment by isoos** [comment]
Closing as we can't really add much to this request at this point. `sdk:dart -sdk:flutter` should cover most of the packages that are nothing to do with Flutter (although they may be...).
