### ISSUE TITLE
Facebook Ads

### ISSUE THREAD

**Issue by abk57760** [dart-lang/pub-dev#5260]
URL: https://pub.dev/packages/facebook_audience_network/versions/1.0.0-nullsafety.0

<Describe your issue or suggestion here>
It is not working 
it is using a depreciated version of android embedding.

**Comment by isoos** [comment]
@abk57760: this issue tracker is for the pub.dev site, and not for individual packages. Please report such bugs to the package's issue tracker, in this case: https://github.com/dreamsoftin/facebook_audience_network/issues
