### ISSUE TITLE
Cannot create publisher even with domain ownership verified

### ISSUE THREAD

**Issue by GP4cK** [dart-lang/pub-dev#5283]
URL: https://pub.dev/create-publisher

I'm trying to create a verified publisher. I've verified the domain ownership by adding a TXT record (see the first screenshot) but I keep getting the verification error (second screenshot).
What else can I do?
Thanks for your help.

![image](https://user-images.githubusercontent.com/2680243/142748108-3a5037bd-40e6-47bc-9ab2-d813cf4f17b6.png)
![image](https://user-images.githubusercontent.com/2680243/142748110-78dd874a-9470-4096-9bfb-61947d9e4be2.png)

**Comment by isoos** [comment]
@GP4cK: there seem to be publisher creations today, so I think your issue may be temporary. Could you try it again, maybe it is a cache issue? Also: please make sure that the DNS verification is not for a subdomain.

**Comment by GP4cK** [comment]
Still no luck :'(. And I confirm that the DNS verification is for the root domain.
I see however that there are 3 TXT records starting with `google-site-verification=...`. Could that be the reason?

**Comment by isoos** [comment]
Based on the logs it seems like that we query the search console successfully, but the returned list doesn't have the domain + `siteOwner` access right combination. Couple of things that you could checks:
- Are you using the same account on pub.dev and on the search console? (Was it deleted and re-created at any point?)
- Do you have the `siteOwner` role of the domain in search console? IIRC if you have only delegated access, it may be a different role.

**Comment by GP4cK** [comment]
> Are you using the same account on pub.dev and on the search console?

That was the issue. I didn't see that the account was automatically changed when I got redirected to the search console.
It gave me a new TXT record and I was able to create the verified publisher almost instantly.
Thanks a lot for your help!
