### ISSUE TITLE
 error: lambda expressions are not supported in -source 7

### ISSUE THREAD

**Issue by AnthonyRootdevs** [dart-lang/pub-dev#5297]
URL: https://pub.dev/packages/startapp_sdk/example

startapp/flutter/sdk/StartAppSdkPlugin.java:88: error: lambda expressions are not supported in -source 7
                        new StartAppViewFactory<>(() -> new StartAppFlutterBanner(bannerAdKeeper)));
                                                     ^
  (use -source 8 or higher to enable lambda expressions)
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':startapp_sdk:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by sigurdm** [comment]
Please report issues with specific packages to their maintainer.

This is the issue tracker for the pub.dev site itself.
