### ISSUE TITLE
Website sign-in does not work

### ISSUE THREAD

**Issue by olegsv** [dart-lang/pub-dev#5302]
URL: https://pub.dev/

After clicking on the "Sign in" link, I see a pop-up window that displays a list of Google Mail accounts. After I choose an account, the window disappears but the "Sign in" link stays.
Browser: Chrome OS: Ubuntu Linux 20.04
Firefox & Chromium are OK. Cleaning cookies and local storage had no effect.

**Comment by isoos** [comment]
Are you using any content blocker? They may interfere with the login flow...

**Comment by olegsv** [comment]
> Are you using any content blocker? They may interfere with the login flow...

I've verified this with  AdblockPlus and "Privacy Sandbox trials" dIsabled before reporting  ...

**Comment by olegsv** [comment]
Sorry, my bad - "Privacy Badger" has blocked the sign-in.
