### ISSUE TITLE
Pub publish "insufficient permissions error" after attempt to publish with missing LICENSE

### ISSUE THREAD

**Issue by iLnaar** [dart-lang/pub-dev#5305]
I got exactly the same problem as in [#4298](https://github.com/dart-lang/pub-dev/issues/4298) issue
I forgot to attach the license file and tried to publish the package. This resulted in an error:
```
dart pub publish
Publishing string_extension 1.0.0 to https://pub.dartlang.org:
|-- CHANGELOG.md
|-- README.md
|-- TEMP
|-- analysis_options.yaml
|-- example
|   '-- string_extension_example.dart
|-- lib
|   |-- src
|   |   '-- string_extension_base.dart
|   '-- string_extension.dart
|-- pubspec.yaml
|-- string_extension.iml
'-- test
    '-- string_extension_test.dart
Package validation found the following error:
* You must have a LICENSE file in the root directory.
  An open-source license helps ensure people can legally use your code.
Sorry, your package is missing a requirement and can't be published yet.
For more information, see: https://dart.dev/tools/pub/cmd/pub-lish.
```
I added the LICENSE file and tried again. But there is no publication. An error is thrown: not enough rights to download _new versions_ of the package. At the same time, there is no package in my "pub.dev" account. I have only one account and no rights settings have changed there.
```
dart pub publish
Publishing string_extension 1.0.0 to https://pub.dartlang.org:
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- analysis_options.yaml
|-- example
|   '-- string_extension_example.dart
|-- lib
|   |-- src
|   |   '-- string_extension_base.dart
|   '-- string_extension.dart
|-- pubspec.yaml
|-- string_extension.iml
'-- test
    '-- string_extension_test.dart

Publishing is forever; packages cannot be unpublished.
Policy details are available at https://pub.dev/policy

Do you want to publish string_extension 1.0.0 (y/N)? y
Uploading...
`ilnarwh@gmail.com` has insufficient permissions to upload new versions of package `string_extension`.
```

**Comment by isoos** [comment]
@iLnaar: there is already a package that is `string_extension` - and based on the git repository it links to, it may not be the same as yours. The insufficient permissions message comes because the account that published the existing package is different from yours.

**Comment by isoos** [comment]
The existing package page: https://pub.dev/packages/string_extension
Was this prior published version yours?

**Comment by iLnaar** [comment]
Really. This is someone else's package with the same name. I didn't think to check it out. I assumed that if the names of the packages match, a message should be displayed that such a package has already been published through another account.
For example, in my case, it would be more informative to show something like:
```
Uploading...
`ilnarwh@gmail.com` has insufficient permissions to upload new versions of package `string_extension`.
The package may have been published by a different publisher.
Existing package: https://pub.dev/packages/string_extension
Repository (GitHub): https://github.com/Soufiene-Hmila/string_extension
```
