### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by abdallahboucedraya** [dart-lang/pub-dev#5349]
URL: https://pub.dev/

Add notifications for packages to get a notice when the package has been updated.

**Comment by sigurdm** [comment]
We are currently working on pub-dependabot integration! https://github.com/dependabot/dependabot-core/pull/4510 that should solve a lot of the use-cases for this.

But I agree some other kind of notification system would be neat.

**Comment by isoos** [comment]
Closing as duplicate of #5532.
