### ISSUE TITLE
GA analytics events for use of filters

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5368]
Let's add a `data-ga-click-event` attribute on search filter buttons, so that we can check if they are being used.
I think we are using client side updates with `History.pushState`, but it's unclear to me if GA will pick up those page changes.
But even if it does, it would be nice to know if the buttons are useful, and if the "advanced" section is frequently unfolded, etc.

![image](https://user-images.githubusercontent.com/149732/146345944-c4a5808d-1fc4-4275-b08d-4b105310381b.png)

cc @jayoung-lee

**Comment by isoos** [comment]
It looks like we could pick these up via GTM triggers:
https://support.google.com/tagmanager/answer/7679322?hl=en

Would that work? I guess it is more reliable to have a single listener on these events than us trying to trigger it every time.

**Comment by jayoung-lee** [comment]
Will the clicks on the filter items change the URL?

Actually, even if it does, I think [measuring the interaction events](https://developers.google.com/analytics/devguides/collection/analyticsjs/events) will provide more straightforward workflow & data for us. 

(If we use GTM, we need to test triggers every time the filter section is updated, and we also need to clean up the data to see what each before-after combination means.)

**Comment by isoos** [comment]
> Will the clicks on the filter items change the URL?

Yes, changes the URL and also calls `pushState`.

Events would work too, any special category/action/label for them?

**Comment by jayoung-lee** [comment]
> Event category is always 'click' for all the clicks.

It looks like we're just using event *action* to distinguish different events (Analytics 360 > Behavior > Events). Event *category* is always 'click' for all the clicks. 

What about using: 'filter-platform-[platform_name]', 'filter-sdk-[sdk_name]', etc?

**Comment by isoos** [comment]
I think this should be active now. @jayoung-lee could you please confirm that this is working as expected?

**Comment by jayoung-lee** [comment]
@isoos Yes I can see the `filter-*` events flowing in. Thank you!
