### ISSUE TITLE
Is it possible to rename my package!

### ISSUE THREAD

**Issue by msayed-net** [dart-lang/pub-dev#5372]
Hello,

Could I change my package name, Keeping everything else in place...

Thank you

**Comment by isoos** [comment]
@msayed-net: As a default rule we treat packages as immutable (to a degree, e.g. obvious abuses will be removed), and don't change the name or the content of the package. You can publish a new version of the package with a new package name and continue publishing it that way. You may also mark the old package name as discontinued on the admin page, and set the replaced-by field pointing to the new package.

**Comment by msayed-net** [comment]
I searched the web for the mentioned field replaced-by and did not find anything even at [Dart Pubspec](https://dart.dev/tools/pub/pubspec), how to use that, please.

**Comment by parlough** [comment]
I believe it shows up in the admin tab once you have marked a package as discontinued.

I've opened an issue to document this within the dart.dev website: https://github.com/dart-lang/site-www/issues/3750
