### ISSUE TITLE
show alert after using a `discontinued` package

### ISSUE THREAD

**Issue by maxzod** [dart-lang/pub-dev#5378]
after running `pub get` show alert that package `X` is `discontinued`

**Comment by jonasfj** [comment]
Please refile in https://github.com/dart-lang/pub, and double check that this isn't already the case with latest version of the Dart SDK.

I'm pretty sure it'll actually print a warning of sorts, it might take 2 days for it to propagate through caches (if pubspec.lock already exists, and nothing needs to be downloaded).
