### ISSUE TITLE
Can not add uploader when transfer to publisher

### ISSUE THREAD

**Issue by gsmlg** [dart-lang/pub-dev#5379]
* Explain the issue,
 * Using bullet points!
 * Link to screenshot.

When try to add uploader, run 

```
dart pub uploader add myemail@gmail.com
```

got

```
Package "package" is owned by publisher "publisher". Updating the uploaders is not permitted.
```

The 'myemail@gmail.com' is admin of publisher, but return not permitted.

**Comment by isoos** [comment]
@gsmlg: There is no mixing between publisher admins and package uploaders. Once a package is transferred to a publisher, the admins of the publisher can upload new versions to it, prior uploaders are removed, and uploaders cannot be added to it.

You may invite new admins to your publisher if you want to allow them to upload a new version. The upload permission for admins applies to all packages under the publisher.

**Comment by gsmlg** [comment]
@isoos 
The problem is I can not get `~/.pub-cache/credentials.json` created.
I need tokens from  `~/.pub-cache/credentials.json` and using them in CI.

**Comment by isoos** [comment]
@gsmlg: I'm not sure: why are the tokens relevant here? Are you trying to publish a new version from CI? That will be unrelated to the error message above, which says that the package is under a publisher now.
