### ISSUE TITLE
Got socket error trying to find package flutter_template_images at https://pub.dartlang.org.

### ISSUE THREAD

**Issue by KimSeokChae** [dart-lang/pub-dev#5383]
URL: https://pub.dev/help

Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ...
Expanding downloaded archive...
Building flutter tool...
Running pub upgrade...
Got socket error trying to find package flutter_template_images at https://pub.dartlang.org.
Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Connection to https://pub.dartlang.org. work fine.

It seems server problem.

flutter doctor is not working too. endless loop.

Solve this problem. thank you.

**Comment by isoos** [comment]
@KimSeokChae: What is your OS, Dart/Flutter version, country and ISP?

Please download and run this script, and report its output here to debug potential network issues:
https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart

Please also run the command with the verbose option (e.g. `flutter pub get -v` or `flutter pub upgrade -v`), and copy its output here (maybe an attachment .txt).
