### ISSUE TITLE
Support automated publishing from CI

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5388]
TODO: design out this should work, probably we can use OIDC from Github Actions, and similar features from Gitlab.

**Comment by Coronon** [comment]
Hi there, I would love this feature! The fact that Dart does not support easy automated deployment is surprising.

The only thing I am wondering about is why [pub.dev](https://pub.dev) does not support [`dart pub token`](https://dart.dev/tools/pub/cmd/pub-token)? If that's already part of the `pub` command, wouldn't it make (and be easiest) sense to just use that?

**Comment by danielgomezrico** [comment]
This would be nice to have, I was trying to automate the deploy on our library https://github.com/la-haus/iterable-flutter/runs/6353878819?check_suite_focus=true using my personal credential.json but it throws an error:

> Pub needs your authorization to upload packages on your behalf.

Based on this it is not possible to automate the library deployment from the CI? it can only be done from the developer machine?

**Comment by Coronon** [comment]
You can deploy with your `credentials.json`, its just a little ugly - see [here](https://github.com/Coronon/flutter_octicons/blob/master/.github/workflows/gen_icon_font.yaml) (a recent project of mine).

**Comment by danielgomezrico** [comment]
@Coronon I got a blocker, it says this:

```bash
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=xxxx-xxxxx.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A37523&code_challenge=xxxx-xxxxth%2Fuserinfo.email
Then click "Allow access".
```

But I haven't tried with `dart pub publish -f`

**Comment by Coronon** [comment]
> @Coronon I got a blocker, it says this:
> 
> ```shell
> Pub needs your authorization to upload packages on your behalf.
> In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=xxxx-xxxxx.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A37523&code_challenge=xxxx-xxxxth%2Fuserinfo.email
> Then click "Allow access".
> ```
> 
> But I haven't tried with `dart pub publish -f`

I really dont want to use this thread for tech support, so this is my final reply here, see my profile for my email if you need more help.

Check if the credentials.json work on your machine, if they do then you set up something incorrectly as that prompt to authenticate wouldn't come up. Again, I have a full [example](https://github.com/Coronon/flutter_octicons/blob/d27e8a5e96f0416ed219a5e6cc809fffe78f20b1/.github/workflows/gen_icon_font.yaml#L43). Remove the condition (`if`), set up the secrets in your repo and off you go :)

PS: Most issues seem to arise because people haven't figured out that the `credentials.json` file has moved to `$HOME/.config/dart/pub-credentials.json` ^^

**Comment by danielgomezrico** [comment]
Thanks for that @Coronon I will try it

**Comment by Coronon** [comment]
It seems you are talking about macOS while I am referring to linux ;)

**Comment by danielgomezrico** [comment]
@Coronon I confirm that it works! thanks for helping me

**Comment by git-elliot** [comment]
This is my workflow file - https://github.com/git-elliot/network_tools/blob/main/.github/workflows/publish.yml and script file to setup env vars - https://github.com/git-elliot/network_tools/blob/main/pub_login.sh.
But my workflow is now stuck at publishing step. I tried multiple ways, i'm not able to publish my dart package. What I'm doing wrong?

**Comment by Coronon** [comment]
@git-elliot To reiterate again: I have a full working [example](https://github.com/Coronon/flutter_octicons/blob/d27e8a5e96f0416ed219a5e6cc809fffe78f20b1/.github/workflows/gen_icon_font.yaml#L43).

**Comment by git-elliot** [comment]
@Coronon My bad that I've referenced files from my main branch. I'm adding my files from dev branch again. I've tried with this path only. 
Workflow file - https://github.com/git-elliot/network_tools/blob/dev/.github/workflows/publish.yml
Pub Env Vars setup file - https://github.com/git-elliot/network_tools/blob/dev/pub_login.sh

**Comment by Coronon** [comment]
@git-elliot You are missing the `idToken` it seems when comparing your code to _my example_

**Comment by git-elliot** [comment]
Yeah I can also see the same. But there is no idToken in my json file as I can see clearly.

**Comment by Coronon** [comment]
@git-elliot have you tried logging out and in again? Or delete your current credentials file and then log in again?

**Comment by git-elliot** [comment]
@Coronon Seems like logging out and in was the only solution to that problem. Thanks a lot. It worked.

**Comment by Coronon** [comment]
> @Coronon Seems like logging out and in was the only solution to that problem. Thanks a lot. It worked. 

Glad to hear that :)

**Comment by sigurdm** [comment]
Closing - this is done: https://dart.dev/tools/pub/automated-publishing

**Comment by cedvdb** [comment]
It's not obvious how to do it with an open source project where you'd like to enable auto publishing when a PR passes on a specific branch

**Comment by sigurdm** [comment]
@cedvdb perhaps you can find inspiration in the dart-teams "firehose" scripts: https://github.com/dart-lang/ecosystem/tree/main/pkgs/firehose

**Comment by Tienisto** [comment]
> Closing - this is done: https://dart.dev/tools/pub/automated-publishing

Unfortunately, It doesn't seem to work with Flutter packages... I have looked into the code and the `OIDC` part is missing in the `subosito/flutter-action` action. I know this action is a third-party action but any ideas?

**Comment by iamchathu** [comment]
This doesn't work with Flutter packages. We need better support for flutter packages and needs support CI to publish them.

**Comment by fadlurahmanfdev** [comment]
> You can deploy with your `credentials.json`, its just a little ugly - see [here](https://github.com/Coronon/flutter_octicons/blob/master/.github/workflows/gen_icon_font.yaml) (a recent project of mine).

legit answer 👍 👍 👍

**Comment by sigurdm** [comment]
@jonasfj, @isoos we need to make automated publishing work with flutter packages!

**Comment by isoos** [comment]
@sigurdm: I'm a bit unsure/out-of-context here: what is the part that we need to implement/provide?

**Comment by sigurdm** [comment]
>  I'm a bit unsure/out-of-context here: what is the part that we need to implement/provide?
The current github action (dart-lang/setup-dart/.github/workflows/publish.yml@v1) for automated publication does not install flutter, but only dart, making it hard to do automated publishing.
