### ISSUE TITLE
Error with encoding linked data for packages with double quotes in their descriptions

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#5402]
![image](https://user-images.githubusercontent.com/17034/148591206-7a5d106e-a577-4d8b-ac06-d68c1a6c7a50.png)

**Comment by isoos** [comment]
Hm, interesting bug:

In the first step, we create the json-string, note the `\"`:
```
{"description":"A routing package that lets you navigate through guarded page stacks and URLs using the Router and Navigator's Pages API, aka \"Navigator 2.0\"."}
```

And in the next step we do try encode unsafe characters, but fail to do so:
```
{"description":"A routing package that lets you navigate through guarded page stacks and URLs using the Router and Navigator\\u0027s Pages API, aka \\u005c"Navigator 2.0\\u005c"."}
```

It seems that our current simple regexp will not able to deal with situations like that, we should replace `\"` prior to the encoding as a separate step.
