### ISSUE TITLE
Package showing as [UNIDENTIFIED]

### ISSUE THREAD

**Issue by gdwenjun** [dart-lang/pub-dev#5408]
The same code, one shows  ** UNIDENTIFIED **, the other is normal。
please check:
https://pub.flutter-io.cn/packages/tencent_trtc_cloud

https://pub.dev/packages/test_gavinwjwang

![image](https://user-images.githubusercontent.com/1098328/148869380-7596ac09-5c8a-41c0-83ce-f1e473d1e383.png)
![image](https://user-images.githubusercontent.com/1098328/148869412-4a591a80-42b1-420b-a20b-2c3e85e94876.png)

**Comment by jonasfj** [comment]
This is a problem in pana, I think we've identified the issue with SDK detection. This should now consistently be unidentified.
But I think we'll fix it.

**Comment by v7lin** [comment]
any news update

i use flutter create new plugin and push to pub.dev, it show [UNIDENTIFIED]

**Comment by isoos** [comment]
@v7lin: unfortunately pub.dev is behind updating analysis SDKs to the latest versions. Your package depends on `sdk: ">=2.17.1 <3.0.0"`, but the latest we've got in pub.dev production is `2.17.0`. Once we update the analysis SDKs, the package will get re-analyzed, and it will get the correct analysis and scores.
