### ISSUE TITLE
Statistics about used Dart/Flutter versions

### ISSUE THREAD

**Issue by ueman** [dart-lang/pub-dev#5414]
As a package maintainer I want to know:

- Which percentage of the users are on which Dart version
- Which percentage of the users are on which Flutter version

Ideally it would be possible to look this up for a specific package (either on the public page or the private package admin page) and for the ecosystem in general.

The former is useful when one wants to raise the Dart/Flutter version in order to get access to new APIs and features.
The latter is useful if one wants to start building a new package.

This is kinda related to https://github.com/dart-lang/pub-dev/issues/4732 and https://github.com/dart-lang/pub-dev/issues/2714

**Comment by jonasfj** [comment]
I can see this would be useful, but there are privacy concerns involved with disclosing such information.

To be honest, I'm not even really sure have the data to determine this. But in general, my feeling is that Flutter users are pretty good at upgrading to the latest version.

-----------------

I'm closing this as I don't think we'll get around to doing this.
