### ISSUE TITLE
ctrl+click not opening in new tab, when using event handler

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5420]
I'm guessing this is because we send some event to GA, or something?

![image](https://user-images.githubusercontent.com/149732/149166411-15610ea2-4bcd-4853-8a11-a31cdafe1155.png)

**Comment by isoos** [comment]
Yeah, we could probably check if the click has any key down (ctrl or cmd), and if it has, we don't prevent the default behavior and don't override the location.
