### ISSUE TITLE
diff_match_patch ^0.4.1 is forbidden

### ISSUE THREAD

**Issue by mehade369** [dart-lang/pub-dev#5422]
getting error when using  [diff_match_patch](https://pub.dev/packages/diff_match_patch) package. 

**Error:** 

```
[flutter_todos] flutter pub get
Running "flutter pub get" in flutter_todos...                   
Because no versions of diff_match_patch match 0.4.1 and no versions of diff_match_patch match >0.4.1 <0.5.0, diff_match_patch ^0.4.1 is forbidden.
So, because flutter_todos depends on bloc_test ^9.0.1 which depends on diff_match_patch ^0.4.1, version solving failed.
pub get failed (1; So, because flutter_todos depends on bloc_test ^9.0.1 which depends on diff_match_patch ^0.4.1, version solving failed.)
exit code 1
```

**Comment by mehade369** [comment]
```
mehade@manjaro ~/D/flutter_todos> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Manjaro Linux 5.10.89-1-MANJARO, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] VS Code
[✓] Connected device (2 available)

• No issues found!
```

**Comment by sigurdm** [comment]
It looks like you have a version conflict.

What is your pubspec.yaml?

**Comment by mehade369** [comment]
> It looks like you have a version conflict.
> 
> What is your pubspec.yaml?

https://github.com/felangel/bloc/blob/master/examples/flutter_todos/pubspec.yaml

Also getting the same error, with other projects that depend on `diff_match_patch ^0.4.1`
 
Current workaround!

``` yaml
dependency_overrides: 
  diff_match_patch: ^0.4.0
```

**Comment by sigurdm** [comment]
This looks very mysterious. We have not been able to reproduce locally.

Could you try running `PUB_CACHE=$HOME/tmp/pub_cache flutter pub get` to see if something in your current cache is obstructing.

Could you also try `flutter pub get --verbose` and attach the output?

**Comment by jonasfj** [comment]
> https://github.com/felangel/bloc/blob/master/examples/flutter_todos/pubspec.yaml

@mehade369 can you still reproduce this? Or was a different revision of the repository?


(please attach verbose out out from `flutter pub pub get --verbose` to a gist).

**Comment by mehade369** [comment]
Thanks everyone for responding, I have reinstalled flutter and it solved the problem.
