### ISSUE TITLE
disallow emojis in package description at publishing time

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5437]
We will not cleanup existing descriptions, but we will stop new descriptions from containing emojis...

**Comment by ayushvrma** [comment]
Hi, I'd like to take this up. I'm kind of new to open-source, would need some guidance if thats okay

**Comment by isoos** [comment]
@ayushvrma: if you wanted to take this up, this PR is very similar in both scope, function, and actual code location where this should live:
https://github.com/dart-lang/pub-dev/pull/5430

The difficulty here is to properly detect the emoji character ranges. We had this PR that started on that, but eventually got killed: https://github.com/dart-lang/pub-dev/pull/5389
