### ISSUE TITLE
Request to remove the package. Please

### ISSUE THREAD

**Issue by sarthakkgarg** [dart-lang/pub-dev#5458]
Hi team, 
I would request you to remove the uploaded library that i mistakenly uploaded to pub.dev.
As this was my first time, I was unaware of the process. I want to publish my package again with a new name. Can you delete my package from the pub search. Please?
URL: https://pub.dev/packages/xdc3dart

**Comment by sarthakkgarg** [comment]
@sigurdm please look into this.

**Comment by isoos** [comment]
Please contact support at the email address as described on the https://pub.dev/policy page.

**Comment by sarthakkgarg** [comment]
Hi,

I email to ***@***.*** regarding my package removal but i didn't get
any response. Can you please help me with this issue?
