### ISSUE TITLE
Some packages don't show any author information

### ISSUE THREAD

**Issue by magnuswikhog** [dart-lang/pub-dev#5459]
Some packages don't display any publisher information, making it look like it's an official plugin by the Dart/Flutter team. 

However,  when you click the Github link, it turns out that the repo is hosted in someones private Github account. 

Example: https://pub.dev/packages/expandable

![image](https://user-images.githubusercontent.com/38244471/151123275-bbcca4f3-c06e-4943-b8d4-63c036f4178a.png)

**Comment by isoos** [comment]
We have released a new version where we display `unverified uploader` in such cases.
