### ISSUE TITLE
Question about .rst README support

### ISSUE THREAD

**Issue by msayed-net** [dart-lang/pub-dev#5472]
Hello, 

I wonder if I can use  (.rst README) files on the pub.dev website as package README file.

Thank you.

**Comment by isoos** [comment]
We only use markdown-based readme files, and we have no immediate plan to extend it to other formats.

I'm curious: is there any structure or feature in rst that you would like to use that markdown lacks of?

**Comment by msayed-net** [comment]
No, there is no feature I need at the moment.

I was just curious what would happen If I re-documented my packages in .rst format, would it be supported on pub.dev like Github! , that's all.

**Comment by sigurdm** [comment]
We are not going to implement this.
