### ISSUE TITLE
[Feature] pub.dev must feature

### ISSUE THREAD

**Issue by firstep-official** [dart-lang/pub-dev#5479]
URL: https://pub.dev/

Guys its starting to be a mess. too many packages that do the same, some are better some are less.
you should have the option to let people attach packages to other packages the are the same.

you go into page and you like have "know similar package? report/add/attach it" then when you open a page you see what the other packages and can decide whats better for you.

**Comment by isoos** [comment]
@firstep-official: Can you share an example or two, where you've experienced this?

What do you think about conflicts: some people want to "attach", others may disagree? What if there is an overlap, but not that significant?

**Comment by firstep-official** [comment]
@isoos for example list pagination. after so many packages I checked, somehow I found this infinite_scroll_pagination which is the best implementation.

look how many there are:
https://pub.dev/packages?q=pagination
https://pub.dev/packages?q=infinite

also httpclient libraries, card swipe, carousel and many many more

"check similar content" is everywhere today, news 
i think the problem of flutter that people coming from all platforms , web , android , ios , desktop. and every community has its own name, so find something is very hard, for example im coming from android and we know infinite list as pagination list

**Comment by firstep-official** [comment]
aslo it will be really usefull to add images on the search list. most of the people put images from github so its not going to cost you.

you can add regex to find image when someone save the page and present it easily . very very useful

**Comment by sigurdm** [comment]
Is this the same as "categories"? https://github.com/dart-lang/pub-dev/issues/5219

**Comment by sigurdm** [comment]
I don't think we will pursuit this in this form. But hopefully we will provide better ways of finding related packages.
