### ISSUE TITLE
[Pub Search] - Rigorous testing on checkbox leads to misbehave

### ISSUE THREAD

**Issue by AbhishekDoshi26** [dart-lang/pub-dev#5483]
### Description
When the user checks-unchecks the checkboxes rigorously without waiting, the checkboxes start misbehaving.

Video [link](https://drive.google.com/file/d/1x84dh7IuqOMfh6Wpu1SathYtWFYnRTUL/view?usp=sharing).

### [Feature Request] 
Should we also have Package Of The Week filter?

**Comment by jonasfj** [comment]
I think this is a case of clicking faster than what the browser can load.
