### ISSUE TITLE
"Flutter favorite" should be capital "Favorite"

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5486]
![image](https://user-images.githubusercontent.com/149732/152212403-9d34b88b-5fc0-44c5-a4a6-574cebdadd5d.png)

Should be "Flutter Favorite".

(Think this is correct, because the program is name).

**Comment by csells** [comment]
Actually, legal has asked us to only use "Flutter Favorite" as title cased and not plural, so *not* "Flutter Favorites"
