### ISSUE TITLE
Cache-Control headers are missing for static file when signed-in

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5501]
This is only when signed in... URLs have content hash embedded in the URL, so we can cache it for a long time.

**Comment by isoos** [comment]
The default cache control header for static resources is private. Should we update it to public too?
https://github.com/dart-lang/pub-dev/blob/master/app/lib/frontend/handlers/misc.dart#L151-L154

**Comment by isoos** [comment]
This has been fixed.
