### ISSUE TITLE
"Flutter favorite" abuse 

### ISSUE THREAD

**Issue by lesnitsky** [dart-lang/pub-dev#5505]
[flutter_fcm](https://pub.dev/packages/flutter_fcm) is an example of a package that tries to abuse the "Flutter Favorite" badge by adding an image to the readme source. Many _real_ packages add [this image](https://raw.githubusercontent.com/rrousselGit/provider/master/resources/flutter_favorite.png) to the readme as well, however the fact that this quality indicator could be abused Is a bit disturbing.

**Comment by jonasfj** [comment]
Thanks for reporting this. We've sent out some emails and are working to resolve this.

Closing as this is a moderation issue.
