### ISSUE TITLE
API request for a method to return the package publisher

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pub-dev#5522]
I'd like an API to return some metadata about a package, including the package publisher.

I see the `https://pub.dev/api/packages/analyzer` API - that returns a json result - but I don't see the publisher info in there (for older package versions, I do see the deprecated 'author' pubspec field).

I'd like to be able to surface - as an SVG or other markdown badge - on a package's readme who the publisher is. I.e., for something like the readme for https://github.com/dart-lang/shelf_web_socket, I'd like to be able to surface that it's a `tools.dart.dev` published package.

My current thinking for how to do this is to:
- add a service to something like dartbug.com, which given a package name, can return an SVG badge w/ info about the publisher (ala https://img.shields.io/pub/v/logging.svg)
- have that service make a RESTful call to pub.dev to get the publisher info
- return to the caller an SVG representing the publisher name (and perhaps other info)

It may also be useful to expose other package metadata - like the pub points, popularity, ...

**Comment by isoos** [comment]
We have only a few API endpoints that are public, supported, and we care about them no to break them suddenly, as described here: https://pub.dev/help/api

However, if you are fine with no guarantees, [this file](https://github.com/dart-lang/pub-dev/blob/master/app/lib/frontend/handlers/pubapi.dart) has a few more, e.g.:
- `/api/packages/<package>/publisher`
- `/api/packages/<package>/score`

**Comment by devoncarew** [comment]
Thanks for the info! That works (`https://pub.dev/api/packages/path/publisher`).

> However, if you are fine with no guarantees, ...

If we do start depending on this - and there are a few different ways to solve the problem of what category a package is in and letting users know the SLO - we would want the API to continue to work. At that point I suppose I'd re-open this issue - request that the `/api/packages/<package>/publisher` API was promoted to a supported status.
