### ISSUE TITLE
<Summarize your issues here>

### ISSUE THREAD

**Issue by Mishalhaneef** [dart-lang/pub-dev#5534]
URL: https://pub.dev/packages/bottom_navy_bar

<in this package we also need container width, that will help to build flexible bottom nav bar that we want. here the value width is double.infinity, as i need to change to achieve my UI . so i changes that code inside the package. just notiiying, if its that add that would be better to use >

**Comment by sigurdm** [comment]
This issue tracker is for issues with the pub.dev site. Please report issues with the specific packages on their repositories. E.g.: https://github.com/pedromassango/bottom_navy_bar/issues/new
