### ISSUE TITLE
Abusive language in show case.

### ISSUE THREAD

**Issue by Tarkanvesh** [dart-lang/pub-dev#5555]
URL: https://pub.dev/
https://pub.dev/packages/dismissible_page

"Fuck Putin" is showing up in demo page, which personally I dont like to show case as product. 

I know Mr. Putin may be doing wrong, but Showing up in opensource community is wrong. This might be bad for Googles efforts on Flutter, Please do create abuse / report mis behavior on pub.dev

**Comment by jonasfj** [comment]
Content concerns can be reported to `support@pub.dev`, see https://pub.dev/policy.
