### ISSUE TITLE
Make `pubHostedUrl` configurable in `PanaRunner`

### ISSUE THREAD

**Issue by szakarias** [dart-lang/pub-dev#5583]
Calling `processJobsWithPanaRunner` results in packages being downloaded from pub.dev. For test purposes, we should talk to the test profile for downloading archives.

**Comment by isoos** [comment]
`pubHostedUrl` is configured in `processJobsWithPanaRunner`:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/analyzer/pana_runner.dart#L80

Possible bugs (looking into these):
- we don't have the HTTP port open
- we don't use the hosted URL to download the archive

**Comment by isoos** [comment]
Ah, yeah, unit tests do not open the HTTP port (and also do not override the primary API URL), only the integration tests using the separate fake server process.
