### ISSUE TITLE
Migrate to uniform access policy for buckets

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5586]
Created the following buckets:

* Staging:
  *   `dartlang-pub-dev-canonical-packages` (private)
  *   `dartlang-pub-dev-public-packages` (public)
  *   `dartlang-pub-dev-incoming-packages` (private)

* Production:
  *   `dartlang-pub-canonical-packages` (private)
  *   `dartlang-pub-public-packages` (public)
  *   `dartlang-pub-incoming-packages` (private)

-----------------------------------------------------

## Migration Stages

 * [x] Stage A: Use `incoming-packages` for uploading new packages.
    * We still need to look in the old bucket, because client might be in the middle of an upload while we migrate.
 * [x] Stage B: Use `incoming-packages` for uploading new packages.
    * Stop looking the old bucket for newly uploaded packages.
 * [x] Stage C: Store in `canonical-packages`
    * After upload packages are copied to `canonical-packages` before declaring package as accepted (before transaction).
      * Overwriting a tarball in `canonical-packages` is not allowed, but if the tarball exists and the datastore entity does not exist, then we let the upload proceed if the tarball is byte-to-byte equivalent to the tarball in `canonical-packages`.
    * All existing packages are copied to `canonical-packages` (using a background job, or one-off job)
    * background job syncs the canonical bucket to the `public-packages` **and** the old bucket.
       * In effect we treat the old bucket the same as we would treat the public bucket.
    * Requests are served from the old bucket.
 * [x] Stage D: Serve from `public-bucket`
 * [ ] Stage E: Stop updating old bucket and delete it.

**Comment by isoos** [comment]
This has been completed.
