### ISSUE TITLE
Need help about starting contribution

### ISSUE THREAD

**Issue by SudiptaAChy** [dart-lang/pub-dev#5634]
Hi all,
I am new to this repository. I want to contribute in this repository. Can anyone guide me where to start from. I have knowledge about DS, Algo, C++, Dart, Flutter. I have done a lot of projects using flutter.
Thank you.

**Comment by isoos** [comment]
@SudiptaAChy This may not be the easiest starting project, but we do have a page that gets you to a running local instance of the pub.dev server with local data: https://github.com/dart-lang/pub-dev/blob/master/doc/development.md

Any particular reason why you've selected this repository to contribute to?

**Comment by SudiptaAChy** [comment]
@isoos Actually the main reason is GSOC'22. Can you suggest me any easiest project for Dart? I have the mentality of learn and implement anything.

**Comment by SudiptaAChy** [comment]
@jonasfj Hi sir, would you please help me finding easiest way to contribute in Dart? Though my primary goal is GSOC'22 but I will like to contribute further as I like dart & flutter.

**Comment by jonasfj** [comment]
There is some getting started tips in: 
https://github.com/dart-lang/sdk/wiki/Dart-GSoC-2022-Project-Ideas

We can't handle a lot of small PRs and therefore haven't created a large list of easy issues.

> Can you suggest me any easiest project for Dart?

We have some harder issues like: https://github.com/dart-lang/pana/issues/1015
Or around `pub` / `pub-dev` / `pana` repositories, you're also welcome to help out the fluttercommunity repositories.
