### ISSUE TITLE
Whitelisting IP addresses

### ISSUE THREAD

**Issue by kittugit** [dart-lang/pub-dev#5637]
We try to access https://pub.dartlang.org through antifactory.  As per our policy, outgoing IPs needs to be whitelisted.  Can you provide the IP or range of IPs that is used for pub.dartlang.org.?

```dart
// Write example code here
```

**Comment by jonasfj** [comment]
At this point no, I don't think we can. I think the IPs may change from time to time.

Maybe at some point in the future.

**Comment by jonasfj** [comment]
You can allow list everything from GCP:
https://cloud.google.com/vpc/docs/configure-private-google-access#ip-addr-defaults
