### ISSUE TITLE
re-think the publisher page -- avoid embedded search

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5641]
Let's re-think the publisher page to avoid embedded search, we can make the search logic better / less complicated and more polished if we don't have to many special cases.

Maybe a publisher page is more like a category page, maybe it should be displayed like we do on the landing page... Perhaps with more boxes or something like that.

![image](https://user-images.githubusercontent.com/149732/161562365-ccf2cd8a-15cf-4ce2-a04b-d3895fbb075d.png)

**Comment by sigurdm** [comment]
Slightly more styled mock-up:
![image](https://user-images.githubusercontent.com/8613953/161774119-f1a3e1a1-a8d8-4a11-a35e-90c95e50dcf2.png)

**Comment by mit-mit** [comment]
If we go down this route, I'm pretty sure we'll end up having to support publishers picking what's listed on this page...
