### ISSUE TITLE
Link to documentation is broken<Summarize your issues here>

### ISSUE THREAD

**Issue by marcogroot** [dart-lang/pub-dev#5658]
URL: https://pub.dev/packages/firebase_app_check

When you click the link to get to the documentation it isn't real.

**Comment by isoos** [comment]
@marcogroot: this repository is for the issues related to the pub.dev site, and not for individual packages. Please use the package's issue tracker to report issues, e.g. in this case https://github.com/FirebaseExtended/flutterfire/issues
