### ISSUE TITLE
Potential spam package "uploadberhadiah"

### ISSUE THREAD

**Issue by yivanscreations** [dart-lang/pub-dev#5662]
URL: https://pub.dev/packages/uploadberhadiah

Looking at its readme shows that it is potentially just for spam. 

The package itself only contains one class `Calculator`, and that class contains one function `addOne`, and even that just adds 1 to an inputted integer. Its `example.dart` is only a basic Flutter app, not showing anything from the package. Its homepage and repository are also a 404.

**Comment by isoos** [comment]
Curios: did this show up in search, or how did you find it?

A bug here, which may be addressed better in `pana` : when we can't find the repository, we shouldn't display the link to the issues derived from the repository URL.

**Comment by yivanscreations** [comment]
I was searching for a package to handle latex (https://pub.dev/packages?q=latex) and that that package turned up as one of the results.

**Comment by jonasfj** [comment]
For future reference please report such issues to `support@pub.dev`.
