### ISSUE TITLE
Make IsFlutterFavorite accessible via pub.dev API

### ISSUE THREAD

**Issue by bryanoltman** [dart-lang/pub-dev#5665]
An endpoint to retrieve package score information exists at https://pub.dev/api/packages/{package_name}/score, but the result does not include a field indicating whether the package is a Flutter Favorite. The addition of this field might make the response look something like:

```json
{
  "grantedPoints": 130,
  "maxPoints": 130,
  "likeCount": 6380,
  "popularityScore": 0.999690928759079,
  "lastUpdated": "2022-04-08T17:53:28.592757Z",
  "isFlutterFavorite": true
}
```

**Comment by bryanoltman** [comment]
CC @jonasfj

**Comment by jonasfj** [comment]
@isoos I think we can easily support this by exposing tags in:
`https://pub.dev/api/packages/retry/score`

```js
{
  "grantedPoints": 130,
  "maxPoints": 130,
  "likeCount": 6380,
  "popularityScore": 0.999690928759079,
  "lastUpdated": "2022-04-08T17:53:28.592757Z",
  "tags": ["is:flutter-favorite", "platform:...", ...] // new field I suggest we add
}
```

I think it might be generally useful for some badging services and the likes to have access to what tags we assign.
