### ISSUE TITLE
Cannot sign into pub.dev

### ISSUE THREAD

**Issue by aeroperf** [dart-lang/pub-dev#5668]
* Attempting to sign into pub.dev for the first time to establish a developer account in order to publish a Dart package
* Using ChromeOS on Pixelbook
* I click on Sign In, get the Google Account dialog, select my gmail account I'm signed in with, get a spinner animation for a few seconds, dialog disappears, but I'm not signed in.
* 3rd party cookies are not blocked (I verified)

**Comment by isoos** [comment]
@aeroperf: there is a slight chance that the JS flow fails somewhere: could you please (1) reload the page, and if the issue still persist (2) do the sign-in with the browser's developer console open, checking the messages there?

If that flow has no issues, please contact the support via email displayed on https://pub.dev/policy, and give more details about the account, so we can track it in the logs. (E.g. `@gmail.com` or custom account, was there any migration of that account in the past?)

**Comment by aeroperf** [comment]
Thank you. The issue appears to be related only to the Pixelbook + native Chrome. I get the following warning when attempting to sign in:

```
POST https://play.google.com/log?format=json&hasfast=true&authuser=0 net::ERR_BLOCKED_BY_CLIENT
```

I have been successful signing in on mobile (Safari) and PC (Brave or Chrome). As far as I'm concerned this is not an issue and case can be closed.

**Comment by isoos** [comment]
Are you using any content blocker or any other extension?  The usual check is that if you are able to log in in a  `Guest` profile, then the issue is with one of the extensions.

**Comment by aeroperf** [comment]
Indeed. I forgot I was running Privacy Badger. With that disabled, I can log in. Thanks!

**Comment by sigurdm** [comment]
Is there any way we can detect that the problem probably comes from a blocker and warn about it?

**Comment by isoos** [comment]
> Is there any way we can detect that the problem probably comes from a blocker and warn about it?

For a certain subset of issues we were able to detect them and warn about it:
https://github.com/dart-lang/pub-dev/blob/master/pkg/web_app/lib/src/account.dart#L57-L65
