### ISSUE TITLE
When mobile phone lock screen, BackgroundMessage method sometime working, but sometime not  be triggered.

### ISSUE THREAD

**Issue by niumj** [dart-lang/pub-dev#5670]
When mobile phone lock screen, BackgroundMessage method sometime working, but sometime not  be triggered.
On Android,When mobile phone lock screen, sometime can receive messages, sometime can't receive messages.
So loged in BackgroundMessage method .
It looks like BackgroundMessage method sometime is triggered , but sometime is  not  triggered.

However On simulator, it works OK.

**Comment by isoos** [comment]
@niumj: This issue tracker is for the `pub.dev` site, and not for individual packages. Please locate the issue tracker of the package you have problem with, and report your problem there.
