### ISSUE TITLE
API documentation for Quick Actions - broken links 404

### ISSUE THREAD

**Issue by workerbee22** [dart-lang/pub-dev#5677]
URL: https://pub.dev/packages/quick_actions

Select the link to API documentation, then over there several lead to broken links, like:

https://pub.dev/documentation/quick_actions_platform_interface/latest/types_types/ShortcutItem-class.html
https://pub.dev/documentation/quick_actions_platform_interface/latest/types_types/QuickActionHandler.html

**Comment by isoos** [comment]
This looks like a bug, or maybe an unintended behavior in `dartdoc`. /cc @devoncarew @srawlins @jcollins-g 

On the [`quick_actions` library](https://pub.dev/documentation/quick_actions/latest/quick_actions/quick_actions-library.html) page we have two classes with different links:
- `QuickActions` is a relative link inside the current package, and it works as expected.
- `ShortCutItem` is an absolute link, pointing outside of the current package, and is missing.

I'd expected that the later is also inside the current package. Isn't that the case anymore?

**Comment by devoncarew** [comment]
Nothing jumps out at me immediately. Can you see when the files in question are being generated? `.../types_types/ShortcutItem-class.html` and the other; i.e., is the issue links pointing to incorrect locations, or the target files not being generated?

I'm not sure what version of dartdoc pub is on; the script reference -`../static-assets/script.js?v1` in the generated docs indicate that at least it's not on dartdoc head (it's not using the re-written front-end script).

**Comment by isoos** [comment]
> not on dartdoc head

pub.dev is on `dartdoc 5.0.1` (we usually follow dartdoc stable release within a week or two at most), and these were generated with that.

> links are pointing to incorrect locations or that the target files not being generated?

This has two issue parts:

1. The outgoing link is `https://pub.dev/documentation/quick_actions_platform_interface/latest/types_types/ShortcutItem-class.html`, while the correct link is `https://pub.dev/documentation/quick_actions_platform_interface/latest/types_shortcut_item/ShortcutItem-class.html`.

2. We are generating and outgoing link in a library page that I though only uses inside-only links. May not be an issue at all, I am just surprised by it, and we may need to check if other parts are correct (e.g. API surface extraction and linking).

**Comment by devoncarew** [comment]
Gotcha; above, it looks like the difference is `/types_types/` vs. `/types_shortcut_item/`. If this is not an isolated problem - if we're seeing it with more packages - I'd file an additional issue on the dartdoc repo w/ some idea of the prioritization.

**Comment by isoos** [comment]
I think this has been fixed, I don't see it to happen anymore.
