### ISSUE TITLE
align verified publisher icon with chrome web store

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5687]
Assuming we can find this icon somewhere in material icons.

![image](https://user-images.githubusercontent.com/149732/164503122-699c1d89-e105-4052-a99f-76f22daa809c.png)

**Comment by animator** [comment]
It actually does exist in material icons - [Link](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Averified%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048)

The name of the Icon is "Verified"

<img width="766" alt="Screenshot 2022-04-30 at 10 41 19 PM" src="https://user-images.githubusercontent.com/615622/166115528-ac63e1a1-1de8-4e12-9fb6-7c38ebc3e939.png">
