### ISSUE TITLE
Is there a test server available to use?

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/pub-dev#5694]
I seem to remember @jonasfj mentioning to me before that there is a pub.dev test server.  Is that available for non-Googlers to use?  If so, is it documented anywhere? (I don't see anything mentioned at https://dart.dev/tools/pub/publishing.)

Since "publishing [to pub.dev] is forever", it would be nice if a test server were available for general use to preview how a published packaged would be shown on pub.dev. `dart pub publish --dry-run` is useful but isn't sufficient for a number of things (e.g. to see what platforms pub.dev's automatically detects).

**Comment by isoos** [comment]
We have  server that stores everything in memory, using a fake datastore. The documentation for it is here:
https://github.com/dart-lang/pub-dev/blob/master/doc/development.md

It was designed to copy packages from the pub.dev site and use it locally, but I guess you could use it to publish you new package and trigger analysis on it. However, if you care only about the analysis part, you could just run [`pana`](https://pub.dev/packages/pana) locally, it would be easier to setup that.

**Comment by jamesderlin** [comment]
Thanks, but I was hoping for something that's already hosted and set up for anybody to use, i.e. the pub.dev equivalent of https://test.pypi.org/.

**Comment by isoos** [comment]
@jamesderlin: What is the workflow that you are looking for from such a tool? What do you want to verify?

**Comment by jamesderlin** [comment]
Well, personally I'd like to be able to preview everything first.  For example:
* Pub point score, especially since pub.dev might be using a different version of the Dart SDK than I am locally.
* To check the generated dartdoc documentation.
* To check how the metadata is presented.
* To check what supported platforms are automatically detected.
* To check that the markdown from the README.md is rendered as expected, in case it differs from how GitHub renders it.

**Comment by sigurdm** [comment]
I think this use case would be served by https://github.com/dart-lang/pub-dev/issues/4489 (staged publishing).

It is definitely a feature we want to provide eventually, but still have not got there. I cannot give you a due date.

**Comment by jamesderlin** [comment]
Yeah, a separate staging step probably would be better.

This is a direct duplicate of https://github.com/dart-lang/pub-dev/issues/3650.
