### ISSUE TITLE
[sign_in_with_apple] Package Instuctions Incomplete

### ISSUE THREAD

**Issue by workerbee22** [dart-lang/pub-dev#5695]
URL: https://pub.dev/packages/sign_in_with_apple

Procedure is incomplete when setting up for Android. Have followed the process precisely, but hit a snag not covered by the documentation.

Under the Integration step of "- Click "Next" and then "Done" to close the settings dialog" cannot be done. 

Both the "Domains and subdomains" and "Return Url" values have been provided, but Next button is no enabled (see image):

<img width="735" alt="image" src="https://user-images.githubusercontent.com/5154664/164889560-c17e73b0-2aaf-4e80-b0fc-6d1283734da1.png">

Seems to be because of the "No app id is available" ? Why might this be?

**Comment by isoos** [comment]
@workerbee22: this issue tracker is for the `pub.dev` site, and not for individual packages. Please use the package's issue tracker to report issues. You can find it in the package's infobox, in this case this looks like this: https://github.com/aboutyou/dart_packages/issues
