### ISSUE TITLE
Is there padding at the bottom missing?

### ISSUE THREAD

**Issue by nilsreichardt** [dart-lang/pub-dev#5704]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24459435/165511091-43e6988f-349b-4fd5-8fcc-69cb84821b5c.png">

https://pub.dev/packages/usage (you can pick any package on pub.dev)

Is it right that there is no padding between `README.md` and the footer?

**Comment by isoos** [comment]
Yes, this look like an untended side-effect of #5648.
