### ISSUE TITLE
Self Host & Add/Import 3rd Party Repositories

### ISSUE THREAD

**Issue by trymeouteh** [dart-lang/pub-dev#5725]
The ability to for an individual, company, group or organisation to self host their own pub package repository and the ability to add/import repositories into the pub package manager.

- Fully open sourcing the pub package server (If it is not yet open source)
- Instructions on how to self host a pub package server
- Adding the ability in the pub package manager client to add/import other repositories
- Making it distinct on what packages in the pub package manager client are from

**Comment by sigurdm** [comment]
I think this belongs better in the pub-dev issue tracker.

> Fully open sourcing the pub package server (If it is not yet open source)
> Instructions on how to self host a pub package server

The server is open source hosted on https://github.com/dart-lang/pub-dev
It is however not that easy to deploy and manage see ().

The basic [spec](https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md) for a package server is quite simple however, and implementing a basic server should not be hard.

See also https://medium.com/dartlang/hosting-a-private-dart-package-repository-774c3c51dff9 for commercially supported hosting of pub packages

> Adding the ability in the pub package manager client to add/import other repositories

You can use this syntax: https://dart.dev/tools/pub/dependencies#hosted-packages

> Making it distinct on what packages in the pub package manager client are from

Not sure I understand this request.

You can see in the `pubspec.lock` of your project where each of your dependencies are coming from.

**Comment by jonasfj** [comment]
I think most of these requests are already supported, self-hosting the service we have on pub.dev is not something I would advise, but there are others that can be self-hosted.

**Comment by trymeouteh** [comment]
> The server is open source hosted on https://github.com/dart-lang/pub-dev
> It is however not that easy to deploy and manage.

This should be made to be as easy as possible and easy to manage.

> Making it distinct on what instance a package is from

I meant to say "Making it distinct on what instance a package is from" to ensure if lets say the _pdf_ package was installed from example.com registry, that the package manager will know to get the package from example.com and not pub.dev.
