### ISSUE TITLE
Email publishers / uploaders when a packages transferred

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5737]
We should send an email when a package is transferred to/from a publisher.

This ensures that:
 * All uploaders notices that they are loosing access to the package because it's being transferred to a publisher.
 * All members of the previous publisher notices that they are loosing access to the package because it's being transferred to a publisher.
 * All members of the new publisher know that the package has arrived and now claims to be published by them.

The email is intended to allow uploaders / members to contact support@pub.dev if they believe this is malicious. We do this because we want compromised accounts to be discovered.

**Comment by sigurdm** [comment]
So the email should go to all uploaders, not just the contact info? (clarifying question)

**Comment by isoos** [comment]
At upload, we refer the users to file an issue on github: https://github.com/dart-lang/pub-dev/blob/master/app/lib/shared/email.dart#L142

Should we change all of these to contact `support@pub.dev`?
