### ISSUE TITLE
Flutter 3.0 deployment issues with packages

### ISSUE THREAD

**Issue by bosskmk** [dart-lang/pub-dev#5753]
If I distribute the package after modifying it for Flutter 3.0 and Dart 2.17 versions, a problem occurs in analysis.
Shouldn't I be distributing a package that supports version 3.0 of Flutter yet?

```dart
// Write example code here
```

**Comment by isoos** [comment]
> Shouldn't I be distributing a package that supports version 3.0 of Flutter yet?

You absolutely could publish them, there is no such restriction. pub.dev does update analysis with gated and tested releases, and those usually lag behind the stable versions of the Flutter SDK, sometimes for Dart too. Once we release such a new version, we will re-analyze all of the packages and update the score and results on the site, no further action is needed. Until then, users can access the package without issue, the analysis on pub.dev doesn't affect local use.
