### ISSUE TITLE
Add label for packages where you have to buy a license / pay for it

### ISSUE THREAD

**Issue by guenth39** [dart-lang/pub-dev#5754]
URL: https://pub.dev/help/search

<Describe your issue or suggestion here>
It would be nice if I could see directly at a glance if a package is not free, and I have to buy a license to use it. A kind of commercial flag / icon would be great.

**Comment by isoos** [comment]
Thanks for filing this! I think this is a duplicate of #4374, please upvote it so we can gauge interest!
