### ISSUE TITLE
Safari with Prevent-cross-site-tracking enabled logs out after tab is closed

### ISSUE THREAD

**Issue by develocode777** [dart-lang/pub-dev#5765]
I am using Safari with Prevent-cross-site-tracking enabled and whenever I close the tab with pub.dev and visit it again i have to sign in again. When Prevent-cross-site-tracking is disabled this doesn't happen.

**Comment by isoos** [comment]
We are using client-side Google authentication for the sign-in functionality, I guess that tracking prevention will block a cookie or two there. Using this authentication has many security benefits, and we are planning to use that for now, therefore you should either used to signing in every time, or whitelist the site and not block it on pub.dev. There is no other way around it right now.
