### ISSUE TITLE
Allow publishing from github

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#5769]

**Comment by sigurdm** [comment]
Seems to be fixed now!

**Comment by rrousselGit** [comment]
Awesome! Is there anywhere we can go to read about how to set it up?

**Comment by AlexV525** [comment]
> Awesome! Is there anywhere we can go to read about how to set it up?

https://dart.dev/tools/pub/automated-publishing might work.

**Comment by rrousselGit** [comment]
This is great, thanks!

**Comment by liodali** [comment]
is there any documentation how we can setup it or used to publish flutter packages ?
