### ISSUE TITLE
Support mathematical expressions

### ISSUE THREAD

**Issue by nilsreichardt** [dart-lang/pub-dev#5774]
This is a feature request for math support in Markdown. GitHub released math support for their Markdown:
```
When $a \ne 0$, there are two solutions to $(ax^2 + bx + c = 0)$ and they are $$ x = {-b \pm \sqrt{b^2-4ac} \over 2a} $$
```

renders to:
When $a \ne 0$, there are two solutions to $(ax^2 + bx + c = 0)$ and they are $$ x = {-b \pm \sqrt{b^2-4ac} \over 2a} $$

https://github.blog/2022-05-19-math-support-in-markdown/

Because GitHub supports this now, more and more people will use it in their `README.md` files. Therefore, it would be nice to support this also on pub.dev. 

Currently, it's not supported, as you can see in this example package: https://pub.dev/packages/nils_pub_dev_playground

I don't know if this feature in the scope of the Dart team, so feel free to close this ticket if it's not the case.

**Comment by srawlins** [comment]
It could be considered a duplicate of https://github.com/dart-lang/markdown/issues/438.

**Comment by isoos** [comment]
Right, closing it as duplicate of https://github.com/dart-lang/markdown/issues/438.
