### ISSUE TITLE
Ignoring `invalid_annotation_target` is not enabled

### ISSUE THREAD

**Issue by myConsciousness** [dart-lang/pub-dev#5775]
Hi amazing developers,

It may be known and there may already be something to deal with it, but I'm curious about the following warning in pub.dev. 

I have specified in the library's `analysis_options.yaml` to ignore this warning during analysis, but it is not enabled in Pub.dev. Or is there a special way to specify this for Pub.dev?

<img width="834" alt="スクリーンショット 2022-05-21 18 35 04" src="https://user-images.githubusercontent.com/13072231/169645548-2c02c582-64da-4c43-a1aa-672bbf670ecd.png">

**Comment by myConsciousness** [comment]
Okay maybe this is a problem with static analysis itself... as Pub.dev may want to add a lot of rules that ignore warnings when parsing and eliminate libraries that raise scores fraudulently.

**Comment by isoos** [comment]
For Dart packages pub.dev uses the core lints from here:
https://github.com/dart-lang/lints/blob/main/lib/core.yaml

We allow a few things that may be customized in the `analysis_options.yaml`, but most of the time such customizations are ignored by pub.dev. You could put `// ignore: <the-lint>` inline or the `ignore_for_file: <the-lint>` at the beginning of the library, to allow specific lints to be ignored, in this case the analysis will not complain about them.

The rational for the inlined lints is the explicit decision to put the ignores alongside the code: the developer needs to evaluate whether they are needed, and the consumer of the code is able to review it and be aware that it diverges from the community best practices.

**Comment by myConsciousness** [comment]
Thanks @isoos , it shows me a solution :)
