### ISSUE TITLE
Tighten platform search filtering so that packages that _only_ support the specified platform(s) are shown

### ISSUE THREAD

**Issue by GroovinChip** [dart-lang/pub-dev#5792]
It would be great if platform search filters showed packages that _only_ support the specified platform(s). Currently, if I select "macOS" as a search filter, I will get results from _all_ packages that support macOS and not packages that are macOS specific, thus making it harder for me to find what I'm looking for. Similarly, selecting "macOS", "Windows", and "Linux" show _all_ packages that support desktop and not desktop-only packages.

**Comment by isoos** [comment]
I don't really see much value in filters like macos-only, but if you want to have such specificity, you could do that by using the standard search query with negative filters like this one:
https://pub.dev/packages?q=platform%3Amacos+-platform%3Aandroid+-platform%3Aios+-platform%3Alinux+-platform%3Aweb+-platform%3Awindows

(You need to manually negate the `platform:x` filters that you don't like.)

**Comment by GroovinChip** [comment]
@isoos the negative filters are actually what I was originally writing my for, but I thought it would be easier understood through positive language.

Could the negative filters be added to the site as filter options? Having to do it manually in the URL each time is kind of a pain.

**Comment by isoos** [comment]
We have previously decided against such filters, and we have no current plans to add these to the UI. The search query processing will support it regardless...
