### ISSUE TITLE
i found mistake from https://pub.dev/packages/rflutter_alert

### ISSUE THREAD

**Issue by mstafamajid** [dart-lang/pub-dev#5798]
URL: https://pub.dev/
in the rflutter_alert 2.0.4  i think its wrong with installation
and wrong is in space, i learned that two space require for extracting package and i test it is working, but in installation its error in my test because of space please check this pictures

[Screenshot 2022-05-27 201535](https://user-images.githubusercontent.com/95578220/170757451-294d4c3c-95e8-4a23-8766-1cb4a4fcc9e1.png)

![Screenshot 2022-05-27 201451](https://user-images.githubusercontent.com/95578220/170757393-9bd0deec-3927-4c8d-8e6b-6beb426afcb8.png)

![Screenshot 2022-05-27 201335](https://user-images.githubusercontent.com/95578220/170757329-d19d2cd8-e05c-4f29-99a1-93bd7eb5167d.png)

**Comment by isoos** [comment]
@mstafamajid: this repository is for the pub.dev site. Please report issues for individual packages on their own issue tracker, e.g. https://github.com/RatelHub/rflutter_alert/issues in this case.
