### ISSUE TITLE
Face verification for mistplay

### ISSUE THREAD

**Issue by SusieH75** [dart-lang/pub-dev#5799]
URL: https://pub.dev/packages/veriff_flutter/install

Lights blinks on and off with Face verification I put my face in the oval push I'm ready and it blinks faster then 30 seconds later it goes back to blinking and I push I'm ready

**Comment by isoos** [comment]
@SusieH75: this is the issue tracker for the `pub.dev` site, and not for individual packages. Please contact the package publisher for issues related to their packages.
