### ISSUE TITLE
Scanner scans multiple qr codes at single time 

### ISSUE THREAD

**Issue by Inventrax69** [dart-lang/pub-dev#5801]
URL: https://pub.dev/packages/mobile_scanner

Mobile scanner scans multiple qr codes and returns even after closing app

**Comment by isoos** [comment]
@Inventrax69: this repository is for the issues with the `pub.dev` site, and not for individual packages. Please follow the repository/issue tracker link on the package page to report issues to the authors (in this case: https://github.com/juliansteenbakker/mobile_scanner/issues)
