### ISSUE TITLE
Refactor `upload_test.dart` to use API and avoid internal backend

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5807]
Should we not be able to test publishing packages against the fake-server without accessing the internal `packageBackend` in testing?

This would move our tests closer to just being integration tests. But might that not be okay?

**Comment by isoos** [comment]
Also related: https://github.com/dart-lang/pub-dev/pull/5810#discussion_r887758476

> Maybe we should tweak testWithProfile to create a global http.Client get testHttpClient that is created/closed before/after tests are running.
> That way we don't have to do: withHttpPubApiClient
> We can just make a final client = pubApiClient(bearerToken: ...);
> or something like that. I don't think we need to block this PR
