### ISSUE TITLE
Strange mouse cursor when hovering over READMEs' copy button

### ISSUE THREAD

**Issue by loic-sharma** [dart-lang/pub-dev#5813]
Hello! Hovering over a pub.dev code snippet's copy button adds a plus sign to your mouse cursor. This does not feel idiomatic: I would expect it to do the same mouse hover effect as a button (which is what GitHub's copy button does as well).

**Comment by sigurdm** [comment]
I think you are right that that icon only applies to drag-and-drop. Doing what github does (a pointing hand, cursor: pointer) seems safe...
