### ISSUE TITLE
https://github.com/cli/cli/releasessite="https://github.com/cli/cli/releases" 
 pattern='/tags/v\K[\d.]+(?=.tar.gz)'

### ISSUE THREAD

**Issue by emmrahcakir** [dart-lang/pub-dev#5814]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/github-cli/update

**Comment by isoos** [comment]
@emmrahcakir: this repository is for the `pub.dev` site. For issues related to individual packages, please visit their issue tracker to report problems.
