### ISSUE TITLE
Require LICENSE file

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5826]
We should:
 * analyze how many packages does not contain a `LICENSE` file.
 * require the license file is `LICENSE`.

**Comment by FMorschel** [comment]
Maybe warn the users that a `LICENSE` file could not be located just like the verified publisher.

**Comment by isoos** [comment]
After randomly sampling 9250 (~28%) of the packages, the following names are present (with random examples):
- `LICENSE`: 9165 **(99%)**
- `LICENSE.md`: 38 (reloadly,stagexl_toolkit,audioplayers_with_rate,data_connection_checker)
- `LICENSE.txt`: 12 (mubicon,request_extras,fledge,galileo_mustache4dart)
- `COPYING`: 11 (eric_demo,hex,blockbook,musicus_shared,tba_api_v3,save_image)
- `UNLICENSE`: 9 (flutter_android,conreality_fonts,openxr,conreality_pulse,model_viewer)
- `UNLICENSE.txt`: 2 (list_chunker,loading_container)
- `COPYING.md`: 1 (tinylog)

- missing: 20 (fluttery_cli,stream_binder,energy2d,toastd,pub_test_pkg)

Roughly 1% of the packages are not using `LICENSE` as the file name, and only 0.2% has no license file (which is a must for new uploads, these packages have no recent version).

**Comment by isoos** [comment]
the final numbers (out of 32404 packages) are not that different in percentages:
- `LICENSE`: 32122 **(99.1%)**
- `LICENSE.md`: 144 **(0.44%)** (flutter_boost,qrpc_client,memory_image_converter,flood,flutter_mix,itch_io,at_persistence_spec,libprimesieve,directory_picker,disposables)
`LICENSE.txt`: 38 **(0.12%)**(mustache4dart2,twitter_1user,tele_bot_api,hestia,galileo_mustache4dart,play_with_words,okhttp,telegram_bot_api,spaceinvaders,lowdb)
- `UNLICENSE`: 29 (conreality_pulse,supreme_camera,flutter_sqlcipher,flutter_android,near,edropinapi_accounts,hello_example,flutter_lua,flutter_face_detection,accounts)
- `COPYING`: 27 (musicus_server,libjson2builtvalue,yui,iban_form_field,suisse,flutter_particles,tba_api_v3,flutter_particle,sunmi,bitcoin_bip44)
- `UNLICENSE.txt`: 5 (list_chunker,image_picker_container,over_screen_widget,polyline_builder,loading_container)
- `COPYING.md`: 2 (tinylog,watch_recursively)

- missing: 62 **(0.19%)**(publish_test_console,parse_server,built_union_test,DartDemoCLI,polymerize,zhopa,dart2ts,pub_test_pkg,flutter_bloc_architecture,zengen)

Roughly 0.9% of the packages are not using `LICENSE` as the file name.
