### ISSUE TITLE
Remove API end-points for `dart pub uploader add/remove`

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5827]
Tasks:
 * [x] Check usage for `POST /api/packages/<package>/uploaders`
 * [x] Check usage for `DELETE /api/packages/<package>/uploaders/<email>`
 * [ ] Remove APIs if not heavily used.

Context: Starting Dart 2.17 `dart pub uploader add/remove` was disabled in the client.

**Comment by jonasfj** [comment]
I suggest we wait this for a few months and land some of the ongoing migrations.

**Comment by jonasfj** [comment]
Usage is low. I suggest we disable the API end-points, and just return an error message telling user to use the web interface.
Linking to the admin page for the given package.

**Comment by isoos** [comment]
> Does the web UI support adding uploaders only for packages with publishers or generally?

Only packages **without a publisher** are supported, otherwise the publisher's members are able to admin/upload.

**Comment by mit-mit** [comment]
Clarifying in https://github.com/dart-lang/site-www/pull/4091

**Comment by isoos** [comment]
This has been deployed and in production for a while now.
