### ISSUE TITLE
Add favorite for package, let user to collect package they like.

### ISSUE THREAD

**Issue by cnmade** [dart-lang/pub-dev#5837]
Is there any starred or favorite button? like github [Started ] button, user can save the package they like.

and next time if they looking for some package they often use, they will look their favorite list, or Starred list.

**Comment by isoos** [comment]
@cnmade: the like on pub.dev also comes with a list that you can look at later:
https://pub.dev/my-liked-packages

I'm not sure if we need a second list with the slight distinction of "using it but not liking it".

**Comment by FMorschel** [comment]
> I'm not sure if we need a second list with the slight distinction of "using it but not liking it".

I would not use it, but I might actually like a package and not have a use for it. That would differentiate them.

**Comment by jonasfj** [comment]
Using browser bookmarks is also an option.

I don't think we'll add features like this anytime soon. It's not that we're oppose to it, just that there are other more pressing concerns.
