### ISSUE TITLE
Example folder gets downloaded as a dependency

### ISSUE THREAD

**Issue by guyluz11** [dart-lang/pub-dev#5862]
`example` folder gets downloaded with the dependencies. 

Pub downloading the `example` folder of all the dependencies, I think it shouldn't happen because it is redundant.

![image](https://user-images.githubusercontent.com/9304740/174586391-9e507306-8c8f-47a4-a8db-bdc40b899991.png)

**Comment by isoos** [comment]
This is a conflicting requirement where we need to choose between the package archive's canonical/unmodified content or reduce the used disk space of the users. I'm not sure if there is a clean solution to this, maybe the `pub` client could remove the `example` directory on certain conditions. /cc @jonasfj @sigurdm wdyt?

**Comment by jonasfj** [comment]
Pub packages are self-contained, they include `test/`, `tool/` and `example/` among others.
If a package author doesn't want to ship those they can ignore them with `.pubignore`.

I think that rethinking pub to ship only what is necessary would be larger redesign, because packages may ship resources in arbitrary folders.

**Comment by sigurdm** [comment]
Yeah - I think it is fair to not optimise for developer disk-space here.

The extra folders will not get into an AOT compiled product because we do tree-shaking (only include what's necessary). So this doesn't hurt users.

**Comment by guyluz11** [comment]
> Yeah - I think it is fair to not optimise for developer disk-space here.
> 
> The extra folders will not get into an AOT compiled product because we do tree-shaking (only include what's necessary). So this doesn't hurt users of the compiled product.

It is not just the extra space for the user.
It can hurt developers since searching in the IDE return results from inside of the package when it is in the example folder

![image](https://user-images.githubusercontent.com/9304740/183401198-e61c15e2-dcc2-49dc-8775-ff5e6396a25d.png)

**Comment by clragon** [comment]
I actively dislike the idea of excluding the example folder;
I browse the source code of my dependencies and it is therefore important and good for me when the example is available directly.

Your search results including the dependencies seems like it might just be your IDE being misconfigured. 
Android Studio does not include my dependencies in searches.

**Comment by guyluz11** [comment]
> I actively dislike the idea of excluding the example folder; I browse the source code of my dependencies locally and it is therefore important and good for me when the example is available directly.
> 
> Your search results including the dependencies seems like it might just be your IDE being misconfigured. Android Studio does not include my dependencies in searches.

I am using mono repo with melos, so multiple projects can be found spread in directories.
That could be the case why it's exist for me and not for you

**Comment by stuartmorgan** [comment]
> Pub packages are self-contained, they include `test/`, `tool/` and `example/` among others. If a package author doesn't want to ship those they can ignore them with `.pubignore`.

Since this comment was being used to argue for excluding examples in many issues (linked above), I want to clarify here that it's unlikely that developers are going to actually exclude `example/` because doing so would remove the example from the `pub.dev` page for the package.

**Comment by guyluz11** [comment]
Could it be that this issue belongs to Android Studio Flutter plugin [flutter-intellij](https://github.com/flutter/flutter-intellij) ?
My project is configured using `melos` multiple projects, maybe this is a bug for big projects that didn't get cached before

**Comment by clragon** [comment]
> I am using mono repo with melos, so multiple projects can be found spread in directories.
> That could be the case why it's exist for me and not for you

I have attempted to recreate this issue, but I am unable to.
I cloned https://github.com/guyluz11/flame and set it up in my Android Studio.

When running a search, it only ever includes packages I would expect it to include, the ones in "packages".
The search does not reach into packages the projects depend on.

![image](https://github.com/dart-lang/pub-dev/assets/11785085/543ae61d-947e-4f7b-aade-4b4a2ce9b87b)

**Comment by guidezpl** [comment]
Agree this is not for individual package authors to handle, perhaps search can be narrowed to one's own project, or pub directories excluded from search?

**Comment by guyluz11** [comment]
With further testing, I have found out that

**Can't find** for packages:
`image_picker`, `image_picker_android`, `image_picker_for_web`, `image_picker_ios`

**Can find** for:
`image_picker_linux`, `image_picker_macos`, `image_picker_windows`

Furthermore for the packages that I can find the content it includes the packages code itself and not just the example folder as I thought in the beginning 

More info, I am on Kubuntu using Android Studio from snap
`android-studio 2022.3.1.18 127  latest/stable snapcrafters*  classic`, flutter plugin version `75.1.2`


> When running a search, it only ever includes packages I would expect it to include, the ones in "packages". The search does not reach into packages the projects depended on.
> 
Interesting, can you try adding `flutter pub add image_picker` in the [my flame fork](https://github.com/guyluz11/flame) example folder and searching for `AlertDialog`

![image](https://github.com/dart-lang/pub-dev/assets/9304740/1355eccf-8643-4033-9c87-a753c68148f6)

**Comment by guyluz11** [comment]
Can reproduce on Mac, tested with different projects with melos

**Comment by rafaelsetragni** [comment]
> > Pub packages are self-contained, they include `test/`, `tool/` and `example/` among others. If a package author doesn't want to ship those they can ignore them with `.pubignore`.
> 
> Since this comment was being used to argue for excluding examples in many issues (linked above), I want to clarify here that it's unlikely that developers are going to actually exclude `example/` because doing so would remove the example from the `pub.dev` page for the package.

101% agreed.

**Comment by guyluz11** [comment]
Agree, example folder/tab should stay in pub.dev
