### ISSUE TITLE
Blocking publisher leads to integrity-check notifications

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#5875]
I ran:

```
> dart pub_services/bin/pub_services.dart admin execute-tool block-publisher-and-all-member -- block <PUBLISHERNAME>
```

Now we get this:

```
integrity.check: [pub-integrity-problem] Publisher "<PUBLISHERNAME>" is marked as abandoned, but has members (first: "4fc8bdae-4ba1-495b-b4f1-71c0f056e23d").
```

Did the members not get blocked in the operation? Or does the integrity check need to take into account that the members are blocked?

**Comment by isoos** [comment]
> Did the members not get blocked in the operation?

Members do get blocked: https://github.com/dart-lang/pub-dev/blob/master/app/lib/admin/tools/block_publisher_and_all_members.dart#L41

> Or does the integrity check need to take into account that the members are blocked?

Correct, this needs to be updated:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/shared/integrity.dart#L185
