### ISSUE TITLE
Integrity check warns about inconsistency

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#5876]
```
{
  insertId: "aa6baof4acpp7"
  labels: {1}
  logName: "projects/dartlang-pub/logs/appengine.googleapis.com%2Fstderr"
  receiveTimestamp: "2022-06-20T11:50:33.347046440Z"
  resource: {2}
  severity: "WARNING"
  textPayload: "integrity.check: [pub-integrity-problem] Canonical archive for PackageVersion "biscuits/0.2.0" differs in the public bucket."
  timestamp: "2022-06-20T11:50:30.338Z"
}
```

Not sure if this is anything important - or a race - we only got this single instance the last month.

**Comment by isoos** [comment]
I can compare only the old and the public bucket's content, and the length, crc and md5 hash seems to be the same for this archive.

Integrity checks are run weekly, so let's wait for the next one to see if it gets repeated.

**Comment by isoos** [comment]
This is not longer an issue on a recent integrity check run.
