### ISSUE TITLE
Can publisher's have their contact information hidden?

### ISSUE THREAD

**Issue by MaikuB** [dart-lang/pub-dev#5887]
Can a verified publisher have the option to keep their contact information hidden? This is to help fight against spam and getting unsolicited emails. Even if laws are in place to penalise businesses for breaking rules around spam, I'd imagine it'd be harder for government agencies to follow up on complaints if the business entity doesn't have a local presence in same country as the person who has filed a complaint

**Comment by isoos** [comment]
> Putting aside the spam concerns, maintainers may not want some form of contact information public at all.

You can publish a package without verified publisher, in that case neither a domain, nor an email will be public. For a verified publisher, the domain will always be public.

> Maintainers are sometimes be treated as vendors with issues getting raised where support is expected and may lead to "OSS burnout".

Unfortunately we cannot do much there: either there is a contact channel and willingness to deal with users, or it is not. On GitHub, you can disable the ability to create new issues... and a homepage/repository URL could get stale... 

> allows maintainers to be contacted but requires users to sign in after which they need to fill in a form and consent to having their email address being exposed to the person they wanted to contact

This idea have been floated around a while back, we don't oppose it, but it is not a priority for us to implement it, as it serves only a small fraction of developers (you can already be anonymous if you wanted to), while other features could have better impact.

> I've been getting unsolicited emails about services.

I'm not really sure that you can be shielded against those, unless you shut off every channel towards yourself. I have been contacted on various random channels and to be honest, if I think it is needed, I'm also guilty of using any channel that is available to contact somebody....

**Comment by sigurdm** [comment]
We won't do this.
