### ISSUE TITLE
Facing crash issue while loading Map and while getting focus on markers

### ISSUE THREAD

**Issue by maulik0webomindapps** [dart-lang/pub-dev#5915]
URL: https://pub.dev/packages/google_maps_flutter

<Describe your issue or suggestion here>
I'm facing issue while I am loading Markers to map and it's crashing on any pages and it will be like on specified devices like Samsung, Oppo, Xiomi . In some device it's working fine but in some device it is crashing continuously. also I'm attaching screen shot which is from firebase crash analytics, Please have a look.

Thank you in advance for checking my issue and please do needful. 

![image](https://user-images.githubusercontent.com/93896937/180140751-e25cf50f-a9bf-4761-bdf0-540c2c7eb6e9.png)

![image](https://user-images.githubusercontent.com/93896937/180140859-c5b34809-d670-41f1-912e-3c766b5e63d3.png)

**Comment by isoos** [comment]
@maulik0webomindapps: this issue tracker is for the `pub.dev` site, and not for individual packages. Please use the package's repository link to file issues, in this case: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+maps%22
