### ISSUE TITLE
Thanks for the report.

### ISSUE THREAD

**Issue by jadeteen989** [dart-lang/pub-dev#5926]
Thanks for the report.
What kind of request is being redirected (GET/HEAD/...)?
My understanding is that new request should point to new URL but otherwise be identical to the original one.
Can you provide a little more details as to why you think copying headers is wrong?

_Originally posted by @aam in https://github.com/dart-lang/sdk/issues/45410#issuecomment-804155778_

**Comment by isoos** [comment]
I'm not sure: how is this relevant to the `pub.dev` site?
