### ISSUE TITLE
Newly submitted package homepage is not accessible by the analysis tool

### ISSUE THREAD

**Issue by ganigeorgiev** [dart-lang/pub-dev#5927]
I've recently published https://pub.dev/packages/pocketbase.

This probably is not an issue with the pub.dev site or dartdoc, but for some reason my package homepage doesn't seems to be accessible by the pub.dev analyzer because in the _Scores tab > Follow Dart file conventions > Provide a valid pubspec.yaml_ I have the following error:
```
Homepage URL doesn't exist.
At the time of the analysis https://pocketbase.io was unreachable.
```

The `pubspec.yaml` of the package could be found here - https://github.com/pocketbase/dart-sdk/blob/master/pubspec.yaml.
I've published 2 versions and both times the package homepage was unreachable.

I've checked my homepage with a vpn from several locations and it is accessible.

Is it possible that my cloud provider (Hetzner) is blocking the pub.dev analysis tool or there is something else wrong with my domain?

**Comment by isoos** [comment]
Is this a new domain? It may be just fluke at the time of the analysis, or DNS settings were not propagated.

Based on my experience with Hetzner, I don't think they are blocking anything.

**Comment by ganigeorgiev** [comment]
@isoos It is a new domain, but not that "new" - it is live since 07 Jul 2022.

Nevermind, maybe you are right and it was just a fluke and it's not that important anyway.
I've just created a publisher and transferred the repo so the url to the project site/api docs is still accessible from there.

**Comment by isoos** [comment]
Hm, DNS propagation should be an issue then... Is it hostend on ipv4/ipv6 IPs?

**Comment by ganigeorgiev** [comment]
The server has public IPv4/IPv6 addresses attached to it automatically when I've created the VPS.

I'll try later this evening to publish again some small change in the documentation and will see if I'll be able to reproduce it.

**Comment by ganigeorgiev** [comment]
@isoos I've published 2 dummy releases to test it again and it still doesn't work and I'm not sure why.

For [0.1.0+3](https://pub.dev/packages/pocketbase/changelog) I've even temporary enabled `ICMP` connections to allow "ping"-ing the domain but without any difference.
Just for clarity, my server has a firewall that by default allows only 80 and 443 ports for any IPv4 and IPv6 TCP inbound connections.

So in the end, I'm not sure what is causing the issue, but I guess I'll leave it as closed because most likely is something conflicting with my setup.

**Comment by ganigeorgiev** [comment]
@isoos I think I've found the culprit. After reading the code for the _pana_ and _safe_url_check_ packages I've found out that the url check is [sending HEAD requests to the specified url](https://github.com/google/dart-neats/blob/master/safe_url_check/lib/safe_url_check.dart#L145) but my homepage allows only GET and therefore 405 is returned (I probably will have to update that).

So in other words - everything is working as expected from the pub.dev side of things.
