### ISSUE TITLE
Consider if the package name similarity check should stop taking moderated names into account.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#5928]
I propose we stop taking moderated package names into account when doing naming similarity checks [here](https://github.com/dart-lang/pub-dev/blob/ca05a26847ffbbe138950ff31e6ee2a5be6601cb/app/lib/package/backend.dart#L924).

Currently if a package `foobar` is moderated we leave a tombstone preventing a package with the same name.

This is good because it prevents the case where someone depending on `foobar` gets an unrelated (or malicious) package on `dart pub get`.

But also the "similarity check" we have takes the name `foobar` into account making it impossible to publish:

* foobars
* foo_bar
* ...

I question the value of this:

* Existing dependents of `foobar` would not be prone to a spelling mistake.
* In most cases where we moderate a package, it has very little usage - making the risk of mistaking another package for it very little.

cc @jonasfj @isoos @szakarias

**Comment by buttonsrtoys** [comment]
@sigurdm @isoos Thanks so much for this, guys! I have an immediate need for this. I published a package and omitted an 's' on the end of it. I dread the "gah" I would feel every time I saw its name in the future so really looking forward to the PR being merged.
