### ISSUE TITLE
Admin Tool for adding members to a publisher

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#5936]
We need such a tool.

**Comment by sigurdm** [comment]
This is no longer urgent.

I think we eventually have such a tool, so I'll leave this open for now.

**Comment by sigurdm** [comment]
We now need this again

**Comment by budde377** [comment]
Started a solution in #6292, anything to get me unblocked! Merging my old account and a new account, removing the package from my publisher, moving my package to a new publisher are all acceptable.

**Comment by isoos** [comment]
This has been done in #6293.
