### ISSUE TITLE
`sentry_flutter` shows `[unknown platforms]`

### ISSUE THREAD

**Issue by marandaneto** [dart-lang/pub-dev#5960]
`sentry_flutter` shows `[unknown platforms]` on [version 6.9.1](https://pub.dev/packages/sentry_flutter/versions/6.9.1)
[version 6.8.1](https://pub.dev/packages/sentry_flutter/versions/6.8.1) shows platforms correctly

<img width="453" alt="Screenshot 2022-08-17 at 17 58 21" src="https://user-images.githubusercontent.com/5731772/185187055-559f585d-1eb0-4676-a0e2-a6cec4f45a88.png">

The only thing that has changed is the min-supported version of the Flutter SDK.

from `flutter: '>=1.17.0'`
https://github.com/getsentry/sentry-dart/blob/45c7b1a2ace9315943018f87038d6b573c296398/flutter/pubspec.yaml#L10

to `flutter: '>=2.0.0'`
https://github.com/getsentry/sentry-dart/blob/9907b2cf3ef4c6a9a16de272a81db9107c4a5dea/flutter/pubspec.yaml#L10

All plugins are declared correctly:
https://github.com/getsentry/sentry-dart/blob/9907b2cf3ef4c6a9a16de272a81db9107c4a5dea/flutter/pubspec.yaml#L33-L49

Ideas what it could be?

**Comment by isoos** [comment]
This was fixed in https://github.com/dart-lang/pana/pull/1116, and we are planning to release a new pub.dev site with it in the coming days. The package will get re-analyze and the platform classification will correct itself.

**Comment by marandaneto** [comment]
> This was fixed in [dart-lang/pana#1116](https://github.com/dart-lang/pana/pull/1116), and we are planning to release a new pub.dev site with it in the coming days. The package will get re-analyze and the platform classification will correct itself.

Thanks @isoos
