### ISSUE TITLE
Error: NotFound(404): Could not find `package "<package>"

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5974]
Where `<package>` was recently removed.

```
Error: NotFound(404): Could not find `package "<package>"`.

at PackageBackend.updatePackageVersions.<fn> ( package:pub_dev/package/backend.dart:317 )
at StackZoneSpecification._registerUnaryCallback.<fn> ( package:stack_trace/src/stack_zone_specification.dart:125 )
```

@isoos is this something we should / could handle better, or do we just ignore it as a plausible race condition.

**Comment by isoos** [comment]
Was the specific package deleted/moderated? Otherwise I don't see why this would happen...

**Comment by jonasfj** [comment]
> Was the specific package deleted/moderated?
Yes

**Comment by isoos** [comment]
In that specific method I'd rather throw a 404 than ignore the missing package. Based on the callers of that method, we shouldn't really have this exception (except for unlucky race conditions like this one).
