### ISSUE TITLE
"Unlisted packages" or "Hidden packages" tab on publishers page

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#5988]
There are some publishers that don't like unlisted / discontinued packages being displayed on the publishers page.

Perhaps we should hide them by default, and offer a "Unlisted Packages" tab, which we only display to admins of the publisher page. Not because unlisted packages are hidden from other users, just that don't show up in search package listings by default.

![image](https://user-images.githubusercontent.com/149732/186665510-ce8391b6-8925-401a-b06f-acafaeb1b7d6.png)

**Comment by jonasfj** [comment]
cc/ @mit-mit

**Comment by isoos** [comment]
The current `Packages` tab only lists the top 10 packages and then both the sorting control or the pagination would redirect the user to the search page (with `publisher:<x>` predicate). I am assuming this won't change for now (except we won't have the `show:hidden` predicate there).

Should the `Unlisted packages` include the ones that are `discontinued` too?

**Comment by sigurdm** [comment]
> Should the Unlisted packages include the ones that are discontinued too?

IMO yes, you need a way of seeing all your packages.

**Comment by isoos** [comment]
> IMO yes, you need a way of seeing all your packages.

So, let's call it `Hidden packages`, and the URL would be `/publishers/<publisherId>/hidden-packages` ?

**Comment by mit-mit** [comment]
I think "hidden" sounds too strong; it may create the illusion that packages on that tab are actually hidden.

**Comment by isoos** [comment]
> I think "hidden" sounds too strong; it may create the illusion that packages on that tab are actually hidden.

We have the same terminology on the search page, I think it won't cause much confusion. (Or the same confusion may be present on search too?)
