### ISSUE TITLE
Dart 3 compatible search filter on pub.dev

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#6022]

**Comment by jonasfj** [comment]
Blocked on https://github.com/dart-lang/pana/issues/1123

**Comment by mit-mit** [comment]
Dart 3 search is live, closing

<img width="354" alt="Screenshot 2023-01-26 at 09 48 07" src="https://user-images.githubusercontent.com/13644170/214774147-29656693-e211-496c-a786-6bfa145539ce.png">
