### ISSUE TITLE
"Dart 3 ready" badge on pub.dev

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#6023]
Requires a full analysis using a Dart 3 alpha release to pass in pana.
This means doing the analysis twice, maybe not running all of pana, but having pana run `dart analyze` twice.

**Unknown:** We need to get hold of a Dart 3 alpha or dev release a few weeks before it's shipped.

**Comment by jonasfj** [comment]
Blocked on https://github.com/dart-lang/pana/issues/1123

**Comment by jonasfj** [comment]
We probably need to launch with this a dev-release, and keep the badge behind experimental. We can even use Dart 2.18, so that we just switch the SDK when we have the alpha release ready.

**Comment by mit-mit** [comment]
Versioning CL is https://dart-review.git.corp.google.com/c/sdk/+/271922?usp=search

**Comment by mit-mit** [comment]
This is currently blocked by https://github.com/dart-lang/sdk/issues/50694

**Comment by mit-mit** [comment]
Badges are live; closing

<img width="643" alt="Screenshot 2023-01-26 at 09 47 20" src="https://user-images.githubusercontent.com/13644170/214773999-c436804b-f3ef-4f62-ac7c-ef3f70ed04be.png">
