### ISSUE TITLE
Can't View images in pub.dev site

### ISSUE THREAD

**Issue by guruprasadh-j** [dart-lang/pub-dev#6053]
URL: https://pub.dev/packages/file_picker
![image](https://user-images.githubusercontent.com/112867700/190558463-74d4b641-5081-4441-9105-1d254ec675fd.png)
Can't View images in pub.dev site
<Describe your issue or suggestion here>

**Comment by isoos** [comment]
The pictures do load on my side. They are gifs hosted on github.com, so they should be fine on most ISPs. Are you using any content blocker or corporate proxy that may filter out these? What country are you located in?

**Comment by guruprasadh-j** [comment]
I'm located in India.

**Comment by isoos** [comment]
@guruprasadh-j: can you see the images when you right click on them, and open image in new tab?

**Comment by isoos** [comment]
Closing as not reproducible.

**Comment by guruprasadh-j** [comment]
> @guruprasadh-j: can you see the images when you right click on them, and open image in new tab?

No, I can't see them

**Comment by isoos** [comment]
>> @guruprasadh-j: can you see the images when you right click on them, and open image in new tab?
>
> No, I can't see them

In that case some content blocker is active or misconfigured, either on your machine, or on a (corporate/ISP) network.

**Comment by guruprasadh-j** [comment]
May be it has. But it's not showing in any kind of network in India(AIRTEL, JIO & BSNL). If use VPN, It shows images.  None can see the images in pub.dev in India
