### ISSUE TITLE
Error in the list of supported platforms

### ISSUE THREAD

**Issue by chykon** [dart-lang/pub-dev#6057]
Dart SDK version: 2.18.0 (stable) (Fri Aug 26 10:22:54 2022 +0000) on "linux_x64"
pana 0.21.17

The page https://pub.dev/packages/utf8decoder_hw states that the package supports the "WEB" platform, however when running pana locally, the output is:

```text
## ✓ Platform support (20 / 20)
### [*] 20/20 points: Supports 5 of 6 possible platforms (**iOS**, **Android**, Web, **Windows**, **MacOS**, **Linux**)

* ✓ Android
* ✓ iOS
* ✓ Windows
* ✓ Linux
* ✓ MacOS

These platforms are not supported:

<details>
<summary>
Package not compatible with platform Web
</summary>

Because:
* `package:utf8decoder_hw/utf8decoder_hw.dart` that imports:
* `package:utf8decoder_hw/src/utf8decoder.dart` that imports:
* `package:utf8decoder_hw/src/explicit_logic.dart` that imports:
* `package:rohd/rohd.dart` that imports:
* `package:rohd/src/wave_dumper.dart` that imports:
* `dart:io`
</details>
```

**Comment by isoos** [comment]
This seems to be a bug, and a rather strange one. I've got the same output locally, not sure why pana on `pub.dev` got a different result.

**Comment by chykon** [comment]
Same problem, just with a different package: https://pub.dev/packages/utf8encoder_hw

**Comment by isoos** [comment]
This seems to got fixed by the `package:analyzer` upgrade.
