### ISSUE TITLE
User survey keeps popping up every time I visit pub.dev

### ISSUE THREAD

**Issue by cbenhagen** [dart-lang/pub-dev#6078]
The following popup is shown every single time I visit pub.dev and it is becoming really annoying:
![IMG_D9CDB42476A5-1](https://user-images.githubusercontent.com/814785/192249520-fcc14b30-df0a-42b7-bfe5-7a242af07c37.jpeg)

This happens in both Chrome and Safari on iOS.

**Comment by sigurdm** [comment]
@cbenhagen have you answered "no thanks" and still get the survey? That sounds like a problem with our survey settings.

We should look into this.

**Comment by jonasfj** [comment]
@jayoung-lee, is there a way we can reduce how many times we prompt a single user.
Any idea what the "Prompt eligibility window" settings will do?

**Comment by cbenhagen** [comment]
@sigurdm yes I am clicking "no thanks" on every single page load to get rid of this annoying popup. I also tried filling out bad surveys with the plea to finally stop annoying me in the hopes that someone might read it.

**Comment by isoos** [comment]
@cbenhagen: Is this still happening?

**Comment by cbenhagen** [comment]
I haven't seen a popup in a long time. Are they enabled at all?

**Comment by jayoung-lee** [comment]
No, the survey is not running at the moment!
