### ISSUE TITLE
Styling is off for tables in dark mode

### ISSUE THREAD

**Issue by ueman** [dart-lang/pub-dev#6104]
The dark mode styling doesn't quite seem right for tables. See the below screenshots. They're from https://pub.dev/documentation/webview_flutter/latest/

![9mcfxv](https://user-images.githubusercontent.com/1270149/193208096-42fd3b6b-58d6-4556-acaa-5643cec760cc.jpg)
![x9kzdk](https://user-images.githubusercontent.com/1270149/193208113-a2d4b2cc-2b8d-4395-a4f2-7e392f101cf8.jpg)

**Comment by isoos** [comment]
I think the CSS rule that affects the rendering is the white background on the table rows:

```
.markdown-body table tr {
  background-color: #fff;
  border-top: 1px solid #c6cbd1;
}
```
