### ISSUE TITLE
Software Heritage - Call for public review

### ISSUE THREAD

**Issue by benoit-chauvet** [dart-lang/pub-dev#6111]
Hello,

The mission of Software Heritage is to collect, preserve and share all the publicly available source code (see https://www.softwareheritage.org/ for more information).

Thanks to Franck Bret from Octobus (https://octobus.net/), Software Heritage now has a lister and a loader for pub.dev [1].

We have ingested pub.dev origins on our staging environment [2]

We would now like to have a round of public review on the actual data output of the ingestion process, so we can either validate or ask for some more updates, and then eventually deploy it in production.

We have some basic documentation about the pub.dev lister [3]

Still, for now, please have a look at some of those origins loaded [2] and let us know what you think!

Cheers,

Benoit
Software Engineering Manager - Software Heritage

[1] https://forge.softwareheritage.org/T4465
[2] https://webapp.staging.swh.network/browse/search/?q=pub.dev&with_visit=true&with_content=true
[3] https://docs.softwareheritage.org/devel/apidoc/swh.lister.pubdev.html

**Comment by jonasfj** [comment]
@isoos We should document listing of package names.

**Comment by isoos** [comment]
@benoit-chauvet: One thing that stood out was that you are using an unofficial endpoint (`/api/packages`) for getting the package names. This is inefficient, both for us and the consumers of the endpoint, and we are in the process of making our dedicated package name endpoint public and officially supported. Soon after that we may deprecate that unofficial endpoint (`/api/packages`).

The suggested HTTP endpoint is paginated, it only contains the names of packages and the url for the next page:
https://pub.dev/api/package-names

We'll have a new site release that will have this information on the https://pub.dev/help/api page.

**Comment by benoit-chauvet** [comment]
Thanks for your feedback, that will be fixed before we deploy it (see https://forge.softwareheritage.org/T4665)

**Comment by anlambert** [comment]
@isoos We are already using the https://pub.dev/api/package-names endpoint to list pubdev packages (see [code](https://forge.softwareheritage.org/source/swh-lister/browse/master/swh/lister/pubdev/lister.py$49-63)). 

We used the https://pub.dev/api/packages in early implementation of the lister but changed it thanks to your feedback (see https://github.com/dart-lang/pub-dev/issues/6016#issuecomment-1235493723).

Nevertheless, we forgot to update the lister documentation, I will take care of it.

**Comment by isoos** [comment]
Sounds great! As there seems to be no other pending question, I'll close this, and feel free to open a new issue if you encounter something unexpected.
