### ISSUE TITLE
Error parsing links with a dot

### ISSUE THREAD

**Issue by chykon** [dart-lang/pub-dev#6126]
Links in brackets located in `CHANGELOG.md` are parsed incorrectly if there is a dot at the end: a closing parenthesis is added to the address, which makes the link invalid.

[Example](https://pub.dev/packages/rohd/changelog). Version `0.3.2` contains a link that does not end with a dot and everything works correctly. Version `0.3.1` contains a dot after the parentheses, which makes the link invalid.

**Comment by isoos** [comment]
This seems to be a `package:markdown` issue, filed https://github.com/dart-lang/markdown/issues/470, and keeping this open until the fix is deployed to `pub.dev`.

**Comment by isoos** [comment]
This seems to be fixed with the latest markdown and site release.
