### ISSUE TITLE
there is no way to report fraud in the package

### ISSUE THREAD

**Issue by denisnadey** [dart-lang/pub-dev#6156]
URL: https://pub.dev/help

I found a malicious package that takes your data and sends it through a third party service! Yes, it does what it promises, but it also steals data. Please add complaint functionality so that it is possible to warn about this not through issue

https://pub.dev/packages/smtpman

**Comment by jonasfj** [comment]
For violations of https://pub.dev/policy, please send an email to `support@pub.dev`
