### ISSUE TITLE
Package was lost while transferring to another publish

### ISSUE THREAD

**Issue by JCKodel** [dart-lang/pub-dev#6177]
1) I published a package using my personal account

2) I transferred the package for a verified publisher in my account:
![image](https://user-images.githubusercontent.com/379339/201448532-f7391368-864d-4fc4-ace4-7ca690df3d2c.png)

3) There is no packages in my personal account nor my publisher account. It just vanished from both publishers O.o

My personal publish account has just an old package:

![image](https://user-images.githubusercontent.com/379339/201448432-e064831e-3463-4c42-90a0-165008ecd2db.png)

My new verified publisher account has nothing:

![image](https://user-images.githubusercontent.com/379339/201448461-3f81c91e-790f-4fa9-bc14-f603d18b435c.png)

**Comment by JCKodel** [comment]
Nevermind... It appears now (cache issues, maybe?)

**Comment by sigurdm** [comment]
Yeah - probably some cache had to pick it up.

@isoos is there something we forget to invalidate when transferring packages? It would be nice not to have this happen.

**Comment by isoos** [comment]
My guess is the search index: when we update the `Package.publisher` field, we do purge the cache that uses it, however, the listing page for packages relies on search, which updates later and asynchronously. (Note: this could be improved if we did had a non-search related index that updates more frequently).
