### ISSUE TITLE
publishing from actions should not allow creating new packages

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#6195]
https://github.com/dart-lang/pub-dev/blob/b811cb472c77937d7ed21536c8d0192d4ab087a9/app/lib/package/backend.dart#L1049-L1052

This isn't an issue yet, since it's not enabled. But we don't want to allow creating new packages using a non-user entity.

I suggest adding `if (agent is! AuthenticatedUser) throw` in the if-statement where we create the package entity.

**Comment by isoos** [comment]
It looks like that we do block service account uploads through the `_listAdminNotificationEmailsForPackage` checks, but it is non-trivial to conclude this just by reading the code.

**Comment by jonasfj** [comment]
Shouldn't we make an explicit check?

**Comment by isoos** [comment]
> Shouldn't we make an explicit check?

Yes, we will.

**Comment by isoos** [comment]
This has been implemented and we a test for it with the right message.
