### ISSUE TITLE
Rendering issue with code blocks in package readme

### ISSUE THREAD

**Issue by osaxma** [dart-lang/pub-dev#6197]
I believe there's a rendering issue with the code blocks looking like this (two boxes in one with two different colors):

<img width="600" alt="Screen Shot 2022-11-18 at 3 29 17 AM" src="https://user-images.githubusercontent.com/46427323/202589076-ab541696-2b5d-4137-b5c3-701b4e0719bd.png">

The screenshot is from: https://pub.dev/packages/requests but I've seen the issue with multiple packages already.

**Comment by isoos** [comment]
Thanks for reporting this! It has been fixed in #6189, but we haven't deployed the new site version yet, it may happen sometime next week.
