### ISSUE TITLE
Clicking on version number should redirect to changelog

### ISSUE THREAD

**Issue by Mravuri96** [dart-lang/pub-dev#6210]
Current clicking on the version number just navigates the user to the readme section of a package, which is kind of redundant. Clicking that hyperlink should take the user to the packages changelog tab.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/28457922/203466991-e8e9ac6e-e156-45c8-879f-560fc86d25e7.png">

https://github.com/dart-lang/pub-dev/blob/7616b914dfb4ed32414d524653e6472085f64b63/app/lib/frontend/templates/views/pkg/package_list.dart#L84

Changing this line to should solve this issue?
```dart
 href: urls.pkgChangelogUrl(
```

**Comment by isoos** [comment]
The link may be redundant on packages that have only a latest version, but we also list and link to the latest prerelease version, e.g.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/4778111/203754563-6d5fedbf-2d16-4ce7-b57d-27f717c4cb15.png">

In such cases it feels like we are better off to link to the specific versions, and not to all versions (or changelog).
We could remove the link if it is only the latest version we are linking to, but that could be more confusing that keeping it as-is.

Closing as this change is not planned for now (not without a redesign on how we display these items).
