### ISSUE TITLE
Quick access to UI packages

### ISSUE THREAD

**Issue by esmaeil-ahmadipour** [dart-lang/pub-dev#6250]
Due to the rich archive of UI packages on this website, It is suggested to have a Tag or Filter for quick access to UI packages.

**Comment by sigurdm** [comment]
I think this would be fulfilled with a solution to https://github.com/dart-lang/pub-dev/issues/5219

**Comment by isoos** [comment]
Closing as duplicate of https://github.com/dart-lang/pub-dev/issues/5219.
