### ISSUE TITLE
To mention a hurtle or obstruction most always is in a negative terminology.  Could our nature of worded plotting be better and how?

### ISSUE THREAD

**Issue by mackxpall** [dart-lang/pub-dev#6285]
URL: https://pub.dev/help/search#ranking

<Describe your issue or suggestion here>

**Comment by isoos** [comment]
@mackxpall: is there an issue with the pub.dev site you wanted to report?

**Comment by sigurdm** [comment]
Please open a new issue explaining your problem a bit more clearly. We are unsure what you mean.
