### ISSUE TITLE
Can't publish the package on pub dev 

### ISSUE THREAD

**Issue by AneeqMalik** [dart-lang/pub-dev#6291]
URL: https://pub.dev/help/publishing

I have been trying to publish my flutter package on pub dev but always failed with the following error.
Connection closed before full header was received
pub finished with exit code 69
However, I have tried to run with --dry-run and it returns no issues.
I don't know how to fix this issue plz help me in this I am new to flutter.

**Comment by isoos** [comment]
@AneeqMalik: Could you try to use verbose logging and attach the log here? e.g. `dart pub publish -v` or `flutter pub publish -v`.

There could be network issues in certain countries and/or ISPs. We have a little script that tries to diagnose these, please download and run it locally, and copy-paste its output: https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart

**Comment by sigurdm** [comment]
Please open a new issue if this persists, and you have more information

**Comment by AneeqMalik** [comment]
There was a network issues. I simply used a VPN services to sort it out.
