### ISSUE TITLE
Package with 4.0.0 upper bound is marked as Dart 2 incompatible

### ISSUE THREAD

**Issue by parlough** [dart-lang/pub-dev#6305]
I published [`package:fluttering_phrases`](https://pub.dev/packages/fluttering_phrases) with a SDK constraint of `sdk: '>=2.17.0 <4.0.0'` and due to the upper bound of 4.0.0, pub.dev marks it as "DART 2 INCOMPATIBLE".

In the short term, I suppose the check for if a package is legacy can be adjusted to allow for an upper bound of 4.0.0, but perhaps the tag needs to be reconsidered. Soon packages with a lower bound of 3.0.0 may be published as well, and they likely don't deserve a big red incompatible tag, which I believe also hides them from search.

**Comment by sigurdm** [comment]
Yeah - we should allow any package that has a constraint overlapping with the 2-range to be compatible with dart 2 - anything else hardly makes sense.

I guess the DART 2 INCOMPATIBLE label should be retired around when we release dart 3.
