### ISSUE TITLE
Can I adopt package:inject?

### ISSUE THREAD

**Issue by the4thfloor** [dart-lang/pub-dev#6309]
[package:inject](https://pub.dev/packages/inject) is reserved since always. But nothing was ever published there. I guess [google/inject.dart](https://github.com/google/inject.dart) is the corresponding GitHub repository.

I have created a [fork](https://github.com/the4thfloor/inject.dart) of this repo and updated it.

Now I would like to publish the package on [pub.dev](https://pub.dev/). For this, I would like to take over [package:inject](https://pub.dev/packages/inject).

Is this possible?

**Comment by the4thfloor** [comment]
Any news on this?

**Comment by isoos** [comment]
Closing this as not relevant for the pub.dev development. @the4thfloor please reach out through other channels (a few available on @matanlurey's profile).
