### ISSUE TITLE
SignIn not working in pub.dev

### ISSUE THREAD

**Issue by pranjal-barnwal** [dart-lang/pub-dev#6310]
URL: https://pub.dev/

Unable to authenticate to the website.
![image](https://user-images.githubusercontent.com/71400605/209775012-abada52c-497c-4c38-8bc6-045359f05d01.png)

The **SignIn** option in top-right is not working.

**Comment by isoos** [comment]
@pranjal-barnwal: Are you using any content/ad blocker? It should work from a Guest mode window, otherwise it is likely that your ISP, or other network infrastructure may be blocking it.

Note: for me it looks like that it needs a forced reload after clicking the Google Sign In.

**Comment by pranjal-barnwal** [comment]
@isoos 
Oh yes, you are right, my browser was blocking the pop-up. It works right.
