### ISSUE TITLE
The images are not being displayed of any of the widgets

### ISSUE THREAD

**Issue by shubhamkislay** [dart-lang/pub-dev#6311]
URL: https://pub.dev/packages/flutter_animator

GET https://raw.githubusercontent.com/sharp3dges/animator/master/animations/attention_seekers.gif net::ERR_CONNECTION_TIMED_OUT

**Comment by isoos** [comment]
@shubhamkislay: Typically this may happen when you Inetwork settings are misconfigured. Previously this was either ISP, or IPv6 vs IPv4 settings not working at the router/ISP level.

Closing as we can't really help here.
