### ISSUE TITLE
[screenshot] Improve switching between multiple screenshots

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/pub-dev#6326]
The screenshot in the carousel can be improved by:
* Provide a page indicator of pages, currently only the pre and next buttons are displayed.
* Provide a loading indicator when switching between pages, currently loading image will display nothing or with the previous screenshot, which will mislead the user that the page is unresponsive.

Example: https://pub.dev/packages/wechat_assets_picker

**Comment by isoos** [comment]
The images might be preloaded when the screenshot icon is clicked.

However, as we have only a limited number of images, I don't think that a number indicator is important there, especially until we have a way to directly link to a specific image while it is displayed. (However, that is not feasible on a search page, so let's not do that.)

**Comment by AlexV525** [comment]
> However, as we have only a limited number of images, I don't think that a number indicator is important there, especially until we have a way to directly link to a specific image while it is displayed. (However, that is not feasible on a search page, so let's not do that.)

Okay that's reasonable.

> The images might be preloaded when the screenshot icon is clicked.

You can simulate a slow network when loading images and it feels like unresponsive.

**Comment by isoos** [comment]
Somewhere in the past two weeks we have released a new version where the image switching UX improved a bit (by hiding the current image before switching to the next one). Closing this for now, as we are not planning to add much more to this.
