### ISSUE TITLE
Hyperlink incorrectly escaped on pub.dev

### ISSUE THREAD

**Issue by timsneath** [dart-lang/pub-dev#6331]
On this page:
   https://github.com/timsneath/win32/blob/main/example/README.md

There is a link as follows:

```markdown
Other examples of packages that use Win32 can be found on pub.dev, at the
following location: <https://pub.dev/packages?q=dependency%3Awin32>
```

This URL is [correctly formatted](https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses) and works on GitHub, but on pub.dev it is double-escaped. See this page:
https://pub.dev/packages/win32/example

Note that the text has a hyperlink of:
https://pub.dev/packages?q=dependency%253Awin32
(the `%3A` has become `%253A`).

**Comment by isoos** [comment]
File an issue for `package:markdown`: https://github.com/dart-lang/markdown/issues/502

**Comment by timsneath** [comment]
Fantastic: thanks for redirecting this, @isoos!

**Comment by isoos** [comment]
This seems to be fixed with the latest markdown and site release.
