### ISSUE TITLE
We should not recognize `Example/` (capitalized example folder)

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#6341]
https://pub.dev/packages/shopify_storefront/versions/0.0.2/example shows an example, but our scoring doesn't recognize it: https://pub.dev/packages/shopify_storefront/versions/0.0.2/score

![image](https://user-images.githubusercontent.com/8613953/212343347-d3283fe7-f8ee-4c58-a3eb-88e2b30a0b5d.png)

I suspect this has to do with capitalization of the folder name. We should align here.

I suggest we only recognize the lowercase version in both cases.

@jonasfj WDYT?

**Comment by Akhil111993** [comment]
Exactly. The documentation says it's case insensitive, which is why I used 'Example' instead of 'example'. Thanks for the reply.
