### ISSUE TITLE
Packages that only support Dart 3 get a red "dart 2 incompatible" badge 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub-dev#6352]
See https://pub.dev/packages/build_runner/versions/2.4.0 as an example.

We should not show this badge for packages where the sdk constraint requires Dart 3.

**Comment by kevmoo** [comment]
![image](https://user-images.githubusercontent.com/17034/213298383-aba4a847-0a6d-443e-acd7-3117dd1be546.png)

**Comment by isoos** [comment]
This also impacts packages on search: when a stable, prerelease or preview version gets the 'Dart 2 incompatible' label (internally: `is:legacy`), it gets hidden from regular search results and one needs to enable it by adding `show:unlisted` as a search term.

Part of this will be fixed #6353, but we also need to change the search backend to include only positive search items from preview and prerelease versions.
