### ISSUE TITLE
Score unreasonably reduced due to analysis with latest stable SDK

### ISSUE THREAD

**Issue by kaboc** [dart-lang/pub-dev#6373]
My package that supports Flutter 3.0.0 and above has got its pub points reduced bacause `toolbarOptions` used in the package has been deprecated after Flutter 3.3.0-0.5.pre.

pubspec.yaml

```yaml
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"
```
<img src="https://user-images.githubusercontent.com/20254485/214789381-3c22a08a-53a0-4305-833f-b783fe9487c5.png" width="640">

The analysis result says `contextMenuBuilder` needs to be used, but it is not available in 3.0.0 and 3.3.0. Therefore I have to either raise the minimum SDK version to 3.7.0 or just accept the penalty. I think it discourages package authors who is trying to support older SDK versions to avoid inconvenience to users.

**Comment by sigurdm** [comment]
Yeah - this is a bit unfortunate. However I'm not sure about the best solution.

If we knew **when** a depreciation is added to an sdk (we currently don't have this information in a reliable format I believe), we could choose not to display it based on the lower bound. @jonasfj WWDYT should we try to convince someone to build this?

As a workaround you can add a `// ignore:` line to annotate that you know what you are doing: https://dart.dev/guides/language/analysis-options#suppressing-rules-for-a-line-of-code

**Comment by isoos** [comment]
I think there won't be any difference (at least scoring-wise) of these deprecations coming from an SDK library or any random package dependency. Tracking and correlating every deprecation may be possible, but that would mean tracking a compatibility matrix for each version combination, which is not something we would like to do in anytime soon.

Also, traditionally, analysis on `pub.dev` is "evergreen", meaning we are interested in the current status of latest stable versions using latest stable SDKs and dependencies. Using `// ignore` would make the score up, and pass analysis for now, but eventually, as the deprecations move to the breaking changes version, the nicely-looking latest stable would suddenly break too, loosing the score.

I think the right strategy here should be to release a new version that follows the deprecations of its dependencies and uses the latest stable (both in code and in dependency constraints). Users of the library could keep using the older, compatible version, and won't break their app on an upgrade.
