### ISSUE TITLE
Chrome's instant search isn't working

### ISSUE THREAD

**Issue by ciriousjoker** [dart-lang/pub-dev#6377]
There is no example code, this is related to Google Chrome's instant search functionality.

1. On sites like npmjs.com, I can press tab to start searching:
<img width="1030" alt="Bildschirm­foto 2023-01-28 um 23 14 27" src="https://user-images.githubusercontent.com/16866223/215293487-e2a9c10f-002d-4f35-80e6-41c6d15c6575.png">

2. On pub.dev, this doesn't work:
<img width="1028" alt="Bildschirm­foto 2023-01-28 um 23 14 45" src="https://user-images.githubusercontent.com/16866223/215293495-b759a399-cf5b-473e-b1fc-d4eeace2a8b0.png">

3. In the past, it occasionally worked, but weirdly every time it did, it displayed a `_` at the end. That "feature" seems to be gone for quite a while, so I can't show a screenshot. It looked like the one on npmjs.com, but it displayed `pub.dev_` as the site being searched and Chrome tried to autocomplete my typed url with a `_` at the end as well.

**Comment by isoos** [comment]
The strange thing is that we do have a good-looking OSD link in the HTML markup:

```
<link rel="search" type="application/opensearchdescription+xml" title="Dart packages" href="[/osd.xml](https://pub.dev/osd.xml)"/>
```

And the osd.xml file is mostly unchanged and was roughly the same over time: https://github.com/dart-lang/pub-dev/blob/master/static/osd.xml

If somebody is interested in digging deeper into the issue, any lead is appreciated!

**Comment by ciriousjoker** [comment]
### Some notes:
- Instant search also doesn't work for me on https://translate.google.com/, so perhaps its an issue on my machine
- the xml file is not loaded at any point while browsing the website (checked via devtools)
- i can reach the xml file when navigating there manually
- issue still occurs in incognito mode without extensions

### Something really interesting:
In Safari, it somewhat works. It displays the "search pub.dev" prompt and i can enter a phrase, but it doesn't actually search for it. This is how it looks:
<img width="554" alt="Bildschirm­foto 2023-01-29 um 04 20 56" src="https://user-images.githubusercontent.com/16866223/215302837-887e38ce-0ad8-4344-94ed-bb1a5ac71afa.png">

@isoos perhaps the xml file has an error?

**Comment by ciriousjoker** [comment]
What the fuck?
https://9to5google.com/2022/03/18/chrome-site-search-activate/

Users apparently now need to manually activate individual sites so that they can search them. I'm glad there is an indicator to tell me when I can do that for a given site. /s

#### There seem to be many issues with the TabToSearch feature:
https://bugs.chromium.org/p/chromium/issues/list?q=component:UI%3EBrowser%3EOmnibox%3ETabToSearch

Firefox allows me to add the search engine:
<img width="263" alt="Bildschirm­foto 2023-01-29 um 05 42 19" src="https://user-images.githubusercontent.com/16866223/215305350-34000c4b-a29b-4e77-84e8-2b4ee7def58e.png">


I guess it's an issue with Chrome then and not pub.dev :/

**Comment by isoos** [comment]
> In Safari, it somewhat works.

Does Google Translate work in Safari? The XML has a maybe relevant difference: Google Translate uses inlined query parameter, while we are using a separate parameter entity.

**Comment by ciriousjoker** [comment]
@isoos No, I've enabled the site search in Chrome and now it works flawlessly. This can be closed.

**Comment by isoos** [comment]
@ciriousjoker: but based on your comment [here](https://github.com/dart-lang/pub-dev/issues/6377#issuecomment-1407549614), it is not working on Safari yet. I'm wondering if it is because of the query parameter. Could you please check if Google Translate works on Safari? (The main difference between the two osd.xml is how the query is parameterized).

**Comment by ciriousjoker** [comment]
@isoos Yes, in Safari, Google Translate works. in Google Chrome as well (after I enabled it in the settings menu)

**Comment by isoos** [comment]
The new format works with Firefox, and since it is the same as in safari, I'd assume it should work there too. It is unfortunate that in chrome it become much harder to add it as custom search...
Closing the issue as we don't have much else to do here.
