### ISSUE TITLE
Auto publishing: can tag creation be automated?

### ISSUE THREAD

**Issue by polina-c** [dart-lang/pub-dev#6384]
I reviewed [the steps](https://dart.dev/tools/pub/automated-publishing) and I see automation could save more of my time. Right now, to publish, i need to flip version in yaml, update CHANGELOG, push the change, run `pub publish` and push the tag. With automation I save just on creating the tag.

It would be amazing if I needed just to update CHANGELOG, flip version in yaml and push. GitHub job could detect that version changed, create tag and publish the package to pub.dev. 

Would it be possible?

**Comment by sigurdm** [comment]
I don't think this has been built yet - I would think it is possible.

Maybe https://github.com/actions-ecosystem/action-push-tag could be used in conjunction with some detection of the version in pubspec.yaml...

@jonasfj has more intimate knowledge about github actions.

**Comment by isoos** [comment]
> Would it be possible?

It is possible to write such a workflow, and you can write it yourself for your own repository without our permission or interaction. 

It is unlikely that we want to write and host such a workflow though, as it has high risk of publishing unintended changes, e.g. flipping the version in a commit that is not the final one it a release. The currently recommended workflow with the tagging is both explicit on the publishing and also makes a nicer repository with proper tagging. Please try it first, and see how little the overhead is.

If you still wanted to write your own implicit-publishing workflow, we can help you setup the publishing token part, but won't be able to verify all the edge cases of the trigger-detection.
