### ISSUE TITLE
Error receiving background notifications for "Android 12" just when permissions are checked

### ISSUE THREAD

**Issue by jvv73** [dart-lang/pub-dev#6388]
Hello,

I am a bit desperate with an error when receiving push notifications in the background, and it is failing due to the error that I indicate below,

I was looking for possible solutions but I haven't found anything that worked, can you help me, maybe it's a bug in the firebase_messaging library? Has anyone experienced something similar?

### **Devices & versions:**

- [FAIL] Physical Devide with Android 12: **_Fail_**
- [✓] Physical Devide with Android 13: _**run perfect**_
- [✓] Physical Devide with IOs 16.2: _**run perfect**_

**NOTE**: I'm not sure if other versions prior to 12 get this error

### **Flutter code where the error occurs:**

I have tried both possibilities with the same result:

`NotificationSettings settings = await FirebaseMessaging.instance.requestPermission();`

OR

`NotificationSettings settings = await FirebaseMessaging.instance.getNotificationSettings();`

### **Flutter Error:**

```
I/flutter (11341): FlutterFire Messaging: An error occurred in your background messaging handler:

I/flutter (11341): [firebase_messaging/unknown] Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
```

### **Flutter environment:**

**plugins related and installed:**
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  permission_handler: ^10.2.0

**fllutter doctor -v**
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-arm64, locale es-ES)
    • Flutter version 3.7.0 on channel stable at /Users/josevv/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (hace 9 días), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/josevv/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • NE2213 (mobile) • eea79ab4 • android-arm64  • Android 12 (API 31)
    • macOS (desktop) • macos    • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by isoos** [comment]
@jvv73: this repository is for the pub.dev site, and not individual packages hosted on the site. Please visit the package's issue tracker to report issues.
