### ISSUE TITLE
Dart 3 ready badge reported incorrectly

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#6412]
A community member reported this issue: It looks like the [Dart 3 ready](https://github.com/dart-lang/pub-dev/issues/6023) badges are in some cases being applied to packages that don't support null safety?

That is not expected; Dart 3 only requires null safety. The following two tests must pass with a Dart 3 alpha SDK to get the badge:

  1. `dart pub get` / `flutter pub get` succesfully completes (this will fail if the SDK constraint don't enable null safety)
  2. `dart analyze` / `flutter analyze` passes with no errors (this will report failures for partial/unsound null safety)

**Comment by sigurdm** [comment]
https://pub.dev/packages?q=is%3Adart3-ready+-is%3Anull-safe shows we have 8259 not null safe packages that are incorrectly reported dart 3 ready.

**Comment by sigurdm** [comment]
This probably only affects non-flutter packages (flutter analyze has an implicit pub get, dart analyze doesn't).

**Comment by sigurdm** [comment]
A fix has landed in pana (https://github.com/dart-lang/pana/pull/1198) and is deployed. We plan to migrate traffic if everything works out.

**Comment by sigurdm** [comment]
We have migrated, waiting for analysis to triggle in.
https://pub.dev/packages?q=is%3Adart3-ready+-is%3Anull-safe now has 6713 packages - not sure how up-to-date the search index is here...

Closing this - assuming things will soon fall in place.
