### ISSUE TITLE
Add documentation of previous package versions to the documentations page 

### ISSUE THREAD

**Issue by folaoluwafemi** [dart-lang/pub-dev#6415]
I am currently working on migrating a codebase I just inherited from an old version to latest version of numerous packages and the codebase used deprecated and removed apis of the various packages.
For the ones that are removed, it is quite difficult to know what they were replace with in it's newer version.
It would be very helpful if package documetations had docs of each release version, so I can easy trace back and check.

**Comment by Mastersam07** [comment]
You are able to visit the documentation of the old package version on pub.dev.

What you have to do is to go to the version tab and click the version of choice. It should open you the package with exactly that verision. Compare below:

[http v0.11.1](https://pub.dev/packages/http/versions/0.11.1)
[http vlatest](https://pub.dev/packages/http)
