### ISSUE TITLE
Strange relevance ordering in search

### ISSUE THREAD

**Issue by spydon** [dart-lang/pub-dev#6420]
![image](https://user-images.githubusercontent.com/744771/218419824-eccdfa4f-921e-4bff-af2b-30b38e791c14.png)

It feels like it would make more sense to order the package that exactly matches the search as the top package when ordering by relevance? I doubt many people are looking for the Cupertino package when they are searching for Flame. 😅

**Comment by isoos** [comment]
Exact package name matches are moved to the top, however, SDK API matches have even higher rank. It is debatable if/how we should reduce the match rank of an icon constant though...

**Comment by spydon** [comment]
It seems like this issue is back.
![Screenshot_20231221-135348.png](https://github.com/dart-lang/pub-dev/assets/744771/e680b89d-ecd5-486b-9f17-88fa9ff8df2c)

**Comment by isoos** [comment]
@spydon: please do not reuse old issues like this one. However, in this case, this is to be expected: `cupertino` is a Flutter SDK package (with the `flame` symbol as part of its API), and we display those before the regular package matches.

**Comment by spydon** [comment]
> @spydon: please do not reuse old issues like this one. However, in this case, this is to be expected: `cupertino` is a Flutter SDK package (with the `flame` symbol as part of its API), and we display those before the regular package matches.

I thought #6443 was supposed to give those icons lower search relevance? I can open a new one if the current behavior isn't intended.

**Comment by isoos** [comment]
@spydon: true, we may have a regression there. Let's just reopen this for now.
