### ISSUE TITLE
Pub dev analysis server should not deduct points from an FFI package that has unused members in the generated files

### ISSUE THREAD

**Issue by Haidar0096** [dart-lang/pub-dev#6422]
- I am developing a dart ffi plugin that exports bindings to C code ([the package](https://pub.dev/packages/image_magick_ffi)).
- I use ffigen tool to autogenerate bindings to native code, then I expose these bindings through my plugin.
- When I upload the package to pub.dev, I notice some points were deducted from the rating because of "unused members", when looking at the explanation, I see the warnings come from the files generated by ffigen. 

It would be really nice if this scoring rule can be modified to account for files generated by ffigen which are not under our control when writings bindings to third party apis.

[This is an example](https://github.com/Haidar0096/image_magick_ffi/blob/master/lib/src/magick_wand_bindings_generated.dart) of a problematic generated file by ffigen.

**Comment by sigurdm** [comment]
I think we should fix ffigen to output `// ignore-for-file` lines, such that they analyze cleanly.
@dcharkes wdyt - does that sound reasonable?

**Comment by sigurdm** [comment]
Seems like we already have an issue here: https://github.com/dart-lang/ffigen/issues/270
Closing this one in favor of that.
