### ISSUE TITLE
some packages showcase Images not loading in pub.dev library

### ISSUE THREAD

**Issue by At738343** [dart-lang/pub-dev#6457]
i have been all ready mention the issue in title
e.g :-check this [flutter_spinkit](https://pub.dev/packages/flutter_spinkit)
<img width="740" alt="Screenshot 2023-02-28 at 11 18" src="https://user-images.githubusercontent.com/92142995/221765527-f81f95ae-d0c5-4152-be65-f47ee6b851d1.png">

**Comment by At738343** [comment]
i face this issue for more than 3-4 months

**Comment by isoos** [comment]
@At738343: what is your network setup (country, ISP, vpn)?

**Comment by sigurdm** [comment]
Also can you access the image directly? https://raw.githubusercontent.com/ybq/AndroidSpinKit/master/art/RotatingPlane.gif

**Comment by sigurdm** [comment]
@salehdemir how would you fix this? It seems to be a connection problem...

**Comment by salehdemir** [comment]
@sigurdm I also think so let me check it

**Comment by At738343** [comment]
fixed

**Comment by sigurdm** [comment]
@At738343 can we close this issue?

**Comment by isoos** [comment]
Closing as the issue seems to be unrelated to pub.dev
