### ISSUE TITLE
null safety issues

### ISSUE THREAD

**Issue by AhmedHosni19** [dart-lang/pub-dev#6460]
URL: https://pub.dev/packages/data_usage/example

The code is not up-to-date with null safety please fix it as soon as you can

**Comment by AhmedHosni19** [comment]
please I need this example soon

**Comment by isoos** [comment]
@AhmedHosni19: this repository is for the pub.dev site, and not for individual packages. Please use the package's repository (below the metadata section, in this case: https://github.com/Zfinix/data_usage ) to contact the author(s) of the package.
