### ISSUE TITLE
flutter_acrylic version 1.1.0+1 should not appear "dart 3 ready"

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#6462]
See: https://pub.dev/packages/flutter_acrylic/versions/1.1.0+1

In score we even see.
```
INFO: Using a colon as a separator before a default value is deprecated and will not be supported in language version 3.0 and later.
lib/window.dart:94:16

   ╷
94 │     Color color: Colors.transparent,
   │                ^
   ╵
```

**Comment by sigurdm** [comment]
I don't think "Not supported in language v. 3.0" means "Not supported by the dart 3.0 sdk" You should still be able to consume packages language versions down to 2.12 with a dart 3 sdk - thus "dart 3 ready".
