### ISSUE TITLE
Anchors in documentations won't scroll the page

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/pub-dev#6471]
### Step to reproduce
* Visit https://pub.dev/documentation/build_runner/latest.
* Click the *Contributing* link.
* The URL has changed, but the page didn't scroll.

https://user-images.githubusercontent.com/15884415/222632390-2202d068-9eae-4161-966c-5dec19581c62.mp4

**Comment by isoos** [comment]
Thanks for reporting this!

@jonasfj: I think this is a result of `--sanitize-html` parameters we are using on dartdoc, as without it we do have the `id="usage"` and similar anchor attributes.

**Comment by jonasfj** [comment]
Yeah, this is a bug we created in `dartdoc`.

**Comment by isoos** [comment]
This has been fixed and deployed.
