### ISSUE TITLE
I'm not sure how to tell a package supports web

### ISSUE THREAD

**Issue by JCKodel** [dart-lang/pub-dev#6476]
I have two published packages, both made with `flutter --org br.com.kodel --project-name xxx --template package .`

One of them shows full support for all platforms, while the other is missing web support.

![image](https://user-images.githubusercontent.com/379339/223173601-56492491-8a3f-4e65-973c-e29c4c6dc63b.png)

How is this determined?

**Comment by JCKodel** [comment]
Nevermind... pub.dev already shows this by clicking on score, Platform support, then it gives us a nice description of the reason:

Package not compatible with platform Web
Because:

package:eva/eva.dart that imports:
package:eva/src/log/log.dart that imports:
dart:isolate

**Comment by sigurdm** [comment]
Hmm - Is there some way we could link from the platform tags to the scores page?

**Comment by isoos** [comment]
On the search result page we link the scores area to the scores page, and the tags to the tags search refinement. In this case it would be the lack of tag that could be linked to the score page, but I don't see UI-wise how it would work out.

**Comment by JCKodel** [comment]
Suggestion:

![image](https://user-images.githubusercontent.com/379339/223503982-ede66e9c-2181-4105-a817-46455409c405.png)

(some line-through reddish clickable link pointing to the reason why it is not supported on that platform)
