### ISSUE TITLE
I think Pub.dev is again down

### ISSUE THREAD

**Issue by Manishmg3994** [dart-lang/pub-dev#6502]
Today we are facing issues with pub.dev and also while we hit
```
dart pub get
```
or
```
flutter pub get
```
In total the Server is down today (date 16-March -2023)
Hope you will Resolve this Issue Soon

**Comment by BolisettySujith** [comment]
yeah

**Comment by sigurdm** [comment]
I can access pub.dev and do `pub.get`.

What error codes/error messages are you getting?

**Comment by Dharini17** [comment]
Hello , I'm also getting same thing & it says below 

This site can’t be reached. pub.dev took too long to respond.

**Comment by isoos** [comment]
Can you please download and run this script, reporting back its output?
https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart

This looks like a network/ISP/config issue, but we can't really debug it remotely.

**Comment by Dharini17** [comment]
Can you explain some steps how to do that or where to put this file & run

**Comment by isoos** [comment]
> Can you explain some steps how to do that or where to put this file & run

download the file, and the run `dart check_domain_access.dart` (location doesn't matter)

**Comment by Dharini17** [comment]
/Users/user/Documents/flutter/bin/cache/dart-sdk/bin/dart --enable-asserts /Volumes/shopno/test_projects/test_web/lib/check_domain_access.dart
Testing host resolves...
- pub.dev IPv4 resolve and connect succeeded: 0 / 4
- pub.dev IPv6 resolve and connect succeeded: 0 / 4
- pub.dartlang.org IPv4 resolve and connect succeeded: 1 / 1
- pub.dartlang.org IPv6 resolve and connect succeeded: 1 / 1
- storage.googleapis.com IPv4 resolve and connect succeeded: 16 / 16
- storage.googleapis.com IPv6 resolve and connect succeeded: 16 / 16
Testing one connection per request...
Unhandled exception:
TimeoutException after 0:00:15.000000: Future not completed

Process finished with exit code 255

**Comment by sigurdm** [comment]
Seems like you have access to pub.dartlang.org

Seems like dns resolution is failing.

A workaround could be to do
```
PUB_HOSTED_URL=https://pub.dartlang.org pub get
```
@Manishmg3994 where are you located?

**Comment by BolisettySujith** [comment]
> Can you please download and run this script, reporting back its output? https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart
> 
> This looks like a network/ISP/config issue, but we can't really debug it remotely.

❯ dart check_domain_access.dart
Testing host resolves...
- pub.dev IPv4 resolve and connect succeeded: 4 / 4
- pub.dev IPv6 resolve and connect succeeded: 0 / 4
- pub.dartlang.org IPv4 resolve and connect succeeded: 1 / 1
- pub.dartlang.org IPv6 resolve and connect succeeded: 0 / 1
- storage.googleapis.com IPv4 resolve and connect succeeded: 16 / 16
- storage.googleapis.com IPv6 resolve and connect succeeded: 0 / 4
Testing one connection per request...
Unhandled exception:
SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 104), address = pub.dev, port = 60268



This is what I got...

**Comment by Dharini17** [comment]
> 

this website is also not working

https://pub.dartlang.org/

**Comment by sigurdm** [comment]
> this website is also not working
> https://pub.dartlang.org/

That site redirects you to pub.dev (for the web-site, the package api should not redirect).

**Comment by BolisettySujith** [comment]
> > Can you please download and run this script, reporting back its output? https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart
> > This looks like a network/ISP/config issue, but we can't really debug it remotely.
> 
> ❯ dart check_domain_access.dart Testing host resolves...
> 
> * pub.dev IPv4 resolve and connect succeeded: 4 / 4
> * pub.dev IPv6 resolve and connect succeeded: 0 / 4
> * pub.dartlang.org IPv4 resolve and connect succeeded: 1 / 1
> * pub.dartlang.org IPv6 resolve and connect succeeded: 0 / 1
> * storage.googleapis.com IPv4 resolve and connect succeeded: 16 / 16
> * storage.googleapis.com IPv6 resolve and connect succeeded: 0 / 4
>   Testing one connection per request...
>   Unhandled exception:
>   SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 104), address = pub.dev, port = 60268
> 
> This is what I got...


❯ dart check_domain_access.dart
Testing host resolves...
- pub.dev IPv4 resolve and connect succeeded: 4 / 4
- pub.dev IPv6 resolve and connect succeeded: 4 / 4
- pub.dartlang.org IPv4 resolve and connect succeeded: 1 / 1
- pub.dartlang.org IPv6 resolve and connect succeeded: 1 / 1
- storage.googleapis.com IPv4 resolve and connect succeeded: 16 / 16
- storage.googleapis.com IPv6 resolve and connect succeeded: 4 / 4
Testing one connection per request...
Testing connection reuse...
- iteration # 1/10...
- iteration # 2/10...
- iteration # 3/10...
- iteration # 4/10...
- iteration # 5/10...
- iteration # 6/10...
- iteration # 7/10...
- iteration # 8/10...
- iteration # 9/10...
- iteration # 10/10...
Done.


After switching to a different network, it was now working fine for me...

**Comment by Dharini17** [comment]
Is their any solution for this cause I can't do pub get

**Comment by isoos** [comment]
@Dharini17: have you tried `PUB_HOSTED_URL=https://pub.dartlang.org pub get` as suggested earlier?

**Comment by Dharini17** [comment]
Yes but it gives me this error,

zsh: command not found: pub

**Comment by sigurdm** [comment]
Oh - should be`PUB_HOSTED_URL=https://pub.dartlang.org dart pub get` :)

**Comment by Dharini17** [comment]
yeah it's worked but it seems like something goes in lnfinite looping, but not giving further logs

Resolving dependencies... (3:52.9s)

**Comment by sigurdm** [comment]
Try to interrupt it with Ctrl+C and then run
`PUB_HOSTED_URL=https://pub.dartlang.org dart pub get --verbose`

**Comment by Dharini17** [comment]
It logs like

IO  : Get versions from https://pub.dev/api/packages/flutter_lints.
IO  : HTTP GET https://pub.dev/api/packages/flutter_lints
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos

....

IO  : Attempt #2 for fetching versions for "flutter_lints" from "https://pub.dev/api/packages/flutter_lints"
IO  : HTTP GET https://pub.dev/api/packages/flutter_lints
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos

....

after 4 attempts in  message prompt like,

The Flutter device daemon cannot be started. 
Please check your configuration and restart the IDE.  
You may need to increase the maximum number of file handles available globally

**Comment by Dharini17** [comment]
on another try it gives,

SLVR: Version solving took 0:09:10.396276 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (9:10.447s).
ERR : Got socket error trying to find package flutter_lints at https://pub.dev.

**Comment by Manishmg3994** [comment]
**Thanks Flutter&Dart Team now Its working Fine (Resolved Timing Evening (IST)(Date :- 17-March-2023) )**
