### ISSUE TITLE
Again it's not loading showcase

### ISSUE THREAD

**Issue by At738343** [dart-lang/pub-dev#6552]
URL: https://pub.dev/packages/flutter_spinkit

<Describe your issue or suggestion here>

**Comment by isoos** [comment]
The showcase images seem to be directly linked to github user content URLs like the following:
https://raw.githubusercontent.com/ybq/AndroidSpinKit/master/art/RotatingPlane.gif

These look good to me and they are loaded properly.

My suspicion is that your network or your ISP may have problems accessing these images. Could you please share more details about these?
