### ISSUE TITLE
Add the ability to filter packages

### ISSUE THREAD

**Issue by joranmulderij** [dart-lang/pub-dev#6565]
When looking for packages on pub.dev, it would be really nice to be able to filter through types of packages.
Often when looking for UI packages, I come across native api packages, or the other way around.

It would be helpful if there was a more structured metadata point that could be used to filter.

I would consider there to be several ways of achieving this:

* Adding a `type` parameter that package owners can set. For example `native-api`, `ui-component`, or `api-client`.
* Allow package owner to set multiple tags, like the ones mentioned above. 

This would also allow for tags like `unfinished` and `experimental`.

**Comment by jonasfj** [comment]
We just shipped topics on pub.dev, see: pub.dev/topics

**Comment by joranmulderij** [comment]
@jonasfj I don't think this is supposed to show.
This only happens on the `/topics` page:

![image](https://github.com/dart-lang/pub-dev/assets/66296620/7acc30ec-c8b3-480c-9935-0c7ebc87cdcd)

Just quickly letting you know.

**Comment by jonasfj** [comment]
lol, I guess I filled the cache, we'll ship a fix asap.
