### ISSUE TITLE
Upvoting Packages Results in No Reaction when User is Logged Out

### ISSUE THREAD

**Issue by pattobrien** [dart-lang/pub-dev#6581]
## Reproduction Steps

 * Be logged out of pub.dev
 * Try selecting upvote (thumbs-up) on a particular package
 
## Expectation
User should be brought to the login screen so that the user can login, so that the upvote could subsequently be recorded.

## Actual Result
User cannot upvote and no redirect is taken to a login page (i.e. nothing happens).

**Comment by Spyy004** [comment]
Hey, I would love to work on this issue.

**Comment by isoos** [comment]
@Spyy004 this has been addressed in #6600.
