### ISSUE TITLE
Getting a 404 for latest gmail API

### ISSUE THREAD

**Issue by gtaubman** [dart-lang/pub-dev#6593]
https://pub.dev/documentation/googleapis/latest/gmail.v1/gmail.v1-library.html was working last week but now gives me a 404.

**Comment by isoos** [comment]
Not sure if it was a googleapis change or a change in dartdoc being used to generate the docs, but now it is on the following URL:
https://pub.dev/documentation/googleapis/latest/gmail_v1/gmail_v1-library.html
