### ISSUE TITLE
Documentation view for googleapis package doesn't show package names in sidebar

### ISSUE THREAD

**Issue by whesse** [dart-lang/pub-dev#6594]
URL:  https://pub.dev/documentation/googleapis/latest/

https://pub.dev/documentation/googleapis/latest/pubsub.v1/pubsub.v1-library.html
is a link from the body of the page, and gives a 404.

The listing of the libraries within the googleapis package lists all their names as "v1", dropping the name of the actual library.

The link from the body test to the API of the pubsub library gives a 404.
The correct link, which shoudl be there instead, is 
https://pub.dev/documentation/googleapis/latest/pubsub_v1/pubsub_v1-library.html

**Comment by isoos** [comment]
Not sure what changed, but documentation is now fixed.
