### ISSUE TITLE
API end-point with completion data for topics

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#6639]
Let's do an API end-point with completion data for topics:
```js
// Request:
// GET https://pub.dev/api/topic-name-completion-data
// Accept-Encoding: gzip
// Accept: application/json

// Response:
// 200 OK
// Content-Encoding: gzip
// Content-Type: application/json; charset="utf-8"
// Cache-Control: public, max-age=28800

{
  "topics": [
    {"name": "server", "count": "8"},
    ...
  ],
}
```

Following conditions:
 * Unless the request carries `Accept-Encoding: gzip` or `Accept-Encoding: *` the request must be rejected with 406.
 * Unless the request carries `Accept: application/json, ...` the request must be rejected with 406.

Note. we encode the response as gzipped JSON and cache this in redis.

As this is intended for API clients only, we reject anyone who doesn't accept gzipped json. We can always allow more in the future.

We let this API end-point return top 10k topics? or something like that. Whether it's 10k or 30k is probably not important. But there should probably be some sanity limit.

See also: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation

**Comment by jonasfj** [comment]
In support of https://github.com/dart-lang/sdk/issues/52256

**Comment by szakarias** [comment]
Done in https://github.com/dart-lang/pub-dev/pull/6705
