### ISSUE TITLE
Analyze package (pub points) with outdated packages versions

### ISSUE THREAD

**Issue by deandreamatias** [dart-lang/pub-dev#6646]
### Description

I update somes packages of flutter form builder ecosystem on pre-release ([example](https://pub.dev/packages/flutter_form_builder/versions/9.0.0-dev.3/score)) but the score is too low

I think that this is because use old packages versions to analyze the package: `Analysed with Pana 0.21.32, Flutter 3.10.0-1.5.pre, Dart 3.0.0-417.4.beta.`

I can decide what versions use to analyze my packages or this is responsible of pub.dev team?

![Screenshot 2023-05-11 at 13 06 54](https://github.com/dart-lang/pub-dev/assets/21011641/1ad84ed7-511b-4928-b311-88e4ae708eb8)

**Comment by sigurdm** [comment]
Yeah - we very soon will deploy a new version of pub.dev that analyzes with flutter 3.10 stable.

**Comment by isoos** [comment]
> I can decide what versions use to analyze my packages or this is responsible of pub.dev team?

The pub.dev team updates the analysis SDKs on an ongoing basis. There may be small delays around releases like today, but we are usually closely tracking the latest stable versions. We re-analyze the packages (at least the latest few versions) every time there is an upgrade, so you usually don't need to worry much about the scores, it will self-correct once the release is rolled out and analysis is completed.

**Comment by deandreamatias** [comment]
Ok
Thanks a lot for quickly response!
So, I will close this issue
