### ISSUE TITLE
Readme texts not visible on pub.dev

### ISSUE THREAD

**Issue by shan-shaji** [dart-lang/pub-dev#6649]
URL: https://pub.dev/packages/day_picker

![image](https://github.com/dart-lang/pub-dev/assets/42430941/22f61b1d-7aac-49e4-a640-3ad21d43ee20)

**Comment by isoos** [comment]
@shan-shaji: are you using some kind of dark-mode browser extension?

**Comment by shan-shaji** [comment]
![image](https://github.com/dart-lang/pub-dev/assets/42430941/fdff966c-fe50-4065-8873-86943e3deb9f)
I do have these extensions

**Comment by shan-shaji** [comment]
Closing this issue as i checked on my phone and on another browser it's working fine.
