### ISSUE TITLE
Links in the changelog tab don't work correctly when within parentheses

### ISSUE THREAD

**Issue by davidmartos96** [dart-lang/pub-dev#6658]
### Explain the issue
When the changelog of a package contains a link surrounded by parentheses, then rendered link is including the closing parentheses.

Sample changelog
```
## 0.5.6

- Upgrade `SQLCipher` to version `4.5.4` (https://www.zetetic.net/blog/2023/04/27/sqlcipher-4.5.4-release).
```

 
When clicking the link, the URL is incorrect, because is including the close parentheses.

![image](https://github.com/dart-lang/pub-dev/assets/22084723/397aa1de-4842-4868-a02d-9649d85b5ea0)

**Comment by isoos** [comment]
@davidmartos96: Thanks for reporting this! I think this is fixed in `package:markdown 7.1.0`. pub.dev will upgrade to use it in the coming week, until then I'd keep this issue open.

**Comment by davidmartos96** [comment]
Thanks!

**Comment by isoos** [comment]
This seems to be fixed with the new release:
https://pub.dev/packages/sqlcipher_flutter_libs/changelog

**Comment by davidmartos96** [comment]
Great, thanks for the update @isoos
