### ISSUE TITLE
Uploading package with gif as screenshot fails

### ISSUE THREAD

**Issue by JakesMD** [dart-lang/pub-dev#6669]
Hi!

- I published a [Flutter package](https://pub.dev/packages/go_router_tabs) with [this gif](https://github.com/JakesMD/flutter_go_router_tabs/blob/main/screenshots/preview.gif) defined as a screenshot in pubspec.yaml
- The screenshot does not show up
- Under the ["Scores" section on pub.dev](https://pub.dev/packages/go_router_tabs/score) it shows errors:
```
Found 4 issues. Showing the first 2:
    /tmp/pana_OZKWTX/screenshots/preview.gif: Tried interpreting screenshot as WebP with webpinfo "/tmp/pana_OZKWTX/screenshots/preview.gif" failed with exit code 2.
    /tmp/pana_OZKWTX/screenshots/preview.gif: Converting screenshot with cwebp "/tmp/pana_OZKWTX/screenshots/preview.gif" -o "/tmp/PFAZTZ/gen/preview.webp" failed with exit code 255.
```

<img width="805" alt="Screenshot 2023-05-18 at 19 38 41" src="https://github.com/dart-lang/pub-dev/assets/71591438/10ce66f4-af79-4484-8a19-ea9673d6c86d">

---

This is in my pubspec.yaml:
```
screenshots:
  - description: 'This is an animation of a web app navigating between tabs using this package.'
    path: screenshots/preview.gif
```

**Comment by szakarias** [comment]
fixed by https://github.com/dart-lang/pub-dev/pull/6693
