### ISSUE TITLE
Question about the package scores / missing points in pana

### ISSUE THREAD

**Issue by SoftwareFreak1** [dart-lang/pub-dev#6672]
Hi ^^

I run pana against my package to verify the scores keeps at the maximum, but after publishing to pub.dev I noticed that pana reports a maximum of 130 points, but pub.dev has 140 points using the same version of pana.
Are the 10 missing points added specific by pub.dev?

Package scores:
<img width="629" alt="image" src="https://github.com/dart-lang/pub-dev/assets/45599667/7368b715-6e14-432b-b5a5-6e34aa7405d7">

Pana result:
<img width="413" alt="image" src="https://github.com/dart-lang/pub-dev/assets/45599667/04f705da-714b-41ba-a880-00a36c46c8e9">

**Comment by isoos** [comment]
pub.dev at the moment runs pana + dartdoc separately, and adding the extra 10 points of dartdoc documentation score separately. We are planning to rewrite pana to run dartdoc as part of the standalone process, so there will be no such difference, but we are not there yet.

**Comment by SoftwareFreak1** [comment]
Ok, thanks!
