### ISSUE TITLE
Markdown table does not rendered on pub.dev page, but renders fine on repository

### ISSUE THREAD

**Issue by Luckey-Elijah** [dart-lang/pub-dev#6674]
I've publish a package at: https://pub.dev/packages/dfn/versions/0.0.2 and have my repo at: https://github.com/Luckey-Elijah/dfn/tree/ced178c8dbd546827a35f8ac3c2ad606f8f89e38

The table under "Usage" is not rendered correctly (or at all) on the pub.dev page. It is meant to look like the the way it's rendered on the github page.

Any ideas why this is the case?

**Comment by isoos** [comment]
@Luckey-Elijah: thanks for reporting, the issue seems to be in `package:markdown`, I've reported an issue here: https://github.com/dart-lang/markdown/issues/543

I think you may be able to fix it too by separating the "Usage" paragraph with an additional extra line from the table.
