### ISSUE TITLE
Some packages show errors in dart-3 section, but seem to pass static analysis

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#6683]
Example https://pub.dev/packages/extended_image

**Comment by isoos** [comment]
Another example: `cbor 6.0.0`.

I've found the root cause: we are using stable SDK for the regular static analysis, and preview SDK for the Dart 3 compatibility check. It made sense pre-3.0, but doesn't make sense anymore, and we should probably also rewrite the analysis in pana.

**Comment by isoos** [comment]
This has been fixed.
