### ISSUE TITLE
trigram matching in search is extremely slow

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#6692]
When we call `searchWord` for each word in the search query, and we then create `parts` as trigrams for each word.
And for each word for each package for each trigram in word, we do `String.contains`, it'll be slow.

https://github.com/dart-lang/pub-dev/blob/84a249aa64905b30775fb7febc78ab9988b092ca/app/lib/search/mem_index.dart#L492-L496

Side note: I'm not even sure this is sound, we don't convert the words to lowercase before splitting them into trigrams. So... those with uppercase will never match anything.

Perhaps we should do something much simpler here, and accept poor scores in favor of speed.

-----------------

If we wanted to search package names with trigrams we should probably convert all words into a single set of trigrams. Then represent that with `Set<String>` or a sorted list of `Uint32List` and for each package name do: 
```dart
for (var i = 0; i < packageName.length - 2; i++) {
  if (trigramSet.contains(packageName.substring(i, i + 3))) {
     // match
  }
}
```

or something even smarter.

-----------------

As what we have has severe degenerate performance, I'm okay with simply making our index dumber and scoring dumber, in favor of faster results.

@isoos should we perhaps consider aborting after each word in:
```dart
      for (final word in words) {
        final nameScore =
            _packageNameIndex.searchWord(word, packages: packages);
        final descr =
            _descrIndex.searchWords([word], weight: 0.90, limitToIds: packages);
        final readme = _readmeIndex
            .searchWords([word], weight: 0.75, limitToIds: packages);
        coreScores.add(Score.max([nameScore, descr, readme]));
      }
```

In `InMemoryPackageIndex._searchText` ?

**Comment by sigurdm** [comment]
Can we close this for now?

**Comment by isoos** [comment]
Let's close it!
