### ISSUE TITLE
Mixed case topics should not be allowed

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#6719]
Didn't we decide to make them all lowercase, or am I remembering wrong @szakarias 

https://pub.dev/packages?q=topic%3AcopyWith

**Comment by sigurdm** [comment]
Hmm - that's a bit late to change.

Maybe we can normalize camelCase to names-with-dashes

**Comment by isoos** [comment]
I think we have a bug, as the check is in place, but the method that checks it is not called from production code, only test:
https://github.com/dart-lang/pub-dev/blob/master/pkg/pub_package_reader/lib/pub_package_reader.dart#L774C24-L830

We should enable the checks, and people will need to change their topics to lowercase-only.

**Comment by isoos** [comment]
I think this has been deployed now.
