### ISSUE TITLE
<Summarize your issues here>

### ISSUE THREAD

**Issue by MuoBinAlshekh** [dart-lang/pub-dev#6742]
URL: https://pub.dev/packages?q=publisher%3Abelin.io+platform%3Aandroid+platform%3Alinux+platform%3Aios+platform%3Amacos+platform%3Aweb+platform%3Awindows+sdk%3Adart+sdk%3Aflutter+license%3Aosi-approved+is%3Aflutter-favorite+show%3Aunlisted+is%3Anull-safe+has%3Ascreenshot+is%3Adart3-compatible&sort=updated

<Describe your issue or suggestion here>

**Comment by sigurdm** [comment]
What is the issue?
