### ISSUE TITLE
`/// @nodoc` annotations work locally, but not on pub.dev

### ISSUE THREAD

**Issue by osa1** [dart-lang/pub-dev#6760]
In protobuf package we use `/// @nodoc` syntax to hide members that are supposed to be used by the generated code and not by the users of the library.

When I generate the documentation locally it works as expected and hides the members.

However we just published a new version on pub.dev, and `/// @nodoc` members appear in documentation: https://pub.dev/documentation/protobuf/latest/protobuf/GeneratedMessage-class.html

To compare, run `dart doc .` in https://github.com/google/protobuf.dart/tree/a9bf79fae6e767bcf6e716965fc4a5432730b3af/protobuf and navigate to the same class. The `$_` prefixed members shown in the public documentation will be gone in the local version.

I'm using Dart 3.0.0 stable.

**Comment by sigurdm** [comment]
I think what's happening is that `latest` is pointing to 2.1.0 still while docs are being generated for 3.0.0, so we are seeing the dartdoc of the old version without the `@nodoc` comments

Unfortunately, the versions page indicates that 3.0.0 has the docs generated. Maybe something is stuck in a cache somewhere.

**Comment by sigurdm** [comment]
![image](https://github.com/dart-lang/pub-dev/assets/8613953/99a6af5c-8c20-4c3b-bd0a-80b40a0651c8)

**Comment by osa1** [comment]
Yeah, it took a few minutes but the page is updated now. The confusing part was when I replaced the "latest" in the URL with "3.0.0" it redirected to "latest", with the old documentation..
