### ISSUE TITLE
Allow removing unused Dart 1 package names 

### ISSUE THREAD

**Issue by simc** [dart-lang/pub-dev#6772]
There are many super old Dart 1 packages that have been discontinued for almost 10 years and are extremely unlikely to be used by anyone. Still it is not allowed to publish a new package with the same name.

It would be nice if the name squatting policy could be adjusted or maybe even all Dart 1 packages could be removed as they serve no purpose.

Examples are: `animation`, `validator`, `serial_port`, `zip`, `discord`, `notification`, `cookie`, `debounce`, `jwt`, `router`, `dart_orm` and around 2200 others

**Comment by isoos** [comment]
We don't have any process for such takeovers. I'd recommend reaching out to the original authors, in many cases I had been able to get the package ownership transferred to me, once I demonstrated what I wanted to do with the package...

**Comment by simc** [comment]
I tried that. In my case the original author was the Dart team and I tried reaching out to support@pub.dev and was told the name squatting policy does not allow it.

**Comment by isoos** [comment]
Sometimes you may need to just find a good name instead :)

**Comment by isoos** [comment]
Closing, as we don't have any direct plan to support package takeover.
