### ISSUE TITLE
Issue on search

### ISSUE THREAD

**Issue by ghost** [dart-lang/pub-dev#6789]
URL: https://pub.dev/packages/firebase_storage

Search for:

-is:dart3-compatible is:null-safe
is:null-safe -is:dart3-compatible
does not give the same results.

**Comment by isoos** [comment]
These two has the same result for me (no packages found):
https://pub.dev/packages?q=-is%3Adart3-compatible+is%3Anull-safe
https://pub.dev/packages?q=is%3Anull-safe+-is%3Adart3-compatible

@midhileshraj01 What's the result you have seen? Can you also link to it/screenshot it?

**Comment by isoos** [comment]
Right now `harmony_sdk 0.0.8` is in this weird state where it is null safe, but not dart3 compatible.
The reason may be the analysis timeout:
```
Failed to analyze Dart 3 compatibilty:
Unable to run pub upgrade.
Exceeded timeout of 0:02:00.000000
```

**Comment by isoos** [comment]
I think we have fixed this.
