### ISSUE TITLE
README marker-down parsing issue with code block when starting with whitespace

### ISSUE THREAD

**Issue by slightfoot** [dart-lang/pub-dev#6791]
URL: https://pub.dev/packages/url_launcher

When browsing this README you'll notice the Android code example is missing. This is because the README in Github has a space just before the code-block type `xml`

https://github.com/flutter/packages/blob/main/packages/url_launcher/url_launcher/README.md?plain=1#L75
![image](https://github.com/dart-lang/pub-dev/assets/906564/19f21dde-015b-4d00-bf58-66f8822dca06)

This causes the pub parser to display initial code block tag and hide the rest of the block.

![image](https://github.com/dart-lang/pub-dev/assets/906564/6a71b548-ab04-4f5b-9a33-8b437aa81b30)

This however works fine on Github.

![image](https://github.com/dart-lang/pub-dev/assets/906564/4abd79d8-eefa-442f-be0a-3e8ab16a7c03)

**Comment by slightfoot** [comment]
@kevmoo pinging this your way as not sure who is in-charge of pub.dev nowadays.

**Comment by isoos** [comment]
Reported a reduced reproducible case in https://github.com/dart-lang/markdown/issues/547
