### ISSUE TITLE
i found a problem , I hope you fix this soon

### ISSUE THREAD

**Issue by axroromonov** [dart-lang/pub-dev#6840]
<img width="1440" alt="Screenshot 2023-07-18 at 22 41 47" src="https://github.com/dart-lang/pub-dev/assets/76530966/4f12088b-3c4c-46d4-80c8-4135980341cf">
<img width="1243" alt="Screenshot 2023-07-18 at 22 41 31" src="https://github.com/dart-lang/pub-dev/assets/76530966/678dcc2b-e9c6-4eda-bd30-24d1debd7568">

**Comment by isoos** [comment]
@axroromonov: I don't see it from my location. You seem to be using direct IP address instead of `https://pub.dev/` - we can't guarantee what the content on third party proxies looks like. Can you check the original pub.dev site?

**Comment by axroromonov** [comment]
yesterday it was like this for a few minutes and later it was fixed, I refreshed again and again, I also checked flutter.dev and everything was fine

why did this happen? , do you know ?

**Comment by isoos** [comment]
Nothing happened on pub.dev, but again: you are not using pub.dev, rather what seems to be a proxy, which may modify the content that you are served with. Closing as there is nothing on our side that we can do with this.

**Comment by axroromonov** [comment]
aha okey , thank you
