### ISSUE TITLE
Add support for package tags

### ISSUE THREAD

**Issue by exoad** [dart-lang/pub-dev#6845]
Allow for tags to be added to a package similar to the tag feature for the GitHub repository description. 

If the `pubspec.yaml`'s `repository` field points to a GitHub repository, it should also be possible to import the tags from that repository and upload it to pub.dev

**Comment by isoos** [comment]
@exoad: wouldn't be this the same as topics? https://dart.dev/tools/pub/pubspec#topics

**Comment by exoad** [comment]
oh huh, whoops!
