### ISSUE TITLE
[Feature] Personal Favorites

### ISSUE THREAD

**Issue by rs5173** [dart-lang/pub-dev#6862]
Provide a personal favorites, I can put my favorite packages into it, I can classify all favorites, and even share them with others

**Comment by isoos** [comment]
You can like a package (if you are signed in on pub.dev), and you can see your liked packages later. We think this covers most of the personal tracking of favorite packages.

At the moment we don't plan to build features around maintaining and sharing lists, it seems to be that other communities are using `awesome-<*>` repositories to collect and share such lists.
