### ISSUE TITLE
"Pending analysis" status shows "Unknown Platforms" instead

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/pub-dev#6878]
I remember the tag should displayed as `PENDING ANALYSIS`, but we got `UNKNOWN PLATFORMS` instead.

![image](https://github.com/dart-lang/pub-dev/assets/15884415/f1610f71-6d94-4d21-b49f-dc5ac87582ad)

**Comment by isoos** [comment]
Thanks for reporting! We are switching to a new analysis process, this must have slipped...

**Comment by gmpassos** [comment]
Same here for many recently uploaded packages.

**Comment by gmpassos** [comment]
Seems to be OK now

**Comment by AlexV525** [comment]
Still seeing this when uploading a new package
![image](https://github.com/dart-lang/pub-dev/assets/15884415/694c0421-96b1-49ed-adaf-1affd573fb11)

**Comment by AlexV525** [comment]
Still seeing this when uploading a new package @isoos 

<img width="883" alt="image" src="https://github.com/dart-lang/pub-dev/assets/15884415/97502264-3a69-4731-8bea-a53efcde5106">

**Comment by isoos** [comment]
@AlexV525 thanks for pinging on this one, I've tracked down a potential stale cache issue, addressing it in https://github.com/dart-lang/pub-dev/pull/7816
