### ISSUE TITLE
API - latestStableVersion not returning on documentation endpoint

### ISSUE THREAD

**Issue by leoafarias** [dart-lang/pub-dev#6885]
When accessing a package documentation endpoint, i.e., `https://pub.dev/api/documentation/intl`, the `latestStableVersion` used to be returned in the payload. However, it seems that the endpoint no longer returns it. 

I wanted to confirm whether this is indeed an issue, or if it's a deprecation that I might have overlooked.

**Comment by leoafarias** [comment]
@isoos I am the maintainer of https://github.com/leoafarias/pub_api_client, I don't have any expectations of deprecation notice or support. Just want to know if it was meant to be removed so I can update our tests. Thanks for the quick response.

**Comment by isoos** [comment]
@leoafarias: As the documentation page on the pub.dev site doesn't need that field, I would expect that it will be removed for good. (I'm not sure if it is a recent change or it never needed it in the first place.)

I was not aware of the package, nor the extent of the APIs that it is using. Are you tracking the "unannounced" pub.dev API development closely? Do you know which parts are used more than the others?

**Comment by sigurdm** [comment]
Closing, as we no longer intend to maintain that API.
