### ISSUE TITLE
Pana should use stable version of Flutter instead of beta (3.12.0) on pub.dev

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/pub-dev#6898]
Related #6810.

Is it because a beta version should not named `x.y.z`?

![Screenshot_2023-08-10-01-24-10-12](https://github.com/dart-lang/pub-dev/assets/15884415/aeb10020-ade6-4b24-ad7b-322fcf761290)

**Comment by sigurdm** [comment]
Should be fixed in the upcoming release.

**Comment by AlexV525** [comment]
Sorry but can you explain more about the duplicate? I don't see its subset contains the info I required.
