### ISSUE TITLE
Help: I lost my package

### ISSUE THREAD

**Issue by chenenyu** [dart-lang/pub-dev#6900]
URL: https://pub.dev/my-packages

Hello, i published a package [flutter_l10n](https://pub.dev/packages/flutter_l10n) several years ago, now i can't find it in the pub console. Can you help me to find where is it? Thanks.

<img width="994" alt="image" src="https://github.com/dart-lang/pub-dev/assets/6647088/b7755105-343a-460c-9d38-25a4ded99db1">

Below is the activity log:

<img width="1040" alt="image" src="https://github.com/dart-lang/pub-dev/assets/6647088/c00477ef-67a4-4640-a23b-358edc12bcf2">

**Comment by isoos** [comment]
@chenenyu: did you have a second account or did you transfer ownership of the package?

In any case, please contact the email support as described on https://pub.dev/policy

**Comment by chenenyu** [comment]
@isoos Thank you for your replay. I have checked another account, and I couldn't find it there either.

**Comment by chenenyu** [comment]
I will seek help through email. Thank you!
