### ISSUE TITLE
Search not working properly

### ISSUE THREAD

**Issue by JCKodel** [dart-lang/pub-dev#6931]
URL: https://pub.dev/packages?q=platform%3Awindows+fluent+ui

1) Open pub.dev and search for `fluent ui`. The `fluent_ui` package is the 7th result.

2) Check the [X] Windows Platforms filter. The `flutter_ui` package vanishes from the result.

That package has availability for Windows platform (obviously).

I checked the Windows Platform filter to be more assertive and filter out some other `fluent` widgets =\

**Comment by isoos** [comment]
@JCKodel: thanks for reporting it! It seems to be that the root cause is search index picking up on the new version published event but not picking up the analysis completed event + our new sandbox-based analysis not triggering search to update itself.
