### ISSUE TITLE
Unable to change publisher's email address due to verification email not being sent

### ISSUE THREAD

**Issue by bjoernahrens** [dart-lang/pub-dev#6932]
I recently created a new publisher. As expected, it put my personal email address as the contact.
So, I want to change that to one that actually ends in the domain of the publisher.
This email is not a real mailbox, but forwards any mail to my personal mail if that is relevant.

When I try to change the email address, I get the expected warning that I need to verify the address and that a verification email will be send.
<img width="50%" alt="Confirm" src="https://github.com/dart-lang/pub-dev/assets/47995029/60f06987-9aa5-4bf4-810d-ec4e576377f9">

After I confirm, I get the message that the publisher has been updated.
<img width="50%" alt="Bildschirmfoto 2023-08-17 um 20 20 07" src="https://github.com/dart-lang/pub-dev/assets/47995029/89ea460c-c0a0-4da0-b7f6-cd606199963e">
On Safari, after the page reloaded, it still shows my current personal email. On Firefox, is shows the new email, at least until I navigate away from the page and open it again.

**The big issue is: I _never_ receive this verification email.**

I have tried it _many times_ on _multiple days_ with _multiple browsers_. It also does _not_ get sorted into my spam folder.
I have also verified that the address correctly forwards mails to my personal address.

**Comment by bjoernahrens** [comment]
@jonasfj Hi Jonas, I received your email :)

**Comment by matanlurey** [comment]
I also have this problem, it appears the verification process is not working.

**Comment by sigurdm** [comment]
Have you checked your spam folder ... ?

**Comment by matanlurey** [comment]
Yeah, that was the problem - I hadn't had to use my spam folder in ages :)

**Comment by sigurdm** [comment]
Reopening - I think we need to investigate how it can happen that gmail marks our mails as spam

**Comment by sigurdm** [comment]
Actually let me open a fresh issue: https://github.com/dart-lang/pub-dev/issues/7924
