### ISSUE TITLE
Documentation goes dead for a while after a package release

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub-dev#6933]
After a package is released, it takes some amount of time to analyze it and rebuild the documentation. For example, at the time of writing, `sass` 1.66.0 was released to pub 2 hours ago and is still listed as [PENDING ANALYSIS]. During this time, _no_ API documentation is available for this package. This is a bad experience for users of the package, and it breaks any automated link checking as well. Please only take down the old documentation once the new documentation is ready to serve.

**Comment by isoos** [comment]
/cc @jonasfj 

It seems that both here and in search, it would be better if we fall back not only in runtime versions, but also in versions. E.g. if all accepted analysis runtimes are pending or absent (for a version that has been just published), we should select the last stable version that has content in any analysis runtime (in descending order).
