### ISSUE TITLE
[calendar_date_picker2] package shows [UNKNOWN PLATFORMS] after new release

### ISSUE THREAD

**Issue by theideasaler** [dart-lang/pub-dev#6953]
I am the creator/publisher of package calendar_date_picker2 (https://pub.dev/packages/calendar_date_picker2).

I have released the new version of the package today and I saw it passed all testing and got 140 points not too long after the release.

But I just found the package is now showing [UNKNOWN PLATFORMS].

![IMG_8230](https://github.com/dart-lang/pub-dev/assets/17869748/6cd11c12-83a8-42b2-ae17-279c87f9d5af)

**Comment by isoos** [comment]
@theideasaler: Thanks for reporting this. We are aware of a bug that affects newly uploaded packages, and there is a fix that should land soon. You don't need to do anything, the analysis, scores and platform tags should correct themselves automatically.

**Comment by natsuk4ze** [comment]
@ Could you please change the tile of issue more versatile? like a "Analytics stuck in PENDING"

**Comment by theideasaler** [comment]
I can see the analysis points are back. 

But looks like the package's position among search results has completely changed

**Comment by isoos** [comment]
> But looks like the package's position in search results has completely changed

Could you please give us more details on that?

**Comment by theideasaler** [comment]
> > But looks like the package's position in search results has completely changed
> 
> 
> 
> Could you please give us more details on that?

It used to be the first search result when search by keyword "date picker" or "calendar picker" by using Search Relevance filter.

And it was on the first page when search by keyword "range picker", "multi picker"

**Comment by isoos** [comment]
> It used to be the first search result when search by keyword "date picker" or "calendar picker" by using Search Relevance filter.

The search index has not picked up the score change yet, it still has the pre-analysis empty score. It should correct itself automatically, I'll look into reasons why it may be missing out on it.

**Comment by isoos** [comment]
We've updated how we handle this, it has been deployed, this should be fixed now.
