### ISSUE TITLE
dart:* packages return 404 on web

### ISSUE THREAD

**Issue by RyanRamchandar** [dart-lang/pub-dev#6956]
Clicking on a package, like dart:html, returns 404.

Eg: https://api.dart.dev/stable/3.1.0/

**Comment by parlough** [comment]
Just for added context, I believe these are the links you mean, correct?

<img width="589" alt="Dart core library broken links" src="https://github.com/dart-lang/pub-dev/assets/18372958/f1f5daee-5371-4b93-8af6-40f4ac68e0ae">

**Comment by RyanRamchandar** [comment]
@parlough yes, that's correct.

**Comment by isoos** [comment]
Thanks for the report! Looks like dartdoc output has changed and we failed to follow/update our code with it.
