### ISSUE TITLE
Pub analysis reports invalid data and lowers pub points based on it

### ISSUE THREAD

**Issue by AmrAbdelmagid** [dart-lang/pub-dev#6974]
URL: https://pub.dev/packages/connection_notifier/score

After my latest updates to connection_notifier package, I have received this warning:

```
WARNING: Missing case clause for 'hidden'.
lib/src/widgets/connection_notifier/connection_notifier_state.dart:18:11

   ╷
18 │           switch (state) {
   │           ^^^^^^^^^^^^^^
   ╵
To reproduce make sure you are using the [lints_core](https://pub.dev/packages/lints) and run flutter analyze lib/src/widgets/connection_notifier/connection_notifier_state.dart
```
This `state` is `AppLifecycleState` enumerated value which contains only 4 values: `resumed`, `inactive`, `paused` and `detached`.
So no `hidden` value as the warning says, also I have run `flutter analyze lib/src/widgets/connection_notifier/connection_notifier_state.dart` locally and every thing is perfect.

And accordingly it lowers pub points based on this warning.

**Comment by isoos** [comment]
@AmrAbdelmagid: the latest stable Flutter API has now a 5th value: `hidden`
https://api.flutter.dev/flutter/dart-ui/AppLifecycleState.html

pub.dev uses an "evergreen" approach with the latest SDKs (with a bit of delay sometimes) to analyze and score the packages, so we will pick up such warnings.
