### ISSUE TITLE
Analysis doesn't seem to respect ignore comments

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/pub-dev#6993]
[cupertino_http](https://pub.dev/packages/cupertino_http) uses a lot of generated code, which has quite a lot of unused fields. It's not practical to remove those unused fields, so there's a `// ignore_for_file: unused_field` comment [at the top of the file](https://raw.githubusercontent.com/dart-lang/http/master/pkgs/cupertino_http/lib/src/native_cupertino_bindings.dart).

If I run `flutter analyze` locally, the analysis passes. But on pub.dev it fails due to the unused fields: https://pub.dev/packages/cupertino_http/score

![image](https://github.com/dart-lang/pub-dev/assets/5958533/9a84b4a1-3ab5-4915-8c27-dac2853035b2)

So pub.dev seems to be ignoring the ignores. Is this intended?

**Comment by quetool** [comment]
Same is happening for `*.freezed.dart files` which uses `ignore_for_file: type=lint`

![Screenshot 2024-03-11 at 12 09 24](https://github.com/dart-lang/pub-dev/assets/14978705/dc526c42-318f-4613-8231-e0b5ea913ed2)

![Screenshot 2024-03-11 at 12 09 18](https://github.com/dart-lang/pub-dev/assets/14978705/7cd2d5aa-d4a2-4695-92aa-461a84c1d100)

**Comment by isoos** [comment]
@quetool: can you post the package name, and also your local Dart SDK version?

**Comment by quetool** [comment]
Thanks for the reply, @isoos !
Dart version 3.2.0
Package https://pub.dev/packages/web3modal_flutter/versions/3.1.2

It started happening a couple of releases ago...

**Comment by isoos** [comment]
I think the issue is that your are lint-level issues with `ignore_for_file: type=lint`, but the `== operator should be non-nullable` seems to be warning-level, and the lint rule is not applied to it. Are you on the latest `freezed`? it seems that they have some related change a few months back.

**Comment by quetool** [comment]
You are right @isoos , they have fixed it on 2.4.6, I have 2.4.5.
Thanks and sorry for the ping!

**Comment by liamappelbe** [comment]
This seems to be fixed now. The remaining analysis issue on the [score page](https://pub.dev/packages/cupertino_http/score) is to do with formatting.
