### ISSUE TITLE
google_g text replaced with google logo ligature in search bar and results

### ISSUE THREAD

**Issue by Benjins** [dart-lang/pub-dev#7000]
URL: https://pub.dev/packages?q=google_generative_language_api

The text `google_g` appears to be a ligature in the "Google Sans" font, which makes a google logo instead of the intended text. This is the case in the search bar (although this seems somewhat inconsistent), and the results on the page. This happens on Chrome Stable (116.0.5845.141), Chrome Canary (118.0.5984.0), and Firefox (117.0)

Originally found by [@fuzzybinary](https://mastodon.gamedev.place/@fuzzybinary):
https://mastodon.gamedev.place/@fuzzybinary/110990100736851608

**Comment by isoos** [comment]
<img width="509" alt="image" src="https://github.com/dart-lang/pub-dev/assets/4778111/470ba59b-b370-452b-8982-795089cbcb30">

**Comment by parlough** [comment]
I don't think we use ligatures anywhere for the Google Sans fonts, so can probably turn them off.

**Comment by Benjins** [comment]
Apologies for re-opening this, but I noticed that while this is fixed for the text in the search results, the text in the user input still shows the ligature. I'm not super-familiar with CSS, but it appears that the input/button elements don't inherit the `font-variant-ligatures: none` property from the `body` and need it applied to them specifically (like how `font-family` already is)

**Comment by isoos** [comment]
Great catch, thanks for the notice!
