### ISSUE TITLE
Bug: Example Page references to a wrong path

### ISSUE THREAD

**Issue by quoc-huynh-cosee** [dart-lang/pub-dev#7017]
Hi,

I noticed a bug that the Example page in pub for a package e.g. https://pub.dev/packages/ruler_scale_picker/example references to a wrong paths (images/codes).
In the past it was working fine. 
The screenshot of the package has the following URL: https://raw.githubusercontent.com/cosee/ruler_scale_picker/main/example/screenshots/example.webp
The screenshots in the Example Page has the following URL: https://github.com/cosee/ruler_scale_picker/raw/main/screenshots/default.webp, which breaks since there is missing the **example** in the path and it references **github.com** now.
You can find the **example.md** here: https://github.com/cosee/ruler_scale_picker/blob/main/example/example.md
Is there any fix for that?

![Bildschirmfoto 2023-09-06 um 09 14 14](https://github.com/dart-lang/pub-dev/assets/93118554/8f12bf26-0c5a-4455-901a-cf7e2e22a45c)

**Comment by quoc-huynh-cosee** [comment]
@isoos Did you deploy a new version? The URLs are still wrong (see https://pub.dev/packages/ruler_scale_picker/example).

**Comment by isoos** [comment]
@quoc-huynh-cosee: not yet, it may be ongoing today, not sure when the traffic will be migrated.

**Comment by isoos** [comment]
Note: this has been deployed yesterday.

**Comment by quoc-huynh-cosee** [comment]
It's working again, thank you very much!
