### ISSUE TITLE
Pub dev not loading

### ISSUE THREAD

**Issue by FriendlyNeighbor** [dart-lang/pub-dev#7034]
Is there a link where I can check if pub dev is down? I can't access it. it just loads and loads. Cleared cache and everything. even tried different devices.

**Comment by FriendlyNeighbor** [comment]
Testing host resolves...
- pub.dev IPv4 resolve and connect succeeded: 0 / 4
- pub.dev IPv6 lookup failed: SocketException: Failed host lookup: 'pub.dev' (OS Error: The requested name is valid, but no data of the requested type was found.
, errno = 11004)
- pub.dartlang.org IPv4 resolve and connect succeeded: 1 / 1
- pub.dartlang.org IPv6 lookup failed: SocketException: Failed host lookup: 'pub.dartlang.org' (OS Error: The requested name is valid, but no data of the requested type was found.
, errno = 11004)
- storage.googleapis.com IPv4 resolve and connect succeeded: 16 / 16
- storage.googleapis.com IPv6 lookup failed: SocketException: Failed host lookup: 'storage.googleapis.com' (OS Error: The requested name is valid, but no data of the requested type was found.
, errno = 11004)
Testing one connection per request...
Unhandled exception:
TimeoutException after 0:00:15.000000: Future not completed

**Comment by sigurdm** [comment]
Where are you located?

**Comment by FriendlyNeighbor** [comment]
Philippines

**Comment by sigurdm** [comment]
Sounds like an ISP issue.

Consider trying the Chinese community mirror: https://docs.flutter.dev/community/china while this is being resolved.

**Comment by FriendlyNeighbor** [comment]
How is that related to accessing the pub.dev website? I just paid and installed a vpn. now I can access it. additional cost but I hope this can be fixed. It happened all of a sudden without even restarting my router or my pc.

**Comment by sigurdm** [comment]
Closing now - not much we can do.
