### ISSUE TITLE
not loading video tumbnails

### ISSUE THREAD

**Issue by ajeetjain1403** [dart-lang/pub-dev#7042]
URL: https://pub.dev/packages/flutter_webview_pro/versions
hello,
I have implemented webview using flutter_webview_pro: ^3.0.1+4 I am getting a problem where my video thumbnail are not loading. Can anyone help me with this.

WebView( initialUrl: 'my-url', javascriptMode: JavascriptMode.unrestricted, onWebViewCreated: (WebViewController webViewController) { // Store the reference to the WebViewController when it's created. [_webViewController]([url]([url](url))) = webViewController; }, geolocationEnabled: true, initialMediaPlaybackPolicy: AutoMediaPlaybackPolicy.always_allow, allowsInlineMediaPlayback: true, onWebResourceError: (error) => { setState(() { isError = true; }) },

img link :- https://i.stack.imgur.com/y8TCf.png

<Describe your issue or suggestion here>

**Comment by sigurdm** [comment]
This is the issue tracker for the pub.dev site itself, not for individual packages.

Try the issue tracker for flutter_webview_pro: https://github.com/wenzhiming/flutter-plugins/issues
