### ISSUE TITLE
Add Dart syntax highlighting for Markdown code blocks marked as `dart`

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/pub-dev#7055]
Adding Dart syntax highlighting for code blocks marked as 'dart' is essential to enhance readability.

I suggest a highlighting style similar to the one used on GitHub.

**Comment by sigurdm** [comment]
I believe we do support this on the pub.dev site: 
![image](https://github.com/dart-lang/pub-dev/assets/8613953/1e7acad7-114c-45ed-820f-46bc3b50417f)
Can you be more specific about where you have seen this not supported?

**Comment by gmpassos** [comment]
I just checked it now, and the syntax highlighting is working.

Yesterday, when I filed the issue, it wasn’t. Then I checked the same README on GitHub, and it was highlighted.

I’m closing this issue since it’s not needed.

**Comment by sigurdm** [comment]
Please reopen if you see this again!

**Comment by gmpassos** [comment]
> Please reopen if you see this again!

Sure, I will try to investigate it if I see it again.

Thanks for the response.

Best regards.

**Comment by gmpassos** [comment]
Ir seems that sometimes the highlight is not loading? It's a separated CSS file?

Or maybe it's an older cache in the browser.

**Comment by isoos** [comment]
I can think of one case where this may happen: if the browser caches an old HTML page, but not its CSS/JS bundle (e.g. `/static/hash-<x1>/<y>.css`) while the site is on a new bundle (e.g. `/static/hash-<x2>/<y>.css`). I don't think our current cache headers would allow/support the behavior, but browsers could always override or ignore them... What kind of browser or extensions are you using?

**Comment by gmpassos** [comment]
Safari (macOS). And it was opening a package that I had published in the same day.
