### ISSUE TITLE
Pub.dev is down

### ISSUE THREAD

**Issue by MominRaza** [dart-lang/pub-dev#7088]
Resolving dependencies... (12:10.7s)
pub upgrade is taking more than 12 minutes, I checked pub.dev website is also not opening

 * Explain the issue,
 * Using bullet points!
 * Link to screenshot.

```dart
// Write example code here
```

**Comment by isoos** [comment]
It is working for me currently.

Can you try running: https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart and post the output? That will give us more information about your network.

**Comment by isoos** [comment]
Also: please share your location, ISP, network setup (e.g. proxy).

**Comment by MominRaza** [comment]
It working fine now.
It was down for me only 1hr
location: UP India
ISP: Airtel
No proxy

**Comment by isoos** [comment]
Closing as we can't really do much here.
