### ISSUE TITLE
Markdown links not being correctly interpreted

### ISSUE THREAD

**Issue by JCKodel** [dart-lang/pub-dev#7096]
URL: https://pub.dev/packages/simple_architecture

My READ.ME file contains the following link:

```
[Pub Package: https://pub.dev/packages/simple_architecture](https://pub.dev/packages/simple_architecture)
```

In GitHub, this is rendered as:

![image](https://github.com/dart-lang/pub-dev/assets/379339/7be5db3f-28e0-43e3-a713-33b92eb5c1cd)

But in pub.dev, this is rendered as:

![image](https://github.com/dart-lang/pub-dev/assets/379339/17f75ae4-b1c7-40e2-a3f0-f1b84cd814d9)

**Comment by isoos** [comment]
I think this has been fixed with last week's release.
