### ISSUE TITLE
repository link missing for package:collection

### ISSUE THREAD

**Issue by eseidel** [dart-lang/pub-dev#7107]
package:collection definitely has `repository` set in its pub spec:
https://github.com/dart-lang/collection/blob/master/pubspec.yaml

But somehow the repository link does not show up in pub:
<img width="216" alt="image" src="https://github.com/dart-lang/pub-dev/assets/478541/db797ac0-c124-4dd8-92c4-d97511e06c44">

Not really sure what's gone wrong. 🤷

**Comment by isoos** [comment]
Looks like either a network, GitHub or a rate limit issue at the time of the analysis:

<img width="610" alt="image" src="https://github.com/dart-lang/pub-dev/assets/4778111/e08077ce-610e-4567-8d55-cb826b428433">

Verification happens here:
https://github.com/dart-lang/pana/blob/master/lib/src/repository/check_repository.dart

@jonasfj any preference on how to retry it?

**Comment by jonasfj** [comment]
@isoos I think we need to debug issues like this.
Ideally, we print the error to task log, and expose a link to the task log from the `/score` page.

Then, if we conclude that it is github rate-limiting us, we can ask github if they can allowlist our IP; or we can register an application or add more external IPs.

**Comment by eseidel** [comment]
Thanks for fixing/re-running the package.

**Comment by sigurdm** [comment]
Closing this in favor of https://github.com/dart-lang/pub-dev/issues/7116
