### ISSUE TITLE
your plateforme is used as phishing site, please stop this

### ISSUE THREAD

**Issue by oppbtp-git** [dart-lang/pub-dev#7143]

**Comment by isoos** [comment]
@oppbtp-git: this doesn't seem to be a pub.dev issue, it is a separate site (r2.dev). Did you get a link to this via pub.dev?

**Comment by oppbtp-git** [comment]
Hi

Thank you for your answer
My error

Have a nice day
Marc

De : István Soós ***@***.***>
Répondre à : dart-lang/pub-dev ***@***.***>
Date : mercredi 25 octobre 2023 à 09:13
À : dart-lang/pub-dev ***@***.***>
Cc : Dufourd Marc ***@***.***>, Mention ***@***.***>
Objet : Re: [dart-lang/pub-dev] your plateforme is used as phishing site, please stop this (Issue #7143)


@oppbtp-git<https://github.com/oppbtp-git>: this doesn't seem to be a pub.dev issue, it is a separate site (r2.dev). Did you get a link to this via pub.dev?

**Comment by isoos** [comment]
Removed spam link from first entry, closing as invalid.
