### ISSUE TITLE
Missing information about getKeys()

### ISSUE THREAD

**Issue by gszesiek** [dart-lang/pub-dev#7145]
URL: https://pub.dev/packages/shared_preferences

After 
// Try reading data from the 'items' key. If it doesn't exist, returns null.
final List<String>? items = prefs.getStringList('items');
I would add information about getKeys():
// Returns all keys in the persistent storage
final Set<String> keys = prefs.getKeys();

**Comment by isoos** [comment]
@gszesiek: This repository is for the pub.dev site. Please report package-related issues on the issue tracker of the package: 
https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+shared_preferences%22

**Comment by gszesiek** [comment]
Package works perfectly fine.
However on the pub.dev site Readme section for this package there's no info about getKeys().

**Comment by isoos** [comment]
> However on the pub.dev site Readme section for this package there's no info about getKeys().

This is a question to the package authors, and not to the pub.dev site. Whether they put it in or leave it out it is up to them.

**Comment by gszesiek** [comment]
OK
Thank you for clarification.
