### ISSUE TITLE
Include id-token permission in "Example workflow"

### ISSUE THREAD

**Issue by mateusfccp** [dart-lang/pub-dev#7146]
Currently, when enabling automated publishing in `pub.dev` panel, the "example workflow" does not include the `id-token` permission.

Without this permission, the GitHub Action is going to fail.

The documentation is correct in https://dart.dev/tools/pub/automated-publishing, and we should make it correct here too.

<img width="770" alt="image" src="https://github.com/dart-lang/pub-dev/assets/4605213/01987e98-b9d9-4b80-bd44-395107cc57c0">

**Comment by isoos** [comment]
I don't think it is critical to include that permission into the file, e.g. `google/dart-neats` doesn't have it, and it is able to run the publish flow:
https://github.com/google/dart-neats/blob/master/.github/workflows/publish.yml#L32

**Comment by isoos** [comment]
I have now only vague memories of this but there are other examples where the permission specification is only needed on the main file: https://github.com/dart-lang/source_gen/blob/master/.github/workflows/publish.yaml

I think as long a package uses the entire `dart-lang/setup-dart` workflow as specified in the example on pub.dev, it should work.

**Comment by mateusfccp** [comment]
> I don't think it is critical to include that permission into the file, e.g. `google/dart-neats` doesn't have it, and it is able to run the publish flow: [google/dart-neats@`master`/.github/workflows/publish.yml#L32](https://github.com/google/dart-neats/blob/master/.github/workflows/publish.yml?rgh-link-date=2023-10-30T06%3A53%3A39Z#L32)

I don't really know how this OICD authentication works... My package is as simple as it could be, and I did the following steps:

1. Enable the automatic publishing in the pub.dev admin panel
1. Copy the workflow example given in the panel
1. Create a `publish.yaml` file in my project with the copied code

When I tried to publish a new version of my package through GitHub Actions, I got the following error: `The workflow is not valid. .github/workflows/publish.yaml (Line: 9, Col: 3): Error calling workflow 'dart-lang/setup-dart/.github/workflows/publish.yml@v1'. The nested job 'publish' is requesting 'id-token: write', but is only allowed 'id-token: none'.` <sup>[[reference]](https://github.com/llucax/pausable_timer/actions/runs/6685915128)</sup>

After investigating a little I got to the aforementioned documentation, that explicitly says to use the `id-token` in the configuration. Note that the documentation does not get in details of why it's needed, nor it gives any condition to use it. All examples, unequivocally, use it.

This means that either the documentation is severely misleading or we should add it to workflow example. I am not sure why some packages work fine without specifying it, tho.

> I think as long a package uses the entire `dart-lang/setup-dart` workflow as specified in the example on pub.dev, it should work.

I'm sorry, what do you mean by "the entire `dart-lang/setup-dart` workflow?

**Comment by isoos** [comment]
Apparently, this is a recent change in github policy: "For securely enabling OpenID Connect (OIDC) in your reusable workflows, we are now making the permissions more restrictive.

If you need to fetch an OIDC token generated within a reusable (called) workflow that is outside your enterprise/organization, then the permissions setting for id-token should now be explicitly set to write at the caller workflow level or in the specific job that calls the reusable workflow."
https://github.blog/changelog/2023-06-15-github-actions-securing-openid-connect-oidc-token-permissions-in-reusable-workflows/

Let's make this part of the default file...
