### ISSUE TITLE
Incorrect publish response for `flutter_lints`?

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/pub-dev#7168]
We've had a strange problem with the last two releases of `flutter_lints` (3.0.1 and 3.0.0) where they are being published by our autopublish system, but not tagged. When I investigated, I found that the auto-release step that is publishing it [reports that it's already published](https://github.com/flutter/packages/actions/runs/6695809031/job/18347000369)

```
[...]
Publishing flutter_lints 3.0.1 to [https://pub.dev:](https://pub.dev/)

├── AUTHORS (<1 KB)
├── CHANGELOG.md (1 KB)
├── LICENSE (1 KB)
├── README.md (3 KB)
├── example
│   ├── README.md (<1 KB)
│   ├── analysis_options.yaml (1 KB)
│   ├── lib
│   │   └── main.dart (1 KB)
│   └── pubspec.yaml (<1 KB)
├── lib
│   └── flutter.yaml (<1 KB)
├── pubspec.yaml (<1 KB)
└── run_tests.sh (<1 KB)

Validating package...


Uploading...


Version 3.0.1 of package flutter_lints already exists.
```

We then get a non-zero exit code from `pub publish`, and thus think it's failed and don't tag.

But in both cases I checked our email notifications and our role account, which is only used by the bot, is what did the publishing. And the script that does this publishing checks the publish state before it does anything; here's the output (from our script, not `pub`) if I re-run exactly the same task on the same commit:

```
flutter_lints 3.0.1 has already been published.
SKIPPING: already published
```

So either somehow we are simultaneously two copies of this script—which I cannot find any evidence of in the GitHub UI, and which would not explain the lack of tagging since if two copies are running, one of them should report success and then push a tag—or pub.dev is giving us incorrect responses. What's particularly strange is that so for this has only happened with `flutter_lints`, even though all of our tooling is uniform. Other packages released recently have been fine.

Is there any server-side record that could be investigated to see which side this is happening on?

**Comment by sigurdm** [comment]
Is there any server-side record that could be investigated to see which side this is happening on?

Flutter lints was published: November 3, 2023 at 6:47:41.277 PM UTC+1 (according to datastore)

We have logs with 
* timestamp 2023-11-03 18:47:45.362 (CET) showing a successful publish 
* timestamp 2023-11-03 18:52:12.337 showing a failed publish due to existing version

**Comment by stuartmorgan** [comment]
> We have logs with
> 
> * timestamp 2023-11-03 18:47:45.362 (CET) showing a successful publish
> * timestamp 2023-11-03 18:52:12.337 showing a failed publish due to existing version

That's deeply strange. The timestamps from the script show:
```
Fri, 03 Nov 2023 17:47:39 GMT Validating package...
Fri, 03 Nov 2023 17:47:39 GMT 
Fri, 03 Nov 2023 17:47:39 GMT 
Fri, 03 Nov 2023 17:47:40 GMT Uploading...
Fri, 03 Nov 2023 17:47:40 GMT
Fri, 03 Nov 2023 17:47:40 GMT
Fri, 03 Nov 2023 17:52:12 GMT Version 3.0.1 of package flutter_lints already exists.
```

So when the script logged "Uploading" from `pub publish` is the time when it succeeded, and when it returned failure was when it reported failed. But that's all just one `pub publish` call on our end.

**Comment by isoos** [comment]
@sigurdm Can this be a retry from `pub` client? The server completed the upload transaction, but failed some of the post-upload work, which returned an error code to the client -> trigger a retry that returned fast as the version has finalized with the transaction.

**Comment by sigurdm** [comment]
> Can this be a retry from pub client?

We do upload inside a retry: https://github.com/dart-lang/pub/blob/2bb8e2c4e1e6099345608dddcbe1def0a3319edb/lib/src/command/lish.dart#L128

So that is certainly possible.... But:

> The server completed the upload transaction, but failed some of the post-upload work, which returned an error code to the client

Should we not always return success to the client if the upload transaction succeeds, no matter the post-upload work?

**Comment by isoos** [comment]
> Should we not always return success to the client if the upload transaction succeeds, no matter the post-upload work?

We ignore errors, but we don't have a strictly enforced timeout:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/package/backend.dart#L1161-L1177

**Comment by sigurdm** [comment]
Ah - that might be the problem...

**Comment by sigurdm** [comment]
Marking as bug - not sure what the best solution is. Can we send the success response before we do the post-upload work?

**Comment by isoos** [comment]
> Can we send the success response before we do the post-upload work?

IIRC we were doing the work `unawaited` previously, but was losing log entries, because once the response sending completed, the log context ignored the messages arriving after that. With that we've changed it back to in-request `await`. We could have an instance-level queue where such tasks could be offloaded, so it has a proper log context.

**Comment by sigurdm** [comment]
> We could have an instance-level queue where such tasks could be offloaded, so it has a proper log context.

Yeah - that would make sense...

We should probably consider if the client retries are done correctly. What happens if the server sends a 200 response but it never arrives because of package loss? Should the client just retry after timing out? Not sure what is most robust

**Comment by isoos** [comment]
We have updated this in #7176.
