### ISSUE TITLE
Enable more automated workflows by allowing publishing from the `workflow_dispatch` trigger

### ISSUE THREAD

**Issue by spydon** [dart-lang/pub-dev#7177]
> Note: Pub.dev only allows automated publishing from GitHub Actions when the workflow is triggered by pushing a git tag to GitHub. Pub.dev rejects publishing from GitHub Actions triggered without a tag. This ensures that new versions cannot be published by events that should never trigger publishing.

I understand the reasoning here, but this also makes it impossible to do fully automated publishing since a tag that is created by another workflow isn't allowed to trigger other workflows. So with this restriction from pub.dev in place the publishing will always need manual intervention from the command-line/IDE, since a user has to push a tag manually to trigger the workflow.

What we would like is to trigger the workflow that publishes the new versions from another workflow by using the `workflow_dispatch` trigger (currently only `push` is allowed).

The simplest flow for our use-case would be this:

1. The users goes to their action tab and presses "Run release action"
2. The melos-action versions and creates changelogs for all packages, and then published a PR with the changes (it also checks if it gets any publish --dry-run warnings in this step)
3. The PR is then reviewed
4. When the PR is merged it triggers the melos publish job which will tag and publish all of newly versioned the packages.

For context this will for example be used by the [melos-action](https://github.com/bluefireteam/melos-action) that should semi-automate (PRs are still used) the whole publishing flow in monorepos, or any repositories using [melos](https://github.com/invertase/melos).

Design doc: https://flutter.dev/go/pub-automated-publishing

**Comment by spydon** [comment]
One solution could be for pub to also allow `workflow_dispatch` events, they can also be connected to tags.
I thought that might already work, but sadly it didn't:
> The calling GitHub Action is not allowed to publish, because: publishing is only allowed from 'push' events, this token originates from a 'workflow_dispatch' event.

**Comment by spydon** [comment]
What do you think @isoos @sigurdm?

**Comment by isoos** [comment]
@spydon: I am not that familiar with the workflow internals. Is there a document that describes what the users are doing and what the system is doing in such case?

**Comment by spydon** [comment]
@isoos So `workflow_dispatch` is the event that is used when a workflow is triggered manually:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

It can also be connected to a tag, so the rest of the server-side checks on your side should still be the same as they are for `push`.

**Comment by isoos** [comment]
I'm more interested in what kind of problem it solves. I remember @jonasfj doing interesting things with workflows+tagging+approvals, and I don't know how this related.

**Comment by spydon** [comment]
Ah sorry, maybe I didn't clarify that properly in the initial post.
So with only allowing publishing on `push` one can never fully automate publishing, or even trigger a workflow manually that handles publishing from GitHub, one always have to manually push tags from the local machine.

What I'm building in the melos-action is so that people can set up the following flow for their monorepos:

1. Automatically version their packages and create changelogs.
3. This creates a PR with the outcome for the maintainers to review.
4. When this release PR is merged, another job creates git tags for all the new versions.
5. After the tags are created it should then publish to pub, but since GitHub doesn't allow workflows to be triggered by the action of other workflows (to avoid infinite loops) this part is not possible, even with an explicit trigger through `workflow_dispatch`, since pub.dev blocks that server-side.

So it really is just an unfortunate combination of the rule from GitHub and the one from pub.dev that blocks this flow, but by allowing `workflow_dispatch` events and not only `push` events to trigger publishing it would be solved.

**Comment by isoos** [comment]
> When this release PR is merged, another job creates git tags for all the new versions.

I've seen people use git tagging and `git push --tag` to trigger automatic publishing. Not sure: what is missing in it for this to work with your workflow?

**Comment by spydon** [comment]
> > When this release PR is merged, another job creates git tags for all the new versions.
> 
> I've seen people use git tagging and `git push --tag` to trigger automatic publishing. Not sure: what is missing in it for this to work with your workflow?

If you do that from a GitHub workflow it can't trigger another action, so you can only do that locally.
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow

**Comment by spydon** [comment]
@isoos to clarify in case it wasn't clear, when you run `git push --tags` from a workflow, it will create the tags, but GitHub refuses to trigger another workflow that is usually triggered by newly created tags when those tags (or any other trigger, except `workflow_dispatch`) is related to another workflow run.

**Comment by spydon** [comment]
@isoos I found a TODO from you about possibly allowing for events :smile:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/package/backend.dart#L1250-L1251

I can implement the PR so that you can see what it would look like with `workflow_dispatch` too, it should be a really minimal change.

**Comment by isoos** [comment]
@spydon: As the TODO says we shall consider it :). I'd wait the input from @jonasfj but he is out right now, it may take a while before we can give you any solid decision on this one.

**Comment by spydon** [comment]
> @spydon: As the TODO says we shall consider it :). I'd wait the input from @jonasfj but he is out right now, it may take a while before we can give you any solid decision on this one.

Makes sense, I'll not put up a PR then, or would it help your decision to have a PR to look at? :)

**Comment by jonasfj** [comment]
> As far as I'm aware there is no work-around for this (without having to use PAT tokens)?

You can use a GCP service account instead. Ideally, not be exporting the service-account keys, but by running on Google Cloud Build or by using Workload Identity Federation to allow your Github JWTs to be used to obtain permission to impersonate the GCP service account.

This is obviously, quite complicated -- just saying it's possible :see_no_evil: 


----------------

On topic we do have concerns, there are reasons we did it the way we did. Some of these concerns include:

 * (1) Publishing a new version should be a _deliberate action_.
   * We do NOT want users publishing a new version of their package for each commit.
     (It's not hard to imagine that someone would think this is a cool thing to do).
   * pub.dev will limit packages to ~1000 package versions or so, if/when someone hits that
     we'll have to make exceptions on a case-by-case basis -- which we'll probably have to do.
   * Having many versions will make the API used by `pub get` slow, we want a simple and fast API.
   * Frequently publishing new versions might cause upgrade fatigue or unnecessary churn for package consumers -- I'm sure there are lots of other good reasons not to have a huge amount of versions.
   * Forcing automated publishing to happen through a tag, makes the initiation somewhat manual. This might be a good thing, and might keep people from publishing on every commit.
 * (2) Reduce complexity reduces the risk of misconfigured Github Actions.
   * The fact that publishing requires permission to publish a tag makes it hard to misconfigure your Github Actions such that a pull-request can publish to pub.dev.
   * The fact that Github Actions can be triggered in so many ways, also means that if we allow arbitrary triggers we increase the risk that someone configures it poorly.
 * (3) Forcing git revisions to be tagged is really awesome!

I think (3) is really nice. I don't know if (1) could be solved by other means -- maybe, but it's definitely a concern that if we make publishing too easy, someone will publish on every commit.

I think (2) is a really be concern though.

----

Please share some examples of how you think the flow should work?

**Comment by spydon** [comment]
> You can use a GCP service account instead

Isn't this kind of strange, that you allow this to be done through one service, but not another?
It wouldn't work here either obviously since it's a GitHub action that we're building for the users, if we don't make something reeeeally hacky. :sweat_smile: 

> Having many versions will make the API used by pub get slow, we want a simple and fast API.

I don't disagree with that it might not be desirable to have too many versions, but this really sounds like a server-side problem that should be possible to solve, the magnitude of data is still really low even if it would be 100 000 versions? But maybe I'm missing some complexity. :shrug: 

> The fact that Github Actions can be triggered in so many ways, also means that if we allow arbitrary triggers we increase the risk that someone configures it poorly.

That is the good thing with `workflow_dispatch`, the user really has to either actively press "Run action" in the UI, or explicitly write that it should be triggered in their action, it is never triggered by anything else happening in the repository.

> (3) Forcing git revisions to be tagged is really awesome!

Melos tags all packages when it creates versions, the problem is that when these tags are created within a pipeline another action is not allowed to be triggered by those tags (https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow).

> I'd be very curious is hear what kind of workflow you envision?

The simplest flow would be this:
1. The users goes to their action tab and presses "Run release action"
2. The `melos-action` versions and creates changelogs for all packages, and then published a PR with the changes (it also checks if it gets any `publish --dry-run` warnings in this step)
3. The PR is then reviewed
4. When the PR is merged it triggers the `melos publish` job which will tag and publish all of newly versioned the packages.

Number 1 here can be changed to for example writing "Trigger release" or something like that in a previous PR description, but a user will still have the manual step of reviewing the PR with the release in it, which I guess could be compared with the manual intervention of creating a tag today.

**Comment by spydon** [comment]
What do you think @jonasfj, does it make sense? :)

**Comment by clragon** [comment]
I have now run into this problem.

This is essentially preventing me from making a single trigger workflow that
- increases my pubspec version 
- stamps my changelog
- commits these changes
- creates a github release
- publishes to pub.dev

Because pub.dev only allows `push: tags` trigger workflows to publish, I use the setup you have provided that publishes on tag push. 
I have a trigger workflow that does the things mentioned above except publishing.
A github workflow that creates a release (read: pushes a tag) with the GITHUB_TOKEN cannot trigger another workflow.
So then finally, I have to create a secret with an auth token or a deploy key plus an extra workflow just to get this setup going.

This makes the setup much more complicated than it could be, and also much less reusable. Each repository where I want this I now have to copy both workflows and setup a new key and secret everytime.

This is essentially a combination of all well meant security measures, but they are making my CD very difficult right now.

**Comment by spydon** [comment]
I made a little bit more research, and publishing packages from a GitHub action is currently available in pretty much any language ecosystem that I can find:
 * [Docker](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images)
 * [Gradle](https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle)
 * [Maven](https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven)
 * [Node.js](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages)
 * [Rust](https://github.com/marketplace/actions/publish-crates)
 * [Go](https://forcepush.tech/go-package-ci-cd-with-git-hub-actions)
 * [Haskell](https://github.com/haskell-actions/hackage-publish)
 * [C#](https://www.meziantou.net/publishing-a-nuget-package-following-best-practices-using-github.htm)
 * [Erlang/Elixir](https://github.com/erlangpack/github-action)
 * [Python](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/)
 * [Ruby](https://github.com/marketplace/actions/publish-gem)

@jonasfj @isoos are there any specific concerns that you have with enabling `workflow_dispatch` [here](https://github.com/dart-lang/pub-dev/blob/master/app/lib/package/backend.dart#L1254)?

And also; Happy new year! :sparkles:

**Comment by spydon** [comment]
> Though we might need to investigate further exactly who can trigger a `workflow_dispatch` (like we'd need some input for at-least a lightweight security review). And we'd need to build some tooling for all of the above, or at-least write some documentation.

It will be the same people as can create releases today by creating tags, so what tooling etc would need to be written for this?

> I'm a little bit conservative about opening up features like this, because they are really hard to remove once we ship them. And currently focus is somewhere else.

Makes sense, I think this is quite an important feature though.

> Ideally, I'd want a `workflow_dispatch` action that creates a PR, and the PR creates a tag. But I don't think creating tags from PRs is possible today. At-least not without using a Github Action, which means that any tag-push Github Action won't run.

There is no problem creating tags from GitHub actions when a PR is closed, that is exactly what will be done with the [melos action](https://github.com/marketplace/actions/melos-action) once `workflow_dispatch` is enabled. The problem GitHub actions are that they can't be triggered by tags created by other actions, hence the need for opening up for `workflow_dispatch`.

> Using the flow above, you'll end up with git commits in the tag, that have not necessarily be landed on `main/master` branch (I guess the action could do that), but certainly the commits wouldn't have a review associated with them in a pull-request. I could imagine that being undesirable in some future where SLSA can attest to whether or not all changes making it into a release have code reviews. I don't think that's on SLSA roadmap yet, hehe, so that's just me thinking too far ahead.

No, the tags are created automatically upon merge of the release PR.

> **Crazy idea**

The workflow will be even simpler than that:

* Trigger the release preparation workflow using a manual workflow_dispatch.
* Review and merge the pull-request created.
* Once the PR is merged another workflow will:
        - This will create the tag
        - It will create a pub release
        - It will create a GitHub release

**Comment by jonasfj** [comment]
> The workflow will be even simpler than that:
>
> * Trigger the release preparation workflow using a manual workflow_dispatch.
> * Review and merge the pull-request created.
> * Once the PR is merged another workflow will:
>   - This will create the tag
>   - It will create a pub release
>   - It will create a GitHub release

So "another workflow" will publish to `pub.dev`, how is that triggered?

By merging the pull-request? Because that would imply publishing from a `push` event on `master/main`, and not `workflow_dispatch`.

And publishing from push to `main/master` is kind of something we'd like to avoid having people do. It's just too easy for someone to publish on every commit, which is a bad idea.
Hmm, or maybe, I'm too worried about building footguns :rofl: 

> Makes sense, I think this is quite an important feature though.

Agreed, but the big feature with automated publishing is that you don't need credentials on your laptop or long-lived credentials in environment variables on Github Actions.

**Comment by spydon** [comment]
> So "another workflow" will publish to `pub.dev`, how is that triggered?

You can trigger `workflow_dispatch` workflows from other workflows, which is what the melos action is set up to do.

> By merging the pull-request? Because that would imply publishing from a `push` event on `master/main`, and not `workflow_dispatch`.
> 
> And publishing from push to `main/master` is kind of something we'd like to avoid having people do. It's just too easy for someone to publish on every commit, which is a bad idea. Hmm, or maybe, I'm too worried about building footguns 🤣

Understandable, I think since it is a bit complicated to build these workflows manually I think that most people will rely on pre-made actions like ours that sets this up for them and thus avoiding the footguns. It could even be undocumented that `workflow_dispatch` can be used, if that is a big worry.

> Agreed, but the big feature with automated publishing is that you don't need credentials on your laptop or long-lived credentials in environment variables on Github Actions.

I think since virtually every other big language ecosystem supports this I think we would have heard of a lot these problems before if it would result in a big problem. :slightly_smiling_face:

**Comment by jonasfj** [comment]
> It could even be undocumented that `workflow_dispatch` can be used, if that is a big worry.

Undocumented ways to publish things sounds a lot like a future security vulnerability :see_no_evil: 

I suspect that it would have to be opt-in, with a checkbox on the "admin page" for each event that should be allowed to publish. Or maybe a radio button is better, no need to allow publishing from multiple events.

![image](https://github.com/dart-lang/pub-dev/assets/149732/cc7c5509-ceca-4965-a4ff-faaad0da6960)

But I can see an argument for not being too worried about `workflow_dispatch`, it probably won't encourage people to make a tag and publish a release on every push to `main`.

Overall, I like the idea of allowing `workflow_dispatch`, because it means we can still require that the code is pushed to a tag. It just allows users to create workflows that automatically push the tag and then trigger a `workflow_dispatch`.

There is still an open question around how provenance will look for such workflows.
How to even make provenance is not resolved yet, so yeah maybe we shouldn't block on it.
But I'd at-least be curious to see what the JWT from Github OIDC on such jobs claims.

**Comment by jonasfj** [comment]
This is not a full design, let's reach consensus on what the right thing to do is before we start adding new settings.

**Comment by spydon** [comment]
> Undocumented ways to publish things sounds a lot like a future security vulnerability 🙈

Agree, I was grasping for straws to get this in. :sweat_smile: 

> I suspect that it would have to be opt-in, with a checkbox on the "admin page" for each event that should be allowed to publish. Or maybe a radio button is better, no need to allow publishing from multiple events.

I would just allow it by default after enabling publishing from GitHub actions, I don't see how a logged in user with admin rights can be a security threat, because I guess that is your thinking?
And also, this is already allowed through GCP, without any checkboxes, so I don't see why it couldn't be enabled for GitHub?

If we go with opt-in, I would make them checkboxes and not radio buttons, because you might want to both push tags manually and press a button in the UI at the same time.

**Comment by clragon** [comment]
The current state is less than optimal.
Assume:
I want to make a workflow that releases my package 
-> I create a workflow dispatch that runs when I specifically say to release a new version
-> Uh oh, I cant do that because no permissions to publish from workflow dispatch

I guess I have to
1. setup the publish on tag push change
  2.a manually do all the release steps 
  3.a push the commit with a tag

OR
1. setup the publish on tag push change
  2.b automatically do all the release steps
  3.b create an _extra_ commit just with a tag that releases the version

I dont think this change needs an extra setting.
People who want to automate their publishing should have the tools to do so comfortably. 
The change to add workflow dispatch seems easy and good and I feel like the changes that someone abuses this are just very minimal. Given that every other ecosystem has this kind of feature I doubt this will become a problem.

Publishing a new release based on a Merge or a Commit is also just not forbidden or undesirable.
Many projects I have worked on have workflows that automatically collect new version information from Merge requests via changeset files that combine into a new version. This isnt "every commit" on the same sense that we make a small change and immediately a new version is released, but it _is_ "every commit" on the master branch where we merge our completed and tested features so they can be released according to semver.

Please just let us have this. I need automation to make my life easier.

**Comment by spydon** [comment]
@jonasfj any thoughts on not having any checkboxes at all? :smiley:

**Comment by jonasfj** [comment]
> create an extra commit just with a tag that releases the version

You don't need an extra commit, you just need to push the tag.

Or create the tag through the releases UI on github.

Which can be done from an easy link, as outlined in "crazy idea" in https://github.com/dart-lang/pub-dev/issues/7177#issuecomment-1895918750

I actually suspect it might be worth prototyping something like that.

**Comment by spydon** [comment]
Then you have to manually create tags in the UI, as I explained [here](https://github.com/dart-lang/pub-dev/issues/7177#issuecomment-1812145569) you can't trigger workflows from a tag created in another workflow. And to create each tag manually in the UI is even more effort than creating them from the terminal.

What I'm building is specifically for monorepos which are the ones that need this the most, so in the case of Flame for example you'd have to click ~30 links if you'd follow the structure in your "crazy idea" plan. Or for flutterfire for example I suspect it would be up to 50 links.

I don't understand what is blocking you from just having `workflow_dispatch` directly alongside `push`?
Pub already support this flow through google cloud, I don't understand what the problem supporting it from GitHub as well, can you please explain because it feels like we're going in circles here.

**Comment by spydon** [comment]
Here's an example of how such a PR could look like:
https://github.com/flame-engine/flame/pull/3044

**Comment by spydon** [comment]
@jonasfj I wrote up a design doc for it: https://flutter.dev/go/pub-automated-publishing
Tell me if I should add you as editor or if commenter is enough, I'm sure you have some suggestions. :slightly_smiling_face:

**Comment by cachapa** [comment]
Thank you @spydon for your engagement. I just ran into this and found this issue, and wanted to give my two cents.

I definitely think that there should be no limitation on what types of workflows should be allowed to publish - or at least allow for the configuration to include all available options.
I understand the concern from the Pub.dev team about unintentional releases, but I suspect that the existing protections against republishing the same version number should protect against that.

Having said that, I'll definitely take `workflow_dispatch` events now as a first step, as that is what I'm [trying to do anyway](https://github.com/cachapa/sql_crdt/blob/c84633ce3df9004dc81bda51a44b8d200b86cba2/.github/workflows/publish.yml).

**Comment by spydon** [comment]
@jonasfj did you have a chance to look at the design doc yet? Are there any other people that should review it too? :)

**Comment by spydon** [comment]
@jonasfj I know some firebase folks have had a look at the design doc now (since it would simplify the maintenance for flutterfire a lot), have you had a chance to have a look at it yet? @sigurdm @isoos any of you that could have a look at it too (it's quite short)?
https://flutter.dev/go/pub-automated-publishing

**Comment by isoos** [comment]
@spydon: We've had the admin UI and the `workflow_dispatch` enabled for a while now. I'm closing this issue, please feel free to open new one if there is any issue with the feature.

**Comment by spydon** [comment]
> @spydon: We've had the admin UI and the `workflow_dispatch` enabled for a while now. I'm closing this issue, please feel free to open new one if there is any issue with the feature.

Thanks for implementing this! I have tried it out and it is working great, after Google I/O Connect and FlutterCon I should be able to finish off the GitHub actions that simplifies the usage. :)

**Comment by Wbbetty** [comment]
oh。。I’m encountering an issue with triggering the flutter pub publish command using the workflow_dispatch event in GitHub Actions. I’m receiving the following error: "The calling GitHub Action is not allowed to publish, because: publishing is only allowed from 'tag' refType, this token has 'branch' refType

**Comment by spydon** [comment]
@wbetty you need to checkout the tag that you want to publish from and then run publish, you can't publish from other ref types than tags (and the tag has to follow the setup version structure that you have in the pub admin console).

**Comment by Gustl22** [comment]
![grafik](https://github.com/user-attachments/assets/58470b02-00c7-4a4f-9bc5-83f40622c0c3)
Ref: https://github.com/bluefireteam/melos-action

**Comment by Wbbetty** [comment]
> @wbetty you need to checkout the tag that you want to publish from and then run publish, you can't publish from other ref types than tags (and the tag has to follow the setup version structure that you have in the pub admin console).

Hi @spydon,
Just to confirm, I can’t create a new tag and publish in the same workflow. I need to create the tag first and then run a separate workflow to publish, correct?

**Comment by Wbbetty** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/18537755/360880372-58470b02-00c7-4a4f-9bc5-83f40622c0c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDY3MjcsIm5iZiI6MTcyNDQwNjQyNywicGF0aCI6Ii8xODUzNzc1NS8zNjA4ODAzNzItNTg0NzBiMDItMDBjNy00YTRmLTliYzUtODNmNDA2MjJjMGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA5NDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZDFhNGU3ZWU3ODMzY2QxOWU3ODg2MzJmNmI1NDVjNmU5MGVmMThjOTZhZTBkOWQ2ODVhNzk2MTg5NWM1YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6LSu1s17xV-iRKS_mCl-yXF8jAVK126XrdVgYeiHgWs) Ref: https://github.com/bluefireteam/melos-action

thanks

**Comment by spydon** [comment]
@Wbbetty exactly, the easiest is to trigger another workflow on the tag after you've created it.

**Comment by Wbbetty** [comment]
> @Wbbetty exactly, the easiest is to trigger another workflow on the tag after you've created it.

Got it, thanks

**Comment by JamieSinn** [comment]
Looks like this isn't properly working for us? 

https://github.com/DevCycleHQ/flutter-client-sdk/actions/runs/16577798064/job/46886291721#step:14:192

This workflow is triggered by a `workflow_dispatch` - but still thinks it's a branch option? 

We manually publish via this workflow to allow our engineering team to publish without bypassing branch permissions to push tags to the main branch.

**Comment by JamieSinn** [comment]
Looks like something is weird with it not being triggered: 

https://github.com/DevCycleHQ/flutter-client-sdk/actions/workflows/dart.yml

I had to manually trigger this workflow after pushing the 1.11.6 tag.

**Comment by spydon** [comment]
> Ideally - you should allow more than just tags to be the triggering element if it's being called from workflow_dispatch.

I think it is pretty good that it is restricted to only tags, so that people don't accidentally run it on other refs that aren't intended to be releases. If you want to do more things you can just split them up on several actions and chain them.

> The calling GitHub Action is not allowed to publish, because: publishing is configured to only be allowed from actions with specific ref pattern, this token has 'refs/tags/v1.11.6' ref for which publishing is not allowed. Expected tag 'refs/tags/v1.11.6'. Check that the version in the tag matches the version in 'pubspec.yaml'.

It looks like you either haven't setup the tag pattern properly on the pub.dev admin page, or that the pubspec didn't have the a version matching the tag here.

Also, a good thing to remember is that actions can't automatically trigger other actions, so if you want to chain them you have to call workflow dispatch explicitly from them. We have a guide for how to set this up on the [melos-action](https://github.com/bluefireteam/melos-action?tab=readme-ov-file#automatic-versioning-and-publishing).

**Comment by JamieSinn** [comment]
Admin config:

<img width="858" height="611" alt="Image" src="https://github.com/user-attachments/assets/9d7abe4d-355e-4224-86e6-e9f12acaf3cb" />


Error logs:

https://github.com/DevCycleHQ/flutter-client-sdk/actions/runs/16578602686/job/46889240706
