### ISSUE TITLE
Getting an error while publishing package

### ISSUE THREAD

**Issue by shirvanie** [dart-lang/pub-dev#7179]
When publishing the package, I encounter the following error:
`Failed to upload the package.`

package name: [flutter_sliding_box](https://pub.dev/packages/flutter_sliding_box)

The results of executing the `dart pub publish -v` command:
[log.txt](https://github.com/dart-lang/pub-dev/files/13336267/log.txt)

**Comment by shirvanie** [comment]
Yes, I have full access. I could publish the packages before today

**Comment by shirvanie** [comment]
[log.txt](https://github.com/dart-lang/pub-dev/files/13336264/log.txt)

**Comment by isoos** [comment]
@shirvanie: it looks like the upload process looks good, until it gets hanging/aborted at the time the binary is being uploaded to google storage (`HTTP POST https://storage.googleapis.com`). Could you please download and run the following script locally?
https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart

Please copy its output here, it should give us some further insight where it may be failing.

**Comment by shirvanie** [comment]
C:/src/flutter/bin/cache/dart-sdk/bin/dart.exe --enable-asserts "E:\AndroidProjects\Flutter Projects\flutter_test1\lib\features\login\presentaion\story\check_domain.dart"
Testing host resolves...
- pub.dev IPv4 resolve and connect succeeded: 1 / 1
- pub.dev IPv6 lookup failed: SocketException: Failed host lookup: 'pub.dev' (OS Error: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
, errno = 11002)
- pub.dartlang.org IPv4 resolve and connect succeeded: 1 / 1
- pub.dartlang.org IPv6 lookup failed: SocketException: Failed host lookup: 'pub.dartlang.org' (OS Error: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
, errno = 11002)
- storage.googleapis.com IPv4 resolve and connect succeeded: 1 / 1
- storage.googleapis.com IPv6 lookup failed: SocketException: Failed host lookup: 'storage.googleapis.com' (OS Error: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
, errno = 11002)
Testing one connection per request...
Testing connection reuse...
- iteration #1/10...
- iteration #2/10...
- iteration #3/10...
- iteration #4/10...
- iteration #5/10...
- iteration #6/10...
- iteration #7/10...
- iteration #8/10...
- iteration #9/10...
- iteration #10/10...
Done.

**Comment by isoos** [comment]
Aside: you can use code fences to format (triple backtick characters "```") to format large code blocks:
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

Your network seems to actively block IPv6 connection attempts to these domains, and it prevents the upload. Was there any change on your side (OS, router, ISP) recently? I'm not an expert in these matters, but it seems to me that you should somehow disable IPv6 connections before publishing.
