### ISSUE TITLE
Unable to change email address while pblishing flutter package

### ISSUE THREAD

**Issue by Concerto-hub** [dart-lang/pub-dev#7180]
I am publishing two different packages for  different users.Now i have published one package but for publishing the second package it is showing the first email address. can you help me to change email address for publishing other package?

**Comment by isoos** [comment]
@Concerto-hub: It is not clear if it is the command line where you want to make this change, or on the pub.dev site. If it is the later, you have two options:

1) You can invite the other email address as admin to the package. After that, you can publish new versions with both emails. If you wanted to, you may remove the original email address from the admins (with the new account).

2) You can transfer the package to a verified publisher and add the new email as admin member of the publisher.

For the command line client, you'll need to copy and when needed change the credential files. (In which case it gets important which OS you are using.)
