### ISSUE TITLE
Can't leave organization

### ISSUE THREAD

**Issue by spydon** [dart-lang/pub-dev#7186]
When trying to leave an organization you get "Can't update self."
![image](https://github.com/dart-lang/pub-dev/assets/744771/27c7c885-cf65-4054-bc6a-963216a5a17c)
Pressed the cross icon on myself in the list there.

```
DELETE https://pub.dev/api/publishers/igindo.com/members/7a153c45-cd7e-4e71-848d-84ab737e4df4
409 Conflict
```

**Comment by isoos** [comment]
This is a deliberate protection to prevent accidental lose of control over a publisher. Please use another admin account to remove this one.

**Comment by parlough** [comment]
I think the protection makes sense but perhaps the error could be more clear/specific on that alternative route.

**Comment by spydon** [comment]
> I think the protection makes sense but perhaps the error could be more clear/specific on that alternative route. Or maybe the button shouldn't exist for yourself in the first place?

I don't have any contact with the other admin in the organization (last time it took 6 months before he replied).
Meanwhile not a huge issue, I think it should be possible to leave the organization, maybe not a bug then, but a feature request?
