### ISSUE TITLE
Allow `dart format ` with line length 120

### ISSUE THREAD

**Issue by techwn** [dart-lang/pub-dev#7187]
Currently, [pub.dev](https://pub.dev) enforces 80 characters per line otherwise you will get lower score with pana, which I think is a bit outdated.

Maybe we should allow 120 by changing the default value from 80 to 120, or allow configuration to be added in "analysis_options.yaml" or something else.

**Comment by isoos** [comment]
Closing as duplicate of #3041.
Note: we are not planning to change the defaults here right now, but open for arguments.
