### ISSUE TITLE
Pub.dev issue with Dart 3.2.0

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/pub-dev#7192]
If you publish a package that has Dart 3.2.0 as the minimal SDK, pub.dev analysis will fail:

```
 Sdk constraint doesn't support current Dart version 3.2.0-210.3.beta. Cannot run `dart pub outdated`.
```

**Comment by isoos** [comment]
Note: pub.dev does not automatically upgrades the analysis SDKs.
