### ISSUE TITLE
Analysis error with package that require Dart 3.2

### ISSUE THREAD

**Issue by bartekpacia** [dart-lang/pub-dev#7195]
I'm the author of [patrol](https://pub.dev/packages/patrol), [patrol_finders](https://pub.dev/packages/patrol_finders), and [patrol_cli](https://pub.dev/packages/patrol_cli) packages. All of them require Dart 3.2.x and Flutter 3.16.x because of breaking changes that took place in Flutter.

All these packages on pub.dev are currently showing `[ANALYSIS ISSUE]`, which negatively impacts how they present to the potential user.

<img width="815" alt="Screenshot 2023-11-16 at 12 16 23 PM" src="https://github.com/dart-lang/pub-dev/assets/40357511/908cbf33-e237-467d-9026-ddde71e01f1f">

**Comment by isoos** [comment]
Note: Note: pub.dev does not automatically upgrades the analysis SDKs. #7189 is on the way to get released.

**Comment by bartekpacia** [comment]
Thanks for quick response. Will you re-trigger analysis for the packages, or will I have to release 3 versions of each of these packages? I'd love for the former to happen :)

**Comment by isoos** [comment]
> Thanks for quick response. Will you re-trigger analysis for the packages, or will I have to release 3 versions of each of these packages? I'd love for the former to happen :)

pub.dev automatically re-analyses versions (*) with new runtimes, no need to publish new versions.

(*) not all of the versions, but after a heuristic some relevant ones, including the latest stable(s)

**Comment by isoos** [comment]
The linked packages have been analyzed with the new SDKs.
