### ISSUE TITLE
Pub Points still Pending after 38 hours

### ISSUE THREAD

**Issue by Andrious** [dart-lang/pub-dev#7218]
Usually doesn't take this long for Pub points:  [Fluttery Framework](https://pub.dev/packages/fluttery_framework/)

Would there be an issue with the package itself?

**Comment by isoos** [comment]
Couple of things to note here:

- we should expose log messages for pending but failed analysis tasks, in this case:
https://pub.dev/packages/fluttery_framework/score/log.txt
- we should log more

```
## Skipping analysis for "fluttery_framework" version "4.6.1"
date-time: 2023-11-23T05:41:29.613150Z

reason:
Processing of package versions exceeded allocated duration.
This is because all versions are analyzed in a single batch,
the other versions of this package took too long time to analyze.
```

When analyzing locally `pana` did complete just fine, it should be a fluke. IIRC it will be retried after a day, let's see it tomorrow.

**Comment by isoos** [comment]
Closing as fixed. With a new version published the retry context of the scheduling was lost, hopefully it was just a fluke.
