### ISSUE TITLE
How to dispose googlemap's widget ?

### ISSUE THREAD

**Issue by hinviarm** [dart-lang/pub-dev#7219]
URL: https://pub.dev/packages/google_maps_flutter

I have many screen in my application and when i clique previous on googlemap widget, it dont dispose and make my application bug

Can you help me please ?

Best regards

**Comment by sigurdm** [comment]
This is the issue tracker for the pub.dev site itself, not for individual packages.

For google_flutter_maps please ask in https://github.com/flutter/flutter/issues
