### ISSUE TITLE
How to transfer package ownership from publisher to main account

### ISSUE THREAD

**Issue by msayed-net** [dart-lang/pub-dev#7235]
Hello,

I want to move some packages back from publisher to main account, how to do that !

Thanks

**Comment by isoos** [comment]
The admin page says: "Upgrading to verified publishers is an irreversible operation. Packages can be transferred between publishers, but they can't be converted back to legacy uploader ownership."

Is there any reason not to use another publisher domain for the transfer?

**Comment by msayed-net** [comment]
Egypt limited foreign currencies payments, so I can not register any new domain and can not hold my domains much longer

**Comment by isoos** [comment]
Please contact support (`support@pub.dev`) about this issue. In the meantime, I have seen `<x>.blogspot.com` domains registered as publishers, so maybe you could register a new publisher with that domain and transfer the packages into it?
