### ISSUE TITLE
Execution of pana exited 255 when computing package score.

### ISSUE THREAD

**Issue by ditman** [dart-lang/pub-dev#7267]
After a version of one of our packages got published ([`package:google_identity_services_web v0.3.0`](https://pub.dev/packages/google_identity_services_web/versions)), the `pana` process crashed attempting to compute its score, with the following [log](https://pub.dev/packages/google_identity_services_web/versions/0.3.0/score/log.txt):

```
## Running analysis for "google_identity_services_web" version "0.3.0"
STARTED: 2023-12-07T12:50:08.395406Z

### Starting pana
Unhandled exception:
Exception: could not find 0.3.0
#0      fetchPubspec.<anonymous closure> (package:pub_worker/src/fetch_pubspec.dart:53:23)
#1      ListIterable.firstWhere (dart:_internal/iterable.dart:116:38)
#2      fetchPubspec (package:pub_worker/src/fetch_pubspec.dart:51:62)
<asynchronous suspension>
#3      main (package:pub_worker/src/bin/pana_wrapper.dart:67:19)
<asynchronous suspension>
### Execution of pana exited 255
STOPPED: 2023-12-07T12:50:22.323495Z
```

Was this a transient problem, or is there anything wrong with my package?

**Comment by ditman** [comment]
@isoos said that this is probably a transient error, and that it'll get automatically retried. Closing.

**Comment by isoos** [comment]
Reopening to track the missing retry/cache invalidation.
