### ISSUE TITLE
actions/publisher-members-list --Converting object to an encodable object failed: Instance of 'DateTime'

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#7272]
> INFO 2023-12-08T10:43:46.978Z pub: Handling request: https://pub.dartlang.org/api/admin/actions/publisher-members-list

api_builder: Unhandled error in API handler (incidentId: 4c00b9ed-daa0-4ebb-b7cb-7f54bb41b039)

Error:
    Converting object to an encodable object failed: Instance of 'DateTime'

**Comment by isoos** [comment]
I think this has been fixed and the fix has been deployed.
