### ISSUE TITLE
fake_server not generating jsonl file

### ISSUE THREAD

**Issue by ebenjs** [dart-lang/pub-dev#7277]
I ran into an issue with fake_server while setting up the development environment on Ubuntu 22.04.3 LTS, following this link https://github.com/dart-lang/pub-dev/blob/upgrade/doc/development.md. I've attached the complete stack trace file for your reference.
[stack_trace.txt](https://github.com/dart-lang/pub-dev/files/13621256/stack_trace.txt)

**Comment by isoos** [comment]
I think the core of your issue was that `pkg/web_app` and `pkg/web_css` was not built. I'm submitting a PR that forces those builds in an earlier step.
