### ISSUE TITLE
Package removal request

### ISSUE THREAD

**Issue by kwado-tech** [dart-lang/pub-dev#7306]
Hi, I published a couple of new packages in [pub.dev](http://pub.dev/) and could not find it under my [pub.dev](http://pub.dev/) user (which I re-authenticated [pub.dev](http://pub.dev/) to resolve this but unfortunately could not republish because of the initial-package already existing in pub.dev) but now, I already published 2 similar packages to understand what the issue is and would like to remove these packages in-order to publish the package (with some name corrections) after re-authenticating pub.

- https://pub.dev/packages/l10_mapper_annotation
- https://pub.dev/packages/l10_mapper_generator

- https://pub.dev/packages/l10n_mapper_annotation
- https://pub.dev/packages/l10n_mapper_generator

PS. The first published packages required name correction which led to the publication of the second duo.

I have filed this particular removal requests 2 times previously to support@pub.dev using my work and personal email addresses but these queries haven't been attended to (even though they were filed less than 48 hours after publishing these packages and I'm the package is not popular yet - as stated in pub policies).

**Comment by isoos** [comment]
@kwado-tech: Support requests are reviewed usually on a weekly schedule, but we are now into the holidays and vacations, so it may take longer than usual. This shouldn't affect the eventual evaluation of your request though, as you have filed it with accordance of the policies. Please keep communication on email, and do not file issues here.
