### ISSUE TITLE
Modals should "trap focus"

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#7308]
Currently the keyboard focus runs through the background controls when using TAB while the following modals are up:

* screenshot carousel
* Confirmation dialog in admin tab

Not sure about the best technique for this. But know at least the "page setup" dialog in google docs achieves this.

**Comment by isoos** [comment]
After a bit of investigation, I don't see any widespread standard that we could use, rather only the following two workarounds:
- catch keyboard and focus events, and if focus gets or would get outside of the modal dialog, we redirect it, preventing the default behavior
- disable all other focusable elements

After experimenting the later (and learning that you can disable `<link>` stylesheets in the `head` element), I think overall it is a more robust way than trying to fight the browser and prevent the default behavior. Cleaning up and sending a PR soon.
