### ISSUE TITLE
DeviceDetailsPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by abasilis** [dart-lang/pub-dev#7311]
URL: https://pub.dev/packages/device_details_flutter/versions

Hi,
When creating a new App in flutter, importing this package in the pubspec.yaml file, first the import in the Installing Tab does not reflect the real one, I had to import it right click the DeviceDetailsPlugin function and Import it from there.

Besides that, and the more important, I get the error below when running the App:
Note: /Users/UserName/.pub-cache/hosted/pub.dev/device_details_flutter-1.1.2/android/src/main/java/com/arif/device_details_plugin/DeviceDetailsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

I am using Flutter 3.16 and I created this project using flutter create command.

Thanks for taking the time looking at this issue, and correcting it. Also, I would like to see the OS name (Android, iOS, etc.) in the next version.

Thanks!

**Comment by isoos** [comment]
@abasilis: This repository is for the `pub.dev` site, and not for individual packages. For using the package and reporting requests for the package, please contact the authors (e.g. follow the `Homepage` or `Repository` link of the package).

For the Install tab issue, please be more specific and provide more details: what was the issue?

**Comment by abasilis** [comment]
Thanks for the information provided, I see not contact information in the device_details_flutter package on pub.dev, I thought that this was the only way to get in contact with the creator.
Thanks!
