### ISSUE TITLE
Is there any API that can obtain a list of dev versions for a package?

### ISSUE THREAD

**Issue by mdddj** [dart-lang/pub-dev#7340]
I am creating a new version detection function for the pubspec.yaml file, but it is unable to determine the information for obtaining pre release
Is there a relevant API that can obtain a list of pre release versions of packages?

<img width="503" alt="image" src="https://github.com/dart-lang/pub/assets/29020213/a6e2a5c5-35f6-405d-a376-30bd15c908a8">

The api I am currently using is https://pub.dartlang.org/api/packages/isar

**Comment by jonasfj** [comment]
We won't add any such API
