### ISSUE TITLE
package name support namespace

### ISSUE THREAD

**Issue by medz** [dart-lang/pub-dev#7356]
In pub.dev, as time goes by, the number of packages is increasing, and at the same time, there are also many developments leaving the dart community. Since pub.dev prohibits similar packages
Release, this resulted in many package names being occupied, which resulted in many package names being very strange.

Another problem is that these packages are difficult to remember, and they do not completely avoid the problem of similar package names, such as `fluttertoast` and `flutter_toast_plus`.

Therefore, we need a better namespace to solve this problem.

## Namespaces

In NPM, namespaces are implemented through `@`, such as `@angular/core`, `@angular/compiler`, `@angular/router`.
In Composer, namespaces are implemented through `vendor/package`, such as `symfony/console`, `symfony/yaml`.

In pub.dev, the existing publisher does not play any role other than marking the publisher. We can explore whether it is possible to use publisher
Implement namespaces.

## Implementation of namespace

In pub.dev, we can reference a package through `package:xxx/xxx.dart`. The name of this package is unique, but we can reference a package under a namespace through `package:@xxx/xxx` Bag.

Why `@`? This is just what I learned from NPM. When the package name starts with `@`, it means that this is a namespace package name, not an ordinary package name.

## Usage of namespace

```yaml
name: @foo/bar
dependencies:
   @fluttertoast/fluttertoast: ^8.0.7
   @vuejs/compiler: ^3.0.11
```

## Determination of permissions

For the use of namespaces, we need to determine a permission issue, such as `@fluttertoast/fluttertoast`, who owns this package? Is it from `fluttertoast`?

Then, the name after @ is the publisher's custom ID. This ID is unique and cannot be modified. This ID will be generated during registration and cannot be modified.

## How to deal with existing Publisher?

For existing Publishers, we allow him to set his own namespace, but this namespace must be unique and cannot be modified.

## How to deal with existing Packages?

As for the definition of publisher, it allows publishing ordinary packages, so there is no need to change it.

## Release process

Now when pub publishes a package for the first time, it is published as pub user, so we need to modify the publishing process so that users can choose to publish as publisher. For example, if the package name is `@foo/bar`, the publisher can choose `foo` as the publisher.

## Another idea

The publisher tag is marked with a domain name. We can use the publisher tag directly in the namespace, such as a namespace like `dart.dev/for`, so there is no need for `@`.

**Comment by sigurdm** [comment]
Related to https://github.com/dart-lang/pub-dev/issues/4146
