### ISSUE TITLE
`flutter_web_plugins` redirect to 404

### ISSUE THREAD

**Issue by osaxma** [dart-lang/pub-dev#7357]
Typing the following url: https://pub.dev/packages/flutter_web_plugins

redirects to: https://api.flutter.dev/flutter/package-flutter_web_plugins_flutter_web_plugins/package-flutter_web_plugins_flutter_web_plugins-library.html

which gives the following error:
<img width="672" alt="Screen Shot 2024-01-08 at 10 30 06 AM" src="https://github.com/dart-lang/pub-dev/assets/46427323/f38ab4e9-e2d6-4b81-9ebe-120d7c929b90">

----
Please let me know if this should be filed elsewhere.

**Comment by isoos** [comment]
Thanks for filing, good catch!
