### ISSUE TITLE
Package dio api doc search not working

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#7367]
https://pub.dev/documentation/dio/latest/
Says "loading search results...", never finishing

There is a minified error in the console:
<img width="1642" alt="image" src="https://github.com/dart-lang/pub-dev/assets/8613953/36663a23-335c-42b7-9edd-fc9d21935589">

**Comment by isoos** [comment]
I was able to reproduce this locally with the latest dartdoc, and I think it is already reported as an issue at dartdoc repository:
https://github.com/dart-lang/dartdoc/issues/3614

**Comment by isoos** [comment]
Note: https://github.com/dart-lang/dartdoc/pull/3616 will fix this. If we think this is urgent, we could (a) roll-in the compiled JS files from dartdoc upfront, or (b) update the generated `index.json` file and always fill out the missing field.

**Comment by sigurdm** [comment]
We'll just roll it in with the next dartdoc roll.

**Comment by isoos** [comment]
This has been fixed.
