### ISSUE TITLE
We still use "null-safety" in version listing, but "dart 3 compatible" in search listing and package page header

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#7396]
![image](https://github.com/dart-lang/pub-dev/assets/8613953/726af39d-10f8-43fb-b0e1-8965207dee3a)

Maybe there is a good reason... I don't remember.

**Comment by isoos** [comment]
Null safety can be calculated from the SDK constraint itself, but compatibility requires further analysis, and we don't analyze every package version.

**Comment by sigurdm** [comment]
Good point - maybe we can not do much more here.

Btw. what further analysis are we doing to decide on dart-3-compat?

**Comment by sigurdm** [comment]
Ah - I think I remember now - all dependencies can resolve null-safety also
