### ISSUE TITLE
Page title should include search terms when searching on pub.dev/documentation

### ISSUE THREAD

**Issue by szakarias** [dart-lang/pub-dev#7406]

**Comment by sigurdm** [comment]
Eg: https://pub.dev/documentation/retry/latest/search.html?q=abc

**Comment by isoos** [comment]
I think we shouldn't have pages like that.

**Comment by sigurdm** [comment]
I think the issue title was misleading.

The point is that the title of the search results page should reflect that it contains search results.

(it should probably be excluded from bots if it is not already)

**Comment by sigurdm** [comment]
Like https://pub.dev/packages?q=camera the title says "Search results for camera"
