### ISSUE TITLE
Atribute and the usage is not similar on your site 

### ISSUE THREAD

**Issue by Sstromdev** [dart-lang/pub-dev#7432]
URL: https://pub.dev/packages/flutter_advanced_switch

There is the problem in you site like there is the section  attribute usage there in enbeld attribute saying defining height and in height attribute saying defining width and same for sum of the other one so check it and do it correct 
![Screenshot 2024-01-24 154511](https://github.com/dart-lang/pub-dev/assets/157590414/ddf85e51-1825-4240-a595-4b5a6e3f2c4b)

**Comment by isoos** [comment]
@Sstromdev: this issue tracker is for the `pub.dev` site, and not for individual packages. Please report this issue to the package authors' repository.
