### ISSUE TITLE
New rate limit for "pub publish" too low

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/pub-dev#7445]
Recently, changes were made to enable publishing only 10 packages at once before hitting API rate limit.

This is IMO too low. When managing multiple packages at once, it is easy to reach this rate limit.
For instance, FlutterFire has 20 packages. Riverpod has 10 packages. Flame has more than 10 too.

**Comment by russellwheatley** [comment]
To add to that, FlutterFire has even more than 20 packages, it has 50+ packages. Trying to simultaneously publish all those packages is not possible with this rate limit and caused our publishing pipeline to fail.

**Comment by isoos** [comment]
We have separate limits for burst (2-minutes), hourly and daily. As the hourly limit is 100, I believe you have hit the burst (2-minutes) window.

While these limits may be changed, I'm curious: what is your workflow for publishing 10-50+ packages all at once? Do you accumulate changes for all of them?

Also: would it be feasible to change your workflow to wait 1-2 minutes between every 10 packages being published?

**Comment by rrousselGit** [comment]
Releases tend to be made in a bundle, yes.

It is inconvenient to make a release after every change. We lose a bit of control over the "version" of our packages.
So on a weekly schedule, it's possible for quite a few packages to be published at once.

**Comment by russellwheatley** [comment]
This is the error I received in the console:
```
Uploading...
The operation is blocked, as rate limit in the current window has been reached (10 in the last few minutes). Please try again later.
```
Which indicates we have hit a limit of 10. 

We need to publish at the same time as packages depend on each other. Here is an example of our latest release: https://github.com/firebase/flutterfire/pull/12233/files

**Comment by russellwheatley** [comment]
Here is where the exception is occurring: https://github.com/dart-lang/pub-dev/blob/4fbe95d434f2bec4336ffe343957c30f43d1dc0c/app/lib/shared/exceptions.dart#L352-L354

**Comment by jonasfj** [comment]
Are limits are configured in:
https://github.com/dart-lang/pub-dev/blob/4fbe95d434f2bec4336ffe343957c30f43d1dc0c/app/config/dartlang-pub.yaml#L74-L83

Perhaps we should not make a difference between `burst` and `daily` for `package-publisher` scoped by `user`.

Maybe a simple solution would be:
```yaml
  - operation: package-published
    scope: user
    burst: 200
    hourly: 200
    daily: 200
```

Perhaps we should just say that publishing 200 packages per day is a lot, and hopefully sufficient. And spreading them across multiple minutes or hours, shouldn't really be required.

@russellwheatley, @rrousselGit, would a limit of 200 package publications per user per day be sufficient?

----------------

We could also make some heuristics or allow-listing to grant higher quotas. But that seems like something that take longer to do, and we don't want to interrupt people here.

**Comment by rrousselGit** [comment]
> @russellwheatley, @rrousselGit, would a limit of 200 package publications per user per day be sufficient?

Sure!

**Comment by russellwheatley** [comment]
> @russellwheatley, @rrousselGit, would a limit of 200 package publications per user per day be sufficient?

@jonasfj - sounds great 🚀

**Comment by jonasfj** [comment]
@isoos maybe we should also improve the error message by mentioning:
 * What rate-limit was reached (Even if we're just giving a string like `package-published`).
 * Where to report the issue (https://github.com/dart-lang/pub-dev/issues/new if you think rate-limits should be increased to accommodate your use case)

After all, we are absolutely not looking to impact the ecosystem here. We're looking to minimize the negative impact of a degenerate behavior, in particular bots. Towards that end, it's perhaps best that the limits are a bit too high, rather than us complicating the workflows of legitimate package authors.

**Comment by isoos** [comment]
The increased limit has been deployed.
