### ISSUE TITLE
Redirect to case-normalized package page

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#7455]
We could let
pub.dev/packages/Retry redirect to pub.dev/packages/retry

**Comment by isoos** [comment]
Do we have these via links, or users type them? Also, what about `/packages/ReTrY`?

**Comment by sigurdm** [comment]
> Do we have these via links, or users type them?

I typed one of these recently and was confused by the 404

> Also, what about /packages/ReTrY?

Yeah - I think just make everything lower-case
