### ISSUE TITLE
"Recently Updated" sort not working

### ISSUE THREAD

**Issue by NeroThroN** [dart-lang/pub-dev#7458]
Filtering with "Recently Updated" not working anymore. All packages in the results have been updated 3 days ago and the order never changes

![image](https://github.com/dart-lang/pub-dev/assets/38684083/97ff8fa2-702d-4f19-815f-cb8ea4bddb99)

**Comment by isoos** [comment]
Thanks for reporting this. It looks like the index update process has been stuck, we are investigating it.

**Comment by NeroThroN** [comment]
Seems fixed!
Thanks 💙
