### ISSUE TITLE
Problem to update package

### ISSUE THREAD

**Issue by JhonaCodes** [dart-lang/pub-dev#7465]
## Erorr Message:
`flutter pub publish`
The "package-published" operation is blocked, as its rate limit has been reached (3 in the last few minutes). Please try again later. Please report the issue on https://github.com/dart-lang/pub-dev/issues/new if you think the limit should be increased to accommodate your use case.

`flutter pub publish --dry-run`
~~~
Resolving dependencies... 
  matcher 0.12.16 (0.12.16+1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.10.0 (1.12.0 available)
  path 1.8.3 (1.9.0 available)
  test_api 0.6.1 (0.7.0 available)
  web 0.3.0 (0.4.2 available)
Got dependencies!
6 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Publishing flex_gap 0.2.2 to https://pub.dev:
├── CHANGELOG.md (<1 KB)
├── LICENSE (1 KB)
├── README.md (4 KB)
├── analysis_options.yaml (<1 KB)
├── example
│   └── main.dart (4 KB)
├── lib
│   ├── flex_gap.dart (1 KB)
│   ├── render
│   │   └── box_gap.dart (1 KB)
│   └── ui
│       ├── flex_gap_widget.dart (4 KB)
│       └── widget
│           ├── expanded_gap.dart (1 KB)
│           ├── main_flex_gap.dart (<1 KB)
│           └── scroll_gap.dart (1 KB)
├── pubspec.yaml (1 KB)
└── test
    ├── expanded_gap_test.dart (1 KB)
    ├── flex_gap_test.dart (<1 KB)
    ├── render_box_gap_test.dart (<1 KB)
    └── scroll_gap.dart (<1 KB)

Total compressed archive size: 7 KB.
Validating package... (1.3s)
Package has 0 warnings.
The server may enforce additional checks.
~~~

`flutter doctor -v`
~~~
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.3 23D56 darwin-arm64, locale en-NZ)
    • Flutter version 3.16.9 on channel stable at /opt/homebrew/Caskroom/flutter/3.13.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (12 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jhonatanortiz/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
~~~
It should be noted that this error appeared to me 14 hours ago yesterday and I tried again today and the same thing appears, maybe I should wait 24 hours?.
Thanks.

**Comment by isoos** [comment]
> and I tried again today and the same thing appears

I think yesterday you had hit the burst limit, and today you may have hit the 12 versions/24-hours limit (it has a different message in the allowed number / time window). Could you please confirm that?

Otherwise: yes, this is a rate limit that is expected if you publish too many versions.

**Comment by JhonaCodes** [comment]
> > and I tried again today and the same thing appears
> 
> I think yesterday you had hit the burst limit, and today you may have hit the 12 versions/24-hours limit (it has a different message in the allowed number / time window). Could you please confirm that?
> 
> Otherwise: yes, this is a rate limit that is expected if you publish too many versions.

To confirm: I don't have a different message in the number/time allowed window, I guess I have to wait 24 hours.
  The error occurred yesterday at 5 pm, I guess I'll try tomorrow.
  Thanks :)

**Comment by JhonaCodes** [comment]
Exactly 24 hours later I made an attempt and was able to update, so I trust that in this case I only had to wait 24 to be able to upload a new update of my package, thank you.
