### ISSUE TITLE
Topic links are broken when the topic name contains a space

### ISSUE THREAD

**Issue by schultek** [dart-lang/pub-dev#7469]
I have a package published on pub.dev that uses dartdoc topics for structuring the documentation. A user of the package pointed out that several links inside the documentation are currently broken, and these are all for topics with a name that contains a space. 

Opening any of those topics from the sidebar returns a "404 Not Found".

Reproduce:

- Go to "https://pub.dev/documentation/dart_mappable/latest/"
- Click "Mapping Hooks" in the left sidebar (or any other topic with a space)

Notes:

I did not publish a new version of that package. All of these doc pages (also from older versions) that previously worked are now broken.

**Comment by isoos** [comment]
I think this is the culprit: https://github.com/dart-lang/pub-dev/pull/7449
We need to also enable spaces in the URL patterns.

**Comment by schultek** [comment]
Wow, thanks for the super quick fix 👍
