### ISSUE TITLE
pub.dev uses dev versions of dart/flutter toolchain

### ISSUE THREAD

**Issue by espresso3389** [dart-lang/pub-dev#7484]
If I publish a plugin that declares the version constraints like:

```
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19'
```

I saw `[ANALYSIS ISSUE]`:

![image](https://github.com/dart-lang/pub-dev/assets/1311400/19db7603-ecec-4a35-8087-93de599213a7)

And I modified SDK min to `3.3.0-76.0.dev`, then another flutter version error occurred.

![image](https://github.com/dart-lang/pub-dev/assets/1311400/60f09d72-8256-4daa-baea-3f046cf7a47a)

So, I'm finally uses the following constraints:

```
environment:
  sdk: '>=3.3.0-76.0.dev <4.0.0'
  flutter: '>=3.19.0-0.4.pre'
```

But I finally got yet another error:

![image](https://github.com/dart-lang/pub-dev/assets/1311400/4925b31d-4f6b-4488-ba88-efe768253f39)

The problem actally does affect nothing. But when pub.dev introduces the stable versions?

**Comment by isoos** [comment]
> But when pub.dev introduces the stable versions?

We upgrade analysis SDKs on a custom schedule, manually, usually not long after their official release. As we tend to be not releasing a new site version on Friday, the 3.19 upgrade is expected to happen early next week.

**Comment by spydon** [comment]
This also affects all API docs:
https://pub.dev/documentation/flame/1.16.0/

And you can't read the previous docs as a workaround either since they are redirected to the new version:
https://pub.dev/documentation/flame/1.15.0/

**Comment by spydon** [comment]
Is there any plan to organize a coordination effort with the Flutter team so that this doesn't happen every new release?

**Comment by sigurdm** [comment]
The flutter sdk is updated now.

**Comment by espresso3389** [comment]
I've confirmed my plugin is now correctly analyzed on pub.dev!

https://pub.dev/packages/pdfrx/versions/1.0.7
