### ISSUE TITLE
The search experience on pub.dev is too poor.

### ISSUE THREAD

**Issue by kjxbyz** [dart-lang/pub-dev#7488]
The search experience of `pub.dev` is too poor. For example, when I search for `dxcaptcha_flutter`, this package can be accurately matched, but because it has just been released, it is ranked at the bottom.

You can refer to `npmjs.com`. The accurately matched package will be ranked first.

![20240217-154001](https://github.com/dart-lang/pub-dev/assets/47768002/7f804c0d-8137-4e84-9ed5-9b2c7e6536a8)

**Comment by isoos** [comment]
@kjxbyz: Search index is updated every 15 minutes or so. The package is now matched and displayed as first hit.
