### ISSUE TITLE
Publishing rate limited with wrong limit and window in the rejection message.

### ISSUE THREAD

**Issue by malengatiger** [dart-lang/pub-dev#7522]
Hi,
My publishing has been blocked even though it has been more than an hour since my last attempt. How do I fix this?

**Comment by sigurdm** [comment]
What error message are you seeing? What is the package?

**Comment by malengatiger** [comment]
the package is mistral_sgela_ai. the error: The "package-published" operation is blocked, as its rate limit has been reached (3 in the last few minutes). Please try again later. Please report the issue on https://github.com/dart-lang/pub-dev/issues/new if you think the limit should be increased to accommodate your use case.

**Comment by isoos** [comment]
First of all, looking at the changelog, this is exactly the use-case that we want to discourage: you seem to publish a new version on each commit with small changes. Please don't put much stress on publishing each small change, it is better and cleaner for your users to get an updated version every now and then, and not having to upgrade 10+ versions each day. For many practical considerations, we limit the number of versions a package may have, and with this rate, you will reach that in a few months, forcing you to chose a new name for new versions.

You also seem to hit not only burst but hourly and daily rate limits, however we may report the wrong window of what has been triggered. We shall investigate why that happens and fix that.
