### ISSUE TITLE
I need to delete my account and my packages because I can't Edith th package name which I uploaded to pub dev

### ISSUE THREAD

**Issue by mazab99** [dart-lang/pub-dev#7585]

**Comment by isoos** [comment]
Please follow the policy as described here: https://pub.dev/policy

Note: package publishing is immutable. You may upload a new package with a different name though, and let the old one be as-is. In most cases we won't allow name reuse anyway.

**Comment by mazab99** [comment]
this was my package 
https://pub.dev/packages/paginated_search_drop_down

and i want to rename it so i changed the name of it in the code 

and try to publish it 
and when i finished publishing i got it as a new package
https://pub.dev/packages/high_q_paginated_drop_down

how can i fix this problem ?

@isoos

**Comment by isoos** [comment]
@mazab99: you may continue publishing it as `high_q_paginated_drop_down`, and maybe mark `paginated_search_drop_down` as discontinued. Also, if you wanted to, you may follow the policy page's process for package deletion.

**Comment by isoos** [comment]
I've forgot to emphasize: we don't support package renaming. If you publish a package version, it should be treated as an immutable publication, and expect that people may use it. Renaming would abrupt their workflow, and it is hard to track the dependencies if you want tight control over them. Therefore, you may only publish a new package, but not rename one.
