### ISSUE TITLE
Preview Release not showing up as a Preview (for Flutter Beta)

### ISSUE THREAD

**Issue by ABausG** [dart-lang/pub-dev#7586]
URL: https://pub.dev/packages/home_widget/versions/0.6.0

I released two new Version today of home_widget

Version 0.5.0

And Version 0.6.0

Version 0.6.0 has some fixes for Flutter 3.20

I changed the flutter constraint in the pubspec.yaml file accordingly to:

```
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=3.20.0-1.2.pre'
```

Base on this comment by @mit-mit https://github.com/ABausG/home_widget/issues/225#issuecomment-1991048192 I assumed that it would only show up as a preview and not as the latest version when going to https://pub.dev/packages/home_widget

The documentation for Preview Releases only states the preview feature for dart versions: https://dart.dev/tools/pub/publishing#publishing-previews

Did I do something wrong and should've added a `pre-release` tag to the version?

Or is this because home_widget did not yet reach 1.0.0?

**Comment by sigurdm** [comment]
Yes, to mark a version pre-release you need to add a prerelease label to the version number itself.

**Comment by isoos** [comment]
For pre-release versions, you need to use `-some-kind-of` postfix labels in the version. However, for preview, you may use normal stable versions, and we may mark it as preview based on SDK constraints. Currently only the Dart SDK constraint is considered for this. I think we should also consider the Flutter SDK constraint.

So far it were usually the Dart core packages that wanted to have preview versions, or they have also set preview SDK constraint for Dart. Your package still claims to be working with Dart 2.12, which by the way is clearly not true if you rely on the latest Flutter beta SDK.

**Comment by ABausG** [comment]
Ah I see totally overlook to adjust the Dart version to the correct constrained!

Guess If I point the lower constraint to ` sdk: '>=3.4.0-99.1.beta <4.0.0'` it should show up as a preview.

@isoos guess it would make sense to retract the 0.6.0 version and release it as something like a `0.6.0+1`?

**Comment by isoos** [comment]
> guess it would make sense to retract the 0.6.0 version and release it as something like a 0.6.0+1?

It is up to you, but why not just leave it as-is, if this is only about the status pub.dev displays? People using and depending on it would't see any difference (beta Flutter users may use it, everybody else wouldn't upgrade to it anyway). It is likely we may be able to fix the SDK constraint soon (although deployment of it may be only next week or later due to Easter), and it will fix itself.

**Comment by mit-mit** [comment]
Thanks @ABausG for filing this, I myself too thought that Flutter SDK constraints were possible for preview releases. It looks like we just landed a fix!

**Comment by ABausG** [comment]
Awesome thanks!

I guess the package would need to be re-analyzed in order for this to be applied?

**Comment by isoos** [comment]
> I guess the package would need to be re-analyzed in order for this to be applied?

Yes, this automatically happens when the landed fix is deployed, and your package will get the new status. Unfortunately we couldn't land this last week due to unrelated issues, but I hope it will land in a few days now.
