### ISSUE TITLE
Publishing a package with an SDK vendored dependency fails

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub-dev#7596]
I am trying to publish [package:macros](https://github.com/dart-lang/sdk/tree/main/pkg/macros) - this is a package which has only one dependency, which is an SDK vendored dependency (similar to how Flutter packages work).

When I try to publish though, I get an error: "Dependency `_macros` does not exist."

This check should be skipped for SDK packages. Presumably, it is already somehow skipped for Flutter packages? Or do they have a version published on pub just to avoid this?

**Comment by jonasfj** [comment]
Short-term work-around: publish `package:_macros` -- just a dummy package such that the name is reserved, then you should get past this check.

Long-term fix: We don't require the package exists on pub.dev, if it's an SDK-dependency.

But even in this case, we really should make you publish a dummy package to ensure that the `_macros` package name is reserved. So it won't be taken by a malicious actor or cause confusion with the SDK-package.

Probably we should still require that the matching SDK-package name is allow-listed, and that the name can't be created on pub.dev in the future (but can be updated, if it already exists).

--------

unrelated, but curious: Why is `macros` not an SDK package?

**Comment by jakemac53** [comment]
> unrelated, but curious: Why is `macros` not an SDK package?

There was some general pushback on making users understand a new concept (fwiw I argued it's not new, most of our users are flutter users, who already know this concept).

The other reason is this gives us more flexibility - the indirection gives us the ability to change back to using `dart:_macros` or something later, without affecting users.

**Comment by jakemac53** [comment]
> Short-term work-around: publish `package:_macros` -- just a dummy package such that the name is reserved, then you should get past this check.

SGTM I can do that

**Comment by jakemac53** [comment]
I tried to publish `_macros` but got:

```
Package name _macros is too similar to another active package: macros (https://pub.dev/packages/macros).
```
