### ISSUE TITLE
Slow tests in test/package/upload_test.dart

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#7608]
I was playing around with: `DEBUG=* dart test test/package/upload_test.dart` and I noticed that tests are really slow.

I reviewed the logs and found:
```
 2445 ms [frontend.search_adapter] INFO: Unable to search packages.
ERROR: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 35688, uri=http://localhost:0/search?q=is%3Aflutter-favorite&tags=-is%3Adiscontinued&tags=-is%3Aunlisted&tags=-is%3Alegacy&offset=0&limit=100, null
```

Are we forgetting to setup something, or doing some sort of retries in the start of the server.

I think this single file takes 2 min, and most of it is probably us spending 2.5s every time we start a test case :see_no_evil:

**Comment by isoos** [comment]
The main reason seems to be the search attempt to connect to `http://localhost:0` timing out after ~2-2.5 seconds, making most of the test cases run longer than needed. However, while #7677 was a simple workaround, it broke most landing page and listing page test, and this needs to be investigated a bit more.

**Comment by isoos** [comment]
It looks like that for most tests we were failing to use/initialize the regular search and have used the fallback search (after a `SocketException` but not a `TimeoutException`). I think we should (a) fix the tests to use the regular search, and (b) refactor and maybe even remove the fallback search (as it will provide confusing or bad data for non-name search queries).
