### ISSUE TITLE
flutter pub and tor

### ISSUE THREAD

**Issue by Rubyer77** [dart-lang/pub-dev#7615]
Many `flutter` commands like `flutter pub outdated` don't work when behind Tor.
Solution would be to make sure all your backend servers accept connections from Tor exit nodes.

**Comment by isoos** [comment]
We don't have any explicit blocker against any VPN services (including tor). I haven't tried it, but I imagine that network-translating wrappers like `torsocks` should just work, unless the tor exit node has troubles accessing the servers. Maybe try restricting the exit nodes to a few specific countries?

**Comment by isoos** [comment]
I don't see what we can do on our end, closing the issue.
