### ISSUE TITLE
[proposal] provide a sign in option alternative google account

### ISSUE THREAD

**Issue by iapicca** [dart-lang/pub-dev#7616]
it would be nice be able to sign in without needing a google account
possibly a "regular" email and password sign-in option would be nice

**Comment by sigurdm** [comment]
This is currently not a priority for us.

You would always need some kind of account on pub.dev - and pub.dev is controlled by google - so in the end you would have some kind of "google" account.

We would not like to support non 2fa-login. And implementing 2fa is a big task.

also check out https://support.google.com/accounts/answer/27441?hl=en for how to make a google account for  a non-google email.

**Comment by sigurdm** [comment]
Closing this as we'll not do this in a foreseeable future.

**Comment by iapicca** [comment]
> This is currently not a priority for us.
> 
> You would always need some kind of account on pub.dev - and pub.dev is controlled by google - so in the end you would have some kind of "google" account.
> 
> We would not like to support non 2fa-login. And implementing 2fa is a big task.
> 
> also check out https://support.google.com/accounts/answer/27441?hl=en for how to make a google account for a non-google email.

@sigurdm 
I understand that 2FA is a tall order, 
but at least signing in with github would be nice
