### ISSUE TITLE
Fatal package site error.

### ISSUE THREAD

**Issue by NikhilRajbhar111** [dart-lang/pub-dev#7624]
I searched for the "dio" package and got "Fatal package site error." which was fixed once i refreshed the page but than i searched for "image" and got the same error again but this time refresh didn't worked.

Here is the complete error message

Pub is not feeling well
Fatal package site error.

Please open an issue: https://github.com/dart-lang/pub-dev/issues/new

Add these details to help us fix the issue:

Requested URL: https://pub.dev/packages?q=image
Request ID: 2c94ea7f627c718b83484de6281b9d5a

**Comment by FaFre** [comment]
Its not only search anymore, viewing packages such as https://pub.dev/packages/animated_size_and_fade as well.

**Comment by jonasfj** [comment]
The services appears to have been dropping some requests over the past hour.

It mostly looks like it's recovering on it's own, but I migrated traffic back to a previous deployment and is keeping an eye on it.

From a high-level it looks like some of the caching has been failing, but it's unclear why.

**Comment by nikeokoronkwo** [comment]
Requested URL: https://pub.dev/
Request ID: d7f406c4a630e48d308df03f9a5887a2

Similar issue here: #7631

**Comment by isoos** [comment]
Update: we were able to upgrade the redis instance (+additional configuration to prevent similar OOM in the future) and the site should operate as normal.
