### ISSUE TITLE
The word "record" triggers issues in pubdev searches.

### ISSUE THREAD

**Issue by mi6ock** [dart-lang/pub-dev#7629]
The word "record" triggers issues in pubdev searches.

![image](https://github.com/dart-lang/pub-dev/assets/12440462/ca9c80d7-5604-476d-9d3d-5661be9ffb65)

**Comment by amadzarak** [comment]
It's the search functionality in general

**Comment by jonasfj** [comment]
Thanks for reporting this!

Closing as duplicate of https://github.com/dart-lang/pub-dev/issues/7624
