### ISSUE TITLE
插件更新不及时 (Plug-ins are not updated in time)

### ISSUE THREAD

**Issue by jianxingbieli** [dart-lang/pub-dev#7641]
URL: https://pub-web.flutter-io.cn/
比如nim_core 已经有了1.7.7版本，但是更新的时候时候，获取不到最新的版本。
不只是是不是更前几天的https过期有关，希望可以修复.

<Describe your issue or suggestion here>

**Comment by sigurdm** [comment]
(google translate)
> Plug-ins are not updated in time

> For example, nim_core already has version 1.7.7, but when updating, the latest version cannot be obtained.
It’s not just related to whether the https expired a few days ago, I hope it can be fixed.

Maybe our new caching headers are interfering with the community mirror?

@chenglu
@jonasfj

**Comment by pickalex** [comment]
The same issue exists with other plugins as well, such as fluttertoast on [flutter](https://pub-web.flutter-io.cn/). It has been updated to version 8.25, but in the list, it shows 8.25, yet when you click on details, it still shows 8.24

**Comment by chenglu** [comment]
Sorry for the late reply and fix, I am currently welcoming a new family member. The CDN cache purge script stopped unexpectedly, and has now returned to normal.

**Comment by isoos** [comment]
Closing as this is unrelated to `pub.dev` (and also it has been fixed since).
