### ISSUE TITLE
Dart package analysis fails on pub.dev, work locally

### ISSUE THREAD

**Issue by yoer** [dart-lang/pub-dev#7644]
I found that this problem has occurred before.

[7521](https://github.com/dart-lang/pub-dev/issues/7521)
[7149](https://github.com/dart-lang/pub-dev/issues/7149)

It is successful in my local area:
![image](https://github.com/dart-lang/pub-dev/assets/11307627/e4663322-e3b4-4e5b-8d58-03e3ac0880fa)

On pub.dev it is failed like this:

[log](https://pub.dev/packages/zego_uikit/versions/2.22.1/score/log.txt)

![image](https://github.com/dart-lang/pub-dev/assets/11307627/059bd0b3-d560-49fd-a34e-c9f5703a4fc7)

**Comment by isoos** [comment]
Not entirely sure what is happening here, but it looks like you may be triggering the `nodoc` error message from dartdoc. We are using `dartdoc 8.0.7` at the moment, could you try to run that against your package locally?

**Comment by yoer** [comment]
**nodoc** , that's warning right?

that's result after run **dartdoc**, also success locally
```terminal
dart pub global activate dartdoc 8.0.7
flutter --no-version-check pub global run dartdoc --output /tmp/dartdoc-zego_uikitQVAWHL --sanitize-html --max-file-count 10000000 --max-total-size 2147483648 --no-validate-links 
```
[dartdoc.txt](https://github.com/dart-lang/pub-dev/files/14995731/dartdoc.txt)

**Comment by isoos** [comment]
When I download the latest archive of `zego_uikit` and run `dartdoc` locally, I get the following errors:

First, a bad reference from `dartdoc_options.yaml`:
```
Unhandled exception:
PathNotFoundException(path=/[...]/doc/header.html; message=Cannot open file)
```
Which is not a problem on `pub.dev`, because we happen to remove the particular entry that references it. After a local update, the next error is the following:
```
 In categories definition for APIs, "markdown" resolves to the missing file /[...]/doc/apis.md
#0      CategoryConfiguration.fromYamlMap (package:dartdoc/src/dartdoc_options.dart:113:13)
```

The root cause of these issues is that the package archive is not complete, references items outside of it. Your local setup may be different from what you are publishing, and the `dartdoc` has no issue with it. To get it running on `pub.dev`, make sure that every references file is correct in the archive.

I'm unsure why we don't have the error in the `log.txt` file, we should have the full output there.

**Comment by Yerannnnnn** [comment]
@isoos Thanks, But our package should not have missing files.

please help to check this case, facing same issue:

pub.dev doc log: https://pub.dev/packages/zego_uikit_prebuilt_call/versions/4.8.2/score/log.txt
repo: https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter.git
![image](https://github.com/dart-lang/pub-dev/assets/25857691/d5e81936-94f5-40ab-9864-7afbfa4db33c)



my local test command:
```bash
git clone https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter.git --depth 1
cd zego_uikit_prebuilt_call_flutter
dart pub global activate dartdoc 8.0.7
flutter --no-version-check pub global run dartdoc --output /tmp/dartdoc-zego_uikitQVAWHL --sanitize-html --max-file-count 10000000 --max-total-size 2147483648 --no-validate-links
```

test result:
```
Found 38 warnings and 0 errors.
Documented 26 public libraries in 7.7 seconds
Success! Docs generated into /tmp/dartdoc-zego_uikitQVAWHL
```

My dart version: 
```bash
$dart --version
Dart SDK version: 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "macos_arm64"
```

I also checked our repository and there is no `.pubignore` file, any ideas?
Many Thanks.

**Comment by isoos** [comment]
I'm not sure about the other package, but the previous one has no `doc/` folder in the uploaded archive file:
https://pub.dev/api/archives/zego_uikit-2.22.1.tar.gz

**Comment by yoer** [comment]
![image](https://github.com/dart-lang/pub-dev/assets/11307627/63861b88-3b8c-463e-8c95-68928e76c3de)

Found the problem, it is caused by the **.gitignore** file, which causes pub publish to lose the doc/*. * file when uploading to the pub.dev.

However, as far as I know, during the pub publishing process, **.gitignore** should not take effect, right? what should take effect is **.pugignore**.

**Comment by isoos** [comment]
Only if you have both files:

> To use different ignore rules for git and dart pub publish, create a .pubignore file to overrule the .gitignore file in a given directory. If a directory contains both a .pubignore file and a .gitignore file, then dart pub publish ignores that directory's .gitignore file. The .pubignore files follow the same format as the .gitignore file.

https://dart.dev/tools/pub/publishing#what-files-are-published

**Comment by yoer** [comment]
👌🏻
