### ISSUE TITLE
Feature request: To copy package latest version directly from the search result listing

### ISSUE THREAD

**Issue by Musaddiq625** [dart-lang/pub-dev#7667]
I always prioritize user experience as my first priority. 📈 
I have a suggestion for improving the user experience on [pub.dev](http://pub.dev/): 😶

Can you guys add a functionality of 'Copy latest version' on the packages listing?

It would be very convenient for the developers to:
1. Search for a package
Go to detail page ❌
2. Copy its latest version
3. Search for another package
4. Repeat steps 1 to 4

Currently, we need to go back and forth between the listing page and the detail page just to copy the version number 😵

**Sample result:**

![image_2024-04-22_011524487](https://github.com/dart-lang/pub-dev/assets/37911054/c927173e-32f5-4d7d-8e6a-bfb6b03f8567)

**Comment by abdul-salam111** [comment]
Yes, this make sense. It's very frustrating and difficult to go back and forth. @fluttergithubbot please resolve the issue.

**Comment by sigurdm** [comment]
I like this idea.

**Comment by Jacob-dvlp** [comment]
Nice idea
