### ISSUE TITLE
package-published operation is blocked

### ISSUE THREAD

**Issue by devbathani** [dart-lang/pub-dev#7688]
The "package-published" operation is blocked, as its rate limit has been reached (12 in the last day). Please try again later.
As the package on which i am working have anonymous functions due to which to test of the function are working fine, we have to release a new version everytime, i would like to request to unblock my operations and allow to push new versions more then 12 per days 
Thank You

**Comment by isoos** [comment]
@devbathani: how do you depend on this package in the anonymous function? For faster developer cycles, you may depend on the git repository instead of the pub.dev, allowing you to test it without publishing a specific version.

**Comment by devbathani** [comment]
Thank you for the suggestions
Currently I am using js interop with our internal js file and I was facing
issue will using the git repo, but I'll give it a try

**Comment by isoos** [comment]
@devbathani: I'm sorry, but I really don't see how/where you need to use the published version if you are using js interop. Please describe the use-case in more details.

**Comment by devbathani** [comment]
Thanks a lot for supporting I was able to solve the issue 
I'll close this issue soon 
Thank you 😊
