### ISSUE TITLE
Unable to flip pages

### ISSUE THREAD

**Issue by 17676160564** [dart-lang/pub-dev#7704]
URL: https://pub-web.flutter-io.cn/packages?q=flutter&page=4

<Describe your issue or suggestion here>

https://github.com/dart-lang/pub-dev/assets/90808925/c4f7c40b-9dd2-4c74-bd8f-e85f58d4ac76

**Comment by sigurdm** [comment]
Looks like an issue with the Chinese public mirror.

@chenglu do you have any insight?
