### ISSUE TITLE
Pass `SupportAgent` into all admin actions

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#7725]
We should also ensure that SupportAgent isn't affected by rate-limits

**Comment by isoos** [comment]
I've investigated the code in admin actions, and it seems that the most difficult part would be to rewrite some of the consent models and audit records related to invites and their handling. They require an active `User` marking from where the invite originates from (storing the `userId` on the `Consent` entity), and this id is used in multiple places.
