### ISSUE TITLE
[Dart 3 compatible] some package is marked as "dart 3" while the source code is clearly "dart 2"

### ISSUE THREAD

**Issue by iapicca** [dart-lang/pub-dev#7738]
some package is marked as "dart 3" while the source code is clearly "dart 2"
eg: 
https://pub.dev/packages/node_interop
https://github.com/pulyaevskiy/node-interop/blob/master/node_interop/pubspec.yaml

**Comment by isoos** [comment]
@iapicca:
"Many packages and apps that used null safety with Dart 2.12 or later are likely backwards compatible with Dart 3. This is possible for any package where the lower bound of the SDK constraint is 2.12.0 or higher."
https://dart.dev/resources/dart-3-migration#dart-3-backwards-compatibility
