### ISSUE TITLE
Inconsistency in character limit for screenshot description in pubspec.yaml

### ISSUE THREAD

**Issue by skw398** [dart-lang/pub-dev#7754]
There is an inconsistency between the character count check and the statement "Should be at least 10 characters".
With the current implementation, a description with exactly 10 characters is not accepted.

https://github.com/dart-lang/pub-dev/blob/d8f809f5585d1c6f6bd14fb01b5f3caf1907b24c/pkg/pub_package_reader/lib/pub_package_reader.dart#L733-L736

I believe either of the following solutions could be considered:

1. Change `textLength <= 10` to `textLength < 10`
1. Change `Should be at least 10 characters.` to something like `Should be more than 10 characters.` or `Should be over 10 characters.`.

And I think any changes to the documentation are unnecessary, because the following link does not mention the character limit for screenshot descriptions.
https://dart.dev/tools/pub/pubspec#screenshots

Thanks!

**Comment by isoos** [comment]
Thanks for reporting this! We should make it `textLength < 10`.

**Comment by skw398** [comment]
Also, it seems that NO changes to tests are necessary.

https://github.com/dart-lang/pub-dev/blob/master/pkg/pub_package_reader/test/package_archive_test.dart#L734-L745
