### ISSUE TITLE
Application Crash Read the phone number using smart_auth packages

### ISSUE THREAD

**Issue by NileshBusysoft** [dart-lang/pub-dev#7793]
Process: com.flabomate, PID: 3571
E/AndroidRuntime( 3571): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/credentials/HintRequest$Builder;
E/AndroidRuntime( 3571): 	at fman.ge.smart_auth.SmartAuthPlugin.requestHint(SmartAuthPlugin.kt:117)
E/AndroidRuntime( 3571): 	at fman.ge.smart_auth.SmartAuthPlugin.onMethodCall(SmartAuthPlugin.kt:77)
E/AndroidRuntime( 3571): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime( 3571): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime( 3571): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime( 3571): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 3571): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime( 3571): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3571): 	at android.os.Looper.loopOnce(Looper.java:230)
E/AndroidRuntime( 3571): 	at android.os.Looper.loop(Looper.java:319)
E/AndroidRuntime( 3571): 	at android.app.ActivityThread.main(ActivityThread.java:8893)
E/AndroidRuntime( 3571): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3571): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
E/AndroidRuntime( 3571): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
E/AndroidRuntime( 3571): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.credentials.HintRequest$Builder" on path: DexPathList[[zip file "/data/app/~~jdpuuHA14rxepyYOu4oQ-g==/com.flabomate-B86YK2MI0JdDuJE7ndruTQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~jdpuuHA14rxepyYOu4oQ-g==/com.flabomate-B86YK2MI0JdDuJE7ndruTQ==/lib/arm, /data/app/~~jdpuuHA14rxepyYOu4oQ-g==/com.flabomate-B86YK2MI0JdDuJE7ndruTQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system_ext/lib]]
E/AndroidRuntime( 3571): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime( 3571): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 3571): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 3571): 	... 14 more
I/Process ( 3571): Sending signal. PID: 3571 SIG: 9
Lost connection to device. it is not add dependencies razorpay_flutter it is correct smart_auth package using read phone number but add razorpay_flutter dependencies app crash some errors

**Comment by isoos** [comment]
@NileshBusysoft: this repository is for the `pub.dev` site and not for individual packages. Please contact the package authors through their contact email or their repository's issue tracker.
