### ISSUE TITLE
Support examples for Dart console packages

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#7800]
Example apps for Dart console packages are likely to use the template from `dart create -t console`. This creates a project where the main file is `. This doesn't match any of the current patterns:
https://dart.dev/tools/pub/package-layout#examples

I suggest we add these patterns as supported example entrypoints:

### Current:
```
example[/lib]/main.dart
example[/lib]/package_name.dart
example[/lib]/package_name_example.dart
**example[/lib]/example.dart
```

### Updated:
```
example[/lib|/bin]/main.dart
example[/lib|/bin]/package_name.dart
example[/lib|/bin]/package_name_example.dart
**example[/lib|/bin]/example.dart
```

**Comment by isoos** [comment]
@mit-mit: when multiple files are present, what is the selection preference, e.g. `example/bin/main.dart` vs. `example/<package_name>.dart`?

**Comment by isoos** [comment]
https://github.com/dart-lang/pana/blob/master/lib/src/maintenance.dart#L8-L21

We are using `main` file first, and within that first `lib/main.dart` then `/main.dart`. The update and the order of optional libraries suggest the new priority would be `lib/<file>`, `bin/<file>` and `/<file>`.

**Comment by isoos** [comment]
This has been implemented in pana and deployed.

**Comment by mit-mit** [comment]
I'm curious, shouldn't this cause the example here to get shown? 
https://pub.dev/packages/platform/example

**Comment by isoos** [comment]
Oh, true, this only applies to newly uploaded versions. We would need to run a backfill to re-extract the example file content for already uploaded versions. @mit-mit Is it urgent, or applied at new versions would be fine here?

**Comment by mit-mit** [comment]
No problem; we'll have new versions soon. I was just checking.
