### ISSUE TITLE
Pub.dev does not recognize 'enable-experiment: macros' in analysis_options.yaml

### ISSUE THREAD

**Issue by alexeyinkin** [dart-lang/pub-dev#7810]
I've published a package with a macro: https://pub.dev/packages/args_macro
When analyzing the package, pub.dev says it needs to enable the `macros` experiment:

<img width="638" alt="image" src="https://github.com/dart-lang/pub-dev/assets/44893228/959eaaee-20b8-4b1e-aaf8-c2601d5feaa7">

However, it's enabled in [analysis_options](https://github.com/alexeyinkin/dart-args-macro/blob/4c491d67a5cd342f9ba16154b7c74f8e19e934ad/analysis_options.yaml):

```yaml
include: package:total_lints/package.yaml

analyzer:
  enable-experiment:
    - macros
```

Locally, `dart analyze` recognizes it.

Searching the [macros topic](https://pub.dev/packages?q=topic%3Amacros), I can see others experimenting with macros too and having the same issue:
- https://pub.dev/packages/data_class by @felangel 
- https://pub.dev/packages/shelf_router_macro

For some reason, the [json](https://pub.dev/packages/json/versions/0.20.2) package is not affected when analyzing it but is affected when checking the formatting:

<img width="801" alt="image" src="https://github.com/dart-lang/pub-dev/assets/44893228/ac8e0a45-5c72-459a-a543-aa70339d99ae">

Is there anything special that the json package does that other examples don't? If so, it needs to be documented.

**Comment by isoos** [comment]
Thanks for reporting this! `pana` analysis overrides the analysis-options, but we should enable the pass-through of this experiment.

**Comment by isoos** [comment]
I think the pana change and the new 3.5 SDK release makes this issue now obsolete. Please reopen if something is still missing.
