### ISSUE TITLE
Doc generation failed https://pub.dev/packages/googleapis/versions/13.2.0/score/log.txt

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#7817]
URL: https://pub.dev/packages/googleapis/

See https://github.com/google/googleapis.dart/issues/630

**Comment by jonasfj** [comment]
Have we added new docs?

Is the package larger. Could also be a fluke, this package is really challenging the limits :)

We might have to review them, or count how many packages are affected and make an allowlist for longer timeouts..

**Comment by kevmoo** [comment]
It's got a bit bigger...new APIs. Nothing huge AFAICT

**Comment by jonasfj** [comment]
Current timeout is 55min!

But it should be starting from the latest version, we should review if ordering changed.

https://github.com/dart-lang/pub-dev/blob/master/pkg/pub_worker/lib/src/analyze.dart#L27

**Comment by isoos** [comment]
Comparing the log.txt files:

```
## Running analysis for "googleapis" version "13.1.0"
STARTED: 2024-06-17T20:04:45.385673Z
[...]
### Execution of pana exited 0
STOPPED: 2024-06-17T20:31:53.645140Z
```

```
## Running analysis for "googleapis" version "12.0.0"
STARTED: 2024-06-17T20:34:47.624734Z
[...]
### Execution of pana exited 0
STOPPED: 2024-06-17T21:02:27.623748Z
```

```
## Skipping analysis for "googleapis" version "13.2.0"
date-time: 2024-06-17T21:05:01.567911Z
```

It looks like the order was (and still is) off.

**Comment by isoos** [comment]
The fix has been deployed, now the latest stable always gets the priority on task scheduling.
