### ISSUE TITLE
Email -- SpamAssassin rule: BASE64_LENGTH_79_INF violated

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#7833]
`BASE64_LENGTH_79_INF`: base64 encoded email part uses line length greater than 79 characters

--------------

It's unclear if this is something `package:mailer` does, if so we should fix it.

![image](https://github.com/dart-lang/pub-dev/assets/149732/0239dc11-b656-450e-9718-3309f0cf4c82)

---------------

This was produced using `mail-tester.com`, I just invited a test email to participate in a publisher (obviously, using an unimportant publisher).

**Comment by isoos** [comment]
Note: opened issue in `package:mailer`.

**Comment by close2** [comment]
mailer version 6.2.0 restricts line lengths to 76 characters.

**Comment by isoos** [comment]
@close2: thanks for the quick change!

**Comment by jonasfj** [comment]
![image](https://github.com/user-attachments/assets/23b71265-8e64-4fe0-b2e1-bd6de1817a31)

Credits https://www.mail-tester.com
