### ISSUE TITLE
`platforms` entries should override `flutter:plugin:`

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/pub-dev#7884]
Per https://dart.dev/tools/pub/pubspec#platforms, the `platforms:` entry is not used when the package is a Flutter plugin. If the author has explicitly said what platforms they support, that should alway trump auto-detection, even detection based on `flutter:plugin:`

See https://github.com/flutter/flutter/issues/152037 for a case where that was problematic, and require dummy entries in a package that was partially implemented like a plugin, and partially like a non-plugin package, depending on the platform. There are alternate structures that wouldn't have had that problem, and there are some workarounds, but the cleanest solution would be to just list `platforms:` directly.

(Note that I didn't explicitly test the current behavior, I just trusted the docs. If it already works this way, then the docs are incorrect.)

**Comment by sigurdm** [comment]
If I read the code right the `platforms` top-level entry takes precedence already.

https://github.com/dart-lang/pana/blob/6811de88ab4b7fd6e0464b5a75297da7800fd1c4/lib/src/tag/_violations.dart#L118-L156

I guess we just need to clarify the documentation.
