### ISSUE TITLE
<Summarize your issues here>

### ISSUE THREAD

**Issue by NagendraThakur** [dart-lang/pub-dev#7895]
URL: https://pub.dev/packages/nepali_date_picker

The date is off by one day.  From couple of day. The converting of English to Nepali is also off with one day.  in desktop build only. It is working fine in android

**Comment by sigurdm** [comment]
This is the issue tracker for the pub.dev site itself, not for individual packages.

Try filing the issue in https://github.com/sarbagyastha/nepali_date_picker/issues
