### ISSUE TITLE
`dart pub publish`  failed with `Internal server error` for package with hooks

### ISSUE THREAD

**Issue by rainyl** [dart-lang/pub-dev#7896]
`hook` directory is used for `native-assets` https://github.com/dart-lang/sdk/issues/54334

```bash
git clone https://github.com/rainyl/bug-report-pubdev
cd bug-report-pubdev
dart pub publish -v
```

<details>

<summary>Detailed logs </summary>

WARN: Package validation found the following potential issues:
WARN: * The name of "lib\aaa.dart", "aaa", should match the name of the package, "test_bug_report_pub_dev".
    |   This helps users know what library to import.
WARN: * Please add a `CHANGELOG.md` to your package. See https://dart.dev/tools/pub/publishing#important-files.
FINE: Validating package finished (1.141s).
MSG :
    | Publishing is forever; packages cannot be unpublished.
    | Policy details are available at https://pub.dev/policy

Package has 2 warnings.. Do you want to publish test_bug_report_pub_dev 0.0.1-dev.0 to https://pub.dev (y/N)? y
FINE: Loading OAuth2 credentials.
FINE: Saving OAuth2 credentials.
IO  : Writing 1432 characters to text file C:\Users\rainy\AppData\Roaming\dart\pub-credentials.json.
MSG : Uploading...
IO  : HTTP GET https://pub.dev/api/packages/versions/new
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: publish
    | X-Pub-Session-ID: 6A36013E-7821-41A4-B973-42A6B4E7F993
    | authorization: <censored>
    | user-agent: Dart pub 3.4.3
IO  : HTTP response 200 OK for GET https://pub.dev/api/packages/versions/new
    | took 0:00:00.367209
    | cache-control: no-store, no-cache, must-revalidate
    | transfer-encoding: chunked
    | date: Wed, 31 Jul 2024 12:49:09 GMT
    | x-appengine-flex-applatency: 0.127
    | vary: Accept-Encoding
    | content-encoding: gzip
    | strict-transport-security: max-age=31536000; preload
    | content-type: application/json; charset="utf-8"
    | x-xss-protection: 1; mode=block
    | x-powered-by: Dart with package:shelf
    | alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
    | x-frame-options: SAMEORIGIN
    | via: 1.1 google
    | x-content-type-options: nosniff
    | expires: Wed, 31 Jul 2024 12:44:09 GMT
IO  : HTTP POST https://storage.googleapis.com
    | authorization: <censored>
    | content-type: multipart/form-data; boundary=dart-http-boundary-FsK1t3FVO2DXYeToANdXD+J-XBfHibzMeP0TpPNwu7x-584vlM4
    | user-agent: Dart pub 3.4.3
IO  : HTTP response 303 See Other for POST https://storage.googleapis.com
    | took 0:00:00.681548
    | alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
    | location: https://pub.dev/api/packages/versions/newUploadFinish?upload_id=6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&bucket=dartlang-pub-incoming-packages&key=tmp/6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&etag=3538f3cd874d57b62cb150e556f9f62a
    | date: Wed, 31 Jul 2024 12:49:10 GMT
    | vary: Origin
    | content-length: 0
    | x-guploader-uploadid: AHxI1nOxyZ8zCXTLGbrwR-Ozku0XQUzmrpAuSvoHjIY_YgWyM8aGPTF9Rfwib7M69KaYkW9QfAA-00fVkw
    | content-type: text/html; charset=UTF-8
    | server: UploadServer
IO  : HTTP GET https://pub.dev/api/packages/versions/newUploadFinish?upload_id=6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&bucket=dartlang-pub-incoming-packages&key=tmp/6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&etag=3538f3cd874d57b62cb150e556f9f62a
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: publish
    | X-Pub-Session-ID: 6A36013E-7821-41A4-B973-42A6B4E7F993
    | authorization: <censored>
    | user-agent: Dart pub 3.4.3
IO  : HTTP response 500 Internal Server Error for GET https://pub.dev/api/packages/versions/newUploadFinish?upload_id=6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&bucket=dartlang-pub-incoming-packages&key=tmp/6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&etag=3538f3cd874d57b62cb150e556f9f62a
    | took 0:00:00.426506
    | cache-control: no-store, no-cache, must-revalidate
    | date: Wed, 31 Jul 2024 12:49:11 GMT
    | x-appengine-flex-applatency: 0.187
    | strict-transport-security: max-age=31536000; preload
    | content-type: application/json; charset="utf-8"
    | x-xss-protection: 1; mode=block
    | x-powered-by: Dart with package:shelf
    | alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
    | content-length: 271
    | x-frame-options: SAMEORIGIN
    | via: 1.1 google
    | x-content-type-options: nosniff
    | expires: Wed, 31 Jul 2024 12:44:11 GMT
IO  : HTTP GET https://pub.dev/api/packages/versions/newUploadFinish?upload_id=6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&bucket=dartlang-pub-incoming-packages&key=tmp/6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&etag=3538f3cd874d57b62cb150e556f9f62a
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: publish
    | X-Pub-Session-ID: 6A36013E-7821-41A4-B973-42A6B4E7F993
    | authorization: <censored>
    | user-agent: Dart pub 3.4.3
IO  : HTTP response 500 Internal Server Error for GET https://pub.dev/api/packages/versions/newUploadFinish?upload_id=6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&bucket=dartlang-pub-incoming-packages&key=tmp/6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&etag=3538f3cd874d57b62cb150e556f9f62a
    | took 0:00:00.489523
    | cache-control: no-store, no-cache, must-revalidate
    | date: Wed, 31 Jul 2024 12:49:12 GMT
    | x-appengine-flex-applatency: 0.246
    | strict-transport-security: max-age=31536000; preload
    | content-type: application/json; charset="utf-8"
    | x-xss-protection: 1; mode=block
    | x-powered-by: Dart with package:shelf
    | alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
    | content-length: 271
    | x-frame-options: SAMEORIGIN
    | via: 1.1 google
    | x-content-type-options: nosniff
    | expires: Wed, 31 Jul 2024 12:44:12 GMT
IO  : HTTP GET https://pub.dev/api/packages/versions/newUploadFinish?upload_id=6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&bucket=dartlang-pub-incoming-packages&key=tmp/6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&etag=3538f3cd874d57b62cb150e556f9f62a
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: publish
    | X-Pub-Session-ID: 6A36013E-7821-41A4-B973-42A6B4E7F993
    | authorization: <censored>
    | user-agent: Dart pub 3.4.3
IO  : HTTP response 500 Internal Server Error for GET https://pub.dev/api/packages/versions/newUploadFinish?upload_id=6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&bucket=dartlang-pub-incoming-packages&key=tmp/6ebcb0a5-b069-45ee-8d63-f7ff374ecd58&etag=3538f3cd874d57b62cb150e556f9f62a
    | took 0:00:00.499375
    | cache-control: no-store, no-cache, must-revalidate
    | date: Wed, 31 Jul 2024 12:49:13 GMT
    | x-appengine-flex-applatency: 0.255
    | strict-transport-security: max-age=31536000; preload
    | content-type: application/json; charset="utf-8"
    | x-xss-protection: 1; mode=block
    | x-powered-by: Dart with package:shelf
    | alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
    | content-length: 271
    | x-frame-options: SAMEORIGIN
    | via: 1.1 google
    | x-content-type-options: nosniff
    | expires: Wed, 31 Jul 2024 12:44:13 GMT

</details>

![image](https://github.com/user-attachments/assets/c1f88a34-ddb5-4136-a33b-a3b8332ef8eb)

## additional infos

```
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (8 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

**Comment by rainyl** [comment]
Allright, I just find 
- https://github.com/dart-lang/pub-dev/pull/7847
- https://github.com/dart-lang/pub-dev/pull/7541

but custom toolchain is included in `hook`, https://github.com/rainyl/bug-report-pubdev/tree/main/hook

So custom toolchains are not allowed anymore? If so, is it works if I put my toolchains into another package?

**Comment by sigurdm** [comment]
> And, if this is not allowed anymore, please at least inform users with more friendly messages instead of a single Internal Server Error.

Yeah - sorry about the confusing error. We had a null-pointer error here: https://github.com/dart-lang/pub-dev/pull/7898.

> but custom toolchain is included in hook, https://github.com/rainyl/bug-report-pubdev/tree/main/hook

@dcharkes should we allow this hook?

**Comment by sigurdm** [comment]
@jonasfj argued that `native_toolchain_conan.dart` is not a hook, but a library imported by the `build.dart` hook.

Thus it should probably be moved to `lib/src`.

**Comment by sigurdm** [comment]
Closing this issue for now - leaving the one about the null-pointer error for fixing the message.

**Comment by sigurdm** [comment]
> can't more friendly messages be given after analyzing the package? just like the issues and warnings before publish confirmation.

I don't think we'll turn this into a client side check.

I think we'll keep the possibility of adding more hooks going forward, and there is no way to change existing clients.
