### ISSUE TITLE
Light mode text is not fading out

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#7902]
The text gets darker towards the bottom. Not exactly sure what is going on. Might be on purpose?

![image](https://github.com/user-attachments/assets/add5351a-21a2-4e17-aad2-7b0df9c795a0)

Here is without dark mode for comparison
<img width="1159" alt="image" src="https://github.com/user-attachments/assets/0b4010aa-7695-46cf-b0ac-383f2383d44a">

**Comment by isoos** [comment]
The bug is that the light mode is not fading out, updated the title.

**Comment by yashathwani** [comment]
Would like to work on this issue!!
