### ISSUE TITLE
An exact match with the package name should be shown first

### ISSUE THREAD

**Issue by Meai** [dart-lang/pub-dev#7938]
Search for the `stream_channel` package on pub.dev: https://pub.dev/packages?q=stream_channel

Package named `stream_channel` is only the 4th result, it should be the first result:

![image](https://github.com/user-attachments/assets/c38ec1b9-0848-45b7-8cb3-d4aa789be05f)

**Comment by isoos** [comment]
While #7872 is related, I don't think it is in conflict with this. Like, #7876 improved on the `bluetooth` query, but in the `stream_channel` case we have low-score hits as well. Maybe instead of the average, we just compare the top value against the SDK hits?

**Comment by isoos** [comment]
Note: with the latest change in #7943 the `services` SDK library is out, so there is a small win there.
