### ISSUE TITLE
The "package-published" operation is blocked

### ISSUE THREAD

**Issue by akmaljon1016** [dart-lang/pub-dev#7953]
I published my package with small bug fixes 12 times in a day and then when i dart publish it shows:
`The "package-published" operation is blocked, as its rate limit has been reached (12 in the last day). Please try again later. Please report the issue on https://github.com/dart-lang/pub-dev/issues/new if you think the limit should be increased to accommodate your use case.`
when i try later but this error shows again

**Comment by isoos** [comment]
@akmaljon1016: what's the package? you will need to wait an entire 24 hours from the first publishing, as the limit is measured in a moving window.

**Comment by akmaljon1016** [comment]
> @akmaljon1016: what's the package? you will need to wait an entire 24 hours from the first publishing, as the limit is measured in a moving window.

Thank you for your answer.Package link:https://pub.dev/packages?q=fancy_indicator

**Comment by isoos** [comment]
Looking at the package changelog, I think the rate limiting is working as intended here: you shouldn't need to feel pressured to release a new version every time you change something small, especially for such a new package and so often. Instead, allow yourself more time to focus more on the code and to develop reasonable updates to the code.
