### ISSUE TITLE
Reduce timestamp size in report email confirmations

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#7984]
> New report received on 2024-08-27T12:27:25.366456Z: 20240827-b31b525a92

Could just be:

> New report received on 2024-08-27: 20240827-b31b525a92

**Comment by isoos** [comment]
This has been implemented https://github.com/dart-lang/pub-dev/pull/7991/files#diff-cbe4768b87ac43f910202bdeeaafabeee12b8c83c5496b861f2502fed26534afR221
