### ISSUE TITLE
pub.dev documentations search is broken

### ISSUE THREAD

**Issue by mateusfccp** [dart-lang/pub-dev#8018]
When accessing any documentation of a pub.dev package ([example](https://pub.dev/documentation/analyzer/latest/)), the search functionality won't work.

The search box is indefinitely in the "Loading search..." state.

<img width="447" alt="image" src="https://github.com/user-attachments/assets/deb25cd1-0ecb-416a-9e39-9de2909c73b1">

Trying to type something in it will do nothing, and if I type anything and press enter it just refreshes the page.

The following can be seen in the console, potentially related:

<img width="607" alt="image" src="https://github.com/user-attachments/assets/2a1ba5dc-842b-4ad1-9c68-c7844962832e">

I've tried both in Safari and Chrome.

@julemand101 confirmed that it also happens to them in Firefox.

**Comment by isoos** [comment]
Thanks for reporting this!

It is a `dartdoc` bug that has been fixed in the recently released `8.1.0` version, and `pub.dev` will soon release a new site version with that (hopefully tomorrow /Thursday/). Thank you for your patience.

**Comment by isoos** [comment]
Note: we have already deployed the fix to the staging site and it is confirmed that the new dartdoc version has a working search.

**Comment by mateusfccp** [comment]
Should I close the issue or do you want to wait it to reach production?

**Comment by isoos** [comment]
Let's keep it open so others will see too.

**Comment by isoos** [comment]
The issue was fixed with this release. Package analysis and new dartdoc generation is ongoing.
