### ISSUE TITLE
Checkmarks missing from markdown rendering

### ISSUE THREAD

**Issue by Matix-Media** [dart-lang/pub-dev#8039]
The current markdown rendering does not include checkmarks like GitHub does, just like this:

- [ ] unfinished
- [x] finished

This causes packages using this syntax to display a simple bullet point list, which can lead to confusion, like in this example:  
![image](https://github.com/user-attachments/assets/550306bd-6e90-4c08-8cfe-d8da37e2502e)
_How it's displayed on GitHub_

![image](https://github.com/user-attachments/assets/2910cdc1-da92-4b2f-9537-5928d4b79b7e)
_How it's displayed on pub.dev_

In this case, a user might assume that a package has a certain feature implemented.

**Edit:**
source package: https://pub.dev/packages/osrm
GitHub link to markdown file: https://github.com/physia/kflutter/blob/main/osrm/README.md

**Comment by isoos** [comment]
@Matix-Media: can you link to the markdown file / package that has this?

**Comment by Matix-Media** [comment]
> @Matix-Media: can you link to the markdown file / package that has this?

source package: https://pub.dev/packages/osrm
GitHub link to markdown file: https://github.com/physia/kflutter/blob/main/osrm/README.md

**Comment by isoos** [comment]
Thanks for reporting, this is a regression in our HTML rendering.
