### ISSUE TITLE
Increase rate limit for “package-created” operation

### ISSUE THREAD

**Issue by ProFive** [dart-lang/pub-dev#8059]
I am currently working on multiple Flutter/Dart packages and need to publish more than 12 packages in a day. My use case requires me to publish 4-5 additional packages beyond the current rate limit.

**Request:**
Could you please increase the rate limit for package creation to accommodate my use case? A higher limit would be beneficial as I'm actively working on several packages in parallel.

**Use Case:**
I am working on a project that involves multiple interconnected packages, and the current rate limit of 12 packages per day is too restrictive. An increase to allow for 4-5 more package creations per day would help me continue development without interruptions.

**Steps to Reproduce:**
1. Create 12 packages within a 24-hour period.
2. Attempt to create additional packages.
3. Receive the error mentioned above.

Thank you for considering this request. Let me know if more details are needed.

**Comment by isoos** [comment]
`package-created` is applied to when publishing the *first* version of a newly created package (note: subsequent version publishing is on a different rate limit). The main reason behind that is to prevent spamming the service and our users, but we also don't want to encourage fragmentations like putting every small method in its own package.

Could you please elaborate more on your packages, and why you need sustained publishing of new packages?
