### ISSUE TITLE
import 'package:toggle_switch/toggle_switch.dart';

### ISSUE THREAD

**Issue by toto-1001** [dart-lang/pub-dev#8099]
* Explain the issue,
 * Using bullet points!
 * Link to screenshot.

```dart
// Write example code here
```
import 'package:toggle_switch/toggle_switch.dart';

**Comment by isoos** [comment]
@toto-1001: this issue tracker is for the `pub.dev` site and not for individual packages. Please file your issue at the package's issue tracker.
