### ISSUE TITLE
Reserve "formatter" as a package name

### ISSUE THREAD

**Issue by munificent** [dart-lang/pub-dev#8128]
At long last, we're [adding support to `dart format` for configuring page width at the project level](https://github.com/dart-lang/sdk/issues/56863). The configuration goes in `analysis_options.yaml` under a `formatter` key:

```yaml
formatter:
  page_width: 123
```

This is consistent with other top level keys in that file: `analyzer` and `linter`. In those latter cases, those keys are also the name of the package. For complicated historical reasons, the formatter's package name is `dart_style` not `formatter`. It would probably be confusing if there was a package named `formatter` that had nothing to do with `dart format` or the `formatter` key in `analysis_options.yaml`.

Is it worth marking that name as reserved? As far as I can tell, there is no package on pub with that name today.

(Long-term, it might be nice to migrate `dart_style` to that name but that would be a lot of work for marginal benefit.)

**Comment by sigurdm** [comment]
The formatter package has now been reserved!

**Comment by munificent** [comment]
Thank you!
