### ISSUE TITLE
Feature Request: Add Package Version View for Old Versions' README on pub.dev

### ISSUE THREAD

**Issue by ashutosh2014** [dart-lang/pub-dev#8131]
Hello team,

I would like to request a feature that allows users to view the README files and details for older versions of packages on pub.dev, similar to what is currently available on [npmjs.com](https://www.npmjs.com/). This feature would greatly enhance the ability to:

- **Track updates:** Users can better understand changes between different versions by reading the README and comparing documentation.
- **Support legacy code:** Sometimes projects are locked to older package versions due to dependency constraints, and it’s crucial to refer to the correct documentation for those versions.
- **Improved adoption:** By making older version documentation easily accessible, developers can better assess when and how to upgrade.

**Proposed Solution:**

- Provide a permalink to each version’s page so that it can be shared easily.

**Example:**

For reference, npmjs has a very useful versioning feature that allows users to select previous versions of a package and view their corresponding README and other metadata. A similar implementation on pub.dev would be incredibly helpful.

**Comment by isoos** [comment]
@ashutosh2014: I'm not sure I understand the scope of this correctly, as we do have version listing pages and permalinks to old versions (and their readme, changelog, ...):
- https://pub.dev/packages/retry/versions/3.0.0
- https://pub.dev/packages/retry/versions

What is on top of this that you are looking for?
