### ISSUE TITLE
Search results by relevance are wrong 

### ISSUE THREAD

**Issue by bigbott** [dart-lang/pub-dev#8139]
Examples: 
1. http (dio not found), 
2. animation(animate_do and flutter_animate not found)
3. navigation (auto_route and go_router not found)

The algorithm that uses the exact package name match is wrong by definition. It is a bug by design.   

Maybe something like this can be used instead: 

Keyword_relevance = number of keywords in package name x 3
                                + number of keywords in short description x 2
                                + number of keywords in readme   

Another issue is the search by most likes. It shows completely irrelevant results. 
For example, it shows `get` for _animation_ keyword as the first result. 

There should be a minimal Keyword_relevance (for example 10) to show package in results for the  particular keyword.

**Comment by isoos** [comment]
@bigbott: Thanks for reporting these! We are in the process of re-thinking how search should work (and/or displayed), and every feedback is important.

The provided examples are really great demonstration of a particular use case where the package name does not contain the key word which many users may search for. (This indicates that we may need to decrease the package name weight, but that may be in conflict with other use cases where we do need to expose them as the users are expecting them.)

> The algorithm that uses the exact package name match is wrong by definition. It is a bug by design.

To be precise, the newly launched feature which highlights exact package name matches is unrelated to the ranking:
![image](https://github.com/user-attachments/assets/9faad353-1c0f-4777-be0e-443851a05716)

Note: ranking is complex and hard to fine-tune, and it is always a push-and-pull between weights, in this case between package name, other package metadata, topics (keywords), and popularity. A quick overview is here: https://pub.dev/help/search#ranking

Please phrase issues like you did in the example queries and expected result differences, we will try to get better overall balance, and not just a specific use case.

> Another issue is the search by most likes. It shows completely irrelevant results.
> For example, it shows get for animation keyword as the first result.

The `get` package has the "animation" string in its readme, so I think it is fair to display it in the result list, along with (at the moment) 3948 other packages. When using the default sort order, which combines keyword relevancy, package score and overall popularity metrics, I don't see `package:get` in the top 500 hits, which seems to be fair. However, if you switch to sort by likes, among this 3948 packages, `get` has the most likes. I think these results are fair.

> There should be a minimal Keyword_relevance (for example 10) to show package in results for the particular keyword.

By keyword search, are you referring to topics?
https://pub.dev/topics

- We seem to have 50+ packages that have set the `animation` topic in their pubspec, and among them, the sort-by likes seems to rather relevant: https://pub.dev/packages?q=topic%3Aanimation&sort=like
- Also for the `topic:http` https://pub.dev/packages?q=topic%3Ahttp, we list `dio` at the first position right now.
- For the `topic:navigation` the two mentioned packages are in the top 3 listed: https://pub.dev/packages?q=topic%3Anavigation

This indicates that we should expose and use the topic data even more.

**Comment by bigbott** [comment]
Thank you for a detailed reply. 

I understand the complexity of the search in general. 
But this particular issue has a very simple cause: search by relevance is mistakenly replaced by exact package name match. Those two searches should be separated. 

`package name` should be added to SORT BY dropdown. 
this option should perform the same way as the current `search relevance`
the `search relevance` option should summarize the appearances of keywords in the package name, short description, and readme. 

This sum of keyword appearances is _search relevance_ or _keyword relevance_. 

It can be used to filter out irrelevant packages when sorted by: most likes, popularity, and other options except `package name`. 

Only one appearance of a keyword in Readme should not be enough to display the package 
in the search results unless it is the search by package name.

The search sorted by `package name` can remain the default since users are used to this behavior. 

But it should be renamed since the current name `search relevance` is irrelevant to what it does. 
-----------------------------
The `topic:something` search is a completely another story and IMHO works well. The problem with it is that package authors do not bother to add hashtags to their descriptions. For example, Riverpod has no hashtags, despite the author (huge respect!) should be aware of how pub.dev works.  
This can be fixed by making hashtags (at least one or two) required field when the package is submitted to pub.dev

**Comment by isoos** [comment]
> But this particular issue has a very simple cause: search by relevance is mistakenly replaced by exact package name match. Those two searches should be separated.

You can find the field-weights of the text indexes here:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/search/mem_index.dart#L258-L265

As you can see, we never use only the package name match, at minimum we use the combination of name, description, readme, and if there is enough budget the API surface. We do weight the description and readme a bit less than the name, but it is never just the name, nor just the text score. By default we always adjust the text score with analysis and popularity, the score merge operation is here (and their calculation):
https://github.com/dart-lang/pub-dev/blob/master/app/lib/search/mem_index.dart#L162-L163
https://github.com/dart-lang/pub-dev/blob/master/app/lib/search/mem_index.dart#L219-L226

It is true though, that if the name doesn't contain the specific keyword, it may have lower rank because of it, and we should compensate that for popular packages.

**Comment by bigbott** [comment]
There are two completely different use cases: 
1. The user searches for the package he is familiar with by name. For example: riverpod,dio, animate_do.
2. The user searches for packages by what they do i.e. keyword.  For example: state, HTTP, animation.  

**Mixing those two cases is a mistake.** 

Accepting mistakes is a mature thing and is the only way to fix them. 

I read your answer: We already do the smartest thing we can.  

Probably by given design you really do the smartest thing possible. 

But mixing search by name and search by keyword relevance (Score in your code) IS A BUG in your design.

**Comment by isoos** [comment]
My point is: we are doing a different thing than what you have claimed we were doing. That does not mean it is good, it just evolved to the current state along often contradicting requirements, and I was describing the current behavior.

As I have stated we are indeed in the process of redesigning it, and reporting issues like the search terms help this goal. However, speculating on specific parts and claiming the entire design is a bug because you think other use cases are not important does not help to keep discussions civil. Please be mindful on other use cases, as we want to support a broad range of users, including seemingly niche ones.

**Comment by bigbott** [comment]
Where do I said that other use cases (which use cases? ) are not important? 

We have very specific issue here: search by relevance does not work. 

And the reason it does not work because it mixed with search by package name. 

Issue has super simple solution: separate those two searches. Solution can be implemented in two working days,  since when they separated each of them is super easy to code.

**Comment by isoos** [comment]
Closing this as the recent search changes now treat the descriptions on the same level as the name matches, and we have now package name matching as a separate result line.

Note: for the `navigation` query, the reported packages have reduced scores during the analysis, that's the reason they are not ranked higher.
