### ISSUE TITLE
Rejected non-canonicalized version strings at publishing time

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#8216]
It's possible to publish a package with the version number: `4.00.0`.

This is semantically the same version as `4.0.0`, at-least we treat it that way.

Perhaps we should consider forbidding non-canonicalized version strings, at-least for newly published package versions.

We can't delete existing package versions, but we can stop the problem from growing.

It's not impossible that in the future we'll introduce a bug that accidentally causes non-canonicalized version string to behave differently.

Thoughts @sigurdm, @szakarias

**Comment by sigurdm** [comment]
Yeah - we should absolutely do this.

**Comment by sigurdm** [comment]
Perhaps we should **also** implement a pubspec.yaml lint that suggests canonicalizing the version number

**Comment by isoos** [comment]
I think we already reject non-canonicalized versions:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/package/backend.dart#L939-L942

Also a test for it:
https://github.com/dart-lang/pub-dev/blob/master/app/test/package/upload_test.dart#L1004-L1016
