### ISSUE TITLE
Consider downloads count matrix measurement with hosted mirror site

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/pub-dev#8302]
We are hosting `flutter-io.cn` which carries significant downloads every second.

It would be good if hosted mirrors could also report their download metrics somehow.

EDIT: I acknowledge that the team and Google are not responsible for any mirror site.

**Comment by isoos** [comment]
At this point we don't have any plans to aggregate such metrics.

**Comment by AlexV525** [comment]
Thanks for the reply. Is there any chance that we can collect the metric on our own using the implementation in the pub.dev?

**Comment by isoos** [comment]
> Thanks for the reply. Is there any chance that we can collect the metric on our own using the implementation in the pub.dev?

Not sure: what would you like to use here?

**Comment by isoos** [comment]
> Like how the pub.dev collects the download metrics so we can implement the same.

I have no idea about the legal details, this may be a good question to `support@pub.dev`.
