### ISSUE TITLE
Experimentals might be available for mirror sites

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/pub-dev#8303]
1. Head over to https://pub-web.flutter-io.cn/experimental
2. Click toggles to enable experiments.
3. Nothing happened with https://pub-web.flutter-io.cn/

What extra configuration do we need for the mirror site, or it's simply not supported yet?

**Comment by sigurdm** [comment]
We are not responsible for running the mirror site. @chenglu might know

Experiments are not officially supported (maybe the experimental page should explain that better). Don't expect them to be reflected on the mirror page.

**Comment by sigurdm** [comment]
Closing as we have no plans for supporting this.
