### ISSUE TITLE
Improve documentation for ci upload to github

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/pub-dev#8349]
A small text describing what each option does would be helpful here.

For the first item: "Enable publishing from push events" 
  - A subtitle should describe which events. I'm guessing it's implied that it is a push events when there is specific tag. Please be explicit and informative.
  
For the second item: "Enable publishing from workflow_dispatch events"
  - What does this do ? I would have guessed this would add an "on: workflow_dispatch"  to the github action yaml generated, but it does not do that.

For the third item: "Require GitHub Actions environment"
  - There is always an environment. What does this even mean ? 

I'm not trying to be dense here, it's genuinely confusing

![image](https://github.com/user-attachments/assets/53eb5fee-0409-4e97-910b-83e2818056ed)

**Comment by sigurdm** [comment]
Thanks for the feedback - I certainly agree we should explain better here.

Everything is documented at https://dart.dev/tools/pub/automated-publishing - maybe we should just link to that page from that admin section.
