### ISSUE TITLE
UI Alignment Issue in Stats Section on Pub.dev

### ISSUE THREAD

**Issue by ahmerrkhan** [dart-lang/pub-dev#8381]
There appears to be an alignment issue in the Stats section of the UI. The elements do not appear to be perfectly aligned, which affects the overall presentation and user experience.

**Steps to Reproduce:**

Go to the Stats section of the UI (Right Side of package page).
Observe the layout of the elements (e.g., Likes, pub points & popularity).
Notice that the alignment does not look consistent across the UI components.
Refer to those packages which have like in thousands, specifically in **K format** 

**Expected Behavior:** 
The UI elements should be evenly aligned, ensuring a consistent and polished design in the Stats section even in **K format**

**Actual Behavior:** 
The alignment is off, and certain elements may appear misaligned, which negatively impacts the overall UI.

**Additional Information:**

The issue appears to be affecting both desktop view.
The alignment issue seems to be in both the text and visual components.

**Screenshots:** 

![Screenshot 2024-12-10 at 10 30 15 AM](https://github.com/user-attachments/assets/3148b468-7bf6-4d43-a962-8d1a4ffa32c8)
![Screenshot 2024-12-10 at 10 30 37 AM](https://github.com/user-attachments/assets/126e58bb-6302-4956-99e9-ee2eaa37e1f2)

**Comment by sigurdm** [comment]
cc @szakarias @isoos

**Comment by isoos** [comment]
I think this has been fixed.
