### ISSUE TITLE
Missing Dart doc pages

### ISSUE THREAD

**Issue by Pante** [dart-lang/pub-dev#8398]
We just noticed that most of the previously working links in the generated dart docs for our project, https://pub.dev/documentation/forui/latest/ now return a 404 error. The links in a locally generated copy of the docs on `Dart SDK version: 3.5.4 (stable) (Wed Oct 16 16:18:51 2024 +0000) on "macos_arm64"` seem to work fine.

**Comment by isoos** [comment]
@Pante: the linked page works for me, do you still get 404?

We are rolling out a new site release, and it may be related to that, although, in general we should fall back without such glitches to the previous release's documentation pages.

**Comment by Pante** [comment]
I think the issue is with the links on the main page, such as https://pub.dev/documentation/forui/latest/forui.assets. I just tested those links again in a private tab and they’re still returning 404 errors.

**Comment by isoos** [comment]
Hm, it seems to be partially generated, not sure what went wrong (we have a few moving parts right now). I will investigate this soon.

**Comment by isoos** [comment]
I have found an unrelated dartdoc glitch that doesn't affect this (https://github.com/dart-lang/dartdoc/issues/3943).

The core issue here seems to be that dartdoc switched to generate dots as part of the library directories and our path parsing thought that these are just regular files. E.g. https://pub.dev/documentation/forui/latest/forui.widgets.alert/index.html works, while https://pub.dev/documentation/forui/latest/forui.widgets.alert does not (neither with the `/` suffix).

I'm submitting a quick fix for that and we shall rewrite the current detection mechanism to have proper file checks in our blob index.

**Comment by Pante** [comment]
Thanks for the quick turn around!

**Comment by isoos** [comment]
Note: the fix is not immediately released, it may take some time before we have the next site release.

**Comment by Pante** [comment]
What timeframe are we looking at? Like days, weeks, months?

**Comment by sigurdm** [comment]
Usually we have ~1 deployment per week (modulo things like vacations)

Today you are lucky, and you can expect this to come online within hours!

**Comment by isoos** [comment]
Note: this is now online.
