### ISSUE TITLE
Weekly downloads graph not visible on Safari

### ISSUE THREAD

**Issue by RepliedSage11** [dart-lang/pub-dev#8400]
The new Weekly Downloads graph is not visible on Safari.

**Safari (18.1.1)**
<img width="219" alt="Screenshot 2024-12-12 at 10 44 54" src="https://github.com/user-attachments/assets/884db43a-9504-4e31-b862-9db50b208c3e" />

**Chrome**
![telegram-cloud-photo-size-4-5969713008106128804-x](https://github.com/user-attachments/assets/003be36f-88eb-4293-8273-6a699ca12688)

**Comment by sigurdm** [comment]
Seems like using 100% for width and height also works:
<img width="657" alt="image" src="https://github.com/user-attachments/assets/e5a5c37e-e2ba-4bca-99d6-e976870e514e" />
