### ISSUE TITLE
task

### ISSUE THREAD

**Issue by Parth26198** [dart-lang/pub-dev#8405]
URL: https://pub.dev/packages/google_sign_in_android/example

<Describe your issue or suggestion here>

import 'package:flutter/material.dart';

/// Entrypoint of the application.
void main() {
  runApp(const MyApp());
}

/// [Widget] building the [MaterialApp].
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Dock(
            items: const [
              Icons.person,
              Icons.message,
              Icons.call,
              Icons.camera,
              Icons.photo,
            ],
            builder: (e) {
              return Container(
                constraints: const BoxConstraints(minWidth: 48),
                height: 48,
                margin: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(8),
                  color: Colors.primaries[e.hashCode % Colors.primaries.length],
                ),
                child: Center(child: Icon(e, color: Colors.white)),
              );
            },
          ),
        ),
      ),
    );
  }
}

/// Dock of the reorderable [items].
class Dock extends StatefulWidget {
  const Dock({
    super.key,
    this.items = const [],
    required this.builder,
  });

  /// Initial [IconData] items to put in this [Dock].
  final List<IconData> items;

  /// Builder building the provided [IconData] item.
  final Widget Function(IconData) builder;

  @override
  State<Dock> createState() => _DockState();
}

/// State of the [Dock] used to manipulate the [_items].
class _DockState extends State<Dock> {
  /// [IconData] items being manipulated.
  late final List<IconData> _items = widget.items.toList();

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(8),
        color: Colors.black12,
      ),
      padding: const EdgeInsets.all(4),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: List.generate(_items.length, (index) {
          return Draggable<IconData>(
            data: _items[index],
            feedback: Material(
              color: Colors.transparent, // Transparent background for the dragged item
              child: Container(
                width: 48,
                height: 48,
                margin: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: Colors.primaries[_items[index].hashCode % Colors.primaries.length],
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Center(child: Icon(_items[index], color: Colors.white)),
              ),
            ),
            childWhenDragging: const SizedBox.shrink(), // Hide the original widget when dragging
            child: widget.builder(_items[index]), // Regular widget display
          );
        }),
      ),
    );
  }
}

**Comment by sigurdm** [comment]
This is the issue tracker for the pub.dev site itself, not for individual packages.

Try the issue tracker for the package: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+google_sign_in%22
