### ISSUE TITLE
Update the project for the files and structure 5.8 generates to match the guide

### ISSUE THREAD

**Issue by toto-1001** [dart-lang/pub-dev#8438]
Update the project for the files and structure 5.8 generates to match the guide

_オリジナルは @0xTim が https://github.com/apple/swift-getting-started-cli/pull/1 にポスト_

**Comment by isoos** [comment]
@toto-1001: This repository is for the issues with pub.dev site. Use the package's repository/issue tracker to contact the authors for specific packages.
