### ISSUE TITLE
Provide independent authorization flow

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub-dev#946]
_From @vanesyan on January 22, 2018 16:28_

Hello there! Let's be realistic, today Dart is not popular and therefore widely used across developers. Among other problems, the one that persist is Dart high addiction of Google, such addiction we can see in different things. Specifically, current pub authorization flow. To simply publish library to pub, I must create Google Account to be able to log in with OAuth2 through it. In objectives, I think, pub should has independent authorization mechanism (like npm has), or more trustable by developers (i.e. GitHub, currently implemented by Rust package manager - Cargo).

_Copied from original issue: dart-lang/pub#1788_

**Comment by nex3** [comment]
Authorization is more of a server concern, so I'm moving this to the pub server repository.

For historical context, we started with Google account support mostly because it was easy to integrate with App Engine. I think it could make a lot of sense to add GitHub account support as well.

**Comment by jwinnie** [comment]
I think this issue is particularly important because Dart is part of Google, and people will always be suspicious of the intentions behind it. If Dart is to be accepted by the wider Open Source community, it needs to rid itself of Google influences, particularly Google lock-ins such as requiring a Google account.

**Comment by jonasfj** [comment]
We've recently agreed that the pub client should support other login methods.. but the pub.dev server will not get this support...

People wanting to host a custom pub server should follow the spec (work in progress), and write a pub server from scratch (this is easy, there aren't many HTTP end-points).

**Comment by jonasfj** [comment]
See: https://github.com/dart-lang/pub/issues/1381
